### ISSUE TITLE
Can't access the settings menu as admin

### ISSUE THREAD

**Issue by rocketskill** [nextcloud/server#10085]
Hello Nextcloud community, i've got an issue and i need your help to resolve it.
I already tried to restart my services and my server and nothing changes.

There is all of my server info : 

### Expected behaviour
When i click on the Settings tab, it should show the administration menu.

### Actual behaviour
When i click on the Settings tab with a user who is member of the admin group, an internal error server appear.
The users who are not member of the admin group have no problem to display the user limited settings menu. 

### Server configuration

- Operating system : **Debian 8.9**

- Web server : **Apache 2.4.10**

- Database : **MySQL Ver 14.14 Distrib 5.5.58**

- PHP version : **PHP 5.6.30**

- Nextcloud version : **13.0.4**

- Updated from an older Nextcloud/ownCloud or fresh install : **Nextcloud fresh install**

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here:

**No errors have been found.**

List of activated apps :
- Activity
- Auditing/Loging
- Deleted Files
- External Storage Support
- Federation
- File sharing
- Files Share Link Renamer
- First Run wizard
- Gallery
- Log Reader
- Monitoring
- Nextcloud Announcements
- Notifications
- Password Policy
- PDF Viewer
- Share by mail
- Text Editor
- Theming
- Update Notification
- Usage Survey
- Versions

All apps are up to date.

Nextcloud configuration :
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.e-va.cloud',
    1 => '185.73.207.21',
    2 => '192.168.200.50',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://nextcloud.e-va.cloud',
  'dbtype' => 'mysql',
  'version' => '13.0.4.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_from_address' => '***',
  'mail_domain' => 'e-va.cloud',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);
```

Are you using external storage, if yes which one: **No**

Are you using encryption: **No**

Are you using an external user-backend, if yes which one: **No**

### Client configuration
Browser: **Bug appear on Google Chrome Version 67.0.3396.99 (64bits) and Firefox 64.0 (64bits)**

Operating system: **Windows 10**

**Comment by MorrisJobke** [comment]
> When i click on the Settings tab with a user who is member of the admin group, an internal error server appear.
> The users who are not member of the admin group have no problem to display the user limited settings menu.

Please look at the nextcloud.log in your data dir and check what error it is. If there is an internal server error, then it is logged there.

**Comment by rocketskill** [comment]
Hello @MorrisJobke  , thank for your help.

I found the error on the nextcloud . log : 

```
{"reqId":"rlnbSlI54tFhAiZLvhMV","level":3,"time":"2018-07-03T07:16:46+00:00","remoteAddr":"185.73.207.98","user":"administrateur","app":"index","method":"GET","url":"\/settings\/user","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/nextcloud\\\/apps\\\/onlyoffice\\\/lib\\\/adminsection.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/nextcl...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(95): ReflectionClass->__construct('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(346): OC\\\\ServerContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(374): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(100): OC\\\\Settings\\\\Manager->getAdminSections()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(51): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatAdminSections('personal', 'personal-info')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(125): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('PersonalSetting...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#20 \\\/var\\\/www\\\/nextcloud\\\/index.php(42): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"}
```

**Comment by MorrisJobke** [comment]
Looks like onlyoffice is causing issues here. Could you go to the apps management and disable and enabled onlyoffice again (might be that it is already disabled then enabling is fine). Then it should work again. After this disabling the app should also clean the entry and fix the issue.

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/issues/3569

**Comment by rocketskill** [comment]
OnlyOffice was already disable.

An enable/Disable of the app was enough to fix the bug.

Thanks for your help.
