### ISSUE TITLE
Error while re-creating a user

### ISSUE THREAD

**Issue by TecJon** [nextcloud/server#1011]
### Steps to reproduce
1. Create User 'UserB'
2. Limit capacity to '10', forget unit (GB), example files (Documents, Photos) are corrupted (zero KB files)
3. Delete UserB
4. Re-create UserB
### Expected behaviour

When logging in as UserB example files and folders are shown.
### Actual behaviour

When logging in as UserB only the Documents folder exists with a zero KB example.odt file. 'Photos' folder is missing. When creating a folder named 'Photos' a fail message is displayed. Other folder names can be used without a problem.
Database table 'oc_jobs' has 835 entries even though cron is working fine. Many of the entries relate to 'UserB' which is currently deleted.
### Server configuration

**Operating system**: Ubuntu

**Web server:** nginx 

**Database:** MySQL

**PHP version:** PHP 5.5.9-1ubuntu4.14 (fpm-fcgi) (built: Oct 28 2015 01:38:24)

**Nextcloud version:** 9.0.52

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** nextcloud website

**Signing status:**
<details>
<summary>

Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.3.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.1
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
  - user_saml
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
{
    "system": {
        "instanceid": "ocl3ill45wmk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/var\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "9.0.52.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "example.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.example.com",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "maintenance": false
    }
}
```

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no 
### Client configuration

**Browser:** Firefox

**Operating system:** Windows 10
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
No errors logged
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
{"reqId":"UeMpSG2JOrQ2ML3eoQTl","remoteAddr":"XXX.XXX.XXX.XX","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_UserA\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'nextclouduser'@'localhost' for table 'user'","level":3,"time":"2016-07-11T18:18:55+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"UeMpSG2JOrQ2ML3eoQTl","remoteAddr":"XXX.XXX.XXX.XX","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `nextcloud` . * TO 'nextclouduser'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'nextclouduser'@'localhost' to database 'nextcloud'","level":3,"time":"2016-07-11T18:18:56+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"UeMpSG2JOrQ2ML3eoQTl","remoteAddr":"XXX.XXX.XXX.XX","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/installer.php(640): include('\\\/var\\\/www\\\/nextcl...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/installer.php(591): OC_Installer::includeAppScript('\\\/var\\\/www\\\/nextcl...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/installer.php(562): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(917): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-07-11T18:19:06+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"UeMpSG2JOrQ2ML3eoQTl","remoteAddr":"XXX.XXX.XXX.XX","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/installer.php(640): include('\\\/var\\\/www\\\/nextcl...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/installer.php(591): OC_Installer::includeAppScript('\\\/var\\\/www\\\/nextcl...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/installer.php(562): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(917): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-07-11T18:19:06+00:00","method":"POST","url":"\/index.php","user":"--"}

```

</details>

**Comment by SamEliotFisher** [comment]
I changed from Ajax cron to system cron. Manually called cron (jobs are down to 12 now). Deleted database entries in oc_addressbooks, oc_calendars. 
Re-creating UserB worked without the error above.

**Comment by MorrisJobke** [comment]
I can't reproduce this anymore. @tecjon Feel free to comment on this again if it still happens for you.

**Comment by bitbonk** [comment]
We just experienced the same thing on nextCloud 13.0.2

**Comment by MorrisJobke** [comment]
> We just experienced exactly the same bug on nextCloud 13.0.2

Please upgrade to the latest maintenance release first.
