### ISSUE TITLE
External sites Setting bug

### ISSUE THREAD

**Issue by run2death** [nextcloud/server#10329]
### Steps to reproduce
1. install External sites app
2. Add a external site.
3. change positon to quota.
4. load user settings page
5. you can see the link
6. go back set position to settings menu or link，
7. load user setting page

### Expected behaviour
user setting page

### Actual behaviour
error report page

### Server configuration

**Operating system:** CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0+

**Nextcloud version:** latest stable

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** nextcloud.com Source Code

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
External sites
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**Chrome
**Operating system:**Win10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"uQ6a7O8BV0Z7aUxKjeQ7","level":3,"time":"2018-07-22T08:34:49+00:00","remoteAddr":"119.165.109.143","user":"jing1","app":"index","method":"GET","url":"\/settings\/user","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"id\\\" for route \\\"external.site.showPage\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'external.site.s...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('external.site.s...', Array, 1)\\n#2 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('external.site.s...', Array, false)\\n#3 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\CachingRouter->generate('external.site.s...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/apps\\\/external\\\/lib\\\/Settings\\\/Personal.php(60): OC\\\\URLGenerator->linkToRoute('external.site.s...', Array)\\n#5 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(115): OCA\\\\External\\\\Settings\\\\Personal->getForm()\\n#6 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(67): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatSettings(Array)\\n#7 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(126): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getSettings('personal-info')\\n#8 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#9 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#10 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#12 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#17 \\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/index.php(42): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/xxxx.com\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (Windows NT 10.0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.4.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by run2death** [comment]
I've found that bug has been fixed in the latest codes.
https://github.com/nextcloud/external/commit/46fd07f320e529fed630011ab7b575993e67aa44
Thanks for all your work.
