### ISSUE TITLE
Unstable WebDAV access only certain device got stable access

### ISSUE THREAD

**Issue by Milokita** [nextcloud/server#10493]
### Steps to reproduce
1. Accessing WebDAV using Kodi 17.6

### Expected behaviour
Success fully connects to the server 

### Actual behaviour

- one android device got connected with no error 
- another android device was able to connect but failed to connect after reinstall the kodi app
- one windows client could  connect using the built-in File Browser but could not connect using kodi 17.6 but they are fresh install

### Server configuration

**Operating system**: debian 9
 
**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP-7

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - announcementcenter: 3.2.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - camerarawpreviews: 0.5.3
  - checksum: 0.4.0
  - circles: 0.14.0
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.6
  - drawio: 0.8.9
  - encryption: 2.0.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - gpxedit: 0.0.8
  - gpxmotion: 0.0.6
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.1
  - metadata: 0.6.0
  - music: 0.5.6
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.3.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED VALUE***,
  
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/242c.top\/",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "zh",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "trashbin_retention_obligation": "180,auto",
        "versions_retention_obligation": "30, auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "debug": false,
        "updater.release.channel": "stable",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:**  no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Kodi 17.6

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No error
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"oQFY1JKG3EZcQEB7tMbO","level":1,"time":"2018-08-02T03:54:05+00:00","remoteAddr":"10.90.90.196","user":"--","app":"admin_audit","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login attempt: \"kodi\"","userAgent":"Kodi\/17.6 (Linux; Android 8.0; VTR-AL00 Build\/HUAWEIVTR-AL00) Android\/8.0.0 Sys_CPU\/aarch64 App_Bitness\/64 Version\/17.6-Git:20171119-ced5097","version":"13.0.1.1"}
{"reqId":"oQFY1JKG3EZcQEB7tMbO","level":1,"time":"2018-08-02T03:54:06+00:00","remoteAddr":"10.90.90.196","user":"kodi","app":"admin_audit","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login successful: \"kodi\"","userAgent":"Kodi\/17.6 (Linux; Android 8.0; VTR-AL00 Build\/HUAWEIVTR-AL00) Android\/8.0.0 Sys_CPU\/aarch64 App_Bitness\/64 Version\/17.6-Git:20171119-ced5097","version":"13.0.1.1"}
{"reqId":"UBDBIhpBypbk4tVb0fZl","level":1,"time":"2018-08-02T03:55:05+00:00","remoteAddr":"10.90.90.181","user":"--","app":"admin_audit","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login attempt: \"kodi\"","userAgent":"Kodi\/17.6 (Windows NT 10.0; WOW64) App_Bitness\/32 Version\/17.6-Git:20171114-a9a7a20","version":"13.0.1.1"}
{"reqId":"UBDBIhpBypbk4tVb0fZl","level":2,"time":"2018-08-02T03:55:05+00:00","remoteAddr":"10.90.90.181","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login failed: 'kodi' (Remote IP: '10.90.90.181')","userAgent":"Kodi\/17.6 (Windows NT 10.0; WOW64) App_Bitness\/32 Version\/17.6-Git:20171114-a9a7a20","version":"13.0.1.1"}
{"reqId":"UBDBIhpBypbk4tVb0fZl","level":1,"time":"2018-08-02T03:55:05+00:00","remoteAddr":"10.90.90.181","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Bruteforce attempt from \"10.90.90.181\" detected for action \"login\".","userAgent":"Kodi\/17.6 (Windows NT 10.0; WOW64) App_Bitness\/32 Version\/17.6-Git:20171114-a9a7a20","version":"13.0.1.1"}
{"reqId":"UBDBIhpBypbk4tVb0fZl","level":0,"time":"2018-08-02T03:55:05+00:00","remoteAddr":"10.90.90.181","user":"--","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}","userAgent":"Kodi\/17.6 (Windows NT 10.0; WOW64) App_Bitness\/32 Version\/17.6-Git:20171114-a9a7a20","version":"13.0.1.1"}
```
</details>

#### KODI log
<details>
<summary>KODI log</summary>

```
11:55:05.613 T:12068   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
11:55:05.613 T:12068   ERROR: CCurlFile::Open failed with code 0 for davs://USERNAME:PASSWORD@REMOVED.COM:443/remote.php/webdav/
11:55:05.613 T:12068   ERROR: XFILE::CDAVDirectory::GetDirectory - Unable to get dav directory (davs://USERNAME:PASSWORD@REMOVED.COM:443/remote.php/webdav/)
11:55:05.625 T:6348   ERROR: XFILE::CDirectory::GetDirectory - Error getting davs://USERNAME:PASSWORD@REMOVED.COM:443/remote.php/webdav/
11:55:05.625 T:6348   ERROR: CGUIDialogFileBrowser::GetDirectory(davs://USERNAME:PASSWORD@REMOVED.COM:443/remote.php/webdav/) failed
```
</details>

**Comment by kesselb** [comment]
Still relevant?

**Comment by Milokita** [comment]
Nah, it's been too old to remember what had happened, it seems to related to the surge in request when access blueray iso via kodi
