### ISSUE TITLE
External-Sites-App breaks settingsmenu

### ISSUE THREAD

**Issue by NextBlaubeere** [nextcloud/server#10609]
Hello,

I wanted to use the official "External Sites" App in Nextcloud which i installed via webinterface.
After that I went into Settings and played a little bit with the sites. After setting a site as visible in the "Settings Menu" when accessing the User-Settings i always get an Internal Error.
Only deactivating the App helps to resolve the problem.

### Steps to reproduce
1. Install "External Sites" App
2. Add a Link as visible in "Settings Menu"
3. Click on the User-Settings again.

### Expected behaviour
Normal Settings Menu should appear.

### Actual behaviour
"Internal Error" Page appears.

### Server configuration
**Operating system**:
Ubuntu 16.04 - with official docker image

**Web server:**
Apache2

**Database:**
Maria

**PHP version:**
PHP 7.1.20

**Nextcloud version:** (see Nextcloud admin page)
13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install with official docker image

**Where did you install Nextcloud from:**
docker-hub

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
www-data@ce8321a74e42:~/html$ php occ app:list
Enabled:
  - activity: 2.6.1
  - camerarawpreviews: 0.5.6
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - oauth2: 1.1.1
  - provisioning_api: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_trashbin
  - flowupload
  - nextcloud_announcements
  - notifications
  - password_policy
  - serverinfo
  - sharebymail
  - smb_test
  - survey_client
  - systemtags
  - unsplash
  - updatenotification
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>

```
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'xxx',
    2 => 'xxx',
    3 => 'xxx',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '13.0.5.2',
  'dbname' => 'nextcloud',
  'dbhost' => 'xxx',
  'dbport' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
);
```

</details>

**Are you using external storage, if yes which one:**
Yes, a local one.

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10 Pro x64

#### Web server error log
<details>
when i "cat /var/log/apache2/*" nothing happens
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"oIQM7Q3HfBOTP0UC8VE2","level":3,"time":"2018-08-09T10:45:32+00:00","remoteAddr":"192.168.1.1","user":"root","app":"PHP","method":"GET","url":"\/settings\/user","message":"Undefined index: url at \/var\/www\/html\/custom_apps\/external\/lib\/Settings\/Personal.php#58","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.5.2"}
{"reqId":"oIQM7Q3HfBOTP0UC8VE2","level":3,"time":"2018-08-09T10:45:32+00:00","remoteAddr":"192.168.1.1","user":"root","app":"PHP","method":"GET","url":"\/settings\/user","message":"Undefined index: redirect at \/var\/www\/html\/custom_apps\/external\/lib\/Settings\/Personal.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.5.2"}
{"reqId":"oIQM7Q3HfBOTP0UC8VE2","level":3,"time":"2018-08-09T10:45:32+00:00","remoteAddr":"192.168.1.1","user":"root","app":"PHP","method":"GET","url":"\/settings\/user","message":"Undefined index: id at \/var\/www\/html\/custom_apps\/external\/lib\/Settings\/Personal.php#60","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.5.2"}
{"reqId":"oIQM7Q3HfBOTP0UC8VE2","level":3,"time":"2018-08-09T10:45:32+00:00","remoteAddr":"192.168.1.1","user":"root","app":"index","method":"GET","url":"\/settings\/user","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"id\\\" for route \\\"external.site.showPage\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'external.site.s...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('external.site.s...', Array, 1)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('external.site.s...', Array, false)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\CachingRouter->generate('external.site.s...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/custom_apps\\\/external\\\/lib\\\/Settings\\\/Personal.php(60): OC\\\\URLGenerator->linkToRoute('external.site.s...', Array)\\n#5 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(115): OCA\\\\External\\\\Settings\\\\Personal->getForm()\\n#6 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/PersonalSettingsController.php(67): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatSettings(Array)\\n#7 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(126): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getSettings('personal-info')\\n#8 \\\/var\\\/www\\\/html\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#9 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#17 \\\/var\\\/www\\\/html\\\/index.php(42): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.5.2"}

```
</details>

any fix for this?

**Comment by NextBlaubeere** [comment]
ok sorry i didnt know there is an extra github-page for the app. i opened the issue there again.
this can be closed then, i think.
