### ISSUE TITLE
SMB can not be mounted.

### ISSUE THREAD

**Issue by juebanlin** [nextcloud/server#10793]
### Steps to reproduce
I recently upgraded Nextcloud and freenas, and found that SMB anonymous sharing on freenas was not mounted. It was already mounted successfully. Now the situation is that SMB sharing on Windows server can be mounted, SMB of freenas can not be mounted, SMB of freenas can be mounted successfully on windows.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
ubuntu 16.04 ova
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Error | PHP | Undefined offset: 4 at /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php#56 | 2018-08-22T16:05:59+0800
-- | -- | -- | --
Error | no app in context | issuetemplate | 2018-08-22T16:05:44+0800
Error | no app in context | issuetemplate | 2018-08-22T16:05:36+0800
Error | no app in context | issuetemplate | 2018-08-22T16:05:34+0800
Error | no app in context | Error  while getting file info:  {"Exception":"Icewind\\SMB\\Exception\\TimedOutException","Message":"\/","Code":110,"Trace":"#0   \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(49):  Icewind\\SMB\\Exception\\Exception::fromMap(Array, 110, '\/')\n#1  \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(61):  Icewind\\SMB\\NativeState->handleError('\/')\n#2  \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(170):  Icewind\\SMB\\NativeState->testResult(false,  'smb:\/\/192.168.0...')\n#3  \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(107):  Icewind\\SMB\\NativeState->stat('smb:\/\/192.168.0...')\n#4  \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(103):  Icewind\\SMB\\NativeShare->getStat('\/')\n#5  \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(140):  Icewind\\SMB\\NativeShare->stat('\/')\n#6  \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(235):  OCA\\Files_External\\Lib\\Storage\\SMB->getFileInfo('\/')\n#7  \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php(449):  OCA\\Files_External\\Lib\\Storage\\SMB->stat('')\n#8  \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(543):  OC\\Files\\Storage\\Common->test()\n#9  \/var\/www\/nextcloud\/apps\/files_external\/lib\/config.php(234):  OCA\\Files_External\\Lib\\Storage\\SMB->test(false, true)\n#10  \/var\/www\/nextcloud\/apps\/files_external\/lib\/Controller\/StoragesController.php(256):  OC_Mount_Config::getBackendStatus('\\\\OCA\\\\Files_Exte...', Array,  false, true)\n#11  \/var\/www\/nextcloud\/apps\/files_external\/lib\/Controller\/StoragesController.php(305):   OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_External\\Lib\\StorageConfig),  true)\n#12 [internal function]:  OCA\\Files_External\\Controller\\StoragesController->show(7,  true)\n#13  \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161):  call_user_func_array(Array, Array)\n#14  \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91):   OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController),  'show')\n#15  \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(115):  OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController),  'show')\n#16  \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47):  OC\\AppFramework\\App::main('OCA\\\\Files_Exter...', 'show',  Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#17  [internal function]:  OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#18  \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(297):  call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler),  Array)\n#19 \/var\/www\/nextcloud\/lib\/base.php(999):  OC\\Route\\Router->match('\/apps\/files_ext...')\n#20  \/var\/www\/nextcloud\/index.php(42): OC::handleRequest()\n#21  {main}","File":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/Exception.php","Line":30} | 2018-08-22T16:05:16+0800


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by baloan** [comment]
I have the same issue. Seems to me nextcloud and freenas cannot agree on a common protocol:

### nextcloud samba log file
<details>

```
[2018/09/05 19:08:26.801985,  3] ../lib/util/access.c:361(allow_access)
  Allowed connection from 192.168.178.3 (192.168.178.3)
[2018/09/05 19:08:26.802100,  3] ../source3/smbd/oplock.c:1329(init_oplocks)
  init_oplocks: initializing messages.
[2018/09/05 19:08:26.802181,  3] ../source3/smbd/process.c:1959(process_smb)
  Transaction 0 of length 194 (0 toread)
[2018/09/05 19:08:26.802206,  3] ../source3/smbd/process.c:1539(switch_message)
  switch message SMBnegprot (pid 17213) conn 0x0
[2018/09/05 19:08:26.802949,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [PC NETWORK PROGRAM 1.0]
[2018/09/05 19:08:26.802972,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [MICROSOFT NETWORKS 1.03]
[2018/09/05 19:08:26.802988,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [MICROSOFT NETWORKS 3.0]
[2018/09/05 19:08:26.803002,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [LANMAN1.0]
[2018/09/05 19:08:26.803016,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [LM1.2X002]
[2018/09/05 19:08:26.803030,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [DOS LANMAN2.1]
[2018/09/05 19:08:26.803044,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [LANMAN2.1]
[2018/09/05 19:08:26.803058,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [Samba]
[2018/09/05 19:08:26.803072,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [NT LANMAN 1.0]
[2018/09/05 19:08:26.803086,  3] ../source3/smbd/negprot.c:612(reply_negprot)
  Requested protocol [NT LM 0.12]
[2018/09/05 19:08:26.803139,  3] ../source3/smbd/negprot.c:738(reply_negprot)
  reply_negprot: No protocol supported !
[2018/09/05 19:08:26.803794,  3] ../source3/smbd/server_exit.c:248(exit_server_common)
  Server exit (no protocol supported)
[2018/09/05 19:08:26.826961,  3] ../source3/lib/util_procid.c:54(pid_to_procid)
  pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
```
</details>

### Steps to reproduce
1. create external storage to nextcloud server with CIFS/SMB

### Expected behaviour
Should connect to nextcloud.

### Actual behaviour
```
External mount error 
There was an error with message: Empty response from the server. Do you want to review mount point config in personal settings page?

```
### Server configuration
**Operating system**: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64)
**Web server:** Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 
**Database:** mysql 6.7.23
**PHP version:** PHP 7.0.30
**Nextcloud version:** 13.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:** update from 13.0.4
**Where did you install Nextcloud from:** web client

**Configuration status:**
<details>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.3.2
  - bookmarks: 0.12.2
  - bruteforcesettings: 1.1.0
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - gpxpod: 2.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.4.1
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_u2f: 1.5.5
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - direct_menu
  - encryption
  - ojsxc
  - registration
  - spreed
  - systemtags
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "\/",
        "dbtype": "mysql",
        "version": "13.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "trusted_domains": [
            "cloud.baloghs.de"
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "\/",
        "forceSSLforSubdomains": false,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "false",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "production",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** anonymous ubuntu smb access works fine
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** No


### Client configuration
**Browser:** firefox
**Operating system:** Windows 8.1

**Comment by baloan** [comment]
For comparison her the log when another ubuntu server connects:

`/etc/fstab`
`//nas1/backup           /mnt/nas1/backup     cifs    noauto,username=***,password=***,vers=3.0,sec=ntlm,iocharset=utf8      0       0
`

````
[2018/09/05 19:52:35.596587,  3] ../lib/util/access.c:361(allow_access)
  Allowed connection from 192.168.178.3 (192.168.178.3)
[2018/09/05 19:52:35.596702,  3] ../source3/smbd/oplock.c:1329(init_oplocks)
  init_oplocks: initializing messages.
[2018/09/05 19:52:35.596783,  3] ../source3/smbd/process.c:1959(process_smb)
  Transaction 0 of length 106 (0 toread)
[2018/09/05 19:52:35.596926,  3] ../source3/smbd/smb2_negprot.c:290(smbd_smb2_request_process_negprot)
  Selected protocol SMB3_00
[2018/09/05 19:52:35.597642,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'gssapi_spnego' registered
[2018/09/05 19:52:35.597663,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'gssapi_krb5' registered
[2018/09/05 19:52:35.597677,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'gssapi_krb5_sasl' registered
[2018/09/05 19:52:35.597704,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'spnego' registered
[2018/09/05 19:52:35.597718,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'schannel' registered
[2018/09/05 19:52:35.597732,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'naclrpc_as_system' registered
[2018/09/05 19:52:35.597745,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'sasl-EXTERNAL' registered
[2018/09/05 19:52:35.597759,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'ntlmssp' registered
[2018/09/05 19:52:35.597785,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'ntlmssp_resume_ccache' registered
[2018/09/05 19:52:35.597798,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'http_basic' registered
[2018/09/05 19:52:35.597816,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'http_ntlm' registered
[2018/09/05 19:52:35.597842,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'krb5' registered
[2018/09/05 19:52:35.597855,  3] ../auth/gensec/gensec_start.c:977(gensec_register)
  GENSEC backend 'fake_gssapi_krb5' registered
[2018/09/05 19:52:35.598353,  3] ../auth/ntlmssp/ntlmssp_util.c:69(debug_ntlmssp_flags)
  Got NTLMSSP neg_flags=0xe0080225
[2018/09/05 19:52:35.608270,  3] ../auth/ntlmssp/ntlmssp_server.c:454(ntlmssp_server_preauth)
  Got user=[rsync] domain=[NAS1] workstation=[] len1=0 len2=138
[2018/09/05 19:52:35.608331,  3] ../source3/param/loadparm.c:3856(lp_load_ex)
  lp_load_ex: refreshing parameters

```

**Comment by Chluz** [comment]
Same issue, cannot mount freenas smb share on freenas, 16.04 lts with 13.0.6 and freenas 11.1-U6.

**Comment by luntik2012** [comment]
the same issue, archlinux, nextcloud 15.0.2-1 cannot mount smb share

**Comment by GlenHertz** [comment]
Same issue.  Freenas 11.2-U3 and NextCloud docker 15.07 with `apt-get update && apt-get install -y smbclient && rm -rf /var/lib/apt/lists/*` added.

**Comment by kesselb** [comment]
Still an issue?

**Comment by baloan** [comment]
Nextcloud 17.0.3 mounts SMB with freenas 11.2-U7 successfully.
