### ISSUE TITLE
Deadlock in ('UPDATE `oc_file...', Array, Array) when partition full

### ISSUE THREAD

**Issue by DerDakon** [nextcloud/server#11194]
### Steps to reproduce
1. The nextcloud partition is full
2. try to log in with the web interface

### Actual behaviour
Error message:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /srv/www/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /srv/www/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /srv/www/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 /srv/www/htdocs/nextcloud/lib/private/DB/Connection.php(216): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
#3 /srv/www/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
#4 /srv/www/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(214): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /srv/www/htdocs/nextcloud/lib/private/Lock/DBLockingProvider.php(310): OC\\DB\\Q in /srv/www/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115

```

### Server configuration

**Operating system**: Linux
**Web server:** apache2-2.4.23-25.1.x86_64
**Database:** mariadb-10.0.35-35.1.x86_64
**PHP version:** php7-7.0.7-46.1.x86_64
**Nextcloud version:** nextcloud-14.0.0-43.1.noarch
**Updated from an older Nextcloud/ownCloud or fresh install:** updated from at least 12.0.2 on
**Where did you install Nextcloud from:** https://download.opensuse.org/repositories/server:/php:/applications/openSUSE_Leap_42.3/

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "dbtype": "mysql",
        "version": "14.0.0.19",
        "dbtableprefix": "oc_",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "mail_smtpmode": "qmail",
        "mail_smtpdebug": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium
**Operating system:** Linux

**Comment by DerDakon** [comment]
Just to make it explicit: once I found out that the nextcloud partition (which is a different one from system/mysql/everything else) was full and deleted some things there everything worked fine again.

**Comment by MorrisJobke** [comment]
> I would close this one here in favor of #6899.

Let's do that for now.
