### ISSUE TITLE
Nextcloud 14 Upgrade exception

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#11199]
### Steps to reproduce
1. Upgrade from 13.0.6 to 14.0.0
2.
3.

### Expected behaviour
Upgrade successfull

### Actual behaviour
Exception below

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.2

**Nextcloud version:** 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade

**Where did you install Nextcloud from:** Website download

During upgrade using occ the following exception is thrown:

> Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking for update of app activity in appstore
An unhandled exception has been thrown:
Error: Call to undefined method GuzzleHttp\Client::request() in /var/www/nextcloud/lib/private/Http/Client/Client.php:161
Stack trace:
#0 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
#1 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#2 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
#3 /var/www/nextcloud/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
#4 /var/www/nextcloud/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('activity')
#5 /var/www/nextcloud/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Array)
#6 /var/www/nextcloud/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.0.19', '13.0.6.1')
#7 /var/www/nextcloud/core/Command/Upgrade.php(262): OC\Updater->upgrade()
#8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#15 {main}

**Comment by joekerna** [comment]
This seems to be a duplicate of #10954 
Thanks @nextcloud-bot

**Comment by timm2k** [comment]
Try to disable apps bookmarks or files_external_gdrive. They ship an incompatible version of Guzzle.

**Comment by MorrisJobke** [comment]
> @MorrisJobke (if you know someone better, feel free to mention him here) this issue may come up for others, too. The latest bookmarks app solves this. Do you see the possibility to change the update process so it doesn't use the app files? The first step is to check the version and download it, right? Therefore you don't need the app files. This could solve errors like this one here..

I guess there is very little we can do to fix this from the outside :/

cc @nickvergessen

**Comment by joekerna** [comment]
I reinstalled and recovered my data from backup, so I'm fine.
But this was the first time the update process failed on me 👍
