### ISSUE TITLE
Corrupted DB after update to 14.0.1

### ISSUE THREAD

**Issue by Windyo** [nextcloud/server#11509]
### Steps to reproduce
1. go to nextcloud instance
2. get message "Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log."

### Expected behaviour
Nextcloud displays

### Actual behaviour
A server error happens

### Server configuration

**Operating system**: Latest nextcloudpi image

**Web server:** Raspberry pi 3B

**Database:** Latest nextcloudpi image

**PHP version:** 7

**Nextcloud version:** 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated (12.0.4 > 13.0.6 > 14.0.1) 

**Where did you install Nextcloud from:** Latest nextcloudpi image

**Signing status:**
<details>
<summary>Signing status</summary>

No access due to server error

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.1
  - audioplayer: 2.2.2
  - bruteforcesettings: 1.0.3
  - caniupdate: 0.1.1
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - flowupload: 0.0.5
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_twitter: 1.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - unsplash: 1.0.5
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "10.0.4.128",
            "2": "cloud.bessereau.eu",
            "5": "nextcloudpi.local"
        },
        "datadirectory": "\/mnt\/raid0\/ncdata",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocqm0x3te0l7",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "admin",
        "mail_domain": "ownyourbits.com",
        "overwriteprotocol": "https",
        "loglevel": "2",
        "log_type": "file",
        "maintenance": false,
        "theme": "",
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** 
/mnt/raid0

**Are you using encryption:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
#N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"E69bwtZ4hGan3xH6bXMt","level":4,"time":"2018-10-01T11:45:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"An exception occurred while executing 'SELECT * FROM `oc_jobs` WHERE `reserved_at` <= ? ORDER BY `last_checked` ASC LIMIT 1' with params [1538351102]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_jobs' doesn't exist","userAgent":"--","version":"12.0.4.3"}
{"reqId":"W7IIw38AAQEAAAPIG4IAAEEA","level":3,"time":"2018-10-01T11:45:07+00:00","remoteAddr":"100.74.73.11","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)' with params [\\\"Windyo\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_users' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `uid`, `...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(70): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Database.php(249): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Database.php(303): OC\\\\User\\\\Database->loadUser('Windyo')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(137): OC\\\\User\\\\Database->userExists('Windyo')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(762): OC\\\\User\\\\Manager->get('Windyo')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1055): OC\\\\User\\\\Session->loginWithCookie('Windyo', 'hQzCoR+IclPl4ld...', 'kevn121eu10eq17...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(993): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"12.0.4.3"}
{"reqId":"W7IIw38AAQEAAAPIG4IAAEEA","level":3,"time":"2018-10-01T11:45:08+00:00","remoteAddr":"100.74.73.11","user":"--","app":"core","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)' with params [\\\"Windyo\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_users' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `uid`, `...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(70): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Database.php(249): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Database.php(303): OC\\\\User\\\\Database->loadUser('Windyo')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(137): OC\\\\User\\\\Database->userExists('Windyo')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(762): OC\\\\User\\\\Manager->get('Windyo')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1055): OC\\\\User\\\\Session->loginWithCookie('Windyo', 'hQzCoR+IclPl4ld...', 'kevn121eu10eq17...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(993): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"12.0.4.3"}
{"reqId":"W7IIw38AAQEAAAPIG4IAAEEA","level":3,"time":"2018-10-01T11:45:08+00:00","remoteAddr":"100.74.73.11","user":"--","app":"core","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `numeric_id`, `available`, `last_checked` FROM `oc_storages` WHERE `id` IN (?)' with params [\\\"local::\\\\\\\/mnt\\\\\\\/raid0\\\\\\\/ncdata\\\\\\\/\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_storages' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `n...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(192): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `n...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `n...', Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(213): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/StorageGlobal.php(57): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/StorageGlobal.php(69): OC\\\\Files\\\\Cache\\\\StorageGlobal->loadForStorageIds(Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Storage.php(93): OC\\\\Files\\\\Cache\\\\StorageGlobal->getStorageInfo('local::\\\/mnt\\\/rai...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Storage.php(71): OC\\\\Files\\\\Cache\\\\Storage::getStorageById('local::\\\/mnt\\\/rai...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(102): OC\\\\Files\\\\Cache\\\\Storage->__construct(Object(OCA\\\\RansomwareProtection\\\\StorageWrapper))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(326): OC\\\\Files\\\\Cache\\\\Cache->__construct(Object(OCA\\\\RansomwareProtection\\\\StorageWrapper))\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(388): OC\\\\Files\\\\Storage\\\\Common->getCache('appdata_ocqm0x3...', Object(OCA\\\\RansomwareProtection\\\\StorageWrapper))\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ransomware_protection\\\/lib\\\/StorageWrapper.php(411): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('appdata_ocqm0x3...', Object(OCA\\\\RansomwareProtection\\\\StorageWrapper))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1322): OCA\\\\RansomwareProtection\\\\StorageWrapper->getCache('appdata_ocqm0x3...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1376): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\RansomwareProtection\\\\StorageWrapper), 'appdata_ocqm0x3...', '\\\/appdata_ocqm0x...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(196): OC\\\\Files\\\\View->getFileInfo('\\\/appdata_ocqm0x...')\\n#16 [internal function]: OC\\\\Files\\\\Node\\\\Root->get('\\\/appdata_ocqm0x...')\\n#17 \\\/var\\\/www\\\/nextclo
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
#N/A
```
</details>

**Comment by Windyo** [comment]
Leaving the bug up so someone looks into this, but for clarity I solved this by doing a full database wipe and reimport from a very old backup, then running the habitual scan/cleanups etc.

**Comment by Windyo** [comment]
deactivating "theming" brought the app back online, but witha  declared version of 12.0.4 again, running update...

**Comment by Windyo** [comment]
OK i seem to be stuck in a loop of restore > be on 12.0.4 > Try to update > seeems to work > fail.

**Comment by Windyo** [comment]
OK if anyone wants to debug this I have a fully functional backup, that will restore a working 12.0.4 nextcloud instance, and will then fail update to 14.0.0 100% of the time.

In the meantime I installed 14.0.1 clean and reconfigured. No other solution found ATM.
