### ISSUE TITLE
problems update

### ISSUE THREAD

**Issue by unitrav** [nextcloud/server#12218]
Hey there

When I want to update nextcloud I receive the following error.

Any ideas on how to solve it?

Thank you

Tim

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `class` FROM `oc_personal_sections` WHERE `class` = ? LIMIT 1' with params ["OCA\\FederatedFileSharing\\Settings\\PersonalSection"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'timkroeg_next879.oc_personal_sections' doesn't exist

**Comment by kwisatz** [comment]
Interesting. I have the same issue with an upgrade I'm attempting from Owncloud 10, major version by major version. Upgrading/Migrating from Owncloud 10 worked almost like a breeze, but then Upgrading from Nextcloud 12.0.12.2 to NC 13.0.x fails with this exact error. You'd think the migrate tool would have added this table if it's been introduced by NC…

**Comment by kwisatz** [comment]
Here's a little more verbose material while I'm trying to work around this:

Some context:
```
2018-11-03T17:02:22+00:00 Updating <federatedfilesharing> ...
2018-11-03T17:02:22+00:00 Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `class` FROM `oc_personal_sections` WHERE `class` = ? LIMIT 1' with params ["OCA\\FederatedFileSharing\\Settings\\PersonalSection"]:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_personal_sections' doesn't exist
2018-11-03T17:02:22+00:00 Update failed
```

Exception stack-trace:
```
{"reqId":"*******************","level":3,"time":"2018-11-03T17:05:28+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `class` FROM `oc_personal_sections` WHERE `class` = ? LIMIT 1' with params [\\\"OCA\\\\\\\\FederatedFileSharing\\\\\\\\Settings\\\\\\\\PersonalSection\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_personal_sections' doesn't exist\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n
#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `class` ...', Array)\\n
#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `class` ...', Array, Array, NULL)\\n
#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `class` ...', Array, Array)\\n
#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n
#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Mapper.php(177): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n
#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(286): OC\\\\Settings\\\\Mapper->has('personal_sectio...', 'OCA\\\\\\\\FederatedFi...')\\n
#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(233): OC\\\\Settings\\\\Manager->hasSection('OCA\\\\\\\\FederatedFi...', 'personal_sectio...')\\n
#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(151): OC\\\\Settings\\\\Manager->setupSectionEntry('OCA\\\\\\\\FederatedFi...', 'personal')\\n
#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(1061): OC\\\\Settings\\\\Manager->setupSettings(Array)\\n
#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(390): OC_App::updateApp('federatedfilesh...')\\n
#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(271): OC\\\\Updater->doAppUpgrade()\\n
#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(139): OC\\\\Updater->doUpgrade('13.0.6.1', '12.0.12.2')\\n
#13 \\\/var\\\/www\\\/nextcloud\\\/core\\\/Command\\\/Upgrade.php(270): OC\\\\Updater->upgrade()\\n
#14 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(264): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n
#15 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n
#16 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(228): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n
#17 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(130): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(173): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n
#19 \\\/var\\\/www\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n
#20 \\\/var\\\/www\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/nextcl...')\\n
#21 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"--","version":"12.0.12.2"}
```

**Comment by kwisatz** [comment]
What worked for me (but I'm not sure yet if there won't be issues in the future) was to remove the following apps from the apps folder:
* federatedfilesharing
* twofactor_backupcodes
* firstrunwizard

With these gone, the upgrade succeeds, and also a follow-up upgrade from 13.x to 14.x works.

**Comment by johnsonm** [comment]
The title of the issue I filed turns out to be misleading; Version13000Date20170705121758 is the migration that isn't running here.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/13291#issuecomment-450566483

Closing as I assume this has been resolved by now.
