### ISSUE TITLE
Upload a file is fail

### ISSUE THREAD

**Issue by XDavidT** [nextcloud/server#12706]
### Steps to reproduce
1.Login
2. Upload file type 'iso' about 800MB
3.after more 50% not sure where exactly, it fail

### Expected behaviour
get file uploaded

### Actual behaviour
An exception occurred while executing 'SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [2, "f8af092ec890b0ab7e885960d1c0b46b"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### Server configuration

**Operating system**: Ubuntu

**Web server:** 
Apache/2.4

**Database:**
MYSQL

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
NOPE

**Where did you install Nextcloud from:**
download from official site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocnqc7g0x2rf',
  'passwordsalt' => 'p02XaAy2Hi0N88f2XD33ViZwywrap3',
  'secret' => 'MgpyKXXVw70aTWYtSxJaYN66/Ro3uTkjXZsEcg0XNZ1ytVTa',
  'trusted_domains' => 
  array (
    0 => 'dropit.tech',
  ),
  'datadirectory' => '/home/u660827806/domains/domain.com/Data',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'http://domain.com',
  'dbname' => 'u660827806_nextc',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'u660827806_nextc',
  'dbpassword' => '---',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'domain.com',
  'mail_smtphost' => 'domain.com',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'noreply@domain.com',
  'mail_smtppassword' => '---',
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** no 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:** Firefox

**Operating system:**
Win10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Can't find it
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Fatal | webdav | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'SELECT `fileid` FROM `oc_filecache`  WHERE `storage` = ? AND `path_hash` = ?' with params [2,  "f8af092ec890b0ab7e885960d1c0b46b"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-11-28T11:52:16+0200
-- | -- | -- | --
Error | no app in context | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'SELECT `fileid`, `storage`, `path`,  `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, 					   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum` 				FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with  params [2, "45b963397aa40d4a0063e0d85e4fe7a1"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-11-28T11:52:16+0200
Error | no app in context | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'SELECT `fileid`, `storage`, `path`,  `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, 					   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum` 				FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with  params [2, "45b963397aa40d4a0063e0d85e4fe7a1"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-11-28T11:52:16+0200
Error | PHP | Error  while sending QUERY packet. PID=327647 at  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#105 | 2018-11-28T11:52:16+0200
Error | PHP | Uncaught  Doctrine\DBAL\DBALException: Failed to connect to the database: An  exception occured in driver: SQLSTATE[HY000] [1226] User  'u660827806_nextc' has exceeded the 'max_user_connections' resource  (current value: 15) in  /home/u660827806/domains/dropit.tech/public_html/lib/private/DB/Connection.php:64 Stack trace: #0  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429):  OC\DB\Connection->connect() #1  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389):  Doctrine\DBAL\Connection->getDatabasePlatformVersion() #2  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328):  Doctrine\DBAL\Connection->detectDatabasePlatform() #3  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623):  Doctrine\DBAL\Connection->getDatabasePlatform() #4 /home/u660827806/domains/dropit.tech/public_html/lib/private/DB/ at  /home/u660827806/domains/dropit.tech/public_html/lib/private/DB/Connection.php#64 | 2018-11-28T11:03:36+0200
Error | PHP | Uncaught  Doctrine\DBAL\DBALException: Failed to connect to the database: An  exception occured in driver: SQLSTATE[HY000] [1226] User  'u660827806_nextc' has exceeded the 'max_user_connections' resource  (current value: 15) in  /home/u660827806/domains/dropit.tech/public_html/lib/private/DB/Connection.php:64 Stack trace: #0  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429):  OC\DB\Connection->connect() #1  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389):  Doctrine\DBAL\Connection->getDatabasePlatformVersion() #2  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328):  Doctrine\DBAL\Connection->detectDatabasePlatform() #3  /home/u660827806/domains/dropit.tech/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623):  Doctrine\DBAL\Connection->getDatabasePlatform() #4 /home/u660827806/domains/dropit.tech/public_html/lib/private/DB/ at  /home/u660827806/domains/dropit.tech/public_html/lib/private/DB/Connection.php#64 | 2018-11-28T11:03:36+0200
Error | index | Doctrine\DBAL\DBALException: Failed  to connect to the database: An exception occured in driver:  SQLSTATE[HY000] [1226] User 'u660827806_nextc' has exceeded the  'max_user_connections' resource (current value: 15) | 2018-11-25T13:23:46+0200
Fatal | webdav | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'SELECT `fileid` FROM `oc_filecache`  WHERE `storage` = ? AND `path_hash` = ?' with params [2,  "efbe2bf543c15a02a410ac2dc3cb92c9"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-11-23T21:35:23+0200
Error | no app in context | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'SELECT `fileid`, `storage`, `path`,  `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, 					   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum` 				FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with  params [2, "45b963397aa40d4a0063e0d85e4fe7a1"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-11-23T21:35:23+0200
Error | no app in context | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'SELECT `fileid`, `storage`, `path`,  `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, 					   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum` 				FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with  params [2, "45b963397aa40d4a0063e0d85e4fe7a1"]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-11-23T21:35:23+0200


```
</details>

**Comment by ChristophWurst** [comment]
> 2006 MySQL server has gone away

See https://help.nextcloud.com/search?q=MySQL%20server%20has%20gone%20away.
