### ISSUE TITLE
Not able to access settings page after update to v 13.0.7.2/13.0.8

### ISSUE THREAD

**Issue by simogeo** [nextcloud/server#12769]
### Steps to reproduce
1. Try to connect to Settings page (/index.php/settings/user)

### Expected behaviour
Access the page !

### Actual behaviour
Getting following Error message : 

> Erreur interne du serveur
> Le serveur est incapable d'exécuter votre requête.
> Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l'administrateur du serveur.
> Le fichier journal du serveur peut fournir plus de renseignements.
> Renseignements techniques
>     Adresse distante : xx.xxx.xxx.xxx
>     ID de la demande : RbsKRfgmB7Kk5UcmNNhZ

### Server configuration

**Operating system**: ubuntu server 14.04.3

**Web server:** apache 2

**Database:** mysql

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page)  13.0.7.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** ?

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.2
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bookmarks
  - bruteforcesettings
  - documents
  - encryption
  - files_comments
  - files_external
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/xxxx.com",
        "dbtype": "mysql",
        "version": "13.0.7.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false
    }
}

```
</details>

**Are you using external storage, if yes which one: no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"v3myLR04oOopTG1ZHb7A","level":0,"time":"2018-12-01T15:30:36+00:00","remoteAddr":"78.194.248.211","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 7959","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"v3myLR04oOopTG1ZHb7A","level":0,"time":"2018-12-01T15:30:36+00:00","remoteAddr":"78.194.248.211","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 7959 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":3,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"index","method":"GET","url":"\/index.php\/settings\/user","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps2\\\/bookmarks\\\/settings\\\/adminsection.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(95): ReflectionClass->__construct('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(346): OC\\\\ServerContainer->query('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(374): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(100): OC\\\\Settings\\\\Manager->getAdminSections()\\n#9 \\\/var\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(51): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatAdminSections('personal', 'personal-info')\\n#10 \\\/var\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(125): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\\n#11 \\\/var\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('PersonalSetting...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#20 \\\/var\\\/www\\\/owncloud\\\/index.php(42): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":0,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":0,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":0,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":0,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":0,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"NCC9eSxuz6jM9zxPozz8","level":0,"time":"2018-12-01T15:30:39+00:00","remoteAddr":"78.194.248.211","user":"JohnDoe","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/header.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"ic8cG6bDpYn2mQ2ESi0c","level":0,"time":"2018-12-01T15:30:40+00:00","remoteAddr":"78.194.248.211","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 8215","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"ic8cG6bDpYn2mQ2ESi0c","level":0,"time":"2018-12-01T15:30:40+00:00","remoteAddr":"78.194.248.211","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 8215 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}

```
</details>

**Comment by simogeo** [comment]
(Please see nextcloud log above) Thanks for your help

**Comment by simogeo** [comment]
(Please see nextcloud log above) Thanks for your help

**Comment by simogeo** [comment]
Investigating a bit more, it seems this happened when users belongs to admin group only !

**Comment by simogeo** [comment]
I've just updated to 13.0.8 (using command line) but I still have the same issue ...

**Comment by MorrisJobke** [comment]
It seems the bookmarks app is causing issues here. Remove it from the apps/ folder and the problem should be gone. Please check then also the bookmarks app issue tracker for similar errors.

**Comment by LeChi62** [comment]
>Investigating a bit more, it seems this happened when users belongs to admin group only !

I have the same problem
- nextcloud 13
- on an OVH mutual server
- php 5.6 or 7.0 : same result
- nothing in nextcloud.log

**Apps activated**
Activity | 2·6·1
Auditing / Logging | 1·3·0
Calendar | 1·6·1
Contacts | 2·1·5
Dashboard | 5·0·1
Deleted files | 1·3·0
File sharing | 1·5·0
First run wizard | 2·2·1
Gallery | 18·0·0
Group folders | 1·3·3
Log Reader | 2·0·0
Monitoring | 1·3·0
Notes | 2·5·1
OwnBackup | 18·11·0
Password policy | 1·3·0
QOwnNotesAPI | 18·11·0
Tasks | 0·9·8
Text editor | 2·5·1
Update notification | 1·3·0

**Comment by simogeo** [comment]
@LeChi62 : enabling Bookmarks again did the trick for me ....
