### ISSUE TITLE
14.0.4 --> 15.0.0 Failed with `occ upgrade`

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#13040]
### Steps to reproduce
Update with the `occ` command.

### Expected behaviour
Update should work

### Actual behaviour
Update failed with this:

```
root@cloud:~# sudo -u www-data php /var/www/nextcloud/occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
An unhandled exception has been thrown:
TypeError: preg_match() expects parameter 2 to be string, array given in /var/www/nextcloud/lib/private/AppFramework/Http/Request.php:612
Stack trace:
#0 /var/www/nextcloud/lib/private/AppFramework/Http/Request.php(612): preg_match('/^([0-9]{1,3}\\....', Array, NULL)
#1 /var/www/nextcloud/lib/private/AppFramework/Http/Request.php(631): OC\AppFramework\Http\Request->matchesTrustedProxy(Array, '')
#2 /var/www/nextcloud/lib/private/AppFramework/Http/Request.php(650): OC\AppFramework\Http\Request->isTrustedProxy(Array, '')
#3 /var/www/nextcloud/lib/private/Log/File.php(99): OC\AppFramework\Http\Request->getRemoteAddress()
#4 /var/www/nextcloud/lib/private/Log.php(329): OC\Log\File->write('updater', '\\OC\\Updater::se...', 1)
#5 /var/www/nextcloud/lib/private/Log.php(218): OC\Log->writeLog('updater', '\\OC\\Updater::se...', 1)
#6 /var/www/nextcloud/lib/private/Log.php(180): OC\Log->log(1, '\\OC\\Updater::se...', Array)
#7 /var/www/nextcloud/lib/private/Updater.php(602): OC\Log->info('\\OC\\Updater::se...', Array)
#8 [internal function]: OC\Updater->OC\{closure}(0, 'Debug')
#9 /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#10 /var/www/nextcloud/lib/private/Updater.php(104): OC\Hooks\BasicEmitter->emit('\\OC\\Updater', 'setDebugLogLeve...', Array)
#11 /var/www/nextcloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#12 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
#18 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

## Server configuration detail

**Operating system:** Linux 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit

**PHP version:** 

7.2.10-0ubuntu0.18.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, redis, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - calendar: 1.6.4
 - caniupdate: 0.2.0
 - checksum: 0.4.1
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.0
 - deck: 0.5.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_fulltextsearch: 1.1.1
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - fulltextsearch: 1.1.0
 - fulltextsearch_elasticsearch: 1.0.2
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - richdocuments: 3.0.5
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - spreed: 4.0.2
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_snapshots
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.10.8",
        "cloud.hanssonit.se",
        "office.hanssonit.se"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "14.0.4.2",
    "overwrite.cli.url": "https:\/\/cloud.hanssonit.se\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "loglevel": "2",
    "log_type": "file",
    "logfile": "\/mnt\/ncdata\/nextcloud.log",
    "logtimezone": "Europe\/Stockholm",
    "maintenance": false,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "simpleSignUpLink.shown": false,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED",
        "HTTP_FORWARDED_FOR"
    ],
    "trashbin_retention_obligation": "auto, 30",
    "activity_expire_days": 60,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "remember_login_cookie_lifetime": 1800
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

**Operating system:** Ubunu Budgie 18.04

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by danielkesselberg** [comment]
I guess something is wrong with your trusted proxies. Format should be like below:

```
[
'firstproxy',
'secondproxy'
]
```

From the error message I would expect that you have an array inside an array.

**Comment by enoch85** [comment]
@danielkesselberg Thanks! I'll test when I get back home.

**Comment by enoch85** [comment]
Yup, that was the error. Thanks again. :+1:
