### ISSUE TITLE
NC15 - Unhandled exception occ files:scan

### ISSUE THREAD

**Issue by tilllt** [nextcloud/server#13142]
### Steps to reproduce
1. Run "docker exec --user www-data nextcloud php occ files:scan --all"
2. When reaching a certain directory or file, the scan crashes 

### Expected behaviour
occ files:scan --all should complete without errors.

### Actual behaviour
```
Starting scan for user 17 out of 32 (username)
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\OCS\DiscoveryService::discover() must be of the type string, null given, called in /var/www/html/apps/files_sharing/lib/External/Manager.php on line 382 and defined in /var/www/html/lib/private/OCS/DiscoveryService.php:65
Stack trace:
#0 /var/www/html/apps/files_sharing/lib/External/Manager.php(382): OC\OCS\DiscoveryService->discover(NULL, 'FEDERATED_SHARI...')
#1 /var/www/html/apps/files_sharing/lib/External/Manager.php(527): OCA\Files_Sharing\External\Manager->sendFeedbackToRemote(NULL, NULL, NULL, 'decline')
#2 /var/www/html/apps/files_sharing/lib/External/Storage.php(217): OCA\Files_Sharing\External\Manager->removeShare('/files/Shared/i...')
#3 [internal function]: OCA\Files_Sharing\External\Storage->checkStorageAvailability()
#4 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)
#5 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
#6 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)
#7 /var/www/html/apps/files_sharing/lib/External/Scanner.php(89): OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
#8 /var/www/html/apps/files_sharing/lib/External/Scanner.php(44): OCA\Files_Sharing\External\Scanner->scanAll()
#9 /var/www/html/lib/private/Files/Utils/Scanner.php(245): OCA\Files_Sharing\External\Scanner->scan('', true, 3)
#10 /var/www/html/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/username', true, NULL)
#11 /var/www/html/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('username', '/username', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#12 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/console.php(96): OC\Console\Application->run()
#19 /var/www/html/occ(11): require_once('/var/www/html/c...')
#20 {main}
```

### Server configuration

**Operating system**: Centos 7.5 (Host) - Nextcloud Docker

**Web server:** Nginx 1.12.2 proxying Nextcloud Docker

**Database:** Dockerized MariaDB

**PHP version:** Nextcloud Docker

**Nextcloud version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh from Docker

**Where did you install Nextcloud from:** Docker

**Comment by tilllt** [comment]
BTW, this also breaks the indexing of Fulltextsearch-Elasticsearch which bails at the same file.

**Comment by tilllt** [comment]
As far as i can see the issue is gone in 15.0.2 both OCC files:scan and fulltextsearch:index now finish the scan successfully again. Closing this.

**Comment by guzi42** [comment]
As far as I can see, it's still present in 15.0.5. OCC  files:scan and fulltextsearch:index lead the same error for one user folder.
