### ISSUE TITLE
Migration in Version14000Date20180518120534.php appears missing

### ISSUE THREAD

**Issue by johnsonm** [nextcloud/server#13291]
### Steps to reproduce
1. Installed Nextcloud as Fedora packages, realized that wasn't going to be updated after updating from Fedora 27 to 28
2. Upgraded 10→11→12→13→14 in order using occ upgrade, with first three updates done from official php7.0 docker container
3. Errors because authtoken table is missing `version` — and I see `private_key` and `public_key` also missing, making it look like core/Migrations/Version14000Date20180518120534.php did not run

### Expected behaviour
Migration run and authtoken table migrated

Alternatively, a way to use occ migrations to run that migration, which may be possible but I don't know how...

### Actual behaviour
```
An exception occurred while executing 'SELECT * FROM `oc_authtoken` WHERE (`token` = ?) AND (`version` = ?)' with params ...
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'version' in 'where clause'
```

### Server configuration

**Operating system**:
Fedora 28

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
7.2.8

**Nextcloud version:** (see Nextcloud admin page)
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud 10, not previously an ownCloud install.

**Where did you install Nextcloud from:**
Initially fedora packages, replaced with official tarballs.

**Signing status:**

..../settings/integrity/failed 

> Internal Server Error
> The server was unable to complete your request.
> If this happens again, please send the technical details below to the server administrator.
> More details can be found in the server log.

**List of activated apps:**
```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - audioplayer
  - calendar
  - documents
  - encryption
  - files_external
  - twofactor_totp
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "log_type": "syslog",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "check_for_working_htaccess": false,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/www\/html\/nextcloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.danlj.org"
        ],
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{mail.EXAMPLE.COM:993\/imap\/ssl\/readonly}"
                ]
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by johnsonm** [comment]
I tried updating from 12.0.13 to 13.0.0 instead of going straight to 13.0.8 to follow a more "historic" path but that failed in the same way.

**Comment by johnsonm** [comment]
https://help.nextcloud.com/t/upgrade-issues-to-nextcloud-14-on-database/39561 looks similar — the URL says it's about 14 but the text is clear that it's 13.

Then I found #12218 which included a workaround that removes apps and lets the rest of the update progress, but the problem is persistent; I moved the federatedfilesharing, twofactor_backupcodes, and firstrunwizard apps out of the `apps` directory in 13.0.0 and the upgrade continued, but that clearly didn't cause the migration step to work, because the upgrade to 13.0.8 still broke with the error
```
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `class` FROM `oc_personal_sections` WHERE `class` = ? LIMIT 1' with params ["OCA\\FederatedFileSharing\\Settings\\PersonalSection"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_personal_sections' doesn't exist
Update failed
```

**Comment by johnsonm** [comment]
Using the workaround allows the upgrade to proceed, but then trying to go do the admin settings in the browser leads to a 500 Internal Server Error and it's clear that the migration which hasn't happened is still important outside of those three apps: 

```
Dec 30 08:52:59 nextcloud ownCloud[1385]: {index} Exception: {"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT DISTINCT `s`.`class`, `s`.`priority` FROM `oc_personal_sections` `s`, `oc_personal_settings` `f` WHERE `s`.`id` = `f`.`section`':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_personal_sections' doesn't exist","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(855): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT DISTINCT...', Array)\n#2 \/var\/www\/html\/nextcloud\/lib\/private\/DB\/Connection.php(195): Doctrine\\DBAL\\Connection->executeQuery('SELECT DISTINCT...', Array, Array, NULL)\n#3 \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(206): OC\\DB\\Connection->executeQuery('SELECT DISTINCT...', Array, Array)\n#4 \/var\/www\/html\/nextcloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php(214): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 \/var\/www\/html\/nextcloud\/lib\/private\/Settings\/Mapper.php(124): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 \/var\/www\/html\/nextcloud\/lib\/private\/Settings\/Mapper.php(99): OC\\Settings\\Mapper->getSectionsFromDB('personal')\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/Settings\/Manager.php(502): OC\\Settings\\Mapper->getPersonalSectionsFromDB()\n#8 \/var\/www\/html\/nextcloud\/settings\/Controller\/CommonSettingsTrait.php(93): OC\\Settings\\Manager->getPersonalSections()\n#9 \/var\/www\/html\/nextcloud\/settings\/Controller\/CommonSettingsTrait.php(46): OC\\Settings\\Controller\\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')\n#10 \/var\/www\/html\/nextcloud\/settings\/Controller\/CommonSettingsTrait.php(125): OC\\Settings\\Controller\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\n#11 \/var\/www\/html\/nextcloud\/settings\/Controller\/PersonalSettingsController.php(57): OC\\Settings\\Controller\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\n#12 [internal function]: OC\\Settings\\Controller\\PersonalSettingsController->index('personal-info')\n#13 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161): call_user_func_array(Array, Array)\n#14 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Settings\\Controller\\PersonalSettingsController), 'index')\n#15 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Settings\\Controller\\PersonalSettingsController), 'index')\n#16 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OC\\\\Settings\\\\Con...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#17 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#18 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#19 \/var\/www\/html\/nextcloud\/lib\/base.php(999): OC\\Route\\Router->match('\/settings\/user')\n#20 \/var\/www\/html\/nextcloud\/index.php(42): OC::handleRequest()\n#21 {main}","File":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":53}
```

**Comment by johnsonm** [comment]
#8362 may imply that this is due to missing a previous migration step, so I guess I will need to start over again — trying to find all the required migration steps when catching up an old installation is not trivial.

**Comment by johnsonm** [comment]
My tables were already Barracuda, so 8362 was a red herring.

**Comment by johnsonm** [comment]
After setting `'debug' => true,` in config.php, I ran:
```
sudo -u apache php ./occ migration:execute core 13000Date20170705121758
```

That ran the migration and let me move forward.

**Comment by johnsonm** [comment]
After that, more migrations were required:
```
sudo -u apache php ./occ migration:execute core 14000Date20180404140050
sudo -u apache php ./occ migration:execute core 14000Date20180518120534
```

After that, and disabling debug mode again, 14.0.4 worked.
