### ISSUE TITLE
occ files:scan error : Exception during scan: Undefined index: parent

### ISSUE THREAD

**Issue by stanelie** [nextcloud/server#13414]
### Steps to reproduce
1. run sudo -u www-data php occ files:scan username
2.
3.

### Expected behaviour
The scan should complete without error
### Actual behaviour
The scan fails with an error message : 
```
root@cloud:/var/www/nextcloud# sudo -u www-data php occ files:scan username
Starting scan for user 1 out of 1 (username)
Exception during scan: Undefined index: parent
#0 /var/www/nextcloud/lib/private/Files/Cache/Cache.php(168): OCA\Files\Command\Scan->exceptionErrorHandler(8, 'Undefined index...', '/var/www/nextcl...', 168, Array)
#1 /var/www/nextcloud/lib/private/Files/Cache/Cache.php(154): OC\Files\Cache\Cache::cacheEntryFromData(Array, Object(OC\Files\Type\Loader))
#2 /var/www/nextcloud/lib/private/Files/Cache/HomeCache.php(76): OC\Files\Cache\Cache->get(750684300251194812)
#3 /var/www/nextcloud/lib/private/Files/Cache/Cache.php(451): OC\Files\Cache\HomeCache->get(750684300251194812)
#4 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(271): OC\Files\Cache\Cache->remove(750684300251194812)
#5 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(475): OC\Files\Cache\Scanner->removeFromCache(750684300251194812)
#6 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(406): OC\Files\Cache\Scanner->handleChildren('', true, 3, '4014421', true, 0)
#7 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(338): OC\Files\Cache\Scanner->scanChildren('', true, 3, '4014421', true)
#8 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(245): OC\Files\Cache\Scanner->scan('', true, 3)
#9 /var/www/nextcloud/apps/files/lib/Command/Scan.php(172): OC\Files\Utils\Scanner->scan('/username', true, NULL)
#10 /var/www/nextcloud/apps/files/lib/Command/Scan.php(249): OCA\Files\Command\Scan->scanFiles('username', '/username', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#11 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(251): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/core/Command/Base.php(162): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
#18 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#19 {main}

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 1       | 0     | 00:00:00     |
+---------+-------+--------------+
```

### Server configuration

**Operating system**:
Ubuntu 16.04.5 LTS
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
mysql Ver 14.14 Distrib 5.7.24
**PHP version:**
PHP 7.0.32-0ubuntu0.16.04.1
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 14.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated, a few years ago
**Where did you install Nextcloud from:**
Nextcloud website
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>

Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - audioplayer: 2.5.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.0
  - deck: 0.5.2
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - issuetemplate: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - mindmaps: 0.1.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - richdocuments: 3.1.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - socialsharing_email: 1.0.4
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - apporder
  - encryption
  - files_downloadactivity
  - files_reader
  - files_retention
  - ojsxc
  - quota_warning
  - radio
  - spreed
  - theming
  - user_external

</details>

**Nextcloud configuration:**
<details>

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.5",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/New_York",
        "installed": true,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "exm",
        "trashbin_retention_obligation": "7,14",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "ldapIgnoreNamingRules": false,
        "default_language": "fr",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "loglevel": 1,
        "updater.release.channel": "stable",
        "maintenance": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory/

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                              |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                |
| hasPagedResultSupport         |                                                                                                                                                                                  |
| homeFolderNamingRule          | attr:sAMAccountName                                                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                |
| ldapAgentName                 | CN=owncloud,OU=equipmentusers,OU=SBSUsers,OU=Users,OU=MyBusiness,DC=caserne                                                                                                      |
| ldapAgentPassword             | ***                                                                                                                                                                              |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                  |
| ldapAttributesForUserSearch   |                                                                                                                                                                                  |
| ldapBackupHost                |                                                                                                                                                                                  |
| ldapBackupPort                |                                                                                                                                                                                  |
| ldapBase                      | DC=caserne                                                                                                                                                                       |
| ldapBaseGroups                | DC=caserne                                                                                                                                                                       |
| ldapBaseUsers                 | DC=caserne                                                                                                                                                                       |
| ldapCacheTTL                  | 600                                                                                                                                                                              |
| ldapConfigurationActive       | 1                                                                                                                                                                                |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                  |
| ldapEmailAttribute            | mail                                                                                                                                                                             |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                |
| ldapExpertUUIDGroupAttr       | sAMAccountName                                                                                                                                                                   |
| ldapExpertUUIDUserAttr        | samaccountname                                                                                                                                                                   |
| ldapExpertUsernameAttr        | samaccountname                                                                                                                                                                   |
| ldapGidNumber                 | gidNumber                                                                                                                                                                        |
| ldapGroupDisplayName          | samaccountname                                                                                                                                                                   |
| ldapGroupFilter               | (|(cn=owncloud_users)(cn=BUDGETS)(cn=COMMUNICATION)(cn=MBVL)(cn=PRODUCTIONS)(cn=TECHNIQUE)(cn=R&D)(cn=budget_prod))                                                              |
| ldapGroupFilterGroups         | owncloud_users;BUDGETS;COMMUNICATION;MBVL;PRODUCTIONS;TECHNIQUE;R&D;budget_prod                                                                                                  |
| ldapGroupFilterMode           | 0                                                                                                                                                                                |
| ldapGroupFilterObjectclass    |                                                                                                                                                                                  |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                                     |
| ldapHost                      | caserne1                                                                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=owncloud_users,OU=Security Groups,OU=MyBusiness,DC=caserne)(primaryGroupID=5259))))(|(samaccountname=%uid)(|(sAMAccountName=%uid)))) |
| ldapLoginFilterAttributes     | sAMAccountName                                                                                                                                                                   |
| ldapLoginFilterEmail          | 0                                                                                                                                                                                |
| ldapLoginFilterMode           | 0                                                                                                                                                                                |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                                                                                |
| ldapOverrideMainServer        |                                                                                                                                                                                  |
| ldapPagingSize                | 500                                                                                                                                                                              |
| ldapPort                      | 389                                                                                                                                                                              |
| ldapQuotaAttribute            |                                                                                                                                                                                  |
| ldapQuotaDefault              |                                                                                                                                                                                  |
| ldapTLS                       | 0                                                                                                                                                                                |
| ldapUserAvatarRule            | default                                                                                                                                                                          |
| ldapUserDisplayName           | displayName                                                                                                                                                                      |
| ldapUserDisplayName2          |                                                                                                                                                                                  |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=owncloud_users,OU=Security Groups,OU=MyBusiness,DC=caserne)(primaryGroupID=5259))))                                                    |
| ldapUserFilterGroups          | owncloud_users                                                                                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                                                                                                |
| ldapUserFilterObjectclass     | person                                                                                                                                                                           |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                             |
| ldapUuidUserAttribute         | auto                                                                                                                                                                             |
| turnOffCertCheck              | 0                                                                                                                                                                                |
| turnOnPasswordChange          | 0                                                                                                                                                                                |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
</details>

**Comment by skjnldsv** [comment]
Have you tried flushing redis first? :thinking:

**Comment by stanelie** [comment]
Sorry, I cannot replicate the problem anymore, it's been a while and I have upgraded Nextcloud in the mean time.
You can close this ticket.
