### ISSUE TITLE
Nextcloud 15.0.1 upgrade error

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/server#13499]
```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
The current PHP memory limit is below the recommended value of 512MB.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\DAV\Migration\RemoveClassifiedEventActivity::getPrincipal() must be of the type string, null given, called in /var/www/example.tld/cloud.example.tld/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php on line 108 and defined in /var/www/example.tld/cloud.example.tld/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php:120
Stack trace:
#0 /var/www/example.tld/cloud.example.tld/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php(108): OCA\DAV\Migration\RemoveClassifiedEventActivity->getPrincipal(NULL)
#1 /var/www/example.tld/cloud.example.tld/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php(55): OCA\DAV\Migration\RemoveClassifiedEventActivity->removeConfidentialUncensoredEventActivity()
#2 /var/www/example.tld/cloud.example.tld/lib/private/Repair.php(96): OCA\DAV\Migration\RemoveClassifiedEventActivity->run(Object(OC\Repair))
#3 /var/www/example.tld/cloud.example.tld/lib/private/legacy/app.php(966): OC\Repair->run()
#4 /var/www/example.tld/cloud.example.tld/lib/private/legacy/app.php(903): OC_App::executeRepairSteps('dav', Array)
#5 /var/www/example.tld/cloud.example.tld/lib/private/Updater.php(365): OC_App::updateApp('dav')
#6 /var/www/example.tld/cloud.example.tld/lib/private/Updater.php(245): OC\Updater->doAppUpgrade()
#7 /var/www/example.tld/cloud.example.tld/lib/private/Updater.php(121): OC\Updater->doUpgrade('15.0.1.2', '15.0.0.10')
#8 /var/www/example.tld/cloud.example.tld/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#9 /var/www/example.tld/cloud.example.tld/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/example.tld/cloud.example.tld/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/example.tld/cloud.example.tld/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/example.tld/cloud.example.tld/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/example.tld/cloud.example.tld/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/example.tld/cloud.example.tld/console.php(96): OC\Console\Application->run()
#15 /var/www/example.tld/cloud.example.tld/occ(11): require_once('/var/www/magicb...')

```

### Steps to reproduce
1. upgrade from 15 to 15.0.1

### Expected behaviour
Upgrade should run proṕerly

### Actual behaviour
This error appeared.

### Server configuration

**Operating system**:
Debian 9.6

**Web server:**
nginx

**Database:**
MariaDB - 10.1.37-0+deb9u1

**PHP version:**
7.0.33-1

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded all steps until today

**Where did you install Nextcloud from:**
website

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - data_request: 1.2.0
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.9.5
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_nextcloud_notification: 1.0.2
  - twofactor_totp: 2.1.0
  - twofactor_u2f: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_rightclick
  - files_videoplayer
  - socialsharing_email
  - survey_client
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.tld",
            "www.cloud.example.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "15.0.0.10",
        "installed": true,
        "cipher": "AES-256-CFB",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "default_language": "de",
        "defaultapp": "files",
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "updater.release.channel": "stable",
        "upgrade.disable-web": false,
        "check_for_working_webdav": true,
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto",
        "activity_expire_days": 90,
        "filesystem_check_changes": 0,
        "theme": "",
        "maintenance": true,
        "singleuser": false,
        "data-fingerprint": "16b42c01070fc24c2086fb974eda1d16",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.example.tld",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "logdateformat": "d.m.Y - H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": false,
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 1,
            "port": 0,
            "timeout": 1.5
        },
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "sharing.minSearchStringLength": 3,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by edo0** [comment]
I had the very same issue, this being my output
`Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\DAV\Migration\RemoveClassifiedEventActivity::getPrincipal() must be of the type string, null given, called in /var/www/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php on line 78 and defined in /var/www/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php:120
Stack trace:
#0 /var/www/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php(78): OCA\DAV\Migration\RemoveClassifiedEventActivity->getPrincipal(NULL)
#1 /var/www/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php(54): OCA\DAV\Migration\RemoveClassifiedEventActivity->removePrivateEventActivity()
#2 /var/www/nextcloud/lib/private/Repair.php(96): OCA\DAV\Migration\RemoveClassifiedEventActivity->run(Object(OC\Repair))
#3 /var/www/nextcloud/lib/private/legacy/app.php(966): OC\Repair->run()
#4 /var/www/nextcloud/lib/private/legacy/app.php(903): OC_App::executeRepairSteps('dav', Array)
#5 /var/www/nextcloud/lib/private/Updater.php(365): OC_App::updateApp('dav')
#6 /var/www/nextcloud/lib/private/Updater.php(245): OC\Updater->doAppUpgrade()
#7 /var/www/nextcloud/lib/private/Updater.php(121): OC\Updater->doUpgrade('15.0.1.2', '15.0.0.10')
#8 /var/www/nextcloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
#15 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#16 {main}root@host:~# `

**Comment by edo0** [comment]
@mightyBroccoli Were you able to find any fix or workaround for this issue?
I am no web development expert, and am in urgent need to get my NC instance back to work.
Thanks!

**Comment by go2sh** [comment]
There might be a but in the code introduced by #13439. Maybe you could try to replace `principaluri` with `c.principaluri` in line 78 and 108. It is also backported to 14 and 13, I think. So all versions are affected.

**Comment by cunningwasabi** [comment]
updated /usr/share/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php lines 78 and 108 as mentioned...

TypeError: Argument 1 passed to OCA\DAV\Migration\RemoveClassifiedEventActivity::getPrincipal() must be of the type string, null given, called in /usr/share/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php on line 78 and defined in /usr/share/nextcloud/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php:120

**Comment by MorrisJobke** [comment]
Thanks - we are looking into it - we stopped the updater for now

**Comment by cunningwasabi** [comment]
I guess bypassing the loop at line 78 is a reasonable bandaid until we figure out what is going on?

```
                while ($row = $result->fetch()) {
                        #$delete->setParameter('owner', $this->getPrincipal($row['c.principaluri']))
                                #->setParameter('type', 'calendar')
                                #->setParameter('calendar_id', $row['calendarid'])
                                #->setParameter('event_uid', '%' . $this->connection->escapeLikeParameter('{"id":"' . $row['uid'] . '"') . '%');
                        #$deletedEvents += $delete->execute();
                }

```

**Comment by nickvergessen** [comment]
Urgh, this error basically means you have events which don't have a calendar anymore :/

**Comment by rullzer** [comment]
ah so diffeernt than what I tought
well so be it. Let me update my patch then.

**Comment by ChristophWurst** [comment]
You can find the PR here: https://github.com/nextcloud/server/pull/13503
And the patch as a quick fix to proceed with the update: https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/13503.patch

**Comment by edo0** [comment]
Forgive my ignorance, how can I apply the fix to my installation, so as to proceed with the upgrade and restore function?

**Comment by go2sh** [comment]
Download the file in #13503 and replace it.

**Comment by ChristophWurst** [comment]
Alternatively, apply the patch: https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/13503.patch

**Comment by edo0** [comment]
Thank you!!! 
Everything went smoothly

**Comment by nickvergessen** [comment]
Install 15.0.2 and run the update there. Then it should work fine

**Comment by cunningwasabi** [comment]
could do - i upgraded from 14.0.5 to 14.0.6 before running the maintenance:repair.

**Comment by cunningwasabi** [comment]
so, to recap, currently the fix is;
```
                while ($row = $result->fetch()) {
                        if ($row['principaluri'] == null) {
                                continue;
                        }

                        $delete->setParameter('owner', $this->getPrincipal($row['principaluri']))
                                ->setParameter('type', 'calendar')
                                ->setParameter('calendar_id', $row['calendarid'])
                                ->setParameter('event_uid', '%' . $this->connection->escapeLikeParameter('{"id":"' . $row['uid'] . '"') . '%');
                        $deletedEvents += $delete->execute();
                }

```

Which includes a null check. However, the followup issue occurring is where $row['principaluri'] is not actually null, but not of the form we expect.
It seems like we make a few assumptions in getPrincipal about the structure of the passed string.

```
protected function getPrincipal(string $principalUri): string {
$uri = explode('/', $principalUri);
return $uri[2];
}
```

updating this to:
```
protected function getPrincipal(string $principalUri): string {
print "PRINCIPAL URI: ".$principalUri."\n";
                $uri = explode('/', $principalUri);
print "explode0 ".$uri[0]."\n";
print "explode1 ".$uri[1]."\n";
print "explode2 ".$uri[2]."\n";
                return $uri[2];

```        

And we get the output:

```
PRINCIPAL URI: principals/myuser
explode[0] principals
explode[1] myuser
explode[2] 
```

hope this helps someone!

**Comment by nickvergessen** [comment]
Can you try replacing:
https://github.com/nextcloud/server/blob/12e24ed6e706e78190ebea1d95a7927f097003e0/apps/dav/lib/Migration/RemoveClassifiedEventActivity.php#L130
with:
```php
return array_pop($uri);
```

**Comment by cunningwasabi** [comment]
ran through as expected. no issues.
