### ISSUE TITLE
Upgrade 14.0.4 to 15.0.2 failed with an unhandled exception.

### ISSUE THREAD

**Issue by WebOscar** [nextcloud/server#13655]
The web based updater stopped with error. On the console I get this error:

```
...
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Repair\NC15\SetVcardDatabaseUID::getUID() must be of the type string, null given, called in /path/to/nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php on line 132 and defined in /path/to/nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php:87
Stack trace:
#0 /path/to/nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php(132): OC\Repair\NC15\SetVcardDatabaseUID->getUID(NULL, Object(OC\Repair))
#1 /path/to/nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php(149): OC\Repair\NC15\SetVcardDatabaseUID->repair(Object(OC\Repair))
#2 /path/to/nextcloud/lib/private/Repair.php(96): OC\Repair\NC15\SetVcardDatabaseUID->run(Object(OC\Repair))
#3 /path/to/nextcloud/lib/private/Updater.php(265): OC\Repair->run()
#4 /path/to/nextcloud/lib/private/Updater.php(121): OC\Updater->doUpgrade('15.0.2.0', '14.0.6.0')
#5 /path/to/nextcloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#6 /path/to/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/to/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /path/to/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /path/to/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /path/to/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /path/to/nextcloud/console.php(96): OC\Console\Application->run()
#12 /path/to/nextcloud/occ(11): require_once('/path/to/next...')
```

The Nextcloud Log:

```
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] request to updater
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] currentStep()
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] show HTML page
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] current version: 14.0.6 build time: 2019-01-11T15:20:19+00:00 58d94d16a6e60988274230cdb625791f3426103f
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] getUpdateServerResponse()
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] updaterServer: https://updates.nextcloud.org/updater_server/
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] releaseChannel: stable
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] internal version: 14.0.6.0
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] updateURL: https://updates.nextcloud.org/updater_server/?version=14x0x6x0xxxstablexx2019-01-11T15%3A20%3A19%2B00%3A00+58d94d16a6e60988274230cdb625791f3426103fx7x0x30
2019-01-17T16:44:43+0100 wPdoFhKeHH [info] getUpdateServerResponse response: Array
(
    [version] => 15.0.2.0
    [versionstring] => Nextcloud 15.0.2
    [url] => https://download.nextcloud.com/server/releases/nextcloud-15.0.2.zip
    [web] => https://docs.nextcloud.com/server/15/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=15.0.2
    [autoupdater] => 1
    [eol] => 0
    [signature] => jbMZKu/ICGvOnG44z6I3H996RJ5At4c0i6E4b/K6/imO/18XxRXnKVpUkImt46q0
+2PjJ8CL8v/2hbhYO1kCExeQ9HWrKn9FnkkxT4K6Q+jnq42nOv/BddDMrzAlxmAu
qCKARb652D3bfOyGx2+cSc45YxbJqQiGMm/wCnPCZLtx9RUOG5C0Lt4/vgeN8Rk2
GaBv6cn6GE9lntP4aa3YKqt67KovHeSHYIiP7MVwe0Bwiu2n6adkDLn+WmVU/Osw
dQWgfifeB/isVeb8koOmkK8rQ+M0FicrfHsCUqzh/oDap7lu7WdgRvNCiUbEwcIw
GZyAWsPsboY0Qg7I2XWssA==
)

2019-01-17T16:44:43+0100 wPdoFhKeHH [info] checkForUpdate() Array
(
    [version] => 15.0.2.0
    [versionstring] => Nextcloud 15.0.2
    [url] => https://download.nextcloud.com/server/releases/nextcloud-15.0.2.zip
    [web] => https://docs.nextcloud.com/server/15/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=15.0.2
    [autoupdater] => 1
    [eol] => 0
    [signature] => jbMZKu/ICGvOnG44z6I3H996RJ5At4c0i6E4b/K6/imO/18XxRXnKVpUkImt46q0
+2PjJ8CL8v/2hbhYO1kCExeQ9HWrKn9FnkkxT4K6Q+jnq42nOv/BddDMrzAlxmAu
qCKARb652D3bfOyGx2+cSc45YxbJqQiGMm/wCnPCZLtx9RUOG5C0Lt4/vgeN8Rk2
GaBv6cn6GE9lntP4aa3YKqt67KovHeSHYIiP7MVwe0Bwiu2n6adkDLn+WmVU/Osw
dQWgfifeB/isVeb8koOmkK8rQ+M0FicrfHsCUqzh/oDap7lu7WdgRvNCiUbEwcIw
GZyAWsPsboY0Qg7I2XWssA==
)

2019-01-17T16:44:43+0100 wPdoFhKeHH [info] end of checkForUpdate() Update to Nextcloud 15.0.2 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://dow
nload.nextcloud.com/server/releases/nextcloud-15.0.2.zip</code>
2019-01-17T16:44:48+0100 MeymGVF1zU [info] request to updater
2019-01-17T16:44:48+0100 MeymGVF1zU [info] currentStep()
2019-01-17T16:44:48+0100 MeymGVF1zU [info] POST request for step "1"
2019-01-17T16:44:48+0100 MeymGVF1zU [info] startStep("1")
2019-01-17T16:44:48+0100 MeymGVF1zU [info] checkForExpectedFilesAndFolders()
2019-01-17T16:44:48+0100 MeymGVF1zU [info] end of checkForExpectedFilesAndFolders()
2019-01-17T16:44:48+0100 MeymGVF1zU [info] endStep("1")
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] request to updater
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] currentStep()
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] Step 1 is in state "end".
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] POST request for step "2"
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] startStep("2")
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] checkWritePermissions()
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] end of checkWritePermissions()
2019-01-17T16:44:48+0100 y3dFBXGA49 [info] endStep("2")
2019-01-17T16:44:48+0100 5AZjZEAKTh [info] request to updater
2019-01-17T16:44:48+0100 5AZjZEAKTh [info] currentStep()
2019-01-17T16:44:48+0100 5AZjZEAKTh [info] Step 2 is in state "end".
2019-01-17T16:44:48+0100 5AZjZEAKTh [info] POST request for step "3"
2019-01-17T16:44:48+0100 5AZjZEAKTh [info] startStep("3")
2019-01-17T16:44:48+0100 5AZjZEAKTh [info] createBackup()
2019-01-17T16:44:54+0100 5AZjZEAKTh [info] end of createBackup()
2019-01-17T16:44:54+0100 5AZjZEAKTh [info] endStep("3")
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] request to updater
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] currentStep()
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] Step 3 is in state "end".
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] POST request for step "4"
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] startStep("4")
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] downloadUpdate()
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] getUpdateServerResponse()
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] updaterServer: https://updates.nextcloud.org/updater_server/
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] releaseChannel: stable
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] internal version: 14.0.6.0
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] updateURL: https://updates.nextcloud.org/updater_server/?version=14x0x6x0xxxstablexx2019-01-11T15%3A20%3A19%2B00%3A00+58d94d16a6e60988274230cdb625791f3426103fx7x0x30
2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] getUpdateServerResponse response: Array
(
    [version] => 15.0.2.0
    [versionstring] => Nextcloud 15.0.2
    [url] => https://download.nextcloud.com/server/releases/nextcloud-15.0.2.zip
    [web] => https://docs.nextcloud.com/server/15/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=15.0.2
    [autoupdater] => 1
    [eol] => 0
    [signature] => jbMZKu/ICGvOnG44z6I3H996RJ5At4c0i6E4b/K6/imO/18XxRXnKVpUkImt46q0
+2PjJ8CL8v/2hbhYO1kCExeQ9HWrKn9FnkkxT4K6Q+jnq42nOv/BddDMrzAlxmAu
qCKARb652D3bfOyGx2+cSc45YxbJqQiGMm/wCnPCZLtx9RUOG5C0Lt4/vgeN8Rk2
GaBv6cn6GE9lntP4aa3YKqt67KovHeSHYIiP7MVwe0Bwiu2n6adkDLn+WmVU/Osw
dQWgfifeB/isVeb8koOmkK8rQ+M0FicrfHsCUqzh/oDap7lu7WdgRvNCiUbEwcIw
GZyAWsPsboY0Qg7I2XWssA==
)

2019-01-17T16:44:54+0100 rFwZ1dVHeu [info] storage location exists
2019-01-17T16:44:55+0100 rFwZ1dVHeu [info] end of downloadUpdate()
2019-01-17T16:44:55+0100 rFwZ1dVHeu [info] endStep("4")
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] request to updater
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] currentStep()
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] Step 4 is in state "end".
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] POST request for step "5"
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] startStep("5")
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] verifyIntegrity()
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] getUpdateServerResponse()
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] updaterServer: https://updates.nextcloud.org/updater_server/
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] releaseChannel: stable
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] internal version: 14.0.6.0
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] updateURL: https://updates.nextcloud.org/updater_server/?version=14x0x6x0xxxstablexx2019-01-11T15%3A20%3A19%2B00%3A00+58d94d16a6e60988274230cdb625791f3426103fx7x0x30
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] getUpdateServerResponse response: Array
(
    [version] => 15.0.2.0
    [versionstring] => Nextcloud 15.0.2
    [url] => https://download.nextcloud.com/server/releases/nextcloud-15.0.2.zip
    [web] => https://docs.nextcloud.com/server/15/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=15.0.2
    [autoupdater] => 1
    [eol] => 0
    [signature] => jbMZKu/ICGvOnG44z6I3H996RJ5At4c0i6E4b/K6/imO/18XxRXnKVpUkImt46q0
+2PjJ8CL8v/2hbhYO1kCExeQ9HWrKn9FnkkxT4K6Q+jnq42nOv/BddDMrzAlxmAu
qCKARb652D3bfOyGx2+cSc45YxbJqQiGMm/wCnPCZLtx9RUOG5C0Lt4/vgeN8Rk2
GaBv6cn6GE9lntP4aa3YKqt67KovHeSHYIiP7MVwe0Bwiu2n6adkDLn+WmVU/Osw
dQWgfifeB/isVeb8koOmkK8rQ+M0FicrfHsCUqzh/oDap7lu7WdgRvNCiUbEwcIw
GZyAWsPsboY0Qg7I2XWssA==
)

2019-01-17T16:44:55+0100 BNyPsaN8KR [info] storage location: /path/to/nextcloud/data/updater-ocd348d22b57/downloads/
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] end of verifyIntegrity()
2019-01-17T16:44:55+0100 BNyPsaN8KR [info] endStep("5")
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] request to updater
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] currentStep()
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] Step 5 is in state "end".
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] POST request for step "6"
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] startStep("6")
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] extractDownload()
2019-01-17T16:44:55+0100 iPri8rXJbQ [info] storage location: /path/to/nextcloud/data/updater-ocd348d22b57/downloads/
2019-01-17T16:45:00+0100 iPri8rXJbQ [info] end of extractDownload()
2019-01-17T16:45:00+0100 iPri8rXJbQ [info] endStep("6")
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] request to updater
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] currentStep()
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] Step 6 is in state "end".
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] POST request for step "7"
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] startStep("7")
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] setMaintenanceMode("true")
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] configFileName /path/to/nextcloud/updater/../config/config.php
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] end of setMaintenanceMode()
2019-01-17T16:45:00+0100 1CwxCyKyfZ [info] endStep("7")
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] request to updater
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] currentStep()
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] Step 7 is in state "end".
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] POST request for step "8"
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] startStep("8")
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replaceEntryPoints()
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replace index.php
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replace status.php
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replace remote.php
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replace public.php
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replace ocs/v1.php
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] replace ocs/v2.php
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] end of replaceEntryPoints()
2019-01-17T16:45:00+0100 3RMBGfLtnw [info] endStep("8")
2019-01-17T16:45:00+0100 lGmMYveVep [info] request to updater
2019-01-17T16:45:00+0100 lGmMYveVep [info] currentStep()
2019-01-17T16:45:00+0100 lGmMYveVep [info] Step 8 is in state "end".
2019-01-17T16:45:00+0100 lGmMYveVep [info] POST request for step "9"
2019-01-17T16:45:00+0100 lGmMYveVep [info] startStep("9")
2019-01-17T16:45:00+0100 lGmMYveVep [info] deleteOldFiles()
2019-01-17T16:45:00+0100 lGmMYveVep [info] config sample exists
2019-01-17T16:45:00+0100 lGmMYveVep [info] themes README exists
2019-01-17T16:45:03+0100 lGmMYveVep [info] end of deleteOldFiles()
2019-01-17T16:45:03+0100 lGmMYveVep [info] endStep("9")
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] request to updater
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] currentStep()
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] Step 9 is in state "end".
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] POST request for step "10"
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] startStep("10")
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] moveNewVersionInPlace()
2019-01-17T16:45:03+0100 Mg2iNFRyd6 [info] storage location: /path/to/nextcloud/data/updater-ocd348d22b57/downloads/nextcloud/
2019-01-17T16:45:04+0100 Mg2iNFRyd6 [info] end of moveNewVersionInPlace()
2019-01-17T16:45:04+0100 Mg2iNFRyd6 [info] endStep("10")
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] request to updater
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] currentStep()
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] Step 10 is in state "end".
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] POST request for step "11"
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] startStep("11")
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] setMaintenanceMode("false")
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] configFileName /path/to/nextcloud/updater/../config/config.php
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] end of setMaintenanceMode()
2019-01-17T16:47:59+0100 gbaF5sOVqQ [info] endStep("11")
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] request to updater
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] currentStep()
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] Step 11 is in state "end".
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] POST request for step "12"
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] startStep("12")
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] finalize()
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] storage location: /path/to/nextcloud/data/updater-ocd348d22b57/downloads/nextcloud/
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] call opcache_reset()
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] end of finalize()
2019-01-17T16:47:59+0100 C6SpSr5Gxx [info] endStep("12")
```

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
