### ISSUE TITLE
Files app failed after sharing file: "Call to a member function getCache() on null"

### ISSUE THREAD

**Issue by ntinti** [nextcloud/server#13719]
Hi

We have a strange behaviour in Nextcloud 15 and before 14 also. Under unexplained circumstances sharing a file crashes the whole file app with "**Error: Call to a member function getCache() on null"**. Files can't be reached with the file manager from that point on. Only searching a file helps to get it.

After deleting the entries with the "item_source" id "25167" and "26819" (see log below) from table "oc_share" the file manager works again.

Here is the log:

```
sudo -u cloudsrv php ./occ files:scan user.name
Starting scan for user 1 out of 1 (user.name)
An unhandled exception has been thrown:
Error: Call to a member function getCache() on null in cloud/apps/files_sharing/lib/SharedStorage.php:113

Stack trace:
#0 cloud/apps/files_sharing/lib/SharedStorage.php(382): OCA\Files_Sharing\SharedStorage->getSourceRootInfo()
#1 cloud/lib/private/Files/Storage/Wrapper/Wrapper.php(393): OCA\Files_Sharing\SharedStorage->getCache('', Object(OCA\Files_Trashbin\Storage))
#2 cloud/lib/private/Files/View.php(1715): OC\Files\Storage\Wrapper\Wrapper->getCache()
#3 **cloud/apps/files_sharing/lib/SharedStorage.php(128): OC\Files\View->getPath(26819)**
#4 cloud/apps/files_sharing/lib/SharedStorage.php(112): OCA\Files_Sharing\SharedStorage->init()
#5 cloud/apps/files_sharing/lib/SharedStorage.php(382): OCA\Files_Sharing\SharedStorage->getSourceRootInfo()
#6 cloud/lib/private/Files/Storage/Wrapper/Wrapper.php(393): OCA\Files_Sharing\SharedStorage->getCache('', Object(OCA\Files_Trashbin\Storage))
#7 cloud/lib/private/Files/View.php(1715): OC\Files\Storage\Wrapper\Wrapper->getCache()
#8 **cloud/apps/files_sharing/lib/SharedStorage.php(128): OC\Files\View->getPath(25167)**
#9 cloud/apps/files_sharing/lib/SharedStorage.php(482): OCA\Files_Sharing\SharedStorage->init()
#10 cloud/lib/private/Files/Storage/Wrapper/Wrapper.php(495): OCA\Files_Sharing\SharedStorage->getWrapperStorage()
#11 cloud/apps/files_sharing/lib/SharedStorage.php(166): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('OC\\Files\\Storag...')
#12 cloud/lib/private/Files/Storage/Wrapper/Wrapper.php(495): OCA\Files_Sharing\SharedStorage->instanceOfStorage('OC\\Files\\Storag...')
#13 cloud/lib/private/Files/Utils/Scanner.php(200): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('OC\\Files\\Storag...')
#14 cloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/user.name...', true, NULL)
#15 cloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('user.name', '/alexander.ruof...', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#16 cloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 cloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 cloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 cloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 cloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 cloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 cloud/console.php(96): OC\Console\Application->run()
#23 cloud/occ(11): require_once('/usr/local/www/...')

```

Maybe "SharedStorage.php" has a similar problem as "cache.php" had (https://github.com/nextcloud/server/issues/10316) ?

### Server configuration

**Operating system**: FreeBSD 11.2
**Web server:** Nginx
**Database:** PostgreSQL
**PHP version:** 7.2
**Nextcloud version:** 15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 14
**Where did you install Nextcloud from:** FreeBSD Package

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - bookmarks: 0.16.0
  - calendar: 1.6.4
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.2
  - dav: 1.8.1
  - deck: 0.5.2
  - drop_account: 0.0.13
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_fulltextsearch: 1.2.3
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.3
  - fulltextsearch_elasticsearch: 1.2.2
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - passwords: 2019.1.0
  - polls: 0.9.5
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - richdocuments: 3.1.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - spreed: 5.0.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - announcementcenter
  - encryption
  - files_external
  - survey_client
  - user_ldap
</details>

**Comment by McAviti** [comment]
Thanx @ntinti - had the same issue today and could solve it with your help.

Nextcloud
Version: 15.0.2.0
Installierte Apps: 44
Apps mit verfügbaren Aktualisierungen: 0

PHP
Version: 7.2.10
Arbeitspeicher-Grenzwert: 512 MB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 511 MB

Datenbank
Art: pgsql
Version: PostgreSQL 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit
Größe: 77,5 MB

**Comment by ntinti** [comment]
Fine. But error persist. Another phenomena we have with 

`"Error: Call to a member function getCache() on null in cloud/apps/files_sharing/lib/SharedStorage.php:113"`

is the circumstance that a user with that error can not copy or move a folder with its content to another folder. It's very strange and begins to make the user angry.
Maybe the content that is shared, always comes from group folder. Or have a german umlaut. We have to observe it. But it would be great a developer can have a look at "SharedStorage.php" line 113 and what could be wrong with it.
Or does the Postgre database has a buggy table? McAviti has a PG backend too. ... ?

**Comment by McAviti** [comment]
I can at least confirm that a file share in talk happened shortly before this cache problem occured. The file in the oc_share folder was a different one though. (Shared already months ago, but "nomally" via web interface.)

**Comment by ntinti** [comment]
We make more tests - it seems that sharing content from a groupfolder within the talk app space can damage the file manager.
Please, Please Please ! can mind someone

**Comment by cremfert** [comment]
We have the same issue! Please find a solution, it's breaking our whole installation.

**Comment by ntinti** [comment]
@cremfert : What version do you use? I've updated to 15.04 and can't trigger the behaviour anymore. But maybe it's a coincidence.
As a workaround, make a file scan on the terminal and have a look to the IDs after "getPath" and delete this entries in the "oc_share" table.

**Comment by ntinti** [comment]
@cremfert : Do you also share to talk groups ore user? Have a look at https://github.com/nextcloud/spreed/issues/1521

**Comment by ntinti** [comment]
@cremfert Also have a look to https://github.com/nextcloud/spreed/issues/1521

**Comment by cremfert** [comment]
I can confirm that I solved the issues bei Updating to NC 15.04! Thanks a lot!

**Comment by FahrJo** [comment]
I had the same Issue in NC15.05!
After deleting the two entries from table "oc_share" the file manager works again. :-/

**Comment by ldesgrange** [comment]
Hi, I'm running NC15.0.5 and started to use Talk 2 weeks ago. I got this issue twice in the past 2 weeks (never had it before). Deleting entries from oc_share temporarily solve the issue.

**Comment by McAviti** [comment]
We just re-had this issue again, Version 15.0.7

**Comment by ldesgrange** [comment]
Same with Version 16.0.0.

**Comment by stephanosio** [comment]
Same with version 16.0.1. This happened after sharing content from a group folder in the Talk app. Temporarily fixed it by deleting the last oc_share entry.

**Comment by tjareson** [comment]
Had this issue today with nextcloud 18.0.1. Someone shared in a 1:1 conversation a file with me which was in a shared folder. Afterwards I was not able to see my files root directory anymore. 
Deleting the respective (in this case last) record in oc_share table solved the symptom.

**Comment by skjnldsv** [comment]
Thanks!
Please share your logs folks!

**Comment by audelor20** [comment]
> Had this issue today with nextcloud 18.0.1. Someone shared in a 1:1 conversation a file with me which was in a shared folder. Afterwards I was not able to see my files root directory anymore.
> 
> It looks like that the file in the shared folder was deleted, after it was shared in the Talk chat with me. Probably that let to the issue. I will try to reproduce it.

Same problem here with nextcloud 18.0.3
A user shared in a group talk a file stored in a group folder. 
Every time this file is deleted, all users of the group talk can't access the root directory anymore. Restored the file solve the problem.

Error log below :
```
[remote] Error: Error: Call to a member function getCache() on null at <<closure>>

 0. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 382
    OCA\Files_Sharing\SharedStorage->getSourceRootInfo()
 1. /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 393
    OCA\Files_Sharing\SharedStorage->getCache("", OCA\Files_Trashb ... l})
 2. /var/www/html/nextcloud/lib/private/Files/View.php line 1741
    OC\Files\Storage\Wrapper\Wrapper->getCache()
 3. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 128
    OC\Files\View->getPath(2383)
 4. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 112
    OCA\Files_Sharing\SharedStorage->init()
 5. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 382
    OCA\Files_Sharing\SharedStorage->getSourceRootInfo()
 6. /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 393
    OCA\Files_Sharing\SharedStorage->getCache("", OCA\Files_Trashb ... l})
 7. /var/www/html/nextcloud/lib/private/Files/View.php line 1741
    OC\Files\Storage\Wrapper\Wrapper->getCache()
 8. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 128
    OC\Files\View->getPath(48394)
 9. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 112
    OCA\Files_Sharing\SharedStorage->init()
10. /var/www/html/nextcloud/apps/files_sharing/lib/SharedStorage.php line 382
    OCA\Files_Sharing\SharedStorage->getSourceRootInfo()
11. /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 393
    OCA\Files_Sharing\SharedStorage->getCache("", OCA\Files_Trashb ... l})
12. /var/www/html/nextcloud/lib/private/Files/View.php line 1478
    OC\Files\Storage\Wrapper\Wrapper->getCache("")
13. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 265
    OC\Files\View->getDirectoryContent("/")
14. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/TagsPlugin.php line 227
    OCA\DAV\Connector\Sabre\Directory->getChildren()
15. <<closure>>
    OCA\DAV\Connector\Sabre\TagsPlugin->handleGetProperties(Sabre\DAV\PropFind {}, OCA\DAV\Files\FilesHome {})
16. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\Connect ... "], [Sabre\DAV\PropF ... }])
17. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
18. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\Files\FilesHome {})
19. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/a.dauce", ["{DAV:}getlastm ... "], 1)
20. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
21. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
22. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
23. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
24. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
25. /var/www/html/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
26. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
27. /var/www/html/nextcloud/remote.php line 165
    require_once("/var/www/html/n ... p")
```

**Comment by skjnldsv** [comment]
cc @icewind1991 for trashbin?

**Comment by manu-p** [comment]
Just faced the same issue today. 
NC 18.0.4
MySQL 5.7.30
Apache 2.4.29
PHP 7.4.6

Had to delete entries in oc_share to solve the issue.

Can provide more information if explicitly mentioned.
