### ISSUE TITLE
Issue while using occ with files:scan --all on nextcloud 15.0.2.0

### ISSUE THREAD

**Issue by offlinehoster** [nextcloud/server#13977]
### Steps to reproduce
1. php occ files:scan --all   (as user who runs nginx/php)

### Expected behaviour
Should work without any issues.

### Actual behaviour
It starts scanning and by user 21 of 184 there is an error.

```
Starting scan for user 1 out of 184 (01a04dda-36bb-1035-958c-dfac790e4d56)
Starting scan for user 2 out of 184 (02d9786e-594f-1035-86c7-298a5c04cd22)
…
Starting scan for user 21 out of 184 (2d22a818-e43b-1034-956c-dfac790e4d56)
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\OCS\DiscoveryService::discover() must be of the type string, null given, called in /mnt/data/owncloud/apps/files_sharing/lib/External/Manager.php on line 382 and defined in /mnt/data/owncloud/lib/private/OCS/DiscoveryService.php:65
Stack trace:
#0 /mnt/data/owncloud/apps/files_sharing/lib/External/Manager.php(382): OC\OCS\DiscoveryService->discover(NULL, 'FEDERATED_SHARI...')
#1 /mnt/data/owncloud/apps/files_sharing/lib/External/Manager.php(527): OCA\Files_Sharing\External\Manager->sendFeedbackToRemote(NULL, NULL, NULL, 'decline')
#2 /mnt/data/owncloud/apps/files_sharing/lib/External/Storage.php(217): OCA\Files_Sharing\External\Manager->removeShare('18-e43b-1034-95...')
#3 [internal function]: OCA\Files_Sharing\External\Storage->checkStorageAvailability()
#4 /mnt/data/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)
#5 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
#6 /mnt/data/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)
#7 /mnt/data/owncloud/apps/files_sharing/lib/External/Scanner.php(89): OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
#8 /mnt/data/owncloud/apps/files_sharing/lib/External/Scanner.php(44): OCA\Files_Sharing\External\Scanner->scanAll()
#9 /mnt/data/owncloud/lib/private/Files/Utils/Scanner.php(245): OCA\Files_Sharing\External\Scanner->scan('', true, 3)
#10 /mnt/data/owncloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/2d22a818-e43b-...', true, NULL)
#11 /mnt/data/owncloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('2d22a818-e43b-1...', '/2d22a818-e43b-...', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#12 /mnt/data/owncloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /mnt/data/owncloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /mnt/data/owncloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /mnt/data/owncloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /mnt/data/owncloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /mnt/data/owncloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /mnt/data/owncloud/console.php(96): OC\Console\Application->run()
#19 /mnt/data/owncloud/occ(11): require_once('/mnt/data/owncl...')

```

### Server configuration

- Ubuntu 18.04 LTS
- nginx/1.15.
- mysql-common                          5.8+1.0.4
- PHP 7.2
- Nextcloud version: 15.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded all the way from owncloud 8.2.7 to the latest nextcloud 15.0.2.0
**Where did you install Nextcloud from:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
```
Enabled:
  - accessibility: 1.1.0
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - activity
  - encryption
```

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "15.0.2.0",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/mnt\/data\/owncloud\/data\/owncloud.log",
        "loglevel": 0,
        "cron_log": true,
        "log_rotate_size": 104857600,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "trusted_domains": [
            "cloud.domain.com"
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "updater.release.channel": "stable"
    }
}

```
</details>

**Are you using external storage
- no external storage

**Are you using encryption:**
- no

**Are you using an external user-backend, if yes which one:** 
- LDAP

**Comment by bjoernv** [comment]
I have this bug still in NC 15.0.4. The NC 15.0.4 instance is connected with a federation member (NC 14.0.7).

**Comment by phaus** [comment]
You could try to do a select in table `oc_share_external` and see if there is an empty `remote` Column for that specific `user` UUID.

**Comment by kesselb** [comment]
Still happening? I think we fixed some issues (but not all :disappointed:) with offline or misbehaving federated shares.
