### ISSUE TITLE
sabre dav exception "This is not supposed to happen"

### ISSUE THREAD

**Issue by maybeec** [nextcloud/server#1439]
### Steps to reproduce
1. Synchronize Contancts on Android with DAVdroid
### Expected behaviour

Basically, no logs like this :)
I could not identify any bad behavior so far. But perhaps I was not able to find any missing properties in my contacts so far. I have to keep eyes open in future for any odd behavior.

I do not mind, if this is not considered as a bug until there is an odd behavior. However, I have also found this discussion: https://forum.owncloud.org/viewtopic.php?t=36953
It seems to be something worse to be observed, especially, as there is unintended code running as shown in the error message.
### Actual behaviour

An exception is logged in nextcloud:

``` json
Exception: {
    "Message": "This is not supposed to happen",
    "Exception": "LogicException",
    "Code": 0,
    "Trace": "#0 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(159): OCA\\DAV\\CardDAV\\Plugin->getAddressbookHomeForPrincipal('principals\/grou...')
              #1 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropFind.php(98): Sabre\\CardDAV\\Plugin->Sabre\\CardDAV\\{closure}()
              #2 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(160): Sabre\\DAV\\PropFind->handle('{urn:ietf:param...', Object(Closure))
              #3 [internal function]: Sabre\\CardDAV\\Plugin->propFindEarly(Object(Sabre\\DAV\\PropFind), Object(Sabre\\CalDAV\\Principal\\User))
              #4 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
              #5 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(999): Sabre\\Event\\EventEmitter->emit('propFind', Array)
              #6 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(919): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(Sabre\\CalDAV\\Principal\\User))
              #7 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(334): Sabre\\DAV\\Server->getPropertiesForPath('principals\/grou...', Array, 0)
              #8 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
              #9 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
              #10 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)
              #11 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
              #12 \/var\/www\/nextcloud\/apps\/dav\/lib\/server.php(148): Sabre\\DAV\\Server->exec()
              #13 \/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()
              #14 \/var\/www\/nextcloud\/remote.php(138): require_once('\/var\/www\/nextcl...')
              #15 {main}",
    "File": "\/var\/www\/nextcloud\/apps\/dav\/lib\/carddav\/plugin.php",
    "Line": 54,
    "User": "XXX"
}
```
### Server configuration

**Operating system**:
Ubuntu 14.04.5

**Web server:**
Apache/2.4.7

**Database:**
MySQL 5.5.52

**PHP version:**
5.5.9-1ubuntu4.19

**Nextcloud version:** (see Nextcloud admin page)
9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from ownCloud 2.4.7

**Where did you install Nextcloud from:**
Downloaded from https://download.nextcloud.com/server/releases/

**Signing status:**
`Integrity checker has been disabled. Integrity cannot be verified.`

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.3.3
  - comments: 0.2
  - contacts: 1.4.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
  - user_saml

```

**The content of config/config.php:**

``` json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/home\/nextcloud",
        "dbtype": "mysql",
        "version": "9.0.53.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "php",
        "mail_smtpauth": 1,
        "mail_from_address": "no-reply.nextcloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "loglevel": 3,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "production"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### Nextcloud log (data/nextcloud.log)

see above.

**Comment by MorrisJobke** [comment]
Do you still see this with 11.0.3? We updated the underlying library and as far as I know this should™ not happen anymore. Please report back if this still happens in 11. Thanks
