### ISSUE TITLE
dbpassword config value keeps updating to an incorrect value

### ISSUE THREAD

**Issue by nero120** [nextcloud/server#14396]
### Steps to reproduce
Every time a config change is made to nextcloud (e.g. nextcloud is updated), the `dbpassword` config value is changed to an incorrect salted value that causes database connection errors. In order to fix this I have to edit config.php and insert the plain text database user account password.

### Server configuration

**Operating system:** Raspbian GNU/Linux 9 (stretch)

**Web server:** Apache/2.4.25 (Raspbian)

**Database:** 10.1.37-MariaDB-0+deb9u1 Raspbian 9.0

**PHP version:** 7.2

**Nextcloud version:** 15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloudpi

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - admin_notifications
  - comments
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - nextcloudpi
  - password_policy
  - systemtags
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.1.5",
            "nero120.cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nero120.cloud\/",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "loglevel": 0,
        "log_type": "file",
        "maintenance": false,
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "updater.release.channel": "stable",
        "logfile": "\/media\/data\/ncdata\/nextcloud.log",
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sat Feb 23 21:00:18.764560 2019] [php7:error] [pid 1067] [client 51.52.161.75:64607] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'ncadmin'@'localhost' (using password: YES) in /var/www/nextcloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(D in /var/www/nextcloud/lib/private/DB/Connection.php on line 64
```
</details>

**Comment by skjnldsv** [comment]
Hum, I cannot reproduce the issue at all.
My guess is something wrong happened during one of your previous upgrade and somehow broke this.

a temporary fix would be to create a db.config.php file with the dbpassword php config array key and the appropriate data into it.
It will automatically overwrite the config.php values.
``` php
<?php
$CONFIG = array (
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxxxxxxxxxxx',
);
```

**Comment by nero120** [comment]
Thanks @skjnldsv but this can be closed, I moved to NCP on docker and this is no longer an issue. I suspect it was originally caused by a failed upgrade at some point in the past.

**Comment by skjnldsv** [comment]
Hum, after digging, we do not salt the dbpassword.
Though if you use a root user we will create our own db user and a dedicated password. Therefore it will change.

For anyone seeing this, we do NOT salt the password. :)
