### ISSUE TITLE
404 on /remote.php/dav/addressbooks/admin/ on fresh install

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#14483]
Tried it multiple times, I always get a 404 on fresh install of nc16.

## to reproduce:
1. fresh install master with sqlite
2. install contacts
3. open the devtools
4. go to the contacts app
5. cry

@rullzer @MorrisJobke @georgehrke :woman_shrugging: 
Can anyone reproduce?

``` json
{
  "reqId": "T51jTxNlnaUun9quFSX4",
  "level": 3,
  "time": "2019-03-03T10:06:00+00:00",
  "remoteAddr": "172.21.0.1",
  "user": "admin",
  "app": "PHP",
  "method": "PROPFIND",
  "url": "/remote.php/dav/addressbooks/admin/",
  "message": "Uncaught Sabre\\DAV\\Exception\\NotFound: File not found: admin in 'addressbooks' in /var/www/html/3rdparty/sabre/dav/lib/DAV/SimpleCollection.php:91
    Stack trace:
    #0 /var/www/html/3rdparty/sabre/dav/lib/DAV/Collection.php(54): Sabre\\DAV\\SimpleCollection->getChild('admin')
    #1 /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php(105): Sabre\\DAV\\Collection->childExists('admin')
    #2 /var/www/html/3rdparty/sabre/dav/lib/DAVACL/Plugin.php(878): Sabre\\DAV\\Tree->nodeExists('addressbooks/ad...')
    #3 /var/www/html/apps/dav/lib/Connector/Sabre/DavAclPlugin.php(95): Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
    #4 [internal function]: OCA\\DAV\\Connector\\Sabre\\DavAclPlugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
    #5 /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
    #6 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(466): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)
    #7 /var/www/html/3rdparty/sa at /var/www/html/3rdparty/sabre/dav/lib/DAV/SimpleCollection.php#91",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
  "version": "16.0.0.1"
}
```

**Comment by skjnldsv** [comment]
It might be an issue on the cdav-library @georgehrke.
`/remote.php/dav/addressbooks/users/admin/` seems to be correct, not `/remote.php/dav/addressbooks/admin/`, was there a shortcut that got removed?

**Comment by georgehrke** [comment]
@skjnldsv Can you please check the request the PropFind request to the principal uri? 

Maybe the reported addressbook home is wrong

**Comment by skjnldsv** [comment]
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:cs="http://calendarserver.org/ns/" xmlns:nc="http://nextcloud.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
	<d:response>
		<d:href>/remote.php/dav/principals/users/admin/</d:href>
		<d:propstat>
			<d:prop>
				<d:displayname>admin</d:displayname>
				<cal:calendar-user-type>INDIVIDUAL</cal:calendar-user-type>
				<cal:calendar-user-address-set>
					<d:href>/remote.php/dav/principals/users/admin/</d:href>
				</cal:calendar-user-address-set>
				<d:principal-URL>
					<d:href>/remote.php/dav/principals/users/admin/</d:href>
				</d:principal-URL>
				<d:alternate-URI-set />
				<card:addressbook-home-set>
					<d:href>/remote.php/dav/addressbooks/admin/</d:href>
				</card:addressbook-home-set>
				<d:principal-collection-set>
					<d:href>/remote.php/dav/principals/users/</d:href>
					<d:href>/remote.php/dav/principals/groups/</d:href>
					<d:href>/remote.php/dav/principals/calendar-resources/</d:href>
					<d:href>/remote.php/dav/principals/calendar-rooms/</d:href>
				</d:principal-collection-set>
				<d:supported-report-set>
					<d:supported-report>
						<d:report>
							<d:expand-property />
						</d:report>
					</d:supported-report>
					<d:supported-report>
						<d:report>
							<d:principal-match />
						</d:report>
					</d:supported-report>
					<d:supported-report>
						<d:report>
							<d:principal-property-search />
						</d:report>
					</d:supported-report>
					<d:supported-report>
						<d:report>
							<d:principal-search-property-set />
						</d:report>
					</d:supported-report>
					<d:supported-report>
						<d:report>
							<oc:filter-comments />
						</d:report>
					</d:supported-report>
					<d:supported-report>
						<d:report>
							<oc:filter-files />
						</d:report>
					</d:supported-report>
				</d:supported-report-set>
			</d:prop>
			<d:status>HTTP/1.1 200 OK</d:status>
		</d:propstat>
		<d:propstat>
			<d:prop>
				<s:email-address />
			</d:prop>
			<d:status>HTTP/1.1 404 Not Found</d:status>
		</d:propstat>
	</d:response>
</d:multistatus>
```

**Comment by georgehrke** [comment]
> `<d:href>/remote.php/dav/addressbooks/admin/</d:href>`

Indeed. 
https://github.com/nextcloud/server/blob/cfb2098e5cdf9d6c31136179122fa58b2e21a73d/apps/dav/lib/CardDAV/Plugin.php#L47 is still correct though.

My only idea would be to do a `git bisect` to find the faulty commit.

**Comment by skjnldsv** [comment]
cea53d0a07843ccddad9a6bf4c984617435c9409 broke it apparently! This is all @skjnldsv's fault!!

No idea why though, my code doesn't make sense with this issue :(
https://github.com/nextcloud/server/pull/14389

**Comment by georgehrke** [comment]
The answer is fairly easy 😉 

You class is extending `\Sabre\CardDAV\Plugin`, but it's supposed to extend `DAV\ServerPlugin`.
By extending `\Sabre\CardDAV\Plugin` and adding it as a plugin to the sabre server, you replacing our `OCA\DAV\CardDAV\Plugin` with your `OCA\DAV\CardDAV\HasPhotoPlugin`

**Comment by skjnldsv** [comment]
@georgehrke thanks!!

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/14488

**Comment by Quix0r** [comment]
Uff, Nextcloud 16. With latest 24.0.0.6 I'm having this error back:
````
URL:
https://host/remote.php/dav/addressbooks/groups/admin/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: groups in 'addressbooks'</s:message>
</d:error>
````

**Comment by Quix0r** [comment]
Oh, a restart of Thunderbird (TBSync 3.0.2) has "magically" fixed it ...
