### ISSUE TITLE
StackTrace when trying to use occ commands

### ISSUE THREAD

**Issue by AWegnerGitHub** [nextcloud/server#14511]
### Steps to reproduce
1. Visit page to update server to 15.0.5 (Currently on 15.0.2)
2. Be presented with a list of warnings for things that need to be fixed
3. Attempt to follow the directions.

Warning 1: 

```
Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.

    activity.activity_id
    activity.object_id
    activity_mq.mail_id
    filecache.fileid
    filecache.storage
    filecache.parent
    filecache.mimetype
    filecache.mimepart
    filecache.mtime
    filecache.storage_mtime
    mimetypes.id
    storages.numeric_id
```

Result of command:

```
/var/www/html/nextcloud$ sudo -u www-data php occ db:convert-filecache-bigint
An unhandled exception has been thrown:
Error: Call to undefined function OC\App\simplexml_load_file() in /var/www/html/nextcloud/lib/private/App/InfoParser.php:64
Stack trace:
#0 /var/www/html/nextcloud/lib/private/App/AppManager.php(380): OC\App\InfoParser->parse('/var/www/html/n...')
#1 /var/www/html/nextcloud/lib/private/legacy/app.php(551): OC\App\AppManager->getAppInfo('files', false, NULL)
#2 /var/www/html/nextcloud/lib/private/AppFramework/App.php(65): OC_App::getAppInfo('files')
#3 /var/www/html/nextcloud/lib/private/legacy/app.php(236): OC\AppFramework\App::buildAppNamespace('files')
#4 /var/www/html/nextcloud/lib/private/legacy/app.php(119): OC_App::registerAutoloading('files', '/var/www/html/n...')
#5 /var/www/html/nextcloud/lib/base.php(654): OC_App::loadApps(Array)
#6 /var/www/html/nextcloud/lib/base.php(1068): OC::init()
#7 /var/www/html/nextcloud/console.php(46): require_once('/var/www/html/n...')
#8 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#9 {main}
```

### Expected behaviour
No stack trace would occur. 

### Actual behaviour
Stack Trace (above) occurs. 

### Server configuration

**Operating system**: Ubuntu 18.04.2

**Web server:** Server version: Apache/2.4.29 (Ubuntu)
Server built:   2018-10-10T18:59:25

**Database:** mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

**PHP version:** PHP 7.2.15-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:38:01) ( NTS )

**Nextcloud version:** Nextcloud 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** This installation has been installed from version 13 through the current and has been updated periodically via the web UI. 

**Where did you install Nextcloud from:** Installed from instructions [here](https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-16-04-lts-server) using the .tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
An unhandled exception has been thrown:
Error: Call to undefined function OC\App\simplexml_load_file() in /var/www/html/nextcloud/lib/private/App/InfoParser.php:64
Stack trace:
#0 /var/www/html/nextcloud/lib/private/App/AppManager.php(380): OC\App\InfoParser->parse('/var/www/html/n...')
#1 /var/www/html/nextcloud/lib/private/legacy/app.php(551): OC\App\AppManager->getAppInfo('files', false, NULL)
#2 /var/www/html/nextcloud/lib/private/AppFramework/App.php(65): OC_App::getAppInfo('files')
#3 /var/www/html/nextcloud/lib/private/legacy/app.php(236): OC\AppFramework\App::buildAppNamespace('files')
#4 /var/www/html/nextcloud/lib/private/legacy/app.php(119): OC_App::registerAutoloading('files', '/var/www/html/n...')
#5 /var/www/html/nextcloud/lib/base.php(654): OC_App::loadApps(Array)
#6 /var/www/html/nextcloud/lib/base.php(1068): OC::init()
#7 /var/www/html/nextcloud/console.php(46): require_once('/var/www/html/n...')
#8 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#9 {main}
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Error: Call to undefined function OC\App\simplexml_load_file() in /var/www/html/nextcloud/lib/private/App/InfoParser.php:64
Stack trace:
#0 /var/www/html/nextcloud/lib/private/App/AppManager.php(380): OC\App\InfoParser->parse('/var/www/html/n...')
#1 /var/www/html/nextcloud/lib/private/legacy/app.php(551): OC\App\AppManager->getAppInfo('files', false, NULL)
#2 /var/www/html/nextcloud/lib/private/AppFramework/App.php(65): OC_App::getAppInfo('files')
#3 /var/www/html/nextcloud/lib/private/legacy/app.php(236): OC\AppFramework\App::buildAppNamespace('files')
#4 /var/www/html/nextcloud/lib/private/legacy/app.php(119): OC_App::registerAutoloading('files', '/var/www/html/n...')
#5 /var/www/html/nextcloud/lib/base.php(654): OC_App::loadApps(Array)
#6 /var/www/html/nextcloud/lib/base.php(1068): OC::init()
#7 /var/www/html/nextcloud/console.php(46): require_once('/var/www/html/n...')
#8 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#9 {main}
```
</details>

**Are you using external storage, if yes which one:** No. Local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Chrome or Firefox (doesn't matter)

**Operating system:** Windows or Ubuntu (doesn't matter)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Not applicable to the error
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Pages of this:

{"reqId":"GR8W264MZyaAKTSTj3vV","level":3,"time":"2019-03-04T15:42:05+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/html\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"--","version":"15.0.2.0"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Not browser related
```
</details>

**Comment by kesselb** [comment]
Looks like `php7.2-xml` is missing (or not enabled for php cli).
