### ISSUE TITLE
cant open pdf -files through webdav

### ISSUE THREAD

**Issue by colttt** [nextcloud/server#14527]
### Steps to reproduce
1. Upload a PDF file
2. get access to it via KDE Dolphin and webdav protocol
3. try to open it

### Expected behaviour
the pdf should open it with my pdf-viewer (in my case okular)

### Actual behaviour
I got an error message from okular
> Could not open webdavs://colttt@wolke.domain.de:443/remote.php/webdav/LinuxJournal/Linux-Journal-2015-12.pdf. Reason: Internal error in server
> webdavs://colttt@wolke.domain.de/remote.php/webdav/LinuxJournal/Linux-Journal-2015-12.pdf
With a webbrowser/webgui there is no problem, I can open PDF files without any issues

### Server configuration

**Operating system**:  Debian GNU/Linux 9.5 (stretch)

**Web server:** apache2 v2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** 7.0.30-0+deb9u1

**Nextcloud version:** 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
if neccassary I will upload it
```
</details>

**Are you using external storage, if yes which one:** local (mounted via nfs)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** OpenLDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
if neccassary I will upload it
```
</details>

### Client configuration
**Browser:** Dolphin

**Operating system:** Debian Stretch

#### Web server error log
<details>
<summary>Web server error log</summary>

```
open a pdf file:
wolke.domain.de:443 172.16.100.1 - colttt [05/Mar/2019:08:27:03 +0100] "GET /remote.php/webdav/LinuxJournal/Linux-Journal-2015-12.pdf HTTP/1.1" 503 1125 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) okular/4.14.26 Safari/534.34"

copy a pdf file:
wolke.domain.de:443 172.16.100.1 - colttt [05/Mar/2019:08:27:41 +0100] "GET /remote.php/webdav/LinuxJournal/Linux-Journal-2015-12.pdf HTTP/1.1" 200 6764983 "-" "Mozilla/5.0 (X11; Linux x86_64) KHTML/5.28.0 (like Gecko) Konqueror/5.28"

open a simple text file:
wolke.domain.de:443 172.16.100.1 - - [05/Mar/2019:08:28:05 +0100] "PROPFIND /remote.php/webdav/fcx48.txt HTTP/1.1" 401 11681 "-" "Mozilla/5.0 (X11; Linux x86_64) KHTML/5.28.0 (like Gecko) Konqueror/5.28"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
open a pdf file:
{"reqId":"LdTS7T9QJ4ZmMDMBblbe","level":0,"time":"March 05, 2019 08:27:03","remoteAddr":"172.16.100.1","user":"--","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/LinuxJournal\/Linux-Journal-2015-12.pdf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) okular\/4.14.26 Safari\/534.34","version":"13.0.5.2"}

copy a pdf file:
{"reqId":"eRGz026bfVirneuc54MK","level":1,"time":"March 05, 2019 08:27:41","remoteAddr":"172.16.100.1","user":"ae42f7a2-adc0-1033-865e-8763c51afa71","app":"admin_audit","method":"GET","url":"\/remote.php\/webdav\/LinuxJournal\/Linux-Journal-2015-12.pdf","message":"File accessed: \"\/LinuxJournal\/Linux-Journal-2015-12.pdf\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) KHTML\/5.28.0 (like Gecko) Konqueror\/5.28","version":"13.0.5.2"}

open a simple text file:
{"reqId":"6QQRWiVu9lkp6dCxO2LD","level":0,"time":"March 05, 2019 08:28:05","remoteAddr":"172.16.100.1","user":"ae42f7a2-adc0-1033-865e-8763c51afa71","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/fcx48.txt","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) KHTML\/5.28.0 (like Gecko) Konqueror\/5.28","version":"13.0.5.2"}
{"reqId":"vlyUfwEGqtKbzcM9bOfV","level":1,"time":"March 05, 2019 08:28:05","remoteAddr":"172.16.100.1","user":"ae42f7a2-adc0-1033-865e-8763c51afa71","app":"admin_audit","method":"GET","url":"\/remote.php\/webdav\/fcx48.txt","message":"File accessed: \"\/fcx48.txt\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) KHTML\/5.28.0 (like Gecko) Konqueror\/5.28","version":"13.0.5.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
if neccassary I will upload it
```
</details>

**Comment by kesselb** [comment]
Do you see this issue with newer nextcloud versions? We fixed some issues for Microsoft Office and webdav. Probably works for Okular too.

**Comment by colttt** [comment]
sorry I forgott to answer ;-)
yes with 17 it works fine, so I will close it
