### ISSUE TITLE
No SMTP possible after updating credentials

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/server#14604]
I used to send emails from Nextcloud using SMTP. It always worked fine until I recently reset the credentials in Nextcloud without changing them (reset to same values).

Now I always receive the following error:
<details>
<summary>Error report</summary>

```
Failed to authenticate on SMTP server with username "xxx@xxx.com" using 1 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6 " in /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457 Stack trace: #0 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('535 5.7.8 Error...', Array) #1 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('bmp1ejEyNTkuRXY...', Array, Array, false, NULL) #2 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/LoginAuthenticator.php(36): Swift_Transport_EsmtpTransport->executeCommand('bmp1ejEyNTkuRXY...', Array) #3 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(177): Swift_Transport_Esmtp_Auth_LoginAuthenticator->authenticate(Object(Swift_SmtpTransport), 'xxx@xx...', 'xxPasswordxx') #4 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #5 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand() #6 /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start() #7 /var/www/nextcloud/lib/private/Mail/Mailer.php(180): Swift_Mailer->send(Object(Swift_Message), Array) #8 /var/www/nextcloud/settings/Controller/MailSettingsController.php(159): OC\Mail\Mailer->send(Object(OC\Mail\Message)) #9 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): OC\Settings\Controller\MailSettingsController->sendTestMail() #10 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\MailSettingsController), 'sendTestMail') #11 /var/www/nextcloud/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\MailSettingsController), 'sendTestMail') #12 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OC\\Settings\\Con...', 'sendTestMail', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array) #14 /var/www/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) #15 /var/www/nextcloud/lib/base.php(987): OC\Route\Router->match('/settings/admin...') #16 /var/www/nextcloud/index.php(42): OC::handleRequest() #17 {main}.
```
</details>

<br>

This issue also occurs on a fresh installation.

The operating system is NextCloudPi with latest updates.

Any ideas on what level (operating system, Nextcloud, ...) the issue is based?

**Comment by j-ed** [comment]
Support requests should usually be posted in the help forum first and not in this bug tracker.
There you will find several discussions and solutions how to solve email sending problems.
See: https://help.nextcloud.com/search?q=smtp
