### ISSUE TITLE
Avoid warning for non-existing LDAP users

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1470]
- use user_ldap
- try to login a user that doesn't exist on LDAP nor in the internal DB
- expected: no warning level message (at most a message of level debug or info)
- actual:

``` json
{
    "Code": 0,
    "Exception": "Exception",
    "File": "apps/user_ldap/lib/User_LDAP.php",
    "Line": 117,
    "Message": "No user available for the given login name on ldap://server:389",
    "Trace": "
        #0 apps/user_ldap/lib/User_LDAP.php(133): OCA\\User_LDAP\\User_LDAP->getLDAPUserByLoginName('admin')
        #1 lib/private/User/Manager.php(201): OCA\\User_LDAP\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)
        #2 core/Controller/LoginController.php(214): OC\\User\\Manager->checkPassword(*** sensitive parameters replaced ***)
        #3 [internal function]: OC\\Core\\Controller\\LoginController->tryLogin(*** sensitive parameters replaced ***)
        #4 lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
        #5 lib/private/AppFramework/Http/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')
        #6 lib/private/AppFramework/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')
        #7 lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\AppFramework\\App::main('LoginController', 'tryLogin', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)
        #8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)
        #9 lib/private/Route/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)
        #10 lib/base.php(983): OC\\Route\\Router->match('/login')
        #11 index.php(48): OC::handleRequest()
        #12 {main}
    "
}
```

URL: `/login?user=admin`, app: `user_ldap`, log level: 3

cc @blizzz

**Comment by blizzz** [comment]
@MorrisJobke wasn't it the debug info that you have wanted once quite a while ago?

**Comment by MorrisJobke** [comment]
> @MorrisJobke wasn't it the debug info that you have wanted once quite a while ago?

Correct, but not in the log level 3 (warning).

**Comment by blizzz** [comment]
so, removing it completely or downgrading to debug?

**Comment by MorrisJobke** [comment]
@blizzz Is this easy to accomplish?

**Comment by blizzz** [comment]
Here you go https://github.com/nextcloud/server/pull/2409
