### ISSUE TITLE
Create contact on master via contacts app cause "disk_free_space(): No such file or directory at ..."

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1474]
The error message is this:

``` json
{
    "app": "PHP",
    "level": 0,
    "message": "disk_free_space(): No such file or directory at lib/private/Files/Storage/Local.php#291",
    "method": "PUT",
    "remoteAddr": "::1",
    "reqId": "jgv/S+ohAnLYtpM7iB1j",
    "time": "2016-09-20T22:18:24+00:00",
    "url": "/server/remote.php/dav/addressbooks/users/admin/contacts/fb28acc6-4a19-404a-8057-b4892127e917.vcf",
    "user": "admin"
}
```

I created a stack trace right before:

```
{
    "app": "no app in context",
    "level": 3,
    "message": "Exception: {\"Exception\":\"Exception\",\"Message\":\"\",\"Code\":0,\"Trace\":\"

#0 lib/private/Files/Storage/Wrapper/Wrapper.php(327): OC\Files\Storage\Local->free_space('files/addressbo...')
#1 lib/private/Files/Storage/Wrapper/Wrapper.php(327): OC\Files\Storage\Wrapper\Wrapper->free_space('files/addressbo...')
#2 lib/private/Files/View.php(1120): OC\Files\Storage\Wrapper\Wrapper->free_space('files/addressbo...')
#3 lib/private/Files/View.php(1076): OC\Files\View->basicOperation('free_space', 'addressbooks/us...')
#4 apps/dav/lib/Connector/Sabre/QuotaPlugin.php(141): OC\Files\View->free_space('addressbooks/us...')
#5 apps/dav/lib/Connector/Sabre/QuotaPlugin.php(104): OCA\DAV\Connector\Sabre\QuotaPlugin->getFreeSpace('/addressbooks/u...')
#6 [internal function]: OCA\DAV\Connector\Sabre\QuotaPlugin->checkQuota('addressbooks/us...', Resource id #79, Object(OCA\DAV\CardDAV\AddressBook), false)
#7 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#8 3rdparty/sabre/dav/lib/DAV/Server.php(1034): Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)
#9 3rdparty/sabre/dav/lib/DAV/CorePlugin.php(523): Sabre\DAV\Server->createFile('addressbooks/us...', Resource id #79, NULL)
#10 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#11 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#12 3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#13 3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#14 apps/dav/lib/Server.php(184): Sabre\DAV\Server->exec()
#15 apps/dav/appinfo/v2/remote.php(30): OCA\DAV\Server->exec()
#16 remote.php(165): require_once('/Users/morrisjo...')
#17 {main}

    \",\"File\":\"lib/private/Files/Storage/Local.php\",\"Line\":290}",
    "method": "PUT",
    "remoteAddr": "::1",
    "reqId": "jgv/S+ohAnLYtpM7iB1j",
    "time": "2016-09-20T22:18:24+00:00",
    "url": "/server/remote.php/dav/addressbooks/users/admin/contacts/fb28acc6-4a19-404a-8057-b4892127e917.vcf",
    "user": "admin"
}
```

and `$sourcePath` is set to `\/Users\/morrisjobke\/Projects\/nextcloud\/server\/data\/admin\/files\/addressbooks\/users\/admin\/contacts`.

@icewind1991 any idea?

**Comment by MorrisJobke** [comment]
Can't reproduce anymore -> close
