### ISSUE TITLE
[NC 16] $this->property::CONSTANT breaks app:check-code command

### ISSUE THREAD

**Issue by marius-wieschollek** [nextcloud/server#14824]
### Steps to reproduce
1. Create app
2. Reference constant of property dynamically `$this->property::CONSTANT` ([example](https://github.com/marius-wieschollek/passwords/blob/3bca012d2fd4cd1a37e447a0c10bd903b004e72f/src/lib/Settings/AdminSettings.php#L343))
3. Run the `./occ app:check-code <appid>` command for your app

### Expected behaviour
App check finished successfully.

### Actual behaviour
Error: Call to undefined method PhpParser\Node\Expr\PropertyFetch::toString() in /var/www/html/lib/private/App/CodeChecker/NodeVisitor.php:172
It seems like \OC\App\CodeChecker\NodeVisitor:172 expects $node->class to be of type \PhpParser\Node\Name but gets \PhpParser\Node\Expr\PropertyFetch instead.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDb 10.3

**PHP version:** 7.2.16

**Nextcloud version:** (see Nextcloud admin page) 16.0.0 Beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:** 15.0.5

**Where did you install Nextcloud from:** Docker Container

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.12.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.4.0-BUILD
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.0.3",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 1025,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 65

**Operating system:** Ubuntu 18.04

#### Console error log
<details>
<summary>Console error log</summary>

```
An unhandled exception has been thrown:
Error: Call to undefined method PhpParser\Node\Expr\PropertyFetch::toString() in /var/www/html/lib/private/App/CodeChecker/NodeVisitor.php:172
Stack trace:
#0 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): OC\App\CodeChecker\NodeVisitor->enterNode(Object(PhpParser\Node\Expr\ClassConstFetch))
#1 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ArrayDimFetch))
#2 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ArrayDimFetch))
#3 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#4 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#5 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#6 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#7 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#8 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#9 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#10 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#11 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#12 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#13 /var/www/html/3rdparty/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#14 /var/www/html/lib/private/App/CodeChecker/CodeChecker.php(136): PhpParser\NodeTraverser->traverse(Array)
#15 /var/www/html/lib/private/App/CodeChecker/CodeChecker.php(110): OC\App\CodeChecker\CodeChecker->analyseFile('/var/www/html/c...')
#16 /var/www/html/lib/private/App/CodeChecker/CodeChecker.php(74): OC\App\CodeChecker\CodeChecker->analyseFolder('passwords', '/var/www/html/c...')
#17 /var/www/html/core/Command/App/CheckCode.php(125): OC\App\CodeChecker\CodeChecker->analyse('passwords')
#18 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\CheckCode->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/3rdparty/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\CheckCode), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/console.php(97): OC\Console\Application->run()
#24 /var/www/html/occ(11): require_once('/var/www/html/c...')
#25 {main}
```
</details>

**Comment by MorrisJobke** [comment]
@marius-wieschollek Does this also happen in 15?

**Comment by marius-wieschollek** [comment]
The PhpParser in Nextcloud 15 can't read code like this at all and crashes with
```
In ParserAbstract.php line 275:
                                                                                    
  Syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM, expecting ',' or ')' on line 34  
```

**Comment by kesselb** [comment]
```
Index: lib/private/App/CodeChecker/NodeVisitor.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/App/CodeChecker/NodeVisitor.php	(revision 448699502851a60883faf5f0d5cea4a9855bec66)
+++ lib/private/App/CodeChecker/NodeVisitor.php	(date 1553772839000)
@@ -162,7 +162,7 @@
 				if ($node->class instanceof Name) {
 					$this->checkBlackList($node->class->toString(), CodeChecker::CLASS_CONST_FETCH_NOT_ALLOWED, $node);
 				}
-				if ($node->class instanceof Node\Expr\Variable) {
+				if ($node->class instanceof Node\Expr\Variable || $node->class instanceof Node\Expr\PropertyFetch) {
 					/**
 					 * TODO: find a way to detect something like this:
 					 *       $c = "OC_API";
```

@marius-wieschollek does this work?

**Comment by marius-wieschollek** [comment]
@kesselb yes, this works.

**Comment by MorrisJobke** [comment]
@kesselb Mind to open a PR with that?
