### ISSUE TITLE
PHP Fatal error with nextcloud 13 and PostgreSQL after update PHP 5.6 -> 7.2

### ISSUE THREAD

**Issue by achalkov** [nextcloud/server#14929]
### Actual behaviour
After updating php from 5.6 to 7.2 i have 500 error while trying to open nextcloud page.
Errors from apache log:

```
PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:64\n
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n
#4 /var/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Configura in /var/www/nextcloud/lib/private/DB/Connection.php on line 64
```
PHP version (php -v):
```
PHP 7.2.16 (cli) (built: Mar  5 2019 13:10:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

list of php loaded modules (php -m):
```
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
```

List of php-related apache modules (httpd  -t -D DUMP_MODULES | grep php):
```
php7_module (shared)
```
My config.php:
```
<?php
$CONFIG = array (
  'instanceid' => 'aaa',
  'passwordsalt' => 'aaa',
  'secret' => 'aaa',
  'trusted_domains' =>
  array (
    0 => 'dm1',
    1 => 'dm2',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://dm2/nextcloud',
  'dbtype' => 'pgsql',
  'version' => '13.0.12.1',
  'dbname' => 'nextcloud',
  'dbhost' => '/var/run/postgresql',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => '',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_from_address' => 'achalkov87',
  'mail_domain' => 'gmail.com',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'name',
  'mail_smtppassword' => 'pwd',
  'mail_smtpsecure' => 'tls',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.secret' => 'aaa',
);

```

While i'm trying to execute commands via occ, all seems ok:
```
[root@achalkov-hetzner config]# sudo -u apache php /var/www/nextcloud/occ -V
Chalkov's cloud 13.0.12
```

So i strongly suspect there is some enviromental issue, but i really cant find out what wrong exactly. Could you, please, help me with that?

### Server configuration

**Operating system**:
Centos 7
**Web server:**
Apache
**Database:**
Pgsql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13.0.12
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Comment by achalkov** [comment]
ok, i t was my mistake. i installed php version 7.2 and php7.2 simult and didnt install pgsql driver for php ver7.2.
