### ISSUE TITLE
mysql performance and lock issue

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#15093]
### Steps to reproduce
1. start scan with sudo -uwww-data php occ files:scan User

### Expected behaviour
Tell us what should happen

### Actual behaviour
i get an Error from my Database.

### Server configuration

**Operating system**:
ubuntu 18.04

**Web server:**
Nginx

**Database:**
Mysql 

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - announcementcenter: 3.4.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - camerarawpreviews: 0.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.0
  - data_request: 1.2.0
  - dav: 1.8.1
  - drawio: 0.9.2
  - drop_account: 0.1.0
  - event_update_notification: 0.3.4
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.6
  - files_fulltextsearch_tesseract: 1.2.2
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.5
  - fulltextsearch_elasticsearch: 1.2.4
  - gallery: 18.2.0
  - gpxpod: 3.0.3
  - keeporsweep: 0.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.4
  - news: 13.1.6
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - oauth2: 1.3.0
  - ocdownloader: 1.6.3
  - password_policy: 1.5.0
  - phonetrack: 0.5.0
  - piwik: 0.5.1
  - previewgenerator: 2.1.0
  - provisioning_api: 1.5.0
  - radio: 0.6.4
  - rainloop: 6.0.2
  - ransomware_detection: 0.4.3
  - ransomware_protection: 1.3.0
  - registration: 0.4.6
  - richdocuments: 3.2.4
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.4
  - spreed: 5.0.3
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - telephoneprovider: 1.0.2
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - user_usage_report: 1.1.1
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - admin_notifications
  - apporder
  - encryption
  - external
  - files_frommail
  - files_rightclick
  - files_trackdownloads
  - issuetemplate
  - jsloader
  - mail
  - notifications
  - ocsms
  - onlyoffice
  - passwords
  - polls
  - socialsharing_facebook
  - socialsharing_googleplus
  - socialsharing_twitter
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.larsmueller.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "https:\/\/cloud.larsmueller.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

1 local
1 external Nextcloud
1 ftp Server

**Are you using encryption:** yes/no

no

</details>

<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Exception during scan: An exception occurred while executing 'UPDATE `oc_filecache` SET `size`=? WHERE (`size` <> ? OR `size` IS NULL) AND `fileid` = ? ' with params [2644688, 2644688, "637084"]:

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#0 /var/www/cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE `oc_file...', Array)
#2 /var/www/cloud/lib/private/DB/Connection.php(195): Doctrine\DBAL\Connection->executeQuery('UPDATE `oc_file...', Array, Array, NULL)
#3 /var/www/cloud/lib/private/Files/Cache/Cache.php(333): OC\DB\Connection->executeQuery('UPDATE `oc_file...', Array)
#4 /var/www/cloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php(138): OC\Files\Cache\Cache->update('637084', Array)
#5 /var/www/cloud/lib/private/Files/Cache/Scanner.php(417): OC\Files\Cache\Wrapper\CacheWrapper->update('637084', Array)
#6 /var/www/cloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('Documents', true, 3, '637084', true)
#7 /var/www/cloud/lib/private/Files/Cache/Scanner.php(338): OC\Files\Cache\Scanner->scanChildren('', true, 3, '637083', true)
#8 /var/www/cloud/lib/private/Files/Utils/Scanner.php(245): OC\Files\Cache\Scanner->scan('', true, 3)
#9 /var/www/cloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/Lars', true, NULL)
#10 /var/www/cloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('Lars', '/Lars', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#11 /var/www/cloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/cloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/cloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/cloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/cloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/cloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/cloud/console.php(96): OC\Console\Application->run()
#18 /var/www/cloud/occ(11): require_once('/var/www/cloud/...')
```
</details>

#### my.cnf

```
[mysqld]
join_buffer_size = 128M
tmp_table_size = 256M
max_heap_table_size = 256M
innodb_log_file_size = 512M
innodb_log_files_in_group = 512M
query_cache_type                = 0
query_cache_size                = 0
innodb_thread_concurrency       = 8
innodb_buffer_pool_size         = 3G
innodb_io_capacity              = 4000
innodb_buffer_pool_dump_pct     = 100
innodb_log_file_size            = 256M
innodb_log_buffer_size          = 16M
innodb_lock_wait_timeout        = 120
```

#### mysql

```
mysql> show variables like 'innodb_lock_wait_timeout';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| innodb_lock_wait_timeout | 120   |
+--------------------------+-------+
1 row in set (0.00 sec)

mysql> SHOW ENGINE INNODB STATUS\G
*************************** 1. row ***************************
  Type: InnoDB
  Name:
Status:
=====================================
2019-04-14 08:51:33 0x7f079d69c700 INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 25 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 445 srv_active, 0 srv_shutdown, 5827 srv_idle
srv_master_thread log flush and writes: 6269
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 565
OS WAIT ARRAY INFO: signal count 553
RW-shared spins 0, rounds 885, OS waits 405
RW-excl spins 0, rounds 1838, OS waits 19
RW-sx spins 8, rounds 218, OS waits 7
Spin rounds per wait: 885.00 RW-shared, 1838.00 RW-excl, 27.25 RW-sx
------------
TRANSACTIONS
------------
Trx id counter 14593731
Purge done for trx's n:o < 14588457 undo n:o < 0 state: running but idle
History list length 1699
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 421149654734272, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421149654732432, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421149654730592, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 14593721, ACTIVE 76 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 2 lock struct(s), heap size 1136, 1 row lock(s)
MySQL thread id 982, OS thread handle 139670683068160, query id 198379 localhost clouduser updating
UPDATE `oc_filecache` SET `size`='2644688' WHERE (`size` <> '2644688' OR `size` IS NULL) AND `fileid` = '637084'
Trx read view will not see trx with id >= 14593721, sees < 14588448
------- TRX HAS BEEN WAITING 74 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 727 page no 12805 n bits 144 index PRIMARY of table `cloud_db`.`oc_filecache` trx id 14593721 lock_mode X locks rec but not gap waiting
Record lock, heap no 28 PHYSICAL RECORD: n_fields 18; compact format; info bits 0
 0: len 8; hex 800000000009b89c; asc         ;;
 1: len 6; hex 000000ddaeee; asc       ;;
 2: len 7; hex 28000001cf2eed; asc (    . ;;
 3: len 8; hex 800000000000000a; asc         ;;
 4: len 9; hex 446f63756d656e7473; asc Documents;;
 5: len 30; hex 663238313238623338656662633631333464633430373531656532316664; asc f28128b38efbc6134dc40751ee21fd; (total 32 bytes);
 6: len 8; hex 800000000009b89b; asc         ;;
 7: len 9; hex 446f63756d656e7473; asc Documents;;
 8: len 8; hex 8000000000000002; asc         ;;
 9: len 8; hex 8000000000000001; asc         ;;
 10: len 8; hex 8000000000285ad0; asc      (Z ;;
 11: len 8; hex 800000005cb1d695; asc     \   ;;
 12: len 8; hex 800000005cb1d4ed; asc     \   ;;
 13: len 4; hex 80000000; asc     ;;
 14: len 8; hex 8000000000000000; asc         ;;
 15: len 13; hex 35636231643639373562393562; asc 5cb1d6975b95b;;
 16: len 4; hex 8000001f; asc     ;;
 17: len 0; hex ; asc ;;

------------------
---TRANSACTION 14588448, ACTIVE 6075 sec
326 lock struct(s), heap size 41168, 2056 row lock(s)
MySQL thread id 129, OS thread handle 139671062173440, query id 198567 localhost clouduser
Trx read view will not see trx with id >= 14588448, sees < 14588448
--------
FILE I/O
--------
I/O thread 0 state: waiting for completed aio requests (insert buffer thread)
I/O thread 1 state: waiting for completed aio requests (log thread)
I/O thread 2 state: waiting for completed aio requests (read thread)
I/O thread 3 state: waiting for completed aio requests (read thread)
I/O thread 4 state: waiting for completed aio requests (read thread)
I/O thread 5 state: waiting for completed aio requests (read thread)
I/O thread 6 state: waiting for completed aio requests (write thread)
I/O thread 7 state: waiting for completed aio requests (write thread)
I/O thread 8 state: waiting for completed aio requests (write thread)
I/O thread 9 state: waiting for completed aio requests (write thread)
Pending normal aio reads: [0, 0, 0, 0] , aio writes: [0, 0, 0, 0] ,
 ibuf aio reads:, log i/o's:, sync i/o's:
Pending flushes (fsync) log: 0; buffer pool: 0
14609 OS file reads, 9487 OS file writes, 4644 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 0.68 writes/s, 0.48 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 164, seg size 166, 42 merges
merged operations:
 insert 46, delete mark 23, delete 4
discarded operations:
 insert 0, delete mark 0, delete 0
Hash table size 796921, node heap has 5 buffer(s)
Hash table size 796921, node heap has 2 buffer(s)
Hash table size 796921, node heap has 2 buffer(s)
Hash table size 796921, node heap has 1 buffer(s)
Hash table size 796921, node heap has 89 buffer(s)
Hash table size 796921, node heap has 118 buffer(s)
Hash table size 796921, node heap has 6 buffer(s)
Hash table size 796921, node heap has 6 buffer(s)
4.04 hash searches/s, 3.08 non-hash searches/s
---
LOG
---
Log sequence number 14732464926
Log flushed up to   14732464926
Pages flushed up to 14732464926
Last checkpoint at  14732464917
0 pending log flushes, 0 pending chkp writes
2823 log i/o's done, 0.16 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total large memory allocated 3298295808
Dictionary memory allocated 1436524
Buffer pool size   196596
Free buffers       179075
Database pages     14370
Old database pages 5303
Modified db pages  0
Pending reads      0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 28213, not young 383243
0.40 youngs/s, 0.00 non-youngs/s
Pages read 14315, created 55, written 6022
0.00 reads/s, 0.00 creates/s, 0.44 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 17 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 14370, unzip_LRU len: 6385
I/O sum[56]:cur[0], unzip sum[0]:cur[0]
----------------------
INDIVIDUAL BUFFER POOL INFO
----------------------
---BUFFER POOL 0
Buffer pool size   49152
Free buffers       44821
Database pages     3530
Old database pages 1323
Modified db pages  0
Pending reads      0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 2, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 3528, created 2, written 1497
0.00 reads/s, 0.00 creates/s, 0.00 writes/s
No buffer pool page gets since the last printout
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 3530, unzip_LRU len: 1614
I/O sum[14]:cur[0], unzip sum[0]:cur[0]
---BUFFER POOL 1
Buffer pool size   49146
Free buffers       44639
Database pages     3675
Old database pages 1376
Modified db pages  0
Pending reads      0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 1, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 3675, created 0, written 1672
0.00 reads/s, 0.00 creates/s, 0.24 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 3675, unzip_LRU len: 1700
I/O sum[14]:cur[0], unzip sum[0]:cur[0]
---BUFFER POOL 2
Buffer pool size   49152
Free buffers       44574
Database pages     3803
Old database pages 1383
Modified db pages  0
Pending reads      0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 9206, not young 203788
0.12 youngs/s, 0.00 non-youngs/s
Pages read 3752, created 51, written 744
0.00 reads/s, 0.00 creates/s, 0.12 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 11 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 3803, unzip_LRU len: 1608
I/O sum[14]:cur[0], unzip sum[0]:cur[0]
---BUFFER POOL 3
Buffer pool size   49146
Free buffers       45041
Database pages     3362
Old database pages 1221
Modified db pages  0
Pending reads      0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 19004, not young 179455
0.28 youngs/s, 0.00 non-youngs/s
Pages read 3360, created 2, written 2109
0.00 reads/s, 0.00 creates/s, 0.08 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 54 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 3362, unzip_LRU len: 1463
I/O sum[14]:cur[0], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
2 read views open inside InnoDB
Process ID=26392, Main thread ID=139671263573760, state: sleeping
Number of rows inserted 17457, updated 1786, deleted 157, read 69084781
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 5.68 reads/s
----------------------------
END OF INNODB MONITOR OUTPUT
============================

1 row in set (0.00 sec)
```

**Comment by kesselb** [comment]
Hmm. Are you able to reproduce this?

**Comment by Happyfeet01** [comment]
No, I changed Mariadb and it’s faster. Now I’m changed to Docker and it’s really fast.
