### ISSUE TITLE
Upgrade from nextcloud 14.0.10.0 to 15.0.7 fails - SetVcardDatabaseUID.php

### ISSUE THREAD

**Issue by HaleyACS** [nextcloud/server#15388]
### Steps to reproduce
1. launch occ upgrade on nextcloud 14.0.10.0
2.
3.

### Expected behaviour
Tell us what should happen
Upgrade should go through clean

### Actual behaviour
occ exits, upgrade stopped and failed.

### Server configuration

**Operating system**:
Alpine Linux v3.8

**Web server:**
nginx 1.14.2

**Database:**
mariadb 10.3.14

**PHP version:**
7.2.18

**Nextcloud version:** (see Nextcloud admin page)
14.0.10.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.7.0

**Where did you install Nextcloud from:**
Official source. Automated build in Docker-environment. Never had an issue before (doing this since nextcloud 11.x)

**Signing status:**
<details>
<summary>Signing status</summary>
Unable to comply. UI not availabe.
``` 
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
/usr/local/bin # occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: true
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'instanceid' => 'XXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'nas.solsys.org',
    1 => 'sol-gate.solsys.org',
  ),
  'dbtype' => 'mysql',
  'version' => '14.0.10.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-db-dev',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'XXXXXXXX',
  'installed' => true,
  'mail_from_address' => 'root',
  'logtimezone' => 'Europe/Berlin',
  'logdateformat' => 'Y-m-d H:i:s',
  'loglevel' => 0,
  'maintenance' => true,
  'preview_max_x' => 512,
  'preview_max_y' => 512,
  'preview_max_scale_factor' => 1,
  'overwrite.cli.url' => 'https://XXXXXXXX:6443',
  'theme' => '',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => XXXXXXXXX',
  'mail_domain' => 'XXXXXXXX',
  'mail_smtpport' => '25',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Itnernal disks, dedicated docker container

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
66.0.3 (64-bit)

**Operating system:**
Ubuntu 18.10

#### Web server error log
<details>
<summary>Web server error log</summary>
No error logs from WebServer. occ call -> php straight.
```

Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
Note: Logs are dumped to the stdout of the docker instance.
Note2: /apps2 os not on a persistent storage, as it caused too many issues in the past during upgrades. Hance - apps are re-installed from scratch after every upgrade.

nextcloud-dev       | /data/.noscan tag found. Skipped
nextcloud-dev       | Permissions in /config are correct.
nextcloud-dev       | Updating permissions in /apps2...
nextcloud-dev       | Updating permissions in /var/log...
nextcloud-dev       | Updating permissions in /php...
nextcloud-dev       | Updating permissions in /nginx...
nextcloud-dev       | Updating permissions in /tmp...
nextcloud-dev       | Updating permissions in /etc/s6.d...
nextcloud-dev       | Done updating permissions.
nextcloud-dev       | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
nextcloud-dev       | You may use your browser or the occ upgrade command to do the upgrade
nextcloud-dev       | Set log level to debug
nextcloud-dev       | Updating database schema
nextcloud-dev       | Updated database
nextcloud-dev       | Disabled incompatible app: bruteforcesettings
nextcloud-dev       | Disabled incompatible app: calendar
nextcloud-dev       | Disabled incompatible app: camerarawpreviews
nextcloud-dev       | Disabled incompatible app: contacts
nextcloud-dev       | Disabled incompatible app: deck
nextcloud-dev       | Disabled incompatible app: files_accesscontrol
nextcloud-dev       | Disabled incompatible app: groupfolders
nextcloud-dev       | Disabled incompatible app: notes
nextcloud-dev       | Disabled incompatible app: ocsms
nextcloud-dev       | Disabled incompatible app: quota_warning
nextcloud-dev       | Updating <accessibility> ...
nextcloud-dev       | Updated <accessibility> to 1.1.0
nextcloud-dev       | Updating <federatedfilesharing> ...
nextcloud-dev       | Updated <federatedfilesharing> to 1.5.0
nextcloud-dev       | Updating <files_pdfviewer> ...
nextcloud-dev       | Updated <files_pdfviewer> to 1.4.0
nextcloud-dev       | Updating <files_texteditor> ...
nextcloud-dev       | Updated <files_texteditor> to 2.7.0
nextcloud-dev       | Updating <files_videoplayer> ...
nextcloud-dev       | Updated <files_videoplayer> to 1.4.0
nextcloud-dev       | Updating <gallery> ...
nextcloud-dev       | Updated <gallery> to 18.2.0
nextcloud-dev       | Updating <password_policy> ...
nextcloud-dev       | Updated <password_policy> to 1.5.0
nextcloud-dev       | Updating <provisioning_api> ...
nextcloud-dev       | Updated <provisioning_api> to 1.5.0
nextcloud-dev       | Updating <serverinfo> ...
nextcloud-dev       | Updated <serverinfo> to 1.5.0
nextcloud-dev       | Updating <survey_client> ...
nextcloud-dev       | Updated <survey_client> to 1.3.0
nextcloud-dev       | Updating <twofactor_backupcodes> ...
nextcloud-dev       | Updated <twofactor_backupcodes> to 1.4.1
nextcloud-dev       | Updating <updatenotification> ...
nextcloud-dev       | Updated <updatenotification> to 1.5.0
nextcloud-dev       | Updating <federation> ...
nextcloud-dev       | Updated <federation> to 1.5.0
nextcloud-dev       | Updating <lookup_server_connector> ...
nextcloud-dev       | Updated <lookup_server_connector> to 1.3.0
nextcloud-dev       | Updating <files> ...
nextcloud-dev       | Updated <files> to 1.10.0
nextcloud-dev       | Updating <activity> ...
nextcloud-dev       | Updated <activity> to 2.8.2
nextcloud-dev       | Updating <cloud_federation_api> ...
nextcloud-dev       | Updated <cloud_federation_api> to 0.1.0
nextcloud-dev       | Updating <dav> ...
nextcloud-dev       | Fix broken values of calendar objects
nextcloud-dev       | 
nextcloud-dev       |  Starting ...
nextcloud-dev       | 
nextcloud-dev       | Updated <dav> to 1.8.1
nextcloud-dev       | Updating <files_external> ...
nextcloud-dev       | Updated <files_external> to 1.6.0
nextcloud-dev       | Updating <files_sharing> ...
nextcloud-dev       | Updated <files_sharing> to 1.7.0
nextcloud-dev       | Updating <files_trashbin> ...
nextcloud-dev       | Updated <files_trashbin> to 1.5.0
nextcloud-dev       | Updating <files_versions> ...
nextcloud-dev       | Updated <files_versions> to 1.8.0
nextcloud-dev       | Updating <sharebymail> ...
nextcloud-dev       | Updated <sharebymail> to 1.5.0
nextcloud-dev       | Updating <workflowengine> ...
nextcloud-dev       | Updated <workflowengine> to 1.5.0
nextcloud-dev       | Updating <admin_audit> ...
nextcloud-dev       | Updated <admin_audit> to 1.5.0
nextcloud-dev       | Updating <comments> ...
nextcloud-dev       | Updated <comments> to 1.5.0
nextcloud-dev       | Updating <firstrunwizard> ...
nextcloud-dev       | Updated <firstrunwizard> to 2.4.0
nextcloud-dev       | Updating <nextcloud_announcements> ...
nextcloud-dev       | Updated <nextcloud_announcements> to 1.4.0
nextcloud-dev       | Updating <notifications> ...
nextcloud-dev       | Updated <notifications> to 2.3.0
nextcloud-dev       | Updating <systemtags> ...
nextcloud-dev       | Updated <systemtags> to 1.5.0
nextcloud-dev       | Updating <theming> ...
nextcloud-dev       | Updated <theming> to 1.6.0
nextcloud-dev       | Checking for update of app accessibility in appstore
nextcloud-dev       | Checked for update of app "accessibility" in appstore 
nextcloud-dev       | Checking for update of app activity in appstore
nextcloud-dev       | Checked for update of app "activity" in appstore 
nextcloud-dev       | Checking for update of app admin_audit in appstore
nextcloud-dev       | Checked for update of app "admin_audit" in appstore 
nextcloud-dev       | Checking for update of app cloud_federation_api in appstore
nextcloud-dev       | Checked for update of app "cloud_federation_api" in appstore 
nextcloud-dev       | Checking for update of app comments in appstore
nextcloud-dev       | Checked for update of app "comments" in appstore 
nextcloud-dev       | Checking for update of app dav in appstore
nextcloud-dev       | Checked for update of app "dav" in appstore 
nextcloud-dev       | Checking for update of app federatedfilesharing in appstore
nextcloud-dev       | Checked for update of app "federatedfilesharing" in appstore 
nextcloud-dev       | Checking for update of app federation in appstore
nextcloud-dev       | Checked for update of app "federation" in appstore 
nextcloud-dev       | Checking for update of app files in appstore
nextcloud-dev       | Checked for update of app "files" in appstore 
nextcloud-dev       | Checking for update of app files_external in appstore
nextcloud-dev       | Checked for update of app "files_external" in appstore 
nextcloud-dev       | Checking for update of app files_pdfviewer in appstore
nextcloud-dev       | Checked for update of app "files_pdfviewer" in appstore 
nextcloud-dev       | Checking for update of app files_sharing in appstore
nextcloud-dev       | Checked for update of app "files_sharing" in appstore 
nextcloud-dev       | Checking for update of app files_texteditor in appstore
nextcloud-dev       | Checked for update of app "files_texteditor" in appstore 
nextcloud-dev       | Checking for update of app files_trashbin in appstore
nextcloud-dev       | Checked for update of app "files_trashbin" in appstore 
nextcloud-dev       | Checking for update of app files_versions in appstore
nextcloud-dev       | Checked for update of app "files_versions" in appstore 
nextcloud-dev       | Checking for update of app files_videoplayer in appstore
nextcloud-dev       | Checked for update of app "files_videoplayer" in appstore 
nextcloud-dev       | Checking for update of app firstrunwizard in appstore
nextcloud-dev       | Checked for update of app "firstrunwizard" in appstore 
nextcloud-dev       | Checking for update of app gallery in appstore
nextcloud-dev       | Checked for update of app "gallery" in appstore 
nextcloud-dev       | Checking for update of app logreader in appstore
nextcloud-dev       | Checked for update of app "logreader" in appstore 
nextcloud-dev       | Checking for update of app lookup_server_connector in appstore
nextcloud-dev       | Checked for update of app "lookup_server_connector" in appstore 
nextcloud-dev       | Checking for update of app nextcloud_announcements in appstore
nextcloud-dev       | Checked for update of app "nextcloud_announcements" in appstore 
nextcloud-dev       | Checking for update of app notifications in appstore
nextcloud-dev       | Checked for update of app "notifications" in appstore 
nextcloud-dev       | Checking for update of app oauth2 in appstore
nextcloud-dev       | Checked for update of app "oauth2" in appstore 
nextcloud-dev       | Checking for update of app password_policy in appstore
nextcloud-dev       | Checked for update of app "password_policy" in appstore 
nextcloud-dev       | Checking for update of app provisioning_api in appstore
nextcloud-dev       | Checked for update of app "provisioning_api" in appstore 
nextcloud-dev       | Checking for update of app serverinfo in appstore
nextcloud-dev       | Checked for update of app "serverinfo" in appstore 
nextcloud-dev       | Checking for update of app sharebymail in appstore
nextcloud-dev       | Checked for update of app "sharebymail" in appstore 
nextcloud-dev       | Checking for update of app support in appstore
nextcloud-dev       | Checked for update of app "support" in appstore 
nextcloud-dev       | Checking for update of app survey_client in appstore
nextcloud-dev       | Checked for update of app "survey_client" in appstore 
nextcloud-dev       | Checking for update of app systemtags in appstore
nextcloud-dev       | Checked for update of app "systemtags" in appstore 
nextcloud-dev       | Checking for update of app theming in appstore
nextcloud-dev       | Checked for update of app "theming" in appstore 
nextcloud-dev       | Checking for update of app twofactor_backupcodes in appstore
nextcloud-dev       | Checked for update of app "twofactor_backupcodes" in appstore 
nextcloud-dev       | Checking for update of app updatenotification in appstore
nextcloud-dev       | Checked for update of app "updatenotification" in appstore 
nextcloud-dev       | Checking for update of app workflowengine in appstore
nextcloud-dev       | Checked for update of app "workflowengine" in appstore 
nextcloud-dev       | oauth2: Failed to enable app oauth2
nextcloud-dev       | An unhandled exception has been thrown:
nextcloud-dev       | TypeError: Argument 1 passed to OC\Repair\NC15\SetVcardDatabaseUID::getUID() must be of the type string, null given, called in /nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php on line 132 and defined in /nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php:87
nextcloud-dev       | Stack trace:
nextcloud-dev       | #0 /nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php(132): OC\Repair\NC15\SetVcardDatabaseUID->getUID(NULL, Object(OC\Repair))
nextcloud-dev       | #1 /nextcloud/lib/private/Repair/NC15/SetVcardDatabaseUID.php(149): OC\Repair\NC15\SetVcardDatabaseUID->repair(Object(OC\Repair))
nextcloud-dev       | #2 /nextcloud/lib/private/Repair.php(96): OC\Repair\NC15\SetVcardDatabaseUID->run(Object(OC\Repair))
nextcloud-dev       | #3 /nextcloud/lib/private/Updater.php(265): OC\Repair->run()
nextcloud-dev       | #4 /nextcloud/lib/private/Updater.php(121): OC\Updater->doUpgrade('15.0.7.0', '14.0.10.0')
nextcloud-dev       | #5 /nextcloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
nextcloud-dev       | #6 /nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-dev       | #7 /nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-dev       | #8 /nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-dev       | #9 /nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-dev       | #10 /nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-dev       | #11 /nextcloud/console.php(96): OC\Console\Application->run()
nextcloud-dev       | #12 /nextcloud/occ(11): require_once('/nextcloud/cons...')
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
Not relevant, as this is on the console.

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Still an issue?
