### ISSUE TITLE
Can't delete federated folder

### ISSUE THREAD

**Issue by ThomasCr** [nextcloud/server#15720]
Hi, I have a folder included from a remote nextcloud instance. Now something is broken - maybe the share got deleted or it is from nextcloud update.

The Nextcloud Windows Client shows server 500 for this folder (an so the complet sync of the account is broken) and when I am on the Webpage I also not able to delete the folder.

It shows only "Error on delete file" when I select Delete or also when I select remove share.

I did a file scan and there I also get a error for my user (USER2):

```
sudo -u web32 php7.1 occ files:scan --all
Starting scan for user 1 out of 11 (USER1)
Starting scan for user 2 out of 11 (USER2)
Exception during scan: An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ' with params ["29726"]:

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
#0 /var/www/clients/client22/web32/web/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(184): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/clients/client22/web32/web/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(158): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /var/www/clients/client22/web32/web/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(938): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE `oc_file...', Array)
#3 /var/www/clients/client22/web32/web/lib/private/DB/Connection.php(195): Doctrine\DBAL\Connection->executeQuery('UPDATE `oc_file...', Array, Array, NULL)
#4 /var/www/clients/client22/web32/web/lib/private/Files/Cache/Cache.php(340): OC\DB\Connection->executeQuery('UPDATE `oc_file...', Array)
#5 /var/www/clients/client22/web32/web/lib/private/Files/Cache/Cache.php(235): OC\Files\Cache\Cache->update('29726', Array)
#6 /var/www/clients/client22/web32/web/apps/files_sharing/lib/External/Scanner.php(111): OC\Files\Cache\Cache->put('', Array)
#7 /var/www/clients/client22/web32/web/apps/files_sharing/lib/External/Scanner.php(97): OCA\Files_Sharing\External\Scanner->addResult(Array, '')
#8 /var/www/clients/client22/web32/web/apps/files_sharing/lib/External/Scanner.php(44): OCA\Files_Sharing\External\Scanner->scanAll()
#9 /var/www/clients/client22/web32/web/lib/private/Files/Utils/Scanner.php(245): OCA\Files_Sharing\External\Scanner->scan('', true, 3)
#10 /var/www/clients/client22/web32/web/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/creutz', true, NULL)
#11 /var/www/clients/client22/web32/web/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('creutz', '/creutz', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#12 /var/www/clients/client22/web32/web/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/clients/client22/web32/web/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/clients/client22/web32/web/3rdparty/symfony/console/Application.php(901): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/clients/client22/web32/web/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/clients/client22/web32/web/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/clients/client22/web32/web/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/clients/client22/web32/web/console.php(97): OC\Console\Application->run()
#19 /var/www/clients/client22/web32/web/occ(11): require_once('/var/www/client...')
#20 {main}
```

### Server configuration

**Operating system:**  Ubuntu 16.04.6 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.26

**PHP version:** 7.1

**Nextcloud version:** 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded

**Where did you install Nextcloud from:** your Website

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.7.0
  - bruteforcesettings: 1.3.0
  - camerarawpreviews: 0.7.0
  - checksum: 0.4.2
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - encryption: 2.4.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_readmemd: 1.0.4
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_gateway: 0.14.0
  - twofactor_nextcloud_notification: 1.1.1
  - twofactor_totp: 2.1.2
  - twofactor_u2f: 3.0.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - external
  - files_accesscontrol
  - files_external
  - groupfolders
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "theme": "",
        "trusted_domains": [
            "cloud.domain.com",
            "cloud.domain.net"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "trashbin_retention_obligation": "auto, 365",
        "appcodechecker": false,
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "enable_previews": true,
        "versions_retention_obligation": "auto",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "_memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "memcache.locking": "\\OC\\Memcache\\Memcached",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Comment by ThomasCr** [comment]
![grafik](https://user-images.githubusercontent.com/226670/58341363-57f91000-7e4e-11e9-81d3-871a7865c391.png)
Thats the Folder on the Nextcloud Webpage

**Comment by ThomasCr** [comment]
The logfile is full of sensitive informations, thats why I not included it: for what should I look, when needed?

**Comment by ThomasCr** [comment]
Ok, I catched now the exeption from the logfile, when I hit delete:

```
{"reqId":"47EUsUE9im9TeBSmBMOK","level":4,"time":"2019-05-24T16:12:25+00:00","remoteAddr":"2001:470:XXX:XXX:XXX:XXX:XXX:XXX","user":"USER2","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/files\/USER2\/MYFOLDER","mess
age":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ' with params [\"29726\"]:\n\nSQLSTATE[HY093]: Inval
id parameter number: number of bound variables does not match number of tokens","Code":0,"Trace":[{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":184,"function"
:"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ' with params [\"29726\"]:\n\nS
QLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens",{"errorInfo":["HY093",0],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdpa
rty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":158,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY093"
,0],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ' with params [\"29726\"]:\n\nSQLSTATE[HY093]: Invalid parameter numb
er: number of bound variables does not match number of tokens"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":938,"function":"driverExceptionDuringQuery","class
":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY093",0],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS
 NULL) AND `fileid` = ? ",{"1":"*** sensitive parameter replaced ***"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","typ
e":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"],[],null]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Cache.php","lin
e":340,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client2
2\/web32\/web\/lib\/private\/Files\/Cache\/Cache.php","line":235,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps
\/files_sharing\/lib\/External\/Scanner.php","line":111,"function":"put","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/clients\/
client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":97,"function":"addResult","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter r
eplaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":44,"function":"scanAll","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Watcher.php","line":104,"function":"scan","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",false]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/View.php","line":1336,"function":"update","class":"OC\\Files\\Cache\\Watcher","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/View.php","line":1376,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"*** sensitive parameter replaced ***","\/\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":223,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/USER2\/files\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":178,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/USER2\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":287,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/USER2\/MYFOLDER"]},{"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpDelete"],[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:DELETE",[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/remote.php","line":163,"args":["\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":125,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens","Code":"HY093","Trace":[{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":932,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"],[],null]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Cache.php","line":340,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Cache.php","line":235,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":111,"function":"put","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":97,"function":"addResult","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":44,"function":"scanAll","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Watcher.php","line":104,"function":"scan","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",false]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/View.php","line":1336,"function":"update","class":"OC\\Files\\Cache\\Watcher","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/View.php","line":1376,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"*** sensitive parameter replaced ***","\/\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":223,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/USER2\/files\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":178,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/USER2\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":287,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/USER2\/MYFOLDER"]},{"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpDelete"],[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:DELETE",[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/remote.php","line":163,"args":["\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":143,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens","Code":"HY093","Trace":[{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","line":141,"function":"execute","class":"PDOStatement","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":932,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"],[],null]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Cache.php","line":340,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Cache.php","line":235,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":111,"function":"put","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":97,"function":"addResult","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/files_sharing\/lib\/External\/Scanner.php","line":44,"function":"scanAll","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/Cache\/Watcher.php","line":104,"function":"scan","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",false]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/View.php","line":1336,"function":"update","class":"OC\\Files\\Cache\\Watcher","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/lib\/private\/Files\/View.php","line":1376,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"*** sensitive parameter replaced ***","\/\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":223,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/USER2\/files\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":178,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/USER2\/MYFOLDER"]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":287,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/USER2\/MYFOLDER"]},{"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpDelete"],[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:DELETE",[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.domain.com\/remote.php\/dav\/files\/USER2\/MYFOLDER","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/clients\/client22\/web32\/web\/remote.php","line":163,"args":["\/var\/www\/clients\/client22\/web32\/web\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/clients\/client22\/web32\/web\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":141}},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.1.1"}
```

**Comment by ThomasCr** [comment]
OK, when I searched for the exeption, I found that is is also reported there:
https://github.com/nextcloud/server/issues/15211

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/15385#issuecomment-490418046 :see_no_evil:

**Comment by hcderaad** [comment]
The problem is that the federation client server is not checking validity of the response received from the federation host deep enough to detect malformed JSON bodies. I have opened an issue for making the federation client server actually test that input from individual files is also wellformed and not just trusting a server that gives a "healthy" status response. https://github.com/nextcloud/server/issues/15765

**Comment by kesselb** [comment]
Does this error still occur?
