### ISSUE TITLE
Upgrade to 10.0.1 fails when using postgres

### ISSUE THREAD

**Issue by nktje** [nextcloud/server#1591]
### Steps to reproduce
1. cd /var/www/html && curl https://download.nextcloud.com/server/releases/nextcloud-10.0.1.tar.bz2 | tar xpjf - && chown -R apache:apache nextcloud
2. cd nextcloud
3. sudo -u apache php ./occ upgrade
### Expected behaviour

Upgrade should succeed
### Actual behaviour

```
# sudo -u apache php ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                     
 27/27 [============================] 100%
Checked database schema update
Checking updates of apps
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
 nc_addressbooks                          
  1/10 [==>-------------------------]  10%OC\DB\MigrationException: An exception occurred while executing 'ALTER TABLE nc_nc_addressbooks_cpbweriw1dnxf ALTER id TYPE BIGSERIAL':

SQLSTATE[42704]: Undefined object: 7 ERROR:  type "bigserial" does not exist
Update failed
Maintenance mode is kept active
Reset log level
```
### Server configuration

**Operating system**:
CentOS 7
**Web server:**
nginx/1.10.1
**Database:**
PostgreSQL 9.2.15
**PHP version:**
7.0.11
**Nextcloud version:** (see Nextcloud admin page)
10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrading from 10.0
**Where did you install Nextcloud from:**
tarball off the nextcloud.com site
**Signing status:**
<details>
<summary>

Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - news
  - user_external
  - user_ldap
  - user_saml

```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
{
    "system": {
        "instanceid": "ocea4d8119ae",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "censored.fqdn"
        ],
        "datadirectory": "\/nextcloud",
        "quota_include_external_storage": false,
        "version": "9.1.0.16",
        "knowledgebaseenabled": true,
        "auth.bruteforce.protection.enabled": true,
        "skeletondirectory": "",
        "dbtype": "pgsql",
        "dbname": "nextcloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "\/var\/run\/postgresql",
        "dbtableprefix": "nc_",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "0",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/nextcloud",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "censored.fqdn",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "overwrite.cli.url": "https:\/\/censored.fqdn\/nextcloud",
        "overwritewebroot": "\/nextcloud",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/server\/",
        "has_internet_connection": true,
        "check_for_working_wellknown_setup": true,
        "log_rotate_size": 536870912,
        "filelocking.enabled": true,
        "upgrade.disable-web": true,
        "debug": true,
        "logtimezone": "Europe\/Helsinki",
        "logfile": "\/nextcloud\/nextcloud.log",
        "log_type": "owncloud"
    }
}

```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

Not applicable
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
{"reqId":"i8uap2QeU2Kw+AecE+Te","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.0.16 to 9.1.1.5"
,"level":0,"time":"2016-09-30T13:47:09+03:00","method":"--","url":"\/nextcloud\/occ","user":"--"}
{"reqId":"i8uap2QeU2Kw+AecE+Te","remoteAddr":"","app":"core","message":"Simulated database structure update fa
iled (OC\\DB\\MigrationException: An exception occurred while executing 'ALTER TABLE nc_nc_addressbooks_cpbweriw1dnxf ALTER id TYPE BIGSERIAL':\n\nSQLSTATE[42704]: Undefined object: 7 ERROR:  type \"bigserial\" does not exist in \/var\/www\/html\/nextcloud\/lib\/private\/DB\/Migrator.php:170\nStack trace:\n#0 \/var\/www\/html\/nextcloud\/lib\/private\/DB\/Migrator.php(128): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/var\/www\/html\/nextcloud\/lib\/private\/DB\/MDB2SchemaManager.php(131): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/db.php(203): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/html\/n...')\n#3 \/var\/www\/html\/nextcloud\/lib\/private\/Updater.php(354): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/html\/n...')\n#4 \/var\/www\/html\/nextcloud\/lib\/private\/Updater.php(262): OC\\Updater->checkAppUpgrade('9.1.1.5')\n#5 \/var\/www\/html\/nextcloud\/lib\/private\/Updater.php(151): OC\\Updater->doUpgrade('9.1.1.5', '9.1.0.16')\n#6 \/var\/www\/html\/nextcloud\/core\/Command\/Upgrade.php(292): OC\\Updater->upgrade()\n#7 \/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php(259): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php(844): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php(192): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php(123): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/html\/nextcloud\/lib\/private\/Console\/Application.php(146): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 \/var\/www\/html\/nextcloud\/console.php(90): OC\\Console\\Application->run()\n#13 \/var\/www\/html\/nextcloud\/occ(11): require_once('\/var\/www\/html\/n...')\n#14 {main})","level":4,"time":"2016-09-30T13:47:22+03:00","method":"--","url":"\/nextcloud\/occ","user":"--"}
{"reqId":"i8uap2QeU2Kw+AecE+Te","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"OC\\\\DB\\\\MigrationException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE nc_nc_addressbooks_cpbweriw1dnxf ALTER id TYPE BIGSERIAL':\\n\\nSQLSTATE[42704]: Undefined object: 7 ERROR:  type \\\"bigserial\\\" does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(128): OC\\\\DB\\\\Migrator->checkTableMigrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Table))\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/MDB2SchemaManager.php(131): OC\\\\DB\\\\Migrator->checkMigrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/db.php(203): OC\\\\DB\\\\MDB2SchemaManager->simulateUpdateDbFromStructure('\\\/var\\\/www\\\/html\\\/n...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(354): OC_DB::simulateUpdateDbFromStructure('\\\/var\\\/www\\\/html\\\/n...')\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(262): OC\\\\Updater->checkAppUpgrade('9.1.1.5')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.1.5', '9.1.0.16')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/Command\\\/Upgrade.php(292): OC\\\\Updater->upgrade()\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Migrator.php\",\"Line\":170}","level":3,"time":"2016-09-30T13:47:22+03:00","method":"--","url":"\/nextcloud\/occ","user":"--"}
```

</details>
#### Browser log

Not applicable

**Comment by nickvergessen** [comment]
From which version are you upgrading? 10.0.0 or 9.0.*?

**Comment by nktje** [comment]
@nickvergessen from 10.0.0

**Comment by nickvergessen** [comment]
The strange thing is, we didn't even change that column.
So a blind guess would be, that using `occ upgrade --skip-migration-test` would actually work and finish the update.
Can you try that?

**Comment by nktje** [comment]
Sadly it didn't work any better. I forgot to mention that I had used mysql previously. I may or may not have fudged things while migrating.
```
# sudo -u apache php ./occ upgrade --skip-migration-test
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <dav> ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE nc_addressbooks ALTER id TYPE BIGSERIAL':

SQLSTATE[42704]: Undefined object: 7 ERROR:  type "bigserial" does not exist
Update failed
Maintenance mode is kept active
Reset log level
# 
```
As bigserial is not really a datatype in postgres (more like a bigint with a sequence), I "resolved" the problem by simply executing
`ALTER TABLE foo ALTER COLUMN id SET DATA TYPE bigint;`
on the failing tables (nc_addressbooks, nc_cards, nc_addressbookchanges, nc_calendarobjects, nc_calendars, nc_calendarchanges, nc_calendarsubscriptions, nc_schedulingobjects, nc_cards_properties, nc_dav_shares)

Sorry for the noise as this was probably a problem I had caused by my own. Anyways everything seems to be in order after changing the datatypes by hand.

**Comment by nickvergessen** [comment]
Okay, so let's close this for now, until a second admin experiences this problem

**Comment by nickvergessen** [comment]
@icewind1991 can you check whether updating to 10.0.2 works on postgres?

**Comment by MorrisJobke** [comment]
> Okay, so let's close this for now, until a second admin experiences this problem
