### ISSUE TITLE
Improve feedback of occ script

### ISSUE THREAD

**Issue by krichter722** [nextcloud/server#1592]
### Steps to reproduce
1. Run `sudo -u www-data php occ  maintenance:install --database sqlite`
   2.
   3.
### Expected behaviour

If the command line is incorrect (missing option/argument), display a helpful error message). Otherwise the installation should start or helpful feedback about the reason for the failure and possible fixes should be provided.
### Actual behaviour

```
$ sudo -u www-data php occ  maintenance:install --database "sqlite"
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:59
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(973): OC\DB\Connection->connect()
#1 /var/www/nextcloud/lib/private/DB/Connection.php(210): Doctrine\DBAL\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): OC\DB\Connection->executeUpdate('PRAGMA read_unc...')
#3 /var/www/nextcloud/lib/private/DB/Connection.php(142): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#4 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#5 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(121): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/Server.php(415): OC\DB\ConnectionFactory->getConnection('sqlite3', Array)
#7 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#8 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('DatabaseConnect...')
#9 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#10 /var/www/nextcloud/lib/private/Server.php(1029): OC\ServerContainer->query('DatabaseConnect...')
#11 /var/www/nextcloud/lib/private/Server.php(220): OC\Server->getDatabaseConnection()
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#15 /var/www/nextcloud/lib/private/Server.php(224): OC\ServerContainer->query('OC\\Authenticati...')
#16 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#18 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#19 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(151): OC\ServerContainer->query('OC\\Authenticati...')
#20 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#22 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#23 /var/www/nextcloud/lib/private/Server.php(239): OC\ServerContainer->query('OC\\Authenticati...')
#24 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('UserSession')
#26 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#27 /var/www/nextcloud/lib/private/Server.php(906): OC\ServerContainer->query('UserSession')
#28 /var/www/nextcloud/lib/private/Server.php(459): OC\Server->getUserSession()
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('AppManager')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#32 /var/www/nextcloud/lib/private/Server.php(1206): OC\ServerContainer->query('AppManager')
#33 /var/www/nextcloud/lib/private/legacy/app.php(293): OC\Server->getAppManager()
#34 /var/www/nextcloud/lib/private/legacy/app.php(109): OC_App::getEnabledApps()
#35 /var/www/nextcloud/lib/base.php(658): OC_App::loadApps(Array)
#36 /var/www/nextcloud/lib/base.php(1059): OC::init()
#37 /var/www/nextcloud/console.php(48): require_once('/var/www/nextcl...')
#38 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#39 {main}richter@richtercloud:/var/www/nextcloud:539> 
richter@richtercloud:/var/www/nextcloud:539> 
richter@richtercloud:/var/www/nextcloud:539> 
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('UserSession')
#26 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#27 /var/www/nextcloud/lib/private/Server.php(906): OC\ServerContainer->query('UserSession')
#28 /var/www/nextcloud/lib/private/Server.php(459): OC\Server->getUserSession()
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('AppManager')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#32 /var/www/nextcloud/lib/private/Server.php(1206): OC\ServerContainer->query('AppManager')
#33 /var/www/nextcloud/lib/private/legacy/app.php(293): OC\Server->getAppManager()
#34 /var/www/nextcloud/lib/private/legacy/app.php(109): OC_App::getEnabledApps()
#35 /var/www/nextcloud/lib/base.php(658): OC_App::loadApps(Array)
#36 /var/www/nextcloud/lib/base.php(1059): OC::init()
#37 /var/www/nextcloud/console.php(48): require_once('/var/www/nextcl...')
#38 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#39 {main}
```

This is not a support request. I don't intend to use nextcloud until intuitive usage is improved (including this issue).
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** apache 2.4

**Database:** none yet/planned to use sqlite

**PHP version:** 7.1

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** No.

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-10.0.1.tar.bz2

**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment]
Yeah, we should catch the exception I guess....

**Comment by mikygee** [comment]
Hello,
I opened a bug with a similar request.
Debugging Nextcloud is like finding the TV remote control in a dark room.

**Comment by gratuxri** [comment]
Hello, nowaday with php updater/updater.phar -vvv ; php ./occ -vvv app:update --all
it looks very verbose, can you please check this issue on new version of nextcloud and maybe close this issue?

**Comment by krichter722** [comment]
I'm sorry, I didn't check this, I'd recommend running a nextcloud installation in a Docker container or composition of such.
