### ISSUE TITLE
Upgrade to 16.0.3 fails 

### ISSUE THREAD

**Issue by mipla23** [nextcloud/server#16430]
### Steps to reproduce
1. Upgrade from nextcloud 15.? to 16.0.3

### Expected behaviour
It should succeed

### Actual behaviour
I get an error:

Aktualisierung auf 16.0.3

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

### Server configuration

**Operating system**: 
Ubuntu Server 18.04

**Web server:** 
Apache/2.4.29

**Database:** 
10.1.40-MariaDB

**PHP version:** 
7.2

**Nextcloud version:** (see Nextcloud admin page) 
15.? -> 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
originally owncloud, later upgraded to nextcloud (version 10 or so)

**Where did you install Nextcloud from:**
source code

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Impossible to login right now
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_rightclick
  - privacy
  - recommendations
  - user_ldap
  - viewer

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXXXXXXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 67.0.4

**Operating system:**
macOS Sierra

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Jul 16 06:25:01.984120 2019] [mpm_prefork:notice] [pid 5611] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 06:25:01.984140 2019] [core:notice] [pid 5611] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 12:22:16.189059 2019] [php7:error] [pid 126722] [client 106.12.225.241:60658] script '/var/www/cloud.***DOMAIN***/html/elrekt.php' not found or unable to stat
[Tue Jul 16 21:04:10.264424 2019] [php7:error] [pid 129896] [client 178.198.180.117:58064] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php on line 64
[Tue Jul 16 21:04:10.264642 2019] [php7:error] [pid 129896] [client 178.198.180.117:58064] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php on line 64
[Tue Jul 16 21:04:11.369257 2019] [mpm_prefork:notice] [pid 5611] AH00169: caught SIGTERM, shutting down
[Tue Jul 16 21:05:05.153017 2019] [mpm_prefork:notice] [pid 1526] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 21:05:05.193878 2019] [core:notice] [pid 1526] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 21:09:58.735376 2019] [mpm_prefork:notice] [pid 1526] AH00169: caught SIGTERM, shutting down
[Tue Jul 16 21:10:39.755325 2019] [mpm_prefork:notice] [pid 3796] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 21:10:39.755377 2019] [core:notice] [pid 3796] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 21:33:34.120660 2019] [mpm_prefork:notice] [pid 3796] AH00169: caught SIGTERM, shutting down
[Tue Jul 16 22:00:07.663324 2019] [mpm_prefork:notice] [pid 1322] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 22:00:07.712404 2019] [core:notice] [pid 1322] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 22:35:40.179656 2019] [mpm_prefork:notice] [pid 1322] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jul 16 22:35:40.268546 2019] [mpm_prefork:notice] [pid 1322] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 22:35:40.268556 2019] [core:notice] [pid 1322] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 22:36:18.912211 2019] [mpm_prefork:notice] [pid 1322] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jul 16 22:36:18.974814 2019] [mpm_prefork:notice] [pid 1322] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 22:36:18.974824 2019] [core:notice] [pid 1322] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 22:36:19.509072 2019] [mpm_prefork:notice] [pid 1322] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jul 16 22:36:19.568590 2019] [mpm_prefork:notice] [pid 1322] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 22:36:19.568600 2019] [core:notice] [pid 1322] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 23:20:38.331973 2019] [mpm_prefork:notice] [pid 1322] AH00169: caught SIGTERM, shutting down
[Tue Jul 16 23:29:19.011947 2019] [mpm_prefork:notice] [pid 1518] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 23:29:19.016280 2019] [core:notice] [pid 1518] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 16 23:36:57.719736 2019] [php7:error] [pid 1524] [client 213.188.247.86:50581] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(448): OC\\DB\\Connection->connect()\n#1 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(410): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(354): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(710): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(181): OC\\DB\\Connectio in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php on line 64
[Tue Jul 16 23:36:57.719975 2019] [php7:error] [pid 1524] [client 213.188.247.86:50581] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(448): OC\\DB\\Connection->connect()\n#1 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(410): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(354): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(710): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/cloud.***DOMAIN***/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(181): OC\\DB\\Connectio in /var/www/cloud.***DOMAIN***/html/lib/private/DB/Connection.php on line 64
[Tue Jul 16 23:36:58.234448 2019] [mpm_prefork:notice] [pid 1518] AH00169: caught SIGTERM, shutting down
[Tue Jul 16 23:38:58.448525 2019] [mpm_prefork:notice] [pid 1481] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jul 16 23:38:58.455940 2019] [core:notice] [pid 1481] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 17 00:23:21.695541 2019] [php7:error] [pid 1503] [client 31.202.101.40:52126] script '/var/www/cloud.***DOMAIN***/html/xmlrpc.php' not found or unable to stat
[Wed Jul 17 00:23:22.190791 2019] [php7:error] [pid 1734] [client 31.202.101.40:52219] script '/var/www/cloud.***DOMAIN***/html/wp-login.php' not found or unable to stat
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

is empty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by j-ed** [comment]
Have you checked the Nextcloud [**help forum**](https://help.nextcloud.com/) for a solution, because similar problems have already been reported and solved [**there**](https://help.nextcloud.com/t/mise-a-jour-15-0-10-erreur-with-create-table-oc-personal-sections/56343).

**Comment by kesselb** [comment]
Please check https://github.com/nextcloud/server/issues/15974 for more details.
