### ISSUE TITLE
Server check errors can not be displayed

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#16512]
So on the weekend I had my external hard drive removed from my cloud server.
After restarting apache, I was prompted by white error pages.

The problem is, we do have a nice check for the data directory:
https://github.com/nextcloud/server/blob/5898e87e0f69ed4a3be73cd044c19d7c4872b639/lib/base.php#L653

But rendering the error page nowadays involves the SCSS which is in appdata and therefor creates another error:

```
    Typ: RuntimeException
    Code: 0
    Nachricht: Could not get appdata folder
    Datei: /home/nickv/Nextcloud/17/server/lib/private/Files/AppData/AppData.php
    Zeile: 92


Trace

#0 /home/nickv/Nextcloud/17/server/lib/private/Files/AppData/AppData.php(108): OC\Files\AppData\AppData->getAppDataRootFolder()
#1 /home/nickv/Nextcloud/17/server/lib/private/Files/AppData/AppData.php(155): OC\Files\AppData\AppData->getAppDataFolder()
#2 /home/nickv/Nextcloud/17/server/lib/private/Template/IconsCacher.php(83): OC\Files\AppData\AppData->newFolder('icons')
#3 [internal function]: OC\Template\IconsCacher->__construct(Object(OC\Log), Object(OC\Files\AppData\Factory), Object(OC\URLGenerator), Object(OC\AppFramework\Utility\TimeFactory))
#4 /home/nickv/Nextcloud/17/server/lib/private/AppFramework/Utility/SimpleContainer.php(82): ReflectionClass->newInstanceArgs(Array)
#5 /home/nickv/Nextcloud/17/server/lib/private/AppFramework/Utility/SimpleContainer.php(99): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#6 /home/nickv/Nextcloud/17/server/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Template\\Ico...')
#7 /home/nickv/Nextcloud/17/server/lib/private/ServerContainer.php(145): OC\AppFramework\Utility\SimpleContainer->query('OC\\Template\\Ico...', true)
#8 /home/nickv/Nextcloud/17/server/lib/private/Server.php(981): OC\ServerContainer->query('OC\\Template\\Ico...')
#9 /home/nickv/Nextcloud/17/server/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#10 /home/nickv/Nextcloud/17/server/lib/private/ServerContainer.php(120): Pimple\Container->offsetGet('OC\\Template\\SCS...')
#11 /home/nickv/Nextcloud/17/server/lib/private/TemplateLayout.php(284): OC\ServerContainer->query('OC\\Template\\SCS...')
#12 /home/nickv/Nextcloud/17/server/lib/private/TemplateLayout.php(201): OC\TemplateLayout::findStylesheetFiles(Array)
#13 /home/nickv/Nextcloud/17/server/lib/private/legacy/template.php(183): OC\TemplateLayout->__construct('guest', '')
#14 /home/nickv/Nextcloud/17/server/lib/private/Template/Base.php(131): OC_Template->fetchPage()
#15 /home/nickv/Nextcloud/17/server/lib/private/legacy/template.php(273): OC\Template\Base->printPage()
#16 /home/nickv/Nextcloud/17/server/lib/base.php(676): OC_Template::printGuestPage('', 'error', Array)
#17 /home/nickv/Nextcloud/17/server/lib/base.php(1081): OC::init()
#18 /home/nickv/Nextcloud/17/server/index.php(40): require_once('/home/nickv/Nex...')
#19 {main}
```

**Comment by nickvergessen** [comment]
Fixed by #17163
