### ISSUE TITLE
BirthdayService expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#17004]
@georgehrke 

## Infos
- [ ] NC 17
- [ ] Request ID: ocBQc7pD89YyCCf2IcUw
- [x] Type: TypeError
- [x] Code: 0
- [ ] Message: DateTime::__construct() expects parameter 1 to be string, object given
- [ ] File: /var/www/html/apps/dav/lib/CalDAV/BirthdayService.php
- [ ] Line: 246

## Trace
```
#0 /var/www/html/apps/dav/lib/CalDAV/BirthdayService.php(246): DateTime-&gt;__construct(Object(Sabre\VObject\Property\VCard\Date))
#1 /var/www/html/apps/dav/lib/CalDAV/BirthdayService.php(368): OCA\DAV\CalDAV\BirthdayService-&gt;buildDateFromContact(&#039;BEGIN:VCARD\r\nVE...&#039;, &#039;BDAY&#039;, &#039;&#039;)
#2 /var/www/html/apps/dav/lib/CalDAV/BirthdayService.php(125): OCA\DAV\CalDAV\BirthdayService-&gt;updateCalendar(&#039;BA0E8376-9842-4...&#039;, &#039;BEGIN:VCARD\r\nVE...&#039;, Array, 6, Array)
#3 /var/www/html/apps/dav/lib/AppInfo/Application.php(128): OCA\DAV\CalDAV\BirthdayService-&gt;onCardChanged(1, &#039;BA0E8376-9842-4...&#039;, &#039;BEGIN:VCARD\r\nVE...&#039;)
#4 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(212): OCA\DAV\AppInfo\Application-&gt;OCA\DAV\AppInfo\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), &#039;\\OCA\\DAV\\CardDA...&#039;, Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, &#039;\\OCA\\DAV\\CardDA...&#039;, Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /var/www/html/lib/private/EventDispatcher/SymfonyAdapter.php(59): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch(&#039;\\OCA\\DAV\\CardDA...&#039;, Object(Symfony\Component\EventDispatcher\GenericEvent))
#7 /var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php(701): OC\EventDispatcher\SymfonyAdapter-&gt;dispatch(&#039;\\OCA\\DAV\\CardDA...&#039;, Object(Symfony\Component\EventDispatcher\GenericEvent))
#8 /var/www/html/3rdparty/sabre/dav/lib/CardDAV/Card.php(96): OCA\DAV\CardDAV\CardDavBackend-&gt;updateCard(&#039;1&#039;, &#039;BA0E8376-9842-4...&#039;, &#039;BEGIN:VCARD\r\nVE...&#039;)
#9 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(1130): Sabre\CardDAV\Card-&gt;put(&#039;BEGIN:VCARD\r\nVE...&#039;)
#10 /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server-&gt;updateFile(&#039;addressbooks/us...&#039;, &#039;BEGIN:VCARD\r\nVE...&#039;, NULL)
#11 [internal function]: Sabre\DAV\CorePlugin-&gt;httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#12 /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#13 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter-&gt;emit(&#039;method:PUT&#039;, Array)
#14 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#15 /var/www/html/apps/dav/lib/Server.php(317): Sabre\DAV\Server-&gt;exec()
#16 /var/www/html/apps/dav/appinfo/v2/remote.php(35): OCA\DAV\Server-&gt;exec()
#17 /var/www/html/remote.php(163): require_once(&#039;/var/www/html/a...&#039;)
#18 {main}
```
___ 
```vcard
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:41e602ab-83cc-46fc-89c2-57dc39243901
REV;VALUE=DATE-AND-OR-TIME:2019-09-04T14:01:20Z
FN:Photo
ADR;TYPE=HOME:;;;;;;
EMAIL;TYPE=HOME:
TEL;TYPE="HOME,VOICE":
CLOUD;TYPE=HOME:
BDAY;VALUE=DATE:20190830
END:VCARD
```

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/befe38e1d71079eeaf31421bee08b0dcf79fd000/apps/dav/lib/CalDAV/BirthdayService.php#L236-L242

- [ ] The data has a year
- [ ] There is no `X-APPLE-OMIT-YEAR`
- [ ] And the year is bigger than > 1970

`$birthday = $originalYear . $dateParts['month'] . '-' . $dateParts['date'];` as else block should do the trick but just guessing from the code ;)
