### ISSUE TITLE
Cannot create new user folder

### ISSUE THREAD

**Issue by naiaokami** [nextcloud/server#17029]
### Steps to reproduce
1. Use any form of external authentication on NextCloud; I used the user_sql plugin.
2. Attempt to login to NextCloud for the first time as an externally authenticated user.
3. User will see an internal server error, 
4. If the user tries again, it will let them in though.

### Expected behaviour
No error should occur; user should enter smoothly.

### Actual behaviour
User receives error; create folder error is logged by Next Cloud.

## Server configuration detail

**Operating system:** Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (apache2handler)

**Database:** mysql 10.1.41

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Installation

**Where did you install Nextcloud from:** Web Installer - https://nextcloud.com/install/

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => dc48de7ad4baa030c5e563350c9a80b274bad783f6f5adbf1595ecef6c6a32e52890a24cb26cddb0aa20193ba52c001150c68d8bfb567f0aed566f4029a190a3
                            [current] => 6a05a7a2bd52651177dc54170f94c7ccf1966c421f30540be49d64770d71c71731052565c2f8e00406a579e7c78dad16673202051231626f1e6d4e656046e6fc
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.rnd] => Array
                        (
                            [expected] => 
                            [current] => f01e75199f0044353514a85149d5f1939c601c53fde41da5be6540d6564b60e2b2b27b5744a0d56729ae409ff0b749d620a6d879b27131b8aedac77db59801b2
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - admin_notifications: 1.0.2
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - checksum: 0.4.3
 - circles: 0.17.7
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - deck: 0.6.6
 - encryption: 2.4.0
 - end_to_end_encryption: 1.1.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_mindmap: 0.0.15
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - groupfolders: 4.1.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - maps: 0.1.2
 - metadata: 0.9.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.2
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - sociallogin: 1.16.7
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.1
 - terms_of_service: 1.2.2
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - twofactor_u2f: 3.0.1
 - updatenotification: 1.6.0
 - user_sql: 4.3.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - files_external
 - spreed
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.wolfhowl.me"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "https:\/\/cloud.wolfhowl.me",
    "htaccess.RewriteBase": "\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "app_install_overwrite": [
        "end_to_end_encryption",
        "admin_notifications"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 2,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "Staff",
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtptimeout": 10,
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** No, it's disabled.

**Are you using an external user-backend, if yes which one:** user_sql

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Operating system:** Ubuntu 19.04

## Logs

<details><summary>Web server error log</summary>

```
[Thu Sep 05 15:36:46.984343 2019] [authz_core:error] [pid 22427] [client 192.99.58.77:43150] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/htaccesstest.txt
[Thu Sep 05 15:48:54.310105 2019] [authz_core:error] [pid 24583] [client 107.220.157.229:53062] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 16:06:24.128940 2019] [authz_core:error] [pid 27629] [client 107.220.157.229:54180] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 16:39:33.593231 2019] [authz_core:error] [pid 32586] [client 107.220.157.229:56482] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 16:49:58.807741 2019] [authz_core:error] [pid 532] [client 107.220.157.229:56906] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 16:54:08.665442 2019] [php7:emerg] [pid 1577] [client 107.220.157.229:57054] PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/cloud.wolfhowl.me/config/config.php on line 23
[Thu Sep 05 16:54:09.834664 2019] [php7:emerg] [pid 1545] [client 107.220.157.229:57056] PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/cloud.wolfhowl.me/config/config.php on line 23
[Thu Sep 05 16:54:10.491445 2019] [php7:emerg] [pid 1577] [client 107.220.157.229:57058] PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/cloud.wolfhowl.me/config/config.php on line 23
[Thu Sep 05 19:47:24.874747 2019] [authz_core:error] [pid 25057] [client 107.220.157.229:36964] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 19:58:28.239278 2019] [authz_core:error] [pid 27438] [client 107.220.157.229:37502] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 19:59:44.822446 2019] [authz_core:error] [pid 27393] [client 107.220.157.229:37568] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 21:19:05.876643 2019] [authz_core:error] [pid 6342] [client 107.220.157.229:42912] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
[Thu Sep 05 21:23:55.097715 2019] [php7:error] [pid 11729] [client 107.220.157.229:43090] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'RedisException:...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'RedisException:...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'RedisException:...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(81): OC\\Log->critical('RedisException:...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onException(Object(RedisException))\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:23:55.097927 2019] [php7:error] [pid 11729] [client 107.220.157.229:43090] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'Uncaught RedisE...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'Uncaught RedisE...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(68): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:23:59.412293 2019] [php7:error] [pid 11740] [client 107.220.157.229:43092] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'RedisException:...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'RedisException:...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'RedisException:...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(81): OC\\Log->critical('RedisException:...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onException(Object(RedisException))\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:23:59.412626 2019] [php7:error] [pid 11740] [client 107.220.157.229:43092] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'Uncaught RedisE...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'Uncaught RedisE...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(68): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:24:05.775669 2019] [php7:error] [pid 11745] [client 98.29.97.83:62052] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'RedisException:...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'RedisException:...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'RedisException:...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(81): OC\\Log->critical('RedisException:...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onException(Object(RedisException))\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:24:05.775945 2019] [php7:error] [pid 11745] [client 98.29.97.83:62052] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'Uncaught RedisE...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'Uncaught RedisE...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(68): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:24:17.411818 2019] [php7:error] [pid 11741] [client 107.220.157.229:43096] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'RedisException:...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'RedisException:...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'RedisException:...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(81): OC\\Log->critical('RedisException:...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onException(Object(RedisException))\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Thu Sep 05 21:24:17.412167 2019] [php7:error] [pid 11741] [client 107.220.157.229:43096] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php(54): Redis->get('defa95871dd4c1d...')\n#1 /var/www/cloud.wolfhowl.me/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/cloud.wolfhowl.me/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /var/www/cloud.wolfhowl.me/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'Uncaught RedisE...', 3)\n#5 /var/www/cloud.wolfhowl.me/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'Uncaught RedisE...', 3)\n#6 /var/www/cloud.wolfhowl.me/lib/private/Log.php(130): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /var/www/cloud.wolfhowl.me/lib/private/Log/ErrorHandler.php(68): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /var/www/cloud.wolfhowl.me/lib/private/Memcache/Redis.php on line 54
[Fri Sep 06 00:46:03.874369 2019] [authz_core:error] [pid 29633] [client 107.220.157.229:54790] AH01630: client denied by server configuration: /var/www/cloud.wolfhowl.me/data/.ocdata
```
</details>

<details><summary>Nextcloud log</summary>

```
[no app in context] Error: OCP\Files\NotPermittedException: Could not create folder at <<closure>>

 0. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/Root.php line 383
    OC\Files\Node\Folder->newFolder("/wolfgoeswoof/files")
 1. <<closure>>
    OC\Files\Node\Root->getUserFolder("*** sensitive parameter replaced ***")
 2. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/LazyRoot.php line 64
    undefinedundefinedcall_user_func_array([OC\Files\Node\Root {},"getUserFolder"], ["*** sensitive parameter replaced ***"])
 3. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/LazyRoot.php line 281
    OC\Files\Node\LazyRoot->__call("getUserFolder", ["*** sensitive parameter replaced ***"])
 4. /var/www/cloud.wolfhowl.me/apps/groupfolders/lib/Mount/MountProvider.php line 90
    OC\Files\Node\LazyRoot->getUserFolder("*** sensitive parameter replaced ***")
 5. /var/www/cloud.wolfhowl.me/lib/private/Files/Config/MountProviderCollection.php line 103
    OCA\GroupFolders\Mount\MountProvider->getMountsForUser("*** sensitive parameter replaced ***", OC\Files\Storage\StorageFactory {})
 6. /var/www/cloud.wolfhowl.me/lib/private/Files/Filesystem.php line 447
    OC\Files\Config\MountProviderCollection->addMountForUser("*** sensitive parameter replaced ***", OC\Files\Mount\Manager {})
 7. /var/www/cloud.wolfhowl.me/lib/private/Files/Filesystem.php line 376
    OC\Files\Filesystem::initMountPoints("*** sensitive parameter replaced ***")
 8. /var/www/cloud.wolfhowl.me/lib/private/legacy/util.php line 309
    OC\Files\Filesystem::init("*** sensitive parameter replaced ***", "/wolfgoeswoof/files")
 9. /var/www/cloud.wolfhowl.me/apps/encryption/lib/Hooks/UserHooks.php line 346
    OC_Util::setupFS("*** sensitive parameter replaced ***")
10. /var/www/cloud.wolfhowl.me/apps/encryption/lib/Hooks/UserHooks.php line 177
    OCA\Encryption\Hooks\UserHooks->setupFS("*** sensitive parameter replaced ***")
11. /var/www/cloud.wolfhowl.me/lib/private/legacy/hook.php line 106
    OCA\Encryption\Hooks\UserHooks->login("*** sensitive parameters replaced ***")
12. /var/www/cloud.wolfhowl.me/lib/private/Server.php line 420
    OC_Hook::emit("OC_User", "post_login", "*** sensitive parameter replaced ***")
13. <<closure>>
    OC\Server->OC\{closure}("*** sensitive parameters replaced ***")
14. /var/www/cloud.wolfhowl.me/lib/private/Hooks/EmitterTrait.php line 99
    undefinedundefinedcall_user_func_array(Closure {}, ["*** sensitive  ... "])
15. /var/www/cloud.wolfhowl.me/lib/private/Hooks/PublicEmitter.php line 36
    OC\Hooks\BasicEmitter->emit("\\OC\\User", "postLogin", ["*** sensitive  ... "])
16. /var/www/cloud.wolfhowl.me/lib/private/User/Session.php line 375
    OC\Hooks\PublicEmitter->emit("\\OC\\User", "postLogin", ["*** sensitive  ... "])
17. /var/www/cloud.wolfhowl.me/core/Controller/LoginController.php line 336
    OC\User\Session->completeLogin("*** sensitive parameters replaced ***")
18. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/Http/Dispatcher.php line 166
    OC\Core\Controller\LoginController->tryLogin("*** sensitive parameters replaced ***")
19. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controller\LoginController {}, "tryLogin")
20. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\LoginController {}, "tryLogin")
21. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\LoginController", "tryLogin", OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
22. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.login.tryLogin"})
23. /var/www/cloud.wolfhowl.me/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
24. /var/www/cloud.wolfhowl.me/lib/base.php line 975
    OC\Route\Router->match("/login")
25. /var/www/cloud.wolfhowl.me/index.php line 42
    OC::handleRequest()

POST /login
from 107.220.157.229 by wolfgoeswoof at 2019-09-06T04:37:03+00:00

[index] Error: OCP\Lock\LockedException: "Photos/Nut.jpg" is locked at <<closure>>

 0. /var/www/cloud.wolfhowl.me/lib/private/Files/View.php line 2050
    OC\Files\View->lockPath("/wolfgoeswoof/files/Photos/Nut.jpg", 1, false)
 1. /var/www/cloud.wolfhowl.me/lib/private/Files/View.php line 1140
    OC\Files\View->lockFile("/wolfgoeswoof/files/Photos/Nut.jpg", 1)
 2. /var/www/cloud.wolfhowl.me/lib/private/Files/View.php line 595
    OC\Files\View->basicOperation("file_get_contents", "/wolfgoeswoof/files/Photos/Nut.jpg", ["read"])
 3. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/File.php line 52
    OC\Files\View->file_get_contents("/wolfgoeswoof/files/Photos/Nut.jpg")
 4. /var/www/cloud.wolfhowl.me/apps/maps/lib/Service/PhotofilesService.php line 447
    OC\Files\Node\File->getContent()
 5. /var/www/cloud.wolfhowl.me/apps/maps/lib/Service/PhotofilesService.php line 391
    OCA\Maps\Service\PhotofilesService->getExifPelBackup("*** sensitive parameter replaced ***")
 6. /var/www/cloud.wolfhowl.me/apps/maps/lib/Service/PhotofilesService.php line 278
    OCA\Maps\Service\PhotofilesService->getExif("*** sensitive parameter replaced ***")
 7. /var/www/cloud.wolfhowl.me/apps/maps/lib/Service/PhotofilesService.php line 83
    OCA\Maps\Service\PhotofilesService->safeAddPhoto("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 8. /var/www/cloud.wolfhowl.me/apps/maps/lib/Hooks/FileHooks.php line 49
    OCA\Maps\Service\PhotofilesService->safeAddByFile("*** sensitive parameter replaced ***")
 9. <<closure>>
    OCA\Maps\Hooks\FileHooks->OCA\Maps\Hooks\{closure}("*** sensitive parameters replaced ***")
10. /var/www/cloud.wolfhowl.me/lib/private/Hooks/EmitterTrait.php line 99
    undefinedundefinedcall_user_func_array(Closure {}, ["*** sensitive parameter replaced ***"])
11. /var/www/cloud.wolfhowl.me/lib/private/Hooks/PublicEmitter.php line 36
    OC\Hooks\BasicEmitter->emit("\\OC\\Files", "postWrite", ["*** sensitive parameter replaced ***"])
12. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/Root.php line 136
    OC\Hooks\PublicEmitter->emit("\\OC\\Files", "postWrite", ["*** sensitive parameter replaced ***"])
13. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/Node.php line 109
    OC\Files\Node\Root->emit("\\OC\\Files", "postWrite", ["*** sensitive parameter replaced ***"])
14. /var/www/cloud.wolfhowl.me/lib/private/Files/Node/File.php line 109
    OC\Files\Node\Node->sendHooks(["postWrite"])
15. /var/www/cloud.wolfhowl.me/lib/private/legacy/util.php line 473
    OC\Files\Node\File->fopen("w")
16. /var/www/cloud.wolfhowl.me/lib/private/legacy/util.php line 464
    OC_Util::copyr("/var/www/cloud. ... s", OC\Files\Node\Folder {})
17. /var/www/cloud.wolfhowl.me/lib/private/legacy/util.php line 436
    OC_Util::copyr("/var/www/cloud. ... n", OC\Files\Node\Folder {})
18. /var/www/cloud.wolfhowl.me/lib/private/User/Session.php line 520
    OC_Util::copySkeleton("*** sensitive parameter replaced ***", OC\Files\Node\Folder {})
19. /var/www/cloud.wolfhowl.me/lib/private/User/Session.php line 378
    OC\User\Session->prepareUserLogin("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
20. /var/www/cloud.wolfhowl.me/core/Controller/LoginController.php line 336
    OC\User\Session->completeLogin("*** sensitive parameters replaced ***")
21. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/Http/Dispatcher.php line 166
    OC\Core\Controller\LoginController->tryLogin("*** sensitive parameters replaced ***")
22. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controller\LoginController {}, "tryLogin")
23. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\LoginController {}, "tryLogin")
24. /var/www/cloud.wolfhowl.me/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\LoginController", "tryLogin", OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
25. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.login.tryLogin"})
26. /var/www/cloud.wolfhowl.me/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
27. /var/www/cloud.wolfhowl.me/lib/base.php line 975
    OC\Route\Router->match("/login")
28. /var/www/cloud.wolfhowl.me/index.php line 42
    OC::handleRequest()

POST /login
from 107.220.157.229 by wolfgoeswoof at 2019-09-06T04:37:03+00:00
```
</details>

<details><summary>Browser log</summary>

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: 107.220.157.229
Request ID: PFiShdhTK6ttqc9jbryN
</details>

**Comment by tsueri** [comment]
I have the same problem on Ubuntu 18.04, php7.3-fpm, mariadb 10.4, apache2

I use the default user-backend.
