### ISSUE TITLE
unable to update Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable on ipv4 only server

### ISSUE THREAD

**Issue by unnilennium** [nextcloud/server#17055]
I have observed for a while now strange behaviour of my nextcloud installation.
It can take a long time to load the apps page, I get alerted that there are few updates for apps and when I login I have not access to them,  I know that there is an available nextcloud update and the webupdater tells me I am uptodate. 
Also notifications sometimes told me that the update server was unreachable for few days.
and lately, when trying to update to 16.0.4, I get 

> Initializing
> Current version is 16.0.3.

And everything stop there. And got an error in log files. See in steps to reproduces

### Steps to reproduce
1. access the updater page /nextcloud/updater/
> Initializing
> Current version is 16.0.3.
2. check the log
[08-Sep-2019 20:51:08 UTC] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable in /usr/share/nextcloud/updater/index.php:589
Stack trace:
#0 /usr/share/nextcloud/updater/index.php(235): Updater->getUpdateServerResponse()
#1 /usr/share/nextcloud/updater/index.php(1700): Updater->checkForUpdate()
#2 {main}
  thrown in /usr/share/nextcloud/updater/index.php on line 589

alternatively try to upgrade using command line ( I have also apps known to be out of date)
```
 # php71 occ status
  - installed: true
  - version: 16.0.3.0
  - versionstring: 16.0.3
  - edition: 
# php71 occ update:check
Everything up to date
# php71 occ update:check
Nextcloud 16.0.4 is available. Get more information on how to update at https://docs.nextcloud.com/server/16/admin_manual/maintenance/upgrade.html.
1 update available
# php71 occ  upgrade
Nextcloud is already latest version
```

### Expected behaviour
update using ipv4 when ipv6 is not available

### Actual behaviour
fails trying to reach ipv6 address when there is no ipv6 connectivity.

### Server configuration

**Operating system**: SME Server 9 based on CentOS 6, fully updated

**Web server:**  httpd-2.2.15-69.el6.centos.x86_64

**Database:** mysql-5.1

**PHP version:** php71-2.0-1.el6.remi.x86_64

**Nextcloud version:** 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since nextcloud 14

**Where did you install Nextcloud from:** rpm package allowing web update

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - dicomviewer: 1.2.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_inotify: 0.1.4
  - files_pdfviewer: 1.5.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ocr: 4.2.31
  - password_policy: 1.6.0
  - provisioning_api: 1.6.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_reader
  - files_rightclick
  - privacy
  - recommendations
  - workflow_pdf_converter
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.com",
            "myhostname",
            "localhost",
            "IPv4",
            "IPv4"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "files_reader"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.9.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "636059"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1547173439.7946",
            "lastcron": "1567977314",
            "lastupdateResult": "{\"version\":\"16.0.4.1\",\"versionstring\":\"Nextcloud 16.0.4\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-16.0.4.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/16\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=16.0.4\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1567977501",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "08343dd3f787291558383b46e1b489fb",
            "updater.secret.created": "1567972819",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.9.2",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "dicomviewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,swift,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_inotify": {
            "enabled": "yes",
            "installed_version": "0.1.4",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "files_reader": {
            "enabled": "no",
            "installed_version": "1.2.3",
            "types": "filesystem"
        },
        "files_rightclick": {
            "enabled": "no",
            "installed_version": "0.13.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.3.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "pub_date": "Mon, 02 Sep 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.4.2",
            "types": "authentication"
        },
        "ocr": {
            "enabled": "yes",
            "installed_version": "4.2.31",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "privacy": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "updatenotification": {
            "core": "16.0.4.1",
            "dicomviewer": "1.2.0",
            "enabled": "yes",
            "files_inotify": "0.1.4",
            "files_rightclick": "0.15.1",
            "installed_version": "1.6.0",
            "ocr": "4.3.7",
            "types": "",
            "update_check_errors": "0"
        },
        "user_external": {
            "installed_version": "0.6.1",
            "types": "prelogin,authentication"
        },
        "user_ldap": {
            "background_sync_interval": "1800",
            "background_sync_offset": "0",
            "background_sync_prefix": "s01",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "s01_lastChange": "1562012543",
            "s01ldap_base": "dc=itx,dc=pialasse,dc=com",
            "s01ldap_base_groups": "ou=Groups,dc=itx,dc=pialasse,dc=com",
            "s01ldap_base_users": "ou=Users,dc=itx,dc=pialasse,dc=com",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_display_name": "cn",
            "s01ldap_email_attr": "mail",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(&(|(objectclass=posixGroup)))",
            "s01ldap_group_member_assoc_attribute": "memberUid",
            "s01ldap_groupfilter_objectclass": "posixGroup",
            "s01ldap_host": "localhost",
            "s01ldap_login_filter": "(&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mail=%uid))))",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_email": "1",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_port": "389",
            "s01ldap_turn_off_cert_check": "1",
            "s01ldap_user_display_name_2": "uid",
            "s01ldap_userfilter_objectclass": "inetOrgPerson",
            "s01ldap_userlist_filter": "(|(objectclass=inetOrgPerson))",
            "s01use_memberof_to_detect_membership": "0",
            "s02_lastChange": "1547173503",
            "s02ldap_configuration_active": "0",
            "types": "authentication"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflow_pdf_converter": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        }
    }
}

```
</details>

**Are you using external storage, if **yes** which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
not related
```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** fedora 30

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[08-Sep-2019 19:48:53 UTC] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable in /usr/share/nextcloud/updater/index.php:589
Stack trace:
#0 /usr/share/nextcloud/updater/index.php(235): Updater->getUpdateServerResponse()
#1 /usr/share/nextcloud/updater/index.php(1699): Updater->checkForUpdate()
#2 {main}
  thrown in /usr/share/nextcloud/updater/index.php on line 589
[08-Sep-2019 20:01:23 UTC] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable in /usr/share/nextcloud/updater/index.php:589
Stack trace:
#0 /usr/share/nextcloud/updater/index.php(235): Updater->getUpdateServerResponse()
#1 /usr/share/nextcloud/updater/index.php(1699): Updater->checkForUpdate()
#2 {main}
  thrown in /usr/share/nextcloud/updater/index.php on line 589
[08-Sep-2019 20:08:46 UTC] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable in /usr/share/nextcloud/updater/index.php:589
Stack trace:
#0 /usr/share/nextcloud/updater/index.php(235): Updater->getUpdateServerResponse()
#1 /usr/share/nextcloud/updater/index.php(1699): Updater->checkForUpdate()
#2 {main}
  thrown in /usr/share/nextcloud/updater/index.php on line 589
[08-Sep-2019 20:10:29 UTC] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable in /usr/share/nextcloud/updater/index.php:589
Stack trace:
#0 /usr/share/nextcloud/updater/index.php(235): Updater->getUpdateServerResponse()
#1 /usr/share/nextcloud/updater/index.php(1699): Updater->checkForUpdate()
#2 {main}
  thrown in /usr/share/nextcloud/updater/index.php on line 589
[08-Sep-2019 20:15:12 UTC] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to 2a01:4f8:130:32f1::52: Network is unreachable in /usr/share/nextcloud/updater/index.php:589
Stack trace:
#0 /usr/share/nextcloud/updater/index.php(235): Updater->getUpdateServerResponse()
#1 /usr/share/nextcloud/updater/index.php(1699): Updater->checkForUpdate()
#2 {main}
  thrown in /usr/share/nextcloud/updater/index.php on line 589

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
```
</details>

From what I see, curl has no configuration in nextcloud to force ipv4 CURLOPT_IPRESOLVE is defaulted to CURL_IPRESOLVE_WHATEVER  and sometime gets the ipv4 and it works, and sometimes will hit the ipv6 and fail everytime.
see https://www.php.net/manual/en/function.curl-setopt.php

Unfortunatly there is no way I see to set this in the server configuration and it is set

**Comment by pyavdr** [comment]
Curl is a problem.

I found a workarround and included in my /etc/hosts the IPV4 address:
176.9.217.52  download.nextcloud.com

it works.

**Comment by kesselb** [comment]
Smart workaround :+1: 

It's an interesting topic but i'm not sure if this is related to nextcloud? Look we use the network stack of your operating system. We don't enforce any ipv6 requests. I've done a bit research and found these links:

https://superuser.com/questions/403716/how-do-client-applications-know-to-use-ipv4-or-ipv6
https://unix.stackexchange.com/questions/90742/curl-with-ipv6-not-working-by-default
[https://github.com/curl/curl/issues/593](https://bit.ly/2m3mNj8)

Also tried `net.ipv6.conf.all.disable_ipv6 = 1` and `net.ipv6.conf.default.disable_ipv6 = 1` with https://github.com/nextcloud/vm/ and could not reproduce. The DNS-Request returns the address for ipv4 and ipv6 but `curl -Iv download.nextcloud.com` shows that only ipv4 is used if ipv6 is disabled.

**Comment by unnilennium** [comment]
you are right, found out the issue was firewall issue blocking  a ip range.

thanks for your time investigating.

it seems that curl was doing it good by trying ipv6 when unable to reach ipv4 ;)
