### ISSUE TITLE
Calendars don't load after Nextcloud 9 to 10 update

### ISSUE THREAD

**Issue by Cypouz** [nextcloud/server#1727]
### Steps to reproduce
1. Update from Nextcloud 9 to 10;
2. Go to Calendar app after enabled;
3. Continous spinning wheels. Calendars don't load.

### Expected behaviour
Calendars would be loaded and visible, without continous spinning wheels.

### Actual behaviour
No calendars loaded. Spinning wheels.

### Server configuration
**Operating system:** Debian 7

**Web server:** Apache 2.2

**Database:** MySQL 5.5

**PHP version:** 5.4

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** from Nextcloud 9.

**Where did you install Nextcloud from:** manual tarball.

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: true
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - systemtags
  - user_external
  - user_ldap
  - user_sam
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "51ef9990e685a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***\/data",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "log_rotate_size": 104857600,
        "memcache.local": "\\OC\\Memcache\\APC",
        "minimum.supported.desktop.version": 1.6,
        "theme": "",
        "maintenance": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "***REMOVED SENSITIVE VALUE***\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "***REMOVED SENSITIVE VALUE***\/nextcloud\/apps_user",
                "url": "\/apps_user",
                "writable": true
            }
        ],
        "appcodechecker": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no.

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45.4

**Operating system:** Debian 8

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"1hJgL5yTW1PoR6mSLJKy","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `id`, `uri`, `lastmodified`, `etag
`, `calendarid`, `size`, `calendardata`, `componenttype`, `classification` FROM `oc_calendarobjects` WHERE (`calendarid` = ?) AND (`uri` = ?)' with params [\\\"3\\\", \\\"20160418T225650Z-2780-1
000-1-11_***REMOVED SENSITIVE VALUE***-20160418T225701Z.ics\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'classification' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\Inv
alidFieldNameException\",\"Code\":0,\"Trace\":\"#0 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.p
hp(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DB
AL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/li
b\\\/private\\\/DB\\\/Connection.php(189): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 ***REMOVED SENSITIVE VALUE***\\\/nex
tcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(142): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(539): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(169): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->getCalendarObject('3', '20160418T225650...')\\n#7 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\CalDAV\\\\Calendar->getChild('20160418T225650...')\\n#8 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): Sabre\\\\DAV\\\\Tree->getNodeForPath('calendars\\\/Cyp\\\/c...')\\n#9 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(605): Sabre\\\\DAV\\\\Server->getPropertiesForPath('calendars\\\/Cyp\\\/c...', A
rray)\\n#10 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(236): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport))\\n#11 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport), 'calendars\\\/Cyp\\\/c...')\\n#12 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(716): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#17 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(184): Sabre\\\\DAV\\\\Server->exec()\\n#19 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#20 ***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/remote.php(165): require_once('***REMOVED SENSITIVE VALUE***...')\\n#21 {main}\",\"File\":\"***REMOVED SENSITIVE VALUE***\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"Cyp\"}","level":4,"time":"2016-10-12T21:42:14+00:00","method":"REPORT","url":"\/remote.php\/dav\/calendars\/Cyp\/***REMOVED SENSITIVE VALUE***\/","user":"Cyp"}
```
</details>

I have verified in the database table oc_calendarobjects, there is no column named "classification".

**Comment by Cypouz** [comment]
Same bug here: https://github.com/nextcloud/server/issues/1025

**Comment by nickvergessen** [comment]
Closing as duplicate
