### ISSUE TITLE
When moving a folder into my Nextcloud directory, files within subfolders will not sync

### ISSUE THREAD

**Issue by briankendall** [nextcloud/server#17424]
### Steps to reproduce
1. Setup Nextcloud desktop in macOS (preferably 10.14.6)
2. Execute the following terminal commands to create a folder with a subdirectory and some files and move it into the Nextcloud directory, replacing `/path/to/Nextcloud` with the path of the Nextcloud directory:

        mkdir test
        echo data > test/file.txt
        mkdir test/subdir
        echo moredata > test/subdir/missing_file1.txt
        echo stillmoredata > test/subdir/missing_file2.txt
        mv test /path/to/Nextcloud

3. Wait for Nextcloud Desktop to sync
4. Use the Nextcloud web interface to see what files were actually synced
5. Note that `missing_file1.txt` and `missing_file2.txt` are not synced!

### Expected behaviour
All files inside the directory are synced, including files inside all subdirectories

### Actual behaviour
Any files contained within a subdirectory are not synced

### Some more noteworthy info:

Moving `test` into the Nextcloud directory using the Finder also triggers the bug.

I can work around the bug by copying a folder into my Nextcloud directory instead of moving it.

I can also force Nextcloud to sync the missing files by using `touch` to change their modification dates, e.g.: `find /path/to/Nextcloud/test -exec touch {} \;`

### Server configuration

**Operating system**: macOS 10.12.6, docker 18.06.1-ce, docker-machine 0.15.0

**Web server:** Apache/2.4.38 (Debian)

**Database:** mysqld  Ver 10.3.17-MariaDB-0+deb10u1

**PHP version:** PHP 7.3.9-1~deb10u1

**Nextcloud version:** NextcloudPi docker v1.17.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Docker image

**Signing status:** No errors have been found.

**List of activated apps:**
```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.4
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 14.0.0
  - nextcloud_announcements: 1.5.0
  - nextcloudpi: 0.0.1
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.3
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**Nextcloud configuration:**

```
    {
        "system": {
            "passwordsalt": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "trusted_domains": {
                "0": "localhost",
                "11": "redacted",
                "1": "redacted",
                "5": "nextcloudpi.local",
                "7": "nextcloudpi",
                "8": "nextcloudpi.lan",
                "6": "redacted",
                "3": "redacted",
                "2": "redacted",
                "4": "redacted"
            },
            "datadirectory": "***REMOVED SENSITIVE VALUE***",
            "dbtype": "mysql",
            "version": "16.0.5.1",
            "overwrite.cli.url": "https:\/\/redacted\/",
            "dbname": "***REMOVED SENSITIVE VALUE***",
            "dbhost": "***REMOVED SENSITIVE VALUE***",
            "dbport": "",
            "dbtableprefix": "oc_",
            "mysql.utf8mb4": true,
            "dbuser": "***REMOVED SENSITIVE VALUE***",
            "dbpassword": "***REMOVED SENSITIVE VALUE***",
            "installed": true,
            "instanceid": "***REMOVED SENSITIVE VALUE***",
            "memcache.local": "\\OC\\Memcache\\Redis",
            "memcache.locking": "\\OC\\Memcache\\Redis",
            "redis": {
                "host": "***REMOVED SENSITIVE VALUE***",
                "port": 0,
                "timeout": 0,
                "password": "***REMOVED SENSITIVE VALUE***"
            },
            "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
            "mail_smtpmode": "sendmail",
            "mail_smtpauthtype": "LOGIN",
            "mail_from_address": "***REMOVED SENSITIVE VALUE***",
            "mail_domain": "***REMOVED SENSITIVE VALUE***",
            "preview_max_x": "2048",
            "preview_max_y": "2048",
            "jpeg_quality": "60",
            "overwriteprotocol": "https",
            "maintenance": false,
            "data-fingerprint": "f392db3bba68967e5d4434f6253c682b",
            "theme": "",
            "loglevel": 2
        }
    }


```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
There are no commands defined in the "ldap" namespace.
</details>

### Client configuration
**Browser:** Safari 12.1.12

**Operating system:** macOS 10.14.6

**Nextcloud Desktop version:** 2.6.0stable (build 20190927)

#### Web server

Here are the lines that appear in nc-access.log when I trigger the bug by moving `test` into the root of my Nextcloud directory:

```
10.0.2.2 - - [06/Oct/2019:03:21:19 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1216 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:20 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1215 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:21 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 300 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:22 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 299 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:25 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1215 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:26 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 297 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:27 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 299 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:30 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1446 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:30 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1215 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:32 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 299 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:35 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1180 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:37 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 447 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:40 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1216 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:42 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 300 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:43 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 298 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:44 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 10039 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:44 +0000] "MKCOL /remote.php/dav/files/bribri/test HTTP/1.1" 201 696 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:45 +0000] "MKCOL /remote.php/dav/files/bribri/test/subdir HTTP/1.1" 201 696 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:45 +0000] "PUT /remote.php/dav/files/bribri/test/file.txt HTTP/1.1" 201 805 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:45 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3601 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:48 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1400 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1216 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 298 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 10835 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/test HTTP/1.1" 207 1241 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/test HTTP/1.1" 207 2816 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/test/subdir HTTP/1.1" 207 1583 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "GET /remote.php/dav/files/bribri/test/file.txt HTTP/1.1" 200 950 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 5553 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:49 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1216 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:50 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1216 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:51 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 300 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:51 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 10671 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:51 +0000] "PROPFIND /remote.php/dav/files/bribri/test HTTP/1.1" 207 2816 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:52 +0000] "PROPFIND /remote.php/dav/files/bribri/test/subdir HTTP/1.1" 207 1583 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:21:52 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 300 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:22:00 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1446 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)"
10.0.2.2 - - [06/Oct/2019:03:22:00 +0000] "PROPFIND /remote.php/dav/files/bribri/ HTTP/1.1" 207 1380 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)"
```

error.log entries from past 24 hours: 
```
[Sat Oct 05 00:23:32.320036 2019] [mpm_event:notice] [pid 91:tid 139753468871808] AH00492: caught SIGWINCH, shutting down gracefully
[Sat Oct 05 00:27:49.028630 2019] [ssl:warn] [pid 90:tid 139925876757632] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sat Oct 05 00:27:49.059731 2019] [ssl:warn] [pid 91:tid 139925876757632] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sat Oct 05 00:27:49.061397 2019] [mpm_event:notice] [pid 91:tid 139925876757632] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Oct 05 00:27:49.061431 2019] [core:notice] [pid 91:tid 139925876757632] AH00094: Command line: '/usr/sbin/apache2'
[Sat Oct 05 00:43:05.404111 2019] [ssl:warn] [pid 90:tid 140266834105472] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sat Oct 05 00:43:05.434542 2019] [ssl:warn] [pid 91:tid 140266834105472] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sat Oct 05 00:43:05.436255 2019] [core:warn] [pid 91:tid 140266834105472] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Oct 05 00:43:05.437386 2019] [mpm_event:notice] [pid 91:tid 140266834105472] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Oct 05 00:43:05.437421 2019] [core:notice] [pid 91:tid 140266834105472] AH00094: Command line: '/usr/sbin/apache2'
[Sat Oct 05 20:06:37.640303 2019] [ssl:warn] [pid 90:tid 139820661970048] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sat Oct 05 20:06:37.675755 2019] [ssl:warn] [pid 91:tid 139820661970048] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sat Oct 05 20:06:37.676481 2019] [core:warn] [pid 91:tid 139820661970048] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Oct 05 20:06:37.677644 2019] [mpm_event:notice] [pid 91:tid 139820661970048] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Sat Oct 05 20:06:37.677681 2019] [core:notice] [pid 91:tid 139820661970048] AH00094: Command line: '/usr/sbin/apache2'
[Sun Oct 06 02:52:51.591352 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:51.641572 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:51.790509 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:51.831268 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:51.853898 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:52.941058 2019] [proxy_fcgi:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: app in /var/www/ncp-web/index.php on line 238PHP message: PHP Notice:  Undefined index: app in /var/www/ncp-web/index.php on line 244'
[Sun Oct 06 02:52:52.946984 2019] [authz_host:error] [pid 94:tid 139820389840640] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:52.947257 2019] [authz_host:error] [pid 94:tid 139820381439744] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /js/ncp.js failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:52.947524 2019] [authz_host:error] [pid 94:tid 139820398241536] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /js/minified.js failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:52.947682 2019] [authz_host:error] [pid 94:tid 139820373038848] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:52.947671 2019] [authz_host:error] [pid 94:tid 139820406642432] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:53.101252 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:53.124752 2019] [authz_host:error] [pid 94:tid 139820373038848] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:57.202741 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Sun Oct 06 02:52:57.222870 2019] [authz_host:error] [pid 94:tid 139820356237056] [client 10.0.2.2:49398] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
```

nc-error.log entries from past 24 hours: 
```
[Sat Oct 05 00:27:56.101546 2019] [proxy_fcgi:error] [pid 93:tid 139925638231808] [client 10.0.2.2:45948] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /data/nextcloud/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /data/nextcloud/lib/private/Memcache/Redis.php(54): Redis->get('83b27249f26a725...')\n#1 /data/nextcloud/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /data/nextcloud/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /data/nextcloud/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'RedisException:...', 3)\n#5 /data/nextcloud/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'RedisException:...', 3)\n#6 /data/nextcloud/lib/private/Log.php(130): OC\\Log->log(3, 'RedisException:...', Array)\n#7 /data/nextcloud/lib/private/Log/ErrorHandler.php(81): OC\\Log->critical('RedisException:...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onException(Object(RedisException))\n#9 {main}\n  thrown in /data/nextcloud/lib/private/Memcache/Redis.php on line 54PHP message: PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /data/nextcloud/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /data/nextcloud/lib/private/Memcache/Redis.php(54): Redis->get('83b27249f26a725...')\n#1 /data/nextcloud/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /data/nextcloud/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /data/nextcloud/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'Uncaught RedisE...', 3)\n#5 /data/nextcloud/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'Uncaught RedisE...', 3)\n#6 /data/nextcloud/lib/private/Log.php(130): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /data/nextcloud/lib/private/Log/ErrorHandler.php(68): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /data/nextcloud/lib/private/Memcache/Redis.php on line 54'
[Sat Oct 05 00:28:19.716132 2019] [authz_core:error] [pid 93:tid 139925345208064] [client 10.0.2.2:51142] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sat Oct 05 00:43:14.600192 2019] [authz_core:error] [pid 94:tid 140266358949632] [client 10.0.2.2:49355] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sat Oct 05 00:43:17.038074 2019] [proxy_fcgi:error] [pid 93:tid 140266350556928] [client 10.0.2.2:36693] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /data/nextcloud/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /data/nextcloud/lib/private/Memcache/Redis.php(54): Redis->get('83b27249f26a725...')\n#1 /data/nextcloud/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /data/nextcloud/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /data/nextcloud/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'RedisException:...', 3)\n#5 /data/nextcloud/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'RedisException:...', 3)\n#6 /data/nextcloud/lib/private/Log.php(130): OC\\Log->log(3, 'RedisException:...', Array)\n#7 /data/nextcloud/lib/private/Log/ErrorHandler.php(81): OC\\Log->critical('RedisException:...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onException(Object(RedisException))\n#9 {main}\n  thrown in /data/nextcloud/lib/private/Memcache/Redis.php on line 54PHP message: PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /data/nextcloud/lib/private/Memcache/Redis.php:54\nStack trace:\n#0 /data/nextcloud/lib/private/Memcache/Redis.php(54): Redis->get('83b27249f26a725...')\n#1 /data/nextcloud/lib/autoloader.php(150): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /data/nextcloud/lib/private/Log/File.php(105): spl_autoload_call('OC_User')\n#4 /data/nextcloud/lib/private/Log.php(329): OC\\Log\\File->write('PHP', 'Uncaught RedisE...', 3)\n#5 /data/nextcloud/lib/private/Log.php(218): OC\\Log->writeLog('PHP', 'Uncaught RedisE...', 3)\n#6 /data/nextcloud/lib/private/Log.php(130): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /data/nextcloud/lib/private/Log/ErrorHandler.php(68): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /data/nextcloud/lib/private/Memcache/Redis.php on line 54'
[Sat Oct 05 00:43:41.808836 2019] [authz_core:error] [pid 93:tid 140266461132544] [client 10.0.2.2:39893] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sat Oct 05 00:47:17.228011 2019] [authz_core:error] [pid 93:tid 140266233059072] [client 10.0.2.2:38429] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sat Oct 05 20:07:00.415182 2019] [authz_core:error] [pid 94:tid 139820143687424] [client 10.0.2.2:51110] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sat Oct 05 20:08:52.989458 2019] [authz_core:error] [pid 93:tid 139820076545792] [client 10.0.2.2:58006] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sat Oct 05 20:10:35.489947 2019] [authz_core:error] [pid 93:tid 139820118509312] [client 10.0.2.2:39131] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Sun Oct 06 02:53:39.469737 2019] [authz_core:error] [pid 94:tid 139820398241536] [client 10.0.2.2:49422] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
```

#### Nextcloud log (data/nextcloud.log)
```There are no log entries for the day I triggered this bug, nor any entries for the past several days.```

**Comment by swingpatrol** [comment]
I have the same problem.
In my case, another way to force the correct sync of missing files is to stop/start the Nextcloud client.

server: Nextcloud 7.0.0 on Debian 9.11 (Apache 2.4.39, TLSv.1.3, PHP 7.3, MariaDB 10.3)
client: Nextcloud-2.6.0.20190927 on macOS 10.14.6

**Comment by briankendall** [comment]
This is a desktop bug and should not have been created here. I'm closing this and opening a new bug in nextcloud/desktop
