### ISSUE TITLE
Upgrade failed from 16.0.5 to 17.0.2

### ISSUE THREAD

**Issue by donb9000** [nextcloud/server#18657]
### Steps to reproduce
1. Have installed and running 16.0.5
2. Upgrade to 17.0.2 (Archlinux update via pacman)
3. Run via pacman hook: /usr/bin/runuser -u http -- /usr/bin/php /usr/share/webapps/nextcloud/occ upgrade

<details>
<summary>Output of pacman hook</summary>

```:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Update Nextcloud installation
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: announcementcenter
Disabled incompatible app: files_texteditor
Disabled incompatible app: spreed
Updating <accessibility> ...
Updated <accessibility> to 1.3.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.7.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 1.6.0
Updating <files_rightclick> ...
Updated <files_rightclick> to 0.14.2
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.6.0
Updating <gallery> ...
Updated <gallery> to 18.4.0
Updating <logreader> ...
Updated <logreader> to 2.2.0
Updating <password_policy> ...
Updated <password_policy> to 1.7.0
Updating <privacy> ...
Updated <privacy> to 1.1.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.7.0
Updating <recommendations> ...
Updated <recommendations> to 0.5.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.7.0
Updating <support> ...
Updated <support> to 1.0.1
Updating <survey_client> ...
Updated <survey_client> to 1.5.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.6.0
Updating <updatenotification> ...
Updated <updatenotification> to 1.7.0
Updating <viewer> ...
Updated <viewer> to 1.2.0
Updating <federation> ...
Updated <federation> to 1.7.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.5.0
Updating <oauth2> ...
Updated <oauth2> to 1.5.0
Updating <files> ...
Updated <files> to 1.12.0
Updating <activity> ...
Updated <activity> to 2.10.1
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.0.0
Updating <dav> ...
Fix broken values of calendar objects

 Starting ...
    0/0 [>---------------------------]   0%
Updated <dav> to 1.13.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.9.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.7.0
Updating <files_versions> ...
Updated <files_versions> to 1.10.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.7.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.7.0
Updating <comments> ...
Updated <comments> to 1.7.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.6.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.6.0
Updating <notifications> ...
Updated <notifications> to 2.5.0
Updating <systemtags> ...
Updated <systemtags> to 1.7.0
Updating <theming> ...
Updated <theming> to 1.8.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app apporder in appstore
Checked for update of app "apporder" in appstore
Checking for update of app bookmarks in appstore
Checked for update of app "bookmarks" in appstore
Checking for update of app bruteforcesettings in appstore
Checked for update of app "bruteforcesettings" in appstore
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore
Checking for update of app carnet in appstore
Checked for update of app "carnet" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app dicomviewer in appstore
Checked for update of app "dicomviewer" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_rightclick in appstore
Update app files_rightclick from appstore
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OC_App::executeRepairSteps() must be of the type array, null given, called in /usr/share/webapps/nextcloud/lib/private/legacy/app.php on line 905 and defined in /usr/share/webapps/nextcloud/lib/private/legacy/app.php:957
Stack trace:
#0 /usr/share/webapps/nextcloud/lib/private/legacy/app.php(905): OC_App::executeRepairSteps('files_rightclic...', NULL)
#1 /usr/share/webapps/nextcloud/lib/private/Installer.php(194): OC_App::updateApp('files_rightclic...')
#2 /usr/share/webapps/nextcloud/lib/private/Updater.php(450): OC\Installer->updateAppstoreApp('files_rightclic...')
#3 /usr/share/webapps/nextcloud/lib/private/Updater.php(258): OC\Updater->upgradeAppStoreApps(Array)
#4 /usr/share/webapps/nextcloud/lib/private/Updater.php(128): OC\Updater->doUpgrade('17.0.2.1', '16.0.5.1')
#5 /usr/share/webapps/nextcloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#6 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/share/webapps/nextcloud/console.php(97): OC\Console\Application->run()
#12 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
#13 {main}
#13 {main}
error: command failed to execute correctly
```
</details>

<details>
<summary>Attempted repair via command line</summary>

```
[root@monster nextcloud]# runuser -u http -- ./occ maintenance:repair
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
 - Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Move .step file of updater to backup location
 - Fix potential broken mount points
     - No mounts updated
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - SCSS cache cleared
     - JS cache cleared
 - Clear every generated avatar on major updates
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Cleanup invalid photocache files for carddav
 - Add background job to cleanup login flow v2 tokens
 - Remove potentially over exposing share links
     - No need to remove link shares.
 - Clear access cache of projects
 - Cleanup cypress files from viewer app
 - Switches from deprecated "production" to "stable" update channel
 - Sets the enterprise logo
 - Fix component of birthday calendars
     - 6 birthday calendars updated.
 - Regenerating birthday calendars to use new icons and fix old birthday events without year
     - Repair step already executed
 - Fix broken values of calendar objects
    0 [>---------------------------]
 - Registering building of calendar search index as background job
     - Repair step already executed
 - Registering background jobs to update cache for webcal calendars
     - Added 0 background jobs to update webcal calendars
 - Registering building of calendar reminder index as background job
     - Repair step already executed
 - Clean up orphan event and contact data
     - 0 events without a calendar have been cleaned up
     - 0 properties without an events have been cleaned up
     - 0 changes without a calendar have been cleaned up
     - 0 cached events without a calendar subscription have been cleaned up
     - 0 changes without a calendar subscription have been cleaned up
     - 0 contacts without an addressbook have been cleaned up
     - 0 properties without a contact have been cleaned up
     - 0 changes without an addressbook have been cleaned up
 - Remove activity entries of private events
     - Removed 0 activity entries
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Update OAuth token expiration times
 - Passwords Legacy Database Migration
     - Legacy migration not available for version 2019.12.1
 - Duplicate Object Deletion
 - Repair Passwords Database Objects
     - Checking 0 tag revisions
    0 [>---------------------------]
     - Fixed 0 tag revisions
     - Checking 10 folder revisions
 10/10 [============================] 100%
     - Fixed 0 folder revisions
     - Checking 135 password revisions
 135/135 [============================] 100%
     - Fixed 0 password revisions
     - Checking 0 tag models
    0 [>---------------------------]
     - Fixed 0 tag models
     - Checking 9 folder models
 9/9 [============================] 100%
     - Fixed 0 folder models
     - Checking 89 password models
 89/89 [============================] 100%
     - Fixed 0 password models
     - Checking 0 password tag relations
    0 [>---------------------------]
     - Fixed 0 password tag relations
 - Add background job to check for backup codes
[root@monster nextcloud]# runuser -u http -- ./occ maintenance:mode --off
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
[root@monster nextcloud]# runuser -u http -- ./occ maintenance:mode --on
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode enabled
[root@monster nextcloud]# runuser -u http -- ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
UnexpectedValueException: The files of the app "files_rightclick" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Reset log level
[root@monster nextcloud]# runuser -u http -- ./occ maintenance:mode --off
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
[root@monster nextcloud]# runuser -u http -- ./occ maintenance:mode --on
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode enabled
```
</details>

### Expected behaviour
Upgrade should succeed and Nextcloud 17 should be accessible

### Actual behaviour
Upgrade failed. Login page is inaccessible.

### Server configuration

**Operating system:** Archlinux

**Web server:** nginx-mainline 1.17.7-1

**Database:** mariadb 10.4.11-1

**PHP version:** php 7.3.12-1

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 16.0.5

**Where did you install Nextcloud from:** Archlinux package repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Web Access Not Available
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

[root@monster nextcloud]# runuser -u http -- ./occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - carnet: 0.19.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - dicomviewer: 1.2.1
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - passwords: 2019.12.1
  - phonetrack: 0.5.2
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - unsplash: 1.1.4
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - weather: 1.6.4
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - announcementcenter
  - encryption
  - files_external
  - spreed
  - text
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

[root@monster nextcloud]# runuser -u http -- ./occ config:list system
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "monster.bostrom.org",
            "gremlin.homelinux.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "apporder",
        "overwrite.cli.url": "http:\/\/monster.bostrom.org\/nextcloud",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "logtimezone": "UTC",
        "log_rotate_size": 16777216,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "asset-pipeline.enabled": false,
        "session_lifetime": 21600,
        "session_keepalive": true,
        "installed": true,
        "theme": "",
        "maintenance": true,
        "htaccess.RewriteBase": "\/nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true,
        "mysql.utf8mb4": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 71.0

**Operating system:** Archlinux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No entries in /var/log/nginx/error.log from today
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
[nextcloud.log](https://github.com/nextcloud/server/files/4022037/nextcloud.log)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

N/A
```
</details>

**Comment by kesselb** [comment]
Replace `apps/files_rightclick` with the version from https://download.nextcloud.com/server/releases/latest-17.zip.

**Comment by donb9000** [comment]
> Replace `apps/files_rightclick` with the version from https://download.nextcloud.com/server/releases/latest-17.zip.

After doing this, should I run `occ upgrade` again, or `occ maintenance:repair`, or nothing?

**Comment by kesselb** [comment]
Run both ;)

**Comment by donb9000** [comment]
Thank you very much. I replaced the `apps/files_rightclick` directory as you instructed, ran `upgrade` and then `maintenance:repair`.

I am now able to use Nextcloud normally.
