### ISSUE TITLE
Argument 1 passed to OC\Security\Crypto::decrypt()

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/server#18931]
Similar but not the same trace than https://github.com/nextcloud/server/pull/16782

- NC 17.0.2
- PHP-FPM 7.3.13

```
[cron] Error: TypeError: Argument 1 passed to OC\Security\Crypto::decrypt() must be of the type string, bool given,
called in /srv/lib/private/Security/IdentityProof/Manager.php on line 113 at <<closure>>

0. /srv/lib/private/Security/IdentityProof/Manager.php line 113
   OC\Security\Crypto->decrypt("*** sensitive parameters replaced ***")
1. /srv/lib/private/Security/IdentityProof/Manager.php line 130
   OC\Security\IdentityProof\Manager->retrieveKey("user-u221218")
2. /srv/lib/private/Security/IdentityProof/Signer.php line 62
   OC\Security\IdentityProof\Manager->getKey(OC\User\User {})
3. /srv/apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php line 142
   OC\Security\IdentityProof\Signer->sign("lookupserver", {federationId: " ... "}, OC\User\User {})
4. /srv/lib/public/BackgroundJob/Job.php line 77
   OCA\LookupServerConnector\BackgroundJobs\RetryJob->run({userId: "u221218"})
5. /srv/apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php line 105
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
6. /srv/cron.php line 124
   OCA\LookupServerConnector\BackgroundJobs\RetryJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

**Comment by mundschenk-at** [comment]
I get the same error when trying to use `occ encryption:migrate-key-storage-format` on NC 20.0.5.

**Comment by linoskoczek** [comment]
I got the same error on my NextCloud 20.0.7
```
$ docker exec -i nextcloud occ encryption:migrate-key-storage-format
Updating key storage format
Start to update the keys:
    0 [>---------------------------]An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Security\Crypto::decrypt() must be of the type string, bool given, called in /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php on line 187 and defined in /config/www/nextcloud/lib/private/Security/Crypto.php:113
Stack trace:
#0 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(187): OC\Security\Crypto->decrypt()
#1 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#2 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#3 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#4 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#5 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#6 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#7 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#8 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#9 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(167): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#10 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(258): OC\Core\Command\Encryption\MigrateKeyStorage->traverseFileKeys()
#11 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(234): OC\Core\Command\Encryption\MigrateKeyStorage->updateUserKeys()
#12 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(101): OC\Core\Command\Encryption\MigrateKeyStorage->updateUsersKeys()
#13 /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php(83): OC\Core\Command\Encryption\MigrateKeyStorage->updateKeys()
#14 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Encryption\MigrateKeyStorage->execute()
#15 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#16 /config/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#17 /config/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#18 /config/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#19 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#21 {main}
```

**Comment by xn--nding-jua** [comment]
On trying to migrate my keystore with command `occ encryption:migrate-key-storage-format` I faced the same problem:
`OC\Security\Crypto::decrypt() must be of the type string, bool given, called in /config/www/nextcloud/core/Command/Encryption/MigrateKeyStorage.php on line 187`

I found that this problem is related with several old file-entries within the SQL-database, but files and/or folder have been deleted long ago without deleting the entry in the database. To find these zombies, I've edited MigrateKeyStorage.php and inserted the following command before line 187 to output the affected file:
`if (is_bool($content)) {
  echo $path;
}`

First check if the presented files are present or not. If not, open your SQL-editor and search for the specific entries in the table oc_filecache. Then delete the entries with `DELETE FROM "oc_filecache" WHERE "path" LIKE "%FULLPATHTOMISSINGFILE%";` (remeber to delete both files/ and files_encryption/keys/files/) and re-run the key-migration. You have to do this all over the time until all zombie-entries are gone. For me about 10 entries were responsible for the problem.

Drawback of this solution: you have to restart the process all over again on each missing file... maybe someone has a better idea?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
Here is a fix mentioned: https://github.com/nextcloud/server/issues/26562#issuecomment-822780572

**Comment by Meistache** [comment]
Still happening on NC21.0.3, fix mentioned by @szaimen working properly.

**Comment by Eeems** [comment]
I'm also encountering this on NC 21.0.3. I'll update to latest, check to see if it's still happening and then I guess I'll use @xn--nding-jua's workaround
