### ISSUE TITLE
update v18 max key length is 1000 bytes

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#19175]
### Steps to reproduce
start occ upgrade
wait for the step "Updating <user_ldap> ...

### Expected behaviour
The update runs smoothly through

### Actual behaviour
The update stops with the following message:

> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_ldap_user_mapping CHANGE `owncloud_name` `owncloud_name` VARCHAR(255) DEFAULT '' NOT NULL, CHANGE `ldap_dn` `ldap_dn` VARCHAR(255) DEFAULT '' NOT NULL, CHANGE `directory_uuid` `directory_uuid` VARCHAR(255) DEFAULT '' NOT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
Update failed

![image](https://user-images.githubusercontent.com/12276250/73267005-fef92d00-41cf-11ea-9294-e846cda5ce6c.png)

## Server configuration detail

**Operating system:** Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.1.43

**PHP version:** 

7.3.14-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.2 - 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => ae47d266712d250a6210b68b92072f39d0c99283507d6e63db83fc891af9a316e9e394af094d0b7f8f2920c4c3534bb362c11390ee974abd4fe7e21c51a87a8f
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - bruteforcesettings: 1.5.0
 - circles: 0.17.10
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_accesscontrol: 1.7.0
 - files_automatedtagging: 1.7.0
 - files_downloadactivity: 1.6.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - groupfolders: 5.0.5
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - quota_warning: 1.6.0
 - ransomware_protection: 1.5.1
 - richdocuments: 3.5.1
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.2
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.2
 - twofactor_u2f: 5.0.2
 - updatenotification: 1.7.0
 - user_ldap: 1.7.0
 - user_usage_report: 1.1.2
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - firstrunwizard
 - gallery
 - recommendations

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "mmmbox.mmmgroup.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/www\/mmmbox-data\/_skeleton",
    "tempdirectory": "\/tmp\/nextcloud",
    "dbtype": "mysql",
    "version": "17.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "loglevel": 3,
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "d.m.y H:i:s",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "forcessl": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "ldapUserCleanupInterval": 51,
    "lost_password_link": "https:\/\/www.mmmgroup.com\/de\/user\/password",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/mmmbox.mmmgroup.com",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "default_language": "de",
    "default_locale": "de",
    "trashbin_retention_obligation": "auto, 60",
    "versions_retention_obligation": "auto, 60",
    "theme": "mmmbox",
    "simpleSignUpLink": "false",
    "activity_expire_days": "90"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 0background_sync_prefix: s01bgjUpdateGroupsLastRun: 1380561887cleanUpJobOffset: 350enabled: yesenforce_home_folder_naming_rule: installed_version: 1.7.0s01_lastChange: 1579567503s01has_memberof_filter_support: s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: SGVybWVzbW1tKioyMDE0s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: dc=mmmgroup,dc=coms01ldap_base_groups: ou=groups-mmmbox,dc=mmmgroup,dc=coms01ldap_base_users: ou=people-services,dc=mmmgroup,dc=coms01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: cn=admin,dc=mmmgroup,dc=coms01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 1s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=posixGroup)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: memberUids01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: posixGroups01ldap_host: ldap://services.mmmgroup.coms01ldap_login_filter: (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 1s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: nones01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: inetOrgPersons01ldap_userlist_filter: (|(objectclass=inetOrgPerson))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
2020/01/28 13:36:42 [error] 21662#21662: *587363 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"1i7SyADwFOZI6UJYJcdy","level":3,"time":"2020-01-28T12:36:42+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/admin.php","message":"touch(): Utime failed: Permission denied at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Config.php#240","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"1i7SyADwFOZI6UJYJcdy","level":3,"time":"2020-01-28T12:36:42+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/admin.php","message":"fopen(\/var\/www\/nexttest.mmmgroup.com\/config\/config.php): failed to open stream: Permission denied at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Config.php#241","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"1i7SyADwFOZI6UJYJcdy","level":3,"time":"2020-01-28T12:36:42+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/admin.php","message":"chmod(): Operation not permitted at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Config.php#244","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"1i7SyADwFOZ
2020/01/28 13:36:42 [error] 21662#21662: *587363 FastCGI sent in stderr: ":42+00:00","remoteAddr":"212.211.192.4","user":"--","app":"index","method":"GET","url":"\/admin.php","message":{"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occurred in driver: could not find driver","Code":0,"Trace":[{"file":"\/var\/www\/nexttest.mmmgroup.com\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1040,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"\/var\/www\/nexttest.mmmgroup.com\/lib\/private\/DB\/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["PRAGMA read_uncommitted = 1",[],[]]},{"file":"\/var\/www\/nexttest.mmmgroup.com\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":683,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["PRAGMA read_uncommitted = 1"]},{"file":"\/var\/www\/nexttes" while reading response header from upstream, client: 212.211.192.4, server: nexttest.mmmgroup.com, request: "GET /admin.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "nexttest.mmmgroup.com"
2020/01/28 13:36:42 [error] 21662#21662: *587363 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"1i7SyADwFOZI6UJYJcdy","level":3,"time":"2020-01-28T12:36:42+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/admin.php","message":"fileperms(): stat failed for \/var\/www\/nexttest.mmmgroup.com\/data\/nextcloud.log at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Log\/File.php#85","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: {"reqId":"1i7SyADwFOZI6UJYJcdy","level":3,"time":"2020-01-28T12:36:42+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/admin.php","message":"chmod(): No such file or directory at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Log\/File.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}" while reading upstream, client: 212.211.192.4, server: nexttest.mmmgroup.com, request: "GET /admin.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "nexttest.mmmgroup.com"
2020/01/28 13:36:52 [error] 21662#21662: *587397 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"zaedfrtx5MkVZqCAlHDY","level":3,"time":"2020-01-28T12:36:52+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/settings\/apps","message":"touch(): Utime failed: Permission denied at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Config.php#240","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"zaedfrtx5MkVZqCAlHDY","level":3,"time":"2020-01-28T12:36:52+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/settings\/apps","message":"fopen(\/var\/www\/nexttest.mmmgroup.com\/config\/config.php): failed to open stream: Permission denied at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Config.php#241","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"zaedfrtx5MkVZqCAlHDY","level":3,"time":"2020-01-28T12:36:52+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/settings\/apps","message":"chmod(): Operation not permitted at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Config.php#244","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqI
2020/01/28 13:36:52 [error] 21662#21662: *587397 FastCGI sent in stderr: ","time":"2020-01-28T12:36:52+00:00","remoteAddr":"212.211.192.4","user":"--","app":"index","method":"GET","url":"\/settings\/apps","message":{"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occurred in driver: could not find driver","Code":0,"Trace":[{"file":"\/var\/www\/nexttest.mmmgroup.com\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1040,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"\/var\/www\/nexttest.mmmgroup.com\/lib\/private\/DB\/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["PRAGMA read_uncommitted = 1",[],[]]},{"file":"\/var\/www\/nexttest.mmmgroup.com\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":683,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["PRAGMA read_uncommitted = 1"]},{"file":"\/var\/www\/ne" while reading response header from upstream, client: 212.211.192.4, server: nexttest.mmmgroup.com, request: "GET /settings/apps HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "nexttest.mmmgroup.com"
2020/01/28 13:36:52 [error] 21662#21662: *587397 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nexttest.mmmgroup.com/data/nextcloud.log in /var/www/nexttest.mmmgroup.com/lib/private/Log/File.php on line 85PHP message: {"reqId":"zaedfrtx5MkVZqCAlHDY","level":3,"time":"2020-01-28T12:36:52+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/settings\/apps","message":"fileperms(): stat failed for \/var\/www\/nexttest.mmmgroup.com\/data\/nextcloud.log at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Log\/File.php#85","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}PHP message: {"reqId":"zaedfrtx5MkVZqCAlHDY","level":3,"time":"2020-01-28T12:36:52+00:00","remoteAddr":"212.211.192.4","user":"--","app":"PHP","method":"GET","url":"\/settings\/apps","message":"chmod(): No such file or directory at \/var\/www\/nexttest.mmmgroup.com\/lib\/private\/Log\/File.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":""}" while reading upstream, client: 212.211.192.4, server: nexttest.mmmgroup.com, request: "GET /settings/apps HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "nexttest.mmmgroup.com"

```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"M9vtceMjB9qnK4eWMWcm","level":4,"time":"28.01.20 14:04:08","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Failed to update database structure (PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88\nStack trace:\n#0 /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(88): PDO->query('ALTER TABLE oc_...')\n#1 /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1010): Doctrine\\DBAL\\Driver\\PDOConnection->query('ALTER TABLE oc_...')\n#2 /var/www/nexttest.mmmgroup.com/lib/private/DB/Migrator.php(262): Doctrine\\DBAL\\Connection->query('ALTER TABLE oc_...')\n#3 /var/www/nexttest.mmmgroup.com/lib/private/DB/Migrator.php(85): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#4 /var/www/nexttest.mmmgroup.com/lib/private/DB/MDB2SchemaManager.php(123): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#5 /var/www/nexttest.mmmgroup.com/lib/private/legacy/db.php(189): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('/var/www/nextte...')\n#6 /var/www/nexttest.mmmgroup.com/lib/private/legacy/app.php(912): OC_DB::updateDbFromStructure('/var/www/nextte...')\n#7 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(376): OC_App::updateApp('user_ldap')\n#8 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(255): OC\\Updater->doAppUpgrade()\n#9 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(131): OC\\Updater->doUpgrade('18.0.0.10', '17.0.2.1')\n#10 /var/www/nexttest.mmmgroup.com/core/Command/Upgrade.php(257): OC\\Updater->upgrade()\n#11 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Command/Command.php(255): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(915): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /var/www/nexttest.mmmgroup.com/lib/private/Console/Application.php(214): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 /var/www/nexttest.mmmgroup.com/console.php(99): OC\\Console\\Application->run()\n#17 /var/www/nexttest.mmmgroup.com/occ(11): require_once('/var/www/nextte...')\n#18 {main}\n\nNext Doctrine\\DBAL\\Driver\\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:90\nStack trace:\n#0 /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1010): Doctrine\\DBAL\\Driver\\PDOConnection->query('ALTER TABLE oc_...')\n#1 /var/www/nexttest.mmmgroup.com/lib/private/DB/Migrator.php(262): Doctrine\\DBAL\\Connection->query('ALTER TABLE oc_...')\n#2 /var/www/nexttest.mmmgroup.com/lib/private/DB/Migrator.php(85): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#3 /var/www/nexttest.mmmgroup.com/lib/private/DB/MDB2SchemaManager.php(123): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#4 /var/www/nexttest.mmmgroup.com/lib/private/legacy/db.php(189): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('/var/www/nextte...')\n#5 /var/www/nexttest.mmmgroup.com/lib/private/legacy/app.php(912): OC_DB::updateDbFromStructure('/var/www/nextte...')\n#6 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(376): OC_App::updateApp('user_ldap')\n#7 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(255): OC\\Updater->doAppUpgrade()\n#8 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(131): OC\\Updater->doUpgrade('18.0.0.10', '17.0.2.1')\n#9 /var/www/nexttest.mmmgroup.com/core/Command/Upgrade.php(257): OC\\Updater->upgrade()\n#10 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Command/Command.php(255): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(915): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /var/www/nexttest.mmmgroup.com/lib/private/Console/Application.php(214): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /var/www/nexttest.mmmgroup.com/console.php(99): OC\\Console\\Application->run()\n#16 /var/www/nexttest.mmmgroup.com/occ(11): require_once('/var/www/nextte...')\n#17 {main}\n\nNext Doctrine\\DBAL\\Exception\\DriverException: An exception occurred while executing 'ALTER TABLE oc_ldap_user_mapping CHANGE `owncloud_name` `owncloud_name` VARCHAR(255) DEFAULT '' NOT NULL, CHANGE `ldap_dn` `ldap_dn` VARCHAR(255) DEFAULT '' NOT NULL, CHANGE `directory_uuid` `directory_uuid` VARCHAR(255) DEFAULT '' NOT NULL':\n\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106\nStack trace:\n#0 /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 /var/www/nexttest.mmmgroup.com/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1012): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'ALTER TABLE oc_...')\n#3 /var/www/nexttest.mmmgroup.com/lib/private/DB/Migrator.php(262): Doctrine\\DBAL\\Connection->query('ALTER TABLE oc_...')\n#4 /var/www/nexttest.mmmgroup.com/lib/private/DB/Migrator.php(85): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#5 /var/www/nexttest.mmmgroup.com/lib/private/DB/MDB2SchemaManager.php(123): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#6 /var/www/nexttest.mmmgroup.com/lib/private/legacy/db.php(189): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('/var/www/nextte...')\n#7 /var/www/nexttest.mmmgroup.com/lib/private/legacy/app.php(912): OC_DB::updateDbFromStructure('/var/www/nextte...')\n#8 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(376): OC_App::updateApp('user_ldap')\n#9 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(255): OC\\Updater->doAppUpgrade()\n#10 /var/www/nexttest.mmmgroup.com/lib/private/Updater.php(131): OC\\Updater->doUpgrade('18.0.0.10', '17.0.2.1')\n#11 /var/www/nexttest.mmmgroup.com/core/Command/Upgrade.php(257): OC\\Updater->upgrade()\n#12 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Command/Command.php(255): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(915): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /var/www/nexttest.mmmgroup.com/3rdparty/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 /var/www/nexttest.mmmgroup.com/lib/private/Console/Application.php(214): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 /var/www/nexttest.mmmgroup.com/console.php(99): OC\\Console\\Application->run()\n#18 /var/www/nexttest.mmmgroup.com/occ(11): require_once('/var/www/nextte...')\n#19 {main})","userAgent":"--","version":"17.0.2.1"}

```
</details>

<details><summary>Browser log</summary>

Nothing
</details>

**Comment by kesselb** [comment]
Check for possible solutions: https://github.com/nextcloud/server/issues/17975
