### ISSUE TITLE
Function ldap_control_paged_result_response() is deprecated .../user_ldap/lib/LDAP.php

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#19187]
### Steps to reproduce
dont know

### Expected behaviour
dont know

### Actual behaviour
The log is flooded with the error message

## Server configuration detail

**Operating system:** Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.1.43

**PHP version:** 

7.4.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.0 - 18.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - bruteforcesettings: 1.5.0
 - circles: 0.18.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_downloadactivity: 1.7.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - groupfolders: 6.0.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - ransomware_protection: 1.6.0
 - richdocuments: 3.5.1
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.1
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.2
 - twofactor_u2f: 5.0.2
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - user_usage_report: 1.2.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - firstrunwizard
 - recommendations
 - text

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "DOMAIN"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/www\/data\/_skeleton",
    "tempdirectory": "\/tmp\/nextcloud",
    "dbtype": "mysql",
    "version": "18.0.0.10",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "loglevel": 3,
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "d.m.y H:i:s",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "forcessl": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "ldapUserCleanupInterval": 51,
    "lost_password_link": "https:\/\/DOMAIN\/de\/user\/password",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/DOMAIN",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "default_language": "de",
    "default_locale": "de",
    "trashbin_retention_obligation": "auto, 60",
    "versions_retention_obligation": "auto, 60",
    "theme": "mmmbox",
    "simpleSignUpLink": "false",
    "activity_expire_days": "90"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 500background_sync_prefix: s01bgjUpdateGroupsLastRun: 1380561887cleanUpJobOffset: 300enabled: yesenforce_home_folder_naming_rule: installed_version: 1.8.0s01_lastChange: 1579567503s01has_memberof_filter_support: s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: SGVybWVzbW1tKioyMDE0s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: dc=DCDOMAIN,dc=coms01ldap_base_groups: ou=groups-mmmbox,dc=DCDOMAIN,dc=coms01ldap_base_users: ou=people-services,dc=DCDOMAIN,dc=coms01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: cn=admin,dc=DCDOMAIN,dc=coms01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 1s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=posixGroup)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: memberUids01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: posixGroups01ldap_host: ldap://services.DCDOMAIN.coms01ldap_login_filter: (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 1s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: nones01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: inetOrgPersons01ldap_userlist_filter: (|(objectclass=inetOrgPerson))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
found nothing
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"PDpopcX4PE743gQTVc3X","level":3,"time":"29.01.20 09:04:11","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"GET","url":"/settings/admin/activity","message":"Trying to access array offset on value of type null at WEBPATH/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.0.10"}
{"reqId":"k6kqC9XnjiDGR9s1AI9j","level":3,"time":"29.01.20 09:04:13","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=11111","message":"Trying to access array offset on value of type null at WEBPATH/apps/logreader/lib/Log/LogIterator.php#78","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.0.10"}
{"reqId":"k6kqC9XnjiDGR9s1AI9j","level":3,"time":"29.01.20 09:04:13","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=11111","message":"Trying to access array offset on value of type null at WEBPATH/apps/logreader/lib/Log/LogIterator.php#78","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.0.10"}
{"reqId":"TaKZuYnTA2FSnczv3A1i","level":3,"time":"29.01.20 09:04:15","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/UUID/","message":"Function ldap_control_paged_result() is deprecated at WEBPATH/apps/user_ldap/lib/LDAP.php#310","userAgent":"Mozilla/5.0 (Windows) mirall/2.6.2stable-Win64 (build 20191224) (Nextcloud)","version":"18.0.0.10"}
{"reqId":"TaKZuYnTA2FSnczv3A1i","level":3,"time":"29.01.20 09:04:15","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/UUID/","message":"Function ldap_control_paged_result() is deprecated at WEBPATH/apps/user_ldap/lib/LDAP.php#310","userAgent":"Mozilla/5.0 (Windows) mirall/2.6.2stable-Win64 (build 20191224) (Nextcloud)","version":"18.0.0.10"}
{"reqId":"TaKZuYnTA2FSnczv3A1i","level":3,"time":"29.01.20 09:04:15","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/UUID/","message":"Function ldap_control_paged_result_response() is deprecated at WEBPATH/apps/user_ldap/lib/LDAP.php#75","userAgent":"Mozilla/5.0 (Windows) mirall/2.6.2stable-Win64 (build 20191224) (Nextcloud)","version":"18.0.0.10"}
{"reqId":"efjsnlwKpXBgJnfc7XBc","level":3,"time":"29.01.20 09:04:17","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=11111","message":"Trying to access array offset on value of type null at WEBPATH/apps/logreader/lib/Log/LogIterator.php#78","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.0.10"}
{"reqId":"efjsnlwKpXBgJnfc7XBc","level":3,"time":"29.01.20 09:04:17","remoteAddr":"212.211.192.4","user":"UUID","app":"PHP","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=11111","message":"Trying to access array offset on value of type null at WEBPATH/apps/logreader/lib/Log/LogIterator.php#78","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.0.10"}
```
</details>

<details><summary>Browser log</summary>

found nothing
</details>

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/19127

**Comment by Bubbelb** [comment]
I have the same issue. It seems like it has to do with PHP 7.4
Tasks like occ files:scan throws a deprecated warning when scanning a single user. When scanning all users (with the --all option) the following error occurs:
```
Exception during scan: Function ldap_control_paged_result() is deprecated
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler()
#1 /usr/share/webapps/nextcloud/apps/user_ldap/lib/LDAP.php(310): call_user_func_array()
#2 /usr/share/webapps/nextcloud/apps/user_ldap/lib/LDAP.php(89): OCA\User_LDAP\LDAP->invokeLDAPMethod()
#3 [internal function]: OCA\User_LDAP\LDAP->controlPagedResult()
#4 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Access.php(1125): call_user_func_array()
#5 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Access.php(1129): OCA\User_LDAP\Access->OCA\User_LDAP\{closure}()
#6 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Access.php(1957): OCA\User_LDAP\Access->invokeLDAPMethod()
#7 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Access.php(203): OCA\User_LDAP\Access->abandonPagedSearch()
#8 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Group_LDAP.php(523): OCA\User_LDAP\Access->readAttribute()
#9 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Group_LDAP.php(547): OCA\User_LDAP\Group_LDAP->getEntryGroupID()
#10 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Group_LDAP.php(628): OCA\User_LDAP\Group_LDAP->getUserPrimaryGroupIDs()
#11 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Group_LDAP.php(665): OCA\User_LDAP\Group_LDAP->getUserPrimaryGroup()
#12 /usr/share/webapps/nextcloud/apps/user_ldap/lib/Group_Proxy.php(125): OCA\User_LDAP\Group_LDAP->getUserGroups()
#13 /usr/share/webapps/nextcloud/lib/private/Group/Manager.php(283): OCA\User_LDAP\Group_Proxy->getUserGroups()
#14 /usr/share/webapps/nextcloud/lib/private/Group/Manager.php(270): OC\Group\Manager->getUserIdGroups()
#15 /usr/share/webapps/nextcloud/lib/private/Group/Manager.php(334): OC\Group\Manager->getUserGroups()
#16 /usr/share/webapps/nextcloud/apps/files_external/lib/Service/UserGlobalStoragesService.php(187): OC\Group\Manager->getUserGroupIds()
#17 /usr/share/webapps/nextcloud/apps/files_external/lib/Config/ConfigAdapter.php(128): OCA\Files_External\Service\UserGlobalStoragesService->getAllStoragesForUser()
#18 /usr/share/webapps/nextcloud/lib/private/Files/Config/MountProviderCollection.php(104): OCA\Files_External\Config\ConfigAdapter->getMountsForUser()
#19 /usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php(448): OC\Files\Config\MountProviderCollection->addMountForUser()
#20 /usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php(377): OC\Files\Filesystem::initMountPoints()
#21 /usr/share/webapps/nextcloud/lib/private/legacy/util.php(310): OC\Files\Filesystem::init()
#22 /usr/share/webapps/nextcloud/lib/private/Files/Utils/Scanner.php(116): OC_Util::setupFS()
#23 /usr/share/webapps/nextcloud/lib/private/Files/Utils/Scanner.php(202): OC\Files\Utils\Scanner->getMounts()
#24 /usr/share/webapps/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan()
#25 /usr/share/webapps/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles()
#26 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#27 /usr/share/webapps/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#28 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(915): OC\Core\Command\Base->run()
#29 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#30 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#31 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#32 /usr/share/webapps/nextcloud/console.php(99): OC\Console\Application->run()
#33 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
#34 {main}
```
And nothing seems to be scanned...

**Comment by kesselb** [comment]
Closing as duplicate.

**Comment by Tealk** [comment]
And where do I find a solution to this now? @kesselb  Even with 18.0.1 the error is still present.

**Comment by Bubbelb** [comment]
Kind of strange. As I cannot find a similar bug report.
@kesselb , did you perhaps close the wrong ticket?

**Comment by Bubbelb** [comment]
> Closing as duplicate of #19127

Thanks for the edit.
