### ISSUE TITLE
WebDav: 405 error

### ISSUE THREAD

**Issue by carlox97** [nextcloud/server#19216]
### Steps to reproduce
1. Download [FileExplorer](https://www.skyjos.com/fileexplorer/) or [Neutron Music Player](https://neutronmp.com/buy)
2. Try to access Nextcloud via WedDav with `example.com/nextcloud/remote.php/dav/files/USERNAME/` or `example.com/nextcloud/remote.php/webdav/files/USERNAME/`

3. Error 405 (emtpy directory on Neutron Music Player). 

4. /var/log/apache2/access.log

`X.X.X.X - - [30/Jan/2020:12:14:06 +0100] "PROPFIND /nextcloud/remote.php/dav/files/admin/ HTTP/1.1" 301 595 "-" "-"
X.X.X.X - - [30/Jan/2020:12:14:06 +0100] "PROPFIND /nextcloud/remote.php/dav/files/admin/ HTTP/1.1" 405 3900 "http://X.X.X.X/nextcloud/remote.php/dav/files/admin/" "-"`

### Expected behaviour
No error 405, ability to browse Nextcloud

### Actual behaviour
Error 405, emtpy folder or unable to access

### Server configuration

**Operating system:** Kubuntu 19

**Web server:** Apache2 2.4

**Database:** mariadb

**PHP version:** 7.3

**Nextcloud version:** 18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** wget

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - audioplayer: 2.9.0
  - breezedark: 18.0.1
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - music
  - occweb
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MY.DOMAIN"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/MY.DOMAIN",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** WebDav

### Client configuration
**Browser:** apps

**Operating system:** Android & iOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Thu Jan 30 00:13:54.802744 2020] [mpm_event:notice] [pid 14643:tid 140116487334976] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Jan 30 00:13:54.802841 2020] [core:notice] [pid 14643:tid 140116487334976] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:13:58.259736 2020] [mpm_event:notice] [pid 14643:tid 140116487334976] AH00491: caught SIGTERM, shutting down
[Thu Jan 30 00:13:58.329155 2020] [mpm_prefork:notice] [pid 16111] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Jan 30 00:13:58.329235 2020] [core:notice] [pid 16111] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:13:58.651705 2020] [mpm_prefork:notice] [pid 16111] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:13:58.781204 2020] [mpm_prefork:notice] [pid 16173] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Jan 30 00:13:58.781256 2020] [core:notice] [pid 16173] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:16:04.136927 2020] [mpm_prefork:notice] [pid 16173] AH00171: Graceful restart requested, doing restart
[Thu Jan 30 00:16:04.180073 2020] [mpm_prefork:notice] [pid 16173] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Jan 30 00:16:04.180084 2020] [core:notice] [pid 16173] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:16:50.287310 2020] [mpm_prefork:notice] [pid 16173] AH00171: Graceful restart requested, doing restart
[Thu Jan 30 00:16:50.332731 2020] [mpm_prefork:notice] [pid 16173] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Jan 30 00:16:50.332740 2020] [core:notice] [pid 16173] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:16:58.076415 2020] [mpm_prefork:notice] [pid 16173] AH00171: Graceful restart requested, doing restart
[Thu Jan 30 00:16:58.122190 2020] [mpm_prefork:notice] [pid 16173] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Jan 30 00:16:58.122201 2020] [core:notice] [pid 16173] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:17:00.541912 2020] [mpm_prefork:notice] [pid 16173] AH00171: Graceful restart requested, doing restart
[Thu Jan 30 00:17:00.588455 2020] [mpm_prefork:notice] [pid 16173] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:17:00.588464 2020] [core:notice] [pid 16173] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:17:11.777080 2020] [mpm_prefork:notice] [pid 16173] AH00171: Graceful restart requested, doing restart
[Thu Jan 30 00:17:11.824231 2020] [mpm_prefork:notice] [pid 16173] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:17:11.824245 2020] [core:notice] [pid 16173] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:21:50.231699 2020] [php7:error] [pid 19145] [client X.X.X.X:1024] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 315841760 bytes) in /var/www/nextcloud/lib/private/Installer.php on line 278
[Thu Jan 30 00:23:54.209871 2020] [mpm_prefork:notice] [pid 16173] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:23:54.355487 2020] [mpm_prefork:notice] [pid 19208] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:23:54.355533 2020] [core:notice] [pid 19208] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:24:26.037974 2020] [mpm_prefork:notice] [pid 19208] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:24:26.127796 2020] [mpm_prefork:notice] [pid 19592] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:24:26.127832 2020] [core:notice] [pid 19592] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:25:23.243364 2020] [mpm_prefork:notice] [pid 19592] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:25:23.373405 2020] [mpm_prefork:notice] [pid 19663] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:25:23.373457 2020] [core:notice] [pid 19663] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:27:20.858180 2020] [php7:error] [pid 19678] [client X.X.X.X:58194] script '/var/www/html/status.php' not found or unable to stat
[Thu Jan 30 00:27:21.194181 2020] [php7:error] [pid 19667] [client X.X.X.X:58214] script '/var/www/html/status.php' not found or unable to stat
[Thu Jan 30 00:27:22.373346 2020] [php7:error] [pid 19666] [client X.X.X.X:58216] script '/var/www/html/status.php' not found or unable to stat
[Thu Jan 30 00:27:28.204254 2020] [php7:error] [pid 19691] [client X.X.X.X:58250] script '/var/www/html/status.php' not found or unable to stat
[Thu Jan 30 00:27:29.407814 2020] [php7:error] [pid 19691] [client X.X.X.X:58250] script '/var/www/html/status.php' not found or unable to stat
[Thu Jan 30 00:27:30.716257 2020] [php7:error] [pid 19691] [client X.X.X.X:58250] script '/var/www/html/status.php' not found or unable to stat
[Thu Jan 30 00:35:13.143390 2020] [mpm_prefork:notice] [pid 19663] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:35:13.281237 2020] [mpm_prefork:notice] [pid 22295] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:35:13.281331 2020] [core:notice] [pid 22295] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:36:58.018922 2020] [mpm_prefork:notice] [pid 22295] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:36:58.158695 2020] [mpm_prefork:notice] [pid 22349] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:36:58.158729 2020] [core:notice] [pid 22349] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:47:00.434403 2020] [mpm_prefork:notice] [pid 22349] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 00:47:00.533250 2020] [mpm_prefork:notice] [pid 26070] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:47:00.533295 2020] [core:notice] [pid 26070] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:48:53.071366 2020] [mpm_prefork:notice] [pid 26070] AH00173: SIGHUP received.  Attempting to restart
[Thu Jan 30 00:48:53.118634 2020] [mpm_prefork:notice] [pid 26070] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:48:53.118654 2020] [core:notice] [pid 26070] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 00:52:31.375046 2020] [mpm_prefork:notice] [pid 26070] AH00173: SIGHUP received.  Attempting to restart
[Thu Jan 30 00:52:31.451051 2020] [mpm_prefork:notice] [pid 26070] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 00:52:31.451070 2020] [core:notice] [pid 26070] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 01:04:08.183384 2020] [mpm_prefork:notice] [pid 26070] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 01:04:08.314957 2020] [mpm_prefork:notice] [pid 30075] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 01:04:08.315083 2020] [core:notice] [pid 30075] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 01:05:39.972823 2020] [mpm_prefork:notice] [pid 30075] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 01:07:41.734724 2020] [mpm_prefork:notice] [pid 985] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 01:07:41.735211 2020] [core:notice] [pid 985] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 01:09:45.782914 2020] [mpm_prefork:notice] [pid 985] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 01:09:45.871762 2020] [mpm_prefork:notice] [pid 1414] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 01:09:45.871839 2020] [core:notice] [pid 1414] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 01:10:13.302149 2020] [mpm_prefork:notice] [pid 1414] AH00169: caught SIGTERM, shutting down
[Thu Jan 30 01:10:13.445562 2020] [mpm_prefork:notice] [pid 1445] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 01:10:13.445600 2020] [core:notice] [pid 1445] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 01:38:36.858128 2020] [php7:error] [pid 1447] [client X.X.X.X:1024] script '/var/www/html/index.php' not found or unable to stat
[Thu Jan 30 01:38:40.702766 2020] [php7:error] [pid 1447] [client X.X.X.X:1024] script '/var/www/html/index.php' not found or unable to stat
[Thu Jan 30 01:38:41.500165 2020] [php7:error] [pid 1447] [client X.X.X.X:1024] script '/var/www/html/index.php' not found or unable to stat
[Thu Jan 30 01:39:06.107185 2020] [php7:error] [pid 1446] [client X.X.X.X:1024] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:39:11.476948 2020] [php7:error] [pid 1448] [client X.X.X.X:1025] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:39:12.373031 2020] [php7:error] [pid 1448] [client X.X.X.X:1025] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:39:15.255480 2020] [php7:error] [pid 1448] [client X.X.X.X:1025] script '/var/www/html/index.php' not found or unable to stat
[Thu Jan 30 01:39:16.890033 2020] [php7:error] [pid 1448] [client X.X.X.X:1025] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:40:01.579959 2020] [php7:error] [pid 1459] [client X.X.X.X:1028] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:40:02.058511 2020] [php7:error] [pid 1459] [client X.X.X.X:1028] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:40:03.365363 2020] [php7:error] [pid 1459] [client X.X.X.X:1028] script '/var/www/html/index.php' not found or unable to stat, referer: http://X.X.X.X/
[Thu Jan 30 01:40:31.108839 2020] [php7:error] [pid 1454] [client X.X.X.X:1024] script '/var/www/html/index.php' not found or unable to stat
[Thu Jan 30 01:44:40.143712 2020] [mpm_prefork:notice] [pid 1445] AH00171: Graceful restart requested, doing restart
[Thu Jan 30 01:44:40.198575 2020] [mpm_prefork:notice] [pid 1445] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Thu Jan 30 01:44:40.198586 2020] [core:notice] [pid 1445] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 30 02:37:18.734355 2020] [php7:error] [pid 2798] [client X.X.X.X:10184] PHP Fatal error:  Uncaught PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1054): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/nextcloud/lib/private/DB/Connection.php(220): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(203): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(215): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /var/www/nextcloud/lib/private/Lock/DBLockingProvider.php(316): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 [internal  in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 34

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

EDIT: 

I am willing to help solve this problem, so I could provide additional information.

maybe related?
owncloud/core#1210

https://github.com/nextcloud/server/issues/17064

https://github.com/nextcloud/server/issues/13092

**Comment by carlox97** [comment]
https://github.com/owncloud/core/issues/1210

maybe related?

**Comment by acs-ferreira** [comment]
Can you please try the command at https://github.com/nextcloud/server/issues/17064#issuecomment-569455683 (adapt to your sever)

**Comment by carlox97** [comment]
@acs-ferreira Apparently I was using the wrong URL:

the correct one is
`https://your.domain.com/remote.php/dav/files/admin/` or `https://your.domain.com/remote.php/webdav`

instead of
`https://your.domain.com/nextcloud/remote.php/dav/files/admin/`, which was advised by the [Documentation ](https://docs.nextcloud.com/server/18/user_manual/files/access_webdav.html)

Everything works fine now. I wonder why that 405 error instead of something to acknowledge the wrong URL is being inserted.

TIP: Find your correct WebDav URL by checking "settings" in the bottom left corner of your Nextcloud (via browser).
