### ISSUE TITLE
Loading chunk 0 failed

### ISSUE THREAD

**Issue by cwbsl** [nextcloud/server#19280]
Hello

After updating Nextcloud 17.0.3 to 18.0.0 we get the following error when accessing the users page or the apps page:

![image](https://user-images.githubusercontent.com/37547654/73661631-a7a90000-469a-11ea-8b20-15b2414bf94d.png)

### Steps to reproduce
1. Download and install Nextcloud 18.0.0 over 17.0.3
2. Manually upgrade with OCC upgrade command
3. access users or apps page

### Expected behaviour
See the users or the app center

### Actual behaviour
Empty page and redirection to /index.php/

### Server configuration

**Operating system:**
Synology DSM 6.2.2-24922 Update 4

**Web server:**
Apache 2.4.39

**Database:**
MariaDB 10.3.21

**PHP version:**
7.3.11

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Nextcloud 17.0.3

**Where did you install Nextcloud from:**
Official Nextcloud Download website

**Signing status:**
<details>
<summary>Signing status</summary>
See: https://pastebin.com/YxzmDtxe
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - cloud_federation_api: 1.1.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - announcementcenter
  - comments
  - encryption
  - files_external
  - files_texteditor
  - gallery
  - impersonate
  - quota_warning
  - registration
  - sharebymail
  - sociallogin
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "debug": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "trusted_domains": [
            "cloud.***REMOVED SENSITIVE VALUE***:80",
            "cloud.***REMOVED SENSITIVE VALUE***:443",
            "cloud.***REMOVED SENSITIVE VALUE***:8080",
            "cloud.***REMOVED SENSITIVE VALUE***:8181",
            "storage.***REMOVED SENSITIVE VALUE***:80",
            "storage.***REMOVED SENSITIVE VALUE***:443",
            "storage.***REMOVED SENSITIVE VALUE***:8080",
            "storage.***REMOVED SENSITIVE VALUE***:8181",
            "storage.***REMOVED SENSITIVE VALUE***.ch",
            "192.168.10.126:8181",
            "192.168.10.126:8080"
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF"
        ],
        "tempdirectory": "\/volume1\/web\/cloud\/data\/tmp",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "log_type": "file",
        "loglevel": 0,
        "logfile": "\/volume1\/web\/cloud\/nextcloud.log",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "trashbin_retention_obligation": "auto, 180",
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+--------------+
| Configuration                 | s01          |
+-------------------------------+--------------+
| hasMemberOfFilterSupport      | 0            |
| homeFolderNamingRule          |              |
| lastJpegPhotoLookup           | 0            |
| ldapAgentName                 |              |
| ldapAgentPassword             | ***          |
| ldapAttributesForGroupSearch  |              |
| ldapAttributesForUserSearch   |              |
| ldapBackupHost                |              |
| ldapBackupPort                |              |
| ldapBase                      |              |
| ldapBaseGroups                |              |
| ldapBaseUsers                 |              |
| ldapCacheTTL                  | 600          |
| ldapConfigurationActive       | 0            |
| ldapDefaultPPolicyDN          |              |
| ldapDynamicGroupMemberURL     |              |
| ldapEmailAttribute            |              |
| ldapExperiencedAdmin          | 0            |
| ldapExpertUUIDGroupAttr       |              |
| ldapExpertUUIDUserAttr        |              |
| ldapExpertUsernameAttr        |              |
| ldapExtStorageHomeAttribute   |              |
| ldapGidNumber                 | gidNumber    |
| ldapGroupDisplayName          | cn           |
| ldapGroupFilter               |              |
| ldapGroupFilterGroups         |              |
| ldapGroupFilterMode           | 0            |
| ldapGroupFilterObjectclass    |              |
| ldapGroupMemberAssocAttr      | uniqueMember |
| ldapHost                      |              |
| ldapIgnoreNamingRules         |              |
| ldapLoginFilter               |              |
| ldapLoginFilterAttributes     |              |
| ldapLoginFilterEmail          | 0            |
| ldapLoginFilterMode           | 0            |
| ldapLoginFilterUsername       | 1            |
| ldapNestedGroups              | 0            |
| ldapOverrideMainServer        |              |
| ldapPagingSize                | 500          |
| ldapPort                      |              |
| ldapQuotaAttribute            |              |
| ldapQuotaDefault              |              |
| ldapTLS                       | 0            |
| ldapUserAvatarRule            | default      |
| ldapUserDisplayName           | displayName  |
| ldapUserDisplayName2          |              |
| ldapUserFilter                |              |
| ldapUserFilterGroups          |              |
| ldapUserFilterMode            | 0            |
| ldapUserFilterObjectclass     |              |
| ldapUuidGroupAttribute        | auto         |
| ldapUuidUserAttribute         | auto         |
| turnOffCertCheck              | 0            |
| turnOnPasswordChange          | 0            |
| useMemberOfToDetectMembership | 1            |
+-------------------------------+--------------+

</details>

### Client configuration
**Browser:**
Chrome, Firefox, Edge (Cache cleaned, rebooted OS + rebooted Browser)
Also tried on 6 other computers from different networks.

**Operating system:**
Windows 10 Pro

#### Web server error log
<details>
<summary>Web server error log</summary>
2020-01-29T13:47:46+01:00 flugdaten [Wed Jan 29 13:47:46.242100 2020] [proxy_fcgi:error] [pid 21552:tid 140320926783232] [client 212.147.57.25:49899] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'OC\\DB\\QueryBuilder\\QueryBuilder' not found in /volume1/web/cloud/lib/private/DB/Connection.php:78\nStack trace:\n#0 /volume1/web/cloud/lib/private/AppConfig.php(327): OC\\DB\\Connection->getQueryBuilder()\n#1 /volume1/web/cloud/lib/private/AppConfig.php(108): OC\\AppConfig->loadConfigValues()\n#2 /volume1/web/cloud/lib/private/AppConfig.php(286): OC\\AppConfig->getApps()\n#3 /volume1/web/cloud/lib/private/legacy/app.php(888): OC\\AppConfig->getValues(false, 'installed_versi...')\n#4 /volume1/web/cloud/lib/private/TemplateLayout.php(165): OC_App::getAppVersions()\n#5 /volume1/web/cloud/lib/private/legacy/template.php(184): OC\\TemplateLayout->__construct('error', '')\n#6 /volume1/web/cloud/lib/private/Template/Base.php(132): OC_Template->fetchPage()\n#7 /volume1/web/cloud/lib/private/legacy/template.php(333): OC\\Template\\Base->printPage()\n#8 /volume1/web/cloud/index.php(79): OC_Template::printExceptionErrorPage(Object(Error), 500)\n#9 {main}\n  thrown in /volume1/web/cl...', referer: https://storage.cadwork.ch/index.php/apps/files/?dir=/&fileid=7
2020-01-29T14:10:15+01:00 flugdaten [Wed Jan 29 14:10:15.265591 2020] [authz_core:error] [pid 21552:tid 140321061066496] [client 212.147.57.25:50935] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:10:50+01:00 flugdaten [Wed Jan 29 14:10:50.663767 2020] [authz_core:error] [pid 21552:tid 140320977139456] [client 212.147.57.25:50963] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:11:17+01:00 flugdaten [Wed Jan 29 14:11:17.144349 2020] [authz_core:error] [pid 21552:tid 140320834463488] [client 212.147.57.25:51070] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:11:28+01:00 flugdaten [Wed Jan 29 14:11:28.419689 2020] [authz_core:error] [pid 21552:tid 140320893212416] [client 212.147.57.25:51176] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:17:51+01:00 flugdaten [Wed Jan 29 14:17:51.204477 2020] [proxy_fcgi:error] [pid 21552:tid 140320834463488] (70007)The timeout specified has expired: [client 212.147.57.25:51788] AH01075: Error dispatching request to : (polling)
2020-01-29T14:18:06+01:00 flugdaten [Wed Jan 29 14:18:06.211480 2020] [proxy_fcgi:error] [pid 21552:tid 140320901605120] (70007)The timeout specified has expired: [client 212.147.57.25:51819] AH01075: Error dispatching request to : (polling)
2020-01-29T14:18:19+01:00 flugdaten [Wed Jan 29 14:18:19.039254 2020] [proxy_fcgi:error] [pid 21552:tid 140320868034304] (70007)The timeout specified has expired: [client 212.147.57.25:51786] AH01075: Error dispatching request to : (polling)
2020-01-29T14:20:30+01:00 flugdaten [Wed Jan 29 14:20:30.038987 2020] [authz_core:error] [pid 21552:tid 140321027495680] [client 178.199.107.98:52165] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:20:44+01:00 flugdaten [Wed Jan 29 14:20:44.861578 2020] [negotiation:error] [pid 21552:tid 140320817678080] [client 212.147.57.25:52229] AH00687: Negotiation: discovered file(s) matching request: /volume1/web/cloud/settings/help (None could be negotiated).
2020-01-29T14:21:02+01:00 flugdaten [Wed Jan 29 14:21:02.001610 2020] [authz_core:error] [pid 21552:tid 140321002317568] [client 178.199.107.98:52309] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:21:34+01:00 flugdaten [Wed Jan 29 14:21:34.184030 2020] [authz_core:error] [pid 21552:tid 140321077851904] [client 178.199.107.98:52362] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:21:39+01:00 flugdaten [Wed Jan 29 14:21:39.108810 2020] [authz_core:error] [pid 21552:tid 140320943568640] [client 178.199.107.98:52379] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-29T14:36:49+01:00 flugdaten [Wed Jan 29 14:36:49.965170 2020] [mpm_worker:notice] [pid 20535:tid 139891741050752] AH00292: Apache/2.4.39 (Unix) configured -- resuming normal operations
2020-01-29T14:36:49+01:00 flugdaten [Wed Jan 29 14:36:49.967029 2020] [core:notice] [pid 20535:tid 139891741050752] AH00094: Command line: '/var/packages/Apache2.4/target/usr/local/bin/httpd24'
2020-01-29T14:36:53+01:00 flugdaten [Wed Jan 29 14:36:53.762686 2020] [mpm_worker:notice] [pid 20535:tid 139891741050752] AH00297: SIGUSR1 received.  Doing graceful restart
2020-01-29T14:36:53+01:00 flugdaten AH00558: httpd24: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
2020-01-29T14:36:53+01:00 flugdaten [Wed Jan 29 14:36:53.852128 2020] [mpm_worker:notice] [pid 20535:tid 139891741050752] AH00292: Apache/2.4.39 (Unix) configured -- resuming normal operations
2020-01-29T14:36:53+01:00 flugdaten [Wed Jan 29 14:36:53.852162 2020] [core:notice] [pid 20535:tid 139891741050752] AH00094: Command line: '/var/packages/Apache2.4/target/usr/local/bin/httpd24'
2020-01-29T14:37:30+01:00 flugdaten [Wed Jan 29 14:37:30.618528 2020] [authz_core:error] [pid 21354:tid 139891505620736] [client 178.199.107.98:60494] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-30T01:01:35+01:00 flugdaten [Thu Jan 30 01:01:35.583197 2020] [authz_core:error] [pid 21354:tid 139891320981248] [client 178.199.107.98:46285] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-30T17:36:21+01:00 flugdaten [Thu Jan 30 17:36:21.212820 2020] [authz_core:error] [pid 21354:tid 139891404908288] [client 212.147.57.25:39953] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-01-31T01:01:41+01:00 flugdaten [Fri Jan 31 01:01:41.519223 2020] [authz_core:error] [pid 21354:tid 139891630757632] [client 212.147.57.25:49866] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-02-01T01:01:42+01:00 flugdaten [Sat Feb 01 01:01:42.340821 2020] [authz_core:error] [pid 21354:tid 139891480442624] [client 212.147.57.25:56195] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-02-01T12:35:02+01:00 flugdaten [Sat Feb 01 12:35:02.184229 2020] [proxy_fcgi:error] [pid 21354:tid 139891320981248] (70008)Partial results are valid but processing is incomplete: [client 83.76.34.34:43935] AH01075: Error dispatching request to : (reading input brigade)
2020-02-01T12:35:02+01:00 flugdaten [Sat Feb 01 12:35:02.271916 2020] [proxy_fcgi:error] [pid 21354:tid 139891304195840] (70008)Partial results are valid but processing is incomplete: [client 83.76.34.34:43925] AH01075: Error dispatching request to : (reading input brigade)
2020-02-02T01:01:40+01:00 flugdaten [Sun Feb 02 01:01:40.677205 2020] [authz_core:error] [pid 21354:tid 139891597186816] [client 178.199.107.98:39867] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-02-02T01:01:44+01:00 flugdaten [Sun Feb 02 01:01:44.225904 2020] [authz_core:error] [pid 21354:tid 139891613972224] [client 212.147.57.25:39886] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-02-03T01:01:44+01:00 flugdaten [Mon Feb 03 01:01:44.543568 2020] [authz_core:error] [pid 21354:tid 139891295803136] [client 212.147.57.25:55011] AH01630: client denied by server configuration: /volume1/web/cloud/config
2020-02-03T15:28:50+01:00 flugdaten [Mon Feb 03 15:28:50.547179 2020] [core:alert] [pid 21354:tid 139891463657216] [client 212.147.57.25:46882] /volume1/web/cloud/data/.htaccess: Expected </IifModule> but saw </IfModule>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
</details>

#### Browser log
<details>
<summary>Browser log</summary>
See image above
</details>

Thanks a lot for any help in advance!

**Comment by cwbsl** [comment]
I have completely reinstalled my instance and now it seems to work fine, sorry for bothering!

**Comment by arnebr** [comment]
Hmm, have the same error in my NC18 now.
