### ISSUE TITLE
Error during upgrade from 9.0.53 to 10.0.1

### ISSUE THREAD

**Issue by binerf** [nextcloud/server#1959]
### Steps to reproduce
1. Download last release (10.0.1)
2. Rename current nextcloud instance folder (9.0.53)
3. unzip last release package
4. Copy config.php 9.0.53 folder to 10.0.1 folder
5. Start upgrade with: ```# sudo -u www-data php occ upgrade```

### Expected behaviour
Nextcloud instance upgraded to 10.0.1 version.

### Actual behaviour
Error received:
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Done
27/27 [============================] 100%
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Exception: files can't be disabled.
Update failed
Maintenance mode is kept active
Reset log level
#
```
And instance still remains in 9.0.53

### Server configuration
**Operating system**: Debian stretch/sid

**Web server:** Apache/2.4.23 (Debian)

**Database:** mysql  Ver 14.14 Distrib 5.6.30

**PHP version:** PHP 7.0.12-1 

**Nextcloud version:** (see Nextcloud admin page) 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from older Nextcloud version

**Where did you install Nextcloud from:** From official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail.0.5.0
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid for required scope. (Requested: mail.0.5.0, current: CN=mail)
- qownnotesapi
	- FILE_MISSING
		- .gitignore
		- .travis.yml
		- Makefile
		- build/artifacts/appstore/qownnotesapi.tar.gz
		- phpunit.coverage.xml
		- phpunit.integration.xml
		- phpunit.xml
		- tests/integration/AppTest.php
		- tests/travis/php.ini
		- tests/unit/controller/NoteApiControllerTest.php
- user_ldap
	- EXTRA_FILE
		- lib/defines.php

Raw output
==========
Array
(
    [mail.0.5.0] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid for required scope. (Requested: mail.0.5.0, current: CN=mail)
                )

        )

    [qownnotesapi] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.gitignore] => Array
                        (
                            [expected] => d5cc0283d4eb9d4adb7b11ef526d933fafc81e4a3c7191d2331ce6965170a7a1e7117aab69b730e4b25cf5354222230a72adb8a87fe60006929948217218537a
                            [current] => 
                        )

                    [.travis.yml] => Array
                        (
                            [expected] => e54c3c0cef4f1508b6d07fab2da159a136f2380cb62c5b93234b05dc20532e1b79a677b4287659833067d86c3d7f4fdfffdef2d5cd4cdfd9b9aa4520d9db9db5
                            [current] => 
                        )

                    [Makefile] => Array
                        (
                            [expected] => d2f61de81d762aaee5a5876798e702d513eb2ad80cd5e9a62ff256f4b88fb2f7da8876bd74ed7d20f2b95843d1de7c6eba155aaf1f9509029e3ec15b3256999a
                            [current] => 
                        )

                    [build/artifacts/appstore/qownnotesapi.tar.gz] => Array
                        (
                            [expected] => 609e55b65b3f683ebe4f2cfc3b36daf61e65105a7f839f8d049c8a77399defbed1d08bc549e06cb3139428d36c9fd5d6367a616a37fed016f7d80fb3be25d1eb
                            [current] => 
                        )

                    [phpunit.coverage.xml] => Array
                        (
                            [expected] => 21686e83eada96dd35b0187b5f9e5f4df15e9ab0faf36c54c8cc1f0631f739f56bbccb1a0668002ebb13104d7e28ecfec9b277ca665641b3abab4330a12dddca
                            [current] => 
                        )

                    [phpunit.integration.xml] => Array
                        (
                            [expected] => d477d2d4e122ea372352b7e3c96e6973ad6c82b04c3adeb1edf02029f1cff62240ac188b99e063c7423e7603098dd7ab89c8f146c5382d8c8a9e0a9117f70da3
                            [current] => 
                        )

                    [phpunit.xml] => Array
                        (
                            [expected] => c4b7fe8203adf562ae2aa01090b46d0a1337df7766285b97d5fe27be19636f5385deb08f19101305536423006deed50eb22f3cc7f6ebf5c1d2fc4fe009c961bc
                            [current] => 
                        )

                    [tests/integration/AppTest.php] => Array
                        (
                            [expected] => 6ab2b514e3abcdd947f10bdd53e548581bfdaf9cb13fc622860c23907cbeaa999ba472bb243c0812e98766ab8025c2447d5a2ddfaf4a7573483691b8a34ea478
                            [current] => 
                        )

                    [tests/travis/php.ini] => Array
                        (
                            [expected] => 42ae4f728eb4e0cec696ae48c61d58e50e836b0f291cf74fdc0d7229c565c2bf3c076ac150ce7250dde2e4600804f17404a09555e1978d7e79bb84d39e2c78e1
                            [current] => 
                        )

                    [tests/unit/controller/NoteApiControllerTest.php] => Array
                        (
                            [expected] => 08fba9788ace46accf2fb8e1a422294551782b093c8d0d6a87300172cf1b983e859f6786a1891a2ad6d5dc17fd008a674f43357e16f5126812ce261243110a46
                            [current] => 
                        )

                )

        )

    [user_ldap] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/defines.php] => Array
                        (
                            [expected] => 
                            [current] => fe0e9217b1cf6db22edb0ca180fbfd268bb21713f98ed46f0d0f553bf7ba7c491b5bdc248addda23ec2b1632a9f91e6b64e5fead2272649bd7d267d204a54c7f
                        )

                )

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.0.0
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.0.0
  - mail: 0.5.2
  - news: 8.8.0
  - notes: 2.0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - qownnotesapi: 0.4.4
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - encryption
  - gallery
  - mail.0.5.0
  - ownnote
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "theme": "",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "http:\/\/api.apps.owncloud.com\/v1",
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.apps.owncloud.com\/v1",
        "mail_smtpdebug": false,
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "7, auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": "",
        "updatechecker": true,
        "log_type": "owncloud",
        "overwrite.cli.url": "https:\/\/sensitive data\/",
        "logfile": "",
        "loglevel": 0,
        "remember_login_cookie_lifetime": 1296000,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:",
        "datadirectory": "\/mnt\/owncloud\/data",
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/site\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{imap.gmail.com:993\/imap\/ssl}INBOX"
                ]
            }
        ],
        "customclient_desktop": "",
        "customclient_android": "",
        "customclient_ios": "",
        "instanceid": "5141dd4dd0d78",
        "version": "9.0.53.0",
        "trusted_domains": [
            "sensitive data",
            "sensitive data2"
        ],
        "mail_from_address": "noreply",
        "mail_domain": "sensitive data",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "has_internet_connection": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
        "customclient_desktop": "",
        "customclient_android": "",
        "customclient_ios": "",
        "instanceid": "5141dd4dd0d78",
        "version": "9.0.53.0",
        "trusted_domains": [
            "sensitive data",
            "sensitive data2"
        ],
        "mail_from_address": "noreply",
        "mail_domain": "sensitive data",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "has_internet_connection": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes/no (LUKS)

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** php command from server directly

**Operating system:** Same than server

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"vgafgHwfI523ylMOxWaB","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"files can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(423): OC\\\\App\\\\AppManager-
>disableApp('files')\\n#1 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(433): OC_App::disable('files')\\n#2 \\\/var
\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(277): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.1.5', '9.0.53.0')\\n#4 \\\/var\\\/www\\\/html\\\/site\\\/n$xtcloud\\\/core\\\/Command\\\/Upgrade.php(292): OC\\\\Updater->upgrade()\\n#5 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\$\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput)$ Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\\\/c$nsole\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\Argv$nput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfon$
\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Objec$
(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\$
\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Obje$
t(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www$
\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Sym$
ony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/h$
ml\\\/site\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/occ(11): req$
ire_once('\\\/var\\\/www\\\/html\\\/s...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppM$
nager.php\",\"Line\":258}","level":3,"time":"2016-10-30T16:26:36+00:00","method":"--","url":"--","user":"--"}
```
</details>

**Comment by nickvergessen** [comment]
The error message + log indicate that you did not replace the `apps/` folder before starting the update.

**Comment by binerf** [comment]
Thanks for your feedback.

I've tried again with ``` apps/```  folder coming from previous release and same issue:
``` 
# sudo -u www-data php occ -vvv upgrade                                                                                                                  
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2016-10-31T16:14:35+00:00 Set log level to debug
2016-10-31T16:14:36+00:00 Repair step: Repair MySQL database engine
2016-10-31T16:14:37+00:00 Repair step: Repair MySQL collation
2016-10-31T16:14:37+00:00 Repair step: Repair SQLite autoincrement
2016-10-31T16:14:37+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2016-10-31T16:14:38+00:00 Repair info: removing duplicate entries from lucene_status
2016-10-31T16:14:38+00:00 Checking whether the database schema can be updated (this can take a long time depending on the database size)
2016-10-31T16:14:38+00:00  Checking table oc_appconfig
2016-10-31T16:14:45+00:00  Checking table oc_storages
2016-10-31T16:14:47+00:00  Checking table oc_mounts
2016-10-31T16:14:52+00:00  Checking table oc_mimetypes
2016-10-31T16:14:54+00:00  Checking table oc_filecache
2016-10-31T16:16:35+00:00  Checking table oc_group_user
2016-10-31T16:16:37+00:00  Checking table oc_group_admin
2016-10-31T16:16:41+00:00  Checking table oc_groups
2016-10-31T16:16:43+00:00  Checking table oc_preferences
2016-10-31T16:16:44+00:00  Checking table oc_properties
2016-10-31T16:16:51+00:00  Checking table oc_share
2016-10-31T16:16:55+00:00  Checking table oc_jobs
2016-10-31T16:16:57+00:00  Checking table oc_users
2016-10-31T16:16:59+00:00  Checking table oc_authtoken
2016-10-31T16:17:02+00:00  Checking table oc_bruteforce_attempts
2016-10-31T16:17:05+00:00  Checking table oc_vcategory
2016-10-31T16:17:08+00:00  Checking table oc_vcategory_to_object
2016-10-31T16:17:11+00:00  Checking table oc_systemtag
2016-10-31T16:17:14+00:00  Checking table oc_systemtag_object_mapping
2016-10-31T16:17:16+00:00  Checking table oc_systemtag_group
2016-10-31T16:17:18+00:00  Checking table oc_privatedata
2016-10-31T16:17:20+00:00  Checking table oc_file_locks
2016-10-31T16:17:55+00:00  Checking table oc_comments
2016-10-31T16:17:58+00:00  Checking table oc_comments_read_markers
2016-10-31T16:18:01+00:00  Checking table oc_credentials
2016-10-31T16:18:04+00:00  Checking table oc_admin_sections
2016-10-31T16:18:07+00:00  Checking table oc_admin_settings
2016-10-31T16:18:09+00:00 Checked database schema update
2016-10-31T16:18:09+00:00 Checking updates of apps
2016-10-31T16:18:09+00:00 Checked database schema update for apps
2016-10-31T16:18:09+00:00 Updating database schema
2016-10-31T16:18:11+00:00 Updated database
2016-10-31T16:18:11+00:00 Exception: files can't be disabled.
2016-10-31T16:18:11+00:00 Update failed
2016-10-31T16:18:11+00:00 Maintenance mode is kept active
2016-10-31T16:18:11+00:00 Reset log level
# 
``` 
``` 
{"reqId":"nCRzUOKNcKTHLZ6BWI14","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"files can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(423): OC\\\\App\\\\AppManager->disableApp('files')\\n#1 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(433): OC_App::disable('files')\\n#2 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(277): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.1.5', '9.0.53.0')\\n#4 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/core\\\/Command\\\/Upgrade.php(292): OC\\\\Updater->upgrade()\\n#5 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/html\\\/s...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/site\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":258}","level":3,"time":"2016-10-31T16:18:11+00:00","method":"--","url":"--","user":"--"}
```

**Comment by nickvergessen** [comment]
You misunderstood. You **need to replace** the apps/ folder, but aparently did not.

**Comment by binerf** [comment]
Sorry, I didn't get it.

I tried with 2 methods:
- first try: I launched <code>occ upgrade</code> from the last release folder (10.0.1) without changing anything inside but <code>config/config.php</code> file (copied from 9.0.53 release, my previous instance)
- second try: I launched <code>occ upgrade</code> in 10.0.1 folder with <code>apps/</code> folder copied from previous instance.

In both cases, same problem.

**Comment by nickvergessen** [comment]
Can you please post the content of the 10.0.1 `apps/files/appinfo/info.xml` from your server?

**Comment by binerf** [comment]
Sure:
`<?xml version="1.0"?>
<info>
        <id>files</id>
        <name>Files</name>
        <description>File Management</description>
        <licence>AGPL</licence>
        <author>Robin Appelman, Vincent Petry</author>
        <default_enable/>
        <version>1.4.4</version>
        <types>
                <filesystem/>
        </types>
        <dependencies>
                <owncloud min-version="9.0" max-version="9.0" />
        </dependencies>
        <documentation>
                <user>user-files</user>
        </documentation>
</info>
`

**Comment by nickvergessen** [comment]
Exactly that is the problem.
It should start with:
```xml
<?xml version="1.0"?>
<info>
	<id>files</id>
	<name>Files</name>
	<description>File Management</description>
	<licence>AGPL</licence>
	<author>Robin Appelman, Vincent Petry</author>
	<default_enable/>
	<version>1.5.2</version>
	<types>
		<filesystem/>
	</types>
	<dependencies>
		<owncloud min-version="9.1" max-version="9.1" />
	</dependencies>
....
```

So you didn't successfully upload all new files.

**Comment by binerf** [comment]
Okay, I admit: I'm lost.

I repost here the steps followed to reproduce the issue:
<code>
Steps to reproduce
1. Download last release (10.0.1)
2. Rename current nextcloud instance folder (9.0.53)
3. unzip last release package
4. Copy config.php 9.0.53 folder to 10.0.1 folder
5. Start upgrade with: # sudo -u www-data php occ upgrade
</code>

Should I copy my current <code>apps/</code> folder into the new release folder ?

**Comment by nickvergessen** [comment]
Ah, so you copied the config from `/var/www/nextcloud-9.0.53` to `/var/www/nextcloud-10.0.1` without adjusting the path?
You need to move away the older folder and rename the new folder to match the old folder before moving. The config.php contains path information.

**Comment by binerf** [comment]
Not exactly, actually I renamed my `/var/www/nextcloud` into `/var/www/nextcloud-9.0.53`, then I dezipped last release archive into `/var/www/nextcloud`, then copy `/var/www/nextcloud-9.0.53/config` into `/var/www/nextcloud`

**Comment by nickvergessen** [comment]
Please delete the line following code from your config.php:
```php
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/site/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
```

Also you seem to have a lot of empty/duplicate values in your config.php which you could try to clean up.

**Comment by binerf** [comment]
Okay, I've removed mentioned lines in my `config.php` file and an error occurs later in the process:
`
[...]
2016-11-02T16:04:54+00:00  Checking table oc_credentials
2016-11-02T16:05:02+00:00  Checking table oc_admin_sections
2016-11-02T16:05:11+00:00  Checking table oc_admin_settings
2016-11-02T16:05:14+00:00 Checked database schema update
2016-11-02T16:05:14+00:00 Checking updates of apps
2016-11-02T16:05:14+00:00 Checking whether the database schema for <files_external> can be updated (this can take a long time depending on the database size)
2016-11-02T16:05:14+00:00  Checking table oc_external_mounts
2016-11-02T16:05:16+00:00  Checking table oc_external_applicable
2016-11-02T16:05:22+00:00  Checking table oc_external_config
2016-11-02T16:05:29+00:00  Checking table oc_external_options
2016-11-02T16:05:37+00:00 Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
2016-11-02T16:05:37+00:00  Checking table oc_share_external
2016-11-02T16:05:42+00:00 Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
2016-11-02T16:05:42+00:00  Checking table oc_files_trash
2016-11-02T16:06:06+00:00 Checked database schema update for apps
2016-11-02T16:06:06+00:00 Updating database schema
2016-11-02T16:06:07+00:00 Updated database
2016-11-02T16:06:09+00:00 Exception: dav can't be disabled.
2016-11-02T16:06:09+00:00 Update failed
2016-11-02T16:06:09+00:00 Maintenance mode is kept active
2016-11-02T16:06:09+00:00 Reset log level
#
`

**Comment by binerf** [comment]
IT WORKS !!!

Thank you so much for your help !!

I've now to reinstall my apps but upgrade looks ok.

Many thanks !
