### ISSUE TITLE
occ Too few arguments to function

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#19730]
### Steps to reproduce
Try to use a occ command eg occ app:update --all

### Expected behaviour
Update all my apps

### Actual behaviour
I get the following error message:
```
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Push\Command\Test::__construct(), 0 passed in /var/www/DOMAIN/lib/private/Console/Application.php on line 223 and exactly 4 expected in /var/www/DOMAIN/apps/push/lib/Command/Test.php:78
Stack trace:
#0 /var/www/DOMAIN/lib/private/Console/Application.php(223): OCA\Push\Command\Test->__construct()
#1 /var/www/DOMAIN/lib/private/Console/Application.php(135): OC\Console\Application->loadCommandsFromInfoXml()
#2 /var/www/DOMAIN/console.php(98): OC\Console\Application->loadCommands()
#3 /var/www/DOMAIN/occ(11): require_once('/var/www/nextcloud...')
#4 {main}[\]
Ignore errors and continue? ([y]es or [N]o):
```

## Server configuration detail

**Operating system:** Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.1.44

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - bruteforcesettings: 1.5.0
 - checksum: 0.4.4
 - circles: 0.18.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_downloadactivity: 1.7.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - groupfolders: 6.0.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - push: 0.6.0
 - quota_warning: 1.7.0
 - ransomware_protection: 1.6.0
 - richdocuments: 3.5.2
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - socialsharing_email: 2.0.0
 - spreed: 8.0.4
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.2
 - twofactor_u2f: 5.0.2
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - user_usage_report: 1.2.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - firstrunwizard
 - recommendations
 - text
 - unsplash

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "DOMAIN"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/www\/nextcloud-data\/_skeleton",
    "tempdirectory": "\/tmp\/nextcloud",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "loglevel": 3,
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "d.m.y H:i:s",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "forcessl": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "ldapUserCleanupInterval": 51,
    "lost_password_link": "https:\/\/www.mmmgroup.com\/de\/user\/password",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/DOMAIN",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "default_language": "de",
    "default_locale": "de",
    "trashbin_retention_obligation": "auto, 60",
    "versions_retention_obligation": "auto, 60",
    "simpleSignUpLink": "false",
    "activity_expire_days": "90"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 500background_sync_prefix: s01bgjUpdateGroupsLastRun: 1380561887cleanUpJobOffset: 450enabled: yesenforce_home_folder_naming_rule: installed_version: 1.8.0s01_lastChange: 1583133608s01has_memberof_filter_support: s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: SGVybWVzbW1tKioyMDE0s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: dc=mmmgroup,dc=coms01ldap_base_groups: ou=groups-nextcloud,dc=mmmgroup,dc=coms01ldap_base_users: ou=people-services,dc=mmmgroup,dc=coms01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: cn=admin,dc=mmmgroup,dc=coms01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 1s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=posixGroup)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: memberUids01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: posixGroups01ldap_host: ldap://services.mmmgroup.coms01ldap_login_filter: (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 1s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: nones01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: inetOrgPersons01ldap_userlist_filter: (|(objectclass=inetOrgPerson))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Nothing
```
</details>

<details><summary>Nextcloud log</summary>

```
Can't find anything in the log for issue #19127.
```
</details>

<details><summary>Browser log</summary>

No browser is used
</details>

**Comment by kesselb** [comment]
Uninstall the push app.

**Comment by Tealk** [comment]
The push app? Is it not included by default?

**Comment by kesselb** [comment]
The app is not sure included by default: https://github.com/nextcloud/push/issues/76
