### ISSUE TITLE
Update from 17.0.3.1 to 17.0.4.2 fails during occ upgrade - Error: Call to a member function getUID() on null in apps/music/hooks/filehooks.php:80

### ISSUE THREAD

**Issue by beanjammin** [nextcloud/server#19943]
The following was output when updating from 17.0.3.1 to 17.0.4.2 via updater.phar:

sudo -u www-data php ./updater.phar       
Nextcloud Updater - version: v16.0.3-3-ga0c2b25 dirty

Current version is 17.0.3.

Update to Nextcloud 17.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-17.0.4.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] Y
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2020-03-13T18:56:20+00:00 Set log level to debug
2020-03-13T18:56:21+00:00 Repair step: Repair MySQL collation
2020-03-13T18:56:21+00:00 Repair info: All tables already have the correct collation -> nothing to do
2020-03-13T18:56:21+00:00 Repair step: Repair SQLite autoincrement
2020-03-13T18:56:21+00:00 Repair step: Copy data from accounts table when migrating from ownCloud
2020-03-13T18:56:21+00:00 Repair step: Drop account terms table when migrating from ownCloud
2020-03-13T18:56:21+00:00 Updating database schema
2020-03-13T18:56:22+00:00 Updated database
2020-03-13T18:56:22+00:00 Updating <files_rightclick> ...
2020-03-13T18:56:22+00:00 Updated <files_rightclick> to 0.14.2
2020-03-13T18:56:22+00:00 Checking for update of app accessibility in appstore
An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in /data/www/<snip>/apps/music/hooks/filehooks.php:80
Stack trace:
#0 /data/www/<snip>/apps/music/hooks/filehooks.php(57): OCA\Music\Hooks\FileHooks::handleUpdated(Object(OC\Files\Node\File), Object(OCA\Music\App\Music))
#1 [internal function]: OCA\Music\Hooks\FileHooks::updated(Object(OC\Files\Node\File))
#2 /data/www/<snip>/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Array, Array)
#3 /data/www/<snip>/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\Files', 'postWrite', Array)
#4 /data/www/<snip>/lib/private/Files/Node/Root.php(136): OC\Hooks\PublicEmitter->emit('\\OC\\Files', 'postWrite', Array)
#5 /data/www/<snip>/lib/private/Files/Node/Node.php(109): OC\Files\Node\Root->emit('\\OC\\Files', 'postWrite', Array)
#6 /data/www/<snip>/lib/private/Files/Node/File.php(70): OC\Files\Node\Node->sendHooks(Array)
#7 /data/www/<snip>/lib/private/Files/SimpleFS/SimpleFile.php(106): OC\Files\Node\File->putContent('{"data":[{"id":...')
#8 /data/www/<snip>/lib/private/App/AppStore/Fetcher/Fetcher.php(173): OC\Files\SimpleFS\SimpleFile->putContent('{"data":[{"id":...')
#9 /data/www/<snip>/lib/private/Installer.php(396): OC\App\AppStore\Fetcher\Fetcher->get()
#10 /data/www/<snip>/lib/private/Updater.php(448): OC\Installer->isUpdateAvailable('accessibility')
#11 /data/www/<snip>/lib/private/Updater.php(258): OC\Updater->upgradeAppStoreApps(Array)
#12 /data/www/<snip>/lib/private/Updater.php(128): OC\Updater->doUpgrade('17.0.4.2', '17.0.3.1')
#13 /data/www/<snip>/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#14 /data/www/<snip>/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /data/www/<snip>/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /data/www/<snip>/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /data/www/<snip>/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /data/www/<snip>/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /data/www/<snip>/console.php(97): OC\Console\Application->run()
#20 /data/www/<snip>/occ(11): require_once('/data/www/cloud...')
#21 {main}

I'm not sure if it is relevant, but my nextcloud instance uses external users, however this has not caused problems during updating in the past.

Any suggestions on how to further troubleshoot?

**Comment by beanjammin** [comment]
Sorry about the noise, it looks like this is an issue with the music app

I was able to get past this issue by disabling the music app, re-running occ upgrade, upgrading the music app, and then re-enabling it.
