### ISSUE TITLE
Errors during upgrade from NC 17.0.4 -> 18.* : Class OCA\Settings\AppInfo\Application does not exist

### ISSUE THREAD

**Issue by Popyllol** [nextcloud/server#20196]
When I try to upgrade from 17.0.4 to any of the new 18 versions I get this error:
# occ upgrade
```php
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve OCA\Settings\AppInfo\Application! Class OCA\Settings\AppInfo\Application does not exist in /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:106
Stack trace:
#0 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Settings\\Ap...')
#1 /var/www/nextcloud/lib/private/ServerContainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Settings\\Ap...', true)
#2 /var/www/nextcloud/lib/base.php(735): OC\ServerContainer->query('OCA\\Settings\\Ap...')
#3 /var/www/nextcloud/lib/base.php(1089): OC::init()
#4 /var/www/nextcloud/console.php(48): require_once('/var/www/nextcl...')
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}
```

This output is from 17.0.4.2 -> 18.0.3.

I tried it from 17.0.3 before... same error.

# Versions
```bash
# occ status 
  - installed: true
  - version: 17.0.4.2
  - versionstring: 17.0.4
  - edition: 

# php-fpm7.3 -v
PHP 7.3.11-0ubuntu0.19.10.3 (fpm-fcgi) (built: Feb 12 2020 15:22:33)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.3, Copyright (c) 1999-2018, by Zend Technologies
```

My apps:
# app:list
```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - camerarawpreviews: 0.7.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.2.0
  - cookbook: 0.6.1
  - dav: 1.13.0
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - keeweb: 0.6.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.11.1
  - news: 14.1.3
  - nextcloud_announcements: 1.6.0
  - notes: 3.2.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocr: 6.0.25
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - rainloop: 6.1.0
  - ransomware_protection: 1.5.2
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - socialsharing_email: 1.0.6
  - support: 1.0.1
  - systemtags: 1.7.0
  - tasks: 0.12.1
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_external: 0.7.0
  - viewer: 1.2.0
  - weather: 1.7.1
  - workflow_pdf_converter: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - files_snapshots
  - flowupload
  - gpxedit
  - gpxpod
  - mail
  - onlyoffice
  - spreed
  - survey_client
  - user_ldap
```

Any hints for me?
I tried even to disable most of the apps before...

Thanks in advance!
Lars

**Comment by kesselb** [comment]
[Manual upgrade](https://docs.nextcloud.com/server/18/admin_manual/maintenance/manual_upgrade.html)? If so please make sure to copy only apps from the old version to the new version that not exist. Don't replace new/apps with old/apps!

**Comment by Popyllol** [comment]
I started the upgrade via web and tried to finish via occ upgrade. That is where the error output is from.
The way via
```
# cd /var/www/nextcloud/updater && sudo -u www-data php updater.phar
```
Didn’t work either.

**Comment by kesselb** [comment]
Is there a folder settings in apps/. Please try to add some more information. If you write that something do not work (like the updater) please include errors or behavior you see.

**Comment by cbattleprogrammer** [comment]
if this happens disable the app manually with occ app:disable

**Comment by Popyllol** [comment]
Sorry forgot to tell about my solution:
Remove all apps_paths from config
`
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/nextcloud-apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
`

After removing it the update runs perfectly as suggested.
Greetings,
   Lars
