### ISSUE TITLE
Show proper feedback in upload progress bar - seems to hang at 100%

### ISSUE THREAD

**Issue by nccguru** [nextcloud/server#202]
Yesterday I reported an error on IRC channel with the progress bar which is instant at 100% while uploading a file. Today I did a fresh install of nextcloud V9.0.51. The error with the bar still exists with and without OPcache oder APCu. Has anyone a solution or the same problem?

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
The progress bar should update normally while uploading a file.

### Actual behaviour
Starting a download means the progress bar jumps to 100% at beginning.

### Server configuration
**Operating system**: CentOS 7

**Web server:** 2.4.6-40.el7.centos.1

**Database:** mariadb.x86_64 1:5.5.47-1.el7_2

**PHP version:**  5.5.21

**Nextcloud version:** 9.0.51 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** wget from nextcloud official site

**Signing status (Nextcloud 9.0 and above):** -

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

sudo -u apache php occ app:list
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /var/www/example.com/nextcloud/lib/private/db/connection.php:54
Stack trace:
#0 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/example.com/nextcloud/lib/private/db/connection.php(137): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/example.com/nextcloud/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/example.com/nextcloud/lib/private/server.php(366): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/example.com/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/example.com/nextcloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/example.com/nextcloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/example.com/nextcloud/lib/private/server.php(886): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/example.com/nextcloud/lib/private/server.php(260): OC\Server->getDatabaseConnection()
#13 /var/www/example.com/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/example.com/nextcloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppConfig')
#15 /var/www/example.com/nextcloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /var/www/example.com/nextcloud/lib/private/server.php(825): OC\ServerContainer->query('AppConfig')
#17 /var/www/example.com/nextcloud/lib/private/server.php(411): OC\Server->getAppConfig()
#18 /var/www/example.com/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#19 /var/www/example.com/nextcloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppManager')
#20 /var/www/example.com/nextcloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#21 /var/www/example.com/nextcloud/lib/private/server.php(1063): OC\ServerContainer->query('AppManager')
#22 /var/www/example.com/nextcloud/lib/private/app.php(254): OC\Server->getAppManager()
#23 /var/www/example.com/nextcloud/lib/private/app.php(103): OC_App::getEnabledApps()
#24 /var/www/example.com/nextcloud/lib/base.php(643): OC_App::loadApps(Array)
#25 /var/www/example.com/nextcloud/lib/base.php(1180): OC::init()
#26 /var/www/example.com/nextcloud/console.php(46): require_once('/var/www/cloud....')
#27 /var/www/example.com/nextcloud/occ(11): require_once('/var/www/cloud....')
```

**The content of config/config.php:**
 ```
sudo -u apache php occ config:list system
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /var/www/example.com/nextcloud/lib/private/db/connection.php:54
Stack trace:
#0 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/example.com/nextcloud/lib/private/db/connection.php(137): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/example.com/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/example.com/nextcloud/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/example.com/nextcloud/lib/private/server.php(366): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/example.com/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/example.com/nextcloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/example.com/nextcloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/example.com/nextcloud/lib/private/server.php(886): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/example.com/nextcloud/lib/private/server.php(260): OC\Server->getDatabaseConnection()
#13 /var/www/example.com/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/example.com/nextcloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppConfig')
#15 /var/www/example.com/nextcloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /var/www/example.com/nextcloud/lib/private/server.php(825): OC\ServerContainer->query('AppConfig')
#17 /var/www/example.com/nextcloud/lib/private/server.php(411): OC\Server->getAppConfig()
#18 /var/www/example.com/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#19 /var/www/example.com/nextcloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppManager')
#20 /var/www/example.com/nextcloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#21 /var/www/example.com/nextcloud/lib/private/server.php(1063): OC\ServerContainer->query('AppManager')
#22 /var/www/example.com/nextcloud/lib/private/app.php(254): OC\Server->getAppManager()
#23 /var/www/example.com/nextcloud/lib/private/app.php(103): OC_App::getEnabledApps()
#24 /var/www/example.com/nextcloud/lib/base.php(643): OC_App::loadApps(Array)
#25 /var/www/example.com/nextcloud/lib/base.php(1180): OC::init()
#26 /var/www/example.com/nextcloud/console.php(46): require_once('/var/www/cloud....')
#27 /var/www/example.com/nextcloud/occ(11): require_once('/var/www/cloud....')

<?php
$CONFIG = array (
  'instanceid' => 'ocm5iraqy5r7',
  'passwordsalt' => 'PASSWORDHASH',
  'secret' => 'HASH',
  'trusted_domains' =>
  array (
    0 => 'example.com',
  ),
  'datadirectory' => '/var/www/example.com/nextcloud/data',
  'overwrite.cli.url' => 'https://example.com',
  'dbtype' => 'mysql',
  'version' => '9.0.51.0',
  'dbname' => 'DBNAME',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'USERNAME',
  'dbpassword' => 'PASSWORDHASH',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\APCu',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO 
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** IE11, Chrome, Firefox (all latest version)

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/owncloud.log)
```
vi owncloud.log
{"reqId":"V2pst7vHUlEzBUvUvI5ltgAAAAA","remoteAddr":"X.X.X.X","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_admuser\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'CloudDBUser'@'localhost' for table 'user'","level":3,"time":"2016-06-22T10:47:19+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"V2pst7vHUlEzBUvUvI5ltgAAAAA","remoteAddr":"X.X.X.X","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'CREATE DATABASE IF NOT EXISTS `DBNAME` CHARACTER SET utf8 COLLATE utf8_bin;':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'CloudDBUser'@'localhost' to database 'DBNAME'","level":3,"time":"2016-06-22T10:47:19+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"V2ps0MaXn4IeYX0p-LebOQAAAAw","remoteAddr":"X.X.X.X","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/installer.php(640): include('\\\/var\\\/www\\\/cloud....')\\n#4 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/installer.php(591): OC_Installer::includeAppScript('\\\/var\\\/www\\\/cloud....')\\n#5 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/installer.php(562): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/base.php(900): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-06-22T10:49:53+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"V2ps0MaXn4IeYX0p-LebOQAAAAw","remoteAddr":"X.X.X.X","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/installer.php(640): include('\\\/var\\\/www\\\/cloud....')\\n#4 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/installer.php(591): OC_Installer::includeAppScript('\\\/var\\\/www\\\/cloud....')\\n#5 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/installer.php(562): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/base.php(900): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/example.com\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-06-22T10:49:53+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"V2pv6lIRdMH7CiRwIcfAOAAAAAo","remoteAddr":"X.X.X.X","app":"core","message":"Login failed: 'apc' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-06-22T11:00:58+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
{"reqId":"V2pzbvKXlgYUzSEf-ggeDgAAAAI","remoteAddr":"X.X.X.X","app":"core","message":"Login failed: 'apc' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-06-22T11:15:59+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
{"reqId":"V2p28o@frnxPScrNa2gQywAAAAM","remoteAddr":"X.X.X.X","app":"core","message":"Login failed: 'apc' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-06-22T11:30:58+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
{"reqId":"V2p5y5CZTeIY4jlU8ksNYgAAAAE","remoteAddr":"X.X.X.X","app":"PHP","message":"OC\\HintException: Memcache \\OC\\Memcache\\APCu not available for local cache at \/var\/www\/example.com\/nextcloud\/lib\/private\/memcache\/factory.php#94","level":3,"time":"2016-06-22T11:43:08+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"--"}
{"reqId":"V2p56fCcCjzDqo1BXc@@NgAAAAI","remoteAddr":"X.X.X.X","app":"PHP","message":"OC\\HintException: Memcache \\OC\\Memcache\\APCu not available for local cache at \/var\/www\/example.com\/nextcloud\/lib\/private\/memcache\/factory.php#94","level":3,"time":"2016-06-22T11:43:37+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"--"}
{"reqId":"V2p6BzJmo9DTmRIooObxRAAAAAU","remoteAddr":"X.X.X.X","app":"PHP","message":"OC\\HintException: Memcache \\OC\\Memcache\\APCu not available for local cache at \/var\/www\/example.com\/nextcloud\/lib\/private\/memcache\/factory.php#94","level":3,"time":"2016-06-22T11:44:07+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"--"}
{"reqId":"V2p6IDEpkeV3ZVTqBrFE5QAAAAA","remoteAddr":"X.X.X.X","app":"core","message":"Memcache \\OC\\Memcache\\APCu not available for local cache Is the matching PHP module installed and enabled?","level":3,"time":"2016-06-22T11:44:32+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"--"}
{"reqId":"V2p6IDEpkeV3ZVTqBrFE5QAAAAA","remoteAddr":"X.X.X.X","app":"core","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Memcache \\\\OC\\\\Memcache\\\\APCu not available for local cache\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/server.php(298): OC\\\\Memcache\\\\Factory->__construct('bcfad4a73725b26...', Object(OC\\\\Log), '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', NULL, NULL)\\n#1 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#2 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('MemCacheFactory')\\n#3 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCacheFactory')\\n#4 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/server.php(877): OC\\\\ServerContainer->query('MemCacheFactory')\\n#5 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/server.php(272): OC\\\\Server->getMemCacheFactory()\\n#6 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#7 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('URLGenerator')\\n#8 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('URLGenerator')\\n#9 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/server.php(850): OC\\\\ServerContainer->query('URLGenerator')\\n#10 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template\\\/functions.php(170): OC\\\\Server->getURLGenerator()\\n#11 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(15): image_path('', 'favicon.ico')\\n#12 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template\\\/base.php(161): include('\\\/var\\\/www\\\/cloud....')\\n#13 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template\\\/base.php(139): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/cloud....')\\n#14 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template.php(222): OC\\\\Template\\\\Base->fetchPage()\\n#15 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template.php(244): OC_Template->fetchPage()\\n#16 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template\\\/base.php(122): OC_Template->fetchPage()\\n#17 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/template.php(319): OC\\\\Template\\\\Base->printPage()\\n#18 \\\/var\\\/www\\\/example.com\\\/nextcloud\\\/index.php(49): OC_Template::printErrorPage('Memcache \\\\\\\\OC\\\\\\\\Me...', 'Is the matching...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/example.com\\\/nextcloud\\\/lib\\\/private\\\/memcache\\\/factory.php\",\"Line\":94}","level":3,"time":"2016-06-22T11:44:32+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"--"}
{"reqId":"V2p6dhbvf0m3tii0460VVAAAAA4","remoteAddr":"X.X.X.X","app":"core","message":"Login failed: 'apc' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-06-22T11:45:58+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by vincchan** [comment]
Cannot replicate this. What kind of file are you uploading?

**Comment by MorrisJobke** [comment]
> Cannot replicate this. What kind of file are you uploading?

This is mostly due to some operations that happen inside the server. The upload itself is done, but the server moves the file on the hard disk for example, which takes time. Then the upload hangs at 100% (because from the client there is not much to do left, but the server does some stuff)

**Comment by nccguru** [comment]
I am uploading different kinds of files. 
For example: 
.exe with a file size of 30MB
.zip with a file size of 350MB

The problem seems not to be related to the file size. Behaviour is always the same. Upload is running in the background and progress bar is at 100% after a second while upload began. After a while in relation to file size the upload finished.

**Comment by nccguru** [comment]
Is there a php package or module which is needed by the progress bar?

**Comment by nccguru** [comment]
Do you have another idea what I can do or test?

**Comment by MorrisJobke** [comment]
> Do you have another idea what I can do or test?

Currently not. We need to check if and how we could improve the feedback for the user here.

**Comment by nccguru** [comment]
I have another information for you.
I currently tested the bevaviour of file uploading on my webservers (one CentOS7 and one Ubuntu). Both are showing exactly the same result in a fresh installed environment. 

While running an inspector in the OWNCLOUD demo environment I see that the progress bar there is updating as it should do.

Maybe that is an interesting information for you?

**Comment by nccguru** [comment]
Hello Community,

the error is only related to Windows 10 operating system. But I do not know what is causing this error. Using the webclient via Windows 7/8, Safari or for example Ubuntu results in a working progress bar!

Any idea for this behaviour?

**Comment by nccguru** [comment]
Another update while I am doing more troubleshooting.

If you upload a file over LAN there is no problem with the progress bar. While using the same PC and connecting to nextcloud over WAN results in a progress bar which is immediately at 100%.

**Comment by nccguru** [comment]
I have found the problem in that case! I am using Sophos Endpoint Security with a module called Web Control. This module is causing the behaviour to fill the progress bar immediately to 100%. 

I am actually debugging this error and try some other configuration in this tool.

**Comment by MorrisJobke** [comment]
I closed this because another middleware is doing something. We are more than happy if you find a workaround for this to allow proper handling.

Thanks for your investigations.
