### ISSUE TITLE
Verifying integrity - Signature of update is not valid

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/server#21307]
I am on 18.0.3
I get the message 18.0.5 is available
when I start the updater it says it going to update to 18.0.4.

which seems ok as an intermediate step I guess, but still...

Then after creating the backup and download the updates it messages:

Verifying integrity - Signature of update is not valid

My nextcloud runs on an apache 2.4 host. Host is behind nginx reverse proxy. When doing same without reverse proxy, same happens.

**Comment by chriscroome** [comment]
I'm unable to update also:

```
php updater/updater.phar

Nextcloud Updater - version: v16.0.3-3-ga0c2b25 dirty

Current version is 18.0.1.

Update to Nextcloud 18.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✘] Verify integrity failed
Signature of update is not valid

Update failed. To resume or retry just execute the updater again.
```
I have tried this several times...

**Comment by zech** [comment]
I've got the same issue.

Currently on `18.0.3` and getting notifications about `18.0.5`.

Updater tries to download `18.0.4` and complains about an invalid signature.

```
2020-06-08T13:44:32+0200 2iuiCQzeeg [info] updaterServer: https://updates.nextcloud.com/updater_server/
2020-06-08T13:44:32+0200 2iuiCQzeeg [info] releaseChannel: stable
2020-06-08T13:44:32+0200 2iuiCQzeeg [info] internal version: 18.0.3.0
2020-06-08T13:44:32+0200 2iuiCQzeeg [info] updateURL: https://updates.nextcloud.com/updater_server/?version=18x0x3x0xxxstablexx2020-03-11T14%3A54%3A25%2B00%3A00+93cae9d2d17112084c882df902b31604151669c0x7x3x18
2020-06-08T13:44:32+0200 2iuiCQzeeg [info] getUpdateServerResponse response: Array
(
    [version] => 18.0.4.2
    [versionstring] => Nextcloud 18.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
    [web] => https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=18.0.4
    [autoupdater] => 1
    [eol] => 0
    [signature] => UZtvzq+6HDxwjG5BYJGA2dXhWXR+pkMxlCVLYicWfLdHNk+Cy9rhbM+wcXD4ihLW
aOIl1FeK737GbI69z5MM53eRPDu/uqyFyTZfvzk+ia6oh5UHOBpcSZABuqmLRHyL
v+kTiAzY/XtO23EvvFsCZahmOQi2forxutbc07X85SZavUuj9uL3wakp71LZIJoj
llOq6xS08I8ayEfqkmzVyHXAiXqwJvhRQJ2NqxAZlzbjzljoPDZbmWo4uZljDN1O
4wtU37N/nM+NYGx5biD5TuchqdX5LE8aI0JSeVa3APCvpVCPt7PFWrvMD3TgjpQ3
k4TP/m2/0C2ezzBQVP8Atg==
)

2020-06-08T13:44:32+0200 2iuiCQzeeg [info] storage location: /data/updater-oc4t1sj9cqsd/downloads/
2020-06-08T13:44:33+0200 2iuiCQzeeg [error] POST request failed with other exception
2020-06-08T13:44:33+0200 2iuiCQzeeg [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /config/www/nextcloud/updater/index.php(1342): Updater->verifyIntegrity()
#1 {main}
File:/config/www/nextcloud/updater/index.php
Line:761

2020-06-08T13:44:33+0200 2iuiCQzeeg [info] rollbackChanges("5")
2020-06-08T13:44:33+0200 2iuiCQzeeg [info] unlink .step
2020-06-08T13:44:33+0200 2iuiCQzeeg [info] end of  rollbackChanges()

```

**Comment by Galbar** [comment]
I have the same problem upgrading from 17.0.7 to 18.0.4

**Comment by alabusag** [comment]
We have the same problem too, upgrading from 17.0.7 to 18.0.4

**Comment by ivavis** [comment]
Same problem here, upgrading from 17.0.7 to 18.0.4

**Comment by t0mcat1337** [comment]
Same problem here upgrading from 18.0.0/18.0.1 to 18.0.4 with the updater.phar.

The downloaded nextcloud-18.0.4.zip in the updaters download dir seems to be quit ok. I used this to manually upgrade 2 clouds without problems.

**Comment by excedra** [comment]
Same issue here while updating from 18.0.3 to 18.0.4. 

Full log: [nextcloud_log.txt](https://github.com/nextcloud/server/files/4746873/nextcloud_log.txt)

> (
    [version] => 18.0.4.2
    [versionstring] => Nextcloud 18.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
    [web] => https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=18.0.4
    [autoupdater] => 1
    [eol] => 0
    [signature] => UZtvzq+6HDxwjG5BYJGA2dXhWXR+pkMxlCVLYicWfLdHNk+Cy9rhbM+wcXD4ihLW
aOIl1FeK737GbI69z5MM53eRPDu/uqyFyTZfvzk+ia6oh5UHOBpcSZABuqmLRHyL
v+kTiAzY/XtO23EvvFsCZahmOQi2forxutbc07X85SZavUuj9uL3wakp71LZIJoj
llOq6xS08I8ayEfqkmzVyHXAiXqwJvhRQJ2NqxAZlzbjzljoPDZbmWo4uZljDN1O
4wtU37N/nM+NYGx5biD5TuchqdX5LE8aI0JSeVa3APCvpVCPt7PFWrvMD3TgjpQ3
k4TP/m2/0C2ezzBQVP8Atg==
)
2020-06-08T15:07:15+0000 Jdhf2SvtgT [info] storage location: #herewasmystoragedir#/updater-ocfk02f98zpt/downloads/
2020-06-08T15:07:15+0000 Jdhf2SvtgT [error] executeStep request failed with other exception
2020-06-08T15:07:15+0000 Jdhf2SvtgT [error] Exception: Exception
Message: Signature of update is not valid

**Comment by Alfs29** [comment]
Same problem here, upgrading from 17.0.7 to 18.0.4

**Comment by tryallthethings** [comment]
Seeing the same issue while trying to update from 18.0.3 to 18.0.4 via web updater. Additionally the notification reports that 18.0.5 is already available but the updater doesn't see it.

Log:
`2020-06-08T17:53:39+0200 u9O2Lksj1H [info] request to updater
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] currentStep()
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] show HTML page
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] current version: 18.0.3 build time: 2020-03-11T14:54:25+00:00 93cae9d2d17112084c882df902b31604151669c0
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] getUpdateServerResponse()
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] updaterServer: https://updates.nextcloud.com/updater_server/
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] releaseChannel: stable
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] internal version: 18.0.3.0
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] updateURL: https://updates.nextcloud.com/updater_server/?version=18x0x3x0xxxstablexx2020-03-11T14%3A54%3A25%2B00%3A00+93cae9d2d17112084c882df902b31604151669c0x7x3$
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] getUpdateServerResponse response: Array
(
    [version] => 18.0.4.2
    [versionstring] => Nextcloud 18.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
    [web] => https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=18.0.4
    [autoupdater] => 1
    [eol] => 0
    [signature] => UZtvzq+6HDxwjG5BYJGA2dXhWXR+pkMxlCVLYicWfLdHNk+Cy9rhbM+wcXD4ihLW
aOIl1FeK737GbI69z5MM53eRPDu/uqyFyTZfvzk+ia6oh5UHOBpcSZABuqmLRHyL
v+kTiAzY/XtO23EvvFsCZahmOQi2forxutbc07X85SZavUuj9uL3wakp71LZIJoj
llOq6xS08I8ayEfqkmzVyHXAiXqwJvhRQJ2NqxAZlzbjzljoPDZbmWo4uZljDN1O
4wtU37N/nM+NYGx5biD5TuchqdX5LE8aI0JSeVa3APCvpVCPt7PFWrvMD3TgjpQ3
k4TP/m2/0C2ezzBQVP8Atg==
)

2020-06-08T17:53:39+0200 u9O2Lksj1H [info] checkForUpdate() Array
(
    [version] => 18.0.4.2
    [versionstring] => Nextcloud 18.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
    [web] => https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=18.0.4
    [autoupdater] => 1
    [eol] => 0
    [signature] => UZtvzq+6HDxwjG5BYJGA2dXhWXR+pkMxlCVLYicWfLdHNk+Cy9rhbM+wcXD4ihLW
aOIl1FeK737GbI69z5MM53eRPDu/uqyFyTZfvzk+ia6oh5UHOBpcSZABuqmLRHyL
v+kTiAzY/XtO23EvvFsCZahmOQi2forxutbc07X85SZavUuj9uL3wakp71LZIJoj
llOq6xS08I8ayEfqkmzVyHXAiXqwJvhRQJ2NqxAZlzbjzljoPDZbmWo4uZljDN1O
4wtU37N/nM+NYGx5biD5TuchqdX5LE8aI0JSeVa3APCvpVCPt7PFWrvMD3TgjpQ3
k4TP/m2/0C2ezzBQVP8Atg==
)

2020-06-08T17:53:39+0200 u9O2Lksj1H [info] getChangelogURL()
2020-06-08T17:53:39+0200 u9O2Lksj1H [info] end of checkForUpdate() Update to Nextcloud 18.0.4 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span>$
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] request to updater
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] currentStep()
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] POST request for step "1"
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] startStep("1")
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] checkForExpectedFilesAndFolders()
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] end of checkForExpectedFilesAndFolders()
2020-06-08T17:53:44+0200 qP4Hm0WYlB [info] endStep("1")
2020-06-08T17:53:44+0200 IWUl9qtDja [info] request to updater
2020-06-08T17:53:44+0200 IWUl9qtDja [info] currentStep()
2020-06-08T17:53:44+0200 IWUl9qtDja [info] Step 1 is in state "end".
2020-06-08T17:53:44+0200 IWUl9qtDja [info] POST request for step "2"
2020-06-08T17:53:44+0200 IWUl9qtDja [info] startStep("2")
2020-06-08T17:53:44+0200 IWUl9qtDja [info] checkWritePermissions()
2020-06-08T17:53:44+0200 IWUl9qtDja [info] end of checkWritePermissions()
2020-06-08T17:53:44+0200 IWUl9qtDja [info] endStep("2")
2020-06-08T17:53:44+0200 VNChOgH3d4 [info] request to updater
2020-06-08T17:53:44+0200 VNChOgH3d4 [info] currentStep()
2020-06-08T17:53:44+0200 VNChOgH3d4 [info] Step 2 is in state "end".
2020-06-08T17:53:44+0200 VNChOgH3d4 [info] POST request for step "3"
2020-06-08T17:53:44+0200 VNChOgH3d4 [info] startStep("3")
2020-06-08T17:53:44+0200 VNChOgH3d4 [info] createBackup()
2020-06-08T17:53:45+0200 VNChOgH3d4 [info] end of createBackup()
2020-06-08T17:53:45+0200 VNChOgH3d4 [info] endStep("3")
2020-06-08T17:53:45+0200 NffX625zSt [info] request to updater
2020-06-08T17:53:45+0200 NffX625zSt [info] currentStep()
2020-06-08T17:53:45+0200 NffX625zSt [info] Step 3 is in state "end".
2020-06-08T17:53:45+0200 NffX625zSt [info] POST request for step "4"
2020-06-08T17:53:45+0200 NffX625zSt [info] startStep("4")
2020-06-08T17:53:45+0200 NffX625zSt [info] downloadUpdate()
2020-06-08T17:53:45+0200 NffX625zSt [info] getUpdateServerResponse()
2020-06-08T17:53:45+0200 NffX625zSt [info] updaterServer: https://updates.nextcloud.com/updater_server/
2020-06-08T17:53:45+0200 NffX625zSt [info] releaseChannel: stable
2020-06-08T17:53:45+0200 NffX625zSt [info] internal version: 18.0.3.0
2020-06-08T17:53:45+0200 NffX625zSt [info] updateURL: https://updates.nextcloud.com/updater_server/?version=18x0x3x0xxxstablexx2020-03-11T14%3A54%3A25%2B00%3A00+93cae9d2d17112084c882df902b31604151669c0x7x3$
2020-06-08T17:53:45+0200 NffX625zSt [info] getUpdateServerResponse response: Array
(
    [version] => 18.0.4.2
    [versionstring] => Nextcloud 18.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
    [web] => https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=18.0.4
    [autoupdater] => 1
    [eol] => 0
    [signature] => UZtvzq+6HDxwjG5BYJGA2dXhWXR+pkMxlCVLYicWfLdHNk+Cy9rhbM+wcXD4ihLW
aOIl1FeK737GbI69z5MM53eRPDu/uqyFyTZfvzk+ia6oh5UHOBpcSZABuqmLRHyL
v+kTiAzY/XtO23EvvFsCZahmOQi2forxutbc07X85SZavUuj9uL3wakp71LZIJoj
llOq6xS08I8ayEfqkmzVyHXAiXqwJvhRQJ2NqxAZlzbjzljoPDZbmWo4uZljDN1O
4wtU37N/nM+NYGx5biD5TuchqdX5LE8aI0JSeVa3APCvpVCPt7PFWrvMD3TgjpQ3
k4TP/m2/0C2ezzBQVP8Atg==
)

2020-06-08T17:53:47+0200 NffX625zSt [info] end of downloadUpdate()
2020-06-08T17:53:47+0200 NffX625zSt [info] endStep("4")
2020-06-08T17:53:47+0200 adLM7nhnaj [info] request to updater
2020-06-08T17:53:47+0200 adLM7nhnaj [info] currentStep()
2020-06-08T17:53:47+0200 adLM7nhnaj [info] Step 4 is in state "end".
2020-06-08T17:53:47+0200 adLM7nhnaj [info] POST request for step "5"
2020-06-08T17:53:47+0200 adLM7nhnaj [info] startStep("5")
2020-06-08T17:53:47+0200 adLM7nhnaj [info] verifyIntegrity()
2020-06-08T17:53:47+0200 adLM7nhnaj [info] getUpdateServerResponse()
2020-06-08T17:53:47+0200 adLM7nhnaj [info] updaterServer: https://updates.nextcloud.com/updater_server/
2020-06-08T17:53:47+0200 adLM7nhnaj [info] releaseChannel: stable
2020-06-08T17:53:47+0200 adLM7nhnaj [info] internal version: 18.0.3.0
2020-06-08T17:53:47+0200 adLM7nhnaj [info] updateURL: https://updates.nextcloud.com/updater_server/?version=18x0x3x0xxxstablexx2020-03-11T14%3A54%3A25%2B00%3A00+93cae9d2d17112084c882df902b31604151669c0x7x3$
2020-06-08T17:53:47+0200 adLM7nhnaj [info] getUpdateServerResponse response: Array
(
    [version] => 18.0.4.2
    [versionstring] => Nextcloud 18.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
    [web] => https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=18.0.4
    [autoupdater] => 1
    [eol] => 0
    [signature] => UZtvzq+6HDxwjG5BYJGA2dXhWXR+pkMxlCVLYicWfLdHNk+Cy9rhbM+wcXD4ihLW
aOIl1FeK737GbI69z5MM53eRPDu/uqyFyTZfvzk+ia6oh5UHOBpcSZABuqmLRHyL
v+kTiAzY/XtO23EvvFsCZahmOQi2forxutbc07X85SZavUuj9uL3wakp71LZIJoj
llOq6xS08I8ayEfqkmzVyHXAiXqwJvhRQJ2NqxAZlzbjzljoPDZbmWo4uZljDN1O
4wtU37N/nM+NYGx5biD5TuchqdX5LE8aI0JSeVa3APCvpVCPt7PFWrvMD3TgjpQ3
k4TP/m2/0C2ezzBQVP8Atg==
)

2020-06-08T17:53:47+0200 adLM7nhnaj [info] storage location: /var/www/oc_music/updater-octhfy1otkrr/downloads/
2020-06-08T17:53:49+0200 adLM7nhnaj [error] POST request failed with other exception
2020-06-08T17:53:49+0200 adLM7nhnaj [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /var/www/oc/music/updater/index.php(1342): Updater->verifyIntegrity()
#1 {main}
File:/var/www/oc/music/updater/index.php
Line:761

2020-06-08T17:53:49+0200 adLM7nhnaj [info] rollbackChanges("5")
2020-06-08T17:53:49+0200 adLM7nhnaj [info] unlink .step
2020-06-08T17:53:49+0200 adLM7nhnaj [info] end of  rollbackChanges()
`

**Comment by Alfs29** [comment]
i dont see 18.0.5 beeing available in Administration-Overview

**Comment by mthewes** [comment]
Could this be related to 18.0.5 having been pulled due to a bug: [Nextcloud blog](https://nextcloud.com/blog/minor-releases-18-0-5-17-0-7-and-16-0-11-are-here-end-of-support-for-16/) ?

**Comment by hdbreaker** [comment]
I'm having exactly the same issue here

**Comment by Schwaus** [comment]
Same here... Update from 18.0.3 to 18.0.4

**Comment by roNn23** [comment]
Same here :( Update from 18.0.2 to 18.0.4

**Comment by ohunecker** [comment]
Same here! From 18.0.3 to 18.0.4

```console
Nextcloud Updater - version: v16.0.3-3-ga0c2b25 dirty

Current version is 18.0.3.

Update to Nextcloud 18.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-18.0.4.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✘] Verify integrity failed
Signature of update is not valid

Update failed. To resume or retry just execute the updater again.
```

**Comment by kesselb** [comment]
There is a regression in 18.0.5 that breaks the sidebar. They withdraw Nextcloud 18.0.5 and forgot to change the signature back.

18.0.4 to 18.0.5: https://github.com/nextcloud/updater_server/commit/2ab4470b81309eece7bfc61adf960afd4d457fb6 (see signature changed)

18.0.5 to 18.0.4: https://github.com/nextcloud/updater_server/commit/d274425f3fb2ebe262af84c98643d286d29811ed 

Luckily 18.0.6 is out now with a fixed sidebar and the right signatures: https://github.com/nextcloud/updater_server/commit/9ec3b8de52d518ce82f07a883edf6c86233d5d80

**Comment by tryallthethings** [comment]
Can confirm. 18.0.6 is available via web updater and I could update my two instances from 18.0.3 to 18.0.6 without any issues.

**Comment by hdbreaker** [comment]
@tryallthethings seems to fix the issue, I was able to update my Nextcloud instance to 18.0.6 without any issue! Thanks!
