### ISSUE TITLE
User settings page is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#21755]
```
Technical details

    Remote Address: 127.0.0.1
    Request ID: lFgDjqYka5a5Ite42jsn
    Type: Exception
    Code: 0
    Message: no action available
    File: /home/nickv/Nextcloud/20/server/lib/private/Route/Router.php
    Line: 306


Trace

#0 /home/nickv/Nextcloud/20/server/lib/base.php(1004): OC\Route\Router->match('/settings/user')
#1 /home/nickv/Nextcloud/20/server/index.php(37): OC::handleRequest()
#2 {main}
```

Regression from #21643

**Comment by rullzer** [comment]
Fixed

**Comment by MorrisJobke** [comment]
> Fixed

Where?

**Comment by MorrisJobke** [comment]
But yes - I can't reproduce with latest master anymore.

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/21758

Basically 1 tiny change in the logic. I merged because it was failing all other jobs.
