### ISSUE TITLE
ftp external file:scan does loop by special characters in filename, or fails completly resulting in unusable folderstructures and or bloated database

### ISSUE THREAD

**Issue by viisauksena** [nextcloud/server#22497]
### Steps to reproduce
1. make a external (for all users) ftp connection and put there some crafted-named file - ie something with a # in it
2. start file:scan

### Expected behaviour
correctly scan files 

### Actual behaviour
reloop back to some part of file and get "stuck" in file:scan ... while every minute or so (timeout?) it scan a new file , but only adding more complexity to the string , we believe that "something" is just timing out - which makes a filescan ultraslow and it may get messy - we did not yet check the database entry of this file for example, if you want us to try/do specific things we happy to try/help out

even our database is bloated with 1G ` 929M Aug 30 05:31 nextcloud-sqlbkp_20200830.bak`
 
```
### on the ftp server itself it looks "normal like this"
/ftproot/other/E-Books/programmieren/doc.lagout.org/programmation# file C\#*
C#-Visual Basic Bilingual Dictionary_ Visual Studio 2015 Edition [Patrick 2015-05-27].pdf: PDF document, version 1.3
```

``` occ file:scan -vv <user>
Folder  /<user>/files/ftp_other(ro)/E-Books/programmieren/doc.lagout.org/programmation/C#-Visual Basic Bilingual Dictionary_ Visual Studio 2015 Edition [Patrick 2015-05-27].pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/Penser en C   - Bruce Eckel (Traduction) 2008.pdf/C For Engineers and Scientists_ An Introduction to Programming with ANSI C [Bronson 1993].pdf/Poo C++ 2.pdf
```

### Server configuration
debian linux, with nextcloud 17,18 and 19 same behaviour

``` 
### uname -a
Linux nextcloud 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
### php -v
PHP 7.4.9 (cli) (built: Aug  7 2020 14:55:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
### sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "somedomain",
            "someotherdomain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.2.2",
        "overwrite.cli.url": "https:\/\/someotherdomain",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Comment by viisauksena** [comment]
after we renamed the file described above - i.e. removed the # ...
and `occ file:cleanup` we reduced the database size down to normal and get after the third run 
`295782 orphaned file cache entries deleted`
this seems a bug of not correct escaped characters either in the database or the file:scan process

**Comment by viisauksena** [comment]
by the further investigation of other errors (we had plenty problems with our rather big ftp storage) - we found that "[" and or "]" are also breaking the scan completly for whatever user is running into it, resulting in unfinished scans ... and these folder as a whole are than unusable in nextcloud-webgui since there are no entrys. 
here a clear error is produced - 
```
occ file:scan user
Folder  /user/files/ftp_serien(ro)/nicer_shice_serie[TGx]                                                                                  
Exception during scan: Trying to access array offset on value of type null
#0 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(159): OCA\Files\Command\Scan->exceptionErrorHandler()                                                              
#1 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php(207): OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()                                                    
#2 [internal function]: OC\Files\Storage\Wrapper\Encryption->getDirectoryContent()                                                                                                              
#3 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(408): iterator_to_array()                                                                                                             
#4 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren()                                                                                        
#5 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren()                                                                                          
#6 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren()                                                                                          
#7 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan()                                                                                                  
#8 /var/www/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan()                                                                                                      
#9 /var/www/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles()                                                                                                 
#10 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()                                                                                     
#11 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()                                                                                             
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run()                                                                                              
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()                                                                     
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()                                                                            
#15 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()                                                                                   
#16 /var/www/nextcloud/console.php(100): OC\Console\Application->run()                                                                                                                          
#17 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')                                                                                                                              
#18 {main}                                                                         
```

**Comment by viisauksena** [comment]
this https://github.com/nextcloud/server/issues/22836 and other file:scan or filename length error may be connected to this issue

**Comment by viisauksena** [comment]
we have a solution, but no idea of further impacts
we could simply check if array is empty and continue (ie. dont do anything in this foreach iteration) ... so the function getDirectoryContent (line 159)  in **/var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php**
will add **if (is_array($data) == false) continue;**

we have no idea if this would break anything, for us this modification works flawlessly

```
public function getDirectoryContent($directory): \Traversable {
                foreach ($this->getWrapperStorage()->getDirectoryContent($directory) as $data) {
                        if (is_array($data) == false) continue;
                        $data['scan_permissions'] = isset($data['scan_permissions']) ? $data['scan_permissions'] : $data['permissions'];
                        $data['permissions'] &= $this->mask;

                        yield $data;
                }
        }
```

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
