### ISSUE TITLE
Argument 1 passed to OC\Files\Config\CachedMountInfo::__construct() must implement interface OCP\IUser, null given

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2297]
@icewind1991 THX

```
index	TypeError: Argument 1 passed to OC\Files\Config\CachedMountInfo::__construct() must implement interface OCP\IUser, null given, called in /var/www/html/lib/private/Files/Config/UserMountCache.php on line 191
/var/www/html/lib/private/Files/Config/UserMountCache.php - line 191: OC\Files\Config\CachedMountInfo->__construct(NULL, 3, 41, '/demo/files/Eng...', NULL, 'files/Engineeri...')
[internal function] OC\Files\Config\UserMountCache->dbRowToMountInfo(Array)
/var/www/html/lib/private/Files/Config/UserMountCache.php - line 226: array_map(Array, Array)
/var/www/html/lib/private/Files/Config/UserMountCache.php - line 282: OC\Files\Config\UserMountCache->getMountsForStorageId(3)
/var/www/html/lib/private/Files/Node/Folder.php - line 268: OC\Files\Config\UserMountCache->getMountsForFileId(30332)
/var/www/html/lib/private/Preview/GeneratorHelper.php - line 67: OC\Files\Node\Folder->getById(30332)
/var/www/html/lib/private/Preview/GeneratorHelper.php - line 53: OC\Preview\GeneratorHelper->getViewAndPath(Object(OC\Files\Node\File))
/var/www/html/lib/private/Preview/Generator.php - line 155: OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\TXT), Object(OC\Files\Node\File), 2048, 2048)
/var/www/html/lib/private/Preview/Generator.php - line 108: OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'text/plain')
/var/www/html/lib/private/PreviewManager.php - line 182: OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 150, 150, true, 'fill', 'text/plain')
/var/www/html/core/Controller/PreviewController.php - line 113: OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 150, 150, true, 'fill')
[internal function] OC\Core\Controller\PreviewController->getPreview(Object(OC\Files\Node\File), 150, 150, false, true, 'fill')
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\PreviewController), 'getPreview')
/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\PreviewController), 'getPreview')
/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Core\\Control...', 'getPreview', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/lib/base.php - line 1013: OC\Route\Router->match('/core/preview.p...')
/var/www/html/index.php - line 40: OC handleRequest()
{main}
```

```
{"reqId":"GY934utYiAqENMSw1Uab","remoteAddr":"178.199.45.200","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 1 passed to OC\\\\Files\\\\Config\\\\CachedMountInfo::__construct() must implement interface OCP\\\\IUser, null given, called in \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php on line 191\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(191): OC\\\\Files\\\\Config\\\\CachedMountInfo->__construct(NULL, 3, 41, '\\\/demo\\\/files\\\/Eng...', NULL, 'files\\\/Engineeri...')\\n#1 [internal function]: OC\\\\Files\\\\Config\\\\UserMountCache->dbRowToMountInfo(Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(226): array_map(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(282): OC\\\\Files\\\\Config\\\\UserMountCache->getMountsForStorageId(3)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(268): OC\\\\Files\\\\Config\\\\UserMountCache->getMountsForFileId(30332)\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/GeneratorHelper.php(67): OC\\\\Files\\\\Node\\\\Folder->getById(30332)\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/GeneratorHelper.php(53): OC\\\\Preview\\\\GeneratorHelper->getViewAndPath(Object(OC\\\\Files\\\\Node\\\\File))\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/Generator.php(155): OC\\\\Preview\\\\GeneratorHelper->getThumbnail(Object(OC\\\\Preview\\\\TXT), Object(OC\\\\Files\\\\Node\\\\File), 2048, 2048)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/Generator.php(108): OC\\\\Preview\\\\Generator->getMaxPreview(Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), Object(OC\\\\Files\\\\Node\\\\File), 'text\\\/plain')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/PreviewManager.php(182): OC\\\\Preview\\\\Generator->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 150, 150, true, 'fill', 'text\\\/plain')\\n#10 \\\/var\\\/www\\\/html\\\/core\\\/Controller\\\/PreviewController.php(113): OC\\\\PreviewManager->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 150, 150, true, 'fill')\\n#11 [internal function]: OC\\\\Core\\\\Controller\\\\PreviewController->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 150, 150, false, true, 'fill')\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\PreviewController), 'getPreview')\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\PreviewController), 'getPreview')\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'getPreview', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1013): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#19 \\\/var\\\/www\\\/html\\\/index.php(40): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/CachedMountInfo.php\",\"Line\":71}","level":3,"time":"2016-11-24T09:23:06+00:00","method":"GET","url":"\/core\/preview.png?file=CENSOREDFILENAME.TXT&x=150&y=150&c=54560e2edaed7f13272e6e2130b82019","user":"lukas","version":"11.0.0.2"}
```

**Comment by MorrisJobke** [comment]
I also noticed this:

```
Technische Details
Entfernte Adresse: 92.206.40.223
Anfragekennung: dJMMyapnZS6dBD1E4Euz
Typ: TypeError
Code: 0
Nachricht: Argument 1 passed to OC\Files\Config\CachedMountInfo::__construct() must implement interface OCP\IUser, null given, called in /var/www/html/lib/private/Files/Config/UserMountCache.php on line 191
Datei: /var/www/html/lib/private/Files/Config/CachedMountInfo.php
Zeile: 71

Ablauf
#0 /var/www/html/lib/private/Files/Config/UserMountCache.php(191): OC\Files\Config\CachedMountInfo->__construct(NULL, 12, 9136, '/demo/files/Pho...', NULL, 'files/Photos')
#1 [internal function]: OC\Files\Config\UserMountCache->dbRowToMountInfo(Array)
#2 /var/www/html/lib/private/Files/Config/UserMountCache.php(226): array_map(Array, Array)
#3 /var/www/html/lib/private/Files/Config/UserMountCache.php(282): OC\Files\Config\UserMountCache->getMountsForStorageId(12)
#4 /var/www/html/lib/private/Files/Node/Folder.php(268): OC\Files\Config\UserMountCache->getMountsForFileId(26162)
#5 /var/www/html/lib/private/Share20/Share.php(165): OC\Files\Node\Folder->getById(26162)
#6 /var/www/html/apps/files_sharing/lib/Controller/ShareController.php(261): OC\Share20\Share->getNode()
#7 /var/www/html/apps/files_sharing/lib/Controller/ShareController.php(291): OCA\Files_Sharing\Controller\ShareController->validateShare(Object(OC\Share20\Share))
#8 [internal function]: OCA\Files_Sharing\Controller\ShareController->showShare('xxxxxxxxxx', '')
#9 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Sharing\Controller\ShareController), 'showShare')
#11 /var/www/html/lib/private/AppFramework/App.php(114): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Sharing\Controller\ShareController), 'showShare')
#12 /var/www/html/lib/public/AppFramework/App.php(136): OC\AppFramework\App::main('ShareController', 'showShare', Object(OC\AppFramework\DependencyInjection\DIContainer))
#13 /var/www/html/core/routes.php(88): OCP\AppFramework\App->dispatch('ShareController', 'showShare')
#14 [internal function]: OC\Route\Router->{closure}(Array)
#15 /var/www/html/lib/private/Route/Router.php(299): call_user_func(Object(Closure), Array)
#16 /var/www/html/lib/base.php(1013): OC\Route\Router->match('/s/xxxxxxxxx...')
#17 /var/www/html/index.php(40): OC::handleRequest()
#18 {main}
```

**Comment by MorrisJobke** [comment]
This happens for me for all direct file links (either public shares or the ones with `f/FILEID`)

**Comment by MorrisJobke** [comment]
@karlitschek another blocker

**Comment by karlitschek** [comment]
yep

**Comment by LukasReschke** [comment]
I added a json_encode and error logging at https://github.com/nextcloud/server/blob/0d842e0550a15b7b6c501dae2ec24a61b72ef8c9/lib/private/Files/Config/UserMountCache.php#L190

This is the result:

```json
{
   "storage_id":"3",
   "root_id":"41",
   "user_id":"demo",
   "mount_point":"\/demo\/files\/Engineering\/",
   "mount_id":null,
   "path":"files\/Engineering"
}
```

The user `demo` is however already deleted from the system since a longer time. Why do we try to setup the FS on that user?
