### ISSUE TITLE
Backends provided no user object

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2298]
I do have an incoming federated share from @blizzz on our instance and when opening the folder that includes this file I get the following error messages in the log:

```
Backends provided no user object for arthur@ovin.schiwon.me/	
```

```
	OC\User\NoUserException: Backends provided no user object
[internal function] OC\Files\Node\Root->getUserFolder('arthur@o.schiwo...')
/var/www/html/lib/private/Files/Node/LazyRoot.php - line 65: call_user_func_array(Array, Array)
/var/www/html/lib/private/Files/Node/LazyRoot.php - line 282: OC\Files\Node\LazyRoot->__call('getUserFolder', Array)
/var/www/html/lib/private/Preview/GeneratorHelper.php - line 65: OC\Files\Node\LazyRoot->getUserFolder('arthur@o.schiwo...')
/var/www/html/lib/private/Preview/GeneratorHelper.php - line 53: OC\Preview\GeneratorHelper->getViewAndPath(Object(OC\Files\Node\File))
/var/www/html/lib/private/Preview/Generator.php - line 155: OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 2048, 2048)
/var/www/html/lib/private/Preview/Generator.php - line 108: OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg')
/var/www/html/lib/private/PreviewManager.php - line 182: OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 71, 71, true, 'fill', 'image/jpeg')
/var/www/html/core/Controller/PreviewController.php - line 113: OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 71, 71, true, 'fill')
[internal function] OC\Core\Controller\PreviewController->getPreview(Object(OC\Files\Node\File), 71, 71, false, false, 'fill')
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\PreviewController), 'getPreview')
/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\PreviewController), 'getPreview')
/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Core\\Control...', 'getPreview', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/lib/base.php - line 1013: OC\Route\Router->match('/core/preview.p...')
/var/www/html/index.php - line 40: OC handleRequest()
{main}
```

```
{"reqId":"ut17\/YED6JCo9Qz+R5Jr","remoteAddr":"178.199.45.200","app":"files","message":"Backends provided no user object for arthur@ovin.schiwon.me\/","level":3,"time":"2016-11-24T09:59:48+00:00","method":"GET","url":"\/core\/preview.png?file=%2FConf+badge+models.jpg&c=b122e008ca8b7b4608eacdef2f197f56&x=71&y=71&forceIcon=0","user":"lukas","version":"11.0.0.2"}
{"reqId":"ut17\/YED6JCo9Qz+R5Jr","remoteAddr":"178.199.45.200","app":"index","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('arthur@ovin.sch...')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/GeneratorHelper.php(65): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('arthur@ovin.sch...')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/GeneratorHelper.php(53): OC\\\\Preview\\\\GeneratorHelper->getViewAndPath(Object(OC\\\\Files\\\\Node\\\\File))\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/Generator.php(155): OC\\\\Preview\\\\GeneratorHelper->getThumbnail(Object(OC\\\\Preview\\\\JPEG), Object(OC\\\\Files\\\\Node\\\\File), 2048, 2048)\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Preview\\\/Generator.php(108): OC\\\\Preview\\\\Generator->getMaxPreview(Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), Object(OC\\\\Files\\\\Node\\\\File), 'image\\\/jpeg')\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/PreviewManager.php(182): OC\\\\Preview\\\\Generator->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 71, 71, true, 'fill', 'image\\\/jpeg')\\n#8 \\\/var\\\/www\\\/html\\\/core\\\/Controller\\\/PreviewController.php(113): OC\\\\PreviewManager->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 71, 71, true, 'fill')\\n#9 [internal function]: OC\\\\Core\\\\Controller\\\\PreviewController->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 71, 71, false, false, 'fill')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\PreviewController), 'getPreview')\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\PreviewController), 'getPreview')\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'getPreview', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1013): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#17 \\\/var\\\/www\\\/html\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":366}","level":3,"time":"2016-11-24T09:59:48+00:00","method":"GET","url":"\/core\/preview.png?file=%2FConf+badge+models.jpg&c=b122e008ca8b7b4608eacdef2f197f56&x=71&y=71&forceIcon=0","user":"lukas","version":"11.0.0.2"}
```

**Comment by LukasReschke** [comment]
@rullzer Ideas? That seems related to the preview generator.

**Comment by rullzer** [comment]
I'll have a look
