### ISSUE TITLE
Upgrade from 19.0.3 to 19.0.4 - Unhandled exception

### ISSUE THREAD

**Issue by SpamReceiver** [nextcloud/server#23339]
Nextcloud 19.0.3 upgraded to 19.0.4.
on  Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-48-generic x86_64)
with Apache2  2.4.41-4ubuntu3.1
with PHP 7.4.3
with mariadb-server 1:10.3.22-1ubuntu1

Started upgrade via web interface, then switched to command line.
Exception thrown, see below.

```
root@server:/# sudo -u www-data php /mnt/data/var/www/nextcloud/occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled incompatible app: bookmarks_fulltextsearch
Cleanup ocr app data folder.

 Starting ...
 0/1 [>---------------------------]   0%An unhandled exception has been thrown:
TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::advance() must be of the type int, string given, called in /mnt/data/var/www/nextcloud/core/Command/Upgrade.php on line 144 and defined in /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:310
Stack trace:
#0 /mnt/data/var/www/nextcloud/core/Command/Upgrade.php(144): Symfony\Component\Console\Helper\ProgressBar->advance()
#1 /mnt/data/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}()
#2 /mnt/data/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#3 /mnt/data/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#4 /mnt/data/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#5 /mnt/data/var/www/nextcloud/lib/private/Repair.php(201): OC\EventDispatcher\SymfonyAdapter->dispatch()
#6 /mnt/data/var/www/nextcloud/lib/private/Repair.php(232): OC\Repair->emit()
#7 /mnt/data/var/www/nextcloud/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance()
#8 /mnt/data/var/www/nextcloud/lib/private/Repair.php(103): OCA\Ocr\Migration\CleanupTessdata->run()
#9 /mnt/data/var/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\Repair->run()
#10 /mnt/data/var/www/nextcloud/lib/private/App/AppManager.php(412): OC_App::executeRepairSteps()
#11 /mnt/data/var/www/nextcloud/lib/private/Updater.php(410): OC\App\AppManager->disableApp()
#12 /mnt/data/var/www/nextcloud/lib/private/Updater.php(253): OC\Updater->checkAppsRequirements()
#13 /mnt/data/var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#14 /mnt/data/var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#15 /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#16 /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#17 /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#18 /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#19 /mnt/data/var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#20 /mnt/data/var/www/nextcloud/console.php(100): OC\Console\Application->run()
#21 /mnt/data/var/www/nextcloud/occ(11): require_once('/mnt/data/var/w...')
```

**Comment by acsfer** [comment]
See if this helps (follow the links). https://github.com/janis91/ocr/issues/281
