### ISSUE TITLE
occ flies:scan error 

### ISSUE THREAD

**Issue by TorinKR** [nextcloud/server#23540]
one of the servers scans itself, and for one of the users the scan crashes such errors

Where to find a solution ??
looks like it crashes when you start scanning group folders?
for other users I don't have this problem?
Nextcloud 19.0.4
ubuntu 20.04
php7.4
10.3.22-MariaDB

```
        Folder	/xxx.xxx/files_trashbin/keys
	Folder	/xxx.xxx/files_trashbin/versions
	Folder	/xxx.xxx/uploads
Exception during scan: 
#0 [internal function]: OCA\Files_Sharing\External\Storage->checkStorageAvailability()
#1 /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(507): call_user_func_array()
#2 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call()
#3 /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(507): call_user_func_array()
#4 /var/www/html/nextcloud/apps/files_sharing/lib/External/Scanner.php(90): OC\Files\Storage\Wrapper\Wrapper->__call()
#5 /var/www/html/nextcloud/apps/files_sharing/lib/External/Scanner.php(45): OCA\Files_Sharing\External\Scanner->scanAll()
#6 /var/www/html/nextcloud/lib/private/Files/Utils/Scanner.php(260): OCA\Files_Sharing\External\Scanner->scan()
#7 /var/www/html/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan()
#8 /var/www/html/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles()
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#10 /var/www/html/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run()
#12 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#14 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#15 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#16 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#17 {main}

```

**Comment by szaimen** [comment]
Hi there, for scanning groupfolders please use
`occ groupfolders:scan <folder_id>`
ref https://github.com/nextcloud/groupfolders#command-line-configuration-via-occ
Thanks!
