### ISSUE TITLE
Preview generation creates error message

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2364]
If I share the welcome.txt as public link and open the public link I get this error message in the log (but the preview is shown correctly):

````
{"reqId":"ia2n3Ah4mR14YuVtDjB1","remoteAddr":"::1","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"core_ajax_public_preview\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('core_ajax_publi...', Array, 1)\\n#1 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('core_ajax_publi...', Array)\\n#2 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/URLGenerator.php(83): OC\\\\URLGenerator->linkToRoute('core_ajax_publi...', Array)\\n#3 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(374): OC\\\\URLGenerator->linkToRouteAbsolute('core_ajax_publi...', Array)\\n#4 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->showShare('lzkF5FDdcyE9YqW', '')\\n#5 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#7 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#8 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'showShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#9 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/routes.php(88): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'showShare')\\n#10 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#11 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#12 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/lzkF5FDdcyE9...')\\n#13 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2016-11-28T10:11:42+00:00","method":"GET","url":"\/master\/index.php\/s\/lzkF5FDdcyE9YqW","user":"--","version":"11.0.0.4"}
{"reqId":"ia2n3Ah4mR14YuVtDjB1","remoteAddr":"::1","app":"PHP","message":"Uninitialized string offset: 0 at \/home\/schiesbn\/repos\/nextcloud\/server\/master\/lib\/private\/URLGenerator.php#217","level":3,"time":"2016-11-28T10:11:42+00:00","method":"GET","url":"\/master\/index.php\/s\/lzkF5FDdcyE9YqW","user":"--","version":"11.0.0.4"}
````

@rullzer any idea? Does it has something to do with your preview rework?

**Comment by nickvergessen** [comment]
The old route was removed

**Comment by LukasReschke** [comment]
Patch at https://github.com/nextcloud/server/pull/2378
