### ISSUE TITLE
Return value of OC\Http\Client\Client::getCertBundle() must be of the type string, bool returned

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#23664]
- Nextcloud 19.0.4
- PHP 7.4.11

On the CLI: `sudo -u www-data php occ app:enable spreed`

Some time after issued the command:

```
An unhandled exception has been thrown:
TypeError: Return value of OC\Http\Client\Client::getCertBundle() must be of the type string, bool returned in lib/private/Http/Client/Client.php:104
Stack trace:
#0 lib/private/Http/Client/Client.php(75): OC\Http\Client\Client->getCertBundle()
#1 lib/private/Http/Client/Client.php(228): OC\Http\Client\Client->buildRequestOptions()
#2 lib/private/App/AppStore/Fetcher/Fetcher.php(109): OC\Http\Client\Client->get()
#3 lib/private/App/AppStore/Fetcher/AppFetcher.php(86): OC\App\AppStore\Fetcher\Fetcher->fetch()
#4 lib/private/App/AppStore/Fetcher/Fetcher.php(173): OC\App\AppStore\Fetcher\AppFetcher->fetch()
#5 lib/private/Installer.php(221): OC\App\AppStore\Fetcher\Fetcher->get()
#6 core/Command/App/Enable.php(119): OC\Installer->downloadApp()
#7 core/Command/App/Enable.php(92): OC\Core\Command\App\Enable->enableApp()
#8 3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#9 3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#10 3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#11 3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#12 lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#13 console.php(100): OC\Console\Application->run()
#14 occ(11): require_once('/var/www/vhosts...')
#15 {main}
```

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
