### ISSUE TITLE
DAV: Unable to put an .ics file to a shared calendar (calendar v1.4.1)

### ISSUE THREAD

**Issue by raoulbhatia** [nextcloud/server#2402]
_(This is also tracked for DAVDroid via https://forums.bitfire.at/topic/1261/updating-existing-uploading-new-record-exception-at-bitfire-dav4android-exception-notfoundexception-404)_
_(This is also tracked as a closed issue at nextcloud/calendar#206 )_

Hi!

I've recently updated calendar 1.4.0 to 1.4.1 and owncloud from 9.1.1 to 9.1.2

Since then, I am unable to create/update events in a shared calendar via Android & DAVDROID:
```
HTTP RESPONSE:
h2 404 
cache-control: no-store, no-cache, must-revalidate
content-security-policy: default-src 'none';
content-type: application/xml; charset=utf-8
date: Mon, 28 Nov 2016 21:29:36 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: nginx
set-cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: 51deba942f2c9=8ua4avovasdkmmhncfj2d6eu72; path=/; secure; HttpOnly
x-sabre-version: 3.0.9

<?xml version="1.0" encoding="utf-8"?>[LF]
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]
  <s:sabredav-version>3.0.9</s:sabredav-version>[LF]
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>[LF]
  <s:message>Principal with name users not found</s:message>[LF]
</d:error>[LF]
```

The only way I found to resolve this re-curring 404 error is to delete the added/modified event on Android - so to get rid if the scheduled upload - and re-add it via the owncloud web interface.

This used to work until the update to calendar 1.4.1 and owncloud 9.1.2.

Happy to provide more information to get this resolved.

Thanks,
Raoul

**Comment by raoulbhatia** [comment]
Maybe this is only affecting owncloud and should not be tracked here.

The owncloud reference ist owncloud/core#26667

**Comment by nickvergessen** [comment]
> owncloud from 9.1.1 to 9.1.2

In order to get help from us, you need to migrate to Nextcloud.

**Comment by nickvergessen** [comment]
Tested on Nextcloud 11 beta2 ✅ 
Tested on Nextcloud 10.0.2-alpha ✅

**Comment by LukasReschke** [comment]
Closing as it doesn't seem reproducible on Nextcloud.

**Comment by gjedeer** [comment]
It's happening to me on NC 11.0.2.7 and DavDroid.

```
{"reqId":"HH8NZZDR5mVAp2iXUhQl","remoteAddr":"1.1.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Node with name 'd7c6c02a-891b-438f-bcd1-6dd0d3a29de9.vcf' could not be found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(898): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\DavAclPlugin->checkPrivileges('addressbooks\\\/us...', '{DAV:}write-con...')\\n#1 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/remote.php(165): require_once('\\\/var\\\/www\\\/apps\\\/d...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/DavAclPlugin.php\",\"Line\":65,\"User\":\"USER\"}","level":0,"time":"2017-05-22T20:23:04+00:00","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/USER\/default_shared_by_OTHERUSER\/d7c6c02a-891b-438f-bcd1-6dd0d3a29de9.vcf","user":"USER","version":"11.0.2.7"}
```

I verified that the contact with UUID d7c6c02a-891b-438f-bcd1-6dd0d3a29de9 exists.
