### ISSUE TITLE
Uploading lots of files creates undelete-able files

### ISSUE THREAD

**Issue by cyphar** [nextcloud/server#2429]
### Steps to reproduce
1. Upload ~1GB of small image files.
2. Select all of the uploaded files and try to delete them.

### Expected behaviour
All of the files are uploaded, and then they're all successfully deleted.

### Actual behaviour
Some of the file uploads fail with SQL query errors, and attempting to delete some files doesn't work. The files show as having been "deleted" in the history but they still exist in `/var/www/htdocs/data/cyphar/files/...`.

### Server configuration
**Operating system**:
openSUSE Leap 42.1, with NextCloud running in my fork of the [official Docker images](https://github.com/nextcloud/docker).

**Web server:**
Apache.

**Database:**
```
PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
```

**PHP version:**
```
Version: 5.6.28
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513.0 MB
```

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install.

**Where did you install Nextcloud from:**
Docker image (as mentioned above).

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "instanceid": "ochw2p9nstin",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "192.168.0.222",
            "cloud.cyphar.com"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "https:\/\/cloud.cyphar.com",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.cyphar.com",
        "dbtype": "pgsql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "nextcloud-db",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "owncloud",
        "mail_domain": "cyphar.com",
        "loglevel": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium

**Operating system:** openSUSE Tumbleweed

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

When I try to delete something this gets echo'd in the log:
```
Exception: {"Message":"HTTP\/1.1 423 \"Photos\/Old\" is locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OCA\\DAV\\Connector\\Sabre\\Directory->delete()\n#1 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(285): Sabre\\DAV\\Tree->delete('Photos\/Old')\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#5 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/html\/remote.php(165): require_once('\/var\/www\/html\/a...')\n#8 {main}","File":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","Line":284,"User":"cyphar"}
```

And when I try to upload the files I get errors like this:
```
{"reqId":"cjcA5OTOxDikiiAXlgga","remoteAddr":"172.17.0.1","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT \\\"fileid\\\", \\\"storage\\\", \\\"path\\\", \\\"parent\\\", \\\"name\\\", \\\"mimetype\\\", \\\"mimepart\\\", \\\"size\\\", \\\"mtime\\\",\\n\\t\\t\\t\\t\\t   \\\"storage_mtime\\\", \\\"encrypted\\\", \\\"etag\\\", \\\"permissions\\\", \\\"checksum\\\"\\n\\t\\t\\t\\tFROM \\\"oc_filecache\\\" WHERE \\\"storage\\\" = ? AND \\\"path_hash\\\" = ?' with params [3, \\\"1161e4533e6a9b2922fd88ea8e26d749\\\"]:\\n\\nSQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"fileid\\\"...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/Connection.php(189): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT \\\"fileid\\\"...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(129): OC\\\\DB\\\\Connection->executeQuery('SELECT `fileid`...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/HomeCache.php(76): OC\\\\Files\\\\Cache\\\\Cache->get('files\\\/Photos\\\/Im...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1285): OC\\\\Files\\\\Cache\\\\HomeCache->get('files\\\/Photos\\\/Im...')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1338): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/Photos\\\/Im...', '\\\/Photos\\\/Import\\\/...')\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Node.php(92): OC\\\\Files\\\\View->getFileInfo('\\\/Photos\\\/Import\\\/...')\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(218): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Node->refreshInfo()\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #80)\\n#10 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_2008.JPG', Resource id #80)\\n#11 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('files\\\/cyphar\\\/Ph...', Resource id #80, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(184): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91,\"User\":\"cyphar\"}","level":4,"time":"2016-11-30T16:25:15+00:00","method":"PUT","url":"\/remote.php\/dav\/files\/cyphar\/Photos\/Import\/IMG_2008.JPG","user":"cyphar"} 
```

And then when I try to upload a file to the same path that it previously failed to upload to:

```
Exception: {"Message":"HTTP\/1.1 423 \"Photos\/Import\/IMG_20160611_190720.jpg\" is locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1070): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #80)\n#1 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(511): Sabre\\DAV\\Server->updateFile('files\/cyphar\/Ph...', Resource id #80, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#8 \/var\/www\/html\/remote.php(165): require_once('\/var\/www\/html\/a...')\n#9 {main}","File":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":175,"User":"cyphar"}
```
</details>

**Comment by cyphar** [comment]
After restarting the server a few times, it becomes possible to delete the files. However, the failure-to-upload still continues for the same files (with the same error as before).

**Comment by cyphar** [comment]
Here's what the activity log looks like for the undelete-able directory.

<details>
![undeletable](http://i.imgur.com/jl6wEju.png)
</details>

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by cyphar** [comment]
Alright I figured out that `php occ files:scan cyphar` appears to fix the issue. Though I noticed that after a few server reboots the files disappeared by themselves. I ended up resorting to deleting the files from `data` and then manually doing a `files:scan`.

**Comment by LollenJumplan** [comment]
Is this still reproducible in a recent version of NC? Version 10 has been EOL for a while, and I remember having some file locking problems myself that have gone away in the 12-13ish range.

**Comment by cyphar** [comment]
I have not seen this in quite a while (though I did still see it in `11.x`), and upgraded a while ago. So I'll close this and it can be re-opened if someone else hits it.
