### ISSUE TITLE
Error: ArgumentCountError: Too few arguments to function OCP\Files\ForbiddenException

### ISSUE THREAD

**Issue by colttt** [nextcloud/server#24372]
### Steps to reproduce
1. sorry but I don't know how this happen, I just saw this Error in the nextcloud-error logfile
2.
3.

### Server configuration

**Operating system:** Debian 10 (buster)

**Web server:** Apache 2.4.38

**Database:** mariadb 10.3.25

**PHP version:** 7.3.19

**Nextcloud version:** 19.0.5 Enterprise

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** updater.phar

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.2
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.1.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - globalsiteselector
  - impersonate
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "194.94.xxx.xxx",
            "wolke7.example.de",
            "cloud7.example.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "19.0.5.3",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "en",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "enable_avatars": true,
        "allow_user_to_change_display_name": false,
        "remember_login_cookie_lifetime": 604800,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/skeleton",
        "lost_password_link": "https:\/\/ucs.example.de\/",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpdebug": false,
        "mail_smtptimeout": 10,
        "overwritehost": "",
        "overwriteprotocol": "https",
        "overwritewebroot": "",
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto, 30",
        "appcodechecker": true,
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/customers\/YTPIB-TUOZM-DVIYQ-IGQRA-QU5YE\/",
        "updater.release.channel": "enterprise",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/apache2\/nextcloud_app.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "cron_log": true,
        "log_rotate_size": false,
        "customclient_desktop": "https:\/\/nextcloud.com\/install\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "ldapUserCleanupInterval": 51,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "tempdirectory": "\/nfs_nc_storage\/tmp_nextcloud",
        "hashingCost": 10,
        "blacklisted_files": [
            ".htaccess"
        ],
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "1.7.0",
        "filesystem_check_changes": 0,
        "part_file_in_storage": true,
        "mount_file": "\/var\/www\/nextcloud\/data\/mount.json",
        "filesystem_cache_readonly": false,
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "max_filesize_animated_gifs_public_sharing": 5,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "upgrade.disable-web": false,
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": "https:\/\/wolke7.example.de",
        "mail_smtpauthtype": "LOGIN",
        "activity_expire_days": 30,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Wed Nov 25 10:52:27.289848 2020] [access_compat:error] [pid 15121] [client 62.157.66.109:54208] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 10:57:46.051478 2020] [php7:error] [pid 17019] [client 130.75.117.49:62111] PHP Fatal error:  Uncaught PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1054): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/nextcloud/lib/private/DB/Connection.php(214): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(203): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(216): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /var/www/nextcloud/lib/private/Lock/DBLockingProvider.php(316): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 [internal  in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 34
[Wed Nov 25 10:58:02.513839 2020] [php7:error] [pid 17280] [client 130.75.117.49:62116] PHP Fatal error:  Uncaught PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1054): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/nextcloud/lib/private/DB/Connection.php(214): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(203): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(216): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /var/www/nextcloud/lib/private/Lock/DBLockingProvider.php(316): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 [internal  in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 34
[Wed Nov 25 11:00:57.672686 2020] [access_compat:error] [pid 16727] [client 178.12.225.105:62676] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:02:03.957984 2020] [access_compat:error] [pid 18404] [client 95.90.243.36:65155] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:10:06.462755 2020] [access_compat:error] [pid 20442] [client 95.90.202.208:41219] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:22:04.076984 2020] [access_compat:error] [pid 21772] [client 95.90.240.1:25214] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:23:32.898917 2020] [access_compat:error] [pid 23676] [client 130.75.117.49:51521] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:26:29.653404 2020] [access_compat:error] [pid 24318] [client 172.18.1.191:52623] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:31:56.204526 2020] [access_compat:error] [pid 25410] [client 62.157.66.109:55699] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:39:08.565666 2020] [access_compat:error] [pid 26292] [client 172.16.31.254:62507] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:41:17.157723 2020] [access_compat:error] [pid 27988] [client 88.130.48.147:11023] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:41:31.838510 2020] [access_compat:error] [pid 26846] [client 172.16.22.63:52554] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:45:10.434542 2020] [access_compat:error] [pid 28935] [client 47.65.232.28:57061] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:46:36.550225 2020] [access_compat:error] [pid 29634] [client 128.0.147.16:37828] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:53:41.967073 2020] [access_compat:error] [pid 30624] [client 87.123.192.185:33811] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 11:59:02.980042 2020] [access_compat:error] [pid 32532] [client 95.90.243.36:65164] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:05:17.354151 2020] [access_compat:error] [pid 1247] [client 89.182.232.154:20417] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:07:39.281457 2020] [access_compat:error] [pid 2086] [client 84.129.97.178:65342] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:11:07.382542 2020] [access_compat:error] [pid 3191] [client 172.18.2.227:36658] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:30:10.751461 2020] [access_compat:error] [pid 7159] [client 93.242.6.146:49689] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:38:35.361475 2020] [access_compat:error] [pid 8916] [client 84.173.52.212:57426] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:42:59.739502 2020] [access_compat:error] [pid 10507] [client 84.167.181.200:34520] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:45:17.270352 2020] [access_compat:error] [pid 11491] [client 95.90.240.1:25175] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:47:07.366719 2020] [access_compat:error] [pid 11855] [client 84.173.52.212:57572] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:48:28.271113 2020] [access_compat:error] [pid 12590] [client 176.95.216.117:50607] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:51:00.297068 2020] [access_compat:error] [pid 13069] [client 194.94.98.189:52187] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:51:24.319361 2020] [access_compat:error] [pid 12850] [client 84.173.52.212:57658] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:53:14.706294 2020] [access_compat:error] [pid 13556] [client 87.149.66.112:55824] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 12:54:05.746018 2020] [access_compat:error] [pid 14206] [client 95.90.240.1:25185] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Wed Nov 25 13:04:11.400226 2020] [access_compat:error] [pid 16141] [client 84.173.52.212:57864] AH01797: client denied by server configuration: /var/www/nextcloud/config

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[core] Error: ArgumentCountError: Too few arguments to function OCP\Files\ForbiddenException::__construct(), 1 passed in /var/www/nextcloud/lib/private/Files/Storage/DAV.php on line 861 and at least 2 expected at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 861
    OCP\Files\ForbiddenException->__construct("Sabre\\HTTP\\Cl ... n")
 1. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 289
    OC\Files\Storage\DAV->convertException(Sabre\HTTP\ClientHttpException {}, "")
 2. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 587
    OC\Files\Storage\DAV->propfind("")
 3. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 459
    OC\Files\Storage\DAV->stat("")
 4. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 473
    OC\Files\Storage\Common->test()
 5. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 70
    OC\Files\Storage\Wrapper\Wrapper->test()
 6. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 84
    OC\Files\Storage\Wrapper\Availability->updateAvailability("*** sensitive parameters replaced ***")
 7. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 93
    OC\Files\Storage\Wrapper\Availability->isAvailable()
 8. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 442
    OC\Files\Storage\Wrapper\Availability->checkAvailability()
 9. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 583
    OC\Files\Storage\Wrapper\Availability->getMetaData("")
10. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 114
    OC\Files\Storage\Wrapper\Wrapper->getMetaData("")
11. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 152
    OC\Files\Cache\Scanner->getData("")
12. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 338
    OC\Files\Cache\Scanner->scanFile("", 1, -1, null, true)
13. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 500
    OC\Files\Cache\Scanner->scan("", true, 1)
14. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 517
    OC\Files\Cache\Scanner->OC\Files\Cache\{closure}("*** sensitive parameters replaced ***")
15. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 501
    OC\Files\Cache\Scanner->runBackgroundScanJob(Closure {}, "")
16. /var/www/nextcloud/lib/private/Files/Utils/Scanner.php line 186
    OC\Files\Cache\Scanner->backgroundScan()
17. /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 83
    OC\Files\Utils\Scanner->backgroundScan("")
18. /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 111
    OCA\Files\BackgroundJob\ScanFiles->runScanner(OC\User\User {})
19. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 62
    OCA\Files\BackgroundJob\ScanFiles->run(null)
20. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 57
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
21. /var/www/nextcloud/cron.php line 126
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-11-25T12:46:37+01:00
```
</details>

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/server/pull/21589 for Nextcloud 21.
