### ISSUE TITLE
lib/private/Log.php#318 Class 'OC\Log\ExceptionSerializer' not found

### ISSUE THREAD

**Issue by GieltjE** [nextcloud/server#24558]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload a large file that will exceed the php timeout

### Expected behaviour
Probably should find the class?

### Actual behaviour
Exceptions about a missing class

### Server configuration
Operating system: Gentoo
Web server: Apache 2.4.46
Database: Mariadb 10.5.8
PHP version: 7.4.13
Nextcloud version: 20.0.2
Updated from an older Nextcloud/ownCloud or fresh install: Updated from OC a long time ago.
Where did you install Nextcloud from: tarball from the nextcloud.com site
Signing status: No errors have been found.
List of activated apps: 
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - bookmarks: 4.0.5
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - deck: 1.2.2
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.1
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_detection: 0.9.0
  - ransomware_protection: 1.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.3
  - support: 1.3.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
```
Nextcloud configuration:
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - bookmarks: 4.0.5
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - deck: 1.2.2
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.1
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_detection: 0.9.0
  - ransomware_protection: 1.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.3
  - support: 1.3.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - checksum
  - encryption
  - end_to_end_encryption
  - external
  - files_retention
  - files_snapshots
  - onlyoffice
  - quicknotes
  - recommendations
  - survey_client
  - user_ldap
beast /var/www/nextcloud # sudo -u apache php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "thuis.hazelhof.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/thuis.hazelhof.nl:224\/",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Amsterdam",
        "installed": true,
        "maintenance": false,
        "loglevel": 3,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "616",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "appstore.experimental.enabled": true,
        "theme": "",
        "trashbin_retention_obligation": "5, 20",
        "versions_retention_obligation": "20, 30",
        "activity_expire_days": 365,
        "appcodechecker": true,
        "updater.release.channel": "stable",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redimemcache.distributed": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5,
            "dbindex": 1
        },
        "app_install_overwrite": [
            "contacts",
            "ransomware_detection"
        ],
        "onlyoffice": {
            "verify_peer_off": true,
            "jwt_secret": "testtest",
            "jwt_header": "Authorization"
        },
        "allow_local_remote_servers": true
    }
}
```
Are you using external storage, if yes which one: none
Are you using encryption: no
Are you using an external user-backend, if yes which one: no

### Client configuration
Browser: None, desktop client 3.0.3
Operating system: Win 10 X64 20H2

#### Web server error log
```
[Fri Dec 04 14:16:18.339830 2020] [proxy_fcgi:error] [pid 6240:tid 140059504252480] [client 84.105.68.208:65395] AH01071: Got error 'PHP message: PHP Warning:  spl_autoload(): open_basedir restriction in effect. File(oc/log/exceptionserializer.inc) is not within the allowed path(s): (/var/www/nextcloud:/tmp:/mnt/storage/temp:/mnt/storage/data:/dev/urandom:/mnt/storage/backup/) in /var/www/nextcloud/lib/private/Log.php on line 318PHP message: PHP Warning:  spl_autoload(): open_basedir restriction in effect. File(oc/log/exceptionserializer.php) is not within the allowed path(s): (/var/www/nextcloud:/tmp:/mnt/storage/temp:/mnt/storage/data:/dev/urandom:/mnt/storage/backup/) in /var/www/nextcloud/lib/private/Log.php on line 318PHP message: PHP Fatal error:  Uncaught Error: Class 'OC\\Log\\ExceptionSerializer' not found in /var/www/nextcloud/lib/private/Log.php:318\nStack trace:\n#0 /var/www/nextcloud/lib/private/Log/ErrorHandler.php(92): OC\\Log->logException(Object(Error), Array)\n#1 [internal function]: OC\\Log\\ErrorHandler::onError(2, 'Cannot modify h...', '/var/www/nextcl...', 691, Array)\n#2 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php(691): header('X-Hash-SHA256: ...')\n#3 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php(195): OCA\\DAV\\Connector\\Sabre\\File->header('X-Hash-SHA256: ...')\n#4 [internal function]: OCA\\DAV\\Connector\\Sabre\\File->OCA\\DAV\\Connector\\Sabre\\{closure}('1b3e323637bec63...')\n#5 /var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php(71): call_user_func(Object(Closure), '1b3e323637bec63...')\n#6 [internal function]: OC\\Files\\Stream\\HashWrapper->stream_close()\n#7 {main}\n  thrown in /var/www/nextcloud/lib/private/Log.php on line 318'
```
#### Nextcloud log (data/nextcloud.log)
```
Uncaught Error: Class 'OC\Log\ExceptionSerializer' not found in /var/www/nextcloud/lib/private/Log.php:318 Stack trace: #0 /var/www/nextcloud/lib/private/Log/ErrorHandler.php(92): OC\Log->logException(Object(Error), Array) #1 [internal function]: OC\Log\ErrorHandler::onError(2, 'Cannot modify h...', '/var/www/nextcl...', 691, Array) #2 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php(691): header('X-Hash-SHA256: ...') #3 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php(195): OCA\DAV\Connector\Sabre\File->header('X-Hash-SHA256: ...') #4 [internal function]: OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}('3312561ebdb9ccf...') #5 /var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php(71): call_user_func(Object(Closure), '3312561ebdb9ccf...') #6 [internal function]: OC\Files\Stream\HashWrapper->stream_close() #7 {main} thrown at /var/www/nextcloud/lib/private/Log.php#318
```

**Comment by kesselb** [comment]
The file is there https://github.com/nextcloud/server/blob/v20.0.2/lib/private/Log/ExceptionSerializer.php and also in https://download.nextcloud.com/server/releases/nextcloud-20.0.2.zip.

**Comment by GieltjE** [comment]
Yes, it's on my instance, in the exact correct spot too.

**Comment by chrissi55** [comment]
Same here
Error says :

Error | PHP | include():  Failed opening  '/var/www/nextcloud/lib/composer/composer/../../../lib/private/Log/ExceptionSerializer.php'  for inclusion  (include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps')  at /var/www/nextcloud/lib/composer/composer/ClassLoader.php#444
-- | -- | --


<a href="https://www.bilder-upload.eu/bild-f2786a-1608457691.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/f2786a-1608457691.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

<a href="https://www.bilder-upload.eu/bild-03816c-1608457729.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/03816c-1608457729.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

<a href="https://www.bilder-upload.eu/bild-03816c-1608457729.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/03816c-1608457729.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by PhieF** [comment]
same here

**Comment by GieltjE** [comment]
!stale, really starting to dislike all these bots

**Comment by TomasTomecek** [comment]
I am having the same issue when running nextcloud from the official container image:

nextcloud:19-fpm
Image: sha256:f1fd40c9d43fafa623b1a962f8568375d03b893af0d35aca38e9f2de361da161

```
<b>Fatal error</b>:  Uncaught Error: Class 'InterfaSys\LogNormalizer\Normalizer' not found in /var/www/html/lib/private/Log.php:90
Stack trace:
#0 /var/www/html/lib/private/Server.php(720): OC\Log-&gt;__construct(Object(OC\Log\File), Object(OC\SystemConfig), NULL, Object(OC\Support\CrashReport\Registry))
#1 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server-&gt;OC\{closure}(Object(OC\Server))
#2 /var/www/html/lib/private/ServerContainer.php(124): Pimple\Container-&gt;offsetGet('OC\\Log')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer-&gt;query('OC\\Log')
#4 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer-&gt;OC\AppFramework\Utility\{closure}(Object(OC\Server))
#5 /var/www/html/lib/private/ServerContainer.php(124): Pimple\Container-&gt;offsetGet('OCP\\ILogger')
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(71): OC\ServerContainer-&gt;query('OCP\\ILogger', true)
#7 /var/www/html/lib/private/AppFr in <b>/var/www/html/lib/private/Log.php</b> on line <b>90</b><br />
```

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.2?

**Comment by Hecke29** [comment]
Not stale

**Comment by kesselb** [comment]
Could be fixed by https://github.com/nextcloud/server/pull/28907

**Comment by tobiasKaminsky** [comment]
I have this on latest master since ~1 week, while I do this:
```
curl -v --request HEAD \
  --url http://localhost/nc/remote.php/dav \
  --header 'OCS-APIRequest: true'
```

This is Android's way to check for Nextcloud server and it is expected that server returns 401 Unauthorized.
But now I get:
```{
  "reqId": "GFrHu1umvx2ruP57Lhcs",
  "level": 3,
  "time": "2022-02-08T07:17:52+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "--",
  "app": "remote",
  "method": "HEAD",
  "url": "/nc/remote.php/dav",
  "message": "Class \"OC\\Log\\ExceptionSerializer\" not found",
  "userAgent": "curl/7.81.0",
  "version": "24.0.0.4",
  "exception": {
    "Exception": "Error",
    "Message": "Class \"OC\\Log\\ExceptionSerializer\" not found",
    "Code": 0,
    "Trace": [
      {
        "file": "/srv/http/nc/lib/private/Log/ErrorHandler.php",
        "line": 100,
        "function": "logException",
        "class": "OC\\Log",
        "type": "->",
        "args": [
          {
            "__class__": "Error"
          },
          {
            "app": "PHP",
            "level": 3
          }
        ]
      },
      {
        "file": "/srv/http/nc/lib/composer/composer/ClassLoader.php",
        "line": 571,
        "function": "onAll",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::",
        "args": [
          8192,
          "Return type of OCA\\Deck\\Db\\RelationalEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice",
          "/srv/http/nc/apps/deck/lib/Db/RelationalEntity.php",
          66
        ]
      },
      {
        "file": "/srv/http/nc/lib/composer/composer/ClassLoader.php",
        "line": 571,
        "args": [
          "/srv/http/nc/lib/private/Log/ErrorHandler.php"
        ],
        "function": "include"
      },
      {
        "file": "/srv/http/nc/lib/composer/composer/ClassLoader.php",
        "line": 428,
        "function": "Composer\\Autoload\\includeFile",
        "args": [
          "/srv/http/nc/lib/composer/composer/../../../lib/private/Log/ExceptionSerializer.php"
        ]
      },
      {
        "file": "/srv/http/nc/lib/private/Log.php",
        "line": 311,
        "function": "loadClass",
        "class": "Composer\\Autoload\\ClassLoader",
        "type": "->",
        "args": [
          "OC\\Log\\ExceptionSerializer"
        ]
      },
      {
        "file": "/srv/http/nc/apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php",
        "line": 134,
        "function": "logException",
        "class": "OC\\Log",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\DAV\\Exception\\NotAuthenticated"
          },
          {
            "app": "webdav",
            "level": 0
          }
        ]
      },
      {
        "file": "/srv/http/nc/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "logException",
        "class": "OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\DAV\\Exception\\NotAuthenticated"
          }
        ]
      },
      {
        "file": "/srv/http/nc/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 256,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "exception",
          [
            {
              "__class__": "Sabre\\DAV\\Exception\\NotAuthenticated"
            }
          ]
        ]
      },
      {
        "file": "/srv/http/nc/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/srv/http/nc/apps/dav/lib/Server.php",
        "line": 341,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/srv/http/nc/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/srv/http/nc/remote.php",
        "line": 166,
        "args": [
          "/srv/http/nc/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/srv/http/nc/lib/private/Log.php",
    "Line": 311,
    "CustomMessage": "--"
  }
}
```

**Comment by tobiasKaminsky** [comment]
@juliushaertl this seems to be a problem on latest text/deck app. When I disable them, it directly works:
```
"file": "/srv/http/nc/lib/composer/composer/ClassLoader.php",
        "line": 571,
        "function": "onAll",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::",
        "args": [
          8192,
          "Return type of OCA\\Deck\\Db\\RelationalEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice",
          "/srv/http/nc/apps/deck/lib/Db/RelationalEntity.php",
          66
        ]
      },
```

**Comment by juliushaertl** [comment]
@tobiasKaminsky Are you running PHP 8.1? That could explain the error reporting there. I moved this case to https://github.com/nextcloud/office/issues/6

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Are you running PHP 8.1? That could explain the error reporting there. I moved this case to [nextcloud/office#6](https://github.com/nextcloud/office/issues/6)

Yes, 8.1.2, I use Arch btw.

**Comment by andyxheli** [comment]
Same on NC 23.0.4 PHP 8.0

<html>
<body>


{"reqId":"gyBWoZL3LKyEEytiInNs","level":3,"time":"2022-04-21T18:52:33+00:00","remoteAddr":"1.1.1.1","user":"admin","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/axheli/2047109539/0000000000000012","message":"Error: Class \"OC\\Log\\ExceptionSerializer\" not found at /var/www/nextcloud/lib/private/Log.php#311","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.4.83git (build 9900) (Nextcloud, osx-21.4.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"23.0.3.2","id":"6261a858ecc7e"}

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
