### ISSUE TITLE
[21.0.0 beta 1] OCC too few arguments

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#24680]
Just installed beta 1 and tried to follow instructions on https://DOMAIN/settings/admin/overview concerning missing indices and bigint conversion – but I cannot call occ AT ALL:

$ php occ 
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Analytics\Command\Load::__construct(), 0 passed in /PATH/lib/private/Console/Application.php on line 224 and exactly 1 expected in /PATH/apps/analytics/lib/Command/Load.php:25
Stack trace:
#0 /PATH/lib/private/Console/Application.php(224): OCA\Analytics\Command\Load->__construct()
#1 /PATH/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml()
#2 /PATH/console.php(99): OC\Console\Application->loadCommands()
#3 /PATH/occ(11): require_once('/PATH...')

**Comment by acsfer** [comment]
Try disable analytics app first trough the web?

**Comment by Rello** [comment]
thank you. I will check

**Comment by nursoda** [comment]
Thanks, Analytics 3.2.0 solves the issue.

**Comment by Rello** [comment]
yes.
sorry for the delay
