### ISSUE TITLE
occ db:convert-filecache-bigint returns undefined method exception

### ISSUE THREAD

**Issue by jkroepke** [nextcloud/server#24724]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. `occ db:convert-filecache-bigint`
2.
3.

### Expected behaviour
Migration successfull

### Actual behaviour
```
Following columns will be updated:

* federated_reshares.share_id
* filecache_extended.fileid
* share_external.id
* share_external.parent

This can take up to hours, depending on the number of files in your instance!
Continue with the conversion (y/n)? [n] An unhandled exception has been thrown:
Error: Call to undefined method Symfony\Component\Console\Question\ConfirmationQuestion::getAutocompleterCallback() in /var/www/htdocs/3rdparty/symfony/console/Helper/QuestionHelper.php:108
Stack trace:
#0 /var/www/htdocs/3rdparty/symfony/console/Helper/QuestionHelper.php(61): Symfony\Component\Console\Helper\QuestionHelper->doAsk()
#1 /var/www/htdocs/core/Command/Db/ConvertFilecacheBigInt.php(120): Symfony\Component\Console\Helper\QuestionHelper->ask()
#2 /var/www/htdocs/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Db\ConvertFilecacheBigInt->execute()
#3 /var/www/htdocs/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#4 /var/www/htdocs/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/htdocs/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#6 /var/www/htdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#7 /var/www/htdocs/console.php(100): OC\Console\Application->run()
#8 /var/www/htdocs/occ(11): require_once('/var/www/ownclo...')
```

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** nginx

**Database:** MySQL 8

**PHP version:**  7.4.3

**Nextcloud version:** (see Nextcloud admin page) 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated instance via updater `/usr/bin/php /var/www/htdocs/updater/updater.phar`

**Where did you install Nextcloud from:** by tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - audioplayer: 3.0.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_external_gdrive: 0.4.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - groupfolders: 8.2.0
  - guests: 1.6.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - photos: 1.2.1
  - previewgenerator: 3.0.1
  - provisioning_api: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - comments
  - dashboard
  - encryption
  - firstrunwizard
  - nextcloud_announcements
  - password_policy
  - privacy
  - recommendations
  - serverinfo
  - support
  - survey_client
  - systemtags
  - text
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "version": "20.0.4.0",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "trusted_domains": [
            "owncloud.atu-clan.de",
            "owncloud.privneustadt.de",
            "owncloud.creativesandbox.de",
            "nc.jkroepke.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "enable_avatars": false,
        "skeletondirectory": "",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "proxy": "proxy:3128",
        "config_is_read_only": false,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 0,
        "log_rotate_size": 1048576,
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/",
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "30, 60",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "filelocking.enabled": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/owncloud.atu-clan.de",
        "upgrade.disable-web": false,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "quota_warning",
            "keeweb",
            "files_external_gdrive"
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Command Line Interface

**Operating system:** Ubuntu 20.04

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Running the command will not produce logs.
```
</details>

### Additional infos:

```
$ find . -iname 'ConfirmationQuestion*'
./apps/files_external_gdrive/vendor/symfony/console/Tests/Question/ConfirmationQuestionTest.php
./apps/files_external_gdrive/vendor/symfony/console/Question/ConfirmationQuestion.php
./updater/vendor/symfony/console/Question/ConfirmationQuestion.php
./3rdparty/symfony/console/Question/ConfirmationQuestion.php
```

The file `./3rdparty/symfony/console/Question/ConfirmationQuestion.php` exists and has content but no method `getAutocompleterCallback`.

**Comment by jkroepke** [comment]
After disable the `files_external_gdrive` app, everything works.

Looks like the order of include paths are not correct. `3rdparty` should preferred over `apps`?

**Comment by kesselb** [comment]
Must be fixed by files_external_gdrive. The app has https://github.com/NastuzziSamy/files_external_gdrive/blob/a87561ef872fcb684bda01f9117f2c37ead1b673/composer.json#L3 as dependency and pulls in symfony and flysystem another time. 

There are two ways to handle it. If the app author needs his own version (because a newer version of flysystem or symfony is required): https://help.nextcloud.com/t/escaping-the-dependency-hell/81407

If the versions shipped with Nextcloud are fine: https://github.com/nextcloud/news/pull/636

Both are hacks unfortunately. I'm not able to move this report to files_external_gdrive as the repository is not within the Nextcloud org on GitHub. You may report the issue at https://github.com/NastuzziSamy/files_external_gdrive and reference this report.
