### ISSUE TITLE
Updating Password App causing error - Nextcloud stuck in maintenance mode

### ISSUE THREAD

**Issue by paxxoid** [nextcloud/server#24945]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Attempted to update Password App from Web GUI as well as terminal/command line.
2. Error was encountered and Nextcloud is now stuck in maintenance mode.
3. Forcing Nextcloud out of maintenance mode only starts the update process via the web GUI

### Expected behaviour
App should be updated

### Actual behaviour
Terminal output
```

root@67fce579a797:/config/www/nextcloud# occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Updating <passwords> ...
An unhandled exception has been thrown:
ParseError: syntax error, unexpected 'ConfigurationService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /config/www/nextcloud/apps/passwords/lib/Migration/DatabaseObjectRepair.php:39
Stack trace:
#0 /config/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/config/www/nex...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\Passwords\\M...')
#2 [internal function]: spl_autoload_call('OCA\\Passwords\\M...')
#3 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(107): ReflectionClass->__construct('OCA\\Passwords\\M...')
#4 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Passwords\\M...')
#5 /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(455): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Passwords\\M...')
#6 /config/www/nextcloud/lib/private/ServerContainer.php(140): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Passwords\\M...')
#7 /config/www/nextcloud/lib/private/Repair.php(124): OC\ServerContainer->query('OCA\\Passwords\\M...')
#8 /config/www/nextcloud/lib/private/legacy/OC_App.php(1035): OC\Repair->addStep('OCA\\Passwords\\M...')
#9 /config/www/nextcloud/lib/private/legacy/OC_App.php(979): OC_App::executeRepairSteps('passwords', Array)
#10 /config/www/nextcloud/lib/private/Updater.php(379): OC_App::updateApp('passwords')
#11 /config/www/nextcloud/lib/private/Updater.php(258): OC\Updater->doAppUpgrade()
#12 /config/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.4.0', '20.0.4.0')
#13 /config/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#14 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /config/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /config/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /config/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#21 {main}root@67fce579a797:/config/www/nextcloud# 
```

### Server configuration

**Operating system:**  Ubuntu 20.04 - Docker (linuxserver.io image)

**Web server:** Nginx

**Database:** Mysql

**PHP version:**  v7.3.25

**Nextcloud version:** (see Nextcloud admin page) 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**  Recent update from existing from existing install

**Where did you install Nextcloud from:** Docker -  (linuxserver.io image

**Signing status:**
<details>
<summary>Signing status</summary>

```
Unable - cannot log into Nextcloud as maintenance mode is forced. When I disable maintenance mode, the web GUI tries to install the Password update.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - geoblocker: 0.4.5
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - passwords: 2020.12.1
  - phonetrack: 0.6.5
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.11
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_email: 2.1.0
  - socialsharing_facebook: 2.1.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - dicomviewer
  - encryption
  - external
  - files_external
  - spreed
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "upload.buck.cool"
        ],
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "https:\/\/upload.buck.cool",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/config\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "America\/New_York",
        "log_rotate_size": 20971520,
        "logfilemode": 416,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "app_install_overwrite": [
            "impersonate",
            "spreed"
        ],
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "encryption.legacy_format_support": true,
        "encryption.key_storage_migrated": false
    }
}
```
</details>

### Client configuration
**Browser:** Firefox/Chrome

</details>

**Comment by erikkastelec** [comment]
@paxxoid I get the same error. How did you manage to fix it?

**Comment by paxxoid** [comment]
> @paxxoid I get the same error. How did you manage to fix it?

I didn't. I disabled the application via the command line, manually removed maintenance mode and Nextcloud began working. When I went back to the command line to endable passwords, it said it cannot as it requires php 7.4 but I have php 7.3 installed

The linusserver io docker image is based on alpine and a quick search of their github issues found this URL:

https://github.com/linuxserver/docker-nextcloud/issues/168

There was a comment by the Linuxserver io team:

> The container will not have PHP 7.4 until Alpine release 3.13

Once I realized the issue is upstream from Nextcloud, I closed this as it really has nothing to do with Nextcloud.  At this point I'm going to wait for the Alpine release to catch up so that I can reenable Passwords within the Nextcloud container,  Hopefully a new release will happen in coming days. For now I am without the majority of my passwords as it seems there is really no good way for me to enable passwords within Nextcloud with my setup.

**Comment by marius-wieschollek** [comment]
So this issue is caused because the passwords app version 2020.1.0 requires php 7.4. Surprisingly (for me) this requirement is ignored when NC looks for an app update (but not when you try to install or enable it). I have removed the update from the appstore so your Nextcloud won't be attempting to upgrade automatically anymore.

You can follow [this downgrade guide](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Migrations/Minimum-Requirement-Error) to be able to use the app again.
