### ISSUE TITLE
occ files:scan throws exception on 21.0.0Beta5 "Error: Call to undefined method OC\DB\ConnectionAdapter::isConnected()"

### ISSUE THREAD

**Issue by AlexG-78** [nextcloud/server#25051]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to latest Nextcloud Server 21.0.0Beta5
2.run `sudo -u www-data php occ files:scan --all`

### Expected behaviour
Files should be scanned from every user

### Actual behaviour
Exception is thrown:

```
Starting scan for user 1 out of 7 (administrator)
An unhandled exception has been thrown:
Error: Call to undefined method OC\DB\ConnectionAdapter::isConnected() in /var/www/html/nextcloud/apps/files/lib/Command/Scan.php:317
Stack trace:
#0 /var/www/html/nextcloud/apps/files/lib/Command/Scan.php(120): OCA\Files\Command\Scan->reconnectToDatabase(Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/nextcloud/apps/files/lib/Command/Scan.php(209): OCA\Files\Command\Scan->scanFiles('administrator', '/administrator', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#2 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#9 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#10 {main}#
```

### Server configuration

**Operating system:**
Debian 10 Buster

**Web server:**
Apache 2.4

**Database:**
MariaDB 

**PHP version:**
PHP-FPM 7.4

**Nextcloud version:** (see Nextcloud admin page)

21.0.0Beta5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 21.0.0Beta4

**Where did you install Nextcloud from:**
I used update.phar backend script

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found.`
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

`Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - announcementcenter: 5.0.0-alpha.1
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - camerarawpreviews: 0.7.10
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.4.3
  - contactsinteraction: 1.2.0
  - customproperties: 1.0.1
  - dav: 1.17.1
  - deck: 1.3.0-beta1
  - documentserver_community: 0.1.8
  - drawio: 0.9.8
  - emlviewer: 0.0.21
  - event_update_notification: 1.2.0
  - extract: 1.3.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_3d: 0.3.3
  - files_accesscontrol: 1.10.1
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_fulltextsearch: 20.0.0
  - files_fulltextsearch_tesseract: 20.0.1
  - files_inotify: 0.1.8
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - fulltextsearch: 20.0.0
  - fulltextsearch_elasticsearch: 20.0.0
  - groupfolders: 8.2.0
  - groupquota: 0.1.4
  - imageconverter: 1.3.1
  - impersonate: 1.7.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.8
  - metadata: 0.12.0
  - music: 0.17.3
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.2
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 6.2.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.0
  - printer: 0.0.5
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quickaccesssorting: 1.1.2
  - quota_warning: 1.10.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - side_menu: 1.21.0
  - socialsharing_email: 2.1.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - suspicious_login: 3.2.1
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - unsplash: 1.1.7
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - user_usage_report: 1.5.0
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflow_script: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - dashboard
  - encryption
  - user_ldap`
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
safari on Big Sur
**Operating system:**
MacOs Big Sur
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by muhviehstah** [comment]
got the same error with nginx  and without ldap

**Comment by Lars1963** [comment]
also got this error

**Comment by kesselb** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/server/pull/25080. Please give this a try :)
