### ISSUE TITLE
ios dont send Auth basic in header

### ISSUE THREAD

**Issue by inpos** [nextcloud/server#2554]
### Steps to reproduce
1. Configure caldav on ios

### Expected behaviour
Setting up caldav successful

### Actual behaviour
During caldav account setup process ios dont accept login and password.
I have two servers with the same configuration. On another server setup process finished successful.
By using tcpdump I determine that ios dont send "Authorization: Basic" in request header.
But send to second server.

### Server configuration
**Operating system**: Debian Jessie amd64

**Web server:** Apache 2.4

**Database:** PostgreSQL

**PHP version:** 7.0

**Server version:** 10.0.1 (stable)

**Calendar version:** 1.4.1

**Updated from an older installed version or fresh install:** fresh

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.5.1
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_automatedtagging
  - files_retention
  - ojsxc
  - user_external
  - user_saml
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc7642bn2yzy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.zzzzzzz.ru",
            "cloud.yyyyyyy.moscow"
        ],
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "datadirectory": "\/mnt\/data\/nc_data",
        "overwrite.cli.url": "http:\/\/cloud.yyyyyyy.ru",
        "dbtype": "pgsql",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Moscow",
        "installed": true,
        "version": "9.1.1.5",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "3",
        "mail_smtpmode": "smtp",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "mail_from_address": "cloud",
        "mail_domain": "yyyyyyy.ru",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.yyyyyyy.ru",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "default_language": "ru",
        "appstore.experimental.enabled": true
    },
    "apps": {
        "activity": {
            "installed_version": "2.3.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "14"
        },
        "bookmarks": {
            "installed_version": "0.9.0",
            "types": "",
            "enabled": "yes",
            "ocsid": "168710"
        },
        "calendar": {
            "installed_version": "1.4.1",
            "types": "",
            "ocsid": "168707",
            "enabled": "yes"
        },
        "comments": {
            "installed_version": "1.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "types": "",
            "ocsid": "168708",
            "enabled": "yes",
            "installed_version": "1.5.1"
        },
        "core": {
            "installedat": "1478425767.0623",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "oc.integritycheck.checker": "[]",
            "backgroundjobs_mode": "cron",
            "public_documents": "documents\/public.php",
            "lastupdatedat": "1481137337",
            "lastupdateResult": "[]",
            "lastcron": "1481138104",
            "shareapi_allow_public_notification": "yes"
        },
        "dav": {
            "installed_version": "1.0.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "documents": {
            "installed_version": "0.13.1",
            "types": "",
            "enabled": "yes",
            "ocsid": "168711",
            "converter": "local"
        },
        "federatedfilesharing": {
            "installed_version": "1.0.1",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.0.1",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.5.2",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500",
            "default_quota": "5 GB"
        },
        "files_accesscontrol": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.1.2"
        },
        "files_automatedtagging": {
            "installed_version": "1.1.1",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_external": {
            "installed_version": "1.0.2",
            "ocsid": "166048",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_pdfviewer": {
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.0.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_texteditor": {
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.0.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "0.9.8",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": "",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "15.0.0",
            "types": "",
            "enabled": "yes"
        },
        "notifications": {
            "installed_version": "0.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes",
            "enforceUpperLowerCase": "1",
            "enforceNumericCharacters": "1"
        },
        "provisioning_api": {
            "installed_version": "1.0.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "serverinfo": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "survey_client": {
            "installed_version": "0.1.5",
            "types": "",
            "enabled": "yes",
            "last_sent": "1481115073",
            "last_report": "{\"id\":\"oc7642bn2yzy\",\"items\":[[\"server\",\"version\",\"9.1.1.5\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"php\",\"version\",\"5.6.27\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",17179869184],[\"database\",\"type\",\"pgsql\"],[\"database\",\"version\",\"PostgreSQL 9.4.9 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit\"],[\"database\",\"size\",12054292],[\"apps\",\"federatedfilesharing\",\"1.0.1\"],[\"apps\",\"updatenotification\",\"1.0.1\"],[\"apps\",\"notifications\",\"0.3.0\"],[\"apps\",\"files_trashbin\",\"1.0.0\"],[\"apps\",\"survey_client\",\"0.1.5\"],[\"apps\",\"provisioning_api\",\"1.0.0\"],[\"apps\",\"files_pdfviewer\",\"0.8.1\"],[\"apps\",\"federation\",\"1.0.1\"],[\"apps\",\"systemtags\",\"1.0.2\"],[\"apps\",\"files\",\"1.5.2\"],[\"apps\",\"firstrunwizard\",\"1.1\"],[\"apps\",\"comments\",\"1.0.0\"],[\"apps\",\"files_texteditor\",\"2.1\"],[\"apps\",\"dav\",\"1.0.1\"],[\"apps\",\"files_versions\",\"1.3.0\"],[\"apps\",\"activity\",\"2.3.2\"],[\"apps\",\"password_policy\",\"1.0.0\"],[\"apps\",\"gallery\",\"15.0.0\"],[\"apps\",\"files_videoplayer\",\"0.9.8\"],[\"apps\",\"workflowengine\",\"1.0.1\"],[\"apps\",\"serverinfo\",\"1.1.1\"],[\"apps\",\"theming\",\"1.0.1\"],[\"apps\",\"files_sharing\",\"1.0.0\"],[\"apps\",\"files_automatedtagging\",\"1.1.1\"],[\"apps\",\"user_ldap\",\"1.0.1\"],[\"apps\",\"calendar\",\"1.4.1\"],[\"apps\",\"bookmarks\",\"0.9.0\"],[\"apps\",\"files_accesscontrol\",\"1.1.2\"],[\"apps\",\"documents\",\"0.13.1\"],[\"apps\",\"tasks\",\"0.9.3\"],[\"apps\",\"contacts\",\"1.5.1\"],[\"stats\",\"num_files\",127],[\"stats\",\"num_users\",8],[\"stats\",\"num_storages\",14],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",13],[\"stats\",\"num_storages_other\",0],[\"files_sharing\",\"num_shares\",2],[\"files_sharing\",\"num_shares_user\",1],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",1],[\"files_sharing\",\"num_shares_link_no_password\",1],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_15\",1],[\"files_sharing\",\"permissions_3_15\",1],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}"
        },
        "systemtags": {
            "installed_version": "1.0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.9.3",
            "types": "",
            "ocsid": "164356",
            "enabled": "yes"
        },
        "templateeditor": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "1.0.1",
            "types": "logging",
            "enabled": "yes",
            "color": "#319A3B",
            "name": "Some Name",
            "url": "https:\/\/cloud.yyyyyyyy.ru",
            "cachebuster": "7"
        },
        "updatenotification": {
            "installed_version": "1.0.1",
            "types": "",
            "enabled": "yes",
            "contacts": "1.5.0",
            "calendar": "1.4.1"
        },
        "user_ldap": {
            "installed_version": "1.0.1",
            "types": "authentication",
            "enabled": "yes",
            "ldap_base_users": "dc=rrrrrrr,dc=lan",
            "ldap_base_groups": "dc=rrrrrrr,dc=lan",
            "ldap_group_filter": "(&(|(objectclass=group))(|(cn=_Some_group)))",
            "ldap_paging_size": "500",
            "ldap_configuration_active": "1",
            "ldap_expert_uuid_user_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_user_display_name_2": "",
            "ldap_group_filter_mode": "0",
            "ldap_group_display_name": "cn",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_cache_ttl": "600",
            "ldap_override_main_server": "",
            "ldap_attributes_for_group_search": "",
            "ldap_experienced_admin": "0",
            "home_folder_naming_rule": "",
            "use_memberof_to_detect_membership": "1",
            "last_jpegPhoto_lookup": "0",
            "ldap_dynamic_group_member_url": "",
            "ldap_agent_password": "xxxxxxxxxxxxxxxx",
            "ldap_user_filter_mode": "0",
            "has_memberof_filter_support": "1",
            "ldap_dn": "ldapuser@rrrrrrrr.lan",
            "ldap_display_name": "cn",
            "ldap_group_member_assoc_attribute": "member",
            "ldap_email_attr": "mail",
            "ldap_userfilter_objectclass": "person",
            "ldap_attributes_for_user_search": "",
            "ldap_loginfilter_attributes": "sAMAccountName",
            "ldap_port": "636",
            "ldap_groupfilter_objectclass": "group",
            "ldap_base": "ou=some_ou,dc=rrrrrrrr,dc=lan",
            "ldap_userlist_filter": "(&(|(objectclass=person))(|(|(memberof=CN=_Some_group,OU=some_ou1,OU=some_ou2,DC=rrrrrrr,DC=lan)(primaryGroupID=1106))))",
            "ldap_expert_username_attr": "sAMAccountName",
            "ldap_host": "ldaps:\/\/rrrrrrrr.lan",
            "ldap_login_filter_mode": "0",
            "ldap_login_filter": "(&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(sAMAccountName=%uid))))",
            "ldap_nested_groups": "1",
            "cleanUpJobOffset": "0",
            "ldap_userfilter_groups": "_Some_group",
            "ldap_groupfilter_groups": "_Some_group"
        },
        "workflowengine": {
            "installed_version": "1.0.1",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+----------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                      |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                    |
| hasPagedResultSupport         |                                                                                                                      |
| homeFolderNamingRule          |                                                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                                                    |
| ldapAgentName                 | ldapuser@rrrrrrr.lan                                                                                                 |
| ldapAgentPassword             | ***                                                                                                                  |
| ldapAttributesForGroupSearch  |                                                                                                                      |
| ldapAttributesForUserSearch   |                                                                                                                      |
| ldapBackupHost                |                                                                                                                      |
| ldapBackupPort                |                                                                                                                      |
| ldapBase                      | ou=Some_ou,dc=rrrrrrr,dc=lan                                                                                         |
| ldapBaseGroups                | dc=rrrrrrrr,dc=lan                                                                                                    |
| ldapBaseUsers                 | dc=rrrrrrrr,dc=lan                                                                                                    |
| ldapCacheTTL                  | 600                                                                                                                  |
| ldapConfigurationActive       | 1                                                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                                                      |
| ldapEmailAttribute            | mail                                                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                                                    |
| ldapExpertUUIDGroupAttr       |                                                                                                                      |
| ldapExpertUUIDUserAttr        |                                                                                                                      |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                       |
| ldapGroupDisplayName          | cn                                                                                                                   |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=_Some_group)))                                                                             |
| ldapGroupFilterGroups         | _Some_group                                                                                                              |
| ldapGroupFilterMode           | 0                                                                                                                    |
| ldapGroupFilterObjectclass    | group                                                                                                                |
| ldapGroupMemberAssocAttr      | member                                                                                                               |
| ldapHost                      | ldaps://rrrrrrrr.lan                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                                      |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(sAMAccountName=%uid))))                                        |
| ldapLoginFilterAttributes     | sAMAccountName                                                                                                       |
| ldapLoginFilterEmail          | 0                                                                                                                    |
| ldapLoginFilterMode           | 0                                                                                                                    |
| ldapLoginFilterUsername       | 1                                                                                                                    |
| ldapNestedGroups              | 1                                                                                                                    |
| ldapOverrideMainServer        |                                                                                                                      |
| ldapPagingSize                | 500                                                                                                                  |
| ldapPort                      | 636                                                                                                                  |
| ldapQuotaAttribute            |                                                                                                                      |
| ldapQuotaDefault              |                                                                                                                      |
| ldapTLS                       | 0                                                                                                                    |
| ldapUserDisplayName           | cn                                                                                                                   |
| ldapUserDisplayName2          |                                                                                                                      |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=_Some_group,OU=some_ou1,OU=some_ou2,DC=rrrrrrrr,DC=lan)(primaryGroupID=1106)))) |
| ldapUserFilterGroups          | _Some_group                                                                                                              |
| ldapUserFilterMode            | 0                                                                                                                    |
| ldapUserFilterObjectclass     | person                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                 |
| ldapUuidUserAttribute         | auto                                                                                                                 |
| turnOffCertCheck              | 0                                                                                                                    |
| useMemberOfToDetectMembership | 1                                                                                                                    |

```

### Client configuration
**Browser:** ios

**Operating system:** ios

**CalDAV-clients:** ios caldav

#### Web server error log
```
none
```

#### Log file (data/owncloud.log)
```
Dec  6 20:11:30 cloud ownCloud[30982]: {webdav} Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/nextcloud\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/var\/www\/nextcloud\/remote.php(165): require_once('\/var\/www\/nextcl...')\n#7 {main}","File":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
```

#### Browser log
```
none
```

**Comment by inpos** [comment]
Found solution.
Install latest owncloud and walk through migrate to nextcloud process.
Fresh nextcloud installation don't work with ios caldav/carddav.

**Comment by nickvergessen** [comment]
That's an odd workaround, because they should be pretty much the same in that aspect.
After upgrading/migrating it works with nextcloud as well?

**Comment by inpos** [comment]
After migrating from owncloud to nextcloud all works as expected

**Comment by nickvergessen** [comment]
Okay, then I will close this issue.
There is still a similar issue open: https://github.com/nextcloud/server/issues/2540

**Comment by inpos** [comment]
I think #2540 is not similar issue
