### ISSUE TITLE
Class 'InterfaSys\LogNormalizer\Normalizer' not found in /var/www/html/lib/private/Log.php:90

### ISSUE THREAD

**Issue by TomasTomecek** [nextcloud/server#25828]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### The problem

After I did an upgrade from nextcloud 18 to 19, my installation broke and all commands resulted with:
```
www-data@2776db07d5e2:~/html$ ./occ status                                                                                                                                                                         
An unhandled exception has been thrown:                                                                  
Error: Class 'InterfaSys\LogNormalizer\Normalizer' not found in /var/www/html/lib/private/Log.php:90     
Stack trace:                                                                                             
#0 /var/www/html/lib/private/Server.php(720): OC\Log->__construct(Object(OC\Log\File), Object(OC\SystemConfig), NULL, Object(OC\Support\CrashReport\Registry))
#1 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#2 /var/www/html/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\Log')            
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OC\\Log')                                                                                                   
#4 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#5 /var/www/html/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OCP\\ILogger')       
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(71): OC\ServerContainer->query('OCP\\ILogger', true)
#7 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(101): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\EventDispatc...')
#9 /var/www/html/lib/private/ServerContainer.php(149): OC\AppFramework\Utility\SimpleContainer->query('OC\\EventDispatc...', true)
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(71): OC\ServerContainer->query('OC\\EventDispatc...', true)                                                                                 
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(101): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\EventDispatc...')
#13 /var/www/html/lib/private/ServerContainer.php(149): OC\AppFramework\Utility\SimpleContainer->query('OC\\EventDispatc...', true)
#14 /var/www/html/lib/private/Server.php(2023): OC\ServerContainer->query('OC\\EventDispatc...')         
#15 /var/www/html/lib/private/Server.php(1386): OC\Server->getEventDispatcher()                          
#16 /var/www/html/lib/private/Server.php(1361): OC\Server->connectDispatcher()                           
#17 /var/www/html/lib/base.php(599): OC\Server->__construct('', Object(OC\Config))                       
#18 /var/www/html/lib/base.php(1093): OC::init()                                                         
#19 /var/www/html/console.php(49): require_once('/var/www/html/l...')                                    
#20 /var/www/html/occ(11): require_once('/var/www/html/c...')                                             
```

After I found this commit https://github.com/nextcloud/3rdparty/commit/e8d0486b8ad8e4740c6be2a6f0b95fbe8e22c5c3 I realized I just needed to change `InterfaSys` to `Nextcloud` in Log.php - and it worked.

Not sure if this can be reproduced, just leaving this here in case someone has the same issue

### Server configuration

**Operating system:**
Official nextcloud nextcloud:19-fpm container image

**Nextcloud version:** (see Nextcloud admin page)
19

**Updated from an older Nextcloud/ownCloud or fresh install:**
From 18

```
www-data@2776db07d5e2:~/html$ ./occ status
  - installed: true
  - version: 19.0.9.1
  - versionstring: 19.0.9
  - edition: 
```

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by TomasTomecek** [comment]
I am running 20 right now and this is no longer relevant
