### ISSUE TITLE
[SOLVED] : Upgrade to 21 failed in BigInteger.php:662 : int expected

### ISSUE THREAD

**Issue by nmset** [nextcloud/server#25834]
./occ upgrade

failed with this stack trace

```
Starting code integrity check...
An unhandled exception has been thrown:
TypeError: decbin(): Argument #1 ($num) must be of type int, float given in /home/www/nextcloud.2100/3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php:662
Stack trace:
#0 /home/www/nextcloud.2100/3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php(662): decbin(4006366091)
#1 /home/www/nextcloud.2100/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(2848): phpseclib\Math\BigInteger->toBits()
#2 /home/www/nextcloud.2100/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(3177): phpseclib\Crypt\RSA->_rsassa_pss_verify('{".htaccess":"d...', '\xA8\xF2W\xE8p\xC5\x94\x85]\x10t\xDD@\x83\xB5...')
#3 /home/www/nextcloud.2100/lib/private/IntegrityCheck/Checker.php(371): phpseclib\Crypt\RSA->verify('{".htaccess":"d...', '\xA8\xF2W\xE8p\xC5\x94\x85]\x10t\xDD@\x83\xB5...')
#4 /home/www/nextcloud.2100/lib/private/IntegrityCheck/Checker.php(571): OC\IntegrityCheck\Checker->verify('/home/www/nextc...', '/home/www/nextc...', 'core')
#5 /home/www/nextcloud.2100/lib/private/IntegrityCheck/Checker.php(592): OC\IntegrityCheck\Checker->verifyCoreSignature()
#6 /home/www/nextcloud.2100/lib/private/Updater.php(288): OC\IntegrityCheck\Checker->runInstanceVerification()
#7 /home/www/nextcloud.2100/lib/private/Updater.php(132): OC\Updater->doUpgrade('21.0.0.18', '20.0.3.2')
#8 /home/www/nextcloud.2100/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#9 /home/www/nextcloud.2100/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/www/nextcloud.2100/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/www/nextcloud.2100/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/www/nextcloud.2100/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/www/nextcloud.2100/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/www/nextcloud.2100/console.php(100): OC\Console\Application->run()
#15 /home/www/nextcloud.2100/occ(11): require_once('/home/www/nextc...')
```

Upgrading from 20.0.3 to 21.0.0 on Arch Linux armv7l.

Modified /home/www/nextcloud.2100/3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php
on line 662 : 
```
- $bits = str_pad(decbin(hexdec(substr($hex, $i, 8))), 32, '0', STR_PAD_LEFT) . $bits;
+ $bits = str_pad(decbin((int) hexdec(substr($hex, $i, 8))), 32, '0', STR_PAD_LEFT) . $bits;
```

Upgrade then succeeded.

Regards.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by nmset** [comment]
Upgrading from 21.0.0 to 21.0.2 went on error free. Closing.
