### ISSUE TITLE
occ files:scan fails with an exception

### ISSUE THREAD

**Issue by enaut** [nextcloud/server#25851]
### Steps to reproduce
execute `# sudo -u nginx php /var/www/Nextcloud/occ files:scan -vvv Medienpaedagogik`

### Expected behaviour
The Files are indexed and included into the Account

### Actual behaviour
The command errors with:

```
# sudo -u nginx php /var/www/Nextcloud/occ files:scan -vvv Medienpaedagogik
Starting scan for user 1 out of 1 (Medienpaedagogik)
	Folder	/Medienpaedagogik/
	Folder	/Medienpaedagogik/files_external
	File	/Medienpaedagogik/files_external/rootcerts.crt
	Folder	/Medienpaedagogik/uploads
	Folder	/Medienpaedagogik/cache
	Folder	/Medienpaedagogik/files
Exception during scan: Trying to access array offset on value of type null
#0 /var/www/Nextcloud/apps/files_sharing/lib/External/Scanner.php(97): OCA\Files\Command\Scan->exceptionErrorHandler()
#1 /var/www/Nextcloud/apps/files_sharing/lib/External/Scanner.php(45): OCA\Files_Sharing\External\Scanner->scanAll()
#2 /var/www/Nextcloud/lib/private/Files/Utils/Scanner.php(260): OCA\Files_Sharing\External\Scanner->scan()
#3 /var/www/Nextcloud/apps/files/lib/Command/Scan.php(158): OC\Files\Utils\Scanner->scan()
#4 /var/www/Nextcloud/apps/files/lib/Command/Scan.php(214): OCA\Files\Command\Scan->scanFiles()
#5 /var/www/Nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#6 /var/www/Nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#7 /var/www/Nextcloud/apps/mail/vendor/symfony/console/Application.php(971): OC\Core\Command\Base->run()
#8 /var/www/Nextcloud/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/Nextcloud/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#10 /var/www/Nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#11 /var/www/Nextcloud/console.php(100): OC\Console\Application->run()
#12 /var/www/Nextcloud/occ(11): require_once('/var/www/Nextcl...')
#13 {main}

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 5       | 1     | 00:00:02     |
+---------+-------+--------------+
```

Note that I moved all files outside of this folder, cleaned all versions and trashbinfiles using appropriate commands.

## Server configuration detail

**Operating system:** Linux 5.10.14-200.fc33.x86_64 #1 SMP Sun Feb 7 19:59:31 UTC 2021 x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.4.17

**PHP version:** 

7.4.15
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, imagick, msgpack, zip, memcached, systemd, Zend OPcache

**Nextcloud version:** 21.0.0 - 21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:** updated for several versions.

**Where did you install Nextcloud from:** tar file

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - appointments: 1.8.5
 - bbb: 1.3.0-beta.1
 - calendar: 2.1.3
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.4.3
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.3.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_markdown: 2.3.2
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.2.0-beta.1
 - groupfolders: 9.0.0
 - impersonate: 1.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.8.3
 - maps: 0.1.8
 - news: 15.3.2
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - polls: 1.7.5
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - richdocuments: 4.0.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - social: 0.4.2
 - spreed: 11.0.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - suspicious_login: 3.2.1
 - systemtags: 1.11.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_totp: 6.0.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - bruteforcesettings
 - circles
 - encryption
 - files_external
 - richdocumentscode
 - user_ldap
 - workflow_script

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc.teilgedanken.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nc.teilgedanken.de",
    "dbtype": "mysql",
    "version": "21.0.0.18",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "appstore.experimental.enabled": true,
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpport": "8465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "updater.release.channel": "beta",
    "log_type": "systemd",
    "customclient_android": "https:\/\/f-droid.org\/repository\/browse\/?fdid=com.nextcloud.client",
    "app.mail.imaplog.enabled": true,
    "theme": "",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mysql.utf8mb4": true,
    "mail_smtpauthtype": "LOGIN",
    "app_install_overwrite": [
        "mail",
        "onlyoffice",
        "deck",
        "news",
        "polls",
        "calendar",
        "files_markdown",
        "maps",
        "contacts",
        "spreed",
        "documentserver_community",
        "groupfolders",
        "circles",
        "richdocumentscode",
        "suspicious_login",
        "appointments",
        "issuetemplate"
    ],
    "mail_sendmailmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "data-fingerprint": "c34286bce08bf3709385b808451e1a7b"
}
```
</details>

**Are you using external storage, if yes which one:** only native storage

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by enaut** [comment]
This is still the same...

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
