### ISSUE TITLE
Files inconsistent in database and data directory

### ISSUE THREAD

**Issue by heyarne** [nextcloud/server#2605]
### Steps to reproduce

I have moved my nextcloud instance from one server to another (via `rsync -Aax -t --progress $FROM $TO` for the `data` and `config` directories), following [this guide](https://docs.nextcloud.com/server/10/admin_manual/maintenance/migrating.html). After everything appeared to have been working, i moved my data folder (by `mv`ing it on the filesystem and then updating the path in the `config.php`). Unfortunately I am now not getting files listed in the web interface, which are still on the hard drive. At the same time there are files I see in the web interface having a size of 0 kb which are not present on the hard drive. Other weird behavior which might be related to this: I can open some files which are present but only in the web interface (I did not try webdav). When I try viewing them with the Android client, the folders containting them show up as having the correct size – when I open them however, the app tell's me they're empty (after which they appear to be 0 kb large as well, until I open another folder).

I already tried `sudo -u www-data ./occ files:scan --all` as well as `sudo -u www-data ./occ files:scan $MY_USERNAME`, which didn't change anything.

Output of `sudo -u www-data php occ maintenance:repair`:
```
Nextcloud is in maintenance mode - no app have been loaded
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\Classification' is unknown
 - Repair mime types
 - Repair legacy storages
 - Remove asset cache
     - Asset cache cleared.
 - Generate ETags for file where no ETag is present.
     - ETags have been fixed for 0 files/folders.
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Drop old database tables
 31/31 [============================] 100%
 - Drop old background jobs
 - Remove getetag entries in properties table
     - Removed 0 unneeded "{DAV:}getetag" entries from properties table.
 - Repair outdated OCS IDs
 - Repair invalid shares
 - Remove old share propagation app entries
 - Remove old (< 9.0) calendar/contact shares
 4/4 [============================] 100%  
 - Fix permissions so avatars can be stored again
 2/2 [============================] 100%  
 - Remove shares of a users root folder
 - Repair unmerged shares
 - Move .step file of updater to backup location
```

### Server configuration
**Operating system**:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Web server:**
```
nginx version: nginx/1.10.0 (Ubuntu)
```

**Database:**
```
mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**PHP version:**
```
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
```

**Nextcloud version:** (see Nextcloud admin page) 10.0.1

**Where did you install Nextcloud from:** I used the tar.bz2 archive.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: true
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - comments
  - encryption
  - external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocjx58mjh67j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "46.101.150.180",
            "my.url"
        ],
        "datadirectory": "\/var\/nextcloud\/",
        "overwrite.cli.url": "https:\/\/my.url\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "appstore.experimental.enabled": true,
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
Firefox 50 on macOS, Android client 1.3.1

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Error 	index 	Exception: {"Exception":"OC\\PreviewNotAvailableException","Message":"SVG mimetype cannot be rendered","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/lib\/private\/Preview.php(809): OC\\Preview->getMimeIcon()\n#1 \/var\/www\/html\/nextcloud\/core\/ajax\/preview.php(66): OC\\Preview->showPreview()\n#2 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Route.php(155) : runtime-created function(1): require_once('\/var\/www\/html\/n...')\n#3 [internal function]: __lambda_func()\n#4 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func('\\x00lambda_607', Array)\n#5 \/var\/www\/html\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/core\/preview.p...')\n#6 \/var\/www\/html\/nextcloud\/index.php(48): OC::handleRequest()\n#7 {main}","File":"\/var\/www\/html\/nextcloud\/lib\/private\/Preview.php","Line":1188} 	2016-12-10T18:21:38+00:00 	arne
```
</details>
(multiple times)

#### Browser log
When opening the directory that has a 0 kb file in the web interface that's not on disk and misses some from the disk:

<details>
<summary>Browser log</summary>
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  files
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  styles.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  inputs.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  fixes.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  icons.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  header.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  fonts.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  multiselect.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mobile.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  global.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery-ui.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery-ui-fixes.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  apps.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  style.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  tooltip.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  share.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  versions.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  style.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  colorbox.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  firstrunwizard.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  slideshow.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  gallerybutton.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  styles.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  files.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery.ocdialog.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  upload.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mobile.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  external.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  detailsView.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  trash.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  style.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharetabview.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  stylesheet.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  style.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mobile.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  select2.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtags.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagsfilelist.css
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery-migrate.min.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery-ui.custom.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  underscore.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery.min.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  oc.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More] handlebars.js
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://my.url 'unsafe-eval'”). files:1
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  moment-with-locales.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  md5.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  tooltip.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More] backbone.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  es6-promise.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  client.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  clipboard.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  placeholders.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  compatibility.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery.ocdialog.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  oc-dialogs.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  js.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  l10n.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  octemplate.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  eventsource.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  config.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  oc-requesttoken.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  apps.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  search.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mimetype.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mimetypelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  snap.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  oc-backbone.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  placeholder.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  previewplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery.avatar.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  shareconfigmodel.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  shareitemmodel.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedialogmailview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedialogresharerinfoview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedialogexpirationview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedialoglinkshareview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedialogshareelistview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedialogview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  share.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery.colorbox.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  viewer.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  firstrunwizard.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  bigshot-compressed.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  purify.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  galleryutility.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  galleryfileaction.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  slideshow.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  slideshowcontrols.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  slideshowzoomablepreview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  gallerybutton.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  notification.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  notification.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  fileinfo.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  client.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  file-upload.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  newfilemenu.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery.fileupload.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  jquery-visibility.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  fileinfomodel.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  filesummary.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  breadcrumb.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  filelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  search.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  favoritesfilelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  tagsplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  gotoplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  favoritesplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sidebarpreviewmanager.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  detailfileinfoview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sidebarpreviewtext.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  detailtabview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mainfileinfodetailview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  fileactions.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  detailsview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  fileactionsmenu.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  files.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  keyboardshortcuts.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  navigation.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  rollingqueue.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharedfilelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  statusmanager.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mountsfilelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  filelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  activitymodel.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  formatter.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  activitytabview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  activitycollection.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  filesplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  viewer.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  external.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  share.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  sharetabview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  editor.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  ace.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  versionmodel.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  versioncollection.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  filesplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  versionstabview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  select2.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  select2-toggleselect.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  oc-backbone-webdav.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtags.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagmodel.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagsmappingcollection.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagscollection.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagsinputfield.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagsfilelist.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  filesplugin.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  systemtagsinfoview.js
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  theming
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  styles
window.controllers is deprecated. Do not use it for UA detection.  ace.js:1716
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  files.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  activity.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  app.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  documents.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  calendar.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  apps.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  personal.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  users.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  admin.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  help.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  logout.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  delete.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  logo-icon.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  caret.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  search-white.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  folder.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  star.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  share.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  public.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  tag.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  external.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  delete.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  32
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  settings.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  part.results.html
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  toggle-pictures.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More] notifications.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  config
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  notifications
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mimes.php
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  home.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  breadcrumb.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  close.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  loading.gif
GET 
https://my.url/nextcloud/core/preview.png [HTTP/1.1 500 Internal Server Error 182ms]
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  add.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  menu.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  getstoragestats.php
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  star.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  checkbox.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  folder.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  mounts
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  share.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  more.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  image.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  triangle-s.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  triangle-n.svg
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]  preview.png
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More]
```
</details>

**Comment by heyarne** [comment]
I could "fix" the browser log to look like this:
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://shantaram.schlueter.is 'unsafe-eval'”). files:1
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
window.controllers is deprecated. Do not use it for UA detection.  ace.js:1716
GET 
https://my.url/nextcloud/core/preview.png [HTTP/1.1 500 Internal Server Error 99ms]

**Comment by heyarne** [comment]
The issue could be resolved in the meantime. Unfortunately the data already was corrupted on the old server, which had gone unnoticed. I don't know and can't fathom anymore if that was because of an aborted upload or something alike.

The mobile app issue went away after removing the server configuration in the app and updating to 1.4.

The nginx config issue (although unrelated) seems to persist. Can someone point me to the sources to change the docs?

**Comment by MorrisJobke** [comment]
> The nginx config issue (although unrelated) seems to persist. Can someone point me to the sources to change the docs?

https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx_nextcloud_9x.rst
