### ISSUE TITLE
Cannot Copy Log Entries Formatted

### ISSUE THREAD

**Issue by Prog1563** [nextcloud/server#26116]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Visit the Nextcloud web log viewer.
2. Try to copy a log message formatted.

### Expected behaviour
The log entry should be copied to the clipboard formatted and the context menu should disappear.

### Actual behaviour
The context menu stays and nothing is coppied to the clipboard.
Copy raw functions as normal.

### Server configuration

**Operating system:** Debian 10

**Web server:** NGINX 1.14.2

**Database:** MariaDB 10

**PHP version:** 7.4

**Nextcloud version:** 20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded since NC 10 and previously migrated from Owncloud.

**Where did you install Nextcloud from:** The Nextcloud website.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - admin_audit: 1.10.0
  - apporder: 0.12.0
  - bookmarks: 4.1.0
  - breezedark: 20.0.7
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - carnet: 0.23.8
  - cloud_federation_api: 1.3.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.4
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - drawio: 0.9.9
  - duplicatefinder: 0.0.6
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - groupfolders: 8.2.0
  - imageconverter: 1.3.1
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notes: 4.0.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - passwords: 2021.3.0
  - photos: 1.2.3
  - provisioning_api: 1.10.0
  - richdocuments: 3.7.15
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.1.2
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "debug": false,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "defaultapp": "dashboard",
        "logfile": "\/mnt\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "log_rotate_size": 10485760,
        "knowledgebaseenabled": false,
        "has_rebuilt_cache": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** Locally mounted NFS

**Are you using encryption:** yes, drives are LUKS encrypted.

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Google Chrome 89

**Operating system:** Windows 10.20H2

#### Web server error log
No related log entries.

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"NUWvfxOKW33cCB0W8v5w","level":3,"time":"2021-03-15T12:24:05+00:00","remoteAddr":"-----","user":"--","app":"PHP","method":"GET","url":"/index.php/204","message":{"Exception":"Error","Message":"unlink(/mnt/nextcloud/data_dir_writability_test_604f51e5416a3.tmp): No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Util.php#814","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":814,"function":"unlink"},{"file":"/var/www/nextcloud/lib/base.php","line":660,"function":"checkServer","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/var/www/nextcloud/index.php","line":35,"args":["/var/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.15.1","version":"20.0.8.1","id":"604f54a105872"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
main.js?v=bc0cc391-97:35 Uncaught TypeError: Cannot read property 'map' of undefined
    at main.js?v=bc0cc391-97:1
    at Array.map (<anonymous>)
    at ExceptionParser.value (main.js?v=bc0cc391-97:1)
    at i (main.js?v=bc0cc391-97:19)
    at onClick (main.js?v=bc0cc391-97:19)
    at Object.l (main.js?v=bc0cc391-97:35)
    at p (main.js?v=bc0cc391-97:35)
    at main.js?v=bc0cc391-97:35
    at b (main.js?v=bc0cc391-97:35)
    at it (main.js?v=bc0cc391-97:35)
ExceptionParser.js:171 Uncaught TypeError: Cannot read property 'map' of undefined
    at main.js?v=bc0cc391-97:1
    at Array.map (<anonymous>)
    at ExceptionParser.value (main.js?v=bc0cc391-97:1)
    at i (main.js?v=bc0cc391-97:19)
    at onClick (main.js?v=bc0cc391-97:19)
    at Object.l (main.js?v=bc0cc391-97:35)
    at p (main.js?v=bc0cc391-97:35)
    at main.js?v=bc0cc391-97:35
    at b (main.js?v=bc0cc391-97:35)
    at it (main.js?v=bc0cc391-97:35)
(anonymous) @ main.js?v=bc0cc391-97:1
value @ main.js?v=bc0cc391-97:1
i @ main.js?v=bc0cc391-97:19
onClick @ main.js?v=bc0cc391-97:19
l @ main.js?v=bc0cc391-97:35
p @ main.js?v=bc0cc391-97:35
(anonymous) @ main.js?v=bc0cc391-97:35
b @ main.js?v=bc0cc391-97:35
it @ main.js?v=bc0cc391-97:35
at @ main.js?v=bc0cc391-97:35
lt @ main.js?v=bc0cc391-97:35
pt @ main.js?v=bc0cc391-97:35
W @ main.js?v=bc0cc391-97:35
N @ main.js?v=bc0cc391-97:35
Xt @ main.js?v=bc0cc391-97:35
Jt @ main.js?v=bc0cc391-97:35
t.unstable_runWithPriority @ main.js?v=bc0cc391-97:43
qa @ main.js?v=bc0cc391-97:35
U @ main.js?v=bc0cc391-97:35
Qt @ main.js?v=bc0cc391-97:35
ExceptionParser.js:171 Uncaught TypeError: Cannot read property 'map' of undefined
    at main.js?v=bc0cc391-97:1
    at Array.map (<anonymous>)
    at ExceptionParser.value (main.js?v=bc0cc391-97:1)
    at i (main.js?v=bc0cc391-97:19)
    at onClick (main.js?v=bc0cc391-97:19)
    at Object.l (main.js?v=bc0cc391-97:35)
    at p (main.js?v=bc0cc391-97:35)
    at main.js?v=bc0cc391-97:35
    at b (main.js?v=bc0cc391-97:35)
    at it (main.js?v=bc0cc391-97:35)
(anonymous) @ main.js?v=bc0cc391-97:1
value @ main.js?v=bc0cc391-97:1
i @ main.js?v=bc0cc391-97:19
onClick @ main.js?v=bc0cc391-97:19
l @ main.js?v=bc0cc391-97:35
p @ main.js?v=bc0cc391-97:35
(anonymous) @ main.js?v=bc0cc391-97:35
b @ main.js?v=bc0cc391-97:35
it @ main.js?v=bc0cc391-97:35
at @ main.js?v=bc0cc391-97:35
lt @ main.js?v=bc0cc391-97:35
pt @ main.js?v=bc0cc391-97:35
W @ main.js?v=bc0cc391-97:35
N @ main.js?v=bc0cc391-97:35
Xt @ main.js?v=bc0cc391-97:35
Jt @ main.js?v=bc0cc391-97:35
t.unstable_runWithPriority @ main.js?v=bc0cc391-97:43
qa @ main.js?v=bc0cc391-97:35
U @ main.js?v=bc0cc391-97:35
Qt @ main.js?v=bc0cc391-97:35
​ Uncaught TypeError: Cannot read property 'value' of undefined
    at l._checkForDuplication (client.js:28)
    at l._checkFormForPassword (client.js:28)
    at l._checkForNewPassword (client.js:28)
    at window.addEventListener.passive (client.js:28)
_checkForDuplication @ client.js:28
_checkFormForPassword @ client.js:28
_checkForNewPassword @ client.js:28
window.addEventListener.passive @ client.js:28
client.js:24 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at nt (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/client.js:24:625222)
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/client.js:24:771195
nt @ client.js:24
(anonymous) @ client.js:24
Promise.then (async)
i @ client.js:24
gt @ client.js:24
(anonymous) @ client.js:24
o @ client.js:24
(anonymous) @ client.js:24
(anonymous) @ client.js:24
s @ client.js:1
(anonymous) @ client.js:1
s @ client.js:1
(anonymous) @ client.js:22
s @ client.js:1
(anonymous) @ client.js:22
s @ client.js:1
(anonymous) @ client.js:22
s @ client.js:1
(anonymous) @ client.js:22
s @ client.js:1
(anonymous) @ client.js:24
s @ client.js:1
(anonymous) @ client.js:28
s @ client.js:1
(anonymous) @ client.js:1
(anonymous) @ client.js:1
ExceptionParser.js:171 Uncaught TypeError: Cannot read property 'map' of undefined
    at ExceptionParser.js:171
    at Array.map (<anonymous>)
    at ExceptionParser.value (ExceptionParser.js:170)
    at i (LogTable.js:100)
    at onClick (LogTable.js:142)
    at Object.l (react-dom.production.min.js:14)
    at p (react-dom.production.min.js:14)
    at react-dom.production.min.js:14
    at b (react-dom.production.min.js:15)
    at it (react-dom.production.min.js:52)
(anonymous) @ ExceptionParser.js:171
value @ ExceptionParser.js:170
i @ LogTable.js:100
onClick @ LogTable.js:142
l @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
b @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
lt @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
W @ react-dom.production.min.js:287
N @ react-dom.production.min.js:19
Xt @ react-dom.production.min.js:70
Jt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
U @ react-dom.production.min.js:287
Qt @ react-dom.production.min.js:68
```
</details>

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/logreader/issues/301

**Comment by Prog1563** [comment]
Thanks, @kesselb … Yup, that looks the same. Sorry for the duplicate, didn't know the log reader was its own app 😅
