### ISSUE TITLE
21: fatal error " Value of type null is not callable" in phpseclib

### ISSUE THREAD

**Issue by heldchen** [nextcloud/server#26139]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. upgrade from a previous version to 21.0.0
2. use php-fpm 8.0.3
3. have users use the instance
4. after a while check php error log for errors

### Expected behaviour

Not seeing any fatal errors related to phpseclib

### Actual behaviour

many instances of `PHP Fatal error:  Uncaught Error: Value of type null is not callable in /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Base.php:862` logged

### Server configuration

**Operating system:**

Debian GNU/Linux 10 (buster)

**Web server:**

Apache2

**Database:**

Postgresql13

**PHP version:**

8.0.3 (fpm, from sury.org)

**Nextcloud version:** (see Nextcloud admin page)

21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:**

upgraded from 20.something

**Where did you install Nextcloud from:**

commandline updater.phar

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - calendar: 2.1.3
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - groupfolders: 9.0.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - bruteforcesettings
  - encryption
  - files_external
  - firstrunwizard
  - socialsharing_email
  - survey_client
  - user_ldap
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/",
        "dbtype": "pgsql",
        "version": "21.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "beta",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "CH",
        "app_install_overwrite": [
            "socialsharing_email",
            "bruteforcesettings"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

local

**Are you using encryption:** yes/no

no (at least I don't think so)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

n/a

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[15-Mar-2021 17:13:30 UTC] PHP Fatal error:  Uncaught Error: Value of type null is not callable in /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Base.php:862
Stack trace:
#0 /var/www/nextcloud/lib/private/Security/Crypto.php(100): phpseclib\Crypt\Base->encrypt()
#1 /var/www/nextcloud/lib/private/Session/CryptoSessionData.php(180): OC\Security\Crypto->encrypt()
#2 /var/www/nextcloud/lib/private/Session/CryptoSessionData.php(74): OC\Session\CryptoSessionData->close()
#3 [internal function]: OC\Session\CryptoSessionData->__destruct()
#4 {main}
  thrown in /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Base.php on line 862
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"u52jhtAFkWvWc2r6cuTU","level":4,"time":"2021-03-15T17:13:30+00:00","remoteAddr":"*** pii data removed ***","user":"*** pii data removed ***","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/*** pii data removed ***/","message":{"Exception":"Error","Message":"Value of type null is not callable","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Security/Crypto.php","line":100,"function":"encrypt","class":"phpseclib\\Crypt\\Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Session/CryptoSessionData.php","line":180,"function":"encrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":126,"function":"close","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":103,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":254,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":156,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":182,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":137,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Base.php","Line":862,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux) mirall/3.1.3-20210218.151938.3842d306f-1.0~groovy1 (Nextcloud)","version":"21.0.0.18"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a (most errors are from nextcloud sync clients)
```
</details>

**Comment by ToeiRei** [comment]
I have the exact same problem on the new beta / php 8 / nginx

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by ToeiRei** [comment]
Looks solved to me on my end
