### ISSUE TITLE
phpseclib SSH2.php Fatal ErrorException line 3821

### ISSUE THREAD

**Issue by unamundan** [nextcloud/server#26714]
SYSTEM
------
+ macos 10.13.6 host running
+ ubuntu server 18.04 LTS in VM with
+ nextcloud 15.0.5.3

PHP
---

+ Version: 7.2.15
+ Memory Limit: 512 MB
+ Max Execution Time: 3600
+ Upload max size: 2 GB

DATABASE
--------

+ Type: pgsql
+ Version: PostgreSQL 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit

ISSUE
---

+ Added two (large) SFTP mounts via “External Storage” app

```
root@cloud:~# sudo -u www-data php /var/www/nextcloud/occ files:scan --all
Starting scan for user 1 out of 3 [USERNAME1]
Starting scan for user 2 out of 3 [USERNAME2]
Starting scan for user 3 out of 3 [USERNAME3]
+---------+--------+--------------+
| Folders | Files  | Elapsed time |
+---------+--------+--------------+
| 32863   | 592042 | 03:03:48     |
+---------+--------+--------------+
PHP Fatal error:  Uncaught ErrorException: Connection closed prematurely in /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3821
Stack trace:
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler(1024, 'Connection clos...', '/var/www/nextcl...', 3821, Array)
nextcloud/3rdparty#1 /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3821): user_error('Connection clos...')
nextcloud/3rdparty#2 /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4039): phpseclib\Net\SSH2->_send_binary_packet('\x01\x00\x00\x00\v\x00\x00\x00\x00\x00\x00\x00\x00')
nextcloud/3rdparty#3 /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3102): phpseclib\Net\SSH2->_disconnect(11)
nextcloud/3rdparty#4 /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3146): phpseclib\Net\SFTP->_disconnect(11)
nextcloud/3rdparty#5 /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3162): phpseclib\Net\SSH2->disconnect()
nextcloud/3rdparty#6 [internal function]: phpseclib\Net\SSH2->__destruct()
nextcloud/3rdparty#7 {main}
  thrown in /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3821```

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
