### ISSUE TITLE
apps not install & enable, nextcloud 21.0.3

### ISSUE THREAD

**Issue by beniyas** [nextcloud/server#27792]
Yestaday updated nextcloud 21.0.3

so apps not work
apache-2.4.4 php-8.0.6

for example
As I cannot carry it out from Web

php occ app:install calendar

An unhandled exception has been thrown:
TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /usr/local/apache/htdocs/nextcloud/lib/private/Installer.php:130
Stack trace:
#0 /usr/local/apache/htdocs/nextcloud/lib/private/Installer.php(130): in_array('calendar', '0', true)
#1 /usr/local/apache/htdocs/nextcloud/core/Command/App/Install.php(75): OC\Installer->installApp('calendar', false)
#2 /usr/local/apache/htdocs/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/local/apache/htdocs/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/local/apache/htdocs/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /usr/local/apache/htdocs/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/local/apache/htdocs/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /usr/local/apache/htdocs/nextcloud/console.php(100): OC\Console\Application->run()
#8 /usr/local/apache/htdocs/nextcloud/occ(11): require_once('/usr/local/apac...')
#9 {main}

Please give me advice not to understand where is bad

**Comment by giovanni4517** [comment]
Aktualisierung auf 21.0.3

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.
