### ISSUE TITLE
DAVdroid Address book synchronization failed - Server error while uploading created/modified entries.

### ISSUE THREAD

**Issue by jcgruenhage** [nextcloud/server#2799]
## Core Problem:
Somehow some of the vCards are invalid, they contain more than one REV. That first occurred with Nextcloud 11, I don't know if they were not checked before or if the vCards were correct before, but the problem started to occur with the update to Nextcloud 11. 

Edit: The problem seems to occur on locally edited contacts, so this might be a DAVdroid issue.

### Steps to reproduce
1. Use Nextcloud 10.0.1 for a while.
2. Upgrade to Nextcloud 11.0.0
3. DAVdroid does not sync contacts anymore.

### Workaround
1. Delete the contact that you see in the DAVdroid log.
2. Sync.
3. Recreate the contact.
4. Sync again.
5. Wait for it to reappear with a different contact.
(Happend two times so far, only took a day or so in between.)

### Expected behaviour
The contacts should just continue to sync as before.

### Actual behaviour
The contacts do not sync as before.

### Server configuration
**Operating system**: Fedora 24 Server on the host, Alpine Linux in the Docker container.

**Web server:** Caddy as a reverse proxy, nginx in the Docker container.

**Database:** Postgres

**PHP version:** 7

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated, I had 10.0.1 previously.

**Where did you install Nextcloud from:** [Docker](https://hub.docker.com/r/wonderfall/nextcloud/)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.24
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - twofactor_u2f: 0.1.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - audioplayer
  - bookmarks
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - firstrunwizard
  - templateeditor
  - user_external
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "\/data",
        "apps_paths": [
            {
                "path": "\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "ocadc83b19e7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.jcg.re"
        ],
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "pgsql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "postgres",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "nextcloud",
        "logdateformat": "Y-m-d H:i:s",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_domain": "jcg.re",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.jcg.re",
        "mail_smtpport": "587",
        "auth.bruteforce.protection.enabled": false,
        "loglevel": 1,
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** yes, local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** yes, LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-----------------------------------------------------------------+
| Configuration                 |                                                                 |
+-------------------------------+-----------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                 |
| hasPagedResultSupport         |                                                                 |
| homeFolderNamingRule          |                                                                 |
| lastJpegPhotoLookup           | 0                                                               |
| ldapAgentName                 | cn=admin,dc=ldap,dc=jcg,dc=re                                   |
| ldapAgentPassword             | ***                                                             |
| ldapAttributesForGroupSearch  |                                                                 |
| ldapAttributesForUserSearch   |                                                                 |
| ldapBackupHost                |                                                                 |
| ldapBackupPort                |                                                                 |
| ldapBase                      | dc=ldap,dc=jcg,dc=re                                            |
| ldapBaseGroups                | dc=ldap,dc=jcg,dc=re                                            |
| ldapBaseUsers                 | dc=ldap,dc=jcg,dc=re                                            |
| ldapCacheTTL                  | 5                                                               |
| ldapConfigurationActive       | 1                                                               |
| ldapDynamicGroupMemberURL     |                                                                 |
| ldapEmailAttribute            | mail                                                            |
| ldapExperiencedAdmin          | 0                                                               |
| ldapExpertUUIDGroupAttr       |                                                                 |
| ldapExpertUUIDUserAttr        |                                                                 |
| ldapExpertUsernameAttr        |                                                                 |
| ldapGroupDisplayName          | cn                                                              |
| ldapGroupFilter               | (&(|(objectclass=posixGroup))(|(cn=family)(cn=root)(cn=users))) |
| ldapGroupFilterGroups         | family;root;users                                               |
| ldapGroupFilterMode           | 0                                                               |
| ldapGroupFilterObjectclass    | posixGroup                                                      |
| ldapGroupMemberAssocAttr      | memberUid                                                       |
| ldapHost                      | openldap                                                        |
| ldapIgnoreNamingRules         |                                                                 |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)))                  |
| ldapLoginFilterAttributes     | uid                                                             |
| ldapLoginFilterEmail          | 0                                                               |
| ldapLoginFilterMode           | 0                                                               |
| ldapLoginFilterUsername       | 0                                                               |
| ldapNestedGroups              | 0                                                               |
| ldapOverrideMainServer        |                                                                 |
| ldapPagingSize                | 500                                                             |
| ldapPort                      | 389                                                             |
| ldapQuotaAttribute            |                                                                 |
| ldapQuotaDefault              |                                                                 |
| ldapTLS                       | 0                                                               |
| ldapUserDisplayName           | cn                                                              |
| ldapUserDisplayName2          |                                                                 |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                  |
| ldapUserFilterGroups          |                                                                 |
| ldapUserFilterMode            | 0                                                               |
| ldapUserFilterObjectclass     | inetOrgPerson                                                   |
| ldapUuidGroupAttribute        | auto                                                            |
| ldapUuidUserAttribute         | auto                                                            |
| turnOffCertCheck              | 0                                                               |
| turnOnPasswordChange          | 0                                                               |
| useMemberOfToDetectMembership | 1                                                               |
+-------------------------------+-----------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** DAVdroid I guess.

**Operating system:** CyanogenMod 14.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```   
No idea where to find this.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```  
{"reqId":"mhkF3jSP19cXvRXW1lGs","remoteAddr":"172.19.0.12","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 415 Validation error in vCard: REV MUST NOT appear more than once in a VCARD component\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(294): Sabre\\\\CardDAV\\\\Plugin->validateVCard('BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#1 [internal function]: Sabre\\\\CardDAV\\\\Plugin->beforeWriteContent('addressbooks\\\/us...', Object(Sabre\\\\CardDAV\\\\Card), 'BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#2 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1104): Sabre\\\\Event\\\\EventEmitter->emit('beforeWriteCont...', Array)\\n#4 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('addressbooks\\\/us...', 'BEGIN:VCARD\\\\r\\\\nVE...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/nextcloud\\\/remote.php(165): require_once('\\\/nextcloud\\\/apps...')\\n#12 {main}\",\"File\":\"\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":397,\"User\":\"3aee88e4-3657-1036-85e2-8bb479b1dffc\"}","level":4,"time":"2016-12-21 11:41:12","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/3aee88e4-3657-1036-85e2-8bb479b1dffc\/contacts\/a0d10448-18dd-407b-9074-96a33cb5d95d.vcf","user":"3aee88e4-3657-1036-85e2-8bb479b1dffc","version":"11.0.0.10"}

```
</details>  

#### DAVdroid log
<details>
<summary>DAVdroid log</summary>

```  
SYNCHRONIZATION INFO
Synchronization phase: 4
Account name: me@jcg.re
Authority: com.android.contacts

HTTP REQUEST:
PUT /remote.php/dav/addressbooks/users/3aee88e4-3657-1036-85e2-8bb479b1dffc/contacts/a0d10448-18dd-407b-9074-96a33cb5d95d.vcf
If-Match: "a5eabcd512001b163f64e1c06176d5f7"

BEGIN:VCARD[CR][LF]
VERSION:4.0[CR][LF]
PRODID:+//IDN bitfire.at//DAVdroid/1.3.4.1-ose vcard4android ez-vcard/0.10.[CR][LF]
 0[CR][LF]
REV;VALUE=timestamp:2016-12-14T09:41:19.164Z[CR][LF]
UID:a0d10448-18dd-407b-9074-96a33cb5d95d[CR][LF]
FN:***REMOVED SENSITIVE VALUE***[CR][LF]
N:***REMOVED SENSITIVE VALUE***[CR][LF]
TEL;TYPE=cell:***REMOVED SENSITIVE VALUE***[CR][LF]
TEL;TYPE=home:***REMOVED SENSITIVE VALUE***[CR][LF]
EMAIL;TYPE=home:***REMOVED SENSITIVE VALUE***[CR][LF]
IMPP;TYPE=home:***REMOVED SENSITIVE VALUE***[CR][LF]
REV:20161221T104112Z[CR][LF]
END:VCARD[CR][LF]


HTTP RESPONSE:
h2 415 
cache-control: no-store, no-cache, must-revalidate
content-length: 286
content-security-policy: default-src 'none';
content-type: application/xml; charset=utf-8
date: Wed, 21 Dec 2016 10:41:12 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: nginx

<?xml version="1.0" encoding="utf-8"?>[LF]
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]
  <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>[LF]
  <s:message>Validation error in vCard: REV MUST NOT appear more than once in a VCARD component</s:message>[LF]
</d:error>[LF]


EXCEPTION:
at.bitfire.dav4android.exception.HttpException: 415 
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:318)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:291)
	at at.bitfire.dav4android.DavResource.put(DavResource.java:202)
	at at.bitfire.davdroid.syncadapter.SyncManager.uploadDirty(SyncManager.java:317)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.java:147)
	at at.bitfire.davdroid.syncadapter.ContactsSyncAdapterService$ContactsSyncAdapter.onPerformSync(ContactsSyncAdapterService.java:66)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

SOFTWARE INFORMATION
DAVdroid version: 1.3.4.1-ose (128) Wed Nov 16 10:26:01 GMT+01:00 2016
Installed from: com.android.packageinstaller
JB Workaround installed: no

CONFIGURATION
System-wide synchronization: automatically
Account: me@jcg.re
  Address book sync. interval: 240 min
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: manually
  WiFi only: false
  [CardDAV] Contact group method: CATEGORIES
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true

SQLITE DUMP
android_metadata
	|  locale |
	|  en_US |
----------
settings
	|  setting | value |
	|  hint_OpenTasksNotInstalled | 0 |
	|  distrustSystemCerts | 0 |
----------
services
	|  _id | accountName | service | principal |
	|  1 | me@jcg.re | carddav | https://nextcloud.jcg.re/remote.php/dav/principals/users/3aee88e4-3657-1036-85e2-8bb479b1dffc/ |
	|  2 | me@jcg.re | caldav | https://nextcloud.jcg.re/remote.php/dav/principals/users/3aee88e4-3657-1036-85e2-8bb479b1dffc/ |
----------
sqlite_sequence
	|  name | seq |
	|  services | 2 |
	|  homesets | 2 |
	|  collections | 3 |
----------
homesets
	|  _id | serviceID | url |
	|  1 | 1 | https://nextcloud.jcg.re/remote.php/dav/addressbooks/users/3aee88e4-3657-1036-85e2-8bb479b1dffc/ |
	|  2 | 2 | https://nextcloud.jcg.re/remote.php/dav/calendars/3aee88e4-3657-1036-85e2-8bb479b1dffc/ |
----------
collections
	|  _id | serviceID | url | readOnly | displayName | description | color | timezone | supportsVEVENT | supportsVTODO | sync |
	|  1 | 1 | https://nextcloud.jcg.re/remote.php/dav/addressbooks/users/3aee88e4-3657-1036-85e2-8bb479b1dffc/contacts/ | 0 | Contacts | <null> | <null> | <null> | <null> | <null> | 1 |
	|  2 | 2 | https://nextcloud.jcg.re/remote.php/dav/calendars/3aee88e4-3657-1036-85e2-8bb479b1dffc/contact_birthdays/ | 1 | Contact birthdays | <null> | -54 | <null> | 1 | 1 | 1 |
	|  3 | 2 | https://nextcloud.jcg.re/remote.php/dav/calendars/3aee88e4-3657-1036-85e2-8bb479b1dffc/personal/ | 0 | Personal | <null> | <null> | <null> | 1 | 1 | 1 |
----------

SYSTEM INFORMATION
Android version: 7.1.1 (OnePlus3-userdebug 7.1.1 NMF26Q 76459f7268 test-keys)
Device: OnePlus ONEPLUS A3003 (OnePlus3)

```
</details>

**Comment by jcgruenhage** [comment]
Searched in the wrong place. Although nextcloud/server has not had an issue about this, there already is an issue in nextcloud/contacts.
