### ISSUE TITLE
Found error in code. Pls check

### ISSUE THREAD

**Issue by lamnb** [nextcloud/server#28058]
Hi,
At the time I try do re-scan my all files (occ files:scan --all) . this error appeared:
It looks the SQL command can not be completed because of lacking (') in this words: WHERE `filecache`.`parent` = ? 
The correction should be: WHERE `filecache`.`parent` = `?`

Pls check.
Thank you.

Exception during scan: An exception occurred while executing 'SELECT `filecache`.`fileid`, `storage`, `path`, `path_hash`, `filecache`.`parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`, `metadata_etag`, `creation_time`, `upload_time` FROM `oc_filecache` `filecache` LEFT JOIN `oc_filecache_extended` `fe` ON `filecache`.`fileid` = `fe`.`fileid` WHERE `filecache`.`parent` = ? ORDER BY `name` ASC' with params [43293]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
#0 /snap/nextcloud/28392/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /snap/nextcloud/28392/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(149): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /snap/nextcloud/28392/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(914): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT `filecac...', Array)
#3 /snap/nextcloud/28392/htdocs/lib/private/DB/Connection.php(202): Doctrine\DBAL\Connection->executeQuery('SELECT `filecac...', Array, Array, NULL)
#4 /snap/nextcloud/28392/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery('SELECT `filecac...', Array, Array)
#5 /snap/nextcloud/28392/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(248): Doctrine\DBAL\Query\QueryBuilder->execute()
#6 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Cache.php(225): OC\DB\QueryBuilder\QueryBuilder->execute()
#7 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(362): OC\Files\Cache\Cache->getFolderContentsById(43293)
#8 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(407): OC\Files\Cache\Scanner->getExistingChildren(43293)
#9 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('files/My_Reposi...', true, 3, 43293, true, 0)
#10 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 43293, true)
#11 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 41977, true)
#12 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 28101, true)
#13 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 27329, true)
#14 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 27323, true)
#15 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 20647, true)
#16 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files/My_Reposi...', true, 3, 185, true)
#17 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('files', true, 3, 2, true)
#18 /snap/nextcloud/28392/htdocs/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren('', true, 3, 1, true)
#19 /snap/nextcloud/28392/htdocs/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan('', true, 3)
#20 /snap/nextcloud/28392/htdocs/apps/files/lib/Command/Scan.php(152): OC\Files\Utils\Scanner->scan('/lamnb', true, NULL)
#21 /snap/nextcloud/28392/htdocs/apps/files/lib/Command/Scan.php(208): OCA\Files\Command\Scan->scanFiles('lamnb', '/lamnb', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#22 /snap/nextcloud/28392/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /snap/nextcloud/28392/htdocs/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /snap/nextcloud/28392/htdocs/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /snap/nextcloud/28392/htdocs/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /snap/nextcloud/28392/htdocs/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /snap/nextcloud/28392/htdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /snap/nextcloud/28392/htdocs/console.php(100): OC\Console\Application->run()
#29 /snap/nextcloud/28392/htdocs/occ(11): require_once('/snap/nextcloud...')
#30 {main}

**Comment by szaimen** [comment]
Hi there, please dill out the issue remplate. Thanks!
