### ISSUE TITLE
File is lock in Nextcloud 11 with Redis filelocking turned on

### ISSUE THREAD

**Issue by KKyang** [nextcloud/server#2813]
### Steps to reproduce
1. Upload a folder with 13GB of files
2. Nextcloud accidentally crashed
3. Restart Nextcloud server

### Expected behaviour
Able to re-upload files

### Actual behaviour
File is locked by Redis

**Note**: FAQ in the Nextcloud forum does not work. File still locked after deleting the table.

### Server configuration
**Operating system**: Ubuntu 14.04 (kernel 4.4.0-34)

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 11

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from the latest version of Nextcloud 10

**Where did you install Nextcloud from:** Nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Collabora Online
Anouncement Center

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '',
  'dbtype' => 'mysql',
  'version' => '9.1.2.2',
  'dbname' => '',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 0,
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpsecure' => 'ssl',
  'mail_smtptimeout' => 30,
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'overwritewebroot' => '',
  'mail_smtpport' => '465',
  'secret' => 
  'forceSSLforSubdomains' => true,
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'updatechecker' => true,
  'updater.release.channel' => 'production',
  'appstoreenabled' => true,
  'appstore.experimental.enabled' => true,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'updater.secret' => ,
);
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:**  No

### Client configuration
**Browser:** Firefox 50.1.0

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Exception while scanning: "files/789fce897dc6d415e3e99090cd979c4e" is locked
#0 /var/www/nextcloud/lib/private/Files/Storage/Common.php(680): OC\Lock\MemcacheLockingProvider->acquireLock('files/789fce897...', 2)
#1 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(588): OC\Files\Storage\Common->acquireLock('files/lab resou...', 2, Object(OC\Lock\MemcacheLockingProvider))
#2 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(588): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/lab resou...', 2, Object(OC\Lock\MemcacheLockingProvider))
#3 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(588): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/lab resou...', 2, Object(OC\Lock\MemcacheLockingProvider))
#4 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(395): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/lab resou...', 2, Object(OC\Lock\MemcacheLockingProvider))
#5 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(588): OCA\Files_Sharing\SharedStorage->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#6 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(316): OC\Files\Storage\Wrapper\Wrapper->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#7 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(196): OC\Files\Cache\Scanner->scan('', true, 3)
#8 /var/www/nextcloud/apps/files/lib/Command/Scan.php(159): OC\Files\Utils\Scanner->scan('/R05631013')
#9 /var/www/nextcloud/apps/files/lib/Command/Scan.php(227): OCA\Files\Command\Scan->scanFiles('R05631013', '/R05631013', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#10 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/core/Command/Base.php(161): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(818): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#17 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#18 {main}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by KKyang** [comment]
Use 

```
sudo redis-cli flushall
```

does not help either.

**Comment by KKyang** [comment]
Problem solved by 
1. Put the server in maintenance mode.
2. Removing all the uploaded data directly from terminal
3. Flush the Redis server cache
4. Turn off maintenance mode
5. Rescan all files
6. Re-upload all the files with terminal
7. Rescan all files

**Comment by nickvergessen** [comment]
About the error:
> File entry could not be inserted with insertIfNotExist

https://docs.nextcloud.com/server/11/admin_manual/configuration_database/linux_database_configuration.html#database-read-commited-transaction-isolation-level

Other then that, glad to here you found a way to continue.
