### ISSUE TITLE
occ app:update error: Argument 3 passed to OC_App::checkAppDependencies() must be of the type array, null given, called in /path/to/nextcloud/lib/private/legacy/OC_App.php on line 989 and defined in /path/to/nextcloud/lib/private/legacy/OC_App.php:1185

### ISSUE THREAD

**Issue by akwala** [nextcloud/server#28293]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update an app using `occ app:update
2. This error occurs with most apps in the /apps directory.

### Expected behaviour
The app updates without error.

### Actual behaviour
See https://help.nextcloud.com/t/typeerror-argument-2-passed-to-oc-app-executerepairsteps-must-be-of-the-type-array-null-given-when-updating-apps/87295.

Looks similar to #8964

Updating apps using occ (command line) results in the following “unhandled exception.” It seems to leave the apps in a state that keeps them from appearing in the occ app:listlisting as well as in Your Apps on the admin console. Examples of apps whose updates result in this error:  Notes, Appointments, Contacts. The following happened withe the latest updates of the respective apps.

```
contacts new version available: 4.0.1
An unhandled exception has been thrown:
TypeError: Argument 3 passed to OC_App::checkAppDependencies() must be of the type array, null given, called in /path/to/nextcloud/lib/private/legacy/OC_App.php on line 989 and defined in /path/to/nextcloud/lib/private/legacy/OC_App.php:1185
Stack trace:
#0 /path/to/nextcloud/lib/private/legacy/OC_App.php(989): OC_App::checkAppDependencies(Object(OC\AllConfig), Object(OC\L10N\LazyL10N), NULL, false)
#1 /path/to/nextcloud/lib/private/Installer.php(202): OC_App::updateApp('contacts')
#2 /path/to/nextcloud/core/Command/App/Update.php(115): OC\Installer->updateAppstoreApp('contacts', false)
#3 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Update), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/to/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /path/to/nextcloud/console.php(99): OC\Console\Application->run()
#9 /path/to/nextcloud/occ(11): require_once('/path/to/nextcloud...')
#10 {main}

notes new version available: 4.1.1
An unhandled exception has been thrown:
TypeError: Argument 3 passed to OC_App::checkAppDependencies() must be of the type array, null given, called in /path/to/nextcloud/lib/private/legacy/OC_App.php on line 989 and defined in /path/to/nextcloud/lib/private/legacy/OC_App.php:1185
Stack trace:
#0 /path/to/nextcloud/lib/private/legacy/OC_App.php(989): OC_App::checkAppDependencies(Object(OC\AllConfig), Object(OC\L10N\LazyL10N), NULL, false)
#1 /path/to/nextcloud/lib/private/Installer.php(202): OC_App::updateApp('notes')
#2 /path/to/nextcloud/core/Command/App/Update.php(115): OC\Installer->updateAppstoreApp('notes', false)
#3 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Update), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /path/to/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/to/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /path/to/nextcloud/console.php(99): OC\Console\Application->run()
#9 /path/to/nextcloud/occ(11): require_once('/path/to/nc...')
#10 {main}
```
I work around this by manually removing the app directory in apps/ and installing the app anew using occ app:install which succeeds.

### Server configuration

**Operating system:**
FreeBSD 12.2-RELEASE-p2
**Web server:**
Apache 2.4
**Database:**
mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for FreeBSD12.2 (amd64)
**PHP version:**
PHP 7.3
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 22.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nectcloud 21
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-22.0.0.tar.bz2
Manual, command line upgrade
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>
**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_audit: 1.11.0
  - apporder: 0.13.0
  - bookmarks: 4.4.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.1
  - circles: 22.0.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.9
  - metadata: 0.14.0
  - news: 16.0.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - phonetrack: 0.6.9
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - qownnotesapi: 21.7.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - tasks: 0.14.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
 php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/path\/to\/nextcloudtemp",
        "log_type": "file",
        "logfile": "\/path\/to\/data\/nextcloud.log",
        "logfilemode": 432,
        "loglevel": 2,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "log_rotate_size": 10485760,
        "debug": false,
        "dbtype": "mysql",
        "version": "22.0.0.11",
        "overwrite.cli.url": "https:\/\/www.example.com\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "xx_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "groupA",
            "groupB"
        ],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "has_rebuilt_cache": true,
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
                                                          
  There are no commands defined in the "ldap" namespace.  
                                                          
```
</details>

### Client configuration
**Browser:**
Firefox, Brave/Chromium
**Operating system:**
Kubuntu 20.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[issue not related to web server]
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[attached]
```
[nextcloud.log](https://github.com/nextcloud/server/files/6919729/nextcloud.log)

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
[issue not related to web/HTTP requests]
```

</details>

**Comment by szaimen** [comment]
This sounds like an issue that could be introduce by an installed app.
You could try to disable app for app until it works again.
Apart from that this sounds like a configuration/setup issue.
So please continue the discussion on https://help.nextcloud.com
Thanks!
