### ISSUE TITLE
External storage swift cyrillic filename

### ISSUE THREAD

**Issue by Nerkill** [nextcloud/server#2856]
### Steps to reproduce
1. Add OpenStack Swift as external storage
2. Create folder with cyrillic symbols

### Expected behaviour
Folder creation

### Actual behaviour
Could not create folder

### Server configuration
**Operating system**: Debian 9

**Web server:** Apache 2.4.23

**Database:** Postgresql 9.6

**PHP version:** 7.0.13

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.4.1
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - music: 0.3.13
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - ownbackup: 16.11.0
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - rainloop: 4.26.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ochrc4k1sker",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nerkill.com"
        ],
        "datadirectory": "\/var\/www\/nerkill.com\/data",
        "overwrite.cli.url": "https:\/\/nerkill.com",
        "dbtype": "pgsql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Moscow",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "nerkill.com",
        "appstore.experimental.enabled": true,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** openstack swift

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+--------------------------------------+
| Configuration                 |                                      |
+-------------------------------+--------------------------------------+
| hasMemberOfFilterSupport      | 0                                    |
| hasPagedResultSupport         |                                      |
| homeFolderNamingRule          |                                      |
| lastJpegPhotoLookup           | 0                                    |
| ldapAgentName                 | cn=reader,dc=nerkill,dc=com          |
| ldapAgentPassword             | ***                                  |
| ldapAttributesForGroupSearch  |                                      |
| ldapAttributesForUserSearch   |                                      |
| ldapBackupHost                |                                      |
| ldapBackupPort                |                                      |
| ldapBase                      | ou=People,dc=nerkill,dc=com          |
| ldapBaseGroups                | ou=People,dc=nerkill,dc=com          |
| ldapBaseUsers                 | ou=People,dc=nerkill,dc=com          |
| ldapCacheTTL                  | 600                                  |
| ldapConfigurationActive       | 1                                    |
| ldapDynamicGroupMemberURL     |                                      |
| ldapEmailAttribute            | mail                                 |
| ldapExperiencedAdmin          | 0                                    |
| ldapExpertUUIDGroupAttr       |                                      |
| ldapExpertUUIDUserAttr        |                                      |
| ldapExpertUsernameAttr        | uid                                  |
| ldapGroupDisplayName          | cn                                   |
| ldapGroupFilter               |                                      |
| ldapGroupFilterGroups         |                                      |
| ldapGroupFilterMode           | 0                                    |
| ldapGroupFilterObjectclass    |                                      |
| ldapGroupMemberAssocAttr      | uniqueMember                         |
| ldapHost                      | localhost                            |
| ldapIgnoreNamingRules         |                                      |
| ldapLoginFilter               | (&(|(objectclass=person))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                      |
| ldapLoginFilterEmail          | 0                                    |
| ldapLoginFilterMode           | 0                                    |
| ldapLoginFilterUsername       | 1                                    |
| ldapNestedGroups              | 0                                    |
| ldapOverrideMainServer        |                                      |
| ldapPagingSize                | 500                                  |
| ldapPort                      | 389                                  |
| ldapQuotaAttribute            |                                      |
| ldapQuotaDefault              |                                      |
| ldapTLS                       | 0                                    |
| ldapUserDisplayName           | cn                                   |
| ldapUserDisplayName2          |                                      |
| ldapUserFilter                | (|(objectclass=person))              |
| ldapUserFilterGroups          |                                      |
| ldapUserFilterMode            | 0                                    |
| ldapUserFilterObjectclass     | person                               |
| ldapUuidGroupAttribute        | auto                                 |
| ldapUuidUserAttribute         | auto                                 |
| turnOffCertCheck              | 0                                    |
| turnOnPasswordChange          | 0                                    |
| useMemberOfToDetectMembership | 1                                    |
+-------------------------------+--------------------------------------+

```
</details>

### Client configuration
**Browser:** Chrome 55

**Operating system:** Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>
```
empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"cPnwxvvLooUIBfbGrQJD","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"Client error response\\n[status code] 400\\n[reason phrase] Bad request\\n[url] https:\\\/\\\/storage.gra1.cloud.ovh.net\\\/v1\\\/AUTH_aa54720ae8de43e09a0be2e0da74035e\\\/Test\\\/\\u041d\\u043e\\u0432\\u0430\\u044f%20\\u043f\\u0430\\u043f\\u043a\\u0430\\\/\",\"Exception\":\"Guzzle\\\\Http\\\\Exception\\\\ClientErrorResponseException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(145): Guzzle\\\\Http\\\\Exception\\\\BadResponseException::factory(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response))\\n#1 [internal function]: Guzzle\\\\Http\\\\Message\\\\Request::onRequestError(Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#2 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(174): call_user_func(Array, Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#3 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(43): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\\\Common\\\\Event))\\n#4 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(589): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('request.error', Object(Guzzle\\\\Common\\\\Event))\\n#5 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(378): Guzzle\\\\Http\\\\Message\\\\Request->processResponse(Array)\\n#6 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/EntityEnclosingRequest.php(49): Guzzle\\\\Http\\\\Message\\\\Request->setState('complete', Array)\\n#7 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(286): Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest->setState('complete', Array)\\n#8 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(244): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Curl\\\\CurlHandle), Array)\\n#9 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(227): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processMessages()\\n#10 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(211): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->executeHandles()\\n#11 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(105): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->perform()\\n#12 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMultiProxy.php(91): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->send()\\n#13 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Client.php(282): Guzzle\\\\Http\\\\Curl\\\\CurlMultiProxy->send()\\n#14 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(198): Guzzle\\\\Http\\\\Client->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#15 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/rackspace\\\/php-opencloud\\\/lib\\\/OpenCloud\\\/ObjectStore\\\/Resource\\\/Container.php(380): Guzzle\\\\Http\\\\Message\\\\Request->send()\\n#16 \\\/var\\\/www\\\/nerkill.com\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Swift.php(203): OpenCloud\\\\ObjectStore\\\\Resource\\\\Container->uploadObject('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...', '', Array)\\n#17 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Swift->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#18 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(102): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#19 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#20 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(84): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#21 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encoding.php(130): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#22 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encoding->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#23 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#24 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#25 \\\/var\\\/www\\\/nerkill.com\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(62): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#26 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/View.php(1124): OCA\\\\FilesAccessControl\\\\StorageWrapper->mkdir('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#27 \\\/var\\\/www\\\/nerkill.com\\\/lib\\\/private\\\/Files\\\/View.php(266): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/Test\\\/\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1...', Array)\\n#28 \\\/var\\\/www\\\/nerkill.com\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(166): OC\\\\Files\\\\View->mkdir('\\\/Test\\\/\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1...')\\n#29 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1186): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createDirectory('\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F \\\\xD0\\\\xBF\\\\xD0\\\\xB0...')\\n#30 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Test\\\/\\\\xD0\\\\x9D\\\\xD0\\\\xBE\\\\xD0\\\\xB2\\\\xD0\\\\xB0\\\\xD1\\\\x8F...', Object(Sabre\\\\DAV\\\\MkCol))\\n#31 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#32 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#33 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#34 \\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#35 \\\/var\\\/www\\\/nerkill.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#36 \\\/var\\\/www\\\/nerkill.com\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nerkil...')\\n#37 {main}\",\"File\":\"\\\/var\\\/www\\\/nerkill.com\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Exception\\\/BadResponseException.php\",\"Line\":43,\"User\":\"nerkill\"}","level":4,"time":"2016-12-25T13:03:07+03:00","method":"MKCOL","url":"\/remote.php\/webdav\/Test\/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BF%D0%B0%D0%BF%D0%BA%D0%B0","user":"nerkill","version":"11.0.0.10"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
a) The javascript console log
jquery-migrate.min.js?v=355b29e…:2 JQMIGRATE: Migrate is installed, version 1.4.0
fileactions.js?v=355b29e…:769 FileActions.register() is deprecated, please use OCA.Files.fileActions.register() instead ["audio", "Play", 1, "", function]
window.FileActions.register @ fileactions.js?v=355b29e…:769
(anonymous) @ fileactions.js?v=355b29e…:13
j @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
I @ jquery.js:3433
fileactions.js?v=355b29e…:769 FileActions.register() is deprecated, please use OCA.Files.fileActions.register() instead ["application/ogg", "Play", 1, "", function]
window.FileActions.register @ fileactions.js?v=355b29e…:769
(anonymous) @ fileactions.js?v=355b29e…:14
j @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
I @ jquery.js:3433
client.js?v=355b29e…:181 MKCOL https://nerkill.com/remote.php/webdav/Test/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BF%D0%B0%D0%BF%D0%BA%D0%B0 500 (Internal Server 
Error)
request @ client.js?v=355b29e…:181
_simpleCall @ client.js?v=355b29e…:643
createDirectory @ client.js?v=355b29e…:666
createDirectory @ filelist.js?v=355b29e…:2217
actionHandler @ newfilemenu.js?v=355b29e…:72
(anonymous) @ newfilemenu.js?v=355b29e…:192
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
```
</details>

**Comment by MariusBluem** [comment]
Could you please provide us some logs? 🤔

**Comment by Nerkill** [comment]
no more logs
possible error due URL encoded %D0%9D%D0%BE...
I have no idea

**Comment by MorrisJobke** [comment]
@icewind1991 Could you check this and maybe add an integration test for this for external storage?

**Comment by MorrisJobke** [comment]
Swift got a major update with version 12 and the upcoming 14 will use completely different library. I will close this for now, because we didn't received similar problems since then.
