### ISSUE TITLE
Root directories not listed after update to NC 11

### ISSUE THREAD

**Issue by despens** [nextcloud/server#2862]
### Steps to reproduce
1. Update to NC 11 via tar.bz download
2. Update process runs without errors
3. Root directories stay empty in files app

### Expected behaviour
Root directories should be listed

### Actual behaviour
Root directories are displayed empty, notification: `This directory is unavailable, please check the logs or contact the administrator`

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26

**Database:** Server version: 10.0.28-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** 11.0.0 stable

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 10.0.2

**Where did you install Nextcloud from:** manual install from tar.bz

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_markdown: 1.0.0
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_pdfviewer
  - files_retention
  - user_ldap
  - user_saml
```
</details>

**Are you using external storage, if yes which one:** some users have sftp external storage, but this affects all users

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Nothing found in apache error log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Error	remote	Error: Call to a member function getCache() on null

    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php - line 296: OCA\Files_Sharing\Cache->getCache()
    /var/www/nextcloud/lib/private/Files/View.php - line 1687: OC\Files\Cache\Wrapper\CacheJail->getPathById(212215)
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 117: OC\Files\View->getPath(212215)
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 453: OCA\Files_Sharing\SharedStorage->init()
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 449: OCA\Files_Sharing\SharedStorage->getWrapperStorage()
    [internal function] OCA\Files_Sharing\SharedStorage->getSourceStorage()
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 501: call_user_func_array(Array, Array)
    /var/www/nextcloud/apps/files_sharing/lib/Cache.php - line 69: OC\Files\Storage\Wrapper\Wrapper->__call('getSourceStorag...', Array)
    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php - line 296: OCA\Files_Sharing\Cache->getCache()
    /var/www/nextcloud/lib/private/Files/View.php - line 1687: OC\Files\Cache\Wrapper\CacheJail->getPathById(210445)
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 117: OC\Files\View->getPath(210445)
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 453: OCA\Files_Sharing\SharedStorage->init()
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 449: OCA\Files_Sharing\SharedStorage->getWrapperStorage()
    [internal function] OCA\Files_Sharing\SharedStorage->getSourceStorage()
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 501: call_user_func_array(Array, Array)
    /var/www/nextcloud/apps/files_sharing/lib/Cache.php - line 69: OC\Files\Storage\Wrapper\Wrapper->__call('getSourceStorag...', Array)
    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php - line 296: OCA\Files_Sharing\Cache->getCache()
    /var/www/nextcloud/lib/private/Files/View.php - line 1687: OC\Files\Cache\Wrapper\CacheJail->getPathById(206443)
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 117: OC\Files\View->getPath(206443)
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 453: OCA\Files_Sharing\SharedStorage->init()
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 490: OCA\Files_Sharing\SharedStorage->getWrapperStorage()
    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 143: OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OCP\\Files\\IHom...')
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 490: OCA\Files_Sharing\SharedStorage->instanceOfStorage('\\OCP\\Files\\IHom...')
    /var/www/nextcloud/lib/private/Files/FileInfo.php - line 310: OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OCP\\Files\\IHom...')
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Node.php - line 297: OC\Files\FileInfo->isMounted()
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php - line 298: OCA\DAV\Connector\Sabre\Node->getDavPermissions()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php - line 98: OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}()
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php - line 304: Sabre\DAV\PropFind->handle('{http //ownclou...', Object(Closure))
    [internal function] OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties(Object(Sabre\DAV\PropFind), Object(OCA\DAV\Connector\Sabre\Directory))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1035: Sabre\Event\EventEmitter->emit('propFind', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 955: Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OCA\DAV\Connector\Sabre\Directory))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 336: Sabre\DAV\Server->getPropertiesForPath('', Array, 1)
    [internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PROPFIND', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}
```
</details>

**Comment by despens** [comment]
I noticed the same error showing up when trying to invoke nextant: `Error: Call to a member function getCache() on null in /var/www/nextcloud/apps/files_sharing/lib/Cache.php:69`

<details>
<summary>Nextant error log on command line</summary>

```
# sudo -u www-data php occ nextant:index
nextant v1.0.1

* Extracting files:

/user1                           0/     0 [>---------------------------]   0% 
                                                   
An unhandled exception has been thrown:
Error: Call to a member function getCache() on null in /var/www/nextcloud/apps/files_sharing/lib/Cache.php:69
Stack trace:
#0 /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(296): OCA\Files_Sharing\Cache->getCache()
#1 /var/www/nextcloud/lib/private/Files/View.php(1687): OC\Files\Cache\Wrapper\CacheJail->getPathById(212215)
#2 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(117): OC\Files\View->getPath(212215)
#3 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(453): OCA\Files_Sharing\SharedStorage->init()
#4 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(449): OCA\Files_Sharing\SharedStorage->getWrapperStorage()
#5 [internal function]: OCA\Files_Sharing\SharedStorage->getSourceStorage()
#6 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(501): call_user_func_array(Array, Array)
#7 /var/www/nextcloud/apps/files_sharing/lib/Cache.php(69): OC\Files\Storage\Wrapper\Wrapper->__call('getSourceStorag...', Array)
#8 /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(296): OCA\Files_Sharing\Cache->getCache()
#9 /var/www/nextcloud/lib/private/Files/View.php(1687): OC\Files\Cache\Wrapper\CacheJail->getPathById(210445)
#10 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(117): OC\Files\View->getPath(210445)
#11 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(453): OCA\Files_Sharing\SharedStorage->init()
#12 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(449): OCA\Files_Sharing\SharedStorage->getWrapperStorage()
#13 [internal function]: OCA\Files_Sharing\SharedStorage->getSourceStorage()
#14 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(501): call_user_func_array(Array, Array)
#15 /var/www/nextcloud/apps/files_sharing/lib/Cache.php(69): OC\Files\Storage\Wrapper\Wrapper->__call('getSourceStorag...', Array)
#16 /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(296): OCA\Files_Sharing\Cache->getCache()
#17 /var/www/nextcloud/lib/private/Files/View.php(1687): OC\Files\Cache\Wrapper\CacheJail->getPathById(206443)
#18 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(117): OC\Files\View->getPath(206443)
#19 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(453): OCA\Files_Sharing\SharedStorage->init()
#20 /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php(449): OCA\Files_Sharing\SharedStorage->getWrapperStorage()
#21 [internal function]: OCA\Files_Sharing\SharedStorage->getSourceStorage()
#22 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(501): call_user_func_array(Array, Array)
#23 /var/www/nextcloud/apps/files_sharing/lib/Cache.php(69): OC\Files\Storage\Wrapper\Wrapper->__call('getSourceStorag...', Array)
#24 /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(210): OCA\Files_Sharing\Cache->getCache()
#25 [internal function]: OC\Files\Cache\Wrapper\CacheJail->search('%%')
#26 /var/www/nextcloud/lib/private/Files/Node/Folder.php(247): call_user_func_array(Array, Array)
#27 /var/www/nextcloud/lib/private/Files/Node/Folder.php(187): OC\Files\Node\Folder->searchCommon('search', Array)
#28 /var/www/nextcloud/apps/nextant/lib/Service/FileService.php(346): OC\Files\Node\Folder->search('')
#29 /var/www/nextcloud/apps/nextant/lib/Command/Index.php(262): OCA\Nextant\Service\FileService->getFilesPerUserId('/files', Array)
#30 /var/www/nextcloud/apps/nextant/lib/Command/Index.php(205): OCA\Nextant\Command\Index->indexesFiles(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\Nextant\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/nextcloud/core/Command/Base.php(161): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/nextcloud/3rdparty/symfony/console/Application.php(818): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Nextant\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#38 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#39 {main}
```
</details>

**Comment by despens** [comment]
The nextcloud android app shows users' root directories just fine. I wonder what's wrong with the browser view here.

**Comment by nickvergessen** [comment]
Same issue as #3110 I will close this one, since the other one already has some mentions in it.
