### ISSUE TITLE
mariadb problems uploading files after upgrade to 22.1.1

### ISSUE THREAD

**Issue by thijsjek** [nextcloud/server#28634]
### Steps to reproduce
1. upgraded 22.0.1 to 22.1.1
2. make upload photo
3. 

### Expected behaviour
i have automatic upload enabled from android phone, just upload without warnings/crashing the server.

### Actual behaviour
photos are not directly uploaded anymore after upgrade to 22.1.1. after flooding the log nextcloud & mysql restart. pictures are eventually uploaded

### Server configuration

**Operating system:**
FREEBSD 12

**Web server:**
Apache

**Database:**
MariaDB
**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
22.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
22.0.1

**Where did you install Nextcloud from:**
[https://www.samueldowling.com/2020/07/24/install-nextcloud-on-freenas-iocage-jail-with-hardened-security/](url)

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/private/RedisFactory.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/RedisFactory.php] => Array
                        (
                            [expected] => 82e3c6edd20a84764a25b70c45f2a21923f5fd81987d7456ba93c8c9cc358d1457d10d8f085f82c9a5aef46e90f90032d8f55a1baa7cade4718432ad6ddbc95b
                            [current] => 7843cc64d0ef68c5f6375e641eaa7f1127cddf09e4acdcff76bfae10218cbe9b5f8d44cb6cf8bc62da75463da3e8680cb4ccdf44c47236c029eff7831ea7134f
                        )

                )

        )

)
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'redacted',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' =>
  array (
    0 => '192.168.2.212',
    1 => 'redacted',
  ),
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
  ),
  'trusted_proxies' =>
  array (
    0 => '192.168.2.206',
  ),
  0 => 'extension=apcu.so',
  1 => 'apc.enable_cli=1',
  'mail_smtphost' => 'smtp.gmail.com',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'datadirectory' => '/mnt/nextcloud',
  'dbtype' => 'mysql',
  'version' => '22.1.1.2',
  'overwrite.cli.url' => 'http://localhost',
  'overwriteprotocol' => 'https',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'redacted',
  'dbpassword' => 'redacted',
  'installed' => true,
  'mail_from_address' => 'redacted',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'redacted',
  'mail_smtppassword' => 'redacted',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'default_phone_region' => 'NL',
  'twofactor_enforced' => 'true',
  'twofactor_enforced_groups' =>
  array (
    0 => 'redacted',
    1 => 'admin',
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
  'app_install_overwrite' =>
  array (
    0 => 'keeweb',
    1 => 'previewgenerator',
  ),
);

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

**Operating system:**
FreeBSD 12

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sun Aug 29 10:21:22.229920 2021] [proxy_fcgi:error] [pid 18392] [client 192.168.2.206:57373] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Doctrine\\DBAL\\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused in /usr/local/www/nextcloud/lib/private/DB/Connection.php:87\nStack trace:\n#0 /usr/local/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\\DB\\Connection->connect()\n#1 /usr/local/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\\DBAL\\Connection->getWrappedConnection()\n#2 /usr/local/www/nextcloud/lib/private/DB/Connection.php(231): Doctrine\\DBAL\\Connection->executeQuery()\n#3 /usr/local/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\\DB\\Connection->executeQuery()\n#4 /usr/local/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /usr/local/www/nextcloud/lib/private/AppConfig.php(344): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 /usr/local/www/nextcloud/lib/private/AppConfig.php(109): OC\\AppConfig->loadCo...', referer: https://cloud.thijskanters.com/index.php/settings/admin/logging
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"qq74AQd56SYN56pyipIQ","level":4,"time":"2021-08-29T10:17:12+00:00","remoteAddr":"192.168.2.151","user":"Thijs","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/Thijs/65d47290c97be59252d5c22f395550b3/0000000000000000-0000000001926075","message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",">
{"reqId":"2ubUYHy6x7Ch8jmdkEBo","level":3,"time":"2021-08-29T10:17:15+00:00","remoteAddr":"192.168.2.151","user":"--","app":"PHP","method":"GET","url":"/index.php/204","message":"Unknown: send of 5 bytes failed with errno=32 Broken pipe at Unknown#0","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.17.0","version":"22.1.1.2"}
{"reqId":"KviIVdxGQcqIWlvzUZds","level":3,"time":"2021-08-29T10:17:15+00:00","remoteAddr":"192.168.2.151","user":"--","app":"PHP","method":"GET","url":"/index.php/204","message":"Unknown: send of 5 bytes failed with errno=32 Broken pipe at Unknown#0","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.17.0","version":"22.1.1.2"}
{"reqId":"I9GeyHYlwxVCc03sWSe1","level":4,"time":"2021-08-29T10:17:15+00:00","remoteAddr":"192.168.2.151","user":"Thijs","app":"webdav","method":"MOVE","url":"/remote.php/dav/uploads/Thijs/65d47290c97be59252d5c22f395550b3/.file","message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away","userAgent":"Mozilla/5.0 (An>
```
</details>

#### log
<details>
<summary>Mysql log</summary>

```
210829 12:17:12 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 10.4.21-MariaDB
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=6
max_threads=153
thread_count=11
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 467689 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x8223fefc8
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7fffdc5d0f78 thread_stack 0x49000
0x128342c <my_print_stacktrace+0x3c> at /usr/local/libexec/mysqld
0xc1c4f5 <handle_fatal_signal+0x295> at /usr/local/libexec/mysqld
0x8017c9b70 <_pthread_sigmask+0x530> at /lib/libthr.so.3

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x8227c0aa0): INSERT INTO `oc_filecache_extended` (`fileid`, `upload_time`) VALUES(68894, '1630232232')

Connection ID (thread ID): 428
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_ca>

The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mysqld/ contains
information that should help you find out what is causing the crash.
Core pattern: /var/db/system/cores/%N.core
2021-08-29 12:17:12 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2021-08-29 12:17:12 0 [Note] InnoDB: Uses event mutexes
2021-08-29 12:17:12 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-08-29 12:17:12 0 [Note] InnoDB: Number of pools: 1
2021-08-29 12:17:12 0 [Note] InnoDB: Using SSE2 crc32 instructions
2021-08-29 12:17:12 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2021-08-29 12:17:12 0 [Note] InnoDB: Completed initialization of buffer pool
2021-08-29 12:17:12 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=926069475
2021-08-29 12:17:12 0 [Note] InnoDB: Starting final batch to recover 24 pages from redo log.
2021-08-29 12:17:12 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2021-08-29 12:17:12 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-08-29 12:17:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-08-29 12:17:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-08-29 12:17:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-08-29 12:17:12 0 [Note] InnoDB: Waiting for purge to start
2021-08-29 12:17:12 0 [Note] InnoDB: 10.4.21 started; log sequence number 926079227; transaction id 3887069
2021-08-29 12:17:12 0 [Note] InnoDB: Loading buffer pool(s) from /var/db/mysql/ib_buffer_pool
2021-08-29 12:17:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-08-29 12:17:12 0 [Note] Server socket created on IP: '127.0.0.1'.
2021-08-29 12:17:12 0 [Note] Reading of all Master_info entries succeeded
2021-08-29 12:17:12 0 [Note] Added new Master_info '' to hash table
2021-08-29 12:17:12 0 [Note] /usr/local/libexec/mysqld: ready for connections.
Version: '10.4.21-MariaDB'  socket: '/tmp/mysql.sock'  port: 3306  FreeBSD Ports
2021-08-29 12:17:13 0 [Note] InnoDB: Buffer pool(s) load completed at 210829 12:17:13
2021-08-29 12:17:15 0x82237a700  InnoDB: Assertion failure in file /wrkdirs/usr/ports/databases/mariadb104-server/work/mariadb-10.4.21/storage/innobase/btr/btr0cur.cc line 312
InnoDB: Failing assertion: page_is_comp(latch_leaves.blocks[0]->frame) == page_is_comp(page)
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to https://jira.mariadb.org/
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: https://mariadb.com/kb/en/library/innodb-recovery-modes/
InnoDB: about forcing recovery.
210829 12:17:15 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 10.4.21-MariaDB
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=1
max_threads=153
thread_count=6
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 467689 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x8224b4488
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7fffdc747f78 thread_stack 0x49000
0x128342c <my_print_stacktrace+0x3c> at /usr/local/libexec/mysqld
0xc1c4f5 <handle_fatal_signal+0x295> at /usr/local/libexec/mysqld
0x8017c9b70 <_pthread_sigmask+0x530> at /lib/libthr.so.3

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x8224fbae0): INSERT INTO `oc_filecache_extended` (`fileid`, `upload_time`) VALUES(68895, '1630232235')

Connection ID (thread ID): 14
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_ca>

The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mysqld/ contains
information that should help you find out what is causing the crash.
Core pattern: /var/db/system/cores/%N.core
2021-08-29 12:17:15 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2021-08-29 12:17:15 0 [Note] InnoDB: Uses event mutexes
2021-08-29 12:17:15 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-08-29 12:17:15 0 [Note] InnoDB: Number of pools: 1
2021-08-29 12:17:15 0 [Note] InnoDB: Using SSE2 crc32 instructions
2021-08-29 12:17:15 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2021-08-29 12:17:15 0 [Note] InnoDB: Completed initialization of buffer pool
2021-08-29 12:17:15 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=926079791
2021-08-29 12:17:15 0 [Note] InnoDB: Starting final batch to recover 15 pages from redo log.
2021-08-29 12:17:16 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2021-08-29 12:17:16 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-08-29 12:17:16 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-08-29 12:17:16 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-08-29 12:17:16 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-08-29 12:17:16 0 [Note] InnoDB: Waiting for purge to start
2021-08-29 12:17:16 0 [Note] InnoDB: 10.4.21 started; log sequence number 926085842; transaction id 3887104
2021-08-29 12:17:16 0 [Note] InnoDB: Loading buffer pool(s) from /var/db/mysql/ib_buffer_pool
2021-08-29 12:17:16 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-08-29 12:17:16 0 [Note] Server socket created on IP: '127.0.0.1'.
2021-08-29 12:17:16 0 [Note] Reading of all Master_info entries succeeded
2021-08-29 12:17:16 0 [Note] Added new Master_info '' to hash table
2021-08-29 12:17:16 0 [Note] /usr/local/libexec/mysqld: ready for connections.
Version: '10.4.21-MariaDB'  socket: '/tmp/mysql.sock'  port: 3306  FreeBSD Ports
2021-08-29 12:17:16 0 [Note] InnoDB: Buffer pool(s) load completed at 210829 12:17:16

```
</details>

**Comment by acsfer** [comment]
Sorry to say, but this seem a MySQL problem, not a Nextcloud problem.
You'll be better served at https://help.nextcloud.com or (better) at https://jira.mariadb.org/projects/MDEV/issues/MDEV-25114?filter=allopenissues

**Comment by thijsjek** [comment]
> Sorry to say, but this seem a MySQL problem, not a Nextcloud problem.
> You'll be better served at https://help.nextcloud.com or (better) at https://jira.mariadb.org/projects/MDEV/issues/MDEV-25114?filter=allopenissues

Really strange that after an upgrade of Nextcloud the datbase starts to malfunction. Has been running fine for a long while now.

**Comment by acsfer** [comment]
I still suggest to report your MariaDB error log at https://jira.mariadb.org/projects/MDEV/issues/MDEV-25114 and wait for MariaDB developpers feedback. Nextcloud is saying it can't connect to it, and MariaDB crashed. Not Nextcloud. :)
