### ISSUE TITLE
Transfer ownership cannot restore share with circle

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29059]
### Steps

1. Checkout v21.0.4
2. Checkout circles app with tag 0.21.4
3. Create three users "alice", "charles" and "user1"
4. Create a circle "First Circle"
5. Add "alice" and "user1" to the circle
6. `occ files:transfer-ownership alice charles`

### Expected result
Transfer succeeds and the share owner is remapped to "charles".

### Actual result
```
% occ files:transfer-ownership alice charles
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(
Validating quota
Analysing files of alice ...
    1 [============================]
Collecting all share information for files and folders of alice ...
    1 [============================]
Transferring files to charles/files/transferred from Alice on 2021-10-04 09-22-48 ...
Restoring shares ...
Could not restore share with id 1:#0 /srv/www/htdocs/server/apps/files/lib/Service/OwnershipTransferService.php(348): OC\Share20\Manager->updateShare()
#1 /srv/www/htdocs/server/apps/files/lib/Service/OwnershipTransferService.php(179): OCA\Files\Service\OwnershipTransferService->restoreShares()
#2 /srv/www/htdocs/server/apps/files/lib/Command/TransferOwnership.php(120): OCA\Files\Service\OwnershipTransferService->transfer()
#3 /srv/www/htdocs/server/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\TransferOwnership->execute()
#4 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 /srv/www/htdocs/server/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#8 /srv/www/htdocs/server/console.php(100): OC\Console\Application->run()
#9 /srv/www/htdocs/server/occ(11): require_once('/srv/www/htdocs...')
#10 {main}
 1/1 [============================] 100%
```

I've added a patch to log the exception message and it's "Can only update recipient on user shares".

### Version
Nextcloud Server v21.0.4
Circles 0.21.4

**Comment by PVince81** [comment]
Alright, so there's a bug that leads to making the share manager believe that we want to change the "shareWith" attribute:

```
   ⬦ $originalShare->sharedWith = (string [14]) `86a62e66fe7a5a`
   |
   ⬦ $originalShare->sharedWithDisplayName = (string [35]) `First Circle (Public circle, admin)`
```
to
```
   ⬦ $share->sharedWith = (string [52]) `First Circle (Public circle, admin) [86a62e66fe7a5a]`
   |
   ⬦ $share->sharedWithDisplayName = (string [35]) `First Circle (Public circle, admin)`
```

happening in https://github.com/nextcloud/server/blob/v21.0.4/lib/private/Share20/Manager.php#L962

something seems to overwrite "sharedWith" with a combination of display name and id.

**Comment by PVince81** [comment]
@miaulalala FYI as we were looking into similar issues recently

**Comment by PVince81** [comment]
possible ideas for fixing:

1) Find the root cause and see if the combined "shareWith" attribute is expected with circles and fix it ? @ArtificialOwl

or

2) Add a workaround in the transfer ownership code to detect the actual circle id and put it back into "shareWith" before transfer, to prevent the share manager tripping

or

3) See if there's a place in the code where we missed calling the share provider when retrieving the "$originalShare"

**Comment by PVince81** [comment]
as far as I can see there's a discrepancy in the APIs in the Circles app:

- `getShareById' will have the `shareWith` properly being purely the Circles id
- `getSharesBy` calls an extra `editShareEntry` which replaces `share_with` with the display name + id: https://github.com/nextcloud/circles/blob/0.21.4/lib/ShareByCircleProvider.php#L430

Somehow this feels wrong, maybe the latter should rather replace the "share_with_displayname" instead.

I'll investigate further to see if this was fixed already.

**Comment by PVince81** [comment]
on master that provider is deprecated and still has the issue: https://github.com/nextcloud/circles/blob/master/lib/ShareByCircleProviderDeprecated.php#L454

I have some trouble reading the new code as it has increased in complexity, so can't say whether the old logic is still there.

Also when I setup circles from master with server stable22 there is no Circles icon any more, so not sure what's going on.

So the only thing I can offer is to fix the stable21 version by making it place the display name into the correct attribute "share_with_displayname" instead of "share_with"

**Comment by PVince81** [comment]
So for now two issues:
- [ ] ShareWith mismatch, can be fixed by replacing `share_with` with `share_with_displayname` in https://github.com/nextcloud/circles/blob/stable21/lib/ShareByCircleProvider.php#L453

- [ ] getCircle() fails because `CirclesService` expects a user to exist in the session. We might need a way to make that the source user from the transfer

```
Could not restore share with id 1:Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of the type string, null given, called in /srv/www/htdocs/server/apps/circles/lib/Service/CirclesService.php on line 278 : #0 /srv/www/htdocs/server/apps/circles/lib/Service/CirclesService.php(278): OCA\Circles\Db\CirclesRequest->getCircle()
#1 /srv/www/htdocs/server/apps/circles/lib/Api/v1/Circles.php(265): OCA\Circles\Service\CirclesService->detailsCircle()
#2 /srv/www/htdocs/server/lib/private/Share20/Manager.php(247): OCA\Circles\Api\v1\Circles::detailsCircle()
#3 /srv/www/htdocs/server/lib/private/Share20/Manager.php(973): OC\Share20\Manager->generalCreateChecks()
#4 /srv/www/htdocs/server/apps/files/lib/Service/OwnershipTransferService.php(348): OC\Share20\Manager->updateShare()
#5 /srv/www/htdocs/server/apps/files/lib/Service/OwnershipTransferService.php(179): OCA\Files\Service\OwnershipTransferService->restoreShares()
#6 /srv/www/htdocs/server/apps/files/lib/Command/TransferOwnership.php(120): OCA\Files\Service\OwnershipTransferService->transfer()
#7 /srv/www/htdocs/server/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\TransferOwnership->execute()
#8 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#9 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#10 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#11 /srv/www/htdocs/server/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /srv/www/htdocs/server/console.php(100): OC\Console\Application->run()
#13 /srv/www/htdocs/server/occ(11): require_once('/srv/www/htdocs...')
#14 {main}
```

**Comment by ArtificialOwl** [comment]
What about this ? 
https://github.com/nextcloud/circles/pull/808

**Comment by PVince81** [comment]
I've tested with https://github.com/nextcloud/circles/pull/808 applied on top of stable21 and it worked fine.

so we should release that fix for stable20 and stable21
