### ISSUE TITLE
external storage: local: do not stop scanning on permission failure

### ISSUE THREAD

**Issue by alanswanson** [nextcloud/server#29514]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Add a local external storage which includes directories with no access permissions for web server user.
2. NC file scan fails at first directory permission denied.

### Expected behaviour
Skip directory and carry on.

### Actual behaviour
Stops with exception.

### Comments

I had noticed that NC stopped updating any file additions/removals to a local external storage shortly after updating from 21.0.4 to 21.0.5 but had also changed the local external storage from an ext4 filesystem mountpoint to an overlayfs lowerdirs only mountpoint (a merged JBOD including the original ext4 filesystem).

Running _occ files:scan_ shows it flaking at a permission denied with the "lost+found" directory. Since "lost+found" directories permission have always been root 700 not sure why it started failing when it was scanning fine before. The overlayfs doesn't cause any user process visible difference and I can't see any obvious related changes in 21.0.5. Bit odd.

As a workaround I've added "lost+found" to the isIgnoredDir list in lib/private/Files/Filesystem.php file but since directory permissions issues on local storage are quite likely: for any local external storage all directory permission failures should be a warning and carry on **not** an exception and stop.

Reopen of #28277 since it got closed by stale bot without original reporter updating.

### Server configuration

**Operating system:**
Linux
**Web server:**
Lighttpd
**Database:**
MariaDB
**PHP version:**
7.4.25
**Nextcloud version:** (see Nextcloud admin page)
21.0.5

**Where did you install Nextcloud from:**
Nextcloud web tar download.

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

#### OCC server error log

```
$ php occ -vvv files:scan --all
Starting scan for user 1 out of 5 (admin)
        Folder  /admin/
        Folder  /admin/cache
        Folder  /admin/files
        Folder  /admin/files/Media/
        Folder  /admin/files/Media/lost+found/
Exception during scan: opendir(/usr/local/media/lost+found): failed to open dir: Permission denied
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler()
#1 /var/www/localhost/htdocs/cloud/lib/private/Files/Storage/Local.php(135): opendir()
#2 /var/www/localhost/htdocs/cloud/lib/private/Files/Storage/Common.php(878): OC\Files\Storage\Local->opendir()
#3 /var/www/localhost/htdocs/cloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(158): OC\Files\Storage\Common->getDirectoryContent()
#4 /var/www/localhost/htdocs/cloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(158): OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()
#5 [internal function]: OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()
#6 /var/www/localhost/htdocs/cloud/lib/private/Files/Cache/Scanner.php(409): iterator_to_array()
#7 /var/www/localhost/htdocs/cloud/lib/private/Files/Cache/Scanner.php(389): OC\Files\Cache\Scanner->handleChildren()
#8 /var/www/localhost/htdocs/cloud/lib/private/Files/Cache/Scanner.php(392): OC\Files\Cache\Scanner->scanChildren()
#9 /var/www/localhost/htdocs/cloud/lib/private/Files/Cache/Scanner.php(341): OC\Files\Cache\Scanner->scanChildren()
#10 /var/www/localhost/htdocs/cloud/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan()
#11 /var/www/localhost/htdocs/cloud/apps/files/lib/Command/Scan.php(158): OC\Files\Utils\Scanner->scan()
#12 /var/www/localhost/htdocs/cloud/apps/files/lib/Command/Scan.php(214): OCA\Files\Command\Scan->scanFiles()
#13 /var/www/localhost/htdocs/cloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#14 /var/www/localhost/htdocs/cloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#15 /var/www/localhost/htdocs/cloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#16 /var/www/localhost/htdocs/cloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/localhost/htdocs/cloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#18 /var/www/localhost/htdocs/cloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#19 /var/www/localhost/htdocs/cloud/console.php(100): OC\Console\Application->run()
#20 /var/www/localhost/htdocs/cloud/occ(11): require_once('/var/www/localh...')
#21 {main}
```

And repeat for each user sharing the local external storage from /usr/local/media made available under Media in this example.

**Comment by dschrempf** [comment]
I also found:
- https://github.com/nextcloud/server/issues/26426
- https://github.com/nextcloud/server/pull/24989

I don't think this is or has been fixed. I keep having this problem for years now.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by dschrempf** [comment]
Same error on Nextcloud 25.0.3:

```
Starting scan for user 1 out of 3 (...)
Exception during scan: opendir(/path/to/file): Failed to open directory: Permission denied
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler(2, 'opendir(/mnt/ho...', '/nix/store/sj7j...', 152)
#1 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Storage/Local.php(152): opendir('/mnt/home/.cach...')
#2 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Storage/Common.php(890): OC\Files\Storage\Local->opendir('.cache/mesa_sha...')
#3 [internal function]: OC\Files\Storage\Common->getDirectoryContent('.cache/mesa_sha...')
#4 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Cache/Scanner.php(412): iterator_to_array(Object(Generator))
#5 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->handleChildren('.cache/mesa_sha...', true, 3, 9965255, true, 0)
#6 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('.cache/mesa_sha...', true, 3, 9965255, true)
#7 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('.cache/mesa_sha...', true, 3, 8799792, true)
#8 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('.cache', true, 3, 8616359, true)
#9 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Cache/Scanner.php(342): OC\Files\Cache\Scanner->scanChildren('', true, 3, 8616358, true, Array)
#10 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\Scanner->scan('', true, 3)
#11 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/apps/files/lib/Command/Scan.php(161): OC\Files\Utils\Scanner->scan('/dominik', true, NULL)
#12 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/apps/files/lib/Command/Scan.php(217): OCA\Files\Command\Scan->scanFiles('dominik', '/dominik', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#13 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/console.php(100): OC\Console\Application->run()
#20 /nix/store/sj7jjky7jpczf7q1w1sk8ayg1rkkwclp-nextcloud-25.0.3/occ(11): require_once('/nix/store/sj7j...')
#21 {main}
Starting scan for user 2 out of 3 (...)
```

**Comment by lckarssen** [comment]
Same on Nextcloud 25.0.4:
```
tarting scan for user 13 out of 14 (REDACTED)
Exception during scan: opendir(/PATH/TO/FILE/ON/EXTERNALSTORAGE): Failed to open directory: Permission denied
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler()
#1 /var/www/nextcloud/lib/private/Files/Storage/Local.php(153): opendir()
#2 /var/www/nextcloud/lib/private/Files/Storage/Common.php(890): OC\Files\Storage\Local->opendir()
#3 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(157): OC\Files\Storage\Common->getDirectoryContent()
#4 [internal function]: OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()
#5 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(412): iterator_to_array()
#6 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->handleChildren()
#7 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren()
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren()
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren()
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren()
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(342): OC\Files\Cache\Scanner->scanChildren()
#12 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\Scanner->scan()
#13 /var/www/nextcloud/apps/files/lib/Command/Scan.php(161): OC\Files\Utils\Scanner->scan()
#14 /var/www/nextcloud/apps/files/lib/Command/Scan.php(217): OCA\Files\Command\Scan->scanFiles()
#15 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Command/Command.php(298): OCA\Files\Command\Scan->execute()
#16 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#17 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#18 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#19 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#20 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#21 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#22 /var/www/nextcloud/occ(11): require_once('...')
#23 {main}
```

**Comment by megapearl** [comment]
I'm having the same problem with a WebDAV synology mount which has directories like "#recycle".
Is there any way to ignore files or directires with "@" or "#" or "." in front of it?

```
root@cloud:/# occ files:scan -vvv -- donald
Starting scan for user 1 out of 1 (donald)
        Folder  /donald/files/Synology_mountpoint/movies/#recycle
Exception during scan: Sabre\HTTP\ClientHttpException:Forbidden
#0 /app/www/public/lib/private/Files/Storage/DAV.php(931): OC\Files\Storage\DAV->convertException()
#1 /app/www/public/lib/private/Files/Storage/Wrapper/PermissionsMask.php(157): OC\Files\Storage\DAV->getDirectoryContent()
#2 [internal function]: OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()
#3 /app/www/public/lib/private/Files/Cache/Scanner.php(427): iterator_to_array()
#4 /app/www/public/lib/private/Files/Cache/Scanner.php(397): OC\Files\Cache\Scanner->handleChildren()
#5 /app/www/public/lib/private/Files/Cache/Scanner.php(400): OC\Files\Cache\Scanner->scanChildren()
#6 /app/www/public/lib/private/Files/Cache/Scanner.php(400): OC\Files\Cache\Scanner->scanChildren()
#7 /app/www/public/lib/private/Files/Cache/Scanner.php(347): OC\Files\Cache\Scanner->scanChildren()
#8 /app/www/public/lib/private/Files/Utils/Scanner.php(273): OC\Files\Cache\Scanner->scan()
#9 /config/www/nextcloud/apps/files/lib/Command/Scan.php(180): OC\Files\Utils\Scanner->scan()
#10 /config/www/nextcloud/apps/files/lib/Command/Scan.php(241): OCA\Files\Command\Scan->scanFiles()
#11 /app/www/public/3rdparty/symfony/console/Command/Command.php(298): OCA\Files\Command\Scan->execute()
#12 /app/www/public/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#13 /app/www/public/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#14 /app/www/public/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#15 /app/www/public/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#16 /app/www/public/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#17 /app/www/public/console.php(100): OC\Console\Application->run()
#18 /app/www/public/occ(11): require_once('...')
#19 {main}

+---------+-------+-----+---------+---------+--------+--------------+
| Folders | Files | New | Updated | Removed | Errors | Elapsed time |
+---------+-------+-----+---------+---------+--------+--------------+
| 145     | 288   | 0   | 0       | 0       | 1      | 00:00:04     |
+---------+-------+-----+---------+---------+--------+--------------+
root@cloud:/# 

```

**Comment by HansAndreManfredson** [comment]
Same problem over here... I was happy to find this problem because I thought it would be a problem since I use LXD/Incus... I also mounted an NFS share on the host and mounted it to the system container .....
What is weird is that I can read and write to this folder from OS...  

```text
Error during scan: opendir(/mnt/h2c/BackupiPhone/): Failed to open directory: Permission denied
#0 /snap/nextcloud/40887/htdocs/apps/files/lib/Command/Scan.php(246): OCA\Files\Command\Scan->exceptionErrorHandler()
#1 [internal function]: OCA\Files\Command\Scan->OCA\Files\Command\{closure}()
#2 /snap/nextcloud/40887/htdocs/lib/private/Files/Storage/Local.php(157): opendir()
#3 /snap/nextcloud/40887/htdocs/lib/private/Files/Storage/Common.php(896): OC\Files\Storage\Local->opendir()
#4 /snap/nextcloud/40887/htdocs/lib/private/Files/Storage/Wrapper/PermissionsMask.php(157): OC\Files\Storage\Common->getDirectoryContent()
#5 [internal function]: OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()
#6 /snap/nextcloud/40887/htdocs/lib/private/Files/Cache/Scanner.php(447): iterator_to_array()
#7 /snap/nextcloud/40887/htdocs/lib/private/Files/Cache/Scanner.php(404): OC\Files\Cache\Scanner->handleChildren()
#8 /snap/nextcloud/40887/htdocs/lib/private/Files/Cache/Scanner.php(354): OC\Files\Cache\Scanner->scanChildren()
#9 /snap/nextcloud/40887/htdocs/lib/private/Files/Utils/Scanner.php(273): OC\Files\Cache\Scanner->scan()
#10 /snap/nextcloud/40887/htdocs/apps/files/lib/Command/Scan.php(164): OC\Files\Utils\Scanner->scan()
#11 /snap/nextcloud/40887/htdocs/apps/files/lib/Command/Scan.php(219): OCA\Files\Command\Scan->scanFiles()
#12 /snap/nextcloud/40887/htdocs/3rdparty/symfony/console/Command/Command.php(298): OCA\Files\Command\Scan->execute()
#13 /snap/nextcloud/40887/htdocs/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#14 /snap/nextcloud/40887/htdocs/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#15 /snap/nextcloud/40887/htdocs/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#16 /snap/nextcloud/40887/htdocs/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#17 /snap/nextcloud/40887/htdocs/lib/private/Console/Application.php(218): Symfony\Component\Console\Application->run()
#18 /snap/nextcloud/40887/htdocs/console.php(100): OC\Console\Application->run()
#19 /snap/nextcloud/40887/htdocs/occ(11): require_once('...')
#20 {main}
```

```
root@lxd-nxc-01:~# nextcloud.occ status
  - installed: true
  - version: 27.1.7.2
  - versionstring: 27.1.7
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
  
  ```

**Comment by FlattusBlastus** [comment]
Still broken in 28.0.4

**Comment by cbean** [comment]
Still broken in 29.04

**Comment by agrenott** [comment]
Until a proper fix is implemented (if ever), here is a quick and dirty work-around (basically just a massive try/catch in the main loop):

```
# Dirty work-around https://github.com/nextcloud/server/issues/29514
# diff lib/private/Files/Cache/Scanner.php.orig lib/private/Files/Cache/Scanner.php
414c414,415
<               $childQueue = $this->handleChildren($path, $recursive, $reuse, $folderId, $lock, $size, $etagChanged);
---
>               try {
>                       $childQueue = $this->handleChildren($path, $recursive, $reuse, $folderId, $lock, $size, $etagChanged);
416,420c417,421
<               foreach ($childQueue as $child => [$childId, $childSize]) {
<                       // "etag changed" propagates up, but not down, so we pass `false` to the children even if we already know that the etag of the current folder changed
<                       $childEtagChanged = false;
<                       $childSize = $this->scanChildren($child, $recursive, $reuse, $childId, $lock, $childSize, $childEtagChanged);
<                       $etagChanged |= $childEtagChanged;
---
>                       foreach ($childQueue as $child => [$childId, $childSize]) {
>                               // "etag changed" propagates up, but not down, so we pass `false` to the children even if we already know that the etag of the current folder changed
>                               $childEtagChanged = false;
>                               $childSize = $this->scanChildren($child, $recursive, $reuse, $childId, $lock, $childSize, $childEtagChanged);
>                               $etagChanged |= $childEtagChanged;
422,425c423,427
<                       if ($childSize === -1) {
<                               $size = -1;
<                       } elseif ($size !== -1) {
<                               $size += $childSize;
---
>                               if ($childSize === -1) {
>                                       $size = -1;
>                               } elseif ($size !== -1) {
>                                       $size += $childSize;
>                               }
427d428
<               }
429,443c430,445
<               // for encrypted storages, we trigger a regular folder size calculation instead of using the calculated size
<               // to make sure we also updated the unencrypted-size where applicable
<               if ($this->storage->instanceOfStorage(Encryption::class)) {
<                       $this->cache->calculateFolderSize($path);
<               } else {
<                       if ($this->cacheActive) {
<                               $updatedData = [];
<                               if ($oldSize !== $size) {
<                                       $updatedData['size'] = $size;
<                               }
<                               if ($etagChanged) {
<                                       $updatedData['etag'] = uniqid();
<                               }
<                               if ($updatedData) {
<                                       $this->cache->update($folderId, $updatedData);
---
>                       // for encrypted storages, we trigger a regular folder size calculation instead of using the calculated size
>                       // to make sure we also updated the unencrypted-size where applicable
>                       if ($this->storage->instanceOfStorage(Encryption::class)) {
>                               $this->cache->calculateFolderSize($path);
>                       } else {
>                               if ($this->cacheActive) {
>                                       $updatedData = [];
>                                       if ($oldSize !== $size) {
>                                               $updatedData['size'] = $size;
>                                       }
>                                       if ($etagChanged) {
>                                               $updatedData['etag'] = uniqid();
>                                       }
>                                       if ($updatedData) {
>                                               $this->cache->update($folderId, $updatedData);
>                                       }
445a448,453
>                       $this->emit('\OC\Files\Cache\Scanner', 'postScanFolder', [$path, $this->storageId]);
>               } catch (\Throwable $ex) {
>                       \OC::$server->get(LoggerInterface::class)->warning('My patched code ## Exception while scanning path "' . $path . '"', [
>                               'app' => 'core',
>                               'exception' => $ex,
>                       ]);
447d454
<               $this->emit('\OC\Files\Cache\Scanner', 'postScanFolder', [$path, $this->storageId]);

```

**Comment by lckarssen** [comment]
Thanks for the workaround @agrenott! One thing to note is that your diff seems to miss a closing `}` after the `]);` in the last line of the last `>` block. Without it, the `scanChildren()` function isn't properly closed. 

After adding that missing `}`, the scan of my external storage —that includes directories for which the Apache user doesn't have (read and access) permissions— finished properly. This also removed messages like "User username still has unscanned files after running background scan, background scan might be stopped prematurely" (see #43557 and #31283) from the logs. 

In particular, for #31283: With the above diff in place, the output of the SQL statement from https://github.com/nextcloud/server/issues/31283#issuecomment-1046719989 went from 369 lines of stale cache files to 0 lines after running `occ files: scan --unscanned username`

**Comment by OmegaRa** [comment]
I have this same bug, but where/what do I do with that workaround code?
