### ISSUE TITLE
Upgrading: Symfony\Component\EventDispatcher\GenericEvent::getArgument() must be of the type string, int given

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [nextcloud/server#29733]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Upgrade to 22.2.3 with Web UI or `php -f updater/updater.phar`
2. `php occ upgrade`
3. Workaround: https://github.com/nextcloud/server/commit/710f7d629469e91df76ff3dae998ac3ce18e9c15

### Expected behaviour

Upgrading and migration works without errors.

### Actual behaviour

PHP type error.

### Server configuration

**Operating system:**

postmarketOS 21.06 / Alpine 3.14

**Web server:**

nginx

**Database:**

mariadb

**PHP version:**

php 7.4.25

**Nextcloud version:** (see Nextcloud admin page)

22.2.2.0 -> 22.2.3.?

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from 22.2.2.0 to 22.2.3.?

**Where did you install Nextcloud from:**
Official archive / `php -f updater/updater.php`

**Signing status:**

(Unavailable)

**List of activated apps:**

(Skipped)

**Nextcloud configuration:**

(Skipped)

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### PHP outputs
<details>
<summary>Browser log</summary>

```
postmarketos-msm8916:/var/www/localhost/htdocs/nextcloud$ sudo -u nextcloud php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
An unhandled exception has been thrown:
Error: Call to undefined function OC\EventDispatcher\string() in /var/www/localhost/htdocs/nextcloud/lib/private/EventDispatcher/GenericEventWrapper.php:83
Stack trace:
#0 /var/www/localhost/htdocs/nextcloud/lib/private/Updater.php(513): OC\EventDispatcher\GenericEventWrapper->getArgument()
#1 /var/www/localhost/htdocs/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\Updater->OC\{closure}()
#2 /var/www/localhost/htdocs/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#3 /var/www/localhost/htdocs/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(123): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#4 /var/www/localhost/htdocs/nextcloud/lib/private/Repair.php(251): OC\EventDispatcher\SymfonyAdapter->dispatch()
#5 /var/www/localhost/htdocs/nextcloud/lib/private/Repair.php(121): OC\Repair->emit()
#6 /var/www/localhost/htdocs/nextcloud/lib/private/Updater.php(251): OC\Repair->run()
#7 /var/www/localhost/htdocs/nextcloud/lib/private/Updater.php(132): OC\Updater->doUpgrade()
#8 /var/www/localhost/htdocs/nextcloud/core/Command/Upgrade.php(241): OC\Updater->upgrade()
#9 /var/www/localhost/htdocs/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(299): OC\Core\Command\Upgrade->execute()
#10 /var/www/localhost/htdocs/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#11 /var/www/localhost/htdocs/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/localhost/htdocs/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#13 /var/www/localhost/htdocs/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#14 /var/www/localhost/htdocs/nextcloud/console.php(99): OC\Console\Application->run()
#15 /var/www/localhost/htdocs/nextcloud/occ(11): require_once('/var/www/localh...')
```
</details>

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Still happens on 22.2.5. And temporarily solved with the same workaround.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Still happens on 22.2.6 and we know what happens next.
