### ISSUE TITLE
can't active apps

### ISSUE THREAD

**Issue by qwertygc** [nextcloud/server#2977]
Hi ! 
i have install a fresh install of nextcloud (11) and when i want install app, the button dont move. The logs : 

```
{"reqId":"","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given object name is invalid\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(892): OC\\\\Activity\\\\Event->setObject('files', 2, false)\\n#1 \\\/var\\\/www\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(184): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('toto', 'created_self', Array, 2, false, true, true, 0, 'file_created')\\n#2 \\\/var\\\/www\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(111): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/', 'file_created', 'created_self', 'created_by')\\n#3 \\\/var\\\/www\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/View.php(1237): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/View.php(1163): OC\\\\Files\\\\View->runHooks(Array, '\\\/toto\\\/files', true)\\n#8 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/View.php(266): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/toto\\\/files', Array)\\n#9 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(149): OC\\\\Files\\\\View->mkdir('\\\/toto\\\/files')\\n#10 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(380): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/toto\\\/files')\\n#11 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('toto')\\n#12 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#14 \\\/var\\\/www\\\/lib\\\/private\\\/Server.php(948): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('toto')\\n#15 \\\/var\\\/www\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\Server->getUserFolder('toto')\\n#16 \\\/var\\\/www\\\/lib\\\/private\\\/User\\\/Session.php(479): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#17 \\\/var\\\/www\\\/lib\\\/private\\\/User\\\/Session.php(299): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/www\\\/lib\\\/private\\\/Setup.php(393): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/www\\\/core\\\/Controller\\\/SetupController.php(65): OC\\\\Setup->install(Array)\\n#20 \\\/var\\\/www\\\/lib\\\/base.php(957): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#21 \\\/var\\\/www\\\/index.php(40): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/Activity\\\/Event.php\",\"Line\":401}","level":3,"time":"2017-01-08T20:00:48+00:00","method":"POST","url":"\/nc\/index.php","user":"toto","version":"11.0.0.10"}
````
my PHPinfo  : http://www.legtux.org/phpinfo.php

**Comment by qwertygc** [comment]
OK, the problem is in my .htaccess
