### ISSUE TITLE
error if i execute occ command

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#30073]
### Steps to reproduce
use any occ command

### Expected behaviour
execut command

### Actual behaviour
get error since update to nc 23

## Server configuration detail

**Operating system:** Linux 5.11.22-5-pve #1 SMP PVE 5.11.22-10 (Tue, 28 Sep 2021 08:15:41 +0200) x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.5.12

**PHP version:** 

8.0.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 23.0.0 - 23.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [upgrade.log] => Array
                        (
                            [expected] => 
                            [current] => 1787b401abc405f1774662f33d9354d759de727591177c5434fa240ff20088eb198f5af6f957423b041af7adc075cab2c52bf780b0f212444373dde1ea1ff417
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - apporder: 0.13.0
 - approval: 1.0.9
 - calendar: 3.0.1
 - circles: 23.0.0
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contacts: 4.0.6
 - dashboard: 7.3.0
 - dav: 1.21.0
 - deck: 1.6.0
 - event_update_notification: 1.4.0
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_downloadactivity: 1.12.0
 - files_markdown: 2.3.5
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_texteditor: 2.14.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - fileslibreofficeedit: 1.0.2
 - firstrunwizard: 2.12.0
 - forms: 2.4.0
 - groupfolders: 11.1.0
 - guests: 2.1.0
 - integration_mastodon: 1.0.2
 - issuetemplate: 0.7.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - mail: 1.11.0
 - maps: 0.1.9
 - metadata: 0.15.0
 - nextcloud_announcements: 1.12.0
 - notes: 4.2.0
 - notifications: 2.11.1
 - notify_push: 0.3.0
 - oauth2: 1.11.0
 - onlyoffice: 7.2.1
 - password_policy: 1.13.0
 - passwords: 2021.11.20
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - quota_warning: 1.13.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - socialsharing_email: 2.4.0
 - spreed: 13.0.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - tasks: 0.14.2
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - twofactor_nextcloud_notification: 3.3.1
 - twofactor_totp: 6.2.0
 - twofactor_u2f: 6.3.0
 - updatenotification: 1.13.0
 - user_retention: 1.6.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - workflowengine: 2.5.0
Disabled:
 - breezedark
 - contactsinteraction
 - encryption
 - files_external
 - files_linkeditor
 - integration_whiteboard
 - polls
 - recommendations
 - support
 - twofactor_admin
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "anzah.cloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/anzah.cloud",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "23.0.0.10",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "maintenance": false,
    "default_language": "de",
    "default_locale": "de",
    "default_phone_region": "DE",
    "allow_user_to_change_display_name": true,
    "knowledgebaseenabled": true,
    "theme": "",
    "defaultapp": "apporder",
    "skeletondirectory": "\/var\/customers\/webs\/Anzah\/anzah.cloud\/core\/skeleton",
    "trashbin_retention_obligation": "120, auto",
    "versions_retention_obligation": "120, auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.release.channel": "stable",
    "check_for_working_webdav": true,
    "loglevel": 0,
    "logdateformat": "d.m.Y H:i:s",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 10485760,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_filesize_image": 50,
    "preview_max_scale_factor": 10,
    "data-fingerprint": "01b9630d063ba580c331de332a0ab360",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 10,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "twofactor_enforced": false,
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "apporder",
        "circles",
        "groupfolders",
        "whiteboard",
        "issuetemplate",
        "tasks",
        "bookmarks",
        "appointments",
        "quota_warning",
        "jitsi",
        "passwords",
        "files_downloadactivity"
    ],
    "migrate_guest_user_data": true,
    "remove_guest_account_on_conversion": true,
    "keep_users_without_login": "no"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

**Operating system:** 

## Logs
<details><summary>ooc command log</summary>

```
sudo -u Anzah php /var/customers/webs/Anzah/anzah.cloud/occ app:update --all
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OC\App\AppStore\Fetcher\Fetcher::__construct(), 5 passed in /var/customers/webs/Anzah/anzah.cloud/apps/passwords/lib/Fetcher/NightlyAppFetcher.php on line 92 and exactly 6 expected in /var/customers/webs/Anzah/anzah.cloud/lib/private/App/AppStore/Fetcher/Fetcher.php:70
Stack trace:
#0 /var/customers/webs/Anzah/anzah.cloud/apps/passwords/lib/Fetcher/NightlyAppFetcher.php(92): OC\App\AppStore\Fetcher\Fetcher->__construct()
#1 [internal function]: OCA\Passwords\Fetcher\NightlyAppFetcher->__construct()
#2 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): ReflectionClass->newInstanceArgs()
#3 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#4 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#10 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#13 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#14 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#16 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#17 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#18 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#19 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#21 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#23 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#24 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#25 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#26 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#27 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#28 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#29 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#30 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#31 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#32 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#33 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#34 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#35 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#36 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#37 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#38 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#39 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#40 /var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#41 /var/customers/webs/Anzah/anzah.cloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#42 /var/customers/webs/Anzah/anzah.cloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#43 /var/customers/webs/Anzah/anzah.cloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#44 /var/customers/webs/Anzah/anzah.cloud/console.php(98): OC\Console\Application->loadCommands()
#45 /var/customers/webs/Anzah/anzah.cloud/occ(11): require_once('...')
```
</details>

**Comment by rakekniven** [comment]
Could not see an example on how about you call occ. Please provide your shell command.

**Comment by Tealk** [comment]
oh i forgot to rename this, it is under nextcloud log

**Comment by rakekniven** [comment]
which php version is called by php?

**Comment by Tealk** [comment]
atm 8.0.13

**Comment by Tealk** [comment]
ok it's a not compatible app i just see, sorry
https://github.com/marius-wieschollek/passwords/issues/457
