### ISSUE TITLE
Errorlog: Symfony - RouteNotFoundException - settings_admin

### ISSUE THREAD

**Issue by sackla** [nextcloud/server#3022]
Everything seems to work fine, but there are errors logged regularly (see below). at first I thought them to be daily, but there was a 2 day gap now.

someone else reportet this here: https://help.nextcloud.com/t/can-someone-help-me-understand-these-lines-in-nextcloud-log/4664
and here: https://help.nextcloud.com/t/nextcloud-10-cant-open-the-updater/6404

 
### Steps to reproduce
not a clue. I guess opening the admin settings, but it is not happening every time.

### Expected behaviour
No errors logged.

### Actual behaviour
Everything seems to work fine, but there are errors logged.

### Server configuration
**Operating system**: Debian 4.7.8 

**Web server:** Apache/2.4.10

**Database:** mysql 5.5.53

**PHP version:** 5.6.28

**Nextcloud version:** (see Nextcloud admin page) 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from owncloud 9

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - contacts: 1.5.1
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - richdocuments: 1.1.16
  - serverinfo: 1.1.1
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - calendar
  - encryption
  - external
  - files_accesscontrol
  - user_saml
```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => '192.168.10.12',
    1 => 'owncloud.domain.some',
    2 => 'cloud.domain.some',
    3 => 'nextcloud.domain.some'
  ),
  'datadirectory' => '/mnt/clouddata/',
  'overwrite.cli.url' => 'http://192.168.10.12/index.php/',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXXXXX',
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\TIFF',
  ),
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => 'domain.some',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'versions_retention_obligation' => 'auto',
  'theme' => '',
  'loglevel' => 3,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'singleuser' => false,
  'appstore.experimental.enabled' => true,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);
```

**Are you using external storage, if yes which one:** no.

**Are you using encryption:** not atm. tested on owncloud months ago. turned off on owncloud months ago.

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
```
will provide if needed
```

### Client configuration
**Browser:** Firefox 45.6 ESR

**Operating system:** Win10

#### Web server error log
`nothing related`

#### Nextcloud log (data/nextcloud.log)

```
{"reqId":"M0T7NZV4CWQp8OY59aGj","remoteAddr":"10.30.some.address","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"settings_admin\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(333): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('settings_admin', Array, 1)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('settings_admin', Array, false)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(69): OC\\\\Route\\\\CachingRouter->generate('settings_admin', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(82): OC\\\\URLGenerator->linkToRoute('settings_admin', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/updatenotification\\\/lib\\\/Notification\\\/BackgroundJob.php(101): OC\\\\URLGenerator->linkToRouteAbsolute('settings_admin')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/updatenotification\\\/lib\\\/Notification\\\/BackgroundJob.php(84): OCA\\\\UpdateNotification\\\\Notification\\\\BackgroundJob->checkCoreUpdate()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\UpdateNotification\\\\Notification\\\\BackgroundJob->run(NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/cron.php(143): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2017-01-09T10:20:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"M0T7NZV4CWQp8OY59aGj","remoteAddr":"10.30.some.address","app":"PHP","message":"Uninitialized string offset: 0 at \/var\/www\/nextcloud\/lib\/private\/URLGenerator.php#207","level":3,"time":"2017-01-09T10:20:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
```

</details>

#### Browser log

```
will provide if needed.
```

**Comment by nickvergessen** [comment]
This was fixed with 10.0.2 which is available since 9th december please update
