### ISSUE TITLE
Error in `RemoveDeletedUsersCalendarSubscriptions` while upgrading from 22.2.3.0 to 23.0.0.10

### ISSUE THREAD

**Issue by luclu** [nextcloud/server#30337]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Actual behaviour
```sudo -u www-data php -d memory_limit=-1 occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [->--------------------------]   0%
Clean up old calendar subscriptions from deleted users that were not cleaned-up
 Done
 3/3 [============================] 100%
An unhandled exception has been thrown:
TypeError: OCA\DAV\Migration\RemoveDeletedUsersCalendarSubscriptions::deleteOrphanSubscription(): Argument #1 ($orphanSubscriptionID) must be of type int, string given, called in /var/www/html/apps/dav/lib/Migration/RemoveDeletedUsersCalendarSubscriptions.php on line 126 and defined in /var/www/html/apps/dav/lib/Migration/RemoveDeletedUsersCalendarSubscriptions.php:133
Stack trace:
#0 /var/www/html/apps/dav/lib/Migration/RemoveDeletedUsersCalendarSubscriptions.php(126): OCA\DAV\Migration\RemoveDeletedUsersCalendarSubscriptions->deleteOrphanSubscription('5')
#1 /var/www/html/apps/dav/lib/Migration/RemoveDeletedUsersCalendarSubscriptions.php(75): OCA\DAV\Migration\RemoveDeletedUsersCalendarSubscriptions->deleteOrphanSubscriptions()
#2 /var/www/html/lib/private/Repair.php(123): OCA\DAV\Migration\RemoveDeletedUsersCalendarSubscriptions->run(Object(OC\Repair))
#3 /var/www/html/lib/private/legacy/OC_App.php(1071): OC\Repair->run()
#4 /var/www/html/lib/private/legacy/OC_App.php(1013): OC_App::executeRepairSteps('dav', Array)
#5 /var/www/html/lib/private/Updater.php(353): OC_App::updateApp('dav')
#6 /var/www/html/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
#7 /var/www/html/lib/private/Updater.php(133): OC\Updater->doUpgrade('23.0.0.10', '22.2.3.0')
#8 /var/www/html/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#9 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/console.php(99): OC\Console\Application->run()
#15 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by acsfer** [comment]
Fixed by https://github.com/nextcloud/server/issues/30337
