### ISSUE TITLE
Exception When Creating Task List In macOS Reminder App (CalDAV)

### ISSUE THREAD

**Issue by thomaskonrad** [nextcloud/server#3057]
### Steps to reproduce
1. Sync a calendar including tasks with the macOS Reminders app using CalDAV (I uses the URL ```https://my.domain.com/remote.php/dav/principals/users/myusername/```)
2. Open the macOS Reminders app
3. Create a new list by clicking "Add List" in the lower-left corner of the macOS Reminders app
4. See the log file of the Nextcloud server

### Expected behaviour
A new task list should be created on the Nextcloud server in the Tasks app.

### Actual behaviour
An exception is thrown because the SQL insert statement tries to inser the value ```false``` in an integer column named ```transparent```.

### Server configuration
**Operating system**: Ubuntu Server 16.04 64bit

**Web server:** nginx

**Database:** MySQL

**PHP version:** 7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** 11.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Migrated from ownCloud

**Where did you install Nextcloud from:** ZIP file

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "session_lifetime": 36000,
        "appstore.experimental.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.3.3",
            "order": "[\"\/apps\/files\/\",\"\/apps\/tasks\/\",\"\/apps\/news\/\",\"\/apps\/mail\/\",\"\/apps\/calendar\/\",\"\/apps\/contacts\/\",\"\/apps\/bookmarks\/\",\"\/apps\/notes\/\",\"\/apps\/activity\/\",\"\/apps\/gallery\/\"]",
            "types": ""
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "1.3.1",
            "ocsid": "174738",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "10"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1463403682.5717",
            "lastcron": "1484292605",
            "lastupdateResult": "[]",
            "lastupdatedat": "1484290767",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.1.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "15.1.0",
            "ocsid": "169116",
            "signed": "true",
            "types": ""
        },
        "gpxedit": {
            "enabled": "no",
            "installed_version": "0.0.3",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "00111",
            "ocsid": "170871",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.6.2",
            "types": ""
        },
        "music": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "news": {
            "enabled": "yes",
            "installed_version": "10.1.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "0",
            "enforceUpperLowerCase": "0",
            "installed_version": "1.1.0",
            "minLength": "10",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.4",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "cachebuster": "13",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "ocsid": "174726",
            "signed": "true",
            "types": ""
        },
        "updatenotification": {
            "audioplayer": "1.3.1",
            "core": "9.1.2",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "twofactor_totp": "0.4.1",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** macOS (the Reminder app or the OS itself, I don't know actually)

**Operating system:** macOS Sierra 10.12.2

#### Web server error log (i have reformatted and unescaped it for better readability)
<details>
<summary>Web server error log</summary>

```
No relevant webserver logs.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log (I have reformatted it for better readability)</summary>

```
{
	"reqId":"[SNIP]",
	"remoteAddr":"194.SNIP",
	"app":"webdav",
	"message":"Exception:
		{"Message":"An exception occurred while executing
			'INSERT INTO `nc_calendars` (`principaluri`, `uri`, `synctoken`, `transparent`, `components`, `displayname`, `timezone`, `calendarorder`, `calendarcolor`)
			VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)'
			with params [
				"principals/users/SNIP",
				"DE96D73B-SNIP",
				1,
				false,
				"VTODO",
				"New List",
				"BEGIN:VCALENDAR
				VERSION:2.0
				PRODID:-\/\/Apple Inc.\/\/Mac OS X 10.12.2\/\/EN
				CALSCALE:GREGORIAN
				BEGIN:VTIMEZONE
				TZID:Europe\/Vienna
				BEGIN:DAYLIGHT
				TZOFFSETFROM:+0100
				RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
				DTSTART:19810329T020000
				TZNAME:GMT+2
				TZOFFSETTO:+0200
				END:DAYLIGHT
				BEGIN:STANDARD
				TZOFFSETFROM:+0200
				RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
				DTSTART:19961027T030000
				TZNAME:GMT+1
				TZOFFSETTO:+0100
				END:STANDARD
				END:VTIMEZONE
				END:VCALENDAR",
				"855",
				"#0E61B9FF"]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'transparent' at row 1",
		"Exception":"Doctrine\DBAL\Exception\DriverException",
		"Code":0,
		"Trace":"
			#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
			#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `nc...', Array)
			#2 /var/www/nextcloud/lib/private/DB/Connection.php(215): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO `nc...', Array, Array)
			#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('INSERT INTO `nc...', Array, Array)
			#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(177): Doctrine\DBAL\Query\QueryBuilder->execute()
			#5 /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php(616): OC\DB\QueryBuilder\QueryBuilder->execute()
			#6 /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/CalendarHome.php(265): OCA\DAV\CalDAV\CalDavBackend->createCalendar('principals/user...', 'DE96D73B-EF63-4...', Array)
			#7 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(1173): Sabre\CalDAV\CalendarHome->createExtendedCollection('DE96D73B-EF63-4...', Object(Sabre\DAV\MkCol))
			#8 /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(303): Sabre\DAV\Server->createCollection('calendars/tom/D...', Object(Sabre\DAV\MkCol))
			#9 [internal function]: Sabre\CalDAV\Plugin->httpMkCalendar(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))#10 /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
			#11 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:MKCALEND...', Array)
			#12 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))#13 /var/www/nextcloud/apps/dav/lib/Server.php(227): Sabre\DAV\Server->exec()#14 /var/www/nextcloud/apps/dav/appinfo/v2/remote.php(30): OCA\DAV\Server->exec()
			#15 /var/www/nextcloud/remote.php(165): require_once('/var/www/nextcl...')#16 {main}","File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php",
		"Line":116,
		"User":"tom"
		}",
	"level":4,
	"time":"2017-01-13T07:07:35+00:00",
	"method":"MKCALENDAR",
	"url":"/remote.php/dav/calendars/SNIP/DE96D73B-SNIP/",
	"user":"SNIP",
	"version":"11.0.0.10"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No relevant browser logs.
```
</details>

The error seems to be that the DAV library tries to insert the value ```false``` into the integer column ```transparent```.

**Comment by georgehrke** [comment]
Should have been fixed by https://github.com/nextcloud/server/commit/43143e170ee775af7266cb01c8c667186c985d62

If not please speak up.
