### ISSUE TITLE
Integrity check reports extra files even though they are packaged

### ISSUE THREAD

**Issue by onny** [nextcloud/server#3067]
### Steps to reproduce
1.  /usr/share/webapps/nextcloud # sudo -u http occ integrity:check-core
2. Command report extra files
```
  - EXTRA_FILE:
    - core/js/sharedialogmailview.js:
      - expected:
      - current: 5d00889e8138a37fc6df74ad236819629774f73238dded4e152ee7458c4723cbd60bb02313a2029f529b89c243c44b2b7c893275aec8eb88d045be9402f9db75
    - core/js/placeholders.js:
      - expected:
      - current: 1911ab6c19a944bc3bb5fb25460dd16b74718d0b3861d64c94b117e32e0462cc8e4cf27c9948861a8f0c600c719a993eb0cabc294b81dc08c5a6d54407b9228f
[...]
```

### Expected behaviour
Integrity check should pass successfully

### Actual behaviour
Integrity check reports extra files even tough they are packaged in the tarball and important

### Server configuration
**Operating system**: ArchLiux x86_64

**Web server:** Nginx 1.10.2

**Database:** Mysql

**PHP version:** 7.0.14

**Nextcloud version:** 11

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** [Archlinux User Repository](https://aur.archlinux.org/packages/nextcloud/)

**Signing status:** Not signed

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - radio: 0.2
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```
</details>

<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "527b7f969713e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "mysql.pi",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "maxZipInputSize": 5145728000,
        "allowZipDownload": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": [
            "nextcloud.project-insanity.org",
            "http-new.pi"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "project-insanity.org",
        "mail_smtpmode": "php",
        "mail_from_address": "nextcloud",
        "trashbin_retention_obligation": "auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox 50.1

**Operating system:** Archlinux x86_64

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"0bogluCbc3R\/YaayQwok","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve CardDavBackend! Class CardDavBackend does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('CardDavBackend')\\n#1 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('CardDavBackend')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/register_command.php(37): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('CardDavBackend')\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(119): require('\\\/usr\\\/share\\\/weba...')\\n#4 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/console.php(89): OC\\\\Console\\\\Application->loadCommands(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/occ(11): require_once('\\\/usr\\\/share\\\/weba...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","level":3,"time":"2017-01-13T15:17:55+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
> Where did you install Nextcloud from: Archlinux User Repository

=> Please report this to the Archlinux maintainer.

**Comment by LukasReschke** [comment]
Also I can't find those files at https://github.com/nextcloud/server/tree/stable11/core/js
