### ISSUE TITLE
Database and filesystem out of sync (files visible in web interface but never hit filesystem)

### ISSUE THREAD

**Issue by fgrsnau** [nextcloud/server#3071]
### Steps to reproduce
1. ???
2. create new directory in NextCloud desktop app
3. move files into the new directory or upload new files
4. try to access them

Unfortunately, not really reproducible right now. :(

### Expected behaviour
Files should be correctly uploaded or at least show error. The database information and filesystem structure should not diverge in any way as this makes users think that the upload was successful.

### Actual behaviour
The database got updated and all files were visible in the web ui. Accessing any of these files resulted in a 5xx error page. The underlying reason is that neither the directory nor the files were existing. No error was displayed and instead non-existing files were visible in the web interface. It is worth noting that the HTTP status code of the response (MOVE request) was 201 even though an exception was raised.

### Server configuration
**Operating system**: Debian stable/jessie, up to date

**Web server:** nginx 1.6.2

**Database:** PostgreSQL 9.4

**PHP version:** php-fpm 5.6.28

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 10.*, relatively fresh install

**Where did you install Nextcloud from:** tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - documents: 0.13.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.3
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_pdfviewer
  - files_retention
  - ocr
  - password_policy
  - survey_client
  - templateeditor
  - user_external
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'maintenance' => false,
  'singleuser' => false,
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/media/data/nextcloud',
  'dbtype' => 'pgsql',
  'version' => '11.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'xxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'xxx',
  'mail_smtphost' => 'xxx',
  'loglevel' => 2,
);
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+----------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                      |
| hasPagedResultSupport         |                                                                                        |
| homeFolderNamingRule          |                                                                                        |
| lastJpegPhotoLookup           | 0                                                                                      |
| ldapAgentName                 | uid=nextcloud,cn=sysaccounts,cn=etc,dc=xxx,dc=xxx                                      |
| ldapAgentPassword             | ***                                                                                    |
| ldapAttributesForGroupSearch  |                                                                                        |
| ldapAttributesForUserSearch   |                                                                                        |
| ldapBackupHost                |                                                                                        |
| ldapBackupPort                |                                                                                        |
| ldapBase                      | dc=xxx,dc=xxx                                                                          |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=xxx,dc=xxx                                                    |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=xxx,dc=xxx                                                     |
| ldapCacheTTL                  | 600                                                                                    |
| ldapConfigurationActive       | 1                                                                                      |
| ldapDynamicGroupMemberURL     |                                                                                        |
| ldapEmailAttribute            | mail                                                                                   |
| ldapExperiencedAdmin          | 0                                                                                      |
| ldapExpertUUIDGroupAttr       | ipaUniqueID                                                                            |
| ldapExpertUUIDUserAttr        | ipaUniqueID                                                                            |
| ldapExpertUsernameAttr        | uid                                                                                    |
| ldapGroupDisplayName          | cn                                                                                     |
| ldapGroupFilter               | (|(!(objectclass=posixgroup))(cn=nextcloud-admins))                                    |
| ldapGroupFilterGroups         |                                                                                        |
| ldapGroupFilterMode           | 1                                                                                      |
| ldapGroupFilterObjectclass    | ipausergroup                                                                           |
| ldapGroupMemberAssocAttr      | member                                                                                 |
| ldapHost                      | xxx                                                                                    |
| ldapIgnoreNamingRules         |                                                                                        |
| ldapLoginFilter               | (&(objectclass=inetorgperson)(uid=%uid))                                               |
| ldapLoginFilterAttributes     |                                                                                        |
| ldapLoginFilterEmail          | 0                                                                                      |
| ldapLoginFilterMode           | 1                                                                                      |
| ldapLoginFilterUsername       | 1                                                                                      |
| ldapNestedGroups              | 0                                                                                      |
| ldapOverrideMainServer        |                                                                                        |
| ldapPagingSize                | 500                                                                                    |
| ldapPort                      | 389                                                                                    |
| ldapQuotaAttribute            |                                                                                        |
| ldapQuotaDefault              |                                                                                        |
| ldapTLS                       | 0                                                                                      |
| ldapUserDisplayName           | cn                                                                                     |
| ldapUserDisplayName2          |                                                                                        |
| ldapUserFilter                | (&(objectclass=inetorgperson)(memberof=cn=Cloud,cn=privileges,cn=pbac,dc=xxx,dc=xxx))  |
| ldapUserFilterGroups          | aktiv                                                                                  |
| ldapUserFilterMode            | 1                                                                                      |
| ldapUserFilterObjectclass     | inetorgperson                                                                          |
| ldapUuidGroupAttribute        | auto                                                                                   |
| ldapUuidUserAttribute         | auto                                                                                   |
| turnOffCertCheck              | 0                                                                                      |
| turnOnPasswordChange          | 0                                                                                      |
| useMemberOfToDetectMembership | 1                                                                                      |
+-------------------------------+----------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Independent, in this case the NextCloud desktop app was used.

**Operating system:** Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors in error log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"mYt6KJj5oAYahrRlxE9d","remoteAddr":"xxx","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT \\\"path\\\", \\\"fileid\\\" FROM \\\"oc_filecache\\\" WHERE \\\"storage\\\" = ? AND \\\"path\\\" LIKE ?' with params [false, \\\"xxx\\\\\\\/xxx\\\\\\\/%\\\"]:\\n\\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \\\"\\\"\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"path\\\", ...', Array)\\n#2 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/DB\\\/Connection.php(194): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT \\\"path\\\", ...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(526): OC\\\\DB\\\\Connection->executeQuery('SELECT `path`, ...', Array)\\n#4 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheWrapper.php(191): OC\\\\Files\\\\Cache\\\\Cache->moveFromCache(Object(OCA\\\\Files_Sharing\\\\Cache), 'xxx\\\/xxx...', 'files\\\/yyy\\\/fr...')\\n#5 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheJail.php(313): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheWrapper->moveFromCache(Object(OCA\\\\Files_Sharing\\\\Cache), 'xxx\\\/xxx...', 'files\\\/yyy\\\/fr...')\\n#6 \\\/var\\\/www\\\/cloud\\\/apps\\\/files_sharing\\\/lib\\\/Cache.php(106): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheJail->moveFromCache(Object(OCA\\\\Files_Sharing\\\\Cache), 'xxx\\\/xxx...', 'xxx...')\\n#7 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Updater.php(198): OCA\\\\Files_Sharing\\\\Cache->moveFromCache(Object(OCA\\\\Files_Sharing\\\\Cache), 'xxx\\\/xxx...', 'xxx...')\\n#8 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Files\\\/View.php(330): OC\\\\Files\\\\Cache\\\\Updater->renameFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'xxx\\\/xxx...', 'xxx...')\\n#9 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Files\\\/View.php(804): OC\\\\Files\\\\View->renameUpdate(Object(OCA\\\\Files_Trashbin\\\\Storage), Object(OCA\\\\Files_Trashbin\\\\Storage), 'xxx\\\/xxx...', 'xxx...')\\n#10 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(268): OC\\\\Files\\\\View->rename('xxx\\\/xxx...', 'yyy\\\/xxx...')\\n#11 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(642): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->move('xxx\\\/xxx...', 'yyy\\\/xxx...')\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#15 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud\\\/...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91,\"User\":\"user\"}","level":4,"time":"2017-01-07T07:51:48+00:00","method":"MOVE","url":"\/cloud\/remote.php\/webdav\/xxx\/xxx\/xxx","user":"user","version":"11.0.0.10"}
{"reqId":"faUVljRznnZTGahMMIQs","remoteAddr":"xxx","app":"PHP","message":"fopen(\/media\/data\/nextcloud\/xxx\/files\/xxx\/xxx\/xxx): failed to open stream: No such file or directory at \/var\/www\/cloud\/lib\/private\/Files\/Storage\/Local.php#287","level":3,"time":"2017-01-07T07:52:38+00:00","method":"MOVE","url":"\/cloud\/remote.php\/webdav\/xxx\/xxx\/xxx","user":"xxx","version":"11.0.0.10"}
+ one identical failure for each file
```

Note that the returned HTTP status was 201 which does not signal any problem even though an exception was raised.
</details>

Please let me know if you need additional information. Unfortunately this is a problem is not easily reproducible and it is also the first observed problem of its kind. By the way, thanks to all devs for your efforts!

**Comment by nickvergessen** [comment]
Please open a new issue with more details once you know how to reproduce this.

**Comment by fgrsnau** [comment]
Could you please do not close valid bugs and hint me to possibilities of providing further information? I find it very frightening that a file storage solution allows the filesystem and database to easily get out of sync.

The underlying issue still remains unsolved. For an up-to-date Nextcloud instance (11.0.2 stable) I can reproduce the same error 100% by just moving a directory from one share to another one. The source and destinations are shared by different users, so in total we have 3 users here (me, user of src share and user of dest share). When I move a directory, the cloud shows a little flash message stating that an error occured. The physical files are correctly moved, but the database is not updated correctly. Running `occ files:scan --all` fixes this and the files are visible in the new location.
 
I was digging a little bit deeper today. The failure is visible in https://github.com/nextcloud/server/blob/4821c00ea81797fcb5a99c31105ad42be598f113/lib/private/Files/Cache/Cache.php#L515 as `sourceStorageId` is `false`. This is, of course, not a valid integer in Postgres integer and we get this nice error: `ERROR:  invalid input syntax for integer: \"\"`

I tracked this value back to https://github.com/nextcloud/server/blob/4821c00ea81797fcb5a99c31105ad42be598f113/apps/files_sharing/lib/Cache.php#L81.

Unfortunately, I don’t know how to debug this further. Can you push me into the right direction?

**Comment by fgrsnau** [comment]
I am not sure if I am observing the original bug or a different one. The situation is quite different to the initial description.

I have a fully reproducible test case for this slightly different bug (which leads to exactly the same database error as in my initial post). Therefore I filed another bug #4169.
