### ISSUE TITLE
It throws an error while updating and i cannot use the cloud anymore

### ISSUE THREAD

**Issue by Tix-Hosting** [nextcloud/server#31033]
### Steps To Reproduce

I have following Error:

The Maintenance Mode turned on by itself... Then i deactivadet it and was greeted by the message to update nextcloud. Doing this the CLI said there are no updates. Afer that i runned the occ upgrade... but this failed:

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <passwords> ...
An unhandled exception has been thrown:
ParseError: syntax error, unexpected 'ConfigurationService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/nextcloud/apps/passwords/lib/Migration/CliDatabaseObjectRepair.php:45
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
nextcloud/vm#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
nextcloud/vm#2 [internal function]: spl_autoload_call()
nextcloud/vm#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(112): ReflectionClass->__construct()
nextcloud/vm#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
nextcloud/vm#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
nextcloud/vm#6 /var/www/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
nextcloud/vm#7 /var/www/nextcloud/lib/private/Repair.php(141): OC\ServerContainer->query()
nextcloud/vm#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(1064): OC\Repair->addStep()
nextcloud/vm#9 /var/www/nextcloud/lib/private/legacy/OC_App.php(1013): OC_App::executeRepairSteps()
nextcloud/vm#10 /var/www/nextcloud/lib/private/Updater.php(353): OC_App::updateApp()
nextcloud/vm#11 /var/www/nextcloud/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
nextcloud/vm#12 /var/www/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
nextcloud/vm#13 /var/www/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
nextcloud/vm#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
nextcloud/vm#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
nextcloud/vm#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
nextcloud/vm#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
nextcloud/vm#18 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
nextcloud/vm#19 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
nextcloud/vm#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
nextcloud/vm#21 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ upgrade failed
```

### Expected Result

Just that it works

### Actual Result

It is Broken

### Build Version

apperantly the newest and not the newest at the same time

### Environment

By using the scripts

### Environment Details

OP: Debian 20

**Comment by enoch85** [comment]
Please use this to fill in your issue template: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by szaimen** [comment]
Hello @Tix-Hosting, please report this to https://github.com/marius-wieschollek/passwords/issues thanks!

**Comment by fixthemoney** [comment]
I have the same issue. Passwords app failed during update. 
`occ app:disable passwords` got me back up and running until I can figure out how to repair it.

**Comment by fixthemoney** [comment]
FYI, was able to upgrade the app normally then enable it. Not sure what that was all about.
