### ISSUE TITLE
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0

### ISSUE THREAD

**Issue by spicemint** [nextcloud/server#31154]
Linux 5.16.1-arch1-1 x86_64, nginx/1.20.2, PHP 8.0.14,  mysql 10.6.5, Nextcloud 23.0.0, preview generation 4.0.0

Running from cli:
`occ preview:generate-all -vvv david`

would expect it to run and finish without any errors, however, fails 

```
2022-02-12T10:30:29+00:00 Generating previews for /david/files/Photos/20-06-30 19-19-59 0034.bmp
An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument nextcloud/previewgenerator#2 ($height) must be greater than 0 in /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php:780
Stack trace:
#0 /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php(780): imagecreatetruecolor()
nextcloud/previewgenerator#1 /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php(616): OC_Image->imagecreatefrombmp()
nextcloud/previewgenerator#2 /usr/share/webapps/nextcloud/lib/private/Preview/Image.php(52): OC_Image->loadFromFile()
nextcloud/previewgenerator#3 /usr/share/webapps/nextcloud/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\Image->getThumbnail()
nextcloud/previewgenerator#4 /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
nextcloud/previewgenerator#5 /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
nextcloud/previewgenerator#6 /usr/share/webapps/nextcloud/lib/private/PreviewManager.php(227): OC\Preview\Generator->generatePreviews()
nextcloud/previewgenerator#7 /var/lib/nextcloud/apps/previewgenerator/lib/Command/Generate.php(243): OC\PreviewManager->generatePreviews()
nextcloud/previewgenerator#8 /var/lib/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile()
nextcloud/previewgenerator#9 /var/lib/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
nextcloud/previewgenerator#10 /var/lib/nextcloud/apps/previewgenerator/lib/Command/Generate.php(192): OCA\PreviewGenerator\Command\Generate->parseFolder()
nextcloud/previewgenerator#11 /var/lib/nextcloud/apps/previewgenerator/lib/Command/Generate.php(144): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
nextcloud/previewgenerator#12 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
nextcloud/previewgenerator#13 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
nextcloud/previewgenerator#14 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
nextcloud/previewgenerator#15 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
nextcloud/previewgenerator#16 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
nextcloud/previewgenerator#17 /usr/share/webapps/nextcloud/console.php(99): OC\Console\Application->run()
nextcloud/previewgenerator#18 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
nextcloud/previewgenerator#19 {main}
```

info on the image it fails/stops:

```
mediainfo "/var/nextcloud/david/files/Photos/20-06-30 19-19-59 0034.bmp"
General
Complete name                            : /var/nextcloud/david/files/Photos/20-06-30 19-19-59 0034.bmp
Format                                   : Bitmap
File size                                : 2.82 MiB

Image
Format                                   : RGB
Width                                    : 846 pixels
Height                                   : 1 164 pixels
Color space                              : RGB
Bit depth                                : 24 bits
Method                                   : Top down
```

how to fix?

**Comment by st3iny** [comment]
Thanks for your report. There is no fix available but I'll investigate further.

**Comment by st3iny** [comment]
My findings so far: We are using a custom method for loading bmp files (`\OC_Image::imagecreatefrombmp()`). However, since PHP 7.2 there is a [builtin method](https://www.php.net/manual/de/function.imagecreatefrombmp.php) for that. We should use it.

**Comment by acsfer** [comment]
This should be fixed already: https://github.com/nextcloud/server/pull/29800
