### ISSUE TITLE
[Bug]: Weather APP https://api.opentopodata.org/v1/srtm30mAPI error : 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#31245]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Weather App not working 

### Steps to reproduce

1.Lunch Dashboard 
2.
3.

### Expected behavior

![image](https://user-images.githubusercontent.com/59488153/154541498-a9466b63-db40-48c9-8813-fd8caa94117d.png)

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "1.1.1.4",
            "cloud.next.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "https:\/\/cloud.next.com",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "simpleSignUpLink.shown": false,
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,1",
        "skeletondirectory": "",
        "default_phone_region": "US",
        "allow_local_remote_servers": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - officeonline: 1.1.2
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 4.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.2.0
  - sendent: 1.2.10
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - socialsharing_email: 2.4.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login: 4.1.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - circles: 22.1.1
  - encryption
  - user_ldap
```

### Nextcloud Logs

```shell
{"reqId":"NSrNXTBCjdWV2iZ1bTW6","level":2,"time":"2022-02-17T17:51:08+00:00","remoteAddr":"1.1.1.4","user":"admin","app":"weather_status","method":"PUT","url":"/ocs/v2.php/apps/weather_status/api/v1/location","message":"https://api.opentopodata.org/v1/srtm30mAPI error : GuzzleHttp\\Exception\\ServerException: Server error: `GET https://api.opentopodata.org/v1/srtm30m?locations=41.7071104%2C-87.8444544` resulted in a `521 ` response in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php:113\nStack trace:\n#0 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create()\n#1 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()\n#2 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler()\n#3 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\TaskQueue->run()\n#5 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#6 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#7 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#8 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#9 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Promise\\Promise->wait()\n#10 /var/www/nextcloud/lib/private/Http/Client/Client.php(223): GuzzleHttp\\Client->request()\n#11 /var/www/nextcloud/apps/weather_status/lib/Service/WeatherStatusService.php(415): OC\\Http\\Client\\Client->get()\n#12 /var/www/nextcloud/apps/weather_status/lib/Service/WeatherStatusService.php(232): OCA\\WeatherStatus\\Service\\WeatherStatusService->requestJSON()\n#13 /var/www/nextcloud/apps/weather_status/lib/Service/WeatherStatusService.php(189): OCA\\WeatherStatus\\Service\\WeatherStatusService->getAltitude()\n#14 /var/www/nextcloud/apps/weather_status/lib/Controller/WeatherStatusController.php(94): OCA\\WeatherStatus\\Service\\WeatherStatusService->setLocation()\n#15 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(217): OCA\\WeatherStatus\\Controller\\WeatherStatusController->setLocation()\n#16 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(126): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#17 /var/www/nextcloud/lib/private/AppFramework/App.php(157): OC\\AppFramework\\Http\\Dispatcher->dispatch()\n#18 /var/www/nextcloud/lib/private/Route/Router.php(302): OC\\AppFramework\\App::main()\n#19 /var/www/nextcloud/ocs/v1.php(62): OC\\Route\\Router->match()\n#20 /var/www/nextcloud/ocs/v2.php(23): require_once('...')\n#21 {main}","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36","version":"23.0.2.1","id":"620e8b12e7172"}
```

**Comment by acsfer** [comment]
https://api.opentopodata.org/v1/srtm30m?locations=41.7071104%2C-87.8444544 is down.
Surely a temporary error, nothing Nextcloud can do about.

**Comment by andyxheli** [comment]
Thanks! I'll close this out.
