### ISSUE TITLE
[Bug]: Cannot run occ after upgrading to 23.0.2

### ISSUE THREAD

**Issue by xkill** [nextcloud/server#31330]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since I upgraded to Nexcloud 23.0.2 I cannot use occ:

```
# sudo -u www-data php occ
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve userId! in /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:138
Stack trace:
#0 /srv/http/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query()
#1 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\ServerContainer->query()
#2 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#3 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#4 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#5 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#6 /srv/http/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query()
#7 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\ServerContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#10 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /srv/http/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query()
#13 /srv/http/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#14 /srv/http/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#15 /srv/http/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#16 /srv/http/nextcloud/occ(11): require_once('/srv/http/cloud...')
#17 {main}

Next OCP\AppFramework\QueryException: Could not resolve collectorService! Class collectorService does not exist in /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:100
Stack trace:
#0 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#1 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#2 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#3 /srv/http/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#4 /srv/http/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query()
#5 /srv/http/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#6 /srv/http/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#7 /srv/http/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#8 /srv/http/nextcloud/occ(11): require_once('/srv/http/cloud...')
#9 {main}

Next Exception: Failed to construct console command 'OCA\MediaDC\Command\CollectorCleanupCommand': Could not resolve collectorService! Class collectorService does not exist in /srv/http/nextcloud/lib/private/Console/Application.php:223
Stack trace:
#0 /srv/http/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#1 /srv/http/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#2 /srv/http/nextcloud/occ(11): require_once('/srv/http/cloud...')
```

### Steps to reproduce

1. Upgrade Nextcloud
2. Try to run occ from command line
3.

### Expected behavior

Manage to execute occ

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
I cannot run occ
```

### List of activated Apps

```shell
I cannot run occ
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by xkill** [comment]
Fixed: Seems a problem with the mediadc app. I disabled it through the web interface and now occ works fine.
