### ISSUE TITLE
[Bug]: occ files:scan: Exception during scan: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by wansing** [nextcloud/server#31507]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I've uploaded a few thousand files with SSH and have tried to run `occ files:scan` in order to index them. This results in an PHP error:

```
# occ files:scan jane_doe
Starting scan for user 1 out of 1 (jane_doe)
Exception during scan: trim(): Passing null to parameter #1 ($string) of type string is deprecated
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler()
#1 /usr/share/webapps/nextcloud/apps/user_external/lib/base.php(69): trim()
#2 /usr/share/webapps/nextcloud/lib/private/User/User.php(136): OCA\user_external\Base->getDisplayName()
#3 /usr/share/webapps/nextcloud/apps/circles/lib/Service/FederatedUserService.php(484): OC\User\User->getDisplayName()
#4 /usr/share/webapps/nextcloud/apps/circles/lib/ShareByCircleProvider.php(553): OCA\Circles\Service\FederatedUserService->getLocalFederatedUser()
#5 /usr/share/webapps/nextcloud/lib/private/Share20/Manager.php(1375): OCA\Circles\ShareByCircleProvider->getSharedWith()
#6 /usr/share/webapps/nextcloud/apps/files_sharing/lib/MountProvider.php(90): OC\Share20\Manager->getSharedWith()
#7 /usr/share/webapps/nextcloud/lib/private/Files/Config/MountProviderCollection.php(118): OCA\Files_Sharing\MountProvider->getMountsForUser()
#8 /usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php(429): OC\Files\Config\MountProviderCollection->addMountForUser()
#9 /usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php(354): OC\Files\Filesystem::initMountPoints()
#10 /usr/share/webapps/nextcloud/lib/private/legacy/OC_Util.php(326): OC\Files\Filesystem::init()
#11 /usr/share/webapps/nextcloud/lib/private/Files/Utils/Scanner.php(115): OC_Util::setupFS()
#12 /usr/share/webapps/nextcloud/lib/private/Files/Utils/Scanner.php(200): OC\Files\Utils\Scanner->getMounts()
#13 /usr/share/webapps/nextcloud/apps/files/lib/Command/Scan.php(143): OC\Files\Utils\Scanner->scan()
#14 /usr/share/webapps/nextcloud/apps/files/lib/Command/Scan.php(199): OCA\Files\Command\Scan->scanFiles()
#15 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#16 /usr/share/webapps/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#17 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#18 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#19 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#20 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#21 /usr/share/webapps/nextcloud/console.php(99): OC\Console\Application->run()
#22 /usr/share/webapps/nextcloud/occ(11): require_once('...')
#23 {main}
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```

### Steps to reproduce

1. upload some files to `/var/lib/nextcloud/data/jane_doe/files/`
2. run `occ files:scan jane_doe`

### Expected behavior

The command should return without an error.

### Installation method

Other

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Other

### Database engine version

SQlite

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "redacted.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "23.0.2.1",
        "overwrite.cli.url": "https:\/\/redacted.example.com",
        "installed": true,
        "appstoreenabled": false,
        "skeletondirectory": "",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "redacted.example.com",
                    12345,
                    "ssl",
                    "redacted.example.com",
                    true,
                    false
                ]
            }
        ],
        "app_install_overwrite": [
            "user_external"
        ],
        "theme": "",
        "loglevel": 0,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/wapps",
                "writable": true
            }
        ],
        "filesystem_check_changes": 1,
        "sharing.enable_share_mail": false,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "23456",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "config_is_read_only": true,
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.0.6
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.1
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_external: 2.1.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
Results in an internal server error. Log shows same error message as above:

{"reqId":"P4hnlhrE0XLBM2lg1ld3","level":3,"time":"2022-03-09T14:55:15+00:00","remoteAddr":"::1","user":"jane_doe","app":"PHP","method":"GET","url":"/index.php/settings/integrity/failed","message":"trim(): Passing null to parameter #1 ($string) of type string is deprecated at /usr/share/webapps/nextcloud/apps/user_external/lib/base.php#69","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.2.1","exception":{"Exception":"Error","Message":"trim(): Passing null to parameter #1 ($string) of type string is deprecated at /usr/share/webapps/nextcloud/apps/user_external/lib/base.php#69","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/share/webapps/nextcloud/apps/user_external/lib/base.php","line":69,"function":"trim"},{"file":"/usr/share/webapps/nextcloud/lib/private/User/User.php","line":136,"function":"getDisplayName","class":"OCA\\user_external\\Base","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/circles/lib/Service/FederatedUserService.php","line":484,"function":"getDisplayName","class":"OC\\User\\User","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/circles/lib/ShareByCircleProvider.php","line":553,"function":"getLocalFederatedUser","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Share20/Manager.php","line":1375,"function":"getSharedWith","class":"OCA\\Circles\\ShareByCircleProvider","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/files_sharing/lib/MountProvider.php","line":90,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":118,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php","line":429,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php","line":354,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Util.php","line":326,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Mount/Manager.php","line":91,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/View.php","line":1385,"function":"find","class":"OC\\Files\\Mount\\Manager","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Node/Root.php","line":200,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Node/LazyFolder.php","line":65,"function":"call_user_func_array"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Node/LazyFolder.php","line":142,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/AppData/AppData.php","line":141,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/JSCombiner.php","line":96,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/JSResourceLocator.php","line":115,"function":"process","class":"OC\\Template\\JSCombiner","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/JSResourceLocator.php","line":71,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/TemplateLayout.php","line":388,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/TemplateLayout.php","line":216,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Template.php","line":331,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":88,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"P4hnlhrE0XLBM2lg1ld3","level":3,"time":"2022-03-09T14:55:15+00:00","remoteAddr":"::1","user":"jane_doe","app":"PHP","method":"GET","url":"/index.php/settings/integrity/failed","message":"Return type of OCA\\Deck\\Db\\RelationalEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /usr/share/webapps/nextcloud/apps/deck/lib/Db/RelationalEntity.php#66","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.2.1","exception":{"Exception":"Error","Message":"Return type of OCA\\Deck\\Db\\RelationalEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /usr/share/webapps/nextcloud/apps/deck/lib/Db/RelationalEntity.php#66","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Db/RelationalEntity.php","line":28,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/composer/composer/ClassLoader.php","line":571,"args":["/usr/share/webapps/nextcloud/apps/deck/lib/Db/RelationalEntity.php"],"function":"include"},{"file":"/usr/share/webapps/nextcloud/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Db/Acl.php","line":26,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/composer/composer/ClassLoader.php","line":571,"args":["/usr/share/webapps/nextcloud/apps/deck/lib/Db/Acl.php"],"function":"include"},{"file":"/usr/share/webapps/nextcloud/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Db/BoardMapper.php","line":190,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Db/BoardMapper.php","line":117,"function":"findAllByUser","class":"OCA\\Deck\\Db\\BoardMapper","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php","line":698,"function":"findAllForUser","class":"OCA\\Deck\\Db\\BoardMapper","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Share20/Manager.php","line":1375,"function":"getSharedWith","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":118,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php","line":429,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Filesystem.php","line":354,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Util.php","line":326,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Mount/Manager.php","line":91,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/View.php","line":1385,"function":"find","class":"OC\\Files\\Mount\\Manager","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Node/Root.php","line":200,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Node/LazyFolder.php","line":65,"function":"call_user_func_array"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/Node/LazyFolder.php","line":142,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Files/AppData/AppData.php","line":141,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/JSCombiner.php","line":96,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/JSResourceLocator.php","line":115,"function":"process","class":"OC\\Template\\JSCombiner","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/JSResourceLocator.php","line":71,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/TemplateLayout.php","line":388,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/TemplateLayout.php","line":216,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Template.php","line":331,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":88,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

### Additional info

Arch Linux, Webserver: Caddy

```
nextcloud 23.0.2-1
caddy 2.4.6-1
php 8.1.3-1
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by josephsellers** [comment]
I was getting this issue, but I just reran `occ files:scan --all` and I have no errors and it worked as it should. 

I am now on 25.0.3

Thanks for fixing this folks!

**Comment by szaimen** [comment]
Thanks for verifying!
