### ISSUE TITLE
[Bug]: OCP\AppFramework\QueryException: Could not resolve logger! Class logger does not exist Update failed

### ISSUE THREAD

**Issue by zhongjiancong** [nextcloud/server#31512]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Manually update the version
Update from 19.0.8 to 19.0.10

### Steps to reproduce

1.Copy the new version

2.Execute directory permission and occ execute permission settings
chown -Rf apache:apache /var/www/html && chmod u+x /var/www/html/occ

find /var/www/html/ -type d -exec chmod 750 {} \;
find /var/www/html/ -type f -exec chmod 640 {} \;

3.renew
sudo -u apache php occ upgrade

### Expected behavior

Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
OCP\AppFramework\QueryException: Could not resolve logger! Class logger does not exist
Update failed
Maintenance mode is kept active
Reset log level

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

MySQL

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "19.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "activity_expire_days": 365,
        "wnd.logging.enable": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.1.3
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.4.2
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - contactsinteraction
  - encryption
  - files_downloadactivity
  - files_external
  - files_rightclick
  - survey_client
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Cleared logs before update
```

### Additional info

no.

**Comment by szaimen** [comment]
Sry but NC19 is not supported anymore. Feel free to open a thread on https://help.nextcloud.com to get some help on this

**Comment by zhongjiancong** [comment]
I know that nc19 is no longer supported, I need to update from version 19 to the latest version 23, and now this problem prevents me from updating.

**Comment by PSeQXh** [comment]
Same issue here, found a solution for me, bug might be related to some change from ILogger to Psr Logging Interface which results in dependency fall back reflection no longer working in lib/private/AppFramework/Utility/SimpleContainer.php's resolve function.

Passing `-vvv` to `occ upgrade` did not change its output for me, `php occ maintenance:repair -vvv` gave a full exception trace:
```
In SimpleContainer.php line 107:

  [OCP\AppFramework\QueryException]
  Could not resolve logger! Class logger does not exist

Exception trace:
  at /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php:107
 OC\AppFramework\Utility\SimpleContainer->resolve() at /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->query() at /var/www/virtual/user/html/lib/private/ServerContainer.php:149
 OC\ServerContainer->query() at /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php:78
 OC\AppFramework\Utility\SimpleContainer->buildClass() at /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php:101
 OC\AppFramework\Utility\SimpleContainer->resolve() at /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->query() at /var/www/virtual/user/html/lib/private/ServerContainer.php:149
 OC\ServerContainer->query() at /var/www/virtual/user/html/lib/private/Repair.php:161
 OC\Repair::getRepairSteps() at /var/www/virtual/user/html/core/Command/Maintenance/Repair.php:83
 OC\Core\Command\Maintenance\Repair->execute() at /var/www/virtual/user/html/3rdparty/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/virtual/user/html/3rdparty/symfony/console/Application.php:1012
 Symfony\Component\Console\Application->doRunCommand() at /var/www/virtual/user/html/3rdparty/symfony/console/Application.php:272
 Symfony\Component\Console\Application->doRun() at /var/www/virtual/user/html/3rdparty/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/virtual/user/html/lib/private/Console/Application.php:215
 OC\Console\Application->run() at /var/www/virtual/user/html/console.php:100
 require_once() at /var/www/virtual/user/html/occ:11
```

Slightly altering SimpleContainer.php resulted in another insightful stack trace:
```
TypeError: Argument 4 passed to OC\Repair\RepairDavShares::__construct() must implement interface PsrExt\Log\LoggerInterface, null given in /var/www/virtual/user/html/lib/private/Repair/RepairDavShares.php:54
Stack trace:
#0 [internal function]: OC\Repair\RepairDavShares->__construct(Object(OC\AllConfig), Object(OC\DB\Connection), Object(OC\Group\Manager), NULL)
#1 /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php(84): ReflectionClass->newInstanceArgs(Array)
#2 /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php(101): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 /var/www/virtual/user/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Repair\\Repai...')
#4 /var/www/virtual/user/html/lib/private/ServerContainer.php(149): OC\AppFramework\Utility\SimpleContainer->query('OC\\Repair\\Repai...', true)
#5 /var/www/virtual/user/html/lib/private/Repair.php(161): OC\ServerContainer->query('OC\\Repair\\Repai...')
#6 /var/www/virtual/user/html/core/Command/Maintenance/Repair.php(83): OC\Repair::getRepairSteps()
#7 /var/www/virtual/user/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Repair->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/virtual/user/html/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/virtual/user/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Repair), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/virtual/user/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/virtual/user/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/virtual/user/html/console.php(100): OC\Console\Application->run()
#13 /var/www/virtual/user/html/occ(11): require_once('/var/www/virtua...')
#14 {main}
```
Reverting the previous change and only changing the first line of resolve function implementation in `SimpleContainer.php` from `public function resolve($name) {` to `public function resolve($name) { if ($name == 'logger') { $name = 'OC\Log\PsrLoggerAdapter'; }` to pass a valid Psr Logging Interface Implementation to use in the fall back reflection call when looking for logger class fixed the issue for me, any `Repair step`'s could log to stdout again, `Update successful`

(in my case this fix was needed upgrading from 19.0.4 to 19.0.13 and again from 19.0.13 to 20.0.14, after that the web updater worked flawlessly, integrity checks will flag SimpleContainer.php)
