### ISSUE TITLE
preview-generator app [Bug]: NC23.0.3 Regression - Argument #2 ($height) must be greater than 0

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#31727]
after a second, i realized it is related to preview-generator app ... wrong location maybe...

Hi, 

23.0.3 regression for command occ preview:pre-generate
 Same as  #252 #29632  and others, only NC version changes ...

system : Debian 11.3, php8.0.17, apache 2.x.54, mariadb10.x.15, Nc23.0.3

`sudo -u www-data php occ preview:pre-generate
An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /var/www/html/lib/private/legacy/OC_Image.php:898
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(898): imagecreatetruecolor()
#1 /var/www/html/lib/private/legacy/OC_Image.php(717): OC_Image->imagecreatefrombmp()
#2 /var/www/html/lib/private/Preview/Image.php(52): OC_Image->loadFromFile()
#3 /var/www/html/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\Image->getThumbnail()
#4 /var/www/html/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/html/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/html/lib/private/PreviewManager.php(227): OC\Preview\Generator->generatePreviews()
#7 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(217): OC\PreviewManager->generatePreviews()
#8 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(195): OCA\PreviewGenerator\Command\PreGenerate->processFile()
#9 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(163): OCA\PreviewGenerator\Command\PreGenerate->processRow()
#10 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(131): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\PreGenerate->execute()
#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#15 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#16 /var/www/html/console.php(99): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('...')
`

### Steps to reproduce

1. sudo -u www-data php occ preview:pre-generate

### Expected behavior

no error, clean exit.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xxx.xxx",
            "192.168.1.71"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": xxxx,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "check_data_directory_permissions": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "max_filesize_animated_gifs_public_sharing": -1,
        "session_keepalive": true,
        "auto_logout": false,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": 99,
        "0": 99,
        "enable_previews": true,
        "preview_max_memory": -1,
        "preview_max_x": 4096,
        "preview_max_y": 4096,
        "preview_max_filesize_image": 50,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita"
        ],
        "default_language": "fr",
        "default_phone_region": "FR",
        "knowledgebaseenabled": true,
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/xxxxxxxxxx",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "has_internet_connection": true,
        "connectivity_check_domains": [
            "www.nextcloud.com",
            "www.google.fr",
            "www.cnn.com",
            "www.google.com"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "cache_chunk_gc_ttl": 86400,
        "auth.bruteforce.protection.enabled": false,
        "loglevel": 1,
        "updater.release.channel": "stable",
        "maintenance": false,
        "app_install_overwrite": [
            "occweb",
            "defaultgroup",
            "issuetemplate",
            "flowupload",
            "twofactor_email",
            "previewgenerator",
            "twofactor_webauthn",
            "data_request"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "theme": ""
    }
}
```

### List of activated Apps

```shell
sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - announcementcenter: 6.1.1
  - apporder: 0.14.0
  - bruteforcesettings: 2.3.0
  - camerarawpreviews: 0.7.15
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - external: 3.10.2
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.12.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - flowupload: 1.1.3
  - geoblocker: 0.5.4
  - groupfolders: 11.1.2
  - groupquota: 0.1.7
  - impersonate: 1.10.0
  - issuetemplate: 0.7.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 4.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.13.1
  - recommendations: 1.2.0
  - registration: 1.4.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - terms_of_service: 1.9.3
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_email: 2.1.1
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_totp: 6.2.0
  - twofactor_webauthn: 0.3.1
  - unsplash: 1.2.4
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - circles: 23.1.0
  - dashboard: 7.1.0
  - encryption
  - files_external
  - user_ldap
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
nextcloud.log not relevant.

sudo -u www-data php occ preview:pre-generate
An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /var/www/html/lib/private/legacy/OC_Image.php:898
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(898): imagecreatetruecolor()
#1 /var/www/html/lib/private/legacy/OC_Image.php(717): OC_Image->imagecreatefrombmp()
#2 /var/www/html/lib/private/Preview/Image.php(52): OC_Image->loadFromFile()
#3 /var/www/html/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\Image->getThumbnail()
#4 /var/www/html/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/html/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/html/lib/private/PreviewManager.php(227): OC\Preview\Generator->generatePreviews()
#7 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(217): OC\PreviewManager->generatePreviews()
#8 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(195): OCA\PreviewGenerator\Command\PreGenerate->processFile()
#9 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(163): OCA\PreviewGenerator\Command\PreGenerate->processRow()
#10 /var/www/html/apps/previewgenerator/lib/Command/PreGenerate.php(131): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\PreGenerate->execute()
#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#15 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#16 /var/www/html/console.php(99): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('...')
```

**Comment by stratege1401** [comment]
Still investigating.... It seem i may have found what's wrong. Just need more time to check it... It may be a missconfiguration on my side ( missing ffmpeg )... Will try to finish testing and post results asap... sorry

**Comment by stratege1401** [comment]
Realized my system was missing ffmpeg.
Command `occ preview:pre-generate -vvv`  is now "working" ( task still running ).

preview:generate-all still failing

Still investigating to verify if it is a regression

**Comment by stratege1401** [comment]
well, after 19h26mns, the occ crash:

`
An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /var/www/html/lib/private/legacy/OC_Image.php:898
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(898): imagecreatetruecolor()
#1 /var/www/html/lib/private/legacy/OC_Image.php(717): OC_Image->imagecreatefrombmp()
#2 /var/www/html/lib/private/Preview/Image.php(52): OC_Image->loadFromFile()
#3 /var/www/html/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\Image->getThumbnail()
#4 /var/www/html/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/html/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/html/lib/private/PreviewManager.php(227): OC\Preview\Generator->generatePreviews()
#7 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(243): OC\PreviewManager->generatePreviews()
#8 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile()
#9 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(192): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(138): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#13 /var/www/html/lib/private/User/Manager.php(656): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#14 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(139): OC\User\Manager->callForSeenUsers()
#15 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#16 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#17 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#20 /var/www/html/console.php(99): OC\Console\Application->run()
#21 /var/www/html/occ(11): require_once('...')
`

**Comment by stratege1401** [comment]
issue not replicated after a complete NC23.0.3 freash install. closing.
