### ISSUE TITLE
[Bug]: Deleted files app | icon missing from *.com/index.php/apps/files pages | deleting files instantly purged 

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/server#31918]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I run two different NC instances on the same physical server managed with Virtualmin. 

One instance uses the localhost's MariaDB server and doesn't have this problem, and that server is new as of October 2021 but fully updated. 

The other instance is having the problem, and it reaches out to a 192.168.???.??? server (_it's only a MySQL server_) for its remote data connection, and has been running since maybe NC 11 was a new release. 

Both instances are upgraded fully (Nextcloud Hub II 23.0.3) with no error messages on the `*.com/index.php/settings/admin/overview` page except for the false negatives of:
```
The PHP OPcache module is not properly configured. See the [documentation ↗](https://docs.nextcloud.com/server/23/go.php?to=admin-php-opcache) for more information.

    The OPcache buffer is nearly full. To assure that all scripts can be hold in cache, it is recommended to apply opcache.memory_consumption to your PHP configuration with a value higher than 128.
    The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.
```
The settings are over the required numbers in the `./php8.0/php.ini` files for the virtual server/sub-server that the NC-23 instances run from. `opcache.memory_consumption=256` & `opcache.interned_strings_buffer=32`.

I also observed that the missing item is true for admin and regular user accounts on Windows and Ubuntu client computers. While poking around the bare-metal server, I see that `./data/<user ID>/files_trashbin` is present for some user accounts. If a user deletes a file since this problem was noticed, nothing goes into that `~files_trashbin/files` folder. Users who deleted files prior to the problem being noticed still have contents in that  `~files_trashbin/files` folder.

I'm not sure if the bug happened farther in the past than yesterday when I ran my upgrades back to back from 22.2.3 to 22.2.4 then to 23.0.3.

I also tried disabling the app and then re-enabling it, but it changed nothing.

### Steps to reproduce

1. Navigate to Files part of Nextcloud.
2. Observe the icon & text for "Deleted Files" is not present.

### Expected behavior

I expect to be able to observe the tool for dealing with deleted files.

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
/public_html/nextcloud$ php8.0 occ config:list system
An unhandled exception has been thrown:
Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found in /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php:38
Stack trace:
#0 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/composer/composer/ClassLoader.php(571): include()
#1 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/AppInfo/Application.php(99): Composer\Autoload\ClassLoader->loadClass()
#3 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#4 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#5 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#6 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#7 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#8 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\AppFramework\DependencyInjection\DIContainer->query()
#9 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/AppInfo/Application.php(94): OC\AppFramework\Utility\SimpleContainer->get()
#10 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#11 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#13 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#14 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#15 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#16 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/Command/Trashbin/Cleanup.php(52): OC\AppFramework\Utility\SimpleContainer->get()
#17 [internal function]: OCA\GroupFolders\Command\Trashbin\Cleanup->__construct()
#18 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): ReflectionClass->newInstanceArgs()
#19 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#20 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#21 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#22 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#23 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#24 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#25 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#26 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/occ(11): require_once('...')
#27 {main}
```

### List of activated Apps

```shell
/public_html/nextcloud$ php8.0 occ app:list
An unhandled exception has been thrown:
Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found in /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php:38
Stack trace:
#0 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/composer/composer/ClassLoader.php(571): include()
#1 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/AppInfo/Application.php(99): Composer\Autoload\ClassLoader->loadClass()
#3 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#4 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#5 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#6 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#7 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#8 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\AppFramework\DependencyInjection\DIContainer->query()
#9 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/AppInfo/Application.php(94): OC\AppFramework\Utility\SimpleContainer->get()
#10 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#11 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#13 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#14 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#15 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#16 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/groupfolders/lib/Command/Trashbin/Cleanup.php(52): OC\AppFramework\Utility\SimpleContainer->get()
#17 [internal function]: OCA\GroupFolders\Command\Trashbin\Cleanup->__construct()
#18 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): ReflectionClass->newInstanceArgs()
#19 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#20 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#21 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#22 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#23 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#24 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#25 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#26 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/occ(11): require_once('...')
#27 {main}
```

### Nextcloud Signing status

```shell
Hmm. We’re having trouble finding that site.

We can’t connect to the server at yournextcloud.tld.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.
```

### Nextcloud Logs

```shell
Skip to main content
Skip to navigation of app
Level	App	Message		Time
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
seconds ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
a minute ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
2 minutes ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
2 minutes ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
2 minutes ago
Fatal	no app in context	Error: Interface "OCA\Files_Versions\Versions\IVersionBackend" not found	
2 minutes ago
```

### System information

Link: [https://cloud.ruppssites.com/index.php/s/qTMxkSQ96jywbeJ](https://cloud.ruppssites.com/index.php/s/qTMxkSQ96jywbeJ)
Password: `Jp7%2)Y^g`

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
