### ISSUE TITLE
[Bug]: Update to Nextcloud 23.0.5 fails with: Error: Call to a member function getAppValue()

### ISSUE THREAD

**Issue by k2iuh** [nextcloud/server#32931]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Trying to upgrade Nextcloud from 23.0.2 to 23.0.5 on Ubuntu 20.04 with occ results in an error when trying to update libresign.

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <libresign> ...
An unhandled exception has been thrown:
Error: Call to a member function getAppValue() on null in /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php:108
Stack trace:
#0 /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php(67): OCA\Libresign\Migration\Version2040Date20211027183759->getLibesignCli()
#1 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(547): OCA\Libresign\Migration\Version2040Date20211027183759->postSchemaChange()
#2 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(425): OC\DB\MigrationService->executeStep()
#3 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(1021): OC\DB\MigrationService->migrate()
#4 /var/www/html/nextcloud/lib/private/Updater.php(353): OC_App::updateApp()
#5 /var/www/html/nextcloud/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
#6 /var/www/html/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
#7 /var/www/html/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#13 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#14 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#15 {main}
```

### Steps to reproduce

1. Enter Command ´sudo -u www-data ./occ upgrade´

### Expected behavior

Update is successful

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED MANUALLY***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/krummeck.ddns.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": true,
        "theme": "",
        "loglevel": 0,
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "spreed"
        ],
        "debug": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - firstrunwizard: 2.12.0
  - integration_github: 1.0.2
  - libresign: 2.4.5
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - activity: 2.7.0
  - admin_audit
  - comments: 1.4.0
  - encryption
  - external: 3.9.0
  - federation: 1.4.0
  - files_bpm: 0.2.1
  - files_videoplayer: 1.3.0
  - sharebymail: 1.4.0
  - spreed: 12.1.2
  - systemtags: 1.4.0
  - user_ldap
```

**Comment by solracsf** [comment]
this is a libresign issue it seem.
Report to libresign at https://github.com/LibreSign/libresign

**Comment by k2iuh** [comment]
You're right. I was able to perform the update, disabling libresign:

``` sudo -u www-data php occ app:disable libresign```
