### ISSUE TITLE
Backends provided no user object

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#3302]
Hi

I found these 2 Erros in my logs for a folder which is shared by email.
Any Ideas what it could be?

```
{"reqId":"RPcwtINNjjnV3FrjLLP\/","remoteAddr":"*****","app":"files","message":"Backends provided no user object for ","level":3,"time":"2017-01-26T22:48:32+01:00","method":"GET","url":"\/s\/xZxdj8Ouuj6nO1H\/download","user":"--","version":"11.0.1.2"}
```

```json
{"reqId":"RPcwtINNjjnV3FrjLLP\/","remoteAddr":" *****","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder(NULL)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_downloadactivity\\\/lib\\\/Activity\\\/Listener.php(141): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder(NULL)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_downloadactivity\\\/lib\\\/Activity\\\/Listener.php(77): OCA\\\\FilesDownloadActivity\\\\Activity\\\\Listener->getSourcePathAndOwner('\\\/mySharedFolder...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_downloadactivity\\\/lib\\\/AppInfo\\\/Application.php(47): OCA\\\\FilesDownloadActivity\\\\Activity\\\\Listener->readFile('\\\/mySharedFolder...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\FilesDownloadActivity\\\\AppInfo\\\\Application->listenReadFile(Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1243): OC_Hook::emit('OC_Filesystem', 'read', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1113): OC\\\\Files\\\\View->runHooks(Array, '\\\/mySharedFolder...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(967): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/mySharedFolder...', Array, 'rb')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(429): OC\\\\Files\\\\View->fopen('\\\/mySharedFolder...', 'rb')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(305): OC\\\\Files\\\\View->readfile('\\\/mySharedFolder...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(120): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/mySharedFolder...', 'mySharedFile...', Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(534): OC_Files::get('\\\/mySharedFolder...', 'mySharedFile...', Array)\\n#14 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('xZxdj8Ouuj6nO1H', NULL, '', '')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#19 \\\/var\\\/www\\\/nextcloud\\\/core\\\/routes.php(100): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#20 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#21 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#22 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/xZxdj8Ouuj6n...')\\n#23 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":366}","level":3,"time":"2017-01-26T22:48:32+01:00","method":"GET","url":"\/s\/xZxdj8Ouuj6nO1H\/download","user":"--","version":"11.0.1.2"}
```

Operating System:
Ubuntu 16.04 LTS
Apache 2.4.18
PHP 7.0.8
Nextcloud 11.0.1

**Comment by nickvergessen** [comment]
Do you happen to know what was done?

**Comment by EasyPeasy1** [comment]
No not really

**Comment by nickvergessen** [comment]
Do you use remote (federated) shares?

**Comment by EasyPeasy1** [comment]
I dont use federated shares. It is turned off

**Comment by EasyPeasy1** [comment]
@nickvergessen : I think that these error always appears if someone is downloading a file by a shared link
