### ISSUE TITLE
[Bug]: TypeError during RefreshWebcalJob

### ISSUE THREAD

**Issue by Derkades** [nextcloud/server#33020]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This started happening somewhere this week, it could be since the 24.0.2 update but not sure.
```
TypeError: strtoupper(): Argument #1 ($string) must be of type string, array given in /var/www/html/3rdparty/sabre/vobject/lib/Document.php:243
Stack trace:
#0 /var/www/html/3rdparty/sabre/vobject/lib/Document.php(243): strtoupper(Array)
#1 /var/www/html/3rdparty/sabre/vobject/lib/Document.php(214): Sabre\VObject\Document->getClassNameForPropertyValue(Array)
#2 /var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(436): Sabre\VObject\Document->createProperty('DTSTART', NULL, Array)
#3 /var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(223): Sabre\VObject\Parser\MimeDir->readProperty('DTSTART;VALUE=D...')
#4 /var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(209): Sabre\VObject\Parser\MimeDir->parseLine('DTSTART;VALUE=D...')
#5 /var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(174): Sabre\VObject\Parser\MimeDir->parseLine('DTSTART;VALUE=D...')
#6 /var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(90): Sabre\VObject\Parser\MimeDir->parseDocument()
#7 /var/www/html/3rdparty/sabre/vobject/lib/Reader.php(47): Sabre\VObject\Parser\MimeDir->parse('BEGIN:VCALENDAR...', 0)
#8 /var/www/html/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php(273): Sabre\VObject\Reader::read('BEGIN:VCALENDAR...')
#9 /var/www/html/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php(101): OCA\DAV\CalDAV\WebcalCaching\RefreshWebcalService->queryWebcalFeed(Array, Array)
#10 /var/www/html/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php(115): OCA\DAV\CalDAV\WebcalCaching\RefreshWebcalService->refreshSubscription('principals/user...', 'canvasuvanl')
#11 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\DAV\BackgroundJob\RefreshWebcalJob->run(Array)
#12 /var/www/html/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php(108): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#13 /var/www/html/cron.php(151): OCA\DAV\BackgroundJob\RefreshWebcalJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#14 {main}
```

### Steps to reproduce

No clear reproduction steps, this is occasionally outputted by the cron script

### Expected behavior

N/A

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - admin_audit: 1.14.0
  - calendar: 3.4.0
  - cloud_federation_api: 1.7.0
  - contacts: 4.1.1
  - dav: 1.22.0
  - drawio: 1.0.3
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - forms: 2.5.1
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - activity: 2.14.3
  - breezedark: 24.0.1
  - circles: 23.0.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.2.0
  - encryption
  - extract: 1.3.5
  - facerecognition: 0.9.5
  - federation: 1.13.0
  - files_rightclick: 1.2.0
  - firstrunwizard: 2.7.0
  - keeweb: 0.6.9
  - maps: 0.1.10
  - nextcloud_announcements: 1.4.0
  - password_policy: 1.11.0
  - privacy: 1.5.0
  - recommendations: 0.5.0
  - registration: 1.5.0
  - richdocuments: 6.1.0
  - richdocumentscode: 21.11.402
  - serverinfo: 1.11.0
  - sharebymail: 1.13.0
  - support: 1.0.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.14.4
  - user_ldap
  - user_status: 1.1.1
  - weather_status: 1.1.0
```

**Comment by Derkades** [comment]
Still happening in 25.0.1

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Derkades** [comment]
I am on 25.0.3 and it does still happen exactly twice per day, at 01:35 and 13:35.

**Comment by Derkades** [comment]
Still affects 25.0.5

**Comment by Derkades** [comment]
Seems to be resolved, probably by 26.0.1 or 26.0.2
