### ISSUE TITLE
[Bug]: Transfer-ownership with '--transfer-incoming-shares' fails with "Could not get proper share mount"

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#33176]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

While transferring ownership of files, it fails with `Could not get proper share mount` (see below)

### Steps to reproduce

1. Execute OCC command (see below)
2. Error

### Nextcloud Logs

```shell
~$ occ files:transfer-ownership --transfer-incoming-shares=1 source.user dest.user

Validating quota
Analysing files of source.user ...
 42778 [============================]
Collecting all share information for files and folders of source.user ...
    9 [============================]
Transferring files to dest.user/files/transferred from source.user on 2022-07-08 17-23-25 ...
Restoring shares ...
Could not restore share with id 29588:Could not get proper share mount for 60602450. Failing since else the next calls are called with null : #0 /lib/private/Share20/Manager.php(972): OC\Share20\Manager->generalCreateChecks()
#1 /apps/files/lib/Service/OwnershipTransferService.php(421): OC\Share20\Manager->updateShare()
#2 /apps/files/lib/Service/OwnershipTransferService.php(185): OCA\Files\Service\OwnershipTransferService->restoreShares()
#3 /apps/files/lib/Command/TransferOwnership.php(150): OCA\Files\Service\OwnershipTransferService->transfer()
#4 /3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\TransferOwnership->execute()
#5 /3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 /3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#9 /console.php(99): OC\Console\Application->run()
#10 /occ(11): require_once('...')
#11 {main}
 1/9 [===>------------------------]  11%Could not restore share with id 33797:Could not get proper share mount for 60218539. Failing since else the next calls are called with null : #0 /lib/private/Share20/Manager.php(972): OC\Share20\Manager->generalCreateChecks()
#1 /apps/files/lib/Service/OwnershipTransferService.php(421): OC\Share20\Manager->updateShare()
#2 /apps/files/lib/Service/OwnershipTransferService.php(185): OCA\Files\Service\OwnershipTransferService->restoreShares()
#3 /apps/files/lib/Command/TransferOwnership.php(150): OCA\Files\Service\OwnershipTransferService->transfer()
#4 /3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\TransferOwnership->execute()
#5 /3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 /3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#9 /console.php(99): OC\Console\Application->run()
#10 /occ(11): require_once('...')
#11 {main}
 9/9 [============================] 100%
Collecting all incoming share information for files and folders of source.user ...
    5 [============================]
Collecting all incoming share information for files and folders of dest.user ...
    1 [============================]
Restoring incoming shares ...
 5/5 [============================] 100%
```

**Comment by MrArcaneGates** [comment]
I have the same issue, sadly i have a very small sample size but what i can say so far is that in my instance it doesn't happen for all users, there are users where i can transfer files and shares just fine.

The user where the issue DOES occur also has access to a Group Folder (Plugin), do you also use this per chance?

**Comment by solracsf** [comment]
No Group Folders for me.

**Comment by fthiery** [comment]
Group folders for me

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by solracsf** [comment]
It doesn't on 24.0.9. 25.0.3 is too much buggy to put it on production.

**Comment by szaimen** [comment]
> It doesn't on 24.0.9.

closing then

**Comment by solracsf** [comment]
Reopening as it can be reproduced on 26.0.9.

```
# occ files:transfer-ownership --path="FTV" user1 user2
Validating quota
Analysing files of user1 ...
  538 [============================]
Collecting all share information for files and folders of user1 ...
  125 [============================]
Transferring files to user2/files/transferred from BCKP - user1 on 2023-07-27 10-10-15 ...
Restoring shares ...
 19/61 [========>-------------------]  31%

Could not restore share with id 27501:Could not get proper share mount for 59393753.
Failing since else the next calls are called with null :

#0 /var/www/nextcloud/lib/private/Share20/Manager.php(993): OC\Share20\Manager->generalCreateChecks()
#1 /var/www/nextcloud/apps/files/lib/Service/OwnershipTransferService.php(424): OC\Share20\Manager->updateShare()
#2 /var/www/nextcloud/apps/files/lib/Service/OwnershipTransferService.php(188): OCA\Files\Service\OwnershipTransferService->restoreShares()
#3 /var/www/nextcloud/apps/files/lib/Command/TransferOwnership.php(150): OCA\Files\Service\OwnershipTransferService->transfer()
#4 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\TransferOwnership->execute()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#9 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#10 /var/www/nextcloud/occ(11): require_once('...')
#11 {main}
```
