### ISSUE TITLE
LDAP User can access nextcloud without authorized user

### ISSUE THREAD

**Issue by rapITler** [nextcloud/server#3331]
### Steps to reproduce
1. For the first time I configured the ldapsearch without any restrictions against AD I retrieved all users.
2. Then I restricted the authorization to only two AD-groups which are successfully displayed at the Users page.
3. Unfortunately all AD-User which are not allowed to login can still login perhaps caused by step 1.

### Expected behaviour
Only authorized users which are in the permitted groups should have the ability to login.

### Actual behaviour
It seems that every user from the AD can login may caused by step 1.

### Server configuration
**Operating system**: 
CentOS 7

**Web server:** 
Apache/2.4.6

**Database:** 
mysql  Ver 15.1 Distrib 5.5.52-MariaDB,

**PHP version:**
PHP 7.0.14

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.1
  - comments: 1.1.0
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_antivirus: 1.0.0.0
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
"system": {
        "instanceid": "REMOVED",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "REMOVED",
            "REMOVED"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "REMOVED",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "REMOVED",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "REMOVED",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "cron_log": true,
        "logfile": "\/www\/log\/nextcloud.log",
        "log_rotate_size": 104857600,
        "mail_smtpmode": "smtp",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "auth.bruteforce.protection.enabled": true,
        "remember_login_cookie_lifetime": 86400,
        "session_lifetime": 28800,
        "session_keepalive": true,
        "updater.release.channel": "production",

```
</details>

**Are you using external storage, if yes which one:**
volume over SAN

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:**
LDAP against AD

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                             |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                           |
| hasPagedResultSupport         |                                                                                                                                                             |
| homeFolderNamingRule          |                                                                                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                                                                                           |
| ldapAgentName                 | CN=REMOVED,OU=ServiceAccount,OU=Users,OU=_Global,dc=removed,dc=removed                                                                      |
| ldapAgentPassword             | ***                                                                                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                                                                                             |
| ldapAttributesForUserSearch   |                                                                                                                                                             |
| ldapBackupHost                |                                                                                                                                                             |
| ldapBackupPort                |                                                                                                                                                             |
| ldapBase                      | dc=removed,dc=removed                                                                                                                                            |
| ldapBaseGroups                | dc=removed,dc=removed                                                                                                                                          |
| ldapBaseUsers                 | dc=removed,dc=removed                                                                                                                                            |
| ldapCacheTTL                  | 600                                                                                                                                                         |
| ldapConfigurationActive       | 1                                                                                                                                                           |
| ldapDynamicGroupMemberURL     |                                                                                                                                                             |
| ldapEmailAttribute            | mail                                                                                                                                                        |
| ldapExperiencedAdmin          | 1                                                                                                                                                           |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                             |
| ldapExpertUUIDUserAttr        |                                                                                                                                                             |
| ldapExpertUsernameAttr        |                                                                                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                                                                          |
| ldapGroupFilter               | (&(|(objectclass=group))(|(memberof:1.2.840.113556.1.4.1941:=cn=removed,OU=removed,OU=Groups,OU=Admin,DC=removed,DC=removed)))                         |
| ldapGroupFilterGroups         | removed.BASIC;removed.ADVANCED                                                                                                          |
| ldapGroupFilterMode           | 0                                                                                                                                                           |
| ldapGroupFilterObjectclass    | group                                                                                                                                                       |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                      |
| ldapHost                      | removed                                                                                                                                       |
| ldapIgnoreNamingRules         |                                                                                                                                                             |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(samaccountname=%uid))                                                                                                            |
| ldapLoginFilterAttributes     |                                                                                                                                                             |
| ldapLoginFilterEmail          | 0                                                                                                                                                           |
| ldapLoginFilterMode           | 0                                                                                                                                                           |
| ldapLoginFilterUsername       | 1                                                                                                                                                           |
| ldapNestedGroups              | 0                                                                                                                                                           |
| ldapOverrideMainServer        |                                                                                                                                                             |
| ldapPagingSize                | 500                                                                                                                                                         |
| ldapPort                      | 389                                                                                                                                                         |
| ldapQuotaAttribute            |                                                                                                                                                             |
| ldapQuotaDefault              |                                                                                                                                                             |
| ldapTLS                       | 0                                                                                                                                                           |
| ldapUserDisplayName           | displayname                                                                                                                                                 |
| ldapUserDisplayName2          |                                                                                                                                                             |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof:1.2.840.113556.1.4.1941:=CN=removed,OU=removed,OU=Groups,OU=Admin,DC=removed,DC=removed)(primaryGroupID=97011)))) |
| ldapUserFilterGroups          | removed.BASIC                                                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                                                                           |
| ldapUserFilterObjectclass     | user                                                                                                                                                        |
| ldapUuidGroupAttribute        | auto                                                                                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                                                                                        |
| turnOffCertCheck              | 0                                                                                                                                                           |
| turnOnPasswordChange          | 0                                                                                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                                                                                           |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
</details>

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>
```
[Mon Jan 30 09:36:18.872154 2017] [mpm_prefork:notice] [pid 7802] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jan 30 09:36:24.944097 2017] [suexec:notice] [pid 17778] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Jan 30 09:36:24.945277 2017] [ssl:warn] [pid 17778] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Jan 30 09:36:24.970801 2017] [auth_digest:notice] [pid 17778] AH01757: generating secret for digest authentication ...
[Mon Jan 30 09:36:24.971397 2017] [lbmethod_heartbeat:notice] [pid 17778] AH02282: No slotmem from mod_heartmonitor
[Mon Jan 30 09:36:24.972437 2017] [ssl:warn] [pid 17778] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Jan 30 09:36:25.009945 2017] [mpm_prefork:notice] [pid 17778] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.14 configured -- resuming normal operations
[Mon Jan 30 09:36:25.009994 2017] [core:notice] [pid 17778] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Jan 30 15:41:52.447664 2017] [mpm_prefork:notice] [pid 17778] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jan 30 15:41:53.509461 2017] [suexec:notice] [pid 31063] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Jan 30 15:41:53.510450 2017] [ssl:warn] [pid 31063] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Jan 30 15:41:53.533404 2017] [auth_digest:notice] [pid 31063] AH01757: generating secret for digest authentication ...
[Mon Jan 30 15:41:53.533856 2017] [lbmethod_heartbeat:notice] [pid 31063] AH02282: No slotmem from mod_heartmonitor
[Mon Jan 30 15:41:53.534653 2017] [ssl:warn] [pid 31063] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Jan 30 15:41:53.562258 2017] [mpm_prefork:notice] [pid 31063] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.14 configured -- resuming normal operations
[Mon Jan 30 15:41:53.562276 2017] [core:notice] [pid 31063] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Jan 30 16:44:31.534562 2017] [mpm_prefork:notice] [pid 31063] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jan 30 16:44:32.593249 2017] [suexec:notice] [pid 1027] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Jan 30 16:44:32.594224 2017] [ssl:warn] [pid 1027] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Jan 30 16:44:32.616774 2017] [auth_digest:notice] [pid 1027] AH01757: generating secret for digest authentication ...
[Mon Jan 30 16:44:32.617280 2017] [lbmethod_heartbeat:notice] [pid 1027] AH02282: No slotmem from mod_heartmonitor
[Mon Jan 30 16:44:32.618187 2017] [ssl:warn] [pid 1027] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Jan 30 16:44:32.644735 2017] [mpm_prefork:notice] [pid 1027] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.14 configured -- resuming normal operations
[Mon Jan 30 16:44:32.644758 2017] [core:notice] [pid 1027] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"WI9cj8H4Q2nce4fc8H3ingAAAAQ","remoteAddr":"removed","app":"index","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"removed is not a valid user anymore\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/lib\\\/private\\\/User\\\/User.php(261): OCA\\\\User_LDAP\\\\User_LDAP->getHome('removed...')\\n#1 \\\/www\\\/lib\\\/private\\\/Files\\\/Mount\\\/LocalHomeMountProvider.php(42): OC\\\\User\\\\User->getHome()\\n#2 \\\/www\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(98): OC\\\\Files\\\\Mount\\\\LocalHomeMountProvider->getHomeMountForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#3 \\\/www\\\/lib\\\/private\\\/Files\\\/Filesystem.php(438): OC\\\\Files\\\\Config\\\\MountProviderCollection->getHomeMountForUser(Object(OC\\\\User\\\\User))\\n#4 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(372): OC\\\\Files\\\\Filesystem::initMountPoints('removed...')\\n#5 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('removed...')\\n#6 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#7 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#8 \\\/www\\\/lib\\\/private\\\/Share20\\\/Share.php(160): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('removed...')\\n#9 \\\/www\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(261): OC\\\\Share20\\\\Share->getNode()\\n#10 \\\/www\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(291): OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->validateShare(Object(OC\\\\Share20\\\\Share))\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->showShare('l34WLhAYfFRc2PJ', '')\\n#12 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#14 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#15 \\\/www\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'showShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/www\\\/core\\\/routes.php(88): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'showShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/www\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/l34WLhAYfFRc...')\\n#20 \\\/www\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":380}","level":3,"time":"2017-01-30T16:32:32+01:00","method":"GET","url":"\/index.php\/s\/l34WLhAYfFRc2PJ","user":"--","version":"11.0.1.2"}
{"reqId":"WI9ckkygRCkan@9VHj--zAAAAAo","remoteAddr":"removed","app":"index","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"removed is not a valid user anymore\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/lib\\\/private\\\/User\\\/User.php(261): OCA\\\\User_LDAP\\\\User_LDAP->getHome('removed...')\\n#1 \\\/www\\\/lib\\\/private\\\/Files\\\/Mount\\\/LocalHomeMountProvider.php(42): OC\\\\User\\\\User->getHome()\\n#2 \\\/www\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(98): OC\\\\Files\\\\Mount\\\\LocalHomeMountProvider->getHomeMountForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#3 \\\/www\\\/lib\\\/private\\\/Files\\\/Filesystem.php(438): OC\\\\Files\\\\Config\\\\MountProviderCollection->getHomeMountForUser(Object(OC\\\\User\\\\User))\\n#4 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(372): OC\\\\Files\\\\Filesystem::initMountPoints('removed...')\\n#5 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('removed...')\\n#6 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#7 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#8 \\\/www\\\/lib\\\/private\\\/Share20\\\/Share.php(160): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('removed...')\\n#9 \\\/www\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(261): OC\\\\Share20\\\\Share->getNode()\\n#10 \\\/www\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(291): OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->validateShare(Object(OC\\\\Share20\\\\Share))\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->showShare('l34WLhAYfFRc2PJ', '')\\n#12 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#14 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#15 \\\/www\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'showShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/www\\\/core\\\/routes.php(88): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'showShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/www\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/l34WLhAYfFRc...')\\n#20 \\\/www\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":380}","level":3,"time":"2017-01-30T16:32:34+01:00","method":"GET","url":"\/index.php\/s\/l34WLhAYfFRc2PJ","user":"--","version":"11.0.1.2"}
{"reqId":"WI9ckjyaUh@9GeuXvl@CiwAAAAU","remoteAddr":"removed","app":"index","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"removed is not a valid user anymore\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/lib\\\/private\\\/User\\\/User.php(261): OCA\\\\User_LDAP\\\\User_LDAP->getHome('removed...')\\n#1 \\\/www\\\/lib\\\/private\\\/Files\\\/Mount\\\/LocalHomeMountProvider.php(42): OC\\\\User\\\\User->getHome()\\n#2 \\\/www\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(98): OC\\\\Files\\\\Mount\\\\LocalHomeMountProvider->getHomeMountForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#3 \\\/www\\\/lib\\\/private\\\/Files\\\/Filesystem.php(438): OC\\\\Files\\\\Config\\\\MountProviderCollection->getHomeMountForUser(Object(OC\\\\User\\\\User))\\n#4 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(372): OC\\\\Files\\\\Filesystem::initMountPoints('removed...')\\n#5 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('removed...')\\n#6 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#7 \\\/www\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#8 \\\/www\\\/lib\\\/private\\\/Share20\\\/Share.php(160): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('removed...')\\n#9 \\\/www\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(261): OC\\\\Share20\\\\Share->getNode()\\n#10 \\\/www\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(291): OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->validateShare(Object(OC\\\\Share20\\\\Share))\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->showShare('l34WLhAYfFRc2PJ', '')\\n#12 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#14 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'showShare')\\n#15 \\\/www\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'showShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/www\\\/core\\\/routes.php(88): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'showShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/www\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/l34WLhAYfFRc...')\\n#20 \\\/www\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":380}","level":3,"time":"2017-01-30T16:32:35+01:00","method":"GET","url":"\/index.php\/s\/l34WLhAYfFRc2PJ","user":"--","version":"11.0.1.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
don't have the browser log.
```
</details>

**Comment by blizzz** [comment]
The login filter (``(&(&(|(objectclass=user)))(samaccountname=%uid))``) misses the restrictions which are present in the user filter. Recreate the Login filter in the wizard and you should be OK.

We are likely to merge user and login filters in the future to avoid cases like this.
