### ISSUE TITLE
can't delete folder - allowed memory size exhausted

### ISSUE THREAD

**Issue by thomasooo** [nextcloud/server#3340]
### Steps to reproduce
Big database and try to delete folder.

Here are similar problems:  https://github.com/nextcloud/nextcloud-snap/issues/171#issue-199388303
https://help.nextcloud.com/t/cant-delete-folder-on-local-external-storage/7732

### Expected behaviour
Delete folder

### Actual behaviour
Log: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at /var/www/html/cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#104

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache2

**Database:** MySQL 5.5.54

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Migrated from Owncloud to nextcloud 11 and then to nextcloud 11

**Where did you install Nextcloud from:**

**The content of config/config.php:**
<details>

```
{
    "system": {
        "integrity.check.disabled": true,
        "instanceid": "ocdgygnbxlcu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.88.248",
            "efervescenspi.ddns.net",
            "localhost"
        ],
        "datadirectory": "\/var\/www\/html\/STORAGE\/CLOUD\/data",
        "overwrite.cli.url": "http:\/\/localhost\/cloud",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Bratislava",
        "installed": true,
        "loglevel": 2,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "blacklisted_files": [],
        "theme": "",
        "maintenance": false,
        "mail_from_address": "cloud",
        "mail_domain": "efervescenspi.ddns.net",
        "htaccess.RewriteBase": "\/cloud"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "1.3.1",
            "ocsid": "174738",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "3284"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "core": {
            "OC_Channel": "stable",
            "installedat": "1456211221.7756",
            "lastcron": "1485878350",
            "lastupdateResult": "[]",
            "lastupdatedat": "1485867422",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "{\"core\":{\"INVALID_HASH\":{\".htaccess\":{\"expected\":\"11e2db30f0cf23df1b5aa1cdf329a8c88d253f86e43f9e7af1b30969eb0175030103b138e2f7ab7608c902bbb57a5d578c2c0ca09f3abf2ef83415f4bc6f6e20\",\"current\":\"184444579a6188a9e8e22bd2a0829efe2a98721fd2ca4d98953219bb5e7839c1b4b4067c97eb46b18ff89bbe47ffa9dd4971e7a2d9209254b9f3652dfbae5615\"}}}}",
            "previewsCleanedUp": "1",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "updater.secret.created": "1481184845",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": ""
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "15.1.1",
            "ocsid": "169116",
            "signed": "true",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "ownbackup": {
            "enabled": "yes",
            "installed_version": "16.11.0",
            "ocsid": "170674",
            "signed": "true",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "previewgenerator": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.1.25",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "last_report": "{\"id\":\"ocdgygnbxlcu\",\"items\":[[\"server\",\"version\",\"11.0.1.2\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.0.15\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",2147483648],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.5.54\"],[\"database\",\"size\",490946560],[\"apps\",\"activity\",\"2.4.1\"],[\"apps\",\"audioplayer\",\"disabled\"],[\"apps\",\"calendar\",\"1.5.0\"],[\"apps\",\"comments\",\"1.1.0\"],[\"apps\",\"dav\",\"1.1.1\"],[\"apps\",\"documents\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.1.1\"],[\"apps\",\"federation\",\"1.1.1\"],[\"apps\",\"files\",\"1.6.1\"],[\"apps\",\"files_mv\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.0.1\"],[\"apps\",\"files_sharing\",\"1.1.1\"],[\"apps\",\"files_texteditor\",\"2.2\"],[\"apps\",\"files_trashbin\",\"1.1.0\"],[\"apps\",\"files_versions\",\"1.4.0\"],[\"apps\",\"files_videoplayer\",\"1.0.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"2.0\"],[\"apps\",\"gallery\",\"16.0.0\"],[\"apps\",\"galleryplus\",\"disabled\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"nextcloud_announcements\",\"1.0\"],[\"apps\",\"notes\",\"2.2.0\"],[\"apps\",\"notifications\",\"1.0.1\"],[\"apps\",\"ownbackup\",\"16.11.0\"],[\"apps\",\"password_policy\",\"1.1.0\"],[\"apps\",\"provisioning_api\",\"1.1.0\"],[\"apps\",\"richdocuments\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.1.1\"],[\"apps\",\"sharebymail\",\"1.0.1\"],[\"apps\",\"survey_client\",\"0.1.5\"],[\"apps\",\"systemtags\",\"1.1.3\"],[\"apps\",\"tasks\",\"disabled\"],[\"apps\",\"templateeditor\",\"0.2\"],[\"apps\",\"theming\",\"1.1.1\"],[\"apps\",\"twofactor_backupcodes\",\"1.0.0\"],[\"apps\",\"updatenotification\",\"1.1.1\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"usage_charts\",\"disabled\"],[\"apps\",\"workflowengine\",\"1.1.1\"],[\"stats\",\"num_files\",464096],[\"stats\",\"num_users\",6],[\"stats\",\"num_storages\",40],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",6],[\"stats\",\"num_storages_other\",32],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",49],[\"files_sharing\",\"num_shares_user\",11],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",38],[\"files_sharing\",\"num_shares_link_no_password\",38],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"33\"],[\"files_sharing\",\"permissions_3_15\",\"5\"],[\"files_sharing\",\"permissions_0_31\",\"11\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1485798254",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "signed": "true",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "cachebuster": "6",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "name": "efervescenspi.ddns.net\/cloud",
            "slogan": "EFERVESCENSPI Cloud",
            "types": "logging",
            "url": "https:\/\/efervescenspi.ddns.net\/cloud"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "updatenotification": {
            "audioplayer": "1.3.1",
            "calendar": "1.4.1",
            "core": "9.1.2",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "notify_groups": "[\"admin\",\"subAdmin\"]",
            "ownbackup": "16.11.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "usage_charts": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}
```

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### MY QUICK FIX:
Nextcloud search for pattern %% in filecache DB.
file **lib/private/Files/Cache/Cache.php** line 597, **method search** (pattern is %%)

Original method search:

```
public function search($pattern) {
		// normalize pattern
		$pattern = $this->normalize($pattern);

		$sql = '
			SELECT `fileid`, `storage`, `path`, `parent`, `name`,
				`mimetype`, `mimepart`, `size`, `mtime`, `encrypted`,
				`etag`, `permissions`, `checksum`
			FROM `*PREFIX*filecache`
			WHERE `storage` = ? AND `name` ILIKE ?';
		$result = $this->connection->executeQuery($sql,
			[$this->getNumericStorageId(), $pattern]
		);

		$files = [];
		while ($row = $result->fetch()) {
			$row['mimetype'] = $this->mimetypeLoader->getMimetypeById($row['mimetype']);
			$row['mimepart'] = $this->mimetypeLoader->getMimetypeById($row['mimepart']);
			$files[] = $row;
		}
		return array_map(function(array $data) {
			return new CacheEntry($data);
		}, $files);
	}
```

My edit:
```
public function search($pattern) {
		// normalize pattern
		$pattern = $this->normalize($pattern);

		if($pattern == '%%'){
			return array();
		}

		$sql = '
			SELECT `fileid`, `storage`, `path`, `parent`, `name`,
				`mimetype`, `mimepart`, `size`, `mtime`, `encrypted`,
				`etag`, `permissions`, `checksum`
			FROM `*PREFIX*filecache`
			WHERE `storage` = ? AND `name` ILIKE ?';
		$result = $this->connection->executeQuery($sql,
			[$this->getNumericStorageId(), $pattern]
		);

		$files = [];
		while ($row = $result->fetch()) {
			$row['mimetype'] = $this->mimetypeLoader->getMimetypeById($row['mimetype']);
			$row['mimepart'] = $this->mimetypeLoader->getMimetypeById($row['mimepart']);
			$files[] = $row;
		}
		return array_map(function(array $data) {
			return new CacheEntry($data);
		}, $files);
	}
```

Just added this three lines

```
if($pattern == '%%'){
	return array();
}
```

after line
`
$pattern = $this->normalize($pattern);`

**Comment by kyrofa** [comment]
You might consider surrounding your config with code tags.

**Comment by nekromant** [comment]
@thomasooo Are you sure this is a working fix? On my instance nc begins to tell something about files being locked.

**Comment by thomasooo** [comment]
Yess, it works for many users. You have probably a different problem, your files are locked. Try this https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883

**Comment by nekromant** [comment]
@thomasooo Hm... might be that the memory exhaustion left some locks dangling. Thanks for the tip!

**Comment by jodlajodla** [comment]
I have the exactly same issue. I did fresh install of NC 10 back in August and I think this issue started appearing after upgrade to Nextcloud 11, which was done in December. I was using OwnCloud for one year before I switched to new virtual machine and NC with almost same set of data and never got such error. Previous virtual machine had 256 MB of RAM with 1 shared core, now I have 2 GB of RAM and 2 shared cores. The difference between files on 256 MB VM (OC) and 2 GB VM (NC) is few folders and files, sizing approximately 1 GB. This is weird since the low end VM was handling OC better then the current one does NC, so this must be a bug in code, not the problem in the improvement of number & size of files.

@thomasooo I didn't check the whole code and don't understand at all what should this code do, but as I see your fix is just a workaround to not "overload" memory with all entries corresponding to query, so it returns empty array. I'm not using this fix yet, but can this cause wrong results for users in any way?

**Comment by thomasooo** [comment]
@jodlajodla This script search for file in filecache. When script search for %%, then it get all files from database (it owerload memory). I don`t know why script search for all files, it is probably bug in calling this search method. When cloud search for any correct pattern (e.g. %some_value%), script run database query and get correct result. I did not recognize any issues after this fix and cloud works normally.

**Comment by oparoz** [comment]
@icewind1991 Does the fix make sense?

**Comment by KekcuHa** [comment]
I also have the same issue:
`{"reqId":"8UEx\/KiTSvAWMyOe1Gl5","remoteAddr":"212.44.153.134","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2017-02-09T07:06:56+00:00","method":"PUT","url":"\/remote.php\/webdav\...","user":"...","version":"11.0.1.2"}`
after applying the fix provided by @thomasooo this issue seems to be gone.

**Comment by cowai** [comment]
@icewind1991  @oparoz  The fix works. But I would assume its better to fix it in the method calling the search().

**Comment by rayheffer** [comment]
Just had the same issue on a fresh install of NC 11.0.1. In fact I had to add the fix below, in addition to removing all of the file locks from the `oc_file_locks table`.
```
if($pattern == '%%'){
	return array();
}
```

**Comment by icewind1991** [comment]
PR is here: https://github.com/nextcloud/server/pull/3828

**Comment by kzhui125** [comment]
I am getting this error, nextcloud 13.02

**Comment by KekcuHa** [comment]
Me too:
```
[Sat May 12 21:25:40.286791 2018] [php7:error] [pid 25165] [client 192.168.1.1:46920] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105

[Sat May 12 21:25:40.287701 2018] [php7:error] [pid 25165] [client 192.168.1.1:46920] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. 
in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105\nStack trace:\n
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)\n
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n
#2 /var/www/owncloud/lib/private/DB/Connection.php(216): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n
#4 /var/www/owncloud/lib/private/DB/QueryBuilder/Q in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115

```
