### ISSUE TITLE
[Bug]: issu upgrading form 24.0.3 to 24.0.4

### ISSUE THREAD

**Issue by rasgra** [nextcloud/server#33523]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud server fails to update from 24.0.3 to 24.0.4, I did an ugly "fix" to get my server accessible again. Details below.

Update log and error report:
```
sudo -u www-data php occ -vvv upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-08-12T22:11:13+00:00 Setting log level to debug
2022-08-12T22:11:13+00:00 Repair step: Repair MySQL collation
2022-08-12T22:11:13+00:00 Repair info: All tables already have the correct collation -> nothing to do
2022-08-12T22:11:13+00:00 Repair step: Repair SQLite autoincrement
2022-08-12T22:11:13+00:00 Repair step: Copy data from accounts table when migrating from ownCloud
2022-08-12T22:11:13+00:00 Repair step: Drop account terms table when migrating from ownCloud
2022-08-12T22:11:13+00:00 Updating database schema
2022-08-12T22:11:13+00:00 Updated database
2022-08-12T22:11:13+00:00 Repair step: Repair MySQL collation
2022-08-12T22:11:13+00:00 Repair info: All tables already have the correct collation -> nothing to do
2022-08-12T22:11:13+00:00 Repair step: Repair mime types
2022-08-12T22:11:13+00:00 Repair step: Clean tags and favorites
2022-08-12T22:11:13+00:00 Repair info: 0 tags of deleted users have been removed.
2022-08-12T22:11:13+00:00 Repair info: 0 tags for delete files have been removed.
2022-08-12T22:11:13+00:00 Repair info: 0 tag entries for deleted tags have been removed.
2022-08-12T22:11:13+00:00 Repair info: 0 tags with no entries have been removed.
2022-08-12T22:11:13+00:00 Repair step: Repair invalid shares
2022-08-12T22:11:13+00:00 Repair step: Move .step file of updater to backup location
2022-08-12T22:11:13+00:00 Repair step: Add move avatar background job
2022-08-12T22:11:13+00:00 Repair info: Repair step already executed
2022-08-12T22:11:13+00:00 Repair step: Add preview cleanup background jobs
2022-08-12T22:11:13+00:00 Repair step: Migrate oauth2_clients table to nextcloud schema
2022-08-12T22:11:13+00:00 Repair info: Update the oauth2_access_tokens table schema.
2022-08-12T22:11:14+00:00 Repair info: Update the oauth2_clients table schema.
2022-08-12T22:11:14+00:00 Repair step: Fix potential broken mount points
2022-08-12T22:11:14+00:00 Repair info: No mounts updated
2022-08-12T22:11:14+00:00 Repair step: Repair language codes
2022-08-12T22:11:14+00:00 Repair step: Install new core bundle components
2022-08-12T22:11:14+00:00 Repair step: Add log rotate job
2022-08-12T22:11:14+00:00 Repair step: Clear frontend caches
2022-08-12T22:11:14+00:00 Repair info: Image cache cleared
An unhandled exception has been thrown:
TypeError: OC\EventDispatcher\ServiceEventListener::__invoke(): Argument #1 ($event) must be of type OCP\EventDispatcher\Event, OC\EventDispatcher\GenericEventWrapper given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264 and defined in /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php:65
Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\EventDispatcher\ServiceEventListener->__invoke()
#1 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#2 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#3 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(122): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#4 /var/www/nextcloud/lib/private/Files/Node/Node.php(118): OC\EventDispatcher\SymfonyAdapter->dispatch()
#5 /var/www/nextcloud/lib/private/Files/Node/File.php(133): OC\Files\Node\Node->sendHooks()
#6 /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php(149): OC\Files\Node\File->delete()
#7 /var/www/nextcloud/lib/private/Template/SCSSCacher.php(386): OC\Files\SimpleFS\SimpleFile->delete()
#8 /var/www/nextcloud/lib/private/Repair/ClearFrontendCaches.php(62): OC\Template\SCSSCacher->resetCache()
#9 /var/www/nextcloud/lib/private/Repair.php(124): OC\Repair\ClearFrontendCaches->run()
#10 /var/www/nextcloud/lib/private/Updater.php(293): OC\Repair->run()
#11 /var/www/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
#12 /var/www/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#13 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#17 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#18 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#19 /var/www/nextcloud/occ(11): require_once('...')
```

The above made the server stuck in update, I "fixed" it (made the server accessible again) by commenting out line 118 in 
`/var/www/nextcloud/lib/private/Files/Node/Node.php `
and then rerunning the upgrade command. My server works again, seemingly without issues, though not sure of the implication of this "fix" at this point, I guess there may be crashes if the event dispatcher is called from other locations.

### Steps to reproduce

1. Update from 24.0.3 to 24.0.4 (using an Ubuntu 22.04 server)

### Expected behavior

Update should finish without throwing an un-handled exception, halting the update and rendering the server in-accessible.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "manually removed, I'd rather not be public with my URL"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.4.1",
        "overwrite.cli.url": "manually removed, I'd rather not be public with my URL",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "SE",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.2
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - drawio: 1.0.3
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - guests: 2.2.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.8
  - maps: 0.2.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recognize: 2.2.0
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - richdocumentscode: 22.5.502
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.4
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - video_converter: 1.0.5
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
Note: This is the file that I mentioned in the description, modification is the specified line only.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/private/Files/Node/Node.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/Files/Node/Node.php] => Array
                        (
                            [expected] => 260682fac0a09ed95fe6a4e36b661565b15275119f4b43eae90cb008abb796c95fb3e995c8ed1a0090e5cd2465cea2c163f6ab6e119297d2a0a5788df72cace2
                            [current] => a239ad60a63e7b56439a6bb7972743ae860281580beeb46a9568d8cbf3f9c00644b025e4c816416e5e7333f00666b3bf5de3ce908985610730faf83ad7306f29
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
Just realized;
I'm missing both the nextcloud.log and the logging file.

I do not have a /settings or /data directory in /var/www/nextcloud, I noticed that I have a /data dir in an old nextcloud ver 22, but not in ver 24
```

**Comment by tacruc** [comment]
Duplicate  #33520 and https://github.com/nextcloud/recognize/issues/279
