### ISSUE TITLE
[Bug]: Upgrade fails due to type error

### ISSUE THREAD

**Issue by super-cooper** [nextcloud/server#33530]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This morning, I tried to upgrade my Nextcloud server. It is currently running in a Docker container based off the `nextcloud:latest` image. I last upgraded to the latest version 2 weeks ago. When I try to perform the upgrade, it fails repeatedly due to what appears to be a type error.

### Steps to reproduce

1. Have an existing server running 24.0.3
2. Pull the `latest` image (24.0.4)
3. Destroy and re-run the container
4. Observe that the upgrade fails

### Expected behavior

The upgrade should complete as it normally does. I've seen it fail before, in which case I either remove the problematic app and re-run. There was one case where the version of database wasn't compatible, so I fixed that. This time, no matter what I try, there is an issue, and I think it's with Nextcloud's code, because it's a typing error.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "filelocking.enabled": true,
        "default_phone_region": "US",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "nextcloud.adamcooper.sh",
            "0": "localhost"
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "opcache.interned_strings_buffer": 256,
        "overwritehost": "nextcloud.adamcooper.sh",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "https:\/\/nextcloud.adamcooper.sh",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "files_external_gdrive",
            "joplin",
            "fulltextsearch",
            "files_fulltextsearch",
            "calendar",
            "carnet",
            "extract",
            "files_texteditor",
            "quicknotes",
            "video_converter",
            "apporder",
            "ransomware_protection",
            "socialsharing_email",
            "socialsharing_twitter",
            "suspicious_login",
            "dropit",
            "podcast",
            "files_antivirus",
            "workflow_pdf_converter",
            "workflow_media_converter",
            "gpgmailer",
            "workflow_script"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "updater.release.channel": "stable",
        "maintenance": true,
        "loglevel": 0,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true,
        "theme": "",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - analytics: 4.3.1
  - apporder: 0.15.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.2
  - checksum: 1.1.4
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.13
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - encryption: 2.12.0
  - event_update_notification: 1.5.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_antivirus: 3.3.1
  - files_automatedtagging: 1.14.0
  - files_external: 1.16.1
  - files_fulltextsearch: 24.0.1
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.2
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - fulltextsearch: 24.0.0
  - integration_discourse: 1.0.2
  - integration_github: 1.0.2
  - integration_google: 1.0.6
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.8
  - maps: 0.2.0
  - mediadc: 0.1.9
  - metadata: 0.16.0
  - news: 18.1.1
  - nextcloud_announcements: 1.13.0
  - notes: 4.4.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - passwords: 2022.6.20
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quicknotes: 0.8.1
  - ransomware_protection: 1.13.0
  - recognize: 2.2.0
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - sharingpath: 0.4.4
  - socialsharing_email: 2.5.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - suspicious_login: 4.2.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_nextcloud_notification: 3.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - video_converter: 1.0.5
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflow_media_converter: 1.4.0
  - workflow_ocr: 1.24.4
  - workflow_script: 1.9.0
  - workflowengine: 2.6.0
Disabled:
  - circles: 22.1.1
  - files_texteditor: 2.14.0
  - user_ldap
  - workflow_pdf_converter: 1.8.0
```

### Nextcloud Signing status

```shell
N/A, since it's in between an upgrade
```

### Nextcloud Logs

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
 - Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Move .step file of updater to backup location
 - Add move avatar background job
     - Repair step already executed
 - Add preview cleanup background jobs
 - Migrate oauth2_clients table to nextcloud schema
     - Update the oauth2_access_tokens table schema.
     - Update the oauth2_clients table schema.
 - Fix potential broken mount points
     - No mounts updated
 - Repair language codes
 - Install new core bundle components
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
An unhandled exception has been thrown:
TypeError: OC\EventDispatcher\ServiceEventListener::__invoke(): Argument #1 ($event) must be of type OCP\EventDispatcher\Event, OC\EventDispatcher\GenericEventWrapper given, called in /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264 and defined in /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php:65
Stack trace:
#0 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OC\EventDispatcher\GenericEventWrapper), '\\OCP\\Files::pos...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OCP\\Files::pos...', Object(OC\EventDispatcher\GenericEventWrapper))
#2 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, '\\OCP\\Files::pos...', Object(OC\EventDispatcher\GenericEventWrapper))
#3 /var/www/html/lib/private/EventDispatcher/SymfonyAdapter.php(122): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OC\EventDispatcher\GenericEventWrapper), '\\OCP\\Files::pos...')
#4 /var/www/html/lib/private/Files/Node/Node.php(118): OC\EventDispatcher\SymfonyAdapter->dispatch('\\OCP\\Files::pos...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#5 /var/www/html/lib/private/Files/Node/File.php(133): OC\Files\Node\Node->sendHooks(Array, Array)
#6 /var/www/html/lib/private/Files/SimpleFS/SimpleFile.php(149): OC\Files\Node\File->delete()
#7 /var/www/html/lib/private/Template/SCSSCacher.php(386): OC\Files\SimpleFS\SimpleFile->delete()
#8 /var/www/html/lib/private/Repair/ClearFrontendCaches.php(62): OC\Template\SCSSCacher->resetCache()
#9 /var/www/html/lib/private/Repair.php(124): OC\Repair\ClearFrontendCaches->run(Object(OC\Repair))
#10 /var/www/html/core/Command/Maintenance/Repair.php(125): OC\Repair->run()
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Repair->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Repair), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/console.php(100): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('/var/www/html/c...')
#18 {main}%
```

### Additional info

I have the `gnupg` PHP extension installed, and the following debian packages:
* libmagickcore-6.q16-6-extra 
* libgpgme-dev 
* sudo 
* python3 
* python3-pip 
* ffmpeg

**Comment by roosemberth** [comment]
I had the same issue; I was able to workaround and successfully complete the upgrade doing the following:

- Disable recognize: `occ app:disable recognize`
- Maintenance repair: `occ maintenance:repair`
- Upgrade: `occ upgrade`
- Disable maintenance mode: `occ maintenance:mode --off`
- Re-enable recognize: `occ app:enable recognize`

**Comment by super-cooper** [comment]
@roosemberth wow, this fixed it! Thank you so much for your help :) I suppose I was mislead by no specific apps appearing in the log; I assumed it was just all base Nextcloud code.
