### ISSUE TITLE
[Bug]: Error: Class "PDO" not found in /var/www/vhosts/cloud.byggvir.de/lib/private/DB/Connection.php:155

### ISSUE THREAD

**Issue by Byggvir** [nextcloud/server#33893]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When starting 

`
sudo -u www-data php occ upgrade 
`

I get the following error on Nexcloud 24.0.4

```
root@example.com:/var/www/vhosts/example.com# sudo -u www-data php occ upgrade
An unhandled exception has been thrown:
Error: Class "PDO" not found in /var/www/vhosts/example.com/lib/private/DB/Connection.php:155
Stack trace:
#0 /var/www/vhosts/example.com/lib/private/AppConfig.php(408): OC\DB\Connection->getQueryBuilder()
#1 /var/www/vhosts/example.com/lib/private/AppConfig.php(176): OC\AppConfig->loadConfigValues()
#2 /var/www/vhosts/example.com/lib/private/AppConfig.php(367): OC\AppConfig->getApps()
#3 /var/www/vhosts/example.com/lib/private/legacy/OC_App.php(983): OC\AppConfig->getValues(false, 'installed_versi...')
#4 /var/www/vhosts/example.com/lib/private/Server.php(713): OC_App::getAppVersions()
#5 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server))
#6 /var/www/vhosts/example.com/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#7 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
#8 /var/www/vhosts/example.com/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...', false)
#9 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#10 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(184): OC\AppFramework\Utility\SimpleContainer->get('OC\\Memcache\\Fac...')
#11 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#12 /var/www/vhosts/example.com/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#13 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OCP\\ICacheFacto...')
#14 /var/www/vhosts/example.com/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OCP\\ICacheFacto...', false)
#15 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCP\\ICacheFacto...')
#16 /var/www/vhosts/example.com/lib/private/Server.php(1105): OC\AppFramework\Utility\SimpleContainer->get('OCP\\ICacheFacto...')
#17 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/vhosts/example.com/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#19 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...')
#20 /var/www/vhosts/example.com/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Lock\\ILocki...', false)
#21 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCP\\Lock\\ILocki...')
#22 /var/www/vhosts/example.com/lib/private/Server.php(2082): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Lock\\ILocki...')
#23 /var/www/vhosts/example.com/lib/private/Files/View.php(122): OC\Server->getLockingProvider()
#24 /var/www/vhosts/example.com/lib/private/Server.php(454): OC\Files\View->__construct()
#25 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server))
#26 /var/www/vhosts/example.com/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#27 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OC\\Files\\Node\\H...')
#28 /var/www/vhosts/example.com/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', false)
#29 /var/www/vhosts/example.com/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OC\\Files\\Node\\H...')
#30 /var/www/vhosts/example.com/lib/private/Server.php(1445): OC\AppFramework\Utility\SimpleContainer->get('OC\\Files\\Node\\H...')
#31 /var/www/vhosts/example.com/lib/base.php(602): OC\Server->boot()
#32 /var/www/vhosts/example.com/lib/base.php(1104): OC::init()
#33 /var/www/vhosts/example.com/console.php(48): require_once('/var/www/vhosts...')
#34 /var/www/vhosts/example.com/occ(11): require_once('/var/www/vhosts...')
#35 {main}root@h1383963:/var/www/vhosts/example.com# rror: Class "PDO" not found in

````

### Steps to reproduce

1. Install Nextcloud latest from today
2. sudo -u www-data php occ upgrade 
3.

### Expected behavior

The script should only use and look for what is in the software.

occ should run without erros.

### Installation method

Community Manual installation with Archive

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
All three command show the same error.

If occ has an error it is useless to retrieve information with occ.
```

### List of activated Apps

```shell
Same result as above
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by Byggvir** [comment]
After deletion all php7.4 and reinstalling
