### ISSUE TITLE
[Bug]: Syncing acalendar ICS fails HTTP500 - This recurrence rule does not generate any valid instances #1423

### ISSUE THREAD

**Issue by marc4s** [nextcloud/server#34790]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dear all, I have opened an issue on sabredav regarding this issue
https://github.com/sabre-io/dav/issues/1423

but maybe davx could have an option to block/pause syncing of elements which are causing trouble because this happens often on my devices and then all ICS are blocked from syncing in general. thanks for your help.

here the details of the original bugreport:

Other ICS Server are syncing those ICS without issues. ﻿What is exactly the issue with those ICS ?
<s:exception>Sabre\VObject\Recur\NoInstancesException</s:exception>
<s:message>This recurrence rule does not generate any valid instances</s:message>

In calendar apps on Smartphones those entrys seems to be valid

--- BEGIN DEBUG INFO ---

SYNCHRONIZATION INFO
Account: Account {name=SURNAME, type=bitfire.at.davdroid}
Authority: com.android.calendar

EXCEPTION
at.bitfire.dav4jvm.exception.HttpException: HTTP 500
at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:5)
at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:3)
at at.bitfire.dav4jvm.DavResource.put(DavResource.kt:2)
at at.bitfire.dav4jvm.DavResource.put$default(Unknown Source:28)
at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$3.invoke(SyncManager.kt:7)
at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$3.invoke(SyncManager.kt:1)
at at.bitfire.davdroid.syncadapter.SyncManager.remoteExceptionContext(SyncManager.kt:1)
at at.bitfire.davdroid.syncadapter.SyncManager.uploadDirty(SyncManager.kt:21)
at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$1$1$1.invoke(SyncManager.kt:2)
at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$1$1$1.invoke(SyncManager.kt:1)
at at.bitfire.davdroid.syncadapter.SyncManager.localExceptionContext(SyncManager.kt:1)
at at.bitfire.davdroid.syncadapter.SyncManager$uploadDirty$1$1.invokeSuspend(SyncManager.kt:2)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

HTTP REQUEST
Request{method=PUT, url=https://servername/remote.php/dav/calendars/USERNAME/af5d6756-30e3-4986-a4bb-6b8948c90879/6bf1bd97-7f8c-4ec7-8bd8-0b47b889d5e3.ics, headers=[If-Match:"d449d020ce0f2afc73cc689712ae5772", User-Agent:DAVx5/4.2.3.4-ose (2022/09/22; dav4jvm; okhttp/4.10.0) Android/11, Accept-Language:de-DE, de;q=0.7, *;q=0.5]}
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.2.3.4-ose ical4j/3.2.5 (org.withouthat.acalendarplus)
BEGIN:VEVENT
DTSTAMP:20221013T052038Z
UID:5aa839bb-d208-4331-8a86-0b10237cd9e5
SEQUENCE:1
SUMMARY:Master your business Coaching Programm
LOCATION:https://url/
DTSTART;TZID=Europe/Berlin:20221003T090000
DTEND;TZID=Europe/Berlin:20221003T103000
RRULE:FREQ=DAILY;UNTIL=20221019T215959Z;INTERVAL=17
EXDATE;TZID=Europe/Berlin:20221003T090000
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Master your business Coaching Programm
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

HTTP RESPONSE
Response{protocol=h2, code=500, message=, url=[https://SERVERNAME/remote.php/dav/calendars/USERNAME/af5d6756-30e3-4986-a4bb-6b8948c90879/6bf1bd97-7f8c-4ec7-8bd8-0b47b889d5e3.ics}](https://servername/remote.php/dav/calendars/USERNAME/af5d6756-30e3-4986-a4bb-6b8948c90879/6bf1bd97-7f8c-4ec7-8bd8-0b47b889d5e3.ics%7D)

<d:error xmlns:d="DAV:" xmlns:s="[http://sabredav.org/ns">](http://sabredav.org/ns%22%3E)
<s:exception>Sabre\VObject\Recur\NoInstancesException</s:exception>
<s:message>This recurrence rule does not generate any valid instances</s:message>
</d:error>

LOCAL RESOURCE
LocalEvent=[eTag=d449d020ce0f2afc73cc689712ae5772, fileName=6bf1bd97-7f8c-4ec7-8bd8-0b47b889d5e3.ics, flags=1, scheduleTag=null, weAreOrgUSERNAME4zer=true, calendar=at.bitfire.davdroid.resource.LocalCalendar@321c7bf, event=Event=[alarms=[BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Master your business Coaching Programm
END:VALARM
], attendees=[], categories=[], classification=null, color=null, description=null, dtEnd=DTEND;TZID=Europe/Berlin:20221003T103000
, dtStart=DTSTART;TZID=Europe/Berlin:20221003T090000
, duration=null, exDates=[EXDATE;TZID=Europe/Berlin:20221003T090000
], exRules=[], exceptions=[], lastModified=null, location=https://us02web.zoom.us/j/84405545581, opaque=true, orgUSERNAME4zer=null, rDates=[], rRules=[RRULE:FREQ=DAILY;UNTIL=20221019T215959Z;INTERVAL=17
], recurrenceId=null, status=STATUS:CONFIRMED
, summary=Master your business Coaching Programm, unknownProperties=[], url=null, userAgents=[org.withouthat.acalendarplus], sequence=1, uid=5aa839bb-d208-4331-8a86-0b10237cd9e5], id=2819]

REMOTE RESOURCE
https://servername/remote.php/dav/calendars/USERNAME/af5d6756-30e3-4986-a4bb-6b8948c90879/6bf1bd97-7f8c-4ec7-8bd8-0b47b889d5e3.ics

SOFTWARE INFORMATION

┌────────────────────────────────┬─────────────┬───────────┬──────────────────────────────┬───────┐
│ Package │ Version │ Code │ Installer │ Notes │
├────────────────────────────────┼─────────────┼───────────┼──────────────────────────────┼───────┤
│ at.bitfire.davdroid │ 4.2.3.4-ose │ 402030402 │ org.fdroid.fdroid.privileged │ │
│ org.dmfs.tasks │ 1.4.2 │ 82200 │ org.fdroid.fdroid.privileged │ │
│ com.android.providers.contacts │ 11 │ 30 │ — │ │
│ com.android.providers.calendar │ 11 │ 30 │ — │ │
│ org.lineageos.etar │ 11 │ 30 │ — │ │
│ org.withouthat.acalendarplus │ 2.6.1 │ 2006010 │ — │ │
└────────────────────────────────┴─────────────┴───────────┴──────────────────────────────┴───────┘

SYSTEM INFORMATION

Android version: 11 (lineage_vayu-userdebug 11 RQ3A.211001.001 eng.root.20211108.175316 dev-keys)
Device: Xiaomi M2102J20SG (vayu)

Locale(s): [de_DE]
Time zone: Europe/Berlin
Internal memory (/data): 134 GB free of 226 GB

CONNECTIVITY

Data saver: disabled

CONFIGURATION

App standby bucket: 10
Power saving disabled: no
System-wide synchronization: automatically

Notifications:

    sync isBlocked=false

    syncProblems: importance=3
    syncIoErrors: importance=1
    syncWarnings: importance=2

    status: importance=2
    general: importance=3
    debug: importance=4

Permissions:

    ACCESS_NETWORK_STATE: granted
    ACCESS_WIFI_STATE: granted
    FOREGROUND_SERVICE: granted
    INTERNET: granted
    READ_SYNC_SETTINGS: granted
    READ_SYNC_STATS: granted
    WRITE_SYNC_SETTINGS: granted
    RECEIVE_BOOT_COMPLETED: granted
    REQUEST_IGNORE_BATTERY_OPTIMIZATIONS: granted
    READ_CONTACTS: granted
    WRITE_CONTACTS: granted
    READ_CALENDAR: granted
    WRITE_CALENDAR: granted
    ACCESS_COARSE_LOCATION: denied
    ACCESS_FINE_LOCATION: denied
    ACCESS_BACKGROUND_LOCATION: denied
    org.dmfs.permission.READ_TASKS: granted
    org.dmfs.permission.WRITE_TASKS: granted
    org.tasks.permission.READ_TASKS: denied
    org.tasks.permission.WRITE_TASKS: denied
    at.techbee.jtx.permission.READ: denied
    at.techbee.jtx.permission.WRITE: denied

ACCOUNTS

    Account: SURNAME

┌──────────────────────────────────┬──────────┬───────────┬──────────┬───────────────────────────────────┐
│ Authority │ Syncable │ Auto-sync │ Interval │ Entries │
├──────────────────────────────────┼──────────┼───────────┼──────────┼───────────────────────────────────┤
│ at.bitfire.davdroid.addressbooks │ 1 │ true │ 240 min │ — │
│ com.android.calendar │ 1 │ true │ 240 min │ 499 event(s) │
│ at.techbee.jtx.provider │ 0 │ false │ 1440 min │ — │
│ org.dmfs.tasks │ 1 │ true │ 240 min │ 208 OpenTasks task(s) │
│ org.tasks.opentasks │ 0 │ false │ 1440 min │ — │
│ com.android.contacts │ 0 │ false │ — │ 0 wrongly assigned raw contact(s) │
└──────────────────────────────────┴──────────┴───────────┴──────────┴───────────────────────────────────┘

WiFi only: false
Contact group method: GROUP_VCARDS
Time range (past days): 90
Default alarm (min before): null
Manage calendar colors: true
Use event colors: false

    Account: USERNAME4

┌──────────────────────────────────┬──────────┬───────────┬──────────┬───────────────────────────────────┐
│ Authority │ Syncable │ Auto-sync │ Interval │ Entries │
├──────────────────────────────────┼──────────┼───────────┼──────────┼───────────────────────────────────┤
│ at.bitfire.davdroid.addressbooks │ 1 │ true │ 240 min │ — │
│ com.android.calendar │ 1 │ true │ 240 min │ 133 event(s) │
│ at.techbee.jtx.provider │ 0 │ false │ 1440 min │ — │
│ org.dmfs.tasks │ 1 │ true │ 240 min │ 117 OpenTasks task(s) │
│ org.tasks.opentasks │ 0 │ false │ 1440 min │ — │
│ com.android.contacts │ 0 │ false │ — │ 0 wrongly assigned raw contact(s) │
└──────────────────────────────────┴──────────┴───────────┴──────────┴───────────────────────────────────┘

WiFi only: false
Contact group method: GROUP_VCARDS
Time range (past days): 90
Default alarm (min before): null
Manage calendar colors: true
Use event colors: false

    Address book: Kontakte (USERNAME4 tA)

    ┌──────────────────────┬──────────┬───────────┬──────────┬────────────────────┐
    │ Authority │ Syncable │ Auto-sync │ Interval │ Entries │
    ├──────────────────────┼──────────┼───────────┼──────────┼────────────────────┤
    │ com.android.contacts │ 1 │ true │ — │ 555 raw contact(s) │
    └──────────────────────┴──────────┴───────────┴──────────┴────────────────────┘

    URL: https://servername/remote.php/dav/addressbooks/users/USERNAME4/contacts/
    Read-only: 0

    Account: Company Team ACCOUNT

┌──────────────────────────────────┬──────────┬───────────┬──────────┬───────────────────────────────────┐
│ Authority │ Syncable │ Auto-sync │ Interval │ Entries │
├──────────────────────────────────┼──────────┼───────────┼──────────┼───────────────────────────────────┤
│ at.bitfire.davdroid.addressbooks │ 1 │ true │ 240 min │ — │
│ com.android.calendar │ 1 │ true │ 240 min │ 38 event(s) │
│ at.techbee.jtx.provider │ 0 │ false │ 1440 min │ — │
│ org.dmfs.tasks │ 1 │ true │ 240 min │ 0 OpenTasks task(s) │
│ org.tasks.opentasks │ 0 │ false │ 1440 min │ — │
│ com.android.contacts │ 0 │ false │ — │ 0 wrongly assigned raw contact(s) │
└──────────────────────────────────┴──────────┴───────────┴──────────┴───────────────────────────────────┘

WiFi only: false
Contact group method: GROUP_VCARDS
Time range (past days): 90
Default alarm (min before): null
Manage calendar colors: true
Use event colors: false

DATABASE DUMP

android_metadata

┌────────┐
│ locale │
├────────┤
│ de_DE │
└────────┘

service

┌────┬──────────────────────┬─────────┬─────────────────────────────────────────────────────────────────────────────────┐
│ id │ accountName │ type │ principal │
├────┼──────────────────────┼─────────┼─────────────────────────────────────────────────────────────────────────────────┤
│ 1 │ SURNAME │ carddav │ https://servername/remote.php/dav/principals/users/USERNAME/ │
│ 2 │ SURNAME │ caldav │ https://servername/remote.php/dav/principals/users/USERNAME/ │
│ 3 │ USERNAME4 │ carddav │ https://servername/remote.php/dav/principals/users/USERNAME4/ │
│ 4 │ USERNAME4 │ caldav │ https://servername/remote.php/dav/principals/users/USERNAME4/ │
│ 5 │ Company Team ACCOUNT │ carddav │ https://www.google.com/carddav/v1/principals/GOOGLEUSER@gmail.com │
│ 6 │ Company Team ACCOUNT │ caldav │ — │
└────┴──────────────────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────┘

sqlite_sequence

┌────────────┬───────┐
│ name │ seq │
├────────────┼───────┤
│ service │ 8 │
│ homeset │ 6 │
│ collection │ 17 │
│ syncstats │ 28205 │
└────────────┴───────┘

homeset

┌────┬───────────┬──────────┬───────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────┐
│ id │ serviceId │ personal │ url │ privBind │ displayName │
├────┼───────────┼──────────┼───────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────┤
│ 1 │ 1 │ 1 │ https://servername/remote.php/dav/addressbooks/users/USERNAME/ │ 1 │ — │
│ 2 │ 2 │ 1 │ https://servername/remote.php/dav/calendars/USERNAME/ │ 1 │ — │
│ 3 │ 3 │ 1 │ https://servername/remote.php/dav/addressbooks/users/USERNAME4/ │ 1 │ — │
│ 4 │ 4 │ 1 │ https://servername/remote.php/dav/calendars/USERNAME4/ │ 1 │ — │
│ 5 │ 5 │ 1 │ https://www.google.com/carddav/v1/principals/GOOGLEUSER@gmail.com/lists/ │ 1 │ Homeset │
└────┴───────────┴──────────┴───────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────┘

collection

┌────┬───────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┬────────────┬───────────────┬───────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────┬───────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────┬───────────────┬──────────────────┬────────┬──────┐
│ id │ serviceId │ homeSetId │ type │ url │ privWriteContent │ privUnbind │ forceReadOnly │ displayName │ description │ owner │ color │ timezone │ supportsVEVENT │ supportsVTODO │ supportsVJOURNAL │ source │ sync │
├────┼───────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┼────────────┼───────────────┼───────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────┼───────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────┼───────────────┼──────────────────┼────────┼──────┤
│ 1 │ 1 │ 1 │ ADDRESS_BOOK │ https://servername/remote.php/dav/addressbooks/users/USERNAME/contacts/ │ 1 │ 1 │ 0 │ Kontakte │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ — │ — │ — │ — │ — │ — │ 0 │
│ 2 │ 1 │ 1 │ ADDRESS_BOOK │ https://servername/remote.php/dav/addressbooks/users/USERNAME/z-app-generated--contactsinteraction--recent/ │ 0 │ 0 │ 0 │ Zuletzt kontaktiert │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ — │ — │ — │ — │ — │ — │ 0 │
│ 3 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/personal/ │ 1 │ 1 │ 0 │ USERNAME1 │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -1579148 │ — │ 1 │ 1 │ 0 │ — │ 1 │
│ 4 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/271fe30e-b45d-4442-bc66-c293b9642b5b/ │ 1 │ 1 │ 0 │ SURNAME │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -37632 │ — │ 0 │ 1 │ 0 │ — │ 1 │
│ 5 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/af5d6756-30e3-4986-a4bb-6b8948c90879/ │ 1 │ 1 │ 0 │ SUR │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -37632 │ — │ 1 │ 1 │ 0 │ — │ 1 │
│ 6 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/bcff192e-e36e-4b40-b64a-ae15d3433fa5/ │ 1 │ 1 │ 0 │ USERNAME2 │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -16776961 │ — │ 1 │ 1 │ 0 │ — │ 1 │
│ 7 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/contact_birthdays/ │ 0 │ 0 │ 0 │ Geburtstage von Kontakten │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -54 │ — │ 1 │ 0 │ 0 │ — │ 0 │
│ 8 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/USERNAME3/ │ 1 │ 1 │ 0 │ USERNAME3 │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -13513604 │ — │ 1 │ 1 │ 0 │ — │ 1 │
│ 9 │ 2 │ 2 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME/USERNAME5/ │ 1 │ 1 │ 0 │ USERNAME5 │ — │ https://servername/remote.php/dav/principals/users/USERNAME/ │ -8638004 │ — │ 1 │ 1 │ 0 │ — │ 1 │
│ 10 │ 3 │ 3 │ ADDRESS_BOOK │ https://servername/remote.php/dav/addressbooks/users/USERNAME4/contacts/ │ 1 │ 1 │ 0 │ Kontakte │ — │ https://servername/remote.php/dav/principals/users/USERNAME4/ │ — │ — │ — │ — │ — │ — │ 1 │
│ 11 │ 3 │ 3 │ ADDRESS_BOOK │ https://servername/remote.php/dav/addressbooks/users/USERNAME4/z-app-generated--contactsinteraction--recent/ │ 0 │ 0 │ 0 │ Zuletzt kontaktiert │ — │ https://servername/remote.php/dav/principals/users/USERNAME4/ │ — │ — │ — │ — │ — │ — │ 0 │
│ 12 │ 4 │ 4 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME4/personal/ │ 1 │ 1 │ 0 │ Persönlich │ — │ https://servername/remote.php/dav/principals/users/USERNAME4/ │ — │ — │ 1 │ 1 │ 0 │ — │ 1 │
│ 13 │ 4 │ 4 │ CALENDAR │ https://servername/remote.php/dav/calendars/USERNAME4/contact_birthdays/ │ 0 │ 0 │ 0 │ Geburtstage von Kontakten │ — │ https://servername/remote.php/dav/principals/users/USERNAME4/ │ -54 │ — │ 1 │ 0 │ 0 │ — │ 1 │
│ 14 │ 6 │ — │ CALENDAR │ https://www.google.com/calendar/dav/m20v5c2bmu54hh4digpgggotpg@group.calendar.google.com/events/ │ 0 │ 0 │ 0 │ LP-Termine TEAM-ACCOUNT │ Hier alle Termine, die für Partner(innen) des gesamten ACCOUNT-Teams zugänglich sind.
Mit Klick auf den Termin erscheinen alle relevanten Informationen. │ — │ -8662712 │ BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:LP-Termine TEAM-ACCOUNT
X-WR-TIMEZONE:Europe/Berlin
X-WR-CALDESC:Hier alle Termine, die für Partner(innen) des gesamten ACCOUNT
-Teams zugänglich sind. \nMit Klick auf den Termin erscheinen alle relevant
en Informationen.
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
│ 1 │ 0 │ 0 │ — │ 1 │
│ 15 │ 5 │ 5 │ ADDRESS_BOOK │ https://www.google.com/carddav/v1/principals/GOOGLEUSER@gmail.com/lists/default/ │ 1 │ 1 │ 0 │ Address Book │ My Contacts │ — │ — │ — │ — │ — │ — │ — │ 0 │
└────┴───────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┴────────────┴───────────────┴───────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────┴───────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────┴───────────────┴──────────────────┴────────┴──────┘

syncstats

┌───────┬──────────────┬──────────────────────┬───────────────┐
│ id │ collectionId │ authority │ lastSync │
├───────┼──────────────┼──────────────────────┼───────────────┤
│ 28190 │ 3 │ org.dmfs.tasks │ 1665638327881 │
│ 28191 │ 12 │ com.android.calendar │ 1665638327964 │
│ 28192 │ 13 │ com.android.calendar │ 1665638329741 │
│ 28193 │ 10 │ com.android.contacts │ 1665638330455 │
│ 28194 │ 5 │ org.dmfs.tasks │ 1665638330582 │
│ 28195 │ 4 │ org.dmfs.tasks │ 1665638331985 │
│ 28196 │ 6 │ org.dmfs.tasks │ 1665638333251 │
│ 28197 │ 8 │ org.dmfs.tasks │ 1665638334595 │
│ 28198 │ 9 │ org.dmfs.tasks │ 1665638335840 │
│ 28199 │ 14 │ com.android.calendar │ 1665638359587 │
│ 28200 │ 12 │ org.dmfs.tasks │ 1665638426853 │
│ 28201 │ 3 │ com.android.calendar │ 1665638427917 │
│ 28202 │ 6 │ com.android.calendar │ 1665638434458 │
│ 28203 │ 8 │ com.android.calendar │ 1665638435551 │
│ 28204 │ 9 │ com.android.calendar │ 1665638436705 │
│ 28205 │ 5 │ com.android.calendar │ 1665638437712 │
└───────┴──────────────┴──────────────────────┴───────────────┘

webdav_document: 0 row(s), data not listed here

webdav_mount

┌────┬──────┬─────┐
│ id │ name │ url │
├────┼──────┼─────┤
└────┴──────┴─────┘

room_master_table

┌────┬──────────────────────────────────┐
│ id │ identity_hash │
├────┼──────────────────────────────────┤
│ 42 │ 223aa7f0fd53730921ca212a663585d8 │
└────┴──────────────────────────────────┘

APP SETTINGS

    SharedPreferencesProvider canWrite=true

┌───────────────────────────┬───────────────┐
│ Setting │ Value │
├───────────────────────────┼───────────────┤
│ hint_AutostartPermissions │ false │
│ hint_BatteryOptimizations │ false │
│ time_nextDonationPopup │ 1650745449963 │
└───────────────────────────┴───────────────┘

    DefaultsProvider canWrite=false

┌───────────────────────┬───────────┐
│ Setting │ Value │
├───────────────────────┼───────────┤
│ default_sync_interval │ 14400 │
│ distrust_system_certs │ false │
│ proxy_host │ localhost │
│ proxy_port │ 9050 │
│ proxy_type │ -1 │
│ sync_all_collections │ false │
└───────────────────────┴───────────┘

--- END DEBUG INFO ---

### Steps to reproduce

1. Create a ICS calender entry on your smartphone with Recorruency (app which MAY cause the isssue is acalendar
2. ICS is valid on device and is syncing successful if using google or other cloud instances
3. ICS is not syncing from device to nextcloud-calendar using DAVX. (it happens not in general. I do not understand when the ICS makes trouble and when not. sorry. maybe you if you read the debug info

### Expected behavior

ICS should be accepted by sabre-dav which is incluided in nextcloud

bugreport in repo of sabredav (hopefully the one Nextcloud is using! - because there some more forks...)

https://github.com/sabre-io/dav/issues/1423

bugreport/idea on DAVX buglist to may block those faulty ICS:
https://github.com/bitfireAT/davx5-ose/discussions/187

### Installation method

Community Manual installation with Archive

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "seafile.msc.loginto.me:444",
            "nextcloud.msc.loginto.me:444",
            "msc.loginto.me:444",
            "nextcloud.amaliaskadi.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/seafile.msc.loginto.me:444",
        "dbtype": "mysql",
        "version": "24.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_sendmailmode": "smtp",
        "enable_previews": "false",
        "app_install_overwrite": [
            "calendar",
            "whiteboard",
            "mindmap_app"
        ],
        "mysql.utf8mb4": true,
        "maintenance": false,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - breezedark: 24.0.2
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.1
  - carnet: 0.24.5
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - collectives: 1.5.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - gpxpod: 4.3.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.1
  - music: 1.6.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - passwords: 2022.10.10
  - phonetrack: 0.7.2
  - photos: 1.6.0
  - polls: 3.8.2
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quicknotes: 0.8.1
  - recommendations: 1.3.0
  - riotchat: 0.13.10
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.5
  - support: 1.7.0
  - systemtags: 1.14.0
  - talked: 0.4.0
  - tasks: 0.14.5
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - whiteboard: 0.0.3
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - files_external
  - files_texteditor: 2.14.0
  - shifts: 1.8.6
  - survey_client: 1.4.0
  - user_ldap
```

**Comment by sparagi** [comment]
Would returning 403 instead (as suggested in https://github.com/nextcloud/server/issues/30514) help?

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by nextcloud-command** [comment]
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by JustACasual** [comment]
Hi all,

just ran into this very same problem. 

Not sure what caused the ics to be invalid, though.
Anyway, also aCalendar, DavX5 and Nextcloud 26.0.1 -> "This recurrence rule does not generate any valid instances". 

copied the ics path from the log message, found the summary, deleted it from the nextcloud UI and this solved the issue...
