### ISSUE TITLE
[Bug]: NC24 - TypeError: Cannot read properties of null (reading 'appendChild')

### ISSUE THREAD

**Issue by kwisatz** [nextcloud/server#34828]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When nextcloud server restarts (e.g. after an upgrade or a server reboot) and a valid user session is still present on the browser, then when attempting to update apps, the following error occurs as one clicks on the "Update" button:

```
TypeError: Cannot read properties of null (reading 'appendChild')
    at o.mounted (main.js:6120:594)
    at Ut (main.js:7:1678)
    at Nn (main.js:7:13691)
    at Object.insert (main.js:7:17904)
    at E (main.js:15:18973)
    at o.__patch__ (main.js:15:21229)
    at e._update (main.js:7:10395)
    at o.a (main.js:7:11799)
    at e.get (main.js:7:6677)
    at new e (main.js:7:6594)
```

This then prevents the "Confirm" button from becoming active.

If I log out, then back in, then this `TypeError` does not occur and I can upgrade or install apps.

### Steps to reproduce

1. Be logged into your nextcloud instance 
2. Restart the nextcloud server
3. Attempt to update or install an app

### Expected behavior

Session works normally after server restart.
No `TypeError`

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tentwentyfour.lu"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "htaccess.RewriteBase": "\/",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.0.18",
        "overwrite.cli.url": "https:\/\/cloud.tentwentyfour.lu",
        "overwritehost": "cloud.tentwentyfour.lu",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "352",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trashbin_retention_obligation": "auto, 90",
        "upgrade.disable-web": "true",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/server.log",
        "loglevel": 2,
        "app_install_overwrite": [
            "ownpad"
        ],
        "has_rebuilt_cache": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.0.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - deck: 1.8.0
  - event_update_notification: 2.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.0
  - files_automatedtagging: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.0
  - groupfolders: 13.0.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflow_ocr: 1.25.0
  - workflowengine: 2.7.0
Disabled:
  - carnet: 0.24.5
  - circles: 23.1.1
  - dashboard: 7.2.0
  - drawio: 1.0.3
  - duplicatefinder: 0.0.15
  - encryption
  - files_external
  - files_markdown: 2.3.6
  - quota_warning: 1.15.0
  - suspicious_login
  - twofactor_u2f: 6.3.1
  - unsplash: 2.0.1
  - weather_status: 1.4.0
  - workflow_script: 1.9.0
```

**Comment by szaimen** [comment]
will get fixed with 25.0.1
