### ISSUE TITLE
[Bug]: Allowed memory size .... exhausted...

### ISSUE THREAD

**Issue by godsgood33** [nextcloud/server#35132]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Running a new install of Nextcloud AIO v2.1.2 NC v24.0.7.  Running any OCC command results in an memory error

```
bash-5.1# sudo -u www-data php occ upgrade

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 442368 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35

bash-5.1# php -i | grep memory_limit
memory_limit => 512M => 512M
```

### Steps to reproduce

I just followed the directions on the AIO page and got it running

### Expected behavior

No error

### Installation method

Official All-in-One appliance

### Operating system

Other

### PHP engine version

PHP 8.0

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Same error
```

### List of activated Apps

```shell
Same error
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Waiting for database to start...
Configuring Redis as session handler...
Setting php max children...
Initializing nextcloud 24.0.7.1 ...
Initializing finished
New nextcloud instance
Installing with PostgreSQL database
starting nextcloud installation
Nextcloud was successfully installed
Applying default settings...
System config value loglevel set to string 2
System config value log_type set to string file
System config value logfile set to string /var/www/html/data/nextcloud.log
System config value log_rotate_size set to string 10485760
admin_audit 1.14.0 enabled
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
System config value log.condition => apps => 0 set to string admin_audit
Applying preview settings...
System config value preview_max_x set to string 2048
System config value preview_max_y set to string 2048
System config value jpeg_quality set to string 60
Config value jpeg_quality for app preview set to 60
System config value enabledPreviewProviders deleted
System config value enabledPreviewProviders => 1 set to string OC\Preview\Image
System config value enabledPreviewProviders => 2 set to string OC\Preview\MarkDown
System config value enabledPreviewProviders => 3 set to string OC\Preview\MP3
System config value enabledPreviewProviders => 4 set to string OC\Preview\TXT
System config value enabledPreviewProviders => 5 set to string OC\Preview\OpenDocument
System config value enabledPreviewProviders => 6 set to string OC\Preview\Movie
System config value enable_previews set to boolean true
Applying other settings...
System config value upgrade.disable-web set to boolean true
System config value mail_smtpmode set to string smtp
System config value trashbin_retention_obligation set to string auto, 30
System config value versions_retention_obligation set to string auto, 30
System config value activity_expire_days set to string 30
System config value simpleSignUpLink.shown set to boolean false
System config value share_folder set to string /Shared
twofactor_totp 6.4.1 installed
twofactor_totp enabled
deck 1.7.2 installed
deck enabled
tasks 0.14.5 installed
tasks enabled
calendar 3.5.2 installed
calendar enabled
contacts 4.2.2 installed
contacts enabled
apporder 0.15.0 installed
apporder enabled
System config value tempdirectory set to string /mnt/ncdata/tmp/
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
System config value one-click-instance.link set to string https://nextcloud.com/all-in-one/
support already enabled
Adjusting log files...
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
Applying network settings...
System config value trusted_domains => 1 set to string tld.domain.com
System config value overwrite.cli.url set to string https://tld.domain.com/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value files_external_allow_create_new_local set to boolean false
notify_push 0.5.0 installed
notify_push enabled
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://tld.domain.com/push
richdocuments 6.3.1 installed
richdocuments enabled
Config value wopi_url for app richdocuments set to https://tld.domain.com/
System config value allow_local_remote_servers set to boolean true
spreed 14.0.6 installed
spreed enabled
Added tld.domain.com:3478.
Added signaling server https://tld.domain.com/standalone-signaling/.
[2022-11-13 21:52:29.177406 -05:00] WARN [rustls::conn] /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.20.6/src/conn.rs:1285: Sending fatal alert BadCertificate
[2022-11-13 21:52:29.177520 -05:00] ERROR [notify_push] src/main.rs:77: Self test failed: Error while communicating with nextcloud instance
Activating collabora config...
Failed to activate any config changes
cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://tld.domain.com/hosting/discovery
#0 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/html/lib/private/Http/Client/DnsPinMiddleware.php(113): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#13 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#14 /var/www/html/lib/private/Http/Client/Client.php(218): GuzzleHttp\Client->request('get', 'https://cloud.r...', Array)
#15 /var/www/html/custom_apps/richdocuments/lib/WOPI/DiscoveryManager.php(84): OC\Http\Client\Client->get('https://cloud.r...', Array)
#16 /var/www/html/custom_apps/richdocuments/lib/WOPI/DiscoveryManager.php(56): OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()
#17 /var/www/html/custom_apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()
#18 /var/www/html/custom_apps/richdocuments/lib/Command/ActivateConfig.php(70): OCA\Richdocuments\WOPI\Parser->getUrlSrc('Capabilities')
#19 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\RichDocuments\Command\ActivateConfig->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\RichDocuments\Command\ActivateConfig), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/console.php(100): OC\Console\Application->run()
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
#26 {main}
              now              
-------------------------------
 2022-11-13 22:00:29.291687-05
(1 row)

Configuring Redis as session handler...
Setting php max children...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value tempdirectory set to string /mnt/ncdata/tmp/
Applying one-click-instance settings...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value one-click-instance set to boolean true
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value one-click-instance.user-limit set to integer 100
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value one-click-instance.link set to string https://nextcloud.com/all-in-one/
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
support already enabled
Adjusting log files...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value logfile set to string /var/www/html/data/nextcloud.log
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
Applying network settings...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value trusted_domains => 1 set to string tld.domain.com
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value overwrite.cli.url set to string https://tld.domain.com/
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value htaccess.RewriteBase set to string /
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
.htaccess has been updated
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value files_external_allow_create_new_local set to boolean false
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value trusted_proxies => 0 set to string 127.0.0.1
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value trusted_proxies => 1 set to string ::1
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Config value base_endpoint for app notify_push set to https://tld.domain.com/push
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Config value wopi_url for app richdocuments set to https://tld.domain.com/
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value allow_local_remote_servers set to boolean true
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  There are no commands defined in the "talk:turn" namespace.  

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  There are no commands defined in the "talk:turn" namespace.  

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  There are no commands defined in the "talk:stun" namespace.

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  There are no commands defined in the "talk:signaling" namespace.  

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  There are no commands defined in the "talk:signaling" namespace.  

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value enabledPreviewProviders => 0 deleted
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
System config value preview_imaginary_url deleted
Activating collabora config...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  There are no commands defined in the "richdocuments" namespace.
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by godsgood33** [comment]
@szaimen I might agree except for the install works fine.
