### ISSUE TITLE
Random decryption failures in files_versions

### ISSUE THREAD

**Issue by serge-vk** [nextcloud/server#3587]
### Steps to reproduce
1. No action seems to be required from the user
2. Periodically check the NextCloud logs

### Expected behaviour
No errors in the server log should be produced

### Actual behaviour
Server spams the log with errors related to old versions of certain files (note that none of the accounts ever had any shares): 
`Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.`
`Couldn't re-calculate unencrypted size for files_versions/Work/scripts/CVS/Root.v1480651735`

When checking those versions through the web interface, most of them download without issue, but a couple are reported as not found by the browser.

This behaviour started a fairly long time ago (though I cannot remember prior or after the upgrade from OwnCloud to NextCloud), but until recently, only two or three files generated the reported error. A few days ago I noticed that more files were reported. Maybe, this happened after I rescanned all the user files from the console. 

All of the problem files have only one version listed (about half a year to a year old). Moreover, it is unlikely that I ever modified those files (e.g. an article in .pdf format). I have just downloaded them and their available versions and they are bit-wise identical. 

Two version file links are reported by the browser as not found. One of those not found files is actually present in the files_versions folder (I can see it from the server console). It generates the following error in the NextCloud log:
`OC\Encryption\Exceptions\DecryptionFailedException: Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length`

The other not found file is truly missing and seems to generate these errors:
`OC\HintException: Bad Signature`
`Couldn't re-calculate unencrypted size for files_versions/Work/Patent application/Literature/An_Introduction_To_Harmonic.pdf.v1477805105`

The web interface shows that the only previous version of this file has the same date as the last (as displayed in the web interface to the minute).

### Server configuration
**Operating system**: FreeBSD 11.0 p7

**Web server:** Nginx 1.11.9

**Database:** MariaDB 10.1.21

**PHP version:** 7.1.1

**Nextcloud version:** 11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from ownCloud 9 to NextCloud 10; then updated to 11.0 and 11.0.1

**Where did you install Nextcloud from:**
NextCloud 10 and 11.0 were downloaded from https://nextcloud.com/install/ and manually installed. Update to 11.0.1 was made through web interface.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - external
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocffm874ikqy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/ocData",
        "overwrite.cli.url": "https:\/\/192.168.0.200\/owncloud",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "OwnCloud",
        "dbhost": "localhost:\/tmp\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "appstore.experimental.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "30, 365",
        "asset-pipeline.enabled": true,
        "logtimezone": "***REMOVED SENSITIVE VALUE***",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "logfile": "\/var\/log\/owncloud.log",
        "activity_expire_days": 365,
        "enable_avatars": true,
        "session_lifetime": 10800,
        "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "debug": true,
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "mail_smtpsecure": "ssl",
        "versions_retention_obligation": "auto, 365",
        "maintenance": false,
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.release.channel": "stable",
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** FireFox 51.0.1 (64-bit)

**Operating system:** Mac OS X 10.10.5

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/02/22 09:27:20 [info] 99679#101311: *29545 kevent() reported that client 23.16.187.29 closed keepalive connection
2017/02/22 09:44:50 [info] 99680#102034: *29665 kevent() reported that client 23.16.187.29 closed keepalive connection
2017/02/22 09:45:01 [info] 99680#102034: *29655 kevent() reported that client 23.16.187.29 closed keepalive connection
2017/02/22 10:00:08 [notice] 99678#101394: signal 30 (SIGUSR1) received, reopening logs
2017/02/22 10:00:08 [notice] 99678#101394: reopening logs
2017/02/22 10:00:08 [notice] 99680#102034: reopening logs
2017/02/22 10:00:08 [notice] 99681#101431: reopening logs
2017/02/22 10:00:08 [notice] 99679#101311: reopening logs
2017/02/22 10:00:08 [notice] 99678#101394: signal 23 (SIGIO) received
2017/02/22 10:00:08 [notice] 99678#101394: signal 23 (SIGIO) received
2017/02/22 10:00:08 [notice] 99678#101394: signal 23 (SIGIO) received
2017/02/22 10:03:03 [info] 99679#101311: *29743 kevent() reported that client 23.16.187.29 closed keepalive connection
2017/02/22 10:21:02 [info] 99679#101311: *29824 kevent() reported that client 23.16.187.29 closed keepalive connection
2017/02/22 10:39:10 [info] 99679#101311: *29924 kevent() reported that client 23.16.187.29 closed keepalive connection
2017/02/22 10:44:32 [info] 99679#101311: *29959 kevent() reported that client 23.16.187.29 closed keepalive connection
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-02-22T10:30:15-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Documents\/DFTv2.docx.v1461949568","level":3,"time":"2017-02-22T10:30:15-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(574): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(493): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 2285630, 2285630)\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(162): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 2285630)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->filesize('files_versions\\\/...')\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1124): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(418): OC\\\\Files\\\\View->basicOperation('filesize', 'files_versions\\\/...')\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(578): OC\\\\Files\\\\View->filesize('files_versions\\\/...')\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(490): OCA\\\\Files_Versions\\\\Storage::getAllVersions('LocAdmin')\\n#8 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/BackgroundJob\\\/ExpireVersions.php(75): OCA\\\\Files_Versions\\\\Storage::expireOlderThanMaxForUser('LocAdmin')\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(410): OCA\\\\Files_Versions\\\\BackgroundJob\\\\ExpireVersions->OCA\\\\Files_Versions\\\\BackgroundJob\\\\{closure}(Object(OC\\\\User\\\\User))\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/BackgroundJob\\\/ExpireVersions.php(76): OC\\\\User\\\\Manager->callForSeenUsers(Object(Closure))\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\Files_Versions\\\\BackgroundJob\\\\ExpireVersions->run(NULL)\\n#12 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#13 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/cron.php(128): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":369}","level":3,"time":"2017-02-22T10:30:15-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-02-22T10:30:15-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Work\/MATLAB\/tftb-0.2\/tutorial\/CVS\/Repository.v1480651767","level":3,"time":"2017-02-22T10:30:15-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(574): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(493): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 116, 8308)\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(162): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 8308)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): ...skipping...
ns\\\/...')\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(418): OC\\\\Files\\\\View->basicOperation('filesize', 'files_versions\\\/...')\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(578): OC\\\\Files\\\\View->filesize('files_versions\\\/...')\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(490): OCA\\\\Files_Versions\\\\Storage::getAllVersions('Serge')\\n#8 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/BackgroundJob\\\/ExpireVersions.php(75): OCA\\\\Files_Versions\\\\Storage::expireOlderThanMaxForUser('Serge')\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(410): OCA\\\\Files_Versions\\\\BackgroundJob\\\\ExpireVersions->OCA\\\\Files_Versions\\\\BackgroundJob\\\\{closure}(Object(OC\\\\User\\\\User))\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/BackgroundJob\\\/ExpireVersions.php(76): OC\\\\User\\\\Manager->callForSeenUsers(Object(Closure))\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\Files_Versions\\\\BackgroundJob\\\\ExpireVersions->run(NULL)\\n#12 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#13 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/cron.php(128): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":369}","level":3,"time":"2017-02-22T10:30:17-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-02-22T10:30:18-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Work\/Displays\/ALP DMD DOCS\/ALP CD\/API\/src\/AlpSample\/res\/AlpSample.rc2.v1469048196","level":3,"time":"2017-02-22T10:30:18-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"trRo2dkUQ29CIWFJN0nv","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(574): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(493): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 664, 8856)\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(162): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 8856)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->filesize('files_versions\\\/...')\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1124): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(418): OC\\\\Files\\\\View->basicOperation('filesize', 'files_versions\\\/...')\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(578): OC\\\\Files\\\\View->filesize('files_versions\\\/...')\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(490): OCA\\\\Files_Versions\\\\Storage::getAllVersions('Serge')\\n#8 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/BackgroundJob\\\/ExpireVersions.php(75): OCA\\\\Files_Versions\\\\Storage::expireOlderThanMaxForUser('Serge')\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(410): OCA\\\\Files_Versions\\\\BackgroundJob\\\\ExpireVersions->OCA\\\\Files_Versions\\\\BackgroundJob\\\\{closure}(Object(OC\\\\User\\\\User))\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/BackgroundJob\\\/ExpireVersions.php(76): OC\\\\User\\\\Manager->callForSeenUsers(Object(Closure))\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\Files_Versions\\\\BackgroundJob\\\\ExpireVersions->run(NULL)\\n#12 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#13 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/cron.php(128): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":369}","level":3,"time":"2017-02-22T10:30:18-08:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
```
</details>

#### Browser log
When I load a folder with a problem file, I don't see anything too suspicious in the JS console (a bunch of warnings about i-frames able to remove sandboxing, deprecated pdf api, and a lot of lines like `#thumbs is undefined`, `#outline is undefined`, &c). 

Network console has only one relevant line saying that a preview for the listed version is not available. If I click to download one of the missing files, I see a `503 Service unavailable` response.

I tend to think that the core of this issue does not depend on browser activity. The reported behaviour began without me touching the problem files or even opening their enclosing folders.

**Comment by dirigit** [comment]
I can confirm such issues but, for me it looks like a change in de-/encryption part of Nextcloud and Owncloud in some previous revision.  I tinkered a while with different versions but could not find a matching one.

Onliest solution for me has been manual deletion of encrypted files and rescan of files in Nextcloud/Owncloud. Therefore I do recommend to not to use encryption or to have a very good backup at hand (in your pocket). Sad enough you don't need *Cloud than.

**Comment by nickvergessen** [comment]
@schiessle

**Comment by serge-vk** [comment]
A little update: I can now positively confirm that file versions are created without the user intervention. I synchronised a new folder and one of the files inside is listed as updated at the same time as it was synced. The listed previous version can be downloaded normally, but causes a decryption error in the log. 

I have not yet seen this when uploading through the web interface. It is theoretically possible that things go wrong between the client and the server because I also encountered persistent sync errors when copying .pdf files to a synced folder on Mac (using the OwnCloud 2.3.0 beta1 client). I had to manually delete those files through the web interface and sync them again. 

This may be related to issues reported for the OwnCloud client/server syncing https://github.com/owncloud/client/issues/4542 and https://github.com/owncloud/client/issues/4583.

**Comment by boldandbusted** [comment]
To underscore what @dirigit said, I think encryption is, at this point, more dangerous to the integrity of your files than not. It seems to take very little to create "Invalid key length" errors when using Android NC client. If a hapless user is not backing up files via some other mechanism, they have a high danger of NC effectively deleting their data without possibility of recovery! I feel that NC should pull the encryption feature until this is comprehensively resolved. :/

**Comment by schiessle** [comment]
can't reproduce it. Feel free to re-open if this is still an issue with the latest version of Nextcloud

**Comment by shadowlmd** [comment]
Seeing these errors with Nextcloud version 24.0.2. This message appears when Nextcloud Desktop client is trying to verify if it needs to re-upload file that already exists on the server. This only happens with several files uploaded in a different time.

It's probably no possible to provide steps to reproduce the issue because it's random. But I can assist in debugging it.
