### ISSUE TITLE
Backport fix for colon in folder name on dav

### ISSUE THREAD

**Issue by benediktg** [nextcloud/server#3699]
This issue should have already been fixed by #2727 but as it seems is not yet backported to the `stable11` branch.

### Steps to reproduce
1. Create a folder like "test:1"
2. Use the nextcloud client (desktop)

### Expected behaviour
The folder should be synced.

### Actual behaviour
The folder does not get synced by the nextcloud client, instead there is a "fatal" entry in the log.

### Server configuration
**Operating system:** openSUSE 42.2

**Web server:** nginx 1.11.9

**Database:** PostgreSQL 9.4

**PHP version:** PHP 7.0.7

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated using the official update script

**Where did you install Nextcloud from:** ZIP/tar archive from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - audioplayer: 1.4.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - twofactor_u2f: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```json
{
    "system": {
        "instanceid": "ocztdatootyj",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "wolke.g5r.eu"
        ],
        "datadirectory": "\/data\/nextcloud",
        "overwrite.cli.url": "https:\/\/wolke.g5r.eu",
        "version": "11.0.2.7",
        "dbtype": "pgsql",
        "dbname": "nextcloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "\/run\/postgresql",
        "dbtableprefix": "oc_",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/run\/redis\/redis.sock",
            "port": 0
        },
        "maintenance": false,
        "loglevel": 4,
        "updater.release.channel": "stable",
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** nextcloud-client as provided by openSUSE Tumbleweed

**Operating system:** openSUSE Tumbleweed

#### Web server error log
<details>
<summary>Web server error log</summary>
No entries in the nginx error log.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```json
{"reqId":"IKaqMQQLL4xHEsPk1QUx","remoteAddr":"134.109.250.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Error: Unsupported operand types\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/nextcloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/srv\\\/www\\\/nextcloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/nextcloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/nextcloud\\\/htdocs\\\/remote.php(70): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/nextcloud\\\/htdocs\\\/remote.php(170): handleException(Object(Error))\\n#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/nextcloud\\\/htdocs\\\/remote.php\",\"Line\":68,\"User\":\"benedikt\"}","level":4,"time":"2017-03-03T13:46:59+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/test:1","user":"benedikt","version":"11.0.2.7"}
```
![screenshot_20170303_140929](https://cloud.githubusercontent.com/assets/14795615/23557331/0044ec06-0030-11e7-9866-f437ab0d91a2.png)

</details>

#### Browser log
<details>
<summary>Browser log</summary>
None
</details>

**Comment by MorrisJobke** [comment]
Too hard to backport -> closing
