### ISSUE TITLE
Cannot login via web browser after upgrade to 11.0.2

### ISSUE THREAD

**Issue by somniumAeternam** [nextcloud/server#3714]
I can't login via web browser after the upgrade to Nextcloud 11.0.2. This seems to be the same error as in the issue #3657, but this was closed. All apps (Android, iOS, Desktop) can login and everything is working fine, so i suppose it has something to do with my nginx web proxy and changes in the behaviour of Nextcloud 11.

### Steps to reproduce
1. log in via web as admin: fill login form and press "log in ->"
2. observe same login form, browser redirected to /login?redirect_url=/apps/files/

### Expected behaviour
see my personal files

### Actual behaviour
same login form

### Server configuration
**Operating system**:
openSUSE Tumbleweed up-to-date

**Web server:**
Nginx 1.11.10

**Database:**
MariaDB 10.1.21

**PHP version:**
PHP 7.1.2

**Nextcloud version:** 
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
yes, from Nextcloud 10

**Where did you install Nextcloud from:**
from the openSUSE Tumbleweed repo

**Signing status:**
<details>
<summary>Signing status</summary>

```
Cannot log in as admin
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - qownnotesapi: 16.12.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "*DELETED*"
        ],
        "datadirectory": "\/srv\/www\/htdocs\/nextcloud\/data",
        "overwrite.cli.url": "*DELETED*",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "oc3fievwocvx",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "administrator",
        "mail_domain": "*DELETED*",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.1und1.de",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 0
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "3.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "62"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.9.1",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.1",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "installedat": "1472680573.9975",
            "lastcron": "1488701788",
            "lastupdateResult": "{\"version\":\"11.0.2.7\",\"versionstring\":\"Nextcloud 11.0.2\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-11.0.2.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/11\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"autoupdater\":\"1\"}",
            "lastupdatedat": "0",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "*DELETED*",
            "previewsCleanedUp": "1",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_links_password": "yes",
            "umgmt_show_backend": "false",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "true",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "ocsid": "169148",
            "types": ""
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "autoAddServers": "1",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "ojsxc": {
            "boshUrl": "*DELETED*",
            "enabled": "no",
            "iceCredential": "",
            "iceSecret": "",
            "iceTtl": "",
            "iceUrl": "",
            "iceUsername": "",
            "installed_version": "3.0.0",
            "ocsid": "162257",
            "serverType": "external",
            "types": "prelogin",
            "xmppDomain": "*DELETED*",
            "xmppOverwrite": "false",
            "xmppResource": "",
            "xmppStartMinimized": "false"
        },
        "ownnote": {
            "enabled": "no",
            "folder": "Notizen",
            "installed_version": "1.08",
            "ocsid": "168512",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "minLength": "8",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "qownnotesapi": {
            "enabled": "yes",
            "installed_version": "16.12.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.1.24",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "spreedme": {
            "OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED": "false",
            "SPREED_WEBRTC_BASEPATH": "\/webrtc",
            "SPREED_WEBRTC_IS_SHARED_INSTANCE": "false",
            "SPREED_WEBRTC_ORIGIN": "*DELETED*",
            "SPREED_WEBRTC_SHAREDSECRET": "*DELETED*",
            "enabled": "no",
            "installed_version": "0.3.5",
            "is_set_up": "true",
            "ocsid": "174436",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "ocsid": "164356",
            "types": ""
        },
        "theming": {
            "cachebuster": "1",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "logging",
            "url": "https:\/\/phasenraum.dedyn.io\/nextcloud"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "updatenotification": {
            "calendar": "1.5.1",
            "contacts": "1.5.3",
            "core": "11.0.2.7",
            "direct_menu": "0.10.0",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "notes": "2.2.0",
            "spreed": "1.2.0",
            "tasks": "0.9.5",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Tried with Safari, Firefox, Chromium and Chrome

**Operating system:**
Tried with iOS, Android and Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing special in nginx log.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"qJNLI\/6s02UMxFT1WNIy","remoteAddr":"192.168.2.100","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2017-03-05T08:15:09+00:00","method":"GET","url":"\/index.phps\/","user":"--","version":"11.0.2.7"}
{"reqId":"glTW3xkrSR10Vn3Sqakm","remoteAddr":"192.168.2.100","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2017-03-05T08:15:10+00:00","method":"GET","url":"\/index.phpery\/config?extramediatypes=1","user":"--","version":"11.0.2.7"}
{"reqId":"FGYNeO5Ts5ahqN7M\/L82","remoteAddr":"192.168.2.100","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2017-03-05T08:16:26+00:00","method":"GET","url":"\/apps\/files\/","user":"--","version":"11.0.2.7"}
{"reqId":"IumvEzGxo3o0MBypRZLU","remoteAddr":"192.168.2.100","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2017-03-05T08:16:27+00:00","method":"GET","url":"\/apps\/gallery\/config?extramediatypes=1","user":"--","version":"11.0.2.7"}
[...]
{"reqId":"JoXAkCia8QydOCh1Vx1v","remoteAddr":"","app":"PHP","message":"Undefined index: activity at \/srv\/www\/htdocs\/nextcloud\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-05T08:29:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"JoXAkCia8QydOCh1Vx1v","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/srv\/www\/htdocs\/nextcloud\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-05T08:29:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
[...]
{"reqId":"JoXAkCia8QydOCh1Vx1v","remoteAddr":"","app":"PHP","message":"Undefined index: updatenotification at \/srv\/www\/htdocs\/nextcloud\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-05T08:29:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"JoXAkCia8QydOCh1Vx1v","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/srv\/www\/htdocs\/nextcloud\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-05T08:29:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"JoXAkCia8QydOCh1Vx1v","remoteAddr":"","app":"PHP","message":"Undefined index: workflowengine at \/srv\/www\/htdocs\/nextcloud\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-05T08:29:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"JoXAkCia8QydOCh1Vx1v","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/srv\/www\/htdocs\/nextcloud\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-05T08:29:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
[...]
{"reqId":"1XCdosQPAK8ujCKMru\/Y","remoteAddr":"192.168.2.154","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}","level":0,"time":"2017-03-05T08:32:04+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/*DELETED*\/","user":"--","version":"11.0.2.7"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
I can't get the log from JS:

jquery-migrate.min.js?v=7b2fc1e…:2 JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: *DELETED*/core/vendor/jquery/dist/jquery.min.map
```
</details>

**Comment by nickvergessen** [comment]
The errors are suspicious, please try to reupload the `lib/private/AppConfig.php` from a newly downloaded package.

**Comment by tetienne** [comment]
I met exactly the same issue with a fresh install on Centos 7 and Nginx! No error log.

**Comment by vytsima** [comment]
Same problem, same nextcloud.log errors
Centos 7 with nginx/1.10.2, Nextcloud version 11.0.2
is there a fix?

**Comment by vytsima** [comment]
Solved my problem, it was permissions. As i'm using php71 from remi repo. Sessions is stored under /var/opt/remi/php71/lib/php/session with owner of **root** and group of **apache**. Changing group to **nginx** fixed the issue.

**Comment by tetienne** [comment]
Thx @vytsima. It help me to identify my issue too. `chown root:nginx -R  /var/lib/php/fpm` did the trick for me.
