### ISSUE TITLE
[Bug]: Upload larg file no seepd until tiemout

### ISSUE THREAD

**Issue by Zhu-Pei** [nextcloud/server#37165]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when upload files over 50M, its just upload a little part of file and then upload will block until timeout

### Steps to reproduce

1. Use Web or client upload Upload files over 50M
2. at first looks normal， speed  is fast
3. and then the process blocked and not io speed until timeout， like this:
![image](https://user-images.githubusercontent.com/23468256/224212790-a944689b-4c99-4df6-a1fc-6b923e004065.png)
![image](https://user-images.githubusercontent.com/23468256/224212945-5b4354d8-cd85-4d81-9116-334fb83099c4.png)
4. in that time mariadb used all CPU like this:
![image](https://user-images.githubusercontent.com/23468256/224213066-c04d651a-4e09-4dfc-9db0-2cc77b503af7.png)
![image](https://user-images.githubusercontent.com/23468256/224213277-3d211ced-4458-4e07-9bb4-9b527c0622b6.png)
5. when upload stoped,

### Expected behavior

upload sucess

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.zhupei.me"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "mysql.utf8mb4": true,
        "version": "25.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "CN",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "overwrite.cli.url": "https:\/\/nextcloud.zhupei.me:9000",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memories.exiftool": "\/srv\/mergerfs\/mfs\/nextcloud\/apps\/memories\/lib\/..\/exiftool-bin\/exiftool-amd64-glibc"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - camerarawpreviews: 0.8.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.4
  - maps: 0.2.4
  - mediadc: 0.3.3
  - memories: 4.11.2
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2023.3.10
  - photos: 2.0.1
  - previewgenerator: 5.2.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recognize: 3.6.1
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.1
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - unsplash: 2.2.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - backup: 1.2.0
  - encryption
  - files_markdown: 2.3.6
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - video_converter: 1.0.5
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"RtvYlBUZuvQBdIu9O2m8","level":3,"time":"2023-03-10T03:22:05+00:00","remoteAddr":"","user":"","app":"no app in context","method":"GET","url":"/apps/dashboard/","message":"Could not load lazy dashboard widget: Could not resolve initialState! Class initialState does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63","version":"25.0.4.1","data":{"excepiton":"{\"class\":\"OCP\\AppFramework\\QueryException\",\"message\":\"Could not resolve initialState! Class initialState does not exist\",\"code\":0,\"file\":\"/srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:102\",\"trace\":\"#0 [internal function]: OC\\AppFramework\\Utility\\SimpleContainer->OC\\AppFramework\\Utility\\{closure}()\\n#1 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()\\n#2 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\\AppFramework\\Utility\\SimpleContainer->buildClass()\\n#3 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\\AppFramework\\Utility\\SimpleContainer->resolve()\\n#4 /srv/mergerfs/mfs/nextcloud/lib/private/ServerContainer.php(161): OC\\AppFramework\\Utility\\SimpleContainer->query()\\n#5 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\\ServerContainer->query()\\n#6 /srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php(78): OC\\AppFramework\\Utility\\SimpleContainer->get()\\n#7 /srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php(131): OC\\Dashboard\\Manager->loadLazyPanels()\\n#8 /srv/mergerfs/mfs/nextcloud/apps/dashboard/lib/Controller/DashboardController.php(101): OC\\Dashboard\\Manager->getWidgets()\\n#9 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\\Dashboard\\Controller\\DashboardController->index()\\n#10 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\\AppFramework\\Http\\Dispatcher->executeController()\\n#11 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/App.php(172): OC\\AppFramework\\Http\\Dispatcher->dispatch()\\n#12 /srv/mergerfs/mfs/nextcloud/lib/private/Route/Router.php(298): OC\\AppFramework\\App::main()\\n#13 /srv/mergerfs/mfs/nextcloud/lib/base.php(1047): OC\\Route\\Router->match()\\n#14 /srv/mergerfs/mfs/nextcloud/index.php(36): OC::handleRequest()\\n#15 {main}\",\"previous\":{\"class\":\"OCP\\AppFramework\\QueryException\",\"message\":\"Could not resolve OCP\\AppFramework\\Services\\IInitialState! Class can not be instantiated\",\"code\":0,\"file\":\"/srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:118\",\"trace\":\"#0 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\\AppFramework\\Utility\\SimpleContainer->resolve()\\n#1 /srv/mergerfs/mfs/nextcloud/lib/private/ServerContainer.php(161): OC\\AppFramework\\Utility\\SimpleContainer->query()\\n#2 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\\ServerContainer->query()\\n#3 [internal function]: OC\\AppFramework\\Utility\\SimpleContainer->OC\\AppFramework\\Utility\\{closure}()\\n#4 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()\\n#5 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\\AppFramework\\Utility\\SimpleContainer->buildClass()\\n#6 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\\AppFramework\\Utility\\SimpleContainer->resolve()\\n#7 /srv/mergerfs/mfs/nextcloud/lib/private/ServerContainer.php(161): OC\\AppFramework\\Utility\\SimpleContainer->query()\\n#8 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\\ServerContainer->query()\\n#9 /srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php(78): OC\\AppFramework\\Utility\\SimpleContainer->get()\\n#10 /srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php(131): OC\\Dashboard\\Manager->loadLazyPanels()\\n#11 /srv/mergerfs/mfs/nextcloud/apps/dashboard/lib/Controller/DashboardController.php(101): OC\\Dashboard\\Manager->getWidgets()\\n#12 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\\Dashboard\\Controller\\DashboardController->index()\\n#13 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\\AppFramework\\Http\\Dispatcher->executeController()\\n#14 /srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/App.php(172): OC\\AppFramework\\Http\\Dispatcher->dispatch()\\n#15 /srv/mergerfs/mfs/nextcloud/lib/private/Route/Router.php(298): OC\\AppFramework\\App::main()\\n#16 /srv/mergerfs/mfs/nextcloud/lib/base.php(1047): OC\\Route\\Router->match()\\n#17 /srv/mergerfs/mfs/nextcloud/index.php(36): OC::handleRequest()\\n#18 {main}\"}}"}}
{"reqId":"RtvYlBUZuvQBdIu9O2m8","level":3,"time":"2023-03-10T03:22:05+00:00","remoteAddr":"","user":"","app":"no app in context","method":"GET","url":"/apps/dashboard/","message":"Could not register lazy dashboard widget: Dashboard widget with this id has already been registered","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63","version":"25.0.4.1","exception":{"Exception":"InvalidArgumentException","Message":"Dashboard widget with this id has already been registered","Code":0,"Trace":[{"file":"/srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php","line":94,"function":"registerWidget","class":"OC\\Dashboard\\Manager","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php","line":131,"function":"loadLazyPanels","class":"OC\\Dashboard\\Manager","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/apps/dashboard/lib/Controller/DashboardController.php","line":101,"function":"getWidgets","class":"OC\\Dashboard\\Manager","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\Dashboard\\Controller\\DashboardController","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/mergerfs/mfs/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/mergerfs/mfs/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/mergerfs/mfs/nextcloud/lib/private/Dashboard/Manager.php","Line":55,"message":"Could not register lazy dashboard widget: Dashboard widget with this id has already been registered","exception":{},"CustomMessage":"Could not register lazy dashboard widget: Dashboard widget with this id has already been registered"}}
data/nextcloud.log
```

### Additional info

Edge and windows Client have same problem

**Comment by szaimen** [comment]
I hears somewhere that this is caused by the recognize app
