### ISSUE TITLE
[Bug]: Nextcloud 26.0.0 (RC3) CalDav calendar sync problem 

### ISSUE THREAD

**Issue by Mululu** [nextcloud/server#37281]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

From my point of view an obscure problem:

Basically, the point is that not all calendars are correctly synchronized when the DAVx5 app is set up again. There were no problems with DAVx5 apps that had been set up for some time.

Users of our organization have asked me that this no longer works for them. To recreate the whole thing, I uninstalled and then reinstalled my own DAVx5 app. The setup is carried out using the menu item in the Nextcloud App (Settings). Calendar selected for synchronization and synchronized. 4 out of 4 calendars are displayed in Google Calendar (foldable sidebar on the left) With 3 out of 4 calendars only the appointments are synchronized.

After activating the error log, it turns out that something is generating a "Got 503 Service unavailable, trying again later" error when retrieving the appointments >> see error log below.

The curious thing is that by deactivating and activating the synchronization of the individual calendars in a different order, the problem is transferred to another calendar. E.g.: initially calendar 1 was not synchronized correctly and after deactivation/activation calendar 3.

What is also strange >> If you create an appointment in the non-syncronizing calendar, this appointment is successfully syncronized, but only this one.

I hope I was able to explain the problem well enough. Since I personally only noticed the problem with Nextcloud 26, I assume that it is Nextcloud and not DAVx5

### Steps to reproduce

1. Uninstall Davx5 App and then reinstall it
2. Set up the Davx5 app using the menu item in the Nextcloud app (settings).
3. Allow/set all necessary permissions and settings in the DAVx5
4. Select calendars to sync and then sync

### Expected behavior

Working synchronization

### Installation method

Community Manual installation with Archive

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.***.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.10",
        "overwrite.cli.url": "https:\/\/cloud.***.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "appstoreenabled": "false",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "share_folder": "\/Mit Dir geteilt",
        "force_language": "de",
        "force_locale": "de_DE",
        "activity_use_cached_mountpoints": true,
        "default_phone_region": "DE",
        "skeletondirectory": "",
        "overwriteprotocol": "https",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "piwik",
            "impersonate"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.***.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.10",
        "overwrite.cli.url": "https:\/\/cloud.***.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "appstoreenabled": "false",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "share_folder": "\/Mit Dir geteilt",
        "force_language": "de",
        "force_locale": "de_DE",
        "activity_use_cached_mountpoints": true,
        "default_phone_region": "DE",
        "skeletondirectory": "",
        "overwriteprotocol": "https",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "piwik",
            "impersonate"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - calendar: 4.3.0-rc.2
  - cloud_federation_api: 1.9.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dav: 1.25.0
  - external: 5.1.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - groupfolders: 14.0.0
  - impersonate: 1.13.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - piwik: 0.11.1
  - provisioning_api: 1.16.0
  - related_resources: 1.1.0-alpha1
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - suspicious_login: 4.4.0
  - tasks: 0.14.5
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0 (installed 2.3.0)
  - circles: 26.0.0 (installed 22.1.1)
  - comments: 1.16.0 (installed 1.12.0)
  - dashboard: 7.6.0 (installed 7.0.0)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.10.1)
  - files_downloadactivity: 1.15.0 (installed 1.15.0)
  - files_external: 1.18.0
  - firstrunwizard: 2.15.0 (installed 2.9.0)
  - nextcloud_announcements: 1.15.0 (installed 1.9.0)
  - photos: 2.2.0 (installed 1.5.0)
  - privacy: 1.10.0 (installed 1.6.0)
  - recommendations: 1.5.0 (installed 0.8.0)
  - serverinfo: 1.16.0 (installed 1.10.0)
  - sharerenamer: 3.1.0 (installed 3.1.0)
  - support: 1.9.0 (installed 1.5.0)
  - survey_client: 1.14.0 (installed 1.8.0)
  - systemtags: 1.16.0 (installed 1.12.0)
  - twofactor_totp: 8.0.0-alpha.0
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.0.1)
  - weather_status: 1.6.0 (installed 1.0.0)
```

### Additional info

2023-03-17 06:48:18 1471 [at.bitfire.dav4jvm.BasicDigestAuthHandler] Adding Basic authorization header for https://cloud.***.de/remote.php/dav/calendars/***/ff-dienste/
2023-03-17 06:48:18 1505 [syncadapter.SyncManager] b17b42cb-476e-4517-abed-21528746670d.ics has been added remotely, queueing download
2023-03-17 06:48:18 1505 [syncadapter.SyncManager] bbad2968-5b1a-429f-ac91-7a9402280b4a.ics has been added remotely, queueing download
2023-03-17 06:48:19 1471 [HttpClient] <-- 503 https://cloud.***.de/remote.php/dav/calendars/***/ff-dienste/ (77ms)
2023-03-17 06:48:19 1471 [HttpClient] server: nginx
2023-03-17 06:48:19 1471 [HttpClient] date: Fri, 17 Mar 2023 05:48:19 GMT
2023-03-17 06:48:19 1471 [HttpClient] content-type: text/html; charset=UTF-8
2023-03-17 06:48:19 1471 [HttpClient] content-length: 0
2023-03-17 06:48:19 1471 [HttpClient] x-content-type-options: nosniff
2023-03-17 06:48:19 1471 [HttpClient] x-xss-protection: 1; mode=block
2023-03-17 06:48:19 1471 [HttpClient] strict-transport-security: max-age=31536000; includeSubDomains; preload
2023-03-17 06:48:19 1471 [HttpClient] permissions-policy: geolocation=(self ); microphone=(self); midi=(self);camera=(self);usb=(self);magnetometer=(self);accelerometer=(self);gyroscope=(self)
2023-03-17 06:48:19 1471 [HttpClient] referrer-policy: no-referrer
2023-03-17 06:48:19 1471 [HttpClient] x-frame-options: SAMEORIGIN
2023-03-17 06:48:19 1471 [HttpClient] x-permitted-cross-domain-policies: none
2023-03-17 06:48:19 1471 [HttpClient] x-robots-tag: noindex, nofollow
2023-03-17 06:48:19 1471 [HttpClient] expires: Thu, 19 Nov 1981 08:52:00 GMT
2023-03-17 06:48:19 1471 [HttpClient] cache-control: no-store, no-cache, must-revalidate
2023-03-17 06:48:19 1471 [HttpClient] pragma: no-cache
2023-03-17 06:48:19 1471 [HttpClient] content-security-policy: default-src 'self'; script-src 'self' 'nonce-WVY1dW95anpMOWNNVG11V05kRTRaaFg3M20xamZLV0k4UnMrOTlCVDZscz06RXdzdDVHUERlcFI2Tml6REJKMUNQeWF0ckIweU1KSFFwVkpJeHVFYjNRZz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
2023-03-17 06:48:19 1471 [HttpClient] set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
2023-03-17 06:48:19 1471 [HttpClient] set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
2023-03-17 06:48:19 1471 [HttpClient] <-- END HTTP (0-byte body)
2023-03-17 06:48:19 1471 [syncadapter.SyncManager] Got 503 Service unavailable, trying again later
EXCEPTION at.bitfire.dav4jvm.exception.ServiceUnavailableException: HTTP 503 
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:6)
	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:1)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:2)
	at at.bitfire.dav4jvm.DavCalendar.multiget(DavCalendar.kt:67)
	at at.bitfire.dav4jvm.DavCalendar.multiget$default(DavCalendar.kt:12)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$downloadRemote$1.invoke(CalendarSyncManager.kt:2)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$downloadRemote$1.invoke(CalendarSyncManager.kt:1)
	at at.bitfire.davdroid.syncadapter.SyncManager.remoteExceptionContext(SyncManager.kt:1)
	at at.bitfire.davdroid.syncadapter.SyncManager.remoteExceptionContext(SyncManager.kt:5)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager.downloadRemote(CalendarSyncManager.kt:46)
	at at.bitfire.davdroid.syncadapter.SyncManager$syncRemote$1$download$1.invokeSuspend(SyncManager.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:154)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:106)
	at at.bitfire.davdroid.syncadapter.SyncManager.syncRemote(SyncManager.kt:41)
	at at.bitfire.davdroid.syncadapter.SyncManager$performSync$1.invoke(SyncManager.kt:46)
	at at.bitfire.davdroid.syncadapter.SyncManager$performSync$1.invoke(SyncManager.kt:1)
	at at.bitfire.davdroid.syncadapter.SyncManager.unwrapExceptions(SyncManager.kt:2)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.kt:20)
	at at.bitfire.davdroid.syncadapter.CalendarsSyncAdapterService$CalendarsSyncAdapter.sync(CalendarsSyncAdapterService.kt:218)
	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter$onPerformSync$1.invoke(SyncAdapterService.kt:8)
	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter$onPerformSync$1.invoke(SyncAdapterService.kt:1)
	at at.bitfire.davdroid.util.ConcurrentUtils.runSingle(ConcurrentUtils.kt:21)
	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:108)
	at at.bitfire.davdroid.syncadapter.SyncWorker.doWork(SyncWorker.kt:302)
	at androidx.work.Worker$1.run(Worker.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by tcitworld** [comment]
This looks like https://github.com/bitfireAT/davx5-ose/discussions/285

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/issues/37277
