### ISSUE TITLE
[Bug]: When I used Nextcloud App auto uploader , it not working

### ISSUE THREAD

**Issue by ndj888** [nextcloud/server#37474]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When i upgrade to NC 26.0 , auto uploader not working in nc mobile app.

### Steps to reproduce

1. Use the latest version NC 26.0.0 from NC 25.5
2. I like always doing, open the next cloud app then it doesn't work in then auto uploader. I get a 500 server error
3. this is some log information, i need nc team help. this problem so sad

### Expected behavior

The auto upload will working.

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Error: Class "OCP\AppFramework\Db\Mapper" not found in /var/www/html/custom_apps/music/lib/Db/BaseMapper.php:29
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(578): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/var/www/html/c...')
#2 /var/www/html/custom_apps/music/lib/Db/ArtistMapper.php(24): Composer\Autoload\ClassLoader->loadClass('OCA\\Music\\Db\\Ba...')
#3 /var/www/html/lib/composer/composer/ClassLoader.php(578): include('/var/www/html/c...')
#4 /var/www/html/lib/composer/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/var/www/html/c...')
#5 /var/www/html/custom_apps/music/lib/App/Music.php(363): Composer\Autoload\ClassLoader->loadClass('OCA\\Music\\Db\\Ar...')
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\Music\App\Music->OCA\Music\App\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#7 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('ArtistMapper')
#9 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(487): OC\AppFramework\Utility\SimpleContainer->query('ArtistMapper')
#10 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('ArtistMapper')
#11 /var/www/html/custom_apps/music/lib/App/Music.php(272): OC\AppFramework\DependencyInjection\DIContainer->query('ArtistMapper')
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\Music\App\Music->OCA\Music\App\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#13 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#14 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('ArtistBusinessL...')
#15 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(487): OC\AppFramework\Utility\SimpleContainer->query('ArtistBusinessL...')
#16 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('ArtistBusinessL...')
#17 /var/www/html/custom_apps/music/lib/App/Music.php(576): OC\AppFramework\DependencyInjection\DIContainer->query('ArtistBusinessL...')
#18 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\Music\App\Music->OCA\Music\App\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#19 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#20 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('Scanner')
#21 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(487): OC\AppFramework\Utility\SimpleContainer->query('Scanner')
#22 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('Scanner')
#23 /var/www/html/custom_apps/music/appinfo/register_command.php(25): OC\AppFramework\DependencyInjection\DIContainer->query('Scanner')
#24 /var/www/html/lib/private/Console/Application.php(138): require('/var/www/html/c...')
#25 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

### List of activated Apps

```shell
An unhandled exception has been thrown:
Error: Class "OCP\AppFramework\Db\Mapper" not found in /var/www/html/custom_apps/music/lib/Db/BaseMapper.php:29
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(578): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/var/www/html/c...')
#2 /var/www/html/custom_apps/music/lib/Db/ArtistMapper.php(24): Composer\Autoload\ClassLoader->loadClass('OCA\\Music\\Db\\Ba...')
#3 /var/www/html/lib/composer/composer/ClassLoader.php(578): include('/var/www/html/c...')
#4 /var/www/html/lib/composer/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/var/www/html/c...')
#5 /var/www/html/custom_apps/music/lib/App/Music.php(363): Composer\Autoload\ClassLoader->loadClass('OCA\\Music\\Db\\Ar...')
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\Music\App\Music->OCA\Music\App\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#7 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('ArtistMapper')
#9 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(487): OC\AppFramework\Utility\SimpleContainer->query('ArtistMapper')
#10 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('ArtistMapper')
#11 /var/www/html/custom_apps/music/lib/App/Music.php(272): OC\AppFramework\DependencyInjection\DIContainer->query('ArtistMapper')
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\Music\App\Music->OCA\Music\App\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#13 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#14 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('ArtistBusinessL...')
#15 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(487): OC\AppFramework\Utility\SimpleContainer->query('ArtistBusinessL...')
#16 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('ArtistBusinessL...')
#17 /var/www/html/custom_apps/music/lib/App/Music.php(576): OC\AppFramework\DependencyInjection\DIContainer->query('ArtistBusinessL...')
#18 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\Music\App\Music->OCA\Music\App\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#19 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#20 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('Scanner')
#21 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(487): OC\AppFramework\Utility\SimpleContainer->query('Scanner')
#22 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('Scanner')
#23 /var/www/html/custom_apps/music/appinfo/register_command.php(25): OC\AppFramework\DependencyInjection\DIContainer->query('Scanner')
#24 /var/www/html/lib/private/Console/Application.php(138): require('/var/www/html/c...')
#25 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

### Nextcloud Logs

```shell
{"reqId":"ieVGlyfircXSiCxMTFKK","level":3,"time":"2023-03-30T04:18:17+00:00","remoteAddr":"172.68.91.161","user":"longbob","app":"webdav","method":"PUT","url":"/remote.php/dav/files/longbob/%E5%AE%9E%E6%97%B6%E4%B8%8A%E4%BC%A0/iPhone/23-03-30%2008-10-10%204435.png","message":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/4.7.0","version":"26.0.0.11","exception":{"Exception":"Error","Message":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":578,"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":432,"function":"Composer\\Autoload\\{closure}","class":"Composer\\Autoload\\ClassLoader","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/music/lib/Db/ArtistMapper.php","line":24,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Music\\Db\\BaseMapper"]},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":578,"args":["/var/www/html/custom_apps/music/lib/Db/ArtistMapper.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":432,"function":"Composer\\Autoload\\{closure}","class":"Composer\\Autoload\\ClassLoader","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/music/lib/App/Music.php","line":363,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Music\\Db\\ArtistMapper"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":171,"function":"OCA\\Music\\App\\{closure}","class":"OCA\\Music\\App\\Music","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["ArtistMapper"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":487,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["ArtistMapper"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["ArtistMapper"]},{"file":"/var/www/html/custom_apps/music/lib/App/Music.php","line":272,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["ArtistMapper"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":171,"function":"OCA\\Music\\App\\{closure}","class":"OCA\\Music\\App\\Music","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["ArtistBusinessLayer"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":487,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["ArtistBusinessLayer"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["ArtistBusinessLayer"]},{"file":"/var/www/html/custom_apps/music/lib/App/Music.php","line":576,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["ArtistBusinessLayer"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":171,"function":"OCA\\Music\\App\\{closure}","class":"OCA\\Music\\App\\Music","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["Scanner"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":487,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["Scanner"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["Scanner"]},{"file":"/var/www/html/custom_apps/music/lib/Hooks/FileHooks.php","line":75,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["Scanner"]},{"file":"/var/www/html/custom_apps/music/lib/Hooks/FileHooks.php","line":62,"function":"handleUpdated","class":"OCA\\Music\\Hooks\\FileHooks","type":"::","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"function":"updated","class":"OCA\\Music\\Hooks\\FileHooks","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Hooks/EmitterTrait.php","line":105,"function":"call_user_func_array","args":[["OCA\\Music\\Hooks\\FileHooks","updated"],["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/lib/private/Hooks/PublicEmitter.php","line":40,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/lib/private/Files/Node/Root.php","line":143,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"function":"emit","class":"OC\\Files\\Node\\Root","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":72,"function":"call_user_func_array","args":[[["OC\\Files\\Node\\Root"],"emit"],["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":100,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":["emit",["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":114,"function":"emit","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":105,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->","args":[["/\u5b9e\u65f6\u4e0a\u4f20/iPhone/23-03-30 08-10-10 4435.png"]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":471,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","post_write",["/\u5b9e\u65f6\u4e0a\u4f20/iPhone/23-03-30 08-10-10 4435.png"]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":398,"function":"emitPostHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[true]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1137,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":492,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":366,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":171,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/music/lib/Db/BaseMapper.php","Line":29,"message":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found","exception":{},"CustomMessage":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found"}}
```

**Comment by szaimen** [comment]
Hi, you should bw able to fix this by disabling the music app

**Comment by ndj888** [comment]
> Hi, you should bw able to fix this by disabling the music app

Thank you i delete the music directory in customer_apps , then it working . So good , thank you .
