### ISSUE TITLE
[Bug]: Maximum number of allowable file uploads has been exceeded at Unknown#0, only in .md files

### ISSUE THREAD

**Issue by Whoffie** [nextcloud/server#37721]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

To my knowledge, this is not a PHP or server issue. I am able to upload images and other documents to my main Nextcloud file system. The issue arises when an image is uploaded to a markdown document using Nextcloud's built-in markdown editor. When an image is uploaded, a simple "Upload error" appears in the top right corner of my screen. Upon further inspection of the logs, I see the following response:

Maximum number of allowable file uploads has been exceeded at Unknown#0

This _would_ lead me to believe that there is something wrong with my install / PHP settings specifically, but as I mentioned earlier, I am able to upload any number of documents and images to my Nextcloud file section.

I am currently on the latest version, Nextcloud Hub 4 (26.0.0)

### Steps to reproduce

1. Create a document in Markdown
2. Attempt to upload an image using the built-in WYSIWYG editor

### Expected behavior

An image is successfully inserted into the markdown document

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Error: Class "PDO" not found in /var/www/nextcloud/lib/public/DB/QueryBuilder/IQueryBuilder.php:44
Stack trace:
#0 /var/www/nextcloud/lib/private/AppConfig.php(414): OC\DB\Connection->getQueryBuilder()
#1 /var/www/nextcloud/lib/private/AppConfig.php(183): OC\AppConfig->loadConfigValues()
#2 /var/www/nextcloud/lib/private/AppConfig.php(373): OC\AppConfig->getApps()
#3 /var/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\AppConfig->getValues(false, 'installed_versi...')
#4 /var/www/nextcloud/lib/private/Server.php(729): OC_App::getAppVersions()
#5 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}(Object(OC\Server))
#6 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
#8 /var/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...', true)
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get('OC\\Memcache\\Fac...')
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCP\\ICacheFacto...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OCP\\ICacheFacto...', true)
#15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OCP\\ICacheFacto...')
#16 /var/www/nextcloud/lib/private/Server.php(1108): OC\AppFramework\Utility\SimpleContainer->get('OCP\\ICacheFacto...')
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#19 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...')
#20 /var/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Lock\\ILocki...', true)
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OCP\\Lock\\ILocki...')
#22 /var/www/nextcloud/lib/private/Server.php(2063): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Lock\\ILocki...')
#23 /var/www/nextcloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#24 /var/www/nextcloud/lib/private/Server.php(464): OC\Files\View->__construct()
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}(Object(OC\Server))
#26 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#27 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OC\\Files\\Node\\H...')
#28 /var/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', true)
#29 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OC\\Files\\Node\\H...')
#30 /var/www/nextcloud/lib/private/Server.php(1465): OC\AppFramework\Utility\SimpleContainer->get('OC\\Files\\Node\\H...')
#31 /var/www/nextcloud/lib/base.php(623): OC\Server->boot()
#32 /var/www/nextcloud/lib/base.php(1164): OC::init()
#33 /var/www/nextcloud/console.php(48): require_once('/var/www/nextcl...')
#34 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

**Comment by solracsf** [comment]
Using https://github.com/nextcloud/text?
