### ISSUE TITLE
[Bug]: occ files:scan fails with ERROR: invalid byte sequence for encoding "UTF8": 0x96

### ISSUE THREAD

**Issue by 905jay** [nextcloud/server#37803]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After moving a large amount of data from an NFS share to the Nextcloud AIO Data folder, I get errors when performing an occ scan

Cross-post as requested from:
https://github.com/nextcloud/all-in-one/discussions/2373#discussioncomment-5647096

### Steps to reproduce

1. build a fresh VM and new install of docker nextcloud AIO from using docker and this github guide to a VM
2. perform all system updates to Debian 11
3. run through the initial startup of nextcloud-aio
4. create my users on the local system
5. rsync a large amount of data to the new user I created
6. On the host VM take ownership of all the files I rsync over
    chown -R www-data:www-data /var/lib/docker/volumes/nextcloud_aio_nextcloud_data/_data/jason/files
7. attempt to occ scan files for my user. Interestingly, it worked for other users on the system, but fails for my user "jason"
    nextcloud-aio:~$ sudo docker exec --user www-data -it 147c8ce311a6 php occ files:scan jason

### Expected behavior

Running nextcloud from linuxserver.io on unraid, when adding a large amount of files I can use the occ command to have nextcloud recognize that they are now present

### Installation method

Official All-in-One appliance

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Sysyem Details

Operating System: Linux 5.10.0-21-amd64 x86_64
CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (4 cores)
Memory: 15.63 GB
PHP details

Version: 8.0.28
Memory limit: 512 MB
Max execution time: 3600
Upload max size: 10 GB
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, Phar, exif, gd, gmp, imagick, imap, intl, ldap, memcached, pcntl, pdo_pgsql, pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache
Database

Type: pgsql
Version: PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
Size: 15.8 MB
```

### List of activated Apps

```shell
fresh install with default apps
```

### Nextcloud Logs

```shell
log appears empty
```

### Additional info

I checked the DB logs and see this:

```
2023-04-17 11:11:04.241 EDT [3462] ERROR: invalid byte sequence for encoding "UTF8": 0x96

2023-04-17 11:11:04.241 EDT [3462] CONTEXT: unnamed portal parameter $8

2023-04-17 11:11:04.241 EDT [3462] STATEMENT: INSERT INTO "oc_filecache" ("mimepart", "mimetype", "mtime", "size", "etag", "storage_mtime", "permissions", "name", "parent", "checksum", "path_hash", "path", "storage") VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)

2023-04-17 11:11:04.253 EDT [3462] ERROR: current transaction is aborted, commands ignored until end of transaction block

2023-04-17 11:11:04.253 EDT [3462] STATEMENT: INSERT INTO "oc_filecache" ("mimepart", "mimetype", "mtime", "size", "etag", "storage_mtime", "permissions", "name", "parent", "checksum", "path_hash", "path", "storage") VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)

2023-04-17 11:11:04.257 EDT [3462] ERROR: current transaction is aborted, commands ignored until end of transaction block

2023-04-17 11:11:04.257 EDT [3462] STATEMENT: INSERT INTO "oc_filecache" ("mimepart", "mimetype", "mtime", "size", "etag", "storage_mtime", "permissions", "name", "parent", "checksum", "path_hash", "path", "storage") VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)

2023-04-17 11:11:04.262 EDT [3462] ERROR: current transaction is aborted, commands ignored until end of transaction block

2023-04-17 11:11:04.262 EDT [3462] STATEMENT: INSERT INTO "oc_filecache" ("mimepart", "mimetype", "mtime", "size", "etag", "storage_mtime", "permissions", "name", "parent", "checksum", "path_hash", "path", "storage") VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)

2023-04-17 11:11:04.267 EDT [3462] ERROR: current transaction is aborted, commands ignored until end of transaction block

2023-04-17 11:11:04.267 EDT [3462] STATEMENT: INSERT INTO "oc_mimetypes" ("mimetype") SELECT $1 FROM "oc_mimetypes" WHERE "mimetype" = $2 HAVING COUNT(*) = 0

```

```
Starting scan for user 1 out of 1 (jason)
Exception during scan: An exception occurred while executing a query: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
#0 /var/www/html/lib/private/DB/ConnectionAdapter.php(101): OC\DB\Exceptions\DbalException::wrap(Object(Doctrine\DBAL\Exception\DriverException))
#1 /var/www/html/lib/private/Files/Type/Loader.php(116): OC\DB\ConnectionAdapter->insertIfNotExist('*PREFIX*mimetyp...', Array)
#2 /var/www/html/lib/private/Files/Type/Loader.php(84): OC\Files\Type\Loader->store('text/rtf')
#3 /var/www/html/lib/private/Files/Cache/Cache.php(451): OC\Files\Type\Loader->getId('text/rtf')
#4 /var/www/html/lib/private/Files/Cache/Cache.php(299): OC\Files\Cache\Cache->normalizeData(Array)
#5 /var/www/html/lib/private/Files/Cache/Scanner.php(296): OC\Files\Cache\Cache->insert('files/Insight/S...', Array)
#6 /var/www/html/lib/private/Files/Cache/Scanner.php(226): OC\Files\Cache\Scanner->addToCache('files/Insight/S...', Array, -1)
#7 /var/www/html/lib/private/Files/Cache/Scanner.php(445): OC\Files\Cache\Scanner->scanFile('files/Insight/S...', 3, 4078, false, true, Array)
#8 /var/www/html/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->handleChildren('files/Insight/S...', true, 3, 4078, true, 113509)
#9 /var/www/html/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('files/Insight/S...', true, 3, 4078, true)
#10 /var/www/html/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('files/Insight/S...', true, 3, 3769, true)
#11 /var/www/html/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('files/Insight/S...', true, 3, 3549, true)
#12 /var/www/html/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('files/Insight', true, 3, 3484, true)
#13 /var/www/html/lib/private/Files/Cache/Scanner.php(394): OC\Files\Cache\Scanner->scanChildren('files', true, 3, 220, true)
#14 /var/www/html/lib/private/Files/Cache/Scanner.php(342): OC\Files\Cache\Scanner->scanChildren('', true, 3, 217, true, Array)
#15 /var/www/html/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\Scanner->scan('', true, 3)
#16 /var/www/html/apps/files/lib/Command/Scan.php(161): OC\Files\Utils\Scanner->scan('/jason', true, NULL)
#17 /var/www/html/apps/files/lib/Command/Scan.php(217): OCA\Files\Command\Scan->scanFiles('jason', '/jason', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#18 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/console.php(100): OC\Console\Application->run()
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
#26 {main}
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 122     | 461   | 00:00:03     |
+---------+-------+--------------+

![2023-04-17 09 25 28](https://user-images.githubusercontent.com/13971036/232497604-c4c64f76-c18e-4a84-99b7-5efaae5508d1.png)```
```

I created a script to find all files and convert them to UTF-8 where needed (pasted below) and after that ran, the errors remained
```
file and convert it to UTF-8
for file in $files
do
  # Check if the file is a text file
  if [[ $(file "$file") == *"text"* ]]; then
    # Convert the file to UTF-8 using iconv
    iconv -f $(file -b --mime-encoding "$file") -t utf-8 "$file" -o "$file.utf8"
    # Replace the original file with the converted file
    mv "$file.utf8" "$file"
  fi
done
```

**Comment by solracsf** [comment]
Are you able to test this using MySQL instead of PostgreSQL?

**Comment by joshtrichards** [comment]
Some things to consider trying:

* Add `-vvv` to the command line to get some extra verbosity - e.g.:

` ./occ files:scan -vvv jason`

What file is it stopping on or just before?

Does the filename - or content - suggest anything unusual?

* It looks like it's kicking in pretty quickly, within your Insights folder

You might also try scanning other parts of your folder structure explicitly to get an idea of how broadly the trigger is by using `--path` parameter to files:scan

If there is a bug on the NC side it'll be easier to resolve if we can find a reproduceable file/folder/something.

You also stated:

>  nextcloud from linuxserver.io on unraid

Where does that come into play with your NC AIO deployment? Is that where your files are being moved from?

**Comment by nextcloud-command** [comment]
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.
