### ISSUE TITLE
[Bug]: Login instrumented test on Android fails as element not interactable

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#38213]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On Android we run a test using web login.
This since a while fails with:
```
java.lang.RuntimeException: java.lang.RuntimeException: Error in evaluationEvaluation: status: 12 value: {message=Element is not currently interactable and may not be manipulated} hasMessage: true message: Element is not currently interactable and may not be manipulated
at androidx.test.espresso.web.sugar.Web$WebInteraction$ExceptionPropagator.<init>(Web.java:4)
at androidx.test.espresso.web.sugar.Web$WebInteraction.doEval(Web.java:17)
at androidx.test.espresso.web.sugar.Web$WebInteraction.perform(Web.java:1)
at com.owncloud.android.ui.LoginIT.login(LoginIT.kt:89)
 ```

We try to access and enter login name:
```
// username
        Web.onWebView()
            .withElement(DriverAtoms.findElement(Locator.XPATH, "//input[@id='user']"))
            .perform(DriverAtoms.webKeys(loginName))
```

### Steps to reproduce

1. run LoginIT from Android test suite

### Expected behavior

Test should pass

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
/
```

**Comment by tobiasKaminsky** [comment]
Argh. Actually the problem is that test is not going to username/password view, but is stucked in "connect to your account".

**Comment by tobiasKaminsky** [comment]
Hm. It seems that click is executed, but nothing happens.
Connecting to it via remote chrome tab, I cannot see a problem, when clicking on it.

Only errors are:
```
Error with Feature-Policy header: Unrecognized feature: 'payment'.
background:1 Failed to load resource: the server responded with a status of 404 (Not Found)
core-common.js:2 Uncaught SyntaxError: Unexpected token .
core-files_fileinfo.js:2 Uncaught ReferenceError: OC is not defined
    at core-files_fileinfo.js:2
mimetype.js:26 Uncaught ReferenceError: OC is not defined
    at mimetype.js:26
mimetypelist.js:9 Uncaught ReferenceError: OC is not defined
    at mimetypelist.js:9
select2-toggleselect.js:53 Uncaught ReferenceError: Select2 is not defined
    at select2-toggleselect.js:53
authpicker.js:1 Uncaught ReferenceError: jQuery is not defined
    at authpicker.js:1
encryption.js:12 Uncaught ReferenceError: OC is not defined
    at encryption.js:12
files_sharing-main.js:2 Uncaught ReferenceError: OC is not defined
    at files_sharing-main.js:2
theming.js:1 Uncaught ReferenceError: OCA is not defined
    at theming.js:1
26 background:1 Failed to load resource: the server responded with a status of 404 (Not Found)
````

**Comment by SystemKeeper** [comment]
Could it be a timing issue because of the button being disabled at first? See https://github.com/nextcloud/server/pull/36286

**Comment by SystemKeeper** [comment]
> Connecting to it via remote chrome tab, I cannot see a problem, when clicking on it.

May I misinterpreted this line. When you connect via remote tab, it _does_ work or it _does not_ work?

**Comment by SystemKeeper** [comment]
Also sounds a bit like https://github.com/nextcloud/server/issues/36934

**Comment by mpivchev** [comment]
As @marinofaggiana mentioned, there is a similar issue on iOS 14 where the Log in button can't be pressed. We are probably not going to work on it ourselves since we will drop support for iOS 14 (it's too old), but if this manages to fix it until then that would be great.

**Comment by tobiasKaminsky** [comment]
I tested it with latest android 14 and it works.
So whatever it caused, it is only happening on old emulator / with old webviews.

**Comment by mpivchev** [comment]
We stopped support for iOS 14 for iOS and this doesn't seem to be a problem in newer versions.
