### ISSUE TITLE
Add a new calendar from client results in error

### ISSUE THREAD

**Issue by maprambo** [nextcloud/server#3851]
[(I was told to post the issue here on `nextcloud/server` as the backend is part of the core)](https://github.com/nextcloud/calendar/issues/370).

### Steps to reproduce
1. Add calendar in macOS Calendar app

### Expected behaviour
The new calendar should be created on the server.

### Actual behaviour
You're constantly getting response 500

### Server configuration
**Operating system**:  Ubuntu 16.04.2 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0.13

**Server version:** 11.0.1 (stable)

**Updated from an older installed version or fresh install:** Updated, used ownCloud for years

**Signing status (ownCloud/Nextcloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**

```
  - activity: 2.4.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocuugavv819x",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***(I hate webcrawlers)***"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "***(I hate webcrawlers)***",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "cloud",
        "mail_domain": "***(I hate webcrawlers)***",
        "loglevel": 2,
        "appstore.experimental.enabled": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_rotate_size": 104857600,
        "auth.bruteforce.protection.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** webdav and dropbox

### Client configuration
**Browser:** Safari 10.0.3

**Operating system:** macOS Sierra 10.12.3 (16D32)

**CalDAV-clients:** Apple Calendar 9.0 (2155.15)

#### Web server error log
```
(nothing)
```

#### Log file (data/owncloud.log)
```
{"reqId":"keRfN9lGWi\/QT2IJZW1u","remoteAddr":"192.168.2.137","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_calendars` (`principaluri`, `uri`, `synctoken`, `transparent`, `components`, `displayname`, `timezone`, `calendarorder`, `calendarcolor`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\\"principals\\\\\\\/users\\\\\\\/matthes\\\", \\\"47755DA1-827E-4FBF-A3A2-E819955442E0\\\", 1, false, \\\"VTODO\\\", \\\"Neue Liste\\\", \\\"BEGIN:VCALENDAR\\\\r\\\\nVERSION:2.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Apple Inc.\\\\\\\/\\\\\\\/Mac OS X 10.12.3\\\\\\\/\\\\\\\/EN\\\\r\\\\nCALSCALE:GREGORIAN\\\\r\\\\nBEGIN:VTIMEZONE\\\\r\\\\nTZID:Europe\\\\\\\/Berlin\\\\r\\\\nBEGIN:DAYLIGHT\\\\r\\\\nTZOFFSETFROM:+0100\\\\r\\\\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\\\\r\\\\nDTSTART:19810329T020000\\\\r\\\\nTZNAME:MESZ\\\\r\\\\nTZOFFSETTO:+0200\\\\r\\\\nEND:DAYLIGHT\\\\r\\\\nBEGIN:STANDARD\\\\r\\\\nTZOFFSETFROM:+0200\\\\r\\\\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\\\\r\\\\nDTSTART:19961027T030000\\\\r\\\\nTZNAME:MEZ\\\\r\\\\nTZOFFSETTO:+0100\\\\r\\\\nEND:STANDARD\\\\r\\\\nEND:VTIMEZONE\\\\r\\\\nEND:VCALENDAR\\\\r\\\\n\\\", \\\"188\\\", \\\"#0E61B9FF\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'transparent' at row 1\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(177): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(622): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarHome.php(265): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->createCalendar('principals\\\/user...', '47755DA1-827E-4...', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1173): Sabre\\\\CalDAV\\\\CalendarHome->createExtendedCollection('47755DA1-827E-4...', Object(Sabre\\\\DAV\\\\MkCol))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(303): Sabre\\\\DAV\\\\Server->createCollection('calendars\\\/matth...', Object(Sabre\\\\DAV\\\\MkCol))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\Plugin->httpMkCalendar(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCALEND...', Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116,\"User\":\"matthes\"}","level":4,"time":"2017-03-15T15:37:05+00:00","method":"MKCALENDAR","url":"\/remote.php\/dav\/calendars\/matthes\/47755DA1-827E-4FBF-A3A2-E819955442E0\/","user":"matthes","version":"11.0.2.7"}
```

#### Browser log
```
(nothing)
```

**Comment by nickvergessen** [comment]
@maprambo can you please try the following changes:
https://github.com/nextcloud/server/pull/3865/files

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/4166
Was backported for 10 and 11
