### ISSUE TITLE
[Bug]: After upgrading to "27", database indices cannot be upgraded and ONLYOFFICE does not work.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/server#38821]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to "27", database indices cannot be upgraded and ONLYOFFICE does not work.

### Steps to reproduce

1. _Administreerimise seaded_.
2.  See that it complains:

>     The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
> Missing index "mounts_user_root_path_index" in table "oc_mounts".
> 

3.  So I did:
    
    `kalmer@test:/projektid/nextcloud$ sudo -u www-data php --define apc.enable_cli=1 occ db:add-missing-indices`

> An unhandled exception has been thrown:
> OCP\AutoloadNotAllowedException: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php in /projektid/nextcloud/lib/autoloader.php:141
> Stack trace:
> #0 /projektid/nextcloud/lib/autoloader.php(166): OC\Autoloader->isValidPath()
> #1 [internal function]: OC\Autoloader->load()
> #2 /projektid/nextcloud/lib/private/ServerContainer.php(106): class_exists()
> #3 /projektid/nextcloud/lib/private/ServerContainer.php(186): OC\ServerContainer->getAppContainer()
> #4 /projektid/nextcloud/lib/private/ServerContainer.php(153): OC\ServerContainer->getAppContainerForService()
> #5 /projektid/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
> #6 /projektid/nextcloud/lib/private/Console/Application.php(131): OC\Console\Application->loadCommandsFromInfoXml()
> #7 /projektid/nextcloud/console.php(99): OC\Console\Application->loadCommands()
> #8 /projektid/nextcloud/occ(11): require_once('...')
> #9 {main}kalmer@test:/projektid/ne

4. See that the settings section for ONLYOFFICE is gone!
5. _Failid_.
6. Click an existing XLSX file! Experience that it only offers a download option, not opening with ONLYOFFICE.

### Expected behavior

ONLYOFFICE works as previously and upgrading indices is possible.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
almer@test:/projektid/nextcloud$ sudo -u www-data php occ config:list system
[sudo] password for kalmer: 
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ php occ config:list system
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ ./occ config:list system
-bash: ./occ: Permission denied
```

### List of activated Apps

```shell
kalmer@test:/projektid/nextcloud$ sudo -u www-data php occ app:list
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ php occ app:list
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ ./occ app:list
-bash: ./occ: Permission denied
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
kalmer@test:/projektid/nextcloud$ tail data/nextcloud.log
{"reqId":"D0gcWqFmCE4gNjKVcUyr","level":4,"time":"2023-06-14T16:37:12+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"onlyoffice","method":"POST","url":"/index.php/apps/text/session/push","message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":217,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":400,"function":"isBootable","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/private/legacy/OC_App.php","line":126,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1044,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/projektid/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
{"reqId":"gM2NXbEBoX0qObNdshAy","level":4,"time":"2023-06-14T16:37:38+00:00","remoteAddr":"127.0.0.1","user":"--","app":"onlyoffice","method":"GET","url":"/index.php/settings/integrity/failed","message":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":129,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":696,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1173,"function":"init","class":"OC","type":"::"},{"file":"/projektid/nextcloud/index.php","line":34,"args":["/projektid/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
{"reqId":"gM2NXbEBoX0qObNdshAy","level":0,"time":"2023-06-14T16:37:38+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"issuetemplate","method":"GET","url":"/index.php/settings/integrity/failed","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","data":{"app":"issuetemplate"}}
{"reqId":"gM2NXbEBoX0qObNdshAy","level":4,"time":"2023-06-14T16:37:38+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"onlyoffice","method":"GET","url":"/index.php/settings/integrity/failed","message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":217,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":400,"function":"isBootable","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/private/legacy/OC_App.php","line":126,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1044,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/projektid/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
{"reqId":"gYY2c9S6OXQl6EWHR1Rp","level":4,"time":"2023-06-14T16:37:42+00:00","remoteAddr":"127.0.0.1","user":"--","app":"onlyoffice","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":129,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":696,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1173,"function":"init","class":"OC","type":"::"},{"file":"/projektid/nextcloud/index.php","line":34,"args":["/projektid/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
{"reqId":"gYY2c9S6OXQl6EWHR1Rp","level":0,"time":"2023-06-14T16:37:42+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"issuetemplate","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","data":{"app":"issuetemplate"}}
{"reqId":"gYY2c9S6OXQl6EWHR1Rp","level":4,"time":"2023-06-14T16:37:42+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"onlyoffice","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":217,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":400,"function":"isBootable","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/private/legacy/OC_App.php","line":126,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1044,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/projektid/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
{"reqId":"h80AcwftOvYhddPfQUTG","level":4,"time":"2023-06-14T16:38:04+00:00","remoteAddr":"127.0.0.1","user":"--","app":"onlyoffice","method":"GET","url":"/index.php/apps/files/api/v1/stats","message":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":129,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":696,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1173,"function":"init","class":"OC","type":"::"},{"file":"/projektid/nextcloud/index.php","line":34,"args":["/projektid/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app service registration: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
{"reqId":"h80AcwftOvYhddPfQUTG","level":0,"time":"2023-06-14T16:38:04+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"issuetemplate","method":"GET","url":"/index.php/apps/files/api/v1/stats","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","data":{"app":"issuetemplate"}}
{"reqId":"h80AcwftOvYhddPfQUTG","level":4,"time":"2023-06-14T16:38:04+00:00","remoteAddr":"127.0.0.1","user":"peacecop-kalmer","app":"onlyoffice","method":"GET","url":"/index.php/apps/files/api/v1/stats","message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->"},{"function":"load","class":"OC\\Autoloader","type":"->"},{"file":"/projektid/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":217,"function":"class_exists"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":400,"function":"isBootable","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/projektid/nextcloud/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/private/legacy/OC_App.php","line":126,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/projektid/nextcloud/lib/base.php","line":1044,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/projektid/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/projektid/nextcloud/lib/autoloader.php","Line":141,"message":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php","exception":{},"CustomMessage":"Error during app loading: Autoload path not allowed: /projektid/nextcloud/apps/onlyoffice/appinfo/application.php"}}
```

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues

**Comment by piiskop** [comment]
I did. They told me to restart apache2 and closed the issue. I did restart apache2 many times with no change. I still cannot upgrade database indices.

**Comment by piiskop** [comment]
In addition, Maps does not work anymore. Everything links to the autoload path problem. And the weather app also does not work anymore but it stopped working before _27_. And the icons are still transparent on the white background.

**Comment by szaimen** [comment]
Apparently maps and weather apps are not compatible with 27 yet.

**Comment by szaimen** [comment]
> And the icons are still transparent on the white background.

This error is already reported
