### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'setIsActive') 

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#39819]
```js
vue.runtime.esm.js:3049 TypeError: Cannot read properties of null (reading 'setIsActive')
    at Tab.setIsActive (files_versions_tab.js:74:1)
    at Sidebar.vue:260:1
    at Array.forEach (<anonymous>)
    at VueComponent.setActiveTab (Sidebar.vue:259:1)
    at VueComponent.<anonymous> (Sidebar.vue:356:1)
    at Array.<anonymous> (vue.runtime.esm.js:3143:1)
    at flushCallbacks (vue.runtime.esm.js:3065:1)
```

cc @artonge 

It happens when I try to open the Sidebar and close it right after. There is a race condition where the TabInstance  is gone already

As a side note, it also break the Sidebar completely, as there is no try/catch  in the [`setIsActive` handler](https://github.com/nextcloud/server/blob/af2664cb919f097f32c3383953d902d89017feea/apps/files/src/views/Sidebar.vue#L373-L376).

**Comment by artonge** [comment]
You fixed it here: https://github.com/nextcloud/server/commit/fdf07fc759f22bcd1f26c7e4fd7f025582cc3519#diff-c19621c82f05c20e184c7e0ecef285ada69024b1e04ea3f7f45dbb6f0b027114

No ?
