### ISSUE TITLE
[Bug]: Exception during scan: File entry could not be inserted 

### ISSUE THREAD

**Issue by jacksbox** [nextcloud/server#39932]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I copied over new files into my users nextcloud dir (mounted via cifs) and wanted to add them to nextcloud via `files:scan`.
But this always results in following error (with `-v`):
```
Folder	/mario/files
File	/mario/files/test.jpg
File	/mario/files/test.jpg
Exception during scan: File entry could not be inserted but could also not be selected with getId() in order to perform an update. Please try again.
#0 /var/www/html/lib/private/Files/Cache/Scanner.php(300): OC\Files\Cache\Cache->insert('files/test.jpg', Array)
#1 /var/www/html/lib/private/Files/Cache/Scanner.php(233): OC\Files\Cache\Scanner->addToCache('files/test.jpg', Array, -1)
#2 /var/www/html/lib/private/Files/Cache/Scanner.php(457): OC\Files\Cache\Scanner->scanFile('files/test.jpg', 3, 107322, false, true, Array)
#3 /var/www/html/lib/private/Files/Cache/Scanner.php(397): OC\Files\Cache\Scanner->handleChildren('files', true, 3, 107322, true, 0)
#4 /var/www/html/lib/private/Files/Cache/Scanner.php(400): OC\Files\Cache\Scanner->scanChildren('files', true, 3, 107322, true, -1)
#5 /var/www/html/lib/private/Files/Cache/Scanner.php(347): OC\Files\Cache\Scanner->scanChildren('', true, 3, 107314, true, 725)
#6 /var/www/html/lib/private/Files/Utils/Scanner.php(269): OC\Files\Cache\Scanner->scan('', true, 3)
#7 /var/www/html/apps/files/lib/Command/Scan.php(164): OC\Files\Utils\Scanner->scan('/mario', true, NULL)
#8 /var/www/html/apps/files/lib/Command/Scan.php(219): OCA\Files\Command\Scan->scanFiles('mario', '/mario', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#9 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/console.php(100): OC\Console\Application->run()
#16 /var/www/html/occ(11): require_once('/var/www/html/c...')
#17 {main}
```
It looks like the file is there twice, because of the two lines with `File	/mario/files/test.jpg` but I double checked, the file is only there once.

In the same installation I did the same before (copy some files to the data dir and add them via `scan`) - it always worked flawlessly - till now. I checked with different files and various methods of copying over the files: `rsync`, mount the volume on my mac and copy a file in the finder directly, mounting the volume as external in another nextcloud instance... it always results on the same error when I try to add the file via `files:scan`

I checked the file permissions as well, they are correct and same as for all other files in the nextcloud data dir

### Steps to reproduce

Duno, it worked before.

### Expected behavior

`scan` adds the files to nextcloud 

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "octopus.jacksbox.de",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "octopus.jacksbox.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.0.2.1",
        "overwrite.cli.url": "https:\/\/octopus.jacksbox.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/exiftool-bin\/exiftool-aarch64-musl",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/exiftool-bin\/go-vod-aarch64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "updatedirectory": "\/nc-updater",
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": true,
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "http:\/\/nextcloud-aio-imaginary:9000",
        "memories.gis_type": 2,
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - calendar: 4.4.4
  - camerarawpreviews: 0.8.2
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.10.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - memories: 5.2.1
  - nextcloud-aio: 0.4.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recognize: 4.3.1
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
empty
```

**Comment by raftersvk** [comment]
I am nearly in the same config as jack and I have the same error :
- docker container alpine-fpm with nextcloud 27
- fresh install
- external storage

scan crashes on first file of external storage :
`sudo docker exec -it -u www-data nextcloud-app php occ files:scan --path="/djelizou/files/NAS/Photos" -vvv 
Starting scan for user 1 out of 1 (djelizou)
	Folder	/djelizou/files/NAS/Photos
	Folder	/djelizou/files/NAS/Photos/2016
	Folder	/djelizou/files/NAS/Photos/2016/2016-08
	File	/djelizou/files/NAS/Photos/2016/2016-08/2016-08-12_18.42.04.jpg
	File	/djelizou/files/NAS/Photos/2016/2016-08/2016-08-12_18.42.04.jpg
Exception during scan: File entry could not be inserted but could also not be selected with getId() in order to perform an update. Please try again.
#0 /var/www/html/lib/private/Files/Cache/Scanner.php(300): OC\Files\Cache\Cache->insert('Photos/2016/201...', Array)
#1 /var/www/html/lib/private/Files/Cache/Scanner.php(233): OC\Files\Cache\Scanner->addToCache('Photos/2016/201...', Array, -1)
#2 /var/www/html/lib/private/Files/Cache/Scanner.php(457): OC\Files\Cache\Scanner->scanFile('Photos/2016/201...', 3, 49668, false, true, Array)
#3 /var/www/html/lib/private/Files/Cache/Scanner.php(397): OC\Files\Cache\Scanner->handleChildren('Photos/2016/201...', true, 3, 49668, true, 0)
#4 /var/www/html/lib/private/Files/Cache/Scanner.php(400): OC\Files\Cache\Scanner->scanChildren('Photos/2016/201...', true, 3, 49668, true, -1)
#5 /var/www/html/lib/private/Files/Cache/Scanner.php(400): OC\Files\Cache\Scanner->scanChildren('Photos/2016', true, 3, 49634, true, -1)
#6 /var/www/html/lib/private/Files/Cache/Scanner.php(347): OC\Files\Cache\Scanner->scanChildren('Photos', true, 3, 49633, true, -1)
#7 /var/www/html/lib/private/Files/Utils/Scanner.php(269): OC\Files\Cache\Scanner->scan('Photos', true, 3)
#8 /var/www/html/apps/files/lib/Command/Scan.php(164): OC\Files\Utils\Scanner->scan('/djelizou/files...', true, NULL)
#9 /var/www/html/apps/files/lib/Command/Scan.php(219): OCA\Files\Command\Scan->scanFiles('djelizou', '/djelizou/files...', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#10 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/console.php(100): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('/var/www/html/c...')
#18 {main}

+---------+-------+--------+--------------+
| Folders | Files | Errors | Elapsed time |
+---------+-------+--------+--------------+
| 3       | 2     | 1      | 00:00:00     |
+---------+-------+--------+--------------+
`

**Comment by raftersvk** [comment]
I may have figured out something which can help : 

after deactivating the "recognize" app the scan works suddenly without any problem.
vesion of recognize : 4.3.1
particular setup : WASM mode enabled (because running on ARM)

also interesting always with the recognize app deactivated :
if I run the scan without the option "--generate-metadata" it works which we can see is doubled in the list
```
sudo docker exec -it -u www-data nextcloud-app php occ files:scan --path="/myuser/files/NAS/Photos/2020" -vvv
Starting scan for user 1 out of 1 (myuser)
	Folder	/myuser/files/NAS/Photos/2020
	Folder	/myuser/files/NAS/Photos/2020/2020_02
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-18_10.56.15.jpg
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-17_09.53.13.jpg
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-24_18.31.18.MP4
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-26_16.14.29.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-23_23.38.48.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-26_15.40.50.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-23_21.59.47.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-25_13.51.41.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/VID_20200227_170302.mp4
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-26_16.14.22.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-25_14.55.27.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-20_18.21.57.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-22_16.01.50.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-24_18.14.33.JPG
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-22_16.46.35.JPG
```

and with the option it stops on the first file : 
```
sudo docker exec -it -u www-data nextcloud-app php occ files:scan --path="/myuser/files/NAS/Photos/2020" -vvv --generate-metadata
Starting scan for user 1 out of 1 (myuser)
	Folder	/myuser/files/NAS/Photos/2020
	Folder	/myuser/files/NAS/Photos/2020/2020_02_Martinique
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-18_10.56.15.jpg
	File	/myuser/files/NAS/Photos/2020/2020_02/2020-02-18_10.56.15.jpg

+---------+-------+--------+--------------+
| Folders | Files | Errors | Elapsed time |
+---------+-------+--------+--------------+
| 2       | 2     | 0      | 00:00:01     |
+---------+-------+--------+--------------+
```
