### ISSUE TITLE
[Bug]: records in "oc_mounts" are not generated correctly / are cleared for particular users

### ISSUE THREAD

**Issue by RPJoshL** [nextcloud/server#40353]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a user shares a file or a folder between users on the same cloud, the file is not displayed to the other person. Also shares created with talk or with the "external_storage" provider are affected with this bug.

This does only apply for specific users and when the shared file / folder is not located at the users root directory. Within the "shared" file view all the shares are displayed correctly (but cannot be opened because the file could not be found).

### Steps to reproduce

1. Add `'share_folder' => '/Shared'` to the configuration file (or share a file with talk so that the file / folder is not placed at the root)
2. Share a file to another user
3. Open the `/Shared` folder
4. The folder is empty

---

After that, the `oc_mounts` table only contains a single record for the affected user:
```
| id      | storage_id | root_id | user_id        | mount_point       | mount_id | mount_provider_class
-----------------------------------------------------------------------------------------------------------------------
|       2 |          3 |    1022 | affectedUser   | /affectedUser /   |     NULL | OC\Files\Mount\LocalHomeMountProvider |
```
But the shared file is listed in  `oc_share` correctly.
```
| id  | share_type | share_with      | password | uid_owner       | uid_initiator   | parent | item_type | item_source | item_target | file_source | file_target      | permissions  | stime        | accepted | expiration          | token           | mail_send | share_name | password_by_talk | note | hide_download | label | password_expiration_time | attributes |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| 344 |          0 | affectedUser    | NULL     | admin           | admin           |   NULL | file      | 596402      | NULL        |      596402 | /Shared/file.txt |           19 |  1694203487  |        1 | 2023-11-07 00:00:00 | NULL            |         0 | NULL       |                0 | NULL |             0 | NULL  | NULL                     | NULL       |
```

In some cases _(~10% of the tries → reload the page until it works)_ the file is displayed correctly, and the required record was inserted into `oc_mounts`. But with the next reload of the page / when trying to open the file, the table is cleared again and the file won't be displayed / cannot be opened anymore.

---

The missing records for the `oc_mounts` table can be determined with the following select.

```
SELECT
  (select numeric_id FROM oc_storages ss WHERE ss.id = CONCAT('home::', s.uid_owner)),
  s.file_source,
  s.share_with,
  CONCAT('/', s.share_with, '/files', s.file_target, '/'),
  'OCA\\Files_Sharing\\MountProvider'
FROM oc_share s 
LEFT JOIN oc_mounts m 
  ON  m.root_id = s.file_source 
  AND m.user_id = s.share_with
WHERE m.id IS NULL 
  AND s.share_with = 'affectedUser';
```

### Expected behavior

The file or folder is visible within `/Shared` and can be opened.

Also, a record should be inserted into `oc_mounts`:

```
| 4557585 |          2 |  596402 | affectedUser  | /affectedUser/files/Shared/file.txt/  | OCA\Files_Sharing\MountProvider |
```

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "trusted_domains": [
            "xxx.de",
            "xxx.de"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.1.2",
        "overwrite.cli.url": "https:\/\/xxx.de",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "cookbook",
            "drawio",
            "gpxedit",
            "ocr",
            "weather",
            "files_retention",
            "emlviewer",
            "rainloop",
            "pdfdraw",
            "camerarawpreviews",
            "pdfannotate",
            "gpxmotion",
            "epubreader",
            "integration_whiteboard",
            "talk_matterbridge",
            "workflow_media_converter",
            "extract",
            "breezedark",
            "video_converter",
            "music",
            "metadata",
            "facerecognition",
            "sharerenamer"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 0,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "default_phone_region": "DE",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpauthtype": "LOGIN",
        "tempdirectory": "\/media\/nextcloudtemp",
        "enforce_theme": "breezedark",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/exiftool-amd64-glibc",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.gis_type": 1,
        "memories.vod.disable": false,
        "memories.video_default_quality": "-2"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - analytics: 4.9.4
  - bookmarks: 13.0.1
  - breezedark: 26.0.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.3
  - camerarawpreviews: 0.8.2
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - cookbook: 0.10.2
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.10.0
  - drawio: 2.1.2
  - emlviewer: 1.0.7
  - event_update_notification: 2.2.0
  - external: 5.2.0
  - extract: 1.3.6
  - facerecognition: 0.9.20
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - files_zip: 1.4.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.1
  - gpxedit: 0.0.14
  - gpxmotion: 0.1.0
  - gpxpod: 5.0.12
  - integration_giphy: 1.0.7
  - integration_openstreetmap: 1.0.6
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.3.1
  - memories: 5.2.1
  - metadata: 0.19.0
  - music: 1.8.4
  - notes: 4.8.1
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - onlyoffice: 8.1.0
  - password_policy: 1.17.0
  - pdfannotate: 0.0.10
  - phonetrack: 0.7.6
  - photos: 2.3.0
  - polls: 5.2.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recognize: 4.3.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.10.2
  - spreed: 17.0.2
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - talk_matterbridge: 1.26.0-0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather: 1.7.7
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - encryption: 2.15.0
  - epubreader: 1.4.7 (installed 1.4.7)
  - integration_whiteboard: 0.0.15 (installed 0.0.15)
  - nextcloud_announcements: 1.16.0 (installed 1.9.0)
  - ocr: 6.0.58 (installed 6.0.58)
  - rainloop: 7.2.6 (installed 7.2.6)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - video_converter: 1.0.6 (installed 1.0.6)
  - workflow_media_converter: 1.8.4 (installed 1.8.4)
  - workflow_ocr: 1.27.0 (installed 1.27.0)
```

### Nextcloud Logs

```shell
When the file was displayed within your 10% chance, opened via the "shared" panel or within Talk: 

{"reqId":"Vnm6Lz7YRPkMaQp4Uzzb","level":0,"time":"2023-09-08T20:13:45+00:00","remoteAddr":"192.168.1.15","user":"affectedUser","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/affectedUser/Sonstige%20Dateien/Apps/Talk/2022-11-27%2013-28-15.jpg","message":"File with name /Sonstige Dateien/Apps/Talk/2022-11-27 13-28-15.jpg could not be located","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0","version":"27.0.1.2","exception":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name /Sonstige Dateien/Apps/Talk/2022-11-27 13-28-15.jpg could not be located","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":78,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":971,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":364,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":172,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":227,"message":"File with name /Sonstige Dateien/Apps/Talk/2022-11-27 13-28-15.jpg could not be located","exception":{},"CustomMessage":"File with name /Sonstige Dateien/Apps/Talk/2022-11-27 13-28-15.jpg could not be located"}}
```

**Comment by RPJoshL** [comment]
> Did this immediately appear after the initial upgrade to NC27?
> 
>     1. Any other recurring (or simply potentially interesting) warnings or errors appearing in your NC logs?
> 
>     2. You have a lot of force installed apps (`app_install_overwrite`), at least some of which aren't compatible with NC27. For example, `epubreader` hasn't been updated for >NC23 from the looks of it. Please audit the listed apps under that config directive for compatibility and disable any incompatible ones. One of them may be causing problems.

Yes, the problem occurred directly after upgrading to Version *27.0.1*. But because we stayed on NC 26 only for a few days before upgrading to 27 *(and didn't test / used it much)*  I can not say for sure if the issue was introduced in Version *26* or *27*.

1. The log file doesn't contain any error or warning
2. After disabling almost all apps (only a few "featured" apps like the sharing app were still enabled) the issue was still present

---

While debugging the issue I was able to examine the following behavior:

* When I refresh the site with the affected user there are two endpoints called that are trying to update the `mounts` table:
  1. The first request adds the records correctly within [this line](https://github.com/nextcloud/server/blob/97dd09c4348ebbd88089cf572ac18e6cdf341493/lib/private/Files/Config/UserMountCache.php#L137) and doesn't remove or update any record
  2. But the second request only receives the default two mount points of the root directory [here](https://github.com/nextcloud/server/blob/97dd09c4348ebbd88089cf572ac18e6cdf341493/lib/private/Files/SetupManager.php#L288) and therefore removes the previously added mounts of the 1. Request within [this line](https://github.com/nextcloud/server/blob/97dd09c4348ebbd88089cf572ac18e6cdf341493/lib/private/Files/Config/UserMountCache.php#L142)
* The issue can be solved by uncomment [the entry point](https://github.com/nextcloud/server/blob/97dd09c4348ebbd88089cf572ac18e6cdf341493/lib/private/Cache/File.php#L56) for the second request so that the records won't be removed anymore

Call stack of the **1.** Request.
```
{"reqId":"QhoX1DKgQipoq49XoRMk","level":3,"time":"2023-09-11T17:59:25+00:00","remoteAddr":"192.168.1.15","user":"affectedUser","app":"no app in context","method":"GET","url":"/apps/recommendations/api/recommendations","message":"xxxx" }
#0 /var/www/nextcloud/lib/private/Files/SetupManager.php(306): OC\\Files\\Config\\UserMountCache->registerMounts()
#1 /var/www/nextcloud/lib/private/Files/SetupManager.php(230): OC\\Files\\SetupManager->afterUserFullySetup()
#2 /var/www/nextcloud/lib/private/Files/SetupManager.php(406): OC\\Files\\SetupManager->setupForUser()
#3 /var/www/nextcloud/lib/private/Files/Mount/Manager.php(128): OC\\Files\\SetupManager->setupForPath()
#4 /var/www/nextcloud/lib/private/Files/Node/Root.php(166): OC\\Files\\Mount\\Manager->findIn()
#5 /var/www/nextcloud/lib/private/Files/Cache/QuerySearchHelper.php(242): OC\\Files\Node\\Root->getMountsIn()
#6 /var/www/nextcloud/lib/private/Files/Node/Folder.php(234): OC\\Files\\Cache\\QuerySearchHelper->getCachesAndMountPointsForSearch()
#7 /var/www/nextcloud/lib/private/Files/Node/Folder.php(457): OC\\Files\\Node\\Folder->search()
#8 [internal function]: OC\\Files\\Node\\Folder->getRecent()
#9 /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php(74): call_user_func_array()
#10 /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php(516): OC\\Files\\Node\\LazyFolder->__call()
#11 /var/www/nextcloud/apps/recommendations/lib/Service/RecentlyEditedFilesSource.php(68): OC\\Files\\Node\\LazyFolder->getRecent()
#12 /var/www/nextcloud/apps/recommendations/lib/Service/RecommendationService.php(88): OCA\\Recommendations\\Service\\RecentlyEditedFilesSource->getMostRecentRecommendation()
#13 [internal function]: OCA\\Recommendations\\Service\\RecommendationService->OCA\\Recommendations\\Service\\{closure}()
#14 /var/www/nextcloud/apps/recommendations/lib/Service/RecommendationService.php(89): array_reduce()
#15 /var/www/nextcloud/apps/recommendations/lib/Controller/RecommendationController.php(64): OCA\\Recommendations\\Service\\RecommendationService->getRecommendations()
#16 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\Recommendations\\Controller\\RecommendationController->index()
#17 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController()
#18 /var/www/nextcloud/lib/private/AppFramework/App.php(183): OC\\AppFramework\\Http\\Dispatcher->dispatch()
#19 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main()
#20 /var/www/nextcloud/lib/base.php(1071): OC\\Route\\Router->match()
#21 /var/www/nextcloud/index.php(36): OC::handleRequest()
#22 {main}
```

Call stack of the **2.** Request.

```
{"reqId":"kGAyTAGFClAsGpTWsuRi","level":3,"time":"2023-09-11T17:59:26+00:00","remoteAddr":"192.168.0.27","user":"affectedUser","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v1/notifications?format=json","message":"" }
#0 /var/www/nextcloud/lib/private/Files/SetupManager.php(306): OC\\Files\\Config\\UserMountCache->registerMounts()
#1 /var/www/nextcloud/lib/private/Files/SetupManager.php(230): OC\\Files\\SetupManager->afterUserFullySetup()
#2 /var/www/nextcloud/lib/private/Files/Filesystem.php(361): OC\\Files\\SetupManager->setupForUser()
#3 /var/www/nextcloud/lib/private/Cache/File.php(56): OC\\Files\\Filesystem::initMountPoints()
#4 /var/www/nextcloud/lib/private/Cache/File.php(177): OC\\Cache\\File->getStorage()
#5 /var/www/nextcloud/lib/base.php(881): OC\\Cache\\File->gc()
#6 [internal function]: OC::{closure}()
#7 /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php(105): call_user_func_array()
#8 /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php(40): OC\\Hooks\\BasicEmitter->emit()
#9 /var/www/nextcloud/lib/private/User/Session.php(401): OC\\Hooks\\PublicEmitter->emit()
#10 /var/www/nextcloud/lib/private/User/Session.php(662): OC\\User\\Session->completeLogin()
#11 /var/www/nextcloud/lib/private/User/Session.php(353): OC\\User\\Session->loginWithToken()
#12 /var/www/nextcloud/lib/private/User/Session.php(452): OC\\User\\Session->login()
#13 /var/www/nextcloud/lib/private/User/Session.php(580): OC\\User\\Session->logClientIn()
#14 /var/www/nextcloud/lib/base.php(1150): OC\\User\\Session->tryBasicAuthLogin()
#15 /var/www/nextcloud/ocs/v1.php(61): OC::handleLogin()
#16 /var/www/nextcloud/ocs/v2.php(23): require_once('...')
#17 {main}","userAgent":"curl/7.81.0","version":"27.0.1.2","data":[]
```

So I'm not really sure why the second request receives the incorrect mount points or even tries to update them. This endpoint was also called while the notification app was disabled.

**Comment by RPJoshL** [comment]
Edit: the endpoint `/ocs/v2.php/apps/notifications/api/v1/notifications` is called from a custom shell script that periodically checks every *10 seconds* if there are new notifications available for the user. Because only he is using that script the other users were unaffected.

When the script is stopped everything works as expected and the shared files and folders are appearing in the /Shared folder. These are the exact steps to reproduce the issue:

1. Add 'share_folder' => '/Shared' to the configuration file (or share a file with talk so that the file / folder is not placed at the root)
2. Share a file to another user
3. Open the /Shared folder
4. The folder contains the shared items
5. Call an endpoint of the *OCS API*: 
```
curl -s --user "affectedUser":"xxxxx-xxxxx-xxxxx-xxxxx-xxxxx" https://yourDomain.com/ocs/v2.php/apps/notifications/api/v1/notifications
```
6. Refresh the /Shared folder
7. The folder is empty

---

Because it appears that the handling of mounts is different for the [OCS API](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html), the incorrect mount points are cached for the time of `fs_mount_cache_duration` also for the "normal" endpoints and results in the describe issue.

**Comment by joshtrichards** [comment]
Cc: @nickvergessen, @icewind1991

**Comment by xinstein** [comment]
This bug also affects the Memories app, heavily

**Comment by xinstein** [comment]
Does anyone know a workaround for this issue?

**Comment by RPJoshL** [comment]
The issue is still present in version *30.0.2*
