### ISSUE TITLE
[Bug]: SQLSTATE[42000] Error while installing 

### ISSUE THREAD

**Issue by agharbeia** [nextcloud/server#40441]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

NextCloud 27,0,2,1 Build 2023-08-08T08:23:54+00:00 9234ae4a0a98ee924cd63974e88c22c3bb3f6b21

MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04

PHP 8.1.2-1ubuntu2.14

While attempting to make a clean installation, I get a breaking error:
```
Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1142 CREATE command denied to user 'nextcloud_user'@'localhost' for table `Nextcloud_DB`.`oc_migrations`
```

The full trace is available.

I have tried both the web installer and the via oc.

I'm able to connect with the database user credentials via the MariaDB CLI via TCP at localhost:3306 using the named database.

and the MariaDB user has the following privileges:

```
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, TRIGGER ON `Nextcloud_DB`.`*` TO `nextcloud_user`@`%`
```

### Steps to reproduce

1. create database and user
1. In the installer, specify credentials of the DB user, DB name, credentials of NC admin, and data path
1. fail with error described above

### Expected behavior

Successful installation of NextCloud

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

```
Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or acces
s violation: 1142 CREATE command denied to user 'nextcloud_wolke'@'localhost' for table `Nextcloud_Wolke`.`oc_migrations`           
Trace: #0 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert
()                                                                                                                                  
#1 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException()                
#2 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery()
#3 /srv/nextcloud/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery()
#4 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1843): OC\DB\Connection->executeQuery()
#5 /srv/nextcloud/lib/private/DB/Migrator.php(162): Doctrine\DBAL\Connection->query()
#6 /srv/nextcloud/lib/private/DB/Migrator.php(68): OC\DB\Migrator->applySchema()
#7 /srv/nextcloud/lib/private/DB/Connection.php(589): OC\DB\Migrator->migrate()
#8 /srv/nextcloud/lib/private/DB/MigrationService.php(169): OC\DB\Connection->migrateToSchema()
#9 /srv/nextcloud/lib/private/DB/MigrationService.php(183): OC\DB\MigrationService->createMigrationTable()
#10 /srv/nextcloud/lib/private/DB/MigrationService.php(256): OC\DB\MigrationService->getMigratedVersions()
#11 /srv/nextcloud/lib/private/DB/MigrationService.php(434): OC\DB\MigrationService->getMigrationsToExecute()
#12 /srv/nextcloud/lib/private/DB/MigrationService.php(409): OC\DB\MigrationService->migrateSchemaOnly()
#13 /srv/nextcloud/lib/private/Setup/AbstractDatabase.php(158): OC\DB\MigrationService->migrate()
#14 /srv/nextcloud/lib/private/Setup.php(371): OC\Setup\AbstractDatabase->runMigrations()
#15 /srv/nextcloud/core/Command/Maintenance/Install.php(104): OC\Setup->install()
#16 /srv/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Maintenance\Install->execute()
#17 /srv/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#18 /srv/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#19 /srv/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#20 /srv/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#21 /srv/nextcloud/console.php(100): OC\Console\Application->run() 
#22 /srv/nextcloud/occ(11): require_once('...')
#23 {main}

Previous: Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42000]: Syntax error or access violation: 1142 CREATE command denied to user 
'nextcloud_wolke'@'localhost' for table `Nextcloud_Wolke`.`oc_migrations`
Trace: #0 /srv/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php(77): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1050): Doctrine\DBAL\Driver\PDO\Connection->query()
#2 /srv/nextcloud/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery()
#3 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1843): OC\DB\Connection->executeQuery()
#4 /srv/nextcloud/lib/private/DB/Migrator.php(162): Doctrine\DBAL\Connection->query()
#5 /srv/nextcloud/lib/private/DB/Migrator.php(68): OC\DB\Migrator->applySchema()
#6 /srv/nextcloud/lib/private/DB/Connection.php(589): OC\DB\Migrator->migrate()
#7 /srv/nextcloud/lib/private/DB/MigrationService.php(169): OC\DB\Connection->migrateToSchema()
#8 /srv/nextcloud/lib/private/DB/MigrationService.php(183): OC\DB\MigrationService->createMigrationTable()
#9 /srv/nextcloud/lib/private/DB/MigrationService.php(256): OC\DB\MigrationService->getMigratedVersions()
#10 /srv/nextcloud/lib/private/DB/MigrationService.php(434): OC\DB\MigrationService->getMigrationsToExecute()
#11 /srv/nextcloud/lib/private/DB/MigrationService.php(409): OC\DB\MigrationService->migrateSchemaOnly()
#12 /srv/nextcloud/lib/private/Setup/AbstractDatabase.php(158): OC\DB\MigrationService->migrate()
#13 /srv/nextcloud/lib/private/Setup.php(371): OC\Setup\AbstractDatabase->runMigrations()
#14 /srv/nextcloud/core/Command/Maintenance/Install.php(104): OC\Setup->install()
#15 /srv/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Maintenance\Install->execute()
#16 /srv/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#17 /srv/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#18 /srv/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#19 /srv/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#20 /srv/nextcloud/console.php(100): OC\Console\Application->run() 
#21 /srv/nextcloud/occ(11): require_once('...')
#22 {main}
Previous: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1142 CREATE command denied to user 'nextcloud_w[75/28631]
alhost' for table `Nextcloud_Wolke`.`oc_migrations`
Trace: #0 /srv/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php(72): PDO->query()
#1 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1050): Doctrine\DBAL\Driver\PDO\Connection->query()
#2 /srv/nextcloud/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery()
#3 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1843): OC\DB\Connection->executeQuery()
#4 /srv/nextcloud/lib/private/DB/Migrator.php(162): Doctrine\DBAL\Connection->query()
#5 /srv/nextcloud/lib/private/DB/Migrator.php(68): OC\DB\Migrator->applySchema()
#6 /srv/nextcloud/lib/private/DB/Connection.php(589): OC\DB\Migrator->migrate()
#7 /srv/nextcloud/lib/private/DB/MigrationService.php(169): OC\DB\Connection->migrateToSchema()
#8 /srv/nextcloud/lib/private/DB/MigrationService.php(183): OC\DB\MigrationService->createMigrationTable()
#9 /srv/nextcloud/lib/private/DB/MigrationService.php(256): OC\DB\MigrationService->getMigratedVersions()
#10 /srv/nextcloud/lib/private/DB/MigrationService.php(434): OC\DB\MigrationService->getMigrationsToExecute()
#11 /srv/nextcloud/lib/private/DB/MigrationService.php(409): OC\DB\MigrationService->migrateSchemaOnly()
#12 /srv/nextcloud/lib/private/Setup/AbstractDatabase.php(158): OC\DB\MigrationService->migrate()
#13 /srv/nextcloud/lib/private/Setup.php(371): OC\Setup\AbstractDatabase->runMigrations()
#14 /srv/nextcloud/core/Command/Maintenance/Install.php(104): OC\Setup->install()
#15 /srv/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Maintenance\Install->execute()
#16 /srv/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#17 /srv/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#18 /srv/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#19 /srv/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#20 /srv/nextcloud/console.php(100): OC\Console\Application->run() 
#21 /srv/nextcloud/occ(11): require_once('...')
#22 {main}
```

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, TRIGGER ON `Nextcloud_DB`.`*` TO `nextcloud_user`@`%`

In the past, it was common to have multiple users in mysql with different hosts. You granted the permissions to nextcloud_user@%, but the error shows nextcloud_user@localhost. 

Are you sure the actual user has the right permissions?

As this seems to be a setup issue, I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by agharbeia** [comment]
Actually, the mistake is in the composition of the ticket.

I had tried both @'%' and @'localhost' as well as combinations thereof.

Anyhow, I ended up adding "WITH GRANT OPTION" to the GRANT statement, and that seemed to solve it.
I still do not understand why, though.
