### ISSUE TITLE
[Bug]: when updating to 25.0.11, archive validation against 26.0.5 is attempted and fails Verifying integrity

### ISSUE THREAD

**Issue by JDrewes** [nextcloud/server#40491]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When starting an update from 25.0.10 to 25.0.11 via web frontend, update fails with "X Verifying integrity".
Inspection of logs seems to suggest that while 25.0.11 was downloaded (nextcloud-25.0.11.zip exists in the updater's download folder and passes manual md5 check), the updater is now expecting to validate against nextcloud-26.0.5.zip, even though I never okayed this upgrade!

I have included the parts of the update log I believe to be relevant.

Please note installation location is in China.

### Steps to reproduce

1. start update from 25.0.10 to 25.0.11
2.
3.

### Expected behavior

system installs update.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
2023-09-18T15:36:17+0800 CKSJaVOLcB [info] getChangelogURL()
2023-09-18T15:36:17+0800 CKSJaVOLcB [info] end of checkForUpdate() Update to Nextcloud 25.0.11 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-25.0.11.zip</code><br /><a class="external_link" href="https://nextcloud.com/changelog/#25-0-11" target="_blank" rel="noreferrer noopener">Open changelog ↗</a>
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] request to updater
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] currentStep()
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] POST request for step "1"
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] startStep("1")
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] checkForExpectedFilesAndFolders()
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] end of checkForExpectedFilesAndFolders()
2023-09-18T15:36:19+0800 H4A5HmhtUu [info] endStep("1")
2023-09-18T15:36:19+0800 VJZAfY3flC [info] request to updater
2023-09-18T15:36:19+0800 VJZAfY3flC [info] currentStep()
2023-09-18T15:36:19+0800 VJZAfY3flC [info] Step 1 is in state "end".
2023-09-18T15:36:19+0800 VJZAfY3flC [info] POST request for step "2"
2023-09-18T15:36:19+0800 VJZAfY3flC [info] startStep("2")
2023-09-18T15:36:19+0800 VJZAfY3flC [info] checkWritePermissions()
2023-09-18T15:36:19+0800 VJZAfY3flC [info] end of checkWritePermissions()
2023-09-18T15:36:19+0800 VJZAfY3flC [info] endStep("2")
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] request to updater
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] currentStep()
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] Step 2 is in state "end".
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] POST request for step "3"
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] startStep("3")
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] createBackup()
2023-09-18T15:36:19+0800 8alPJ3R1Eo [info] backup folder location: /FAST/nextcloud-data/updater-ocrjxvpdzo8r/backups/nextcloud-25.0.10.1-1695022579/
2023-09-18T15:36:28+0800 8alPJ3R1Eo [info] end of createBackup()
2023-09-18T15:36:28+0800 8alPJ3R1Eo [info] endStep("3")
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] request to updater
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] currentStep()
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] Step 3 is in state "end".
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] POST request for step "4"
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] startStep("4")
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] downloadUpdate()
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] getUpdateServerResponse()
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] updaterServer: https://updates.nextcloud.com/updater_server/
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] releaseChannel: stable
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] internal version: 25.0.10.1
2023-09-18T15:36:28+0800 xHQ1nBpHFQ [info] updateURL: https://updates.nextcloud.com/updater_server/?version=25x0x10x1xxxstablexx2023-08-10T06%3A13%3A02%2B00%3A00+8ec206d4c5e802eeb2ba50aa255a92fcb6cde8e0x8x1x2
2023-09-18T15:36:31+0800 xHQ1nBpHFQ [info] getUpdateServerResponse response: Array
(
    [version] => 25.0.11.1
    [versionstring] => Nextcloud 25.0.11
    [url] => https://download.nextcloud.com/server/releases/nextcloud-25.0.11.zip
    [web] => https://docs.nextcloud.com/server/25/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=25.0.11
    [autoupdater] => 1
    [eol] => 0
    [signature] => TBlsiR2Mdlr6yUfDlZ/BldTUt6gkmX20h+RAeO0ZfJ5D+LKzAMLk30By1uysEKg2
AI2j3VBeSdOKYa+16cXWRkHJMRnD1RGTUAePljufhZkmpWsKPpHdcQK5zSZo/KQH
25ZgJpw5Eg/x6fYHmMveDduQ06YdRq2XHcEE1/N629yAuXoHx5pKvC3iwQa7jW67
gj4DYSqwd+QerrjSToqjHQcDBfNCnlDCuv11yvP0j9lGWrehaf7qt0lmBylh+a/1
I6P6M4pVva8ZT7Bzk/7jEOqXB9+k9AVUU1EBLuibqnWpEjG4ID/TqfLj0WCz1w8N
qcrQf/nGMi2GhACpG4PdQw==
)

2023-09-18T15:36:31+0800 xHQ1nBpHFQ [info] storage location exists
2023-09-18T22:09:29+0800 xHQ1nBpHFQ [info] end of downloadUpdate()
2023-09-18T22:09:29+0800 xHQ1nBpHFQ [info] endStep("4")
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] request to updater
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] currentStep()
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] Step 4 is in state "end".
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] POST request for step "5"
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] startStep("5")
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] verifyIntegrity()
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] getUpdateServerResponse()
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] updaterServer: https://updates.nextcloud.com/updater_server/
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] releaseChannel: stable
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] internal version: 25.0.10.1
2023-09-18T22:09:29+0800 J0VgyuGa0P [info] updateURL: https://updates.nextcloud.com/updater_server/?version=25x0x10x1xxxstablexx2023-08-10T06%3A13%3A02%2B00%3A00+8ec206d4c5e802eeb2ba50aa255a92fcb6cde8e0x8x1x2
2023-09-18T22:09:31+0800 J0VgyuGa0P [info] getUpdateServerResponse response: Array
(
    [version] => 26.0.5.1
    [versionstring] => Nextcloud 26.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-26.0.5.zip
    [web] => https://docs.nextcloud.com/server/26/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=26.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => vcbiEky4dRZwpiIWIVqsr7V3+UU4bfd87qgTqLQ1VVqTDU2L1yif6HUFOOpPxdvq
coRKXOJbr8zXjx1xiWz2+nR9mZqiLC4ZoThg5iF6OcaREP5tpV1VL8qvzWWQWTq/
5DRhxiTgVVNgm6Z0c3uLXZwVQRfbPWGXQig4g7o8bQlTZZ2YBzSUmgvr0wyY7c4/
2JVzUbkEBkVhdiM/3bGLzWrVTf4DinKGWOR2WlEPdA7v1qAYqboLV01EYu1Yem+7
xYCUVaWkCxkcwSiDLbzJVt8dczehINEtLjtkvYYYRjDlTtcVTmtJ7peuiApewrDq
K4yLF72MBGtOenDw2QoY4Q==
)

2023-09-18T22:09:31+0800 J0VgyuGa0P [info] storage location: /FAST/nextcloud-data/updater-ocrjxvpdzo8r/downloads/
2023-09-18T22:09:32+0800 J0VgyuGa0P [error] POST request failed with other exception
2023-09-18T22:09:32+0800 J0VgyuGa0P [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /var/www/html/nextcloud/updater/index.php(1376): Updater->verifyIntegrity()
#1 {main}
File:/var/www/html/nextcloud/updater/index.php
Line:688

2023-09-18T22:09:32+0800 J0VgyuGa0P [info] rollbackChanges("5")
2023-09-18T22:09:32+0800 J0VgyuGa0P [info] unlink .step
2023-09-18T22:09:32+0800 J0VgyuGa0P [info] end of  rollbackChanges()
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] request to updater
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] currentStep()
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] POST request for step "5"
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] startStep("5")
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] verifyIntegrity()
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] getUpdateServerResponse()
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] updaterServer: https://updates.nextcloud.com/updater_server/
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] releaseChannel: stable
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] internal version: 25.0.10.1
2023-09-19T11:21:23+0800 Xy9ddI0dSz [info] updateURL: https://updates.nextcloud.com/updater_server/?version=25x0x10x1xxxstablexx2023-08-10T06%3A13%3A02%2B00%3A00+8ec206d4c5e802eeb2ba50aa255a92fcb6cde8e0x8x1x2
2023-09-19T11:21:25+0800 Xy9ddI0dSz [info] getUpdateServerResponse response: Array
(
    [version] => 26.0.5.1
    [versionstring] => Nextcloud 26.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-26.0.5.zip
    [web] => https://docs.nextcloud.com/server/26/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=26.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => vcbiEky4dRZwpiIWIVqsr7V3+UU4bfd87qgTqLQ1VVqTDU2L1yif6HUFOOpPxdvq
coRKXOJbr8zXjx1xiWz2+nR9mZqiLC4ZoThg5iF6OcaREP5tpV1VL8qvzWWQWTq/
5DRhxiTgVVNgm6Z0c3uLXZwVQRfbPWGXQig4g7o8bQlTZZ2YBzSUmgvr0wyY7c4/
2JVzUbkEBkVhdiM/3bGLzWrVTf4DinKGWOR2WlEPdA7v1qAYqboLV01EYu1Yem+7
xYCUVaWkCxkcwSiDLbzJVt8dczehINEtLjtkvYYYRjDlTtcVTmtJ7peuiApewrDq
K4yLF72MBGtOenDw2QoY4Q==
)

2023-09-19T11:21:25+0800 Xy9ddI0dSz [info] storage location: /FAST/nextcloud-data/updater-ocrjxvpdzo8r/downloads/
2023-09-19T11:21:25+0800 Xy9ddI0dSz [error] POST request failed with other exception
2023-09-19T11:21:25+0800 Xy9ddI0dSz [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /var/www/html/nextcloud/updater/index.php(1376): Updater->verifyIntegrity()
#1 {main}
File:/var/www/html/nextcloud/updater/index.php
Line:688

2023-09-19T11:21:25+0800 Xy9ddI0dSz [info] rollbackChanges("5")
2023-09-19T11:21:25+0800 Xy9ddI0dSz [info] unlink .step
2023-09-19T11:21:25+0800 Xy9ddI0dSz [info] end of  rollbackChanges()
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] request to updater
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] currentStep()
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] POST request for step "5"
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] startStep("5")
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] verifyIntegrity()
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] getUpdateServerResponse()
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] updaterServer: https://updates.nextcloud.com/updater_server/
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] releaseChannel: stable
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] internal version: 25.0.10.1
2023-09-19T11:21:31+0800 tT7dTEi2XN [info] updateURL: https://updates.nextcloud.com/updater_server/?version=25x0x10x1xxxstablexx2023-08-10T06%3A13%3A02%2B00%3A00+8ec206d4c5e802eeb2ba50aa255a92fcb6cde8e0x8x1x2
2023-09-19T11:21:32+0800 tT7dTEi2XN [info] getUpdateServerResponse response: Array
(
    [version] => 26.0.5.1
    [versionstring] => Nextcloud 26.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-26.0.5.zip
    [web] => https://docs.nextcloud.com/server/26/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=26.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => vcbiEky4dRZwpiIWIVqsr7V3+UU4bfd87qgTqLQ1VVqTDU2L1yif6HUFOOpPxdvq
coRKXOJbr8zXjx1xiWz2+nR9mZqiLC4ZoThg5iF6OcaREP5tpV1VL8qvzWWQWTq/
5DRhxiTgVVNgm6Z0c3uLXZwVQRfbPWGXQig4g7o8bQlTZZ2YBzSUmgvr0wyY7c4/
2JVzUbkEBkVhdiM/3bGLzWrVTf4DinKGWOR2WlEPdA7v1qAYqboLV01EYu1Yem+7
xYCUVaWkCxkcwSiDLbzJVt8dczehINEtLjtkvYYYRjDlTtcVTmtJ7peuiApewrDq
K4yLF72MBGtOenDw2QoY4Q==
)

2023-09-19T11:21:32+0800 tT7dTEi2XN [info] storage location: /FAST/nextcloud-data/updater-ocrjxvpdzo8r/downloads/
2023-09-19T11:21:32+0800 tT7dTEi2XN [error] POST request failed with other exception
2023-09-19T11:21:32+0800 tT7dTEi2XN [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /var/www/html/nextcloud/updater/index.php(1376): Updater->verifyIntegrity()
#1 {main}
File:/var/www/html/nextcloud/updater/index.php
Line:688

2023-09-19T11:21:32+0800 tT7dTEi2XN [info] rollbackChanges("5")
2023-09-19T11:21:32+0800 tT7dTEi2XN [info] unlink .step
2023-09-19T11:21:32+0800 tT7dTEi2XN [info] end of  rollbackChanges()
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] request to updater
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] currentStep()
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] POST request for step "5"
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] startStep("5")
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] verifyIntegrity()
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] getUpdateServerResponse()
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] updaterServer: https://updates.nextcloud.com/updater_server/
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] releaseChannel: stable
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] internal version: 25.0.10.1
2023-09-19T11:26:53+0800 ppnTLxAfjR [info] updateURL: https://updates.nextcloud.com/updater_server/?version=25x0x10x1xxxstablexx2023-08-10T06%3A13%3A02%2B00%3A00+8ec206d4c5e802eeb2ba50aa255a92fcb6cde8e0x8x1x2
2023-09-19T11:26:54+0800 ppnTLxAfjR [info] getUpdateServerResponse response: Array
(
    [version] => 26.0.5.1
    [versionstring] => Nextcloud 26.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-26.0.5.zip
    [web] => https://docs.nextcloud.com/server/26/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=26.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => vcbiEky4dRZwpiIWIVqsr7V3+UU4bfd87qgTqLQ1VVqTDU2L1yif6HUFOOpPxdvq
coRKXOJbr8zXjx1xiWz2+nR9mZqiLC4ZoThg5iF6OcaREP5tpV1VL8qvzWWQWTq/
5DRhxiTgVVNgm6Z0c3uLXZwVQRfbPWGXQig4g7o8bQlTZZ2YBzSUmgvr0wyY7c4/
2JVzUbkEBkVhdiM/3bGLzWrVTf4DinKGWOR2WlEPdA7v1qAYqboLV01EYu1Yem+7
xYCUVaWkCxkcwSiDLbzJVt8dczehINEtLjtkvYYYRjDlTtcVTmtJ7peuiApewrDq
K4yLF72MBGtOenDw2QoY4Q==
)

2023-09-19T11:26:54+0800 ppnTLxAfjR [info] storage location: /FAST/nextcloud-data/updater-ocrjxvpdzo8r/downloads/
2023-09-19T11:26:54+0800 ppnTLxAfjR [error] POST request failed with other exception
2023-09-19T11:26:54+0800 ppnTLxAfjR [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /var/www/html/nextcloud/updater/index.php(1376): Updater->verifyIntegrity()
#1 {main}
File:/var/www/html/nextcloud/updater/index.php
Line:688

2023-09-19T11:26:54+0800 ppnTLxAfjR [info] rollbackChanges("5")
2023-09-19T11:26:54+0800 ppnTLxAfjR [info] unlink .step
2023-09-19T11:26:54+0800 ppnTLxAfjR [info] end of  rollbackChanges()
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] request to updater
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] currentStep()
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] POST request for step "5"
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] startStep("5")
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] verifyIntegrity()
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] getUpdateServerResponse()
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] updaterServer: https://updates.nextcloud.com/updater_server/
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] releaseChannel: stable
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] internal version: 25.0.10.1
2023-09-19T11:32:54+0800 CbRZKvgpq5 [info] updateURL: https://updates.nextcloud.com/updater_server/?version=25x0x10x1xxxstablexx2023-08-10T06%3A13%3A02%2B00%3A00+8ec206d4c5e802eeb2ba50aa255a92fcb6cde8e0x8x1x2
2023-09-19T11:32:55+0800 CbRZKvgpq5 [info] getUpdateServerResponse response: Array
(
    [version] => 26.0.5.1
    [versionstring] => Nextcloud 26.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-26.0.5.zip
    [web] => https://docs.nextcloud.com/server/26/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=26.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => vcbiEky4dRZwpiIWIVqsr7V3+UU4bfd87qgTqLQ1VVqTDU2L1yif6HUFOOpPxdvq
coRKXOJbr8zXjx1xiWz2+nR9mZqiLC4ZoThg5iF6OcaREP5tpV1VL8qvzWWQWTq/
5DRhxiTgVVNgm6Z0c3uLXZwVQRfbPWGXQig4g7o8bQlTZZ2YBzSUmgvr0wyY7c4/
2JVzUbkEBkVhdiM/3bGLzWrVTf4DinKGWOR2WlEPdA7v1qAYqboLV01EYu1Yem+7
xYCUVaWkCxkcwSiDLbzJVt8dczehINEtLjtkvYYYRjDlTtcVTmtJ7peuiApewrDq
K4yLF72MBGtOenDw2QoY4Q==
)

2023-09-19T11:32:55+0800 CbRZKvgpq5 [info] storage location: /FAST/nextcloud-data/updater-ocrjxvpdzo8r/downloads/
2023-09-19T11:32:55+0800 CbRZKvgpq5 [error] POST request failed with other exception
2023-09-19T11:32:55+0800 CbRZKvgpq5 [error] Exception: Exception
Message: Signature of update is not valid
Code:0
Trace:
#0 /var/www/html/nextcloud/updater/index.php(1376): Updater->verifyIntegrity()
#1 {main}
File:/var/www/html/nextcloud/updater/index.php
Line:688

2023-09-19T11:32:55+0800 CbRZKvgpq5 [info] rollbackChanges("5")
2023-09-19T11:32:55+0800 CbRZKvgpq5 [info] unlink .step
2023-09-19T11:32:55+0800 CbRZKvgpq5 [info] end of  rollbackChanges()
```

**Comment by joshtrichards** [comment]
Speculation: Your update may have gotten hung up on the temporary removal of v25.0.11 from the update server in #40456. 

Kind of looks like your system downloaded it then ~7 hours later tried to do the integrity check. Might have been the time window when the release happened to disappear in-between.

Did it rollback alright?
