### ISSUE TITLE
Upgrade from OC 8.2.10 to NC 9.0.57 failed to enable three apps

### ISSUE THREAD

**Issue by Tronde** [nextcloud/server#4080]
### Steps to reproduce
1. Enable Maintenance Mode with the command line tool: `sudo -u bob php occ maintenance:mode --on`
2. Stop nginx webserver
3. Backup existing configuration and database
4. Remove the directory with the ownCloud code (data is kept in a seperate directory)
5. Download NC 9.0.57 and extract it to the location where the old owncloud code was
6. Copy back the configuration file `config.php` from the ownCloud backup to `nextcloud/config/config.php`
7. Start the upgrade process with the command line tool: `sudo -u bob php occ upgrade`

### Expected behaviour
* No errors during update
* Update successful

### Actual behaviour
Failed to enable several apps:
```
2017-03-26T16:53:57+00:00 notifications: Failed to enable app notifications
2017-03-26T16:53:57+00:00 federation: Failed to enable app federation
2017-03-26T16:53:57+00:00 dav: Failed to enable app dav
```

### Server configuration
**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** nginx 1.10.0

**Database:** mysql-server 5.7.17

**PHP version:** php7.0-fpm 7.0.17

**Nextcloud version:** (see Nextcloud admin page)
9.0.57.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes, I updated from ownCloud 8.2.10.2.

**Where did you install Nextcloud from:**
I downloaded and used the archive from: https://download.nextcloud.com/server/releases/nextcloud-9.0.57.tar.bz2

**Signing status:**
$ sha256sum --check nextcloud-9.0.57.tar.bz2.sha256
nextcloud-9.0.57.tar.bz2: OK

Login as admin not possible anymore. I rolled back to ownCloud 8.2.10, already.

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocf3842ed74c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.my-it-brain.de",
            "oc.my-it-brain.de",
            "oc.my-it-brain.de"
        ],
        "datadirectory": "\/var\/www\/tronde\/sites\/oc.my-it-brain.de\/data",
        "dbtype": "mysql",
        "version": "8.2.10.2",
        "dbname": "tronde_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "my-it-brain.de",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mx.my-it-brain.de",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "3",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox 52.0.1 (64-bit)

**Operating system:** Ubuntu 16.04.2 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/03/26 18:12:43 [error] 7476#7476: *3986 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <IP-ADDRESS>, server: oc.my-it-brain.de, request: "POST / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9200", host: "oc.my-it-brain.de
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.10.2 to 9.0.57.2","level":0,"time":"2017-03-26T16:53:41+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"core","message":"No update found at the Nextcloud appstore for app 166054","level":0,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"notifications","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app notifications\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('notifications')\\n#1 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(340): OC_Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(214): OC\\\\Updater->doUpgrade('9.0.57.2', '8.2.10.2')\\n#3 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/upgrade.php(248): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/base.php(159): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/console\\\/application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/console.php(97): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/occ(11): require_once('\\\/var\\\/www\\\/tronde...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php\",\"Line\":594}","level":3,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"federation","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app federation\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('federation')\\n#1 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(340): OC_Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(214): OC\\\\Updater->doUpgrade('9.0.57.2', '8.2.10.2')\\n#3 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/upgrade.php(248): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/base.php(159): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/console\\\/application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/console.php(97): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/occ(11): require_once('\\\/var\\\/www\\\/tronde...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php\",\"Line\":594}","level":3,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"dav","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app dav\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#1 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(340): OC_Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(214): OC\\\\Updater->doUpgrade('9.0.57.2', '8.2.10.2')\\n#3 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/upgrade.php(248): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/base.php(159): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/console\\\/application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/console.php(97): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/occ(11): require_once('\\\/var\\\/www\\\/tronde...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php\",\"Line\":594}","level":3,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
```
</details>

I had to restore ownCloud 8.2.10. But I could reproduce the issue. So if you need more info I could run the whole process again.

**Comment by MorrisJobke** [comment]
Weird - this code is usually called when the app is installed the first time and it then sees that the tables already exist:

https://github.com/nextcloud/server/blob/32bf8ec826dadbfd342627884fbdf83081db9b29/lib/private/Installer.php#L481-L485

@nickvergessen @rullzer @icewind1991 Any idea why this upgrade from 8.2 to 9.0 doesn't work and the apps seem to be already installed?

@Tronde Which apps do you have installed? Could you also give us the entries in oc_appconfig? Thanks

**Comment by Tronde** [comment]
@MorrisJobke Here comes the list of my installed apps:
```
Enabled:
  - activity: 2.1.4
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - files: 1.2.1
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - ownnote: 1.07
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_external
  - notifications
  - provisioning_api
  - user_external
  - user_ldap
```

I have posted the entries of the table oc_appconfig to this [Gist](https://gist.github.com/Tronde/04b7f87e207a9ed021eb50d4213b86fc).

**Comment by nickvergessen** [comment]
Sounds like you already tried to update before and then simply restored a backup, is it possible?
This created the new database tables already, while the config has no record of the apps (because you restored your backup).
Therefor when you try to re-install the apps now, the database tables they want to create already exist => error. try to manually delete the tables which the apps want to create and it should work.

Please also use the search to find more information, this has been discussed a lot of times already.

**Comment by Tronde** [comment]
@nickvergessen You are right. I restored the installation from backup after an earlier attempt to update to OC 9.0.8 failed. I ran your [app-state-detection](https://gist.github.com/nickvergessen/94b57082a5ab83e47bbbd1bef6d13f66) script today which found the following errors:
```
1491848767 [Error] Table addressbooks of app dav exists although the app is not installed
1491848767 [Error] Table cards of app dav exists although the app is not installed
1491848767 [Error] Table addressbookchanges of app dav exists although the app is not installed
1491848767 [Error] Table calendarobjects of app dav exists although the app is not installed
1491848767 [Error] Table calendars of app dav exists although the app is not installed
1491848767 [Error] Table calendarchanges of app dav exists although the app is not installed
1491848767 [Error] Table calendarsubscriptions of app dav exists although the app is not installed
1491848767 [Error] Table schedulingobjects of app dav exists although the app is not installed
1491848767 [Error] Table cards_properties of app dav exists although the app is not installed
1491848767 [Error] Table dav_shares of app dav exists although the app is not installed
1491848767 [Error] Table trusted_servers of app federation exists although the app is not installed
1491848767 [Error] Table notifications of app notifications exists although the app is not installed
1491848767 [Error] Table addressbook of app contacts does not exists
1491848767 [Error] Table addressbook_backend of app contacts does not exists
```

I'm going to delete these tables and run the update again. I come back and post my results here for documentation.

**Comment by Tronde** [comment]
Dropping the tables from the results in [my previous comment](https://github.com/nextcloud/server/issues/4080#issuecomment-293040944) resolves the issue. After that the upgrade was finished successful.
