### ISSUE TITLE
Upgrade from OC 8.2.10 to NC 9.0.57 failed - existing local user could not log in except the admin user

### ISSUE THREAD

**Issue by Tronde** [nextcloud/server#4081]
### Steps to reproduce
1. Enable Maintenance Mode with the command line tool: `sudo -u bob php occ maintenance:mode --on`
2. Stop nginx webserver
3. Backup existing configuration and database
4. Remove the directory with the ownCloud code (data is kept in a seperate directory)
5. Download NC 9.0.57 and extract it to the location where the old owncloud code was
6. Copy back the configuration file `config.php` from the ownCloud backup to `nextcloud/config/config.php`
7. Start the upgrade process with the command line tool: `sudo -u bob php occ upgrade`

### Expected behaviour
* No errors during update
* Update successful
* Admin and existing local users could login

### Actual behaviour
Failed to enable several apps:
```
[...]
2017-03-26T16:53:57+00:00 notifications: Failed to enable app notifications
2017-03-26T16:53:57+00:00 federation: Failed to enable app federation
2017-03-26T16:53:57+00:00 dav: Failed to enable app dav
[...]
2017-03-26T16:53:58+00:00 Starting code integrity check...
2017-03-26T16:54:00+00:00 Finished code integrity check
2017-03-26T16:54:00+00:00 Update successful
2017-03-26T16:54:00+00:00 Maintenance mode is kept active
2017-03-26T16:54:00+00:00 Reset log level
```

Existing local users could not login. After some time the server returns the error "504 Gateway timed out"

### Server configuration
**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** nginx 1.10.0

**Database:** mysql-server 5.7.17

**PHP version:** php7.0-fpm 7.0.17

**Nextcloud version:** (see Nextcloud admin page)
9.0.57.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes, I updated from ownCloud 8.2.10.2.

**Where did you install Nextcloud from:**
I downloaded and used the archive from: https://download.nextcloud.com/server/releases/nextcloud-9.0.57.tar.bz2

**Signing status:**
$ sha256sum --check nextcloud-9.0.57.tar.bz2.sha256
nextcloud-9.0.57.tar.bz2: OK

Login as admin not possible anymore. I rolled back to ownCloud 8.2.10, already.

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocf3842ed74c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.my-it-brain.de",
            "oc.my-it-brain.de",
            "oc.my-it-brain.de"
        ],
        "datadirectory": "\/var\/www\/tronde\/sites\/oc.my-it-brain.de\/data",
        "dbtype": "mysql",
        "version": "8.2.10.2",
        "dbname": "tronde_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "my-it-brain.de",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mx.my-it-brain.de",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "3",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox 52.0.1 (64-bit)

**Operating system:** Ubuntu 16.04.2 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/03/26 18:12:43 [error] 7476#7476: *3986 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <IP-ADDRESS>, server: oc.my-it-brain.de, request: "POST / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9200", host: "oc.my-it-brain.de
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.10.2 to 9.0.57.2","level":0,"time":"2017-03-26T16:53:41+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"core","message":"No update found at the Nextcloud appstore for app 166054","level":0,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"notifications","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app notifications\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('notifications')\\n#1 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(340): OC_Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(214): OC\\\\Updater->doUpgrade('9.0.57.2', '8.2.10.2')\\n#3 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/upgrade.php(248): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/base.php(159): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/console\\\/application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/console.php(97): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/occ(11): require_once('\\\/var\\\/www\\\/tronde...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php\",\"Line\":594}","level":3,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"federation","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app federation\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('federation')\\n#1 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(340): OC_Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(214): OC\\\\Updater->doUpgrade('9.0.57.2', '8.2.10.2')\\n#3 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/upgrade.php(248): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/base.php(159): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/console\\\/application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/console.php(97): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/occ(11): require_once('\\\/var\\\/www\\\/tronde...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php\",\"Line\":594}","level":3,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
{"reqId":"3HWM5Djq9uE6N0t83GcX","remoteAddr":"","app":"dav","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app dav\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#1 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(340): OC_Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/updater.php(214): OC\\\\Updater->doUpgrade('9.0.57.2', '8.2.10.2')\\n#3 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/upgrade.php(248): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/core\\\/command\\\/base.php(159): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/console\\\/application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/console.php(97): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/occ(11): require_once('\\\/var\\\/www\\\/tronde...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/tronde\\\/sites\\\/oc.my-it-brain.de\\\/public\\\/lib\\\/private\\\/installer.php\",\"Line\":594}","level":3,"time":"2017-03-26T16:53:57+00:00","method":"--","url":"--","user":"--","version":"8.2.10.2"}
```
</details>

#### nginx configuration
<details>
<summary>nginx configuration</summary>
```
upstream php-handler {
    server 127.0.0.1:9200;
}
server {
	listen 80;
	listen [::]:80;
	server_name host.example.com;
	return 301 https://$server_name$request_uri; # enforce https
}
server {
    # Listen on Port 443
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name host.example.com; 
    ssl_certificate /var/www/bob/sites/host.example.com/ssl/host.example.com_chained.crt;
ssl_certificate_key /var/www/bob/sites/host.example.com/ssl/host.example.com.key;

ssl_ciphers 'my ciphers here';

ssl_prefer_server_ciphers on;
ssl_dhparam /etc/nginx/dh_params.pem;

# Add headers to serve security related headers
  	add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
  	add_header X-Content-Type-Options nosniff;
  	add_header X-Frame-Options "SAMEORIGIN";
  	add_header X-XSS-Protection "1; mode=block";
  	add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    # Path to the root of your installation
    root /var/www/bob/sites/$host/public;
    # Path to the logfiles
access_log /var/www/bob/sites/logs/host.example.com_access.log combined;
error_log /var/www/bob/sites/logs/host.example.com_error.log error;
    # Standardconfiguration from owncloud.org following
    # set max upload size
    client_max_body_size 10G;
    fastcgi_buffers 64 4K;
    # Disable gzip to avoid the removal of the ETag header
  	gzip off;
    rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
    rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
    rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;
    index index.php;
    error_page 403 /core/templates/403.php;
    error_page 404 /core/templates/404.php;
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location ~ ^/(data|config|\.ht|db_structure\.xml|README) {
        deny all;
    }
    location / {
        # The following 2 rules are only needed with webfinger
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
        rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
        rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
        try_files $uri $uri/ index.php;
    }
    location ~ ^(.+?\.php)(/.*)?$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
		fastcgi_param modHeadersAvailable true;
        fastcgi_pass php-handler;
    }
    # Optional: set long EXPIRES header on static assets
    location ~* ^.+\.(jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
        expires 30d;
        # Optional: Don't log access to assets
         access_log off;
    }
}
```
</details>

I had to restore ownCloud 8.2.10. But I could reproduce the issue. So if you need more info I could run the whole process again.

**Comment by Tronde** [comment]
This issue happend during the same upgrade attempt as #4080.

**Comment by Tronde** [comment]
Because I'm not sure if this is a bug in nextcloud, an issue with the documentation, the nginx and php-fpm configuration or simply an layer 8 problem of my own, I've opened a [thread in the forum](https://help.nextcloud.com/t/users-cannot-login-via-webinterface-after-upgrade-from-owncloud-8-2-10-to-nextcloud-9-0-57/11306).

Hopefully someone could get me back on track here or there. I could not find the cause of trouble by myself and have to restore the previous version otherwise.

**Comment by Tronde** [comment]
@josh4trunks I was told that you are the contributor of the nginx config files. Could you help me out here?

**Comment by josh4trunks** [comment]
the nginx configuration from OC8 to OC/NC9 changed significantly because of the way URLs were now handled.
specifically the PHP location

did you check your nginx config against the documentation for NC9?

**Comment by Tronde** [comment]
Yes, I checked against the documentation of NC9. You could find the detailed description and nginx configuration in [this topic](https://help.nextcloud.com/t/users-cannot-login-via-webinterface-after-upgrade-from-owncloud-8-2-10-to-nextcloud-9-0-57/11306?u=tronde).

Maybe there is still something wrong, but I couldn't figure it out.

**Comment by josh4trunks** [comment]
I see your css/js block is missing `try_files $uri /nextcloud/index.php$uri$is_args$args;`
I don't remember if that was critical.

some other things your could try...

* Maybe you can try setting 'front_controller_active' to false and see if that gets you in?

* Also, could you use unix sockets for PHP, or is TCP your only option? that might get rid of timeout issues and possibly isolate where the issue is.

**Comment by Tronde** [comment]
I've added the missing block at the end of my configuration file:
```
    location ~* ^.+\.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
        try_files $uri /index.php$uri$is_args$args;
        # Optional: Don't log access to assets
         access_log off;
    }
```

I've set 'front_controller_active' to false and configured php-fpm to use a unix socket. Restarted php-fpm and nginx and tested again with the same result. Still getting '504 Gateway Time-out'. The nginx log shows:
```
2017/04/17 21:01:17 [error] 2995#2995: *157 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: nc.my-it-brain.de, request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php7-fpm-.socket", host: "nc.my-it-brain.de"
```

**Comment by josh4trunks** [comment]
According to your post you already had that block. Why are you adding it again?
https://help.nextcloud.com/t/users-cannot-login-via-webinterface-after-upgrade-from-owncloud-8-2-10-to-nextcloud-9-0-57/11306?u=tronde

That isn't the block I was talking about. Please add this line
`try_files $uri /nextcloud/index.php$uri$is_args$args;`
in this block
`location ~* \.(?:css|js)$ {`

**Comment by Tronde** [comment]
Ah sorry, I messed up there. I've checked to have no double location blocks and added the line
`try_files $uri /nextcloud/index.php$uri$is_args$args;` to the mentioned block. But I still got the 504 error.

Why does it have to be `/nextcloud/index.php$uri$is_args$args;` anyway? The `nextcloud` directory was already specified in the root directive. So it is the webroot and there is no nextcloud dir in it. But I tried the line `/index.php$uri$is_args$args;` as well with same result.

I just discovered that when I enter a false password I got instantly the message "Wrong password. Reset it?". Only when entering the correct password I run in the 504 after some time.

**Comment by josh4trunks** [comment]
whoops, that should be /index.php$uri$is_args$args as you said you tried.

if i remember, the reason that is need is so certain javascript files are server properly.
can you try setting the front_controller to true again.

I vaguely remember getting this same issue a while ago with a nextcloud update. I remember the same login issue and having to wait for a point release to fix it. not sure if this is the same version you are trying.

**Comment by josh4trunks** [comment]
probably not the same version since 9.0.57 is fairly new. this happened to me with 10.x I think.

**Comment by Tronde** [comment]
So, what are my options? Should I do a full restore and try again with the next point release? Or should I proceed with the migration path and upgrade to 11.x using the `occ upgrade` command hoping the issue so not exist there?

**Comment by josh4trunks** [comment]
If you are able to backup your database and config, I see no issue in trying to use 'occ upgrade' to try going to the latest version.

Another you could try is hosting your NC instance with apache to verify if this is an issue with your nginx configuration, or something in the NC code.

**Comment by Tronde** [comment]
Ok. At first I try to take it to NC11. I will come back here to give an update when I'm finished.

**Comment by Tronde** [comment]
Hi,

So, after a lot of backups and upgrades I'm now at version 11.0.2. And I'm able to login, again.

While the webinterface for the users seems broken in some areas and the whole application is running awefully slow this issue is solved. For the other issues I'm experiencing I will look into the other issues here on github. Thanks a lot for your help @josh4trunks.

# Summary
To get from ownCloud 8.2.x to Nextcloud 11.0.2 I did the following:

1. [Backing up ownCloud](https://doc.owncloud.org/server/8.2/admin_manual/maintenance/backup.html)
2. Upgrade to NC 9.0.57 following the [Migration Guide](https://nextcloud.com/migration/)
3. Repeat the steps until the upgrade to NC 11.0.2 finished successfully
4. Finally set maintenance mode off an log in

Thanks again,
Tronde

**Comment by josh4trunks** [comment]
@Tronde gald it is working.

I do remember that the Nextcloud 11 WebUI was noticeably slow when i first upgraded. and if you examine the connection it is downloading hundreds of small files. once these are cached it shouldn't be as bad, also hosting with HTTP2 should makes things better.
