### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException updating oc_filecache table with PostgreSQL

### ISSUE THREAD

**Issue by marcobrt** [nextcloud/server#4095]
Internal Server Error while uploading a file on SMB/CIFS external storage with PostgreSQL:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime"=? WHERE ("mtime" <> ? OR "mtime" IS NULL) AND "fileid" = ? ' with params ["1467279529.796", "1467279529.796", 361]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1467279529.796"
```

### Steps to reproduce
1. Open an SMB/CIFS External storage folder
2. Upload a file

### Expected behaviour
File is uploaded without errors and is shown in the folder.

### Actual behaviour
File is uploaded but an Internal Server Error occurs and is reported in the Nextcloud's interface header. The file is not shown in the folder but if the folder is refreshed (closed and reopened) then the file is shown. A fatal error is reported in Nextcloud's log.

### Server configuration
**Operating system**: CentOS Linux release 7.3.1611 (Core)

**Web server:** Apache 2.4.6

**Database:** postgres (PostgreSQL) 9.2.18

**PHP version:** PHP 7.0.16

**Nextcloud version:** Nextcloud 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://nextcloud.com/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_pdfviewer
  - files_retention
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - sharebymail
  - systemtags
  - templateeditor
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oczbyykilc6u",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.1"
        ],
        "datadirectory": "\/data\/nextcloud\/",
        "overwrite.cli.url": "http:\/\/192.168.1.1\/nextcloud",
        "dbtype": "pgsql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "amministratore",
        "mail_domain": "xxxxxxxx.it",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.xxxxxx.xxxx",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "OC_User_SMB",
                "arguments": [
                    "server.xxxxxxx.xxxxx"
                ]
            }
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** SMB/CIFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** SMB via External user support App

### Client configuration
**Browser:** Chrome 57.0.2987.110 (64-bit)

**Operating system:** Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors reported on apache error log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WNkUx8@TvrB7IpzUPW@frQAAAAE","remoteAddr":"192.168.1.201","app":"webdav","message":"Exception: {\"Message\":\"An excepti
on occurred while executing 'UPDATE \\\"oc_filecache\\\" SET \\\"mtime\\\"=? WHERE (\\\"mtime\\\" <> ? OR \\\"mtime\\\" IS NULL) A
ND \\\"fileid\\\" = ? ' with params [\\\"1467279529.796\\\", \\\"1467279529.796\\\", 363]:\\n\\nSQLSTATE[22P02]: Invalid text repr
esentation: 7 ERRORE: sintassi di input non valida per il tipo integer: \\\"1467279529.796\\\"\",\"Exception\":\"Doctrine\\\\DBAL
\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\
/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exceptio
n oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/
lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\D
BAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE \\\"oc_file...', Array)\\n#2 \\\
/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(194): Doctrine\\\\DBAL\\\\Connection->executeQuery('UPDATE \\\"
oc_file...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(322): OC\\\\DB\
\\\Connection->executeQuery('UPDATE \\\"oc_file...', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\
\/Wrapper\\\/CacheWrapper.php(138): OC\\\\Files\\\\Cache\\\\Cache->update(363, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/p
rivate\\\/Files\\\/Cache\\\/Wrapper\\\/CacheWrapper.php(138): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheWrapper->update(363, Array)\
\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheWrapper.php(111): OC\\\\Files\\\\Cache\\\\
Wrapper\\\\CacheWrapper->update(363, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1533): OC\\\\F
iles\\\\Cache\\\\Wrapper\\\\CacheWrapper->put('201606300808.pd...', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/F
iles\\\/View.php(567): OC\\\\Files\\\\View->putFileInfo('\\\/sala\\\/files\\\/amm...', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/
apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(209): OC\\\\Files\\\\View->touch('\\\/ammcont\\\/201606...', '1467279529.796'
)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\
Sabre\\\\File->put(Resource id #434)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(107
2): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('201606300808.pd...', Resource id #434)\\n#12 \\\/var\\\/www\\\/next
cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('ammcont\\\/2016063...'
, Resource id #434, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(
Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105):
call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479):
 Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\
/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var
\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/n
extcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91,\"User
\":\"sala\"}","level":4,"time":"2017-03-27T13:33:59+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/ammcont\/2016063
00808.pdf","user":"sala","version":"11.0.2.7"}

```
</details>

**Comment by icewind1991** [comment]
@marcobrt can you get a stacktrace of that error?

**Comment by marcobrt** [comment]
You mean this?
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime"=? WHERE ("mtime" <> ? OR "mtime" IS NULL) AND "fileid" = ? ' with params ["1467279529.796", "1467279529.796", 361]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1467279529.796"

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 836: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE "oc_file...', Array)
    /var/www/nextcloud/lib/private/DB/Connection.php - line 194: Doctrine\DBAL\Connection->executeQuery('UPDATE "oc_file...', Array, Array, NULL)
    /var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 322: OC\DB\Connection->executeQuery('UPDATE "oc_file...', Array)
    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 138: OC\Files\Cache\Cache->update(361, Array)
    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 138: OC\Files\Cache\Wrapper\CacheWrapper->update(361, Array)
    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 111: OC\Files\Cache\Wrapper\CacheWrapper->update(361, Array)
    /var/www/nextcloud/lib/private/Files/View.php - line 1533: OC\Files\Cache\Wrapper\CacheWrapper->put('201606300808.pd...', Array)
    /var/www/nextcloud/lib/private/Files/View.php - line 567: OC\Files\View->putFileInfo('/sala/files/amm...', Array)
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 209: OC\Files\View->touch('/ammcont/201606...', '1467279529.796')
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 137: OCA\DAV\Connector\Sabre\File->put(Resource id #434)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1072: OCA\DAV\Connector\Sabre\Directory->createFile('201606300808.pd...', Resource id #434)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('ammcont/2016063...', Resource id #434, NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}
```
Otherwise please guide me on how to obtain a stacktrace.

**Comment by icewind1991** [comment]
Yes, that will help

**Comment by icewind1991** [comment]
Fix is here: https://github.com/nextcloud/server/pull/4096

**Comment by marcobrt** [comment]
Tested. It seems to work correctly now. Files are uploaded without errors.
