### ISSUE TITLE
Recurrent webdav fatal error

### ISSUE THREAD

**Issue by youhost** [nextcloud/server#4113]
I have a continuous error in https://drive.youhost.cloud/index.php/settings/admin/logging
Error is app: webdav, level: fatal and is logged every 30 minutes

### Steps to reproduce
I don't know how to reproduce.
I tried to cancel and reimport all calendars but error did not disapeared.
The calendar is syncing properly thru devices (osx calendar + ios calendar)

### Expected behaviour
Not having conituous fatal error :)

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
CentOs7
**Web server:**
Apache cPanel
**Database:**
MariaDB 10.1
**PHP version:**
ea-php71 + PHP-FPM
**Server version:** (see your admin page)
 11.0.2 (stable)
**Calendar version:** (see the apps page)
1.5.2
**Updated from an older installed version or fresh install:**
Just updated Calendar, but error was there before.
Started with NextCloud 11
**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - apporder: 0.3.3
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_downloadactivity: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ownpad: 0.5.7
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - sharebymail: 1.0.1
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocojjet8ryds",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "drive.youhost.cloud"
        ],
        "datadirectory": "\/home\/drivecloud\/_NEXTdata",
        "overwrite.cli.url": "https:\/\/drive.youhost.cloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "drivecloud_nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "enable_avatars": true,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "loglevel": 1,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "youhost.eu",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "in-v3.mailjet.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox 52.0.1 (64 bit)
**Operating system:**
OS X 10.11.4 (15E65)
**CalDAV-clients:**
Calendar 8.0 (2092.3)
#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
{"reqId":"WKJOKMDEjzsWVGkYn8ZFawAAAAo","remoteAddr":"2.235.171.241","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_youhost\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'drivecloud_next'@'localhost' for table 'user'","level":3,"time":"2017-02-14T00:24:08+00:00","method":"POST","url":"\/index.php","user":"--","version":"11.0.0.10"}
{"reqId":"WKJOKMDEjzsWVGkYn8ZFawAAAAo","remoteAddr":"2.235.171.241","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given object name is invalid\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/drivecloud\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(892): OC\\\\Activity\\\\Event->setObject('files', 2, false)\\n#1 \\\/home\\\/drivecloud\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(184): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('youhost', 'created_self', Array, 2, false, true, true, 0, 'file_created')\\n#2 \\\/home\\\/drivecloud\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(111): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/', 'file_created', 'created_self', 'created_by')\\n#3 \\\/home\\\/drivecloud\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/View.php(1237): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/View.php(1163): OC\\\\Files\\\\View->runHooks(Array, '\\\/youhost\\\/files', true)\\n#8 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/View.php(266): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/youhost\\\/files', Array)\\n#9 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(149): OC\\\\Files\\\\View->mkdir('\\\/youhost\\\/files')\\n#10 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(380): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/youhost\\\/files')\\n#11 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('youhost')\\n#12 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#13 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#14 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Server.php(948): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('youhost')\\n#15 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\Server->getUserFolder('youhost')\\n#16 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/User\\\/Session.php(479): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#17 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/User\\\/Session.php(299): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#18 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Setup.php(393): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#19 \\\/home\\\/drivecloud\\\/public_html\\\/core\\\/Controller\\\/SetupController.php(65): OC\\\\Setup->install(Array)\\n#20 \\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/base.php(957): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#21 \\\/home\\\/drivecloud\\\/public_html\\\/index.php(40): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/home\\\/drivecloud\\\/public_html\\\/lib\\\/private\\\/Activity\\\/Event.php\",\"Line\":401}","level":3,"time":"2017-02-14T00:24:26+00:00","method":"POST","url":"\/index.php","user":"youhost","version":"11.0.0.10"}
```

**Comment by MorrisJobke** [comment]
It seems that your DB rights have been changed: `SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'drivecloud_next'@'localhost' for table 'user'` Please double check that the DB user has rights to do this.

```sql
SELECT user FROM mysql.user WHERE user=?
```

**Comment by youhost** [comment]
Hello, thank you for your advice, but there is no table user in my nextcloud db, but only oc_users.
Also I've check the permissions and drivecloud_next have all permissions granted.
Am I missing user table in my db?

**Comment by MorrisJobke** [comment]
This is a mysql table not an Nextcloud table. What this SQL does is it checks the mysql users for a user with the specified name being present.

**Comment by youhost** [comment]
Hello, and thank you, unfortunately I am not a NC expert so I thought about the NC db.
I've checked the query, it seems to me that the DB user has permission to run the query you suggested to me.
Here is the output:
``````
[root@d02 ~]# mysql -udrivecloud_next -p drivecloud_nextcloud
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 438087
Server version: 10.1.22-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [drivecloud_nextcloud]> SELECT user FROM mysql.user WHERE user=?
    -> 
    -> 
````
Thank you

**Comment by MorrisJobke** [comment]
Ah - this is just a log line that comes from the install and is fine.

The other error is the actual problem and activity related. cc @nickvergessen 

```json

{
	"Exception":"InvalidArgumentException",
	"Message":"The given object name is invalid",
	"Code":0,
	"Trace":"
		#0 apps/activity/lib/FilesHooks.php(892): OC\\Activity\\Event->setObject('files', 2, false)
		#1 apps/activity/lib/FilesHooks.php(184): OCA\\Activity\\FilesHooks->addNotificationsForUser('youhost', 'created_self', Array, 2, false, true, true, 0, 'file_created')
		#2 apps/activity/lib/FilesHooks.php(111): OCA\\Activity\\FilesHooks->addNotificationsForFileAction('/', 'file_created', 'created_self', 'created_by')
		#3 apps/activity/lib/FilesHooksStatic.php(45): OCA\\Activity\\FilesHooks->fileCreate('/')
		#4 [internal function]: OCA\\Activity\\FilesHooksStatic::fileCreate(Array)
		#5 lib/private/legacy/hook.php(106): call_user_func(Array, Array)
		#6 lib/private/Files/View.php(1237): OC_Hook::emit('OC_Filesystem', 'post_create', Array)
		#7 lib/private/Files/View.php(1163): OC\\Files\\View->runHooks(Array, '/youhost/files', true)
		#8 lib/private/Files/View.php(266): OC\\Files\\View->basicOperation('mkdir', '/youhost/files', Array)
		#9 lib/private/Files/Node/Folder.php(149): OC\\Files\\View->mkdir('/youhost/files')
		#10 lib/private/Files/Node/Root.php(380): OC\\Files\\Node\\Folder->newFolder('/youhost/files')
		#11 [internal function]: OC\\Files\\Node\\Root->getUserFolder('youhost')
		#12 lib/private/Files/Node/LazyRoot.php(65): call_user_func_array(Array, Array)
		#13 lib/private/Files/Node/LazyRoot.php(282): OC\\Files\\Node\\LazyRoot->__call('getUserFolder', Array)
		#14 lib/private/Server.php(948): OC\\Files\\Node\\LazyRoot->getUserFolder('youhost')
		#15 lib/private/User/Session.php(411): OC\\Server->getUserFolder('youhost')
		#16 lib/private/User/Session.php(479): OC\\User\\Session->prepareUserLogin(true)
		#17 lib/private/User/Session.php(299): OC\\User\\Session->loginWithPassword(*** sensitive parameters replaced ***)
		#18 lib/private/Setup.php(393): OC\\User\\Session->login(*** sensitive parameters replaced ***)
		#19 core/Controller/SetupController.php(65): OC\\Setup->install(Array)
		#20 lib/base.php(957): OC\\Core\\Controller\\SetupController->run(Array)
		#21 index.php(40): OC::handleRequest()
		#22 {main}
	",
	"File":"lib/private/Activity/Event.php",
	"Line":401,
	"level":3,
	"time":"2017-02-14T00:24:26+00:00",
	"method":"POST",
	"url":"/index.php",
	"user":"youhost",
	"version":"11.0.0.10"
}
```

**Comment by youhost** [comment]
Thank you but I am unable to understand the error.
Please let me know if I can do some test or debug.

**Comment by nickvergessen** [comment]
This was already fixed with https://github.com/nextcloud/activity/pull/117 for Nextcloud 12 and https://github.com/nextcloud/activity/pull/118 for Nextcloud 11.0.3

**Comment by youhost** [comment]
Thank you, last question, I've seen NC 11.0.3 is not available.
Can I safely replace this file on my NC instance to check if this fix the error?
https://github.com/nextcloud/activity/pull/118/files
