### ISSUE TITLE
[Bug]: deleting file fails with `423: Locked`

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/server#42306]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

An attachment test is failing in the `text` app CI for a while now. Similar failures happen in the groupfolders CI.

When trying to delete a file that was created by the same test the server responds with:
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"deleteMe.md" is locked</s:message>
</d:error>
```

### Steps to reproduce

```js
	before(() => {
		cy.createUser(user)
	})

	it('deletes file just fine', () => {
		cy.login(user)
		const fileName = 'deleteMe.md'
		cy.createFile(fileName, '# Hello world!', 'text/markdown')
		cy.visit('/apps/files')
		cy.getFile(fileName)
			.should('exist')
		cy.deleteFile(fileName)  // this fails as reported above.
		cy.reloadFileList()
	})
```

`deleteFile` triggers a `DELETE` on `http://localhost:8081/remote.php/webdav/deleteMe.md`.

### Expected behavior

Delete works fine.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - lookup_server_connector: 1.16.0
  - oauth2: 1.16.3
  - provisioning_api: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - testing: 1.18.0
  - user_ldap: 1.19.0
```

### Nextcloud Logs

```shell
{
  "reqId": "NAIfRhXUWkENynwMPe92",
  "level": 3,
  "time": "2023-12-13T21:56:50+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "nkdpiq",
  "app": "webdav",
  "method": "DELETE",
  "url": "/remote.php/webdav/deleteSource.md",
  "message": "\"deleteSource.md\" is locked",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/13.6.1 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36",
  "version": "29.0.0.2",
  "exception": {
    "Exception": "OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked",
    "Message": "\"deleteSource.md\" is locked",
    "Code": 0,
    "Trace": [
      {
        "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 185,
        "function": "delete",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 281,
        "function": "delete",
        "class": "Sabre\\DAV\\Tree",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpDelete",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php",
        "line": 88,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/home/runner/work/text/text/remote.php",
        "line": 172,
        "args": [
          "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/home/runner/work/text/text/apps/dav/lib/Connector/Sabre/File.php",
    "Line": 552,
    "Previous": {
      "Exception": "OCP\\Lock\\LockedException",
      "Message": "\"deleteSource.md\" is locked",
      "Code": 0,
      "Trace": [
        {
          "file": "/home/runner/work/text/text/lib/private/Files/View.php",
          "line": 1150,
          "function": "changeLock",
          "class": "OC\\Files\\View",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/lib/private/Files/View.php",
          "line": 702,
          "function": "basicOperation",
          "class": "OC\\Files\\View",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/apps/dav/lib/Connector/Sabre/File.php",
          "line": 543,
          "function": "unlink",
          "class": "OC\\Files\\View",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Tree.php",
          "line": 185,
          "function": "delete",
          "class": "OCA\\DAV\\Connector\\Sabre\\File",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
          "line": 281,
          "function": "delete",
          "class": "Sabre\\DAV\\Tree",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
          "line": 89,
          "function": "httpDelete",
          "class": "Sabre\\DAV\\CorePlugin",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 472,
          "function": "emit",
          "class": "Sabre\\DAV\\Server",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 253,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 321,
          "function": "start",
          "class": "Sabre\\DAV\\Server",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php",
          "line": 88,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->"
        },
        {
          "file": "/home/runner/work/text/text/remote.php",
          "line": 172,
          "args": [
            "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/home/runner/work/text/text/lib/private/Files/View.php",
      "Line": 1984,
      "Previous": {
        "Exception": "OCP\\Lock\\LockedException",
        "Message": "\"files/0e2cb9c4e844fb3a76adacb4fea9b781\"(\"files/deleteSource.md\") is locked",
        "Code": 0,
        "Trace": [
          {
            "file": "/home/runner/work/text/text/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line": 629,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Common",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line": 629,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/lib/private/Files/View.php",
            "line": 1978,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/lib/private/Files/View.php",
            "line": 1150,
            "function": "changeLock",
            "class": "OC\\Files\\View",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/lib/private/Files/View.php",
            "line": 702,
            "function": "basicOperation",
            "class": "OC\\Files\\View",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/apps/dav/lib/Connector/Sabre/File.php",
            "line": 543,
            "function": "unlink",
            "class": "OC\\Files\\View",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Tree.php",
            "line": 185,
            "function": "delete",
            "class": "OCA\\DAV\\Connector\\Sabre\\File",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
            "line": 281,
            "function": "delete",
            "class": "Sabre\\DAV\\Tree",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line": 89,
            "function": "httpDelete",
            "class": "Sabre\\DAV\\CorePlugin",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 472,
            "function": "emit",
            "class": "Sabre\\DAV\\Server",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 253,
            "function": "invokeMethod",
            "class": "Sabre\\DAV\\Server",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 321,
            "function": "start",
            "class": "Sabre\\DAV\\Server",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php",
            "line": 88,
            "function": "exec",
            "class": "Sabre\\DAV\\Server",
            "type": "->"
          },
          {
            "file": "/home/runner/work/text/text/remote.php",
            "line": 172,
            "args": [
              "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "/home/runner/work/text/text/lib/private/Files/Storage/Common.php",
        "Line": 833,
        "Previous": {
          "Exception": "OCP\\Lock\\LockedException",
          "Message": "\"files/0e2cb9c4e844fb3a76adacb4fea9b781\" is locked",
          "Code": 0,
          "Trace": [
            {
              "file": "/home/runner/work/text/text/lib/private/Files/Storage/Common.php",
              "line": 831,
              "function": "changeLock",
              "class": "OC\\Lock\\DBLockingProvider",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/lib/private/Files/Storage/Wrapper/Wrapper.php",
              "line": 629,
              "function": "changeLock",
              "class": "OC\\Files\\Storage\\Common",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/lib/private/Files/Storage/Wrapper/Wrapper.php",
              "line": 629,
              "function": "changeLock",
              "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/lib/private/Files/View.php",
              "line": 1978,
              "function": "changeLock",
              "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/lib/private/Files/View.php",
              "line": 1150,
              "function": "changeLock",
              "class": "OC\\Files\\View",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/lib/private/Files/View.php",
              "line": 702,
              "function": "basicOperation",
              "class": "OC\\Files\\View",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/apps/dav/lib/Connector/Sabre/File.php",
              "line": 543,
              "function": "unlink",
              "class": "OC\\Files\\View",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Tree.php",
              "line": 185,
              "function": "delete",
              "class": "OCA\\DAV\\Connector\\Sabre\\File",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
              "line": 281,
              "function": "delete",
              "class": "Sabre\\DAV\\Tree",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
              "line": 89,
              "function": "httpDelete",
              "class": "Sabre\\DAV\\CorePlugin",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
              "line": 472,
              "function": "emit",
              "class": "Sabre\\DAV\\Server",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
              "line": 253,
              "function": "invokeMethod",
              "class": "Sabre\\DAV\\Server",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/3rdparty/sabre/dav/lib/DAV/Server.php",
              "line": 321,
              "function": "start",
              "class": "Sabre\\DAV\\Server",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php",
              "line": 88,
              "function": "exec",
              "class": "Sabre\\DAV\\Server",
              "type": "->"
            },
            {
              "file": "/home/runner/work/text/text/remote.php",
              "line": 172,
              "args": [
                "/home/runner/work/text/text/apps/dav/appinfo/v1/webdav.php"
              ],
              "function": "require_once"
            }
          ],
          "File": "/home/runner/work/text/text/lib/private/Lock/DBLockingProvider.php",
          "Line": 214
        }
      }
    },
    "message": "\"deleteSource.md\" is locked",
    "exception": {},
    "CustomMessage": "\"deleteSource.md\" is locked"
  }
}
```

### Additional info

The logs were optained by making the `FileLocked` error fatal:
https://github.com/nextcloud/server/pull/42253/files

**Comment by max-nextcloud** [comment]
I find it interesting that the innermost exception complains about the entire storage being locked:
```
          "Message": "\"files/0e2cb9c4e844fb3a76adacb4fea9b781\" is locked",
```

**Comment by max-nextcloud** [comment]
Bisecting the issue pointed me to #41010 - which is odd as it only contains frontend changes.

Never the less 0/12 runs fail when using 1d568a89a45456d9405f347d57b2caf9a80ad179
while 7/12 fail for 069eb070a95e65e0468a2679e1a35f5408b10023

**Comment by max-nextcloud** [comment]
@come-nc you observed the same in `groupfolders`, right?

**Comment by max-nextcloud** [comment]
[cypress-1.log(1).zip](https://github.com/nextcloud/server/files/13702978/cypress-1.log.1.zip)
Very verbose log including lock debug output for the failed test run.

**Comment by come-nc** [comment]
Think CI on both https://github.com/nextcloud/groupfolders/pull/2694 and https://github.com/nextcloud/groupfolders/pull/2644 is failing because of this bug.

**Comment by come-nc** [comment]
For the tests in groupfolders, this was somehow fix by making sure the action menu showed up before clicking on the delete button. Maybe only because it slows a bit down requests?

**Comment by come-nc** [comment]
Stack trace:
```
#0 /var/www/html/lib/private/Lock/DBLockingProvider.php(214): OCP\Lock\LockedException->__construct('...')
#1 /var/www/html/lib/private/Files/Storage/Common.php(831): OC\Lock\DBLockingProvider->changeLock('...', 2)
#2 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Common->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#3 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#4 /var/www/html/lib/private/Files/Storage/Wrapper/Jail.php(466): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#5 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Jail->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#6 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#7 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#8 /var/www/html/lib/private/Files/View.php(1980): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#9 /var/www/html/lib/private/Files/View.php(1150): OC\Files\View->changeLock('...', 2)
#10 /var/www/html/lib/private/Files/View.php(702): OC\Files\View->basicOperation('...', '...', Array)
#11 /var/www/html/apps/dav/lib/Connector/Sabre/File.php(543): OC\Files\View->unlink('...')
#12 /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php(185): OCA\DAV\Connector\Sabre\File->delete()
#13 /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(281): Sabre\DAV\Tree->delete('...')
#14 /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#15 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit('...', Array)
#16 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#17 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
#18 /var/www/html/apps/dav/lib/Server.php(370): Sabre\DAV\Server->exec()
#19 /var/www/html/apps/dav/appinfo/v2/remote.php(35): OCA\DAV\Server->exec()
#20 /var/www/html/remote.php(172): require_once('...')
#0 /var/www/html/lib/private/Files/Storage/Common.php(833): OCP\Lock\LockedException->__construct('...', Object(OCP\Lock\LockedException), NULL, '...')
#1 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Common->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#2 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#3 /var/www/html/lib/private/Files/Storage/Wrapper/Jail.php(466): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#4 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Jail->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#5 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#6 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(629): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#7 /var/www/html/lib/private/Files/View.php(1980): OC\Files\Storage\Wrapper\Wrapper->changeLock('...', 2, Object(OC\Lock\DBLockingProvider))
#8 /var/www/html/lib/private/Files/View.php(1150): OC\Files\View->changeLock('...', 2)
#9 /var/www/html/lib/private/Files/View.php(702): OC\Files\View->basicOperation('...', '...', Array)
#10 /var/www/html/apps/dav/lib/Connector/Sabre/File.php(543): OC\Files\View->unlink('...')
#11 /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php(185): OCA\DAV\Connector\Sabre\File->delete()
#12 /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(281): Sabre\DAV\Tree->delete('...')
#13 /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#14 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit('...', Array)
#15 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#16 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
#17 /var/www/html/apps/dav/lib/Server.php(370): Sabre\DAV\Server->exec()
#18 /var/www/html/apps/dav/appinfo/v2/remote.php(35): OCA\DAV\Server->exec()
#19 /var/www/html/remote.php(172): require_once('...')
#0 /var/www/html/lib/private/Files/View.php(1989): OCP\Lock\LockedException->__construct('...', Object(OCP\Lock\LockedException), NULL)
#1 /var/www/html/lib/private/Files/View.php(1150): OC\Files\View->changeLock('...', 2)
#2 /var/www/html/lib/private/Files/View.php(702): OC\Files\View->basicOperation('...', '...', Array)
#3 /var/www/html/apps/dav/lib/Connector/Sabre/File.php(543): OC\Files\View->unlink('...')
#4 /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php(185): OCA\DAV\Connector\Sabre\File->delete()
#5 /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(281): Sabre\DAV\Tree->delete('...')
#6 /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#7 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit('...', Array)
#8 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
#10 /var/www/html/apps/dav/lib/Server.php(370): Sabre\DAV\Server->exec()
#11 /var/www/html/apps/dav/appinfo/v2/remote.php(35): OCA\DAV\Server->exec()
#12 /var/www/html/remote.php(172): require_once('...')
```

**Comment by come-nc** [comment]
```
Array
(
    [0] => Array
        (
            [id] => 3271
            [lock] => 2
            [key] => files/02ea19023cf44d868d8fdb6850886606
            [ttl] => 1707143732
        )
)
```
This entry is found where it expected lock to be 1 to be able to lock it exclusively. That would suggest something else is locking the file. What I do not get is why the path looks like that?

**Comment by come-nc** [comment]
Current theory: the loading of the preview locks the file and conflicts with the deletion. I’m gonna try waiting for preview to be loaded before attempting to delete files.

**Comment by max-nextcloud** [comment]
Looks like the tests are green again now. No idea why. Either way the server behavior is consistent with expectations for locking. So I will close this and in case we run into the failing tests again i will either disable the `files_locking` or wait for previews. Thanks for the pointer @come-nc

**Comment by max-nextcloud** [comment]
Tests went back to flaky - but waiting for preview did the trick! Thanks Come! :heart:
