### ISSUE TITLE
Manual uploading of photos from iOS app results in error

### ISSUE THREAD

**Issue by gbiggs** [nextcloud/server#4269]
### Steps to reproduce
1. Select a folder in the iOS nextcloud app
2. Touch the "+" symbol to upload a file manually
3. Select "Add photos or videos"
4. Choose "Camera roll"
5. Choose one or more photos
6. Touch "Done"

### Expected behaviour
The selected photo(s) should be uploaded to the current folder.

### Actual behaviour
No photos are uploaded. The app produces a red error bar containing the following text:

```
Server error
Read File WebDAV: [items NULL] please fix

```
The server log has an error about not being able to locate the file (see server log below).

Other uploads (automatic photo uploads, manually uploading a PDF from Safari, creating a folder, etc.) work fine. In these cases, the nextcloud server log file shows entries of `File created`, `File written to`, and `File accessed`, with the webserver log showing a `PUT` request for the new file.

I reported this on the iOS tracker (https://github.com/nextcloud/ios/issues/107), but was told that the error is a wrong response from the server, not an iOS problem.

### Server configuration

**Operating system**: Debian 8.7

**Web server:** nginx 1.6.2-5+deb8u4

**Database:** postgresql 9.4+165+deb8u2

**PHP version:** PHP5 5.6.30+dfsg-0+deb8u1

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Owncloud 9.1

**Where did you install Nextcloud from:** Source

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "517936fc25032",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/clouds",
        "dbtype": "pgsql",
        "version": "11.0.1.2",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "logtimezone": "Japan",
        "logfile": "\/var\/log\/nextcloud.log",
        "dbname": "owncloud_db",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** iOS Nextcloud client 2.16 (00012)

**Operating system:** iOS 10.3.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[10/Apr/2017:16:06:50 +0900] "PROPFIND /remote.php/dav/files/geoff/ HTTP/1.1" 207 556 "-" "Mozilla/5.0 (Linux) mirall/2.3.1 (Nextcloud)"
[10/Apr/2017:16:06:52 +0900] "PROPFIND /remote.php/webdav/miscellaneous/2017-03-31%2012-21-27%201746.jpg HTTP/1.1" 200 11828 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.16"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"EkQvoaEg1ZV5gZTA4Qgz","remoteAddr":"XXX.XXX.XXX.XXX","app":"admin_audit","message":"Login attempt: \"geoff\"","level":1,"time":"2017-04-10T16:06:52+09:00","method":"PROPFIND","url":"\/remote.php\/webdav\/miscellaneous\/2017-03-31%2012-21-27%201746.jpg","user":"--","version":"11.0.1.2"}
{"reqId":"EkQvoaEg1ZV5gZTA4Qgz","remoteAddr":"XXX.XXX.XXX.XXX","app":"admin_audit","message":"Login successful: \"geoff\"","level":1,"time":"2017-04-10T16:06:52+09:00","method":"PROPFIND","url":"\/remote.php\/webdav\/miscellaneous\/2017-03-31%2012-21-27%201746.jpg","user":"geoff","version":"11.0.1.2"}
{"reqId":"EkQvoaEg1ZV5gZTA4Qgz","remoteAddr":"XXX.XXX.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name miscellaneous\\\/2017-03-31 12-21-27 1746.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(939): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('miscellaneous\\\/2...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('miscellaneous\\\/2...', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173,\"User\":\"geoff\"}","level":0,"time":"2017-04-10T16:06:52+09:00","method":"PROPFIND","url":"\/remote.php\/webdav\/miscellaneous\/2017-03-31%2012-21-27%201746.jpg","user":"geoff","version":"11.0.1.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
None
```
</details>

**Comment by kozoke** [comment]
I'm having the same problem.  my red error message states: "Automatic Upload https://<server ip>/nextcloud/remote.php/webdav/photos
Folder could not be created

**Comment by MorrisJobke** [comment]
This seems to be a bug in iOS requiring a too specific response and not handle the error case properly.
