### ISSUE TITLE
Use Delta for subscription calendars instead of deleting and reinserting all events

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43541]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/pull/42345 / https://github.com/nextcloud/server/pull/43261 shows a long running transaction for the webcal background sync:

```
Exception: Long running transaction
#9 /var/www/nextcloud/lib/private/DB/Connection.php(680): OC\DB\Connection::commit
#8 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(154): OC\DB\ConnectionAdapter::commit
#7 /var/www/nextcloud/lib/public/AppFramework/Db/TTransactional.php(64): OCA\DAV\CalDAV\CalDavBackend::atomic
#6 /dav/lib/CalDAV/CalDavBackend.php(3075): OCA\DAV\CalDAV\CalDavBackend::purgeAllCachedEventsForSubscription
#5 /dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php(101): OCA\DAV\CalDAV\WebcalCaching\RefreshWebcalService::refreshSubscription
#4 /dav/lib/BackgroundJob/RefreshWebcalJob.php(115): OCA\DAV\BackgroundJob\RefreshWebcalJob::run
#3 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(81): OCP\BackgroundJob\Job::start
#2 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(67): OCP\BackgroundJob\Job::execute
#1 /dav/lib/BackgroundJob/RefreshWebcalJob.php(108): OCA\DAV\BackgroundJob\RefreshWebcalJob::execute
#0 /var/www/nextcloud/cron.php(152): null
```

### Steps to reproduce

1. Set up Nextcloud 28.0.2
2. Install Calendar
3. Add a webcal subscription

### Expected behavior

Fast transaction

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Stepped through the code quickly. Looks like

```sql
SELECT `synctoken` FROM `oc_calendarsubscriptions` WHERE `id` = :dcValue1;
INSERT INTO `oc_calendarchanges` (`uri`, `synctoken`, `calendarid`, `operation`, `calendartype`) VALUES(:dcValue1, :dcValue2, :dcValue3, :dcValue4, :dcValue5);
UPDATE `oc_calendarsubscriptions` SET `synctoken` = :dcValue1 WHERE `id` = :dcValue2;
```

is called for each item in the subscription. This subscription has >2k entries. That makes 6k queries just to purge old data.
