### ISSUE TITLE
[Bug]: error trying to use note app

### ISSUE THREAD

**Issue by Kofangun** [nextcloud/server#43648]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 30270090 (PROD)

---

OS Version: 5.4.242-27760517-abG998BXXS9FWLA(G998BXXS9FWLA)
OS API Level: 34
Device: p3s
Manufacturer: samsung
Model (and Product): SM-G998B (p3sxxx)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 404
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:197)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:180)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:122)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1$it-niedermann-owncloud-notes-persistence-NotesImportTask(NotesImportTask.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="fr" data-locale="fr_FR" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			Nextcloud		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/apps/theming/favicon?v=b6589fc6">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=b6589fc6">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=b6589fc6" crossorigin="use-credentials">
		<link rel="stylesheet" href="/core/css/server.css?v=089b4d01-0">
<link rel="stylesheet" href="/custom_apps/deck/css/deck.css?v=4472fbfb-0">
<link rel="stylesheet" href="/custom_apps/spreed/css/unified-search.css?v=1090b214-0">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=70e2b24f-0">
<link rel="stylesheet" href="/core/css/guest.css?v=089b4d01-0">
		<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/dist/core-common.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/dist/core-main.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/core/l10n/fr.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/apps/firstrunwizard/l10n/fr.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/apps/firstrunwizard/js/about.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/apps/theming/l10n/fr.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/apps/theming/js/theming.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/apps/files_sharing/l10n/fr.js?v=089b4d01-0"></script>
<script nonce="RHhCeDlCeFlEdzJIU1BYRVBoNDUrR1NCNVdJcm04T2ZKTlJwdERad283az06U21NWnduY3VYMkhNQUtLUVYxOURzRGV5Z3pwQzJJanBTcFk0eG1BYnh0cz0=" defer src="/dist/files_sharing-main.js?v=089b4d01-0"></script>
		<link rel="stylesheet" media="" href="/apps/theming/theme/default.css?plain=1&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: light)" href="/apps/theming/theme/light.css?plain=1&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark)" href="/apps/theming/theme/dark.css?plain=1&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="(prefers-contrast: more)" href="/apps/theming/theme/light-highcontrast.css?plain=1&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark) and (prefers-contrast: more)" href="/apps/theming/theme/dark-highcontrast.css?plain=1&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light.css?plain=0&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark.css?plain=0&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light-highcontrast.css?plain=0&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark-highcontrast.css?plain=0&amp;v=3d8f047b" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/opendyslexic.css?plain=0&amp;v=3d8f047b" class="theme"/>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Cette application requiert JavaScript pour fonctionner correctement. Veuillez <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">activer JavaScript</a> et recharger la page.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-firstrunwizard-desktop" value="Imh0dHBzOlwvXC9uZXh0Y2xvdWQuY29tXC9pbnN0YWxsXC8jaW5zdGFsbC1jbGllbnRzIg==">
					<input type="hidden" id="initial-state-firstrunwizard-android" value="Imh0dHBzOlwvXC9wbGF5Lmdvb2dsZS5jb21cL3N0b3JlXC9hcHBzXC9kZXRhaWxzP2lkPWNvbS5uZXh0Y2xvdWQuY2xpZW50Ig==">
					<input type="hidden" id="initial-state-firstrunwizard-ios" value="Imh0dHBzOlwvXC9nZW8uaXR1bmVzLmFwcGxlLmNvbVwvdXNcL2FwcFwvbmV4dGNsb3VkXC9pZDExMjU0MjAxMDI/bXQ9OCI=">
					<input type="hidden" id="initial-state-theming-backgroundImage" value="ImRlZmF1bHQi">
					<input type="hidden" id="initial-state-theming-backgroundColor" value="IiMwMDgyYzki">
					<input type="hidden" id="initial-state-theming-themingDefaultBackground" value="IiI=">
					<input type="hidden" id="initial-state-theming-defaultShippedBackground" value="ImthbWlsLXBvcmVtYmluc2tpLWNsb3Vkcy5qcGci">
					<input type="hidden" id="initial-state-theming-shippedBackgrounds" value="eyJoYW5uYWgtbWFjbGVhbi1zb2Z0LWZsb3JhbC5qcGciOnsiYXR0cmlidXRpb24iOiJTb2Z0IGZsb3JhbCAoSGFubmFoIE1hY0xlYW4sIENDMCkiLCJkZXNjcmlwdGlvbiI6IkFic3RyYWN0IGJhY2tncm91bmQgcGljdHVyZSBpbiB5ZWxsb3cgYW5kIHdoaXRlIGNvbG9yIHdoaXRoIGEgZmxvd2VyIG9uIGl0IiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3N0b2Nrc25hcC5pb1wvcGhvdG9cL3NvZnQtZmxvcmFsLVhPWVdDQ1c1UEEiLCJ0aGVtaW5nIjoiZGFyayIsInByaW1hcnlfY29sb3IiOiIjOWY2NTJmIn0sInRlZC1tb3JhdmVjLW1vcm5pbmctZm9nLmpwZyI6eyJhdHRyaWJ1dGlvbiI6Ik1vcm5pbmcgZm9nIChUZWQgTW9yYXZlYywgUHVibGljIERvbWFpbikiLCJkZXNjcmlwdGlvbiI6IkJhY2tncm91bmQgcGljdHVyZSBvZiBhIGZvcmVzdCBzaHJvdWRlZCBpbiBmb2ciLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvZmxpY2tyLmNvbVwvcGhvdG9zXC90bW9yYXZlY1wvNTIzOTI0MTAyNjEiLCJ0aGVtaW5nIjoiZGFyayIsInByaW1hcnlfY29sb3IiOiIjMTE0YzNiIn0sInN0ZWZhbnVzLW1hcnRhbnRvLXNldHlvLWh1c29kby11bmRlcndhdGVyLW9jZWFuLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlVuZGVyd2F0ZXIgb2NlYW4gKFN0ZWZhbnVzIE1hcnRhbnRvIFNldHlvIEh1c29kbywgQ0MwKSIsImRlc2NyaXB0aW9uIjoiQmFja2dyb3VuZCBwaWN0dXJlIG9mIGFuIHVuZGVyd2F0ZXIgb2NlYW4iLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvc3RvY2tzbmFwLmlvXC9waG90b1wvdW5kZXJ3YXRlci1vY2Vhbi1USkE5TEJINFdTIiwicHJpbWFyeV9jb2xvciI6IiMwNDU3N2UifSwiem9sdGFuLXZvcm9zLXJoeXRobS1hbmQtYmx1ZXMuanBnIjp7ImF0dHJpYnV0aW9uIjoiUmh5dGhtIGFuZCBibHVlcyAoWm9sdFx1MDBlMW4gVlx1MDBmNnJcdTAwZjZzLCBDQyBCWSkiLCJkZXNjcmlwdGlvbiI6IkFic3RyYWN0IGJhY2tncm91bmQgcGljdHVyZSBvZiBzYW5kIGR1bmVzIGR1cmluZyBuaWdodCIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC9mbGlja3IuY29tXC9waG90b3NcL3Y5MjN6XC81MTYzNDQwOTI4OVwvIiwicHJpbWFyeV9jb2xvciI6IiMxYzI0M2MifSwiYW5hdG9seS1taWtoYWx0c292LWJ1dHRlcmZseS13aW5nLXNjYWxlLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IkJ1dHRlcmZseSB3aW5nIHNjYWxlIChBbmF0b2x5IE1pa2hhbHRzb3YsIENDIEJZLVNBKSIsImRlc2NyaXB0aW9uIjoiQmFja2dyb3VuZCBwaWN0dXJlIG9mIGEgcmVkLWlzaCBidXR0ZXJmbHkgd2luZyB1bmRlciBtaWNyb3Njb3BlIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTolRDAlQTclRDAlQjUlRDElODglRDElODMlRDAlQjklRDAlQkElRDAlQjhfJUQwJUJBJUQxJTgwJUQxJThCJUQwJUJCJUQwJUIwXyVEMCVCMSVEMCVCMCVEMCVCMSVEMCVCRSVEMSU4NyVEMCVCQSVEMCVCOC5qcGciLCJwcmltYXJ5X2NvbG9yIjoiI2E1M2MxNyJ9LCJiZXJuaWUtY2V0b25pYS1hdXJhdGEtdGFrZS1vZmYtY29tcG9zaXRpb24uanBnIjp7ImF0dHJpYnV0aW9uIjoiQ2V0b25pYSBhdXJhdGEgdGFrZSBvZmYgY29tcG9zaXRpb24gKEJlcm5pZSwgUHVibGljIERvbWFpbikiLCJkZXNjcmlwdGlvbiI6Ik1vbnRhZ2Ugb2YgYSBjZXRvbmlhIGF1cmF0YSBidWcgdGhhdCB0YWtlcyBvZmYgd2l0aCB3aGl0ZSBiYWNrZ3JvdW5kIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTpDZXRvbmlhX2F1cmF0YV90YWtlX29mZl9jb21wb3NpdGlvbl8wNTE3MjAwOS5qcGciLCJ0aGVtaW5nIjoiZGFyayIsInByaW1hcnlfY29sb3IiOiIjNTY2MzNkIn0sImRlamFuLWtyc21hbm92aWMtcmliYmVkLXJlZC1tZXRhbC5qcGciOnsiYXR0cmlidXRpb24iOiJSaWJiZWQgcmVkIG1ldGFsIChEZWphbiBLcnNtYW5vdmljLCBDQyBCWSkiLCJkZXNjcmlwdGlvbiI6IkFic3RyYWN0IGJhY2tncm91bmQgcGljdHVyZSBvZiByZWQgcmliYmVkIG1ldGFsIHdpdGggdHdvIGhvcml6b250YWwgd2hpdGUgZWxlbWVudHMgb24gdG9wIG9mIGl0IiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3d3dy5mbGlja3IuY29tXC9waG90b3NcL2RlamFua3JzbWFub3ZpY1wvNDI5NzE0NTY3NzRcLyIsInByaW1hcnlfY29sb3IiOiIjOWM0MjM2In0sImVkdWFyZG8tbmV2ZXMtcGVkcmEtYXp1bC5qcGciOnsiYXR0cmlidXRpb24iOiJQZWRyYSBhenVsIG1pbGt5IHdheSAoRWR1YXJkbyBOZXZlcywgQ0MgQlktU0EpIiwiZGVzY3JpcHRpb24iOiJCYWNrZ3JvdW5kIHBpY3R1cmUgb2YgdGhlIG1pbGt5IHdheSBkdXJpbmcgbmlnaHQgd2l0aCBhIG1vdW50YWluIGluIGZyb250IG9mIGl0IiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTpQZWRyYV9BenVsX01pbGt5X1dheS5qcGciLCJwcmltYXJ5X2NvbG9yIjoiIzRmNjA3MSJ9LCJldXJvcGVhbi1zcGFjZS1hZ2VuY3ktYmFyZW50cy1ibG9vbS5qcGciOnsiYXR0cmlidXRpb24iOiJCYXJlbnRzIGJsb29tIChFdXJvcGVhbiBTcGFjZSBBZ2VuY3ksIENDIEJZLVNBKSIsImRlc2NyaXB0aW9uIjoiQWJzdHJhY3QgYmFja2dyb3VuZCBwaWN0dXJlIG9mIGJsb29taW5nIGJhcmVudHMgaW4gYmx1ZSBhbmQgZ3JlZW4gY29sb3JzIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3d3dy5lc2EuaW50XC9FU0FfTXVsdGltZWRpYVwvSW1hZ2VzXC8yMDE2XC8wOFwvQmFyZW50c19ibG9vbSIsInByaW1hcnlfY29sb3IiOiIjMzk2NDc1In0sImhhbm5lcy1mcml0ei1mbGlwcGl0eS1mbG9wcGl0eS5qcGciOnsiYXR0cmlidXRpb24iOiJGbGlwcGl0eSBmbG9wcGl0eSAoSGFubmVzIEZyaXR6LCBDQyBCWS1TQSkiLCJkZXNjcmlwdGlvbiI6IkFic3RyYWN0IGJhY2tncm91bmQgcGljdHVyZSBvZiBtYW55IHBhaXJzIG9mIGZsaXAgZmxvcHMgaGFuZ2luZyBvbiBhIHdhbGwgaW4gbXVsdGlwbGUgY29sb3JzIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cDpcL1wvaGFubmVzLnBob3Rvc1wvZmxpcHBpdHktZmxvcHBpdHkiLCJwcmltYXJ5X2NvbG9yIjoiIzk4NDE1YSJ9LCJoYW5uZXMtZnJpdHotcm91bGV0dGUuanBnIjp7ImF0dHJpYnV0aW9uIjoiUm91bGV0dGUgKEhhbm5lcyBGcml0eiwgQ0MgQlktU0EpIiwiZGVzY3JpcHRpb24iOiJCYWNrZ3JvdW5kIHBpY3R1cmUgb2YgYSByb3RhdGluZyBnaWFudCB3aGVlbCBkdXJpbmcgbmlnaHQiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwOlwvXC9oYW5uZXMucGhvdG9zXC9yb3VsZXR0ZSIsInByaW1hcnlfY29sb3IiOiIjODQ1MzM0In0sImhhbm5lcy1mcml0ei1zZWEtc3ByYXkuanBnIjp7ImF0dHJpYnV0aW9uIjoiU2VhIHNwcmF5IChIYW5uZXMgRnJpdHosIENDIEJZLVNBKSIsImRlc2NyaXB0aW9uIjoiQmFja2dyb3VuZCBwaWN0dXJlIG9mIGEgc3RvbmUgY29hc3Qgd2l0aCBmb2cgYW5kIHNlYSBiZWhpbmQgaXQiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwOlwvXC9oYW5uZXMucGhvdG9zXC9zZWEtc3ByYXkiLCJwcmltYXJ5X2NvbG9yIjoiIzRmNjA3MSJ9LCJrYW1pbC1wb3JlbWJpbnNraS1jbG91ZHMuanBnIjp7ImF0dHJpYnV0aW9uIjoiQ2xvdWRzIChLYW1pbCBQb3JlbWJpXHUwMTQ0c2tpLCBDQyBCWS1TQSkiLCJkZXNjcmlwdGlvbiI6IkJhY2tncm91bmQgcGljdHVyZSBvZiB3aGl0ZSBjbG91ZHMgb24gaW4gZnJvbnQgb2YgYSBibHVlIHNreSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC93d3cuZmxpY2tyLmNvbVwvcGhvdG9zXC9wYXN6Y3phazAwMFwvODcxNTg1MTUyMVwvIiwicHJpbWFyeV9jb2xvciI6IiMwMDgyYzkifSwiYmVybmFyZC1zcHJhZ2ctbmV3LXplYWxhbmQtZmVybi5qcGciOnsiYXR0cmlidXRpb24iOiJOZXcgemVhbGFuZCBmZXJuIChCZXJuYXJkIFNwcmFnZywgQ0MwKSIsImRlc2NyaXB0aW9uIjoiQWJzdHJhY3QgYmFja2dyb3VuZCBwaWN0dXJlIG9mIGZlcm4gbGVhZmVzIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTpOWl9GZXJuLihCbGVjaG51bV9jaGFtYmVyc2lpKV8oMTEyNjM1MzQ5MzYpLmpwZyIsInByaW1hcnlfY29sb3IiOiIjMzE2YjI2In0sInJhd3BpeGVsLXBpbmstdGFwaW9jYS1idWJibGVzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlBpbmsgdGFwaW9jYSBidWJibGVzIChSYXdwaXhlbCwgQ0MgQlkpIiwiZGVzY3JpcHRpb24iOiJBYnN0cmFjdCBiYWNrZ3JvdW5kIHBpY3R1cmUgb2YgcGluayB0YXBpb2NhIGJ1YmJsZXMiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3LmZsaWNrci5jb21cL3Bob3Rvc1wvYnlyYXdwaXhlbFwvMjc2NjUxNDAyOThcL2luXC9waG90b3N0cmVhbVwvIiwidGhlbWluZyI6ImRhcmsiLCJwcmltYXJ5X2NvbG9yIjoiIzdiNGU3ZSJ9LCJuYXNhLXdheGluZy1jcmVzY2VudC1tb29uLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IldheGluZyBjcmVzY2VudCBtb29uIChOQVNBLCBQdWJsaWMgRG9tYWluKSIsImRlc2NyaXB0aW9uIjoiQmFja2dyb3VuZCBwaWN0dXJlIG9mIGdsb3dpbmcgZWFydGggaW4gZm9yZWdyb3VuZCBhbmQgbW9vbiBpbiB0aGUgYmFja2dyb3VuZCIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC93d3cubmFzYS5nb3ZcL2ltYWdlLWZlYXR1cmVcL2Etd2F4aW5nLWNyZXNjZW50LW1vb24iLCJwcmltYXJ5X2NvbG9yIjoiIzAwNWFjMSJ9LCJ0b21teS1jaGF1LWFscmVhZHkuanBnIjp7ImF0dHJpYnV0aW9uIjoiQ2l0eXNjYXBlIChUb21teSBDaGF1LCBDQyBCWSkiLCJkZXNjcmlwdGlvbiI6IkJhY2tncm91bmQgcGljdHVyZSBvZiBhIHNreXNjcmFwZXIgY2l0eSBkdXJpbmcgbmlnaHQiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3LmZsaWNrci5jb21cL3Bob3Rvc1wvOTA5NzU2OTNATjA1XC8xNjkxMDk5OTM2OCIsInByaW1hcnlfY29sb3IiOiIjNmEyYWY0In0sInRvbW15LWNoYXUtbGlvbi1yb2NrLWhpbGwuanBnIjp7ImF0dHJpYnV0aW9uIjoiTGlvbiByb2NrIGhpbGwgKFRvbW15IENoYXUsIENDIEJZKSIsImRlc2NyaXB0aW9uIjoiQmFja2dyb3VuZCBwaWN0dXJlIG9mIG1vdW50YWlucyBkdXJpbmcgc3Vuc2V0IG9yIHN1bnJpc2UiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3LmZsaWNrci5jb21cL3Bob3Rvc1wvOTA5NzU2OTNATjA1XC8xNzEzNjQ0MDI0NiIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM3ZjRmNzAifSwibGFsaS1tYXNyaWVyYS15ZWxsb3ctYnJpY2tzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlllbGxvdyBicmlja3MgKExhbGkgTWFzcmllcmEsIENDIEJZKSIsImRlc2NyaXB0aW9uIjoiQmFja2dyb3VuZCBwaWN0dXJlIG9mIHllbGxvdyBicmlja3Mgd2l0aCBzb21lIHllbGxvdyB0dWJlcyIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC93d3cuZmxpY2tyLmNvbVwvcGhvdG9zXC92aXN1YWxwYW5pY1wvMzk4MjQ2NDQ0NyIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM3ZjU3MDAifX0=">
					<input type="hidden" id="initial-state-theming-data" value="eyJuYW1lIjoiTmV4dGNsb3VkIiwidXJsIjoiaHR0cHM6XC9cL25leHRjbG91ZC5jb20iLCJzbG9nYW4iOiJ1biBsaWV1IHNcdTAwZmJyIHBvdXIgdG91dGVzIHZvcyBkb25uXHUwMGU5ZXMiLCJjb2xvciI6IiMwMDgyYzkiLCJkZWZhdWx0Q29sb3IiOiIjMDA4MmM5IiwiaW1wcmludFVybCI6IiIsInByaXZhY3lVcmwiOiIiLCJpbnZlcnRlZCI6dHJ1ZSwiY2FjaGVCdXN0ZXIiOiIzZDhmMDQ3YiIsImVuYWJsZWRUaGVtZXMiOltdfQ==">
					<input type="hidden" id="initial-state-core-versionHash" value="IjA4OWI0ZDAxIg==">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header>
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						Nextcloud					</h1>
						<div class="body-login-container update">
		<div class="icon-big icon-search"></div>
		<h2>Page non trouvée</h2>
		<p class="infogroup">La page n&#039;a pas pu être trouvée sur le serveur ou vous n&#039;avez pas le droit de la visualiser.</p>
		<p><a class="button primary" href="/">
			Retour à Nextcloud		</a></p>
	</div>
				</main>
			</div>
		</div>
				<footer class="guest-box ">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – un lieu sûr pour toutes vos données			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:454)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:127)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:110)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:110)
	at android.os.Binder.execTransactInternal(Binder.java:1375)
	at android.os.Binder.execTransact(Binder.java:1311)

```

### Steps to reproduce

1.
2.
3.
Installed on docker windows

### Expected behavior

Working

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
You also need to install the Notes app on your Nextcloud Server.
