### ISSUE TITLE
[Bug]: a shared file or folder name didn't renamed.

### ISSUE THREAD

**Issue by jackywu** [nextcloud/server#44345]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

my colleague create a folder named "test" and share it to me. I saw that. and soon later he changes the folder name to "test-2", but on my side the name didn't changed.

### Steps to reproduce

1. create a folder on one computer A on NC webpage.
2. share it to another guy.
3.change the folder name on computer A.
4. ask that guy check the name on his browser.

### Expected behavior

I expect see the changes on both sides.

### Installation method

Community SNAP package

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.31.238"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.7.2",
        "overwrite.cli.url": "http:\/\/192.168.31.238",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "filelocking.enabled": "false"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - calendar: 4.6.7
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.3
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_lock: 27.0.4
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - groupfolders: 15.3.5
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.7
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.2
  - notifications: 2.15.0
  - oauth2: 1.15.2
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.5
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.6
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"wZRcTYSbCKXmvcnMnHYS","level":3,"time":"2024-03-20T06:53:24+00:00","remoteAddr":"192.168.95.243","user":"admin","app":"webdav","method":"MOVE","url":"/remote.php/dav/files/admin/All%20shared/%E6%96%87%E5%AD%97%E6%96%87%E7%A8%BF1.docx","message":"Exception thrown: Sabre\\DAV\\Exception\\Locked","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15","version":"27.1.7.2","exception":{"Exception":"Sabre\\DAV\\Exception\\Locked","Message":"","Code":0,"Trace":[{"file":"/snap/nextcloud/40887/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"validateTokens","class":"Sabre\\DAV\\Locks\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/40887/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":1448,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/40887/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"checkPreconditions","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/40887/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/40887/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/40887/htdocs/apps/dav/lib/Server.php","line":368,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/40887/htdocs/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/40887/htdocs/remote.php","line":172,"args":["/snap/nextcloud/40887/htdocs/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/snap/nextcloud/40887/htdocs/3rdparty/sabre/dav/lib/DAV/Locks/Plugin.php","Line":504,"message":"","exception":[],"CustomMessage":"Exception thrown: Sabre\\DAV\\Exception\\Locked"},"id":"65faaba7da5e9"}

---

{"reqId":"xasBlTmjWpoZe5vaNjqY","level":4,"time":"2024-03-18T13:48:21+00:00","remoteAddr":"","user":"--","app":"activity","method":"","url":"--","message":"Error while parsing activity event","userAgent":"--","version":"27.1.7.2","data":{"exception":"{\"class\":\"InvalidArgumentException\",\"message\":\"\",\"code\":0,\"file\":\"/snap/nextcloud/40887/htdocs/apps/twofactor_backupcodes/lib/Activity/Provider.php:61\",\"trace\":\"#0 /snap/nextcloud/40887/htdocs/apps/activity/lib/MailQueueHandler.php(468): OCA\\TwoFactorBackupCodes\\Activity\\Provider->parse()\\n#1 /snap/nextcloud/40887/htdocs/apps/activity/lib/MailQueueHandler.php(368): OCA\\Activity\\MailQueueHandler->parseEvent()\\n#2 /snap/nextcloud/40887/htdocs/apps/activity/lib/MailQueueHandler.php(165): OCA\\Activity\\MailQueueHandler->sendEmailToUser()\\n#3 /snap/nextcloud/40887/htdocs/apps/activity/lib/BackgroundJob/EmailNotification.php(60): OCA\\Activity\\MailQueueHandler->sendEmails()\\n#4 /snap/nextcloud/40887/htdocs/lib/private/BackgroundJob/Job.php(54): OCA\\Activity\\BackgroundJob\\EmailNotification->run()\\n#5 /snap/nextcloud/40887/htdocs/lib/private/BackgroundJob/TimedJob.php(60): OC\\BackgroundJob\\Job->execute()\\n#6 /snap/nextcloud/40887/htdocs/cron.php(152): OC\\BackgroundJob\\TimedJob->execute()\\n#7 {main}\"}","app":"activity"},"id":"65faaba7da6c7"}
```

**Comment by joshtrichards** [comment]
This is expected behavior for the parent folder, since it's just an arbitrary identifier in the target user's home directory (or wherever they choose to place it for their own organizational purposes). Folders/files *within* the share, however, will be the same.
