### ISSUE TITLE
[Bug]: Nextcloud updater fails to create backup when a data directory is not readable

### ISSUE THREAD

**Issue by Dalmat** [nextcloud/server#44351]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to update through the online updater, the backup creation fails.
The updater currently expects all user data directories to be readable by the user webserver user (www-data in my case).
You can see this in the log file :
```
2024-03-20T11:12:14+0000 89FGWjLfA3 [info] startStep("3")
2024-03-20T11:12:14+0000 89FGWjLfA3 [info] createBackup()
2024-03-20T11:12:14+0000 89FGWjLfA3 [info] backup folder location: /[...]/nextcloud/data/updater-ocdbog484xaj/backups/nextcloud-28.0.1.1-1710933134/
2024-03-20T11:12:53+0000 89FGWjLfA3 [error] POST request failed with other exception
2024-03-20T11:12:53+0000 89FGWjLfA3 [error] Exception: UnexpectedValueException
Message: RecursiveDirectoryIterator::__construct(/[...]/nextcloud/updater/../data/dalmat/files/[...]/MyPrivateDirectory): Failed to open directory: Permission denied
Code:0
Trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct()
#1 /srv/www/nextcloud/updater/index.php(445): RecursiveDirectoryIterator->getChildren()
#2 /srv/www/nextcloud/updater/index.php(1343): Updater->createBackup()
#3 {main}
File:/srv/www/nextcloud/updater/index.php
Line:445

```
This is actually not the case for me as I use nextcloud as a synchronizing solution on top of an existing nfs storage.
Some directories are private and not expected to be synchronized through the www-data user of the webserver.

We may argue whether it is a legitimate usage, but technically speaking I don't see why this is needed in the updater as the data directories/files are not part of the update backup.

As well, I'm not sure why the backup creation needs to recurse the (potentially huge) data volume while only nextcloud code/conf is to be saved according to the documentation I read.

Could we manage the non-readable directory exception or simply not recurse in the data/$user directories for backup creation ?

Thanks a lot

### Steps to reproduce

1. Use nextcloud on top of a multi user storage with different users, and directories non-readable by others
2. Try to update nextcloud through the updater
3.

### Expected behavior

The nextcloud update shall succeed even if some user data directories cannot be read

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
2024-03-20T11:12:14+0000 89FGWjLfA3 [info] startStep("3")
2024-03-20T11:12:14+0000 89FGWjLfA3 [info] createBackup()
2024-03-20T11:12:14+0000 89FGWjLfA3 [info] backup folder location: /[...]/nextcloud/data/updater-ocdbog484xaj/backups/nextcloud-28.0.1.1-1710933134/
2024-03-20T11:12:53+0000 89FGWjLfA3 [error] POST request failed with other exception
2024-03-20T11:12:53+0000 89FGWjLfA3 [error] Exception: UnexpectedValueException
Message: RecursiveDirectoryIterator::__construct(/[...]/nextcloud/updater/../data/dalmat/files/[...]/MyPrivateDirectory): Failed to open directory: Permission denied
Code:0
Trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct()
#1 /srv/www/nextcloud/updater/index.php(445): RecursiveDirectoryIterator->getChildren()
#2 /srv/www/nextcloud/updater/index.php(1343): Updater->createBackup()
#3 {main}
File:/srv/www/nextcloud/updater/index.php
Line:445
```

**Comment by joshtrichards** [comment]
> Could we manage the non-readable directory exception or simply not recurse in the data/$user directories for backup creation ?

nextcloud/updater#507
