### ISSUE TITLE
Acceptance test

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4498]
* from time to time the acceptance tests fail with a timeout issue
* see https://drone.nextcloud.com/nextcloud/server/7415/32

@danxuliu could you have a look?

**Comment by MorrisJobke** [comment]
Log:

```
07:10:40.651 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
Command duration or timeout: 56 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: '3a30ab296074', ip: '172.17.0.10', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-31-generic', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 01a16c11-4572-49d2-8374-9ed291bfc1d7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:150)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
	at com.sun.proxy.$Proxy2.getAttribute(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getAttribute(EventFiringWebDriver.java:373)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy3.getAttribute(Unknown Source)
	at org.openqa.selenium.remote.server.handler.GetElementAttribute.call(GetElementAttribute.java:36)
	at org.openqa.selenium.remote.server.handler.GetElementAttribute.call(GetElementAttribute.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: '3a30ab296074', ip: '172.17.0.10', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-31-generic', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:9457)
	at <anonymous class>.Utils.getElementAt(file:///tmp/anonymous7680842731605908180webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9039)
	at <anonymous class>.WebElement.getElementAttribute(file:///tmp/anonymous7680842731605908180webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12146)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous7680842731605908180webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous7680842731605908180webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous7680842731605908180webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12608)
07:10:40.658 WARN - Exception: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: '3a30ab296074', ip: '172.17.0.10', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-31-generic', java.version: '1.8.0_91'
Driver info: driver.version: unknown
```

**Comment by danxuliu** [comment]
I was just going to open an issue for this.

It is really strange, because that is a problem that simply should not happen in the _I write down the shared link_ step :S I have to think about it, as right now I have no idea :)

Moreover, sometimes, acceptance tests run on Drone fail because Selenium is not able to start properly (`org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.`).

Most advice on the Internet for this problem is "_your Firefox version is not compatible with your Selenium version; upgrade/downgrade Firefox_", which is clearly not the case here.

Could both problems be caused by other Drone steps hogging the system and making Firefox unresponsive or something like that? I do not know yet; I will try to investigate it, but as they are part of those "lovely" non-deterministic problems it may take a while to fix :S

Is it OK if I open a pull request just to test things by triggering builds with different configurations? I would do that in my own Drone setup... but I have never seen those problems there :(

**Comment by rullzer** [comment]
>Could both problems be caused by other Drone steps hogging the system and making Firefox unresponsive or something like that? I do not know yet; I will try to investigate it, but as they are part of those "lovely" non-deterministic problems it may take a while to fix :S

Could be. From time to time the server is under a lot of load.

> Is it OK if I open a pull request just to test things by triggering builds with different configurations? I would do that in my own Drone setup... but I have never seen those problems there :(

Of course that is fine!

**Comment by danxuliu** [comment]
>  >  Could both problems be caused by other Drone steps hogging the system and making Firefox unresponsive or something like that? I do not know yet; I will try to investigate it, but as they are part of those "lovely" non-deterministic problems it may take a while to fix :S
>  
>  Could be. From time to time the server is under a lot of load.

I have realized that I simply had to spawn more Drone agents to increase the load in my Drone setup and, while it is not 100% reproducible, when not loaded everything works fine, when the load is increased some test fail with `Element is no longer attached to the DOM`, and when it is increased even more some test fail with `Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms` .

>  >  Is it OK if I open a pull request just to test things by triggering builds with different configurations? I would do that in my own Drone setup... but I have never seen those problems there :(
>  
>  Of course that is fine!

Well, now that I was able to reproduce the problem in my Drone server there is no need to strain the public one ;)

However, I do not know how to proceed now. The problems are false positives, and it seems that they appear when the system running the tests is very loaded. The `Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms` could be mitigated by increasing the waiting time (I suppose that it can be customized, although I have not checked it), but not the other problem.

As far as I know, Drone does not provide any system to restart a specific job conditionally (for example, if certain string appears in the logs), and it does not seem to provide an API either to restart a specific job externally ([only to cancel it, even in current master](https://github.com/drone/drone/blob/18bee1b84df18e2d1329e61767969e4c7f8d344f/router/router.go#L112)).

So... any ideas? :confused:

**Comment by danxuliu** [comment]
I may have found how to fix all this after all :)

The error message from [Fix details view not closed when viewing a file in its folder](https://github.com/nextcloud/server/pull/4461) (`Element is not currently visible and so may not be interacted with`) gave me a valuable hint, and I think that now I know why that message and `Element is no longer attached to the DOM` happen when they do (basically, a concurrency problem between the test making requests to the browser and the browser processing them) and how to fix them (adding a wrapper over Mink elements that detect the problem and tries to send the requests again). If that works then `Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms` could be just solved increasing the waiting time (although I do not know yet).

I just wanted to let you know that I am working on it, but as I still have to implement the fixes and, what will be way more time consuming, test them by triggering several Drone builds in a stressed system, it will still take some time before I can send the changes ;)

**Comment by rullzer** [comment]
@danxuliu no need to apologize! You are doing us a huge favor by adding those tests and looking into it :+1:

**Comment by danxuliu** [comment]
I reopen the issue because #4662 is just one step towards fixing it, but there are still other changes needed.

**Comment by danxuliu** [comment]
The three last referenced pull requests should minimize the sporadic failures of the acceptance tests. They cover all the problems I was able to find... but there could still be other failures lurking around due to the concurrent nature of the tests with respect to the web browser executing the commands (after triggering, literally, around a hundred builds it turns out that the problems were not as reproducible as I optimistically thought at first :P ).

Moreover, as explained in the pull requests, it is not possible to fix some of the failures, only to minimize their chance of occuring, as it is not possible to guarantee that something will happen before a timeout expires (specially in loaded systems). Anyway, with the increased timeouts used now when running the acceptance tests in Drone hopefully they will not occur very often ;)
