### ISSUE TITLE
Upgrade from fresh 11.0.2 to 11.0.3 failed using the stock updater app

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/server#4505]
### Steps to reproduce
1. Start from fresh 11.0.2. No Apps
2. Run the updater app

I am testing the upgrade with QEMU first, starting from fresh NextCloudPi

https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/

here is the installation code

https://github.com/nachoparker/nextcloud-raspbian-generator/blob/master/nextcloud.sh

running it with QEMU

https://ownyourbits.com/2017/02/06/raspbian-on-qemu-with-network-access/

### Expected behaviour
1. Installation finishes ok, no warnings
2. Hitting the button to go back to your NC 11.0.3 takes you to the new instance

### Actual behaviour
1. Installation finishes ok, no warnings
2. Hitting the button to go back to your NC 11.0.3 takes you a white error screen that says 

> Composer autoloader not found, unable to continue. Check the folder "3rdparty". Running "git submodule update --init" will initialize the git submodule that handles the subfolder "3rdparty"

### Server configuration

**Operating system**: Raspbian 8

**Web server:** Apache 2.4.25, with HTTP2 enabled

**Database:** MariaDB 10

**PHP version:** PHP 7.0.16-3

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** NextCloudPi
https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/
https://github.com/nachoparker/nextcloud-raspbian-generator

**Signing status:**
was signed in as admin and performed update under "admin"

```
unable to access after update
```
</details>

**List of activated apps:**

```
$ sudo -u www-data php occ app:list
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.0.128"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ochvjilx2s62",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

</details>

### Client configuration
**Browser:** Firefox 53 

**Operating system:** raspbian 8

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WPn8JX8AAQEAAALhWYkAAAoH","remoteAddr":"192.168.0.3","app":"internet_connection_check","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 6: Could not resolve host: www.github.com\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(137): GuzzleHttp\\\\Client->get('http:\\\/\\\/www.gith...', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/CheckSetupController.php(124): OC\\\\Http\\\\Client\\\\Client->get('http:\\\/\\\/www.gith...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/CheckSetupController.php(107): OC\\\\Settings\\\\Controller\\\\CheckSetupController->isSiteReachable('www.github.com')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/CheckSetupController.php(363): OC\\\\Settings\\\\Controller\\\\CheckSetupController->isInternetConnectionWorking()\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\CheckSetupController->check()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'check', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#20 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}","level":3,"time":"2017-04-21T12:33:51+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/checksetup","user":"admin","version":"11.0.2.7"}
```
</details>

#### Browser log
irrelevant

**Comment by zenlord** [comment]
I confirm the same behaviour after updating one of my instances from 11.0.1 to 11.0.3 via the web updater. On at least one other instance, the update went fine.

**Comment by MorrisJobke** [comment]
This message is shown if the `3rdparty/` folder is empty. Could you check if there are files and folders in this folder?

**Comment by nachoparker** [comment]
I tried again and the new downloaded update behaves differently. It still goes through installation ok, but instead of that message, I get an infinite redirection loop after entering credentials.

It always requests the same `index.php/apps/files` file, which returns a 302 code and that happens over and over again until firefox detects this situation and fails.

**Comment by MorrisJobke** [comment]
Could you open a new ticket for this?

**Comment by nachoparker** [comment]
sure. I am running the test several times now to be sure that is consistent behaviour. 

I did when I first opened this ticket and everytime this happened to me, so I suspect some code in the downloaded version 11.0.3 is different than a couple weeks ago

**Comment by nachoparker** [comment]
I confirm that this is now working for me. The first time it seems that the browser was confused by the 302 redirection status

I cannot replicate the failure anymore as I used to. Reopen if you deem necessary

Thanks
