### ISSUE TITLE
logreader (2.0.0 on nc 11.0.3) shows spinning icon forever

### ISSUE THREAD

**Issue by tessus** [nextcloud/server#4564]
### Steps to reproduce
1. Goto Admin page
2. Click on Logging

### Expected behaviour
Log entries should be displayed

### Actual behaviour
Nothing is shown, except the spinning icon

### Server configuration

**Operating system**: Linux

**Web server:** Apache 2.4.25

**Database:** MySQL 5.6.25

**PHP version:** 7.1.4

**Nextcloud version:** 11.0.3.2

**Where did you install Nextcloud from:** updated from 11.0.2 to 11.0.3 with updater.phar, then occ upgrade

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - survey_client
  - user_ldap
  - user_saml
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "oc2352d53521",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "installed": true,
        "forcessl": true,
        "loglevel": 2,
        "maintenance": false,
        "trusted_domains": [
            "cloud.evermeet.cx"
        ],
        "share_folder": "\/Shared",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logdateformat": "Y-m-d H:i:s O",
        "logtimezone": "Europe\/Vienna",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_from_address": "evercloud",
        "mail_domain": "evermeet.cx",
        "mail_smtpsecure": "tls",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/data\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/cloud.evermeet.cx",
        "auth.bruteforce.protection.enabled": false
    }
}
```

### Client configuration
**Browser:** Firefox 53.0, Chrome 58.0.3029.81

**Operating system:** macOS 10.11.6

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"vQdB5WyWYdE\/7DwAnyZY","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function format() on boolean\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/projects\\\/nextcloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php(133): OCA\\\\LogReader\\\\Log\\\\LogIterator->current()\\n#1 \\\/data\\\/projects\\\/nextcloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php(73): OCA\\\\LogReader\\\\Controller\\\\LogController->responseFromIterator(Object(OCA\\\\LogReader\\\\Log\\\\LogIterator), 50, 0)\\n#2 [internal function]: OCA\\\\LogReader\\\\Controller\\\\LogController->get(50, 0)\\n#3 \\\/data\\\/projects\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/data\\\/projects\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\LogReader\\\\Controller\\\\LogController), 'get')\\n#5 \\\/data\\\/projects\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\LogReader\\\\Controller\\\\LogController), 'get')\\n#6 \\\/data\\\/projects\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\LogReader\\\\\\\\C...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/data\\\/projects\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/data\\\/projects\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/logreader...')\\n#10 \\\/data\\\/projects\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/data\\\/projects\\\/nextcloud\\\/apps\\\/logreader\\\/lib\\\/Log\\\/LogIterator.php\",\"Line\":75}","level":3,"time":"2017-04-26 04:20:52 +0200","method":"GET","url":"\/apps\/logreader\/get?offset=0&count=50","user":"x","version":"11.0.3.2"}
```

#### Browser log
```
javascript console log

JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
Unhandled rejection (<{"readyState":4,"responseText":"<!DOCT...>, no stack trace)  main.js:30:1190

```

I also opened an issue https://github.com/nextcloud/logreader/issues/50 with the logreader repository, but I think that issue tracker might not be used.

**Comment by MorrisJobke** [comment]
> I also opened an issue nextcloud/logreader#50 with the logreader repository, but I think that issue tracker might not be used.

It is the correct one -> closing here
