### ISSUE TITLE
[Bug]: Upgrade FAILED: ERROR: column "type" does not exist at character 45

### ISSUE THREAD

**Issue by aronmgv** [nextcloud/server#46879]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After performing upgrade (from `28.0.1` to `29.0.3`) started having this problem - Nextcloud will end up in maintenance mode.

### Steps to reproduce

1. using `crazymax/nextcloud:latest` with `postgres:12` images
2. being on nextcloud version `28.0.1`
3. docker-compose pull
4. docker-compose down
5. docker-compose up -d

### Expected behavior

Successful upgrade and working nextcloud server instance

### Installation method

Other Community project: [crazymax/nextcloud](https://github.com/crazy-max/docker-nextcloud)

### Nextcloud Server version

28.0.1

### Operating system

Debian:12

### PHP engine version

None

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
version: "3.7"

services:
  nextcloud:
    container_name: nextcloud.52480
    image: crazymax/nextcloud:latest
    restart: always
    ports:
      - 52480:8000
    depends_on:
      - postgres
      - redis
      - msmtpd
    volumes:
      - "$PWD/nextcloud:/data"
      - "/lvm/raid/public/nextcloud/data/:/data/data"
      - "/lvm/raid/private/backups/:/mnt/private/backups"
      - "/lvm/raid/private/data/:/mnt/private/data"
      - "/lvm/raid/private/drive/:/mnt/private/drive"
      - "/lvm/raid/private/media/:/mnt/private/media"
      - "/lvm/raid/public/backups/:/mnt/public/backups"
      - "/lvm/raid/public/drive/:/mnt/public/drive"
      - "/lvm/raid/public/ftp/:/mnt/public/ftp"
    env_file:
      - "./nextcloud.env"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
      - "DB_TYPE=${DB_TYPE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
  
  postgres:
    container_name: nextcloud.postgres
    image: postgres:12
    restart: always
    expose:
      - 5432
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    environment:
      - TZ
      - PUID
      - PGID
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      #docker exec -it nextcloud.524.postgres bash
      #su postgres
      #createuser -P nextcloud
      #createdb -O nextcloud nextcloud

  adminer:
    container_name: nextcloud.adminer.52482
    image: adminer
    ports:
      - 52482:8080
    restart: always

  redis:
    container_name: nextcloud.redis
    image: redis:4.0-alpine
    environment:
      - "TZ"
    restart: always

  msmtpd:
    container_name: nextcloud.msmtpd
    image: crazymax/msmtpd:latest
    env_file:
      - "./msmtpd.env"
    environment:
      - "TZ"
    restart: always

  cron:
    container_name: nextcloud.cron
    image: crazymax/nextcloud:latest
    depends_on:
      - nextcloud
    volumes:
      - "$PWD/nextcloud:/data"
      - "/lvm/raid/public/nextcloud/data/:/data/data"
      - "/lvm/raid/private/backups/:/mnt/private/backups"
      - "/lvm/raid/private/data/:/mnt/private/data"
      - "/lvm/raid/private/drive/:/mnt/private/drive"
      - "/lvm/raid/private/media/:/mnt/private/media"
      - "/lvm/raid/public/backups/:/mnt/public/backups"
      - "/lvm/raid/public/drive/:/mnt/public/drive"
      - "/lvm/raid/public/ftp/:/mnt/public/ftp"
    env_file:
      - "./nextcloud.env"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
      - "DB_TYPE=${DB_TYPE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/5 * * * *"
    restart: always

  previewgen:
    container_name: nextcloud.previewgen
    image: crazymax/nextcloud:latest
    depends_on:
      - nextcloud
    volumes:
      - "$PWD/nextcloud:/data"
      - "/lvm/raid/public/nextcloud/data/:/data/data"
    env_file:
      - "./nextcloud.env"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
      - "DB_TYPE=${DB_TYPE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "SIDECAR_PREVIEWGEN=1"
      - "PREVIEWGEN_PERIOD=0 * * * *"
    restart: always

  news_updater:
    container_name: nextcloud.news_updater
    image: crazymax/nextcloud:latest
    depends_on:
      - nextcloud
    volumes:
      - "$PWD/nextcloud:/data"
      - "/lvm/raid/public/nextcloud/data/:/data/data"
    env_file:
      - "./nextcloud.env"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
      - "DB_TYPE=${DB_TYPE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "SIDECAR_NEWSUPDATER=1"
      - "NC_NEWSUPDATER_THREADS=10"
      - "NC_NEWSUPDATER_TIMEOUT=300"
      - "NC_NEWSUPDATER_INTERVAL=900"
      - "NC_NEWSUPDATER_LOGLEVEL=error"
    restart: always

  collabora:
    container_name: nextcloud.collabora.52481
    image: collabora/code
    cap_add:
      - MKNOD
    ports:
      - 52481:9980
    environment:
      - "DONT_GEN_SSL_CERT=true"
      - "extra_params=--disable-ssl"
      #- "extra_params=--o:ssl.enable=false"
    restart: always

networks:
  default:
    name: nextcloud
```

### Nextcloud Logs

```shell
nextcloud.postgres         | 2024-07-27 07:34:12.084 UTC [54] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:12.084 UTC [54] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:34:12 +0200] "GET / HTTP/1.1" 503 15999 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.postgres         | 2024-07-27 07:34:13.238 UTC [55] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:13.238 UTC [55] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:34:13 +0200] "GET /index.php/apps/files/preview-service-worker.js HTTP/1.1" 404 1538 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.postgres         | 2024-07-27 07:34:15.684 UTC [57] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:15.684 UTC [57] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.news_updater     | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
nextcloud.news_updater     | You may use your browser or the occ upgrade command to do the upgrade
nextcloud.news_updater     |
nextcloud.news_updater     |
nextcloud.news_updater     |   There are no commands defined in the "news:updater" namespace.
nextcloud.news_updater     |
nextcloud.news_updater     |   Did you mean this?
nextcloud.news_updater     |       maintenance:update
nextcloud.news_updater     |
nextcloud.news_updater     |
nextcloud.news_updater     | 2024-07-27 09:34:15,794 - Nextcloud News Updater - ERROR - Command '['php', '-f', '/var/www/occ', 'news:updater:before-update']' returned non-zero exit status 1.: Trying again in 30 seconds
nextcloud.news_updater     | Traceback (most recent call last):
nextcloud.news_updater     |   File "/usr/lib/python3.12/site-packages/nextcloud_news_updater/api/updater.py", line 69, in run
nextcloud.news_updater     |     self.before_update()
nextcloud.news_updater     |   File "/usr/lib/python3.12/site-packages/nextcloud_news_updater/api/cli.py", line 103, in before_update
nextcloud.news_updater     |     self.cli.run(self.api.before_cleanup_command)
nextcloud.news_updater     |   File "/usr/lib/python3.12/site-packages/nextcloud_news_updater/api/cli.py", line 12, in run
nextcloud.news_updater     |     return check_output(commands)
nextcloud.news_updater     |            ^^^^^^^^^^^^^^^^^^^^^^
nextcloud.news_updater     |   File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
nextcloud.news_updater     |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
nextcloud.news_updater     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nextcloud.news_updater     |   File "/usr/lib/python3.12/subprocess.py", line 571, in run
nextcloud.news_updater     |     raise CalledProcessError(retcode, process.args,
nextcloud.news_updater     | subprocess.CalledProcessError: Command '['php', '-f', '/var/www/occ', 'news:updater:before-update']' returned non-zero exit status 1.
nextcloud.postgres         | 2024-07-27 07:34:22.525 UTC [58] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:22.525 UTC [58] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:34:22 +0200] "GET / HTTP/1.1" 503 15998 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.postgres         | 2024-07-27 07:34:23.561 UTC [59] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:23.561 UTC [59] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.postgres         | 2024-07-27 07:34:23.561 UTC [60] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:23.561 UTC [60] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:34:23 +0200] "GET / HTTP/1.1" 503 15998 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:34:23 +0200] "GET /index.php/apps/files/preview-service-worker.js HTTP/1.1" 404 1538 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.postgres         | 2024-07-27 07:34:24.572 UTC [61] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:24.572 UTC [61] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:34:24 +0200] "GET /index.php/apps/files/preview-service-worker.js HTTP/1.1" 404 1536 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.52480            | 2024/07/27 09:34:39 [info] 591#591: *27 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 192.168.255.12, server: , request: "GET /index.php/204 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "cloud.aronmgv.com"
nextcloud.52480            | 192.168.255.12 - macgyver [27/Jul/2024:09:34:39 +0200] "GET /index.php/204 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/3.13.23.12-Win64 (build 20240708) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
nextcloud.postgres         | 2024-07-27 07:34:39.561 UTC [62] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:39.561 UTC [62] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.postgres         | 2024-07-27 07:34:39.636 UTC [63] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:39.636 UTC [63] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - macgyver [27/Jul/2024:09:34:39 +0200] "GET /index.php/204 HTTP/1.1" 503 15998 "-" "Mozilla/5.0 (Windows) mirall/3.13.23.12-Win64 (build 20240708) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
nextcloud.postgres         | 2024-07-27 07:34:39.658 UTC [64] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:39.658 UTC [64] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - macgyver [27/Jul/2024:09:34:39 +0200] "GET /status.php HTTP/1.1" 200 150 "-" "Mozilla/5.0 (Windows) mirall/3.13.23.12-Win64 (build 20240708) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
nextcloud.postgres         | 2024-07-27 07:34:45.907 UTC [66] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:45.907 UTC [66] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.news_updater     | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
nextcloud.news_updater     | You may use your browser or the occ upgrade command to do the upgrade
nextcloud.news_updater     |
nextcloud.news_updater     |
nextcloud.news_updater     |   There are no commands defined in the "news:updater" namespace.
nextcloud.news_updater     |
nextcloud.news_updater     |   Did you mean this?
nextcloud.news_updater     |       maintenance:update
nextcloud.news_updater     |
nextcloud.news_updater     |
nextcloud.news_updater     | 2024-07-27 09:34:46,016 - Nextcloud News Updater - ERROR - Command '['php', '-f', '/var/www/occ', 'news:updater:before-update']' returned non-zero exit status 1.: Trying again in 30 seconds
nextcloud.news_updater     | Traceback (most recent call last):
nextcloud.news_updater     |   File "/usr/lib/python3.12/site-packages/nextcloud_news_updater/api/updater.py", line 69, in run
nextcloud.news_updater     |     self.before_update()
nextcloud.news_updater     |   File "/usr/lib/python3.12/site-packages/nextcloud_news_updater/api/cli.py", line 103, in before_update
nextcloud.news_updater     |     self.cli.run(self.api.before_cleanup_command)
nextcloud.news_updater     |   File "/usr/lib/python3.12/site-packages/nextcloud_news_updater/api/cli.py", line 12, in run
nextcloud.news_updater     |     return check_output(commands)
nextcloud.news_updater     |            ^^^^^^^^^^^^^^^^^^^^^^
nextcloud.news_updater     |   File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
nextcloud.news_updater     |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
nextcloud.news_updater     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nextcloud.news_updater     |   File "/usr/lib/python3.12/subprocess.py", line 571, in run
nextcloud.news_updater     |     raise CalledProcessError(retcode, process.args,
nextcloud.news_updater     | subprocess.CalledProcessError: Command '['php', '-f', '/var/www/occ', 'news:updater:before-update']' returned non-zero exit status 1.
nextcloud.postgres         | 2024-07-27 07:34:53.285 UTC [67] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:53.285 UTC [67] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - macgyver [27/Jul/2024:09:34:53 +0200] "GET /index.php/204 HTTP/1.1" 503 15998 "-" "Mozilla/5.0 (Windows) mirall/3.13.23.12-Win64 (build 20240708) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
nextcloud.postgres         | 2024-07-27 07:34:53.321 UTC [68] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:34:53.321 UTC [68] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - macgyver [27/Jul/2024:09:34:53 +0200] "GET /status.php HTTP/1.1" 200 150 "-" "Mozilla/5.0 (Windows) mirall/3.13.23.12-Win64 (build 20240708) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
nextcloud.cron             | crond: USER nextcloud pid 656 cmd php -f /var/www/cron.php
nextcloud.postgres         | 2024-07-27 07:35:00.801 UTC [69] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:35:00.801 UTC [69] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.postgres         | 2024-07-27 07:35:03.220 UTC [70] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:35:03.220 UTC [70] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:35:03 +0200] "GET / HTTP/1.1" 503 15998 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.postgres         | 2024-07-27 07:35:04.225 UTC [71] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:35:04.225 UTC [71] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "lazy" = $1
nextcloud.52480            | 192.168.255.12 - - [27/Jul/2024:09:35:04 +0200] "GET /index.php/apps/files/preview-service-worker.js HTTP/1.1" 404 1536 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
nextcloud.postgres         | 2024-07-27 07:35:16.126 UTC [73] ERROR:  column "type" does not exist at character 45
nextcloud.postgres         | 2024-07-27 07:35:16.126 UTC [73] STATEMENT:  SELECT "appid", "configkey", "configvalue", "type" FROM "appconfig" WHERE "
```

**Comment by solracsf** [comment]
Did you check https://github.com/crazy-max/docker-nextcloud/issues/170#issuecomment-2257774305 ?

**Comment by kesselb** [comment]
cc @provokateurin @tobiasKaminsky there was something weird with the migration?

**Comment by aronmgv** [comment]
> Did you check [crazy-max/docker-nextcloud#170 (comment)](https://github.com/crazy-max/docker-nextcloud/issues/170#issuecomment-2257774305) ?
> 
> You should always upgrade to the latest minor before attempting to upgrade to the next major. So 28.0.1 -> 28.0.8 -> 29.0.4.

Well that comment is to my problem I reported - so no, I did not know that.. Wouldn't it make sense to implement a check for this if such attempt of skipping minor version can entirely break the nextcloud instance?

**Comment by susnux** [comment]
> Wouldn't it make sense to implement a check for this if such attempt of skipping minor version can entirely break the nextcloud instance?

There is a check: The updater does not allow such an update.
We can not controll all deployment options out there but the officially supported habe this.
(The updater checks this,  for updates with plain zip file this is part of the documentation and even the AIO docker checks this)

Other docker deployments often just replace the files, so there is no way for us to check.  So should be part of that deployment.

**Comment by aronmgv** [comment]
But I am still facing this error - How am I supposed to troubleshoot it now? What went wrong and how to fix it please. Thanks

**Comment by kesselb** [comment]
Sorry, that went badly.

The migration https://github.com/nextcloud/server/pull/42820/files was not executed on your instance because it was just added with 28.0.2 and therefore the lazy and type columns are missing in the appconfig table. 

To make it even more confusing, we also changed the column definitions in a later migration step:

- Latest definition for type: https://github.com/nextcloud/server/blob/fcc63cad7f49ac6d5e2b6302fae3ae8d3507ee2c/core/Migrations/Version29000Date20240124132201.php#L46
- Latest definition for lazy: https://github.com/nextcloud/server/blob/fcc63cad7f49ac6d5e2b6302fae3ae8d3507ee2c/core/Migrations/Version29000Date20240124132202.php#L26

**Comment by aronmgv** [comment]
> Sorry, that went badly.
> 

Well you should not allow the upgrade then and display error Upgrade not possible due to skipping some important versions.. I already migrated all my stuff to the new instance, but for the next time such safety check can save the whole weekend for someone in the future.. Thanks!

**Comment by joshtrichards** [comment]
> Well you should not allow the upgrade then and display error Upgrade not possible due to skipping some important versions.. I already migrated all my stuff to the new instance, but for the next time such safety check can save the whole weekend for someone in the future.. Thanks!

The code update is deployed by the Docker image you're using. The second phase (the upgrade piece) is only triggered after the new version has already been deployed by the image. So the image's entrypoint needs to check for this. We cannot do so as already stated: https://github.com/nextcloud/server/issues/46879#issuecomment-2259352407
