### ISSUE TITLE
Can't inject app specific classes in ISettings

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#4723]
When I enable my app with the new ISection/ISettings it throws the following exception:

```json
{"reqId":"IcnHSzuuUokAr1GmpT3y","level":3,"time":"2017-05-07T17:15:41+00:00","remoteAddr":"10.0.2.2","user":"admin","app":"no app in context","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve itemService! Class itemService does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('itemService')\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('itemService')\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(73): OC\\\\ServerContainer->query('itemService')\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\News\\\\\\\\Settin...')\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\News\\\\\\\\Settin...')\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\News\\\\\\\\Settin...')\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(239): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\News\\\\\\\\Settin...')\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(109): OC\\\\Settings\\\\Manager->setupAdminSettings('OCA\\\\\\\\News\\\\\\\\Settin...')\\n#9 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(414): OC\\\\Settings\\\\Manager->setupSettings(Array)\\n#10 \\\/nextcloud\\\/settings\\\/ajax\\\/enableapp.php(46): OC_App->enable('news', NULL)\\n#11 \\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Route.php(155) : runtime-created function(1): require_once('\\\/nextcloud\\\/sett...')\\n#12 [internal function]: __lambda_func()\\n#13 \\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func('\\\\x00lambda_155', Array)\\n#14 \\\/nextcloud\\\/lib\\\/base.php(976): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#15 \\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.15"}
```

Reason here looks like it can't resolve my app classes because the app is not yet enabled (chicken egg problem?)

Happens on the latest master fyi

@blizzz @MorrisJobke @LukasReschke

**Comment by BernhardPosselt** [comment]
That's the class in question btw

```php
<?php
namespace OCA\News\Settings;

use OCP\AppFramework\Http\TemplateResponse;
use OCP\IRequest;
use OCP\Settings\ISettings;

use OCA\News\Config\Config;
use OCA\News\Service\ItemService;

class Admin implements ISettings {
    private $config;
    private $configPath;
    private $itemService;

    public function __construct(Config $config,
                                ItemService $itemService,
                                $configFile) {
        $this->config = $config;
        $this->configPath = $configFile;
        $this->itemService = $itemService;
    }

    public function getForm() {
        $data = [
            'autoPurgeMinimumInterval' =>
                $this->config->getAutoPurgeMinimumInterval(),
            'autoPurgeCount' => $this->config->getAutoPurgeCount(),
            'maxRedirects' => $this->config->getMaxRedirects(),
            'feedFetcherTimeout' => $this->config->getFeedFetcherTimeout(),
            'useCronUpdates' => $this->config->getUseCronUpdates(),
            'maxSize' => $this->config->getMaxSize(),
            'exploreUrl' => $this->config->getExploreUrl(),
        ];
        return new TemplateResponse('news', 'admin', $data, '');
    }

    public function getSection() {
        return 'news';
    }

    public function getPriority() {
        return 40;
    }
}
```

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
This works quite fine here with the activity app, not sure what's exactly going wrong on your side.

**Comment by BernhardPosselt** [comment]
[news.tar.gz](https://github.com/nextcloud/server/files/994113/news.tar.gz)

Try this zip file :)

**Comment by nickvergessen** [comment]
The fix is to add `new Application();` in app.php
The problem is that your custom services are registered via your Application class.
However that class is not loaded before, so your Container (with namespace News) is not loaded and registered at the `\OC::$server`, therefor `\OC::$server` can not construct the class `OCA\News\...`...

I mean we can easily add this on install. But I'm not sure if that is enough and whether it breaks on ocs/remote/controller/cron/... so I'd just add it globally.
