### ISSUE TITLE
[Bug]: Upgrade from 29.0.4 to 29.0.6 fails with TypeError in AppFetcher.php

### ISSUE THREAD

**Issue by Derkades** [nextcloud/server#47844]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
Should the "occ upgrade" command be executed? [Y/n] y
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
An unhandled exception has been thrown:
TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php:160
Stack trace:
#0 /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php(160): array_filter(NULL)
#1 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(182): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '', false)
#2 /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php(179): OC\App\AppStore\Fetcher\Fetcher->get(false)
#3 /var/www/html/lib/private/Installer.php(405): OC\App\AppStore\Fetcher\AppFetcher->get(false)
#4 /var/www/html/lib/private/Updater.php(415): OC\Installer->isUpdateAvailable('calendar')
#5 /var/www/html/lib/private/Updater.php(275): OC\Updater->upgradeAppStoreApps(Array)
#6 /var/www/html/lib/private/Updater.php(133): OC\Updater->doUpgrade('29.0.6.1', '29.0.4.1')
#7 /var/www/html/core/Command/Upgrade.php(216): OC\Updater->upgrade()
#8 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/console.php(102): OC\Console\Application->run()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')
#15 {main}
```

Looking at the source code, this happens because the app store server is not returning the expected data. Are there issues with the app store currently?

### Steps to reproduce

Run occ upgrade

### Expected behavior

N/A

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by creopard** [comment]
The server error also occurs when opening the "Apps" menue manually while being logged in (although the upgrade from 29.0.5 to 29.0.6 was successful beforehand).

**Comment by Derkades** [comment]
Alright, it would be nice if starting an upgrade while the app store is down wouldn't result in an unusable instance
