### ISSUE TITLE
Have to use stay logged in to create user/group

### ISSUE THREAD

**Issue by mikedlr** [nextcloud/server#4859]
### Steps to reproduce
1. install nextcloud (according to [Ansible Role](https://galaxy.ansible.com/aalaesar/install_nextcloud/) with PGSQL & nginx) 
2. login as admin 
3. attempt to create normal user

### Expected behaviour

I would expect to be able to create a user.

### Actual behaviour

Every time I try to select a group or click to create a user the interface demands the admin password.  Neither group nor user creation work.  

### Server configuration

**Operating system**:
Debian 8.0 / Raspbian
**Web server:**
Nginx
**Database:**
Postgesql 

**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Apr 14 2017 16:20:58) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.3 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
direct download 
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
		"***REMOVED SENSITIVE VALUE MANUALLY***",
        ],
        "datadirectory": "\/var\/ncdata",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "pgsql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "open_basedir": "\/dev\/urandom",
        "instanceid": "***REMOVED SENSITIVE VALUE MANUALLY***"

    }
}
```
</details>

**Are you using external storage, if yes which one:** 
no
**Are you using encryption:** 
SSL only 
**Are you using an external user-backend, if yes which one:** 
no
</details>

### Client configuration
**Browser:**
Chromium + various extensions
**Operating system:**
CentOS 7
#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/05/10 03:00:45 [warn] 23155#0: "ssl_stapling" ignored, issuer certificate not found
2017/05/10 03:00:45 [warn] 23158#0: "ssl_stapling" ignored, issuer certificate not found
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"GF7gQTV9eR7meBsX3W1v","remoteAddr":"192.168.1.223","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-10T03:23:10+00:00","method":"POST","url":"\/heartbeat","user":"--","version":"11.0.3.2"}
{"reqId":"uZ3cWLFt9vINI0rqLcI3","remoteAddr":"192.168.1.223","app":"core","message":"Login failed: 'admin' (Remote IP: '192.168.1.223')","level":2,"time":"2017-05-10T03:29:25+00:00","method":"POST","url":"\/login","user":"--","version":"11.0.3.2"}
{"reqId":"HZmzl4TqNt1cdgjvlK7X","remoteAddr":"192.168.1.223","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-10T03:41:34+00:00","method":"POST","url":"\/heartbeat","user":"--","version":"11.0.3.2"}
{"reqId":"b8G4LO09qR5Uti0Aq2b6","remoteAddr":"192.168.1.223","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-10T03:53:35+00:00","method":"POST","url":"\/heartbeat","user":"--","version":"11.0.3.2"}
{"reqId":"d\/Q2V4XeH+HerqW80YMa","remoteAddr":"192.168.1.223","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-10T04:05:36+00:00","method":"POST","url":"\/heartbeat","user":"--","version":"11.0.3.2"}
{"reqId":"Uxv6FRNHI4IhBPPra1fa","remoteAddr":"192.168.1.223","app":"core","message":"Login failed: 'admin' (Remote IP: '192.168.1.223')","level":2,"time":"2017-05-10T04:10:47+00:00","method":"POST","url":"\/login\/confirm","user":"admin","version":"11.0.3.2"}
{"reqId":"zsmNB3dVRrQsANu7bQK3","remoteAddr":"192.168.1.223","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given object name is invalid\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(906): OC\\\\Activity\\\\Event->setObject('files', 27, false)\\n#1 \\\/opt\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(191): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('mikedlr', 'created_self', Array, 27, false, true, true, 0, 'file_created')\\n#2 \\\/opt\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(117): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/', 'file_created', 'created_self', 'created_by')\\n#3 \\\/opt\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1237): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1163): OC\\\\Files\\\\View->runHooks(Array, '\\\/mikedlr\\\/files', true)\\n#8 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(266): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/mikedlr\\\/files', Array)\\n#9 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(149): OC\\\\Files\\\\View->mkdir('\\\/mikedlr\\\/files')\\n#10 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(380): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/mikedlr\\\/files')\\n#11 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('mikedlr')\\n#12 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#13 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#14 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Server.php(950): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('mikedlr')\\n#15 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(419): OC\\\\Server->getUserFolder('mikedlr')\\n#16 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(487): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#17 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(307): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#18 \\\/opt\\\/nextcloud\\\/core\\\/Controller\\\/LoginController.php(244): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#19 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#20 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#21 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#22 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#23 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#24 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#25 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#26 \\\/opt\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/login')\\n#27 \\\/opt\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#28 {main}\",\"File\":\"\\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Activity\\\/Event.php\",\"Line\":401}","level":3,"time":"2017-05-14T07:08:48+00:00","method":"POST","url":"\/login","user":"mikedlr","version":"11.0.3.2"}
{"reqId":"H58BgGAK2KEUR1N2Xlv1","remoteAddr":"192.168.1.223","app":"internet_connection_check","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 7: Failed to connect to www.nextcloud.com port 80: Connection refused\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/opt\\\/nextcloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(137): GuzzleHttp\\\\Client->get('http:\\\/\\\/www.next...', Array)\\n#9 \\\/opt\\\/nextcloud\\\/settings\\\/Controller\\\/CheckSetupController.php(124): OC\\\\Http\\\\Client\\\\Client->get('http:\\\/\\\/www.next...')\\n#10 \\\/opt\\\/nextcloud\\\/settings\\\/Controller\\\/CheckSetupController.php(107): OC\\\\Settings\\\\Controller\\\\CheckSetupController->isSiteReachable('www.nextcloud.c...')\\n#11 \\\/opt\\\/nextcloud\\\/settings\\\/Controller\\\/CheckSetupController.php(363): OC\\\\Settings\\\\Controller\\\\CheckSetupController->isInternetConnectionWorking()\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\CheckSetupController->check()\\n#13 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#14 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#15 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#16 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('CheckSetupContr...', 'check', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/opt\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/opt\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#20 \\\/opt\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/opt\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}","level":3,"time":"2017-05-14T08:16:49+00:00","method":"GET","url":"\/settings\/ajax\/checksetup","user":"admin","version":"11.0.3.2"}
```
the log continues with other remote connection failures

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N.A. right now
```
</details>

**Comment by mikedlr** [comment]
Just to be clear, clicking the "stay logged in" box immediately logs me in and then everything works.  This is a reasonable workaround (just remember to log out later) and so this is not an urgent issue for me.  Might be confusing / intimidating for some new users though.

**Comment by MorrisJobke** [comment]
> Every time I try to select a group or click to create a user the interface demands the admin password. Neither group nor user creation work.

This is actually a feature. After logging in you don't need to enter the password for 30 minutes. If the password was not entered in the last 30 minutes it will ask you to do so for administrative tasks (adding users, enabling apps, changing display name/email of users/yourself,...).
