### ISSUE TITLE
[Bug]: Caldav limit tag on initial sync causes incorrect Caldav error response.

### ISSUE THREAD

**Issue by JeroenBer** [nextcloud/server#48678]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

OneCalendar users are experiencing errors when syncing caldav calendars with Nextcloud. This used to be working. 

As OneCalendar developer I tried to reproduce the problem and for the latest versions of 28,29 and 30 the Caldav response is no longer working correctly when 
doing a initial sync.

Hereby an overview of which versions are working correct/incorrect:
- 28.0.9 Correct
- 28.0.10 Incorrect
- 28.0.11 Incorrect
- 29.0.6 Correct
- 29.0.7 Incorrect
- 29.0.8 Incorrect
- 30.0.0 Incorrect

### Steps to reproduce

Sync caldav calendar data:

Request data

```
<sync-collection xmlns="DAV:">
  <sync-token />
  <sync-level>1</sync-level>
  <limit>
    <nresults>100</nresults>
  </limit>
  <prop>
    <getetag />
  </prop>
</sync-collection>
```

Actual response data (507):

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
	<s:exception>Interne serverfout</s:exception>
	<s:message>
		De server was niet in staat je aanvraag te verwerken.		Stuur de hieronder afgebeelde technische details naar de serverbeheerder wanneer dit opnieuw gebeurt.		Meer details in de serverlogging,			</s:message>

	<s:technical-details>
		<s:remote-address>172.17.0.1</s:remote-address>
		<s:request-id>du8YMujFjQr6HIRmBFm1</s:request-id>

		</s:technical-details>
</d:error>
```

### Expected behavior

According to https://tools.ietf.org/html/rfc6578#section-3.11 the caldav server does not need to support limit tag but in that case the following 507 response data is expected:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Exception\UnsupportedLimitOnInitialSyncException</s:exception>
  <s:message/>
  <d:number-of-matches-within-limits/>
</d:error>
```

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Perhaps there has been a minor update/fix of SabreDav that caused this problem in the newer 28/29/30 versions ?

**Comment by joshtrichards** [comment]
> `<s:request-id>du8YMujFjQr6HIRmBFm1</s:request-id>`

The `nextcloud.log` should have a stack trace or some logging associated with this request id since it's an internal server error. Happen to have it handy from one of the instances that isn't responding as expected?

Enabling debug mode should also populate `technical-details` with more info.

I haven't looked too closely, but so far the changes introduced via #47770 & #47805 align most closely with your findings.

**Comment by kesselb** [comment]
Thanks for your report, and sorry for the troubles.

I agree with Josh that likely #47770 and #47805 changed how we handle the UnsupportedLimitOnInitialSyncException.

**Comment by JeroenBer** [comment]
Hi, I reproduced and looked in the nextcloud.log. This was what came up:

`{"reqId":"HXLFwXcaYbWcv9Fym23z","level":3,"time":"2024-10-14T18:45:34+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"webdav","method":"REPORT","url":"/remote.php/dav/calendars/admin/personal/","message":"Exception thrown: OCA\\DAV\\Exception\\UnsupportedLimitOnInitialSyncException","userAgent":"curl/7.54","version":"30.0.0.14","exception":{"Exception":"OCA\\DAV\\Exception\\UnsupportedLimitOnInitialSyncException","Message":"","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Sync/Plugin.php","line":121,"function":"getChanges","class":"OCA\\DAV\\CalDAV\\Calendar","type":"->","args":[null,"1",100]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Sync/Plugin.php","line":62,"function":"syncCollection","class":"Sabre\\DAV\\Sync\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"Sabre\\DAV\\Sync\\{closure}","class":"Sabre\\DAV\\Sync\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":690,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["report",["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpReport","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:REPORT",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":370,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":19,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":146,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/CalDAV/Calendar.php","Line":369,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\DAV\\Exception\\UnsupportedLimitOnInitialSyncException"}}`

It seems indeed the Caldav "UnsupportedLimitOnInitialSyncException". 

Probably the changes in #47770 or #47805 changed this behavior and is now producing incorrect exception behavior for Caldav. In my opinion this is clearly a bug, and it might also potentially cause issues in other Caldav errors. 

We are receiving more and more mails from people affected by this behavior. Is this something that can be fixed soon ?

**Comment by artonge** [comment]
Hmm, maybe we should display the exception for a given set of HTTP code. Probably here: https://github.com/nextcloud/server/blob/dc92218d6d3a53e6e8c825ed4efb080364259156/apps/dav/lib/Files/ErrorPagePlugin.php#L61-L88

Update that method to display or not the exception based on the HTTP code.

**Comment by JeroenBer** [comment]
Hi,
Any news on this ? Can this be solved quickly for the next release ? 
More and more users of OneCalendar are mailing us about this problem in Nextcloud now.

**Comment by pampasadmin** [comment]
The trouble with 30.0.1 is, that there is no switch back possible to 29.0.6 resp. 28.0.9. Therefore waiting for resolution is the only way forward.

**Comment by poek1** [comment]
I use the Android App OneCalender and get the Errormessage "This does not appear to be a valis CalDav server" when try to add my nextcloud account to it. It does work well with Thunderbird at Mac and Win. Would be nice to get it fixxed soon.

**Comment by emaas** [comment]
I have multiple users that are running into this issue.
My Nextcloud automatically get's updated every night to keep all the maintenance manageable.
When you are already connected to OneCalender everything works properly.
It is just with the initial setup that it is not working.

**Comment by pampasadmin** [comment]
On my Android tablet and on win11 the account setup seems to work. However syncing fails.

**Comment by bitsky6** [comment]
Any news? Nextcloud calendar currently unusable with any client. Thanks

**Comment by VEF-Admin** [comment]
The error is still present with the latest version of NC (30.0.5) and OneCalendar (5.6.0). Is there any guess when a patch/update/workaround will be available? Thanks!

**Comment by andreyvb** [comment]
I've tried several apps that sync the calendar over caldav - none work with NextCloud right now.

**Comment by Minstrel27** [comment]
I did some further research and testing, and what I’ve found is that there is a bug in later versions of Nextcloud that prevents INITIAL syncing of davx calendars. Those versions are 28.0.10 or higher, 29.0.7 or higher, and all versions of 30. Calendars where the initial sync was done in prior versions continue to sync correctly in the latest versions.

I was able to confirm this by going back and installing version 29.0.6, migrating all my data and settings, syncing the calendars, then upgrading to 30.0.2 and everything worked correctly. Obviously doing a new install of 29.0.6 each time I want to add a new user with all that entails is a task I don’t want to do every week, but at least I have an option.

Hopefully this will be fixed in the near future.

**Comment by JeroenBer** [comment]
Hello @kesselb @ChristophWurst @joshtrichards @artonge

We (OneCalendar) have already received hundreds of mails from Nextcloud users facing this issue. Reading the comments above it also seems to fail with other CalDav clients. In reality probably thousands of users are affected who can no longer sync their Nextcloud calendars.

It will be more and more affected users since it fails on initial sync if users try to connect their account again, or if they update their Nextcloud server.

For OneCalendar it's difficult/tricky to build a temporary workaround since OneCalendar syncs with a lot of other servers as well, and it could create problems and loops for non-nextcloud users.

Would it be possible to prioritise this issue ? Any estimates on when it will be solved ?

**Comment by JohnNissley** [comment]
This problem makes it very difficult to support calendars in Nextcloud at this time.  Please make the nextcloud dav calendar server compliant with industry standards.  All dav calendar clients I use are having issues connecting to nextcloud calendars when the initial connection did not happen on a lower version of nextcloud.
Please make this a priority since using nextcloud calendar for any size organization is not practical at this time and calendars are very important for any organization.

**Comment by solracsf** [comment]
Fix should be at https://github.com/nextcloud/server/pull/49004 (backports to 30, 29 and 28 will likelly happen in minor releases of January 2025).

**Comment by ibot3** [comment]
Can we somehow patch this manually until there is a proper release?
I don't want a broken calendar for another month.

**Comment by JohnNissley** [comment]
I do not work for nextcloud.

**Comment by ibot3** [comment]
Is there any chance to get this fix into 30.0.3 @kesselb ?

**Comment by poek1** [comment]
i was trying today  to add my nextcloud calender to onecalender and it worked, but syncing failed with a sync error

we have now nextcloud 29.0.9 and onecalender 5.6.0, dont know what changed

but now I get a http error message 507 Insufficient storage ???

**Comment by DesertCookie** [comment]
> but now I get a http error message 507 Insufficient storage ???

This is exactly the error related to this issue. There's a trail all the way from the [OneCalendar support page to here](https://support.onecalendar.nl/i1542-insufficient-storage).

**Comment by devnoname120** [comment]
@JeroenBer I would suggest you do a pull request next time

**Comment by kesselb** [comment]
Hi,

Sorry for not updating you earlier.

We originally planned to resolve this issue with the December 24 maintenance releases (30.0.3, 29.0.10, and 28.0.13), but during the code review, we discovered some issues that needed to be addressed. As a result, the backports weren’t merged.

I plan to resolve the open points and merge the backports for the January 25 maintenance releases (30.0.4, 29.0.11, and 28.0.14). With the holiday season coming up, code review and testing are slower than usual, so there’s a chance the patch might not be ready by the 2025-01-02 deadline.

Thank you for your understanding

**Comment by MaggiWuerze** [comment]
Did the review finish in time for the mentioned deadline? Will it ship in January?

**Comment by MaggiWuerze** [comment]
So, FYI, with the latest update from Dav5X I could do an initial sync again, so at least that doesn't seem to be connected to this (or at least not in my case)

**Comment by JeroenBer** [comment]
Hello @kesselb @ChristophWurst @joshtrichards @artonge 

Could anyone please give an update on this when it can be expected. As mentioned earlier a lot of customers facing this problem at the moment for a long time and becoming more and more...

I would like to request again please make a priority of this issue.

**Comment by nouse4it** [comment]
> Thank you for your message, [@JeroenBer](https://github.com/JeroenBer). This is a high priority for us. It's on the roadmap.

Wasn't this planned for the upcoming release of Version 30.0.5?

**Comment by MajorP93** [comment]
The PR in question that is supposed to fix this issue ([PR #49481](https://github.com/nextcloud/server/pull/49481)) is marked as pending here: https://github.com/nextcloud/server/pull/50096

I wonder if and hope that it will be included in 30.0.5.

**Comment by VEF-Admin** [comment]
I have just upgraded to Nextcloud 30.0.5, but the error still keeps coming back. Wasn't it supposed to be addressed in this release? It is disappointing....

**Comment by kesselb** [comment]
Hi there,

I’m sorry the backports didn’t make it in time. As mentioned before, it’s on our roadmap, but resolving the open points requires further coordination.

We’ll make sure to update you as soon as there’s any progress.

**Comment by JeroenBer** [comment]
Sorry but based on the answers above I don't have the feeling this has any priority at Nextcloud. 

This bug was introduced by a change in Nextcloud in September/October, since then thousands of users can no longer use their favorite third party apps to manage their calendars. A very important feature for users and it's used by many on a daily basis.

Because of the bug the Nextcloud product no longer adheres to the CalDAV standards. I would normally expect such an important feature to be fixed within days or at least in the next release after the bug was discovered. 

It's not some kind of feature you plan on a roadmap in my opinion. Since this bug has been open for more than 3 months now I am pretty disappointed in how this is being handled by Nextcloud. I would just like some commitment that this will be fixed for the first upcoming release.

**Comment by arcoast** [comment]
> Sorry but based on the answers above I don't have the feeling this has any priority at Nextcloud.
> 
> This bug was introduced by a change in Nextcloud in September/October, since then thousands of users can no longer use their favorite third party apps to manage their calendars. A very important feature for users and it's used by many on a daily basis.
> 
> Because of the bug the Nextcloud product no longer adheres to the CalDAV standards. I would normally expect such an important feature to be fixed within days or at least in the next release after the bug was discovered.
> 
> It's not some kind of feature you plan on a roadmap in my opinion. Since this bug has been open for more than 3 months now I am pretty disappointed in how this is being handled by Nextcloud. I would just like some commitment that this will be fixed for the first upcoming release.

As much as I hated doing it, as I prefer to run stable, I upgraded to the 31 beta which did resolve the issue, so I assume it will be fixed in the next **major** release at least.  

Based on the schedule [here](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#nextcloud-31) I've just got to cross my fingers and hope that no bigger issues crop up before the final release.

I do agree with your sentiment that it seems getting this fixed hasn't been a bigger priority, I can only assume the enterprise version works, otherwise I can imagine this being a huge issue for businesses, for me, as a simple home user, I just need to keep my wife happy. 🤷‍♂

**Comment by kesselb** [comment]
Hi there,

> As much as I hated doing it, as I prefer to run stable, I upgraded to the 31 beta which did resolve the issue, so I assume it will be fixed in the next major release at least.

The patch was merged into master (the source for the current 31 version) but will be reverted due to issues discovered during testing the backports for versions 30, 29, and 28.[^1]

> I can only assume the enterprise version works

That assumption is incorrect.


[^1]: https://github.com/nextcloud/server/pull/49960

**Comment by arcoast** [comment]
> Hi there,
> 
> > As much as I hated doing it, as I prefer to run stable, I upgraded to the 31 beta which did resolve the issue, so I assume it will be fixed in the next major release at least.
> 
> The patch was merged into master (the source for the current 31 version) but will be reverted due to issues discovered during testing the backports for versions 30, 29, and 28.[1](#user-content-fn-1-3ca35b45ca132fe627e10a48872b9e20)
> 

Thanks for the heads up.  I'll pin my version for now then on beta 4.  Out of curiosity, what has been the challenge in reverting things back to a working state?  It's clearly something far more involved and complicated than we'd imagined.

> 
> That assumption is incorrect.
> 
> ## Footnotes
> 1. https://github.com/nextcloud/server/pull/49960 [↩](#user-content-fnref-1-3ca35b45ca132fe627e10a48872b9e20)

I stand corrected, I got to say I'm surprised as I would have imagined businesses being of the opinion this is a significant issue.

Like I said, for me, I just need to keep the wife happy.

**Comment by JeroenBer** [comment]
@kesselb @arcoast 

Any idea what timeline we should expect now for a fix ? Days / weeks / months or won't be fixed ?

**Comment by mikebakke** [comment]
My instance upgraded to 3.0.5 last night. One Calendar still fails to sync.

Stuff, [23/01/2025 09:15]
net_http_message_not_success_statuscode_reason, 507, Insufficient Storage : <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
 <s:exception>Internal Server Error</s:exception>
 <s:message>
  The server was unable to complete your request.  If this happens again, please send the technical details below to the server administrator.  More details can be found in the server log.   </s:message>

 <s:technical-details>
  <s:remote-address>86.20.105.221</s:remote-address>
  <s:request-id>OawupUIPUTEVC5c05lGF</s:request-id>

  </s:technical-details>
</d:error>


Action: SyncReceiveCalendar
Calendar: Personal

XCalendarApp.CalDavProvider.DavAccountRequestException: net_http_message_not_success_statuscode_reason, 507, Insufficient Storage : <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
 <s:exception>Internal Server Error</s:exception>
 <s:message>
  The server was unable to complete your request.  If this happens again, please send the technical details below to the server administrator.  More details can be found in the server log.   </s:message>

 <s:technical-details>
  <s:remote-address>86.20.105.221</s:remote-address>
  <s:request-id>OawupUIPUTEVC5c05lGF</s:request-id>

  </s:technical-details>
</d:error>

 ---> CodeSpark.Apps.Common.Net.Exceptions.HttpException: net_http_message_not_success_statuscode_reason, 507, Insufficient Storage
 ---> System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode_reason, 507, Insufficient Storage
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CodeSpark.Apps.Common.Net.HttpClients.OneHttpClient.ExecuteRequest(CancellationToken cancellationToken, String url, String httpMethod, String requestContent, String authorizationHeader, Dictionary2 requestHeaders)
   Exception_EndOfInnerExceptionStack
   at CodeSpark.Apps.Common.Net.HttpClients.OneHttpClient.ExecuteRequest(CancellationToken cancellationToken, String url, String httpMethod, String requestContent, String authorizationHeader, Dictionary2 requestHeaders)
   at CodeSpark.Apps.Common.Net.WebRequests.WebRequest.ExecuteRaw(OneHttpClientFactory httpClientFactory, CancellationToken cancellationToken, XHttpClientRequirements httpClientRequirements, String url, String httpMethod, String mediaType, String requestData, String authorizationHeader, Dictionary2 requestHeaders, HttpCredential serverCredential, Boolean allowAutoRedirect, Boolean addUserAgentHeader, Encoding responseEncoding)
   at CodeSpark.Apps.Common.Net.WebRequests.ScopedWebRequest.ExecuteRaw(CancellationToken cancellationToken, XHttpClientRequirements httpClientRequirements, String url, String httpMethod, String mediaType, String requestData, String authorizationHeader, Dictionary2 requestHeaders, HttpCredential serverCredential, Boolean allowAutoRedirect, Boolean addUserAgentHeader, Encoding responseEncoding)
   at XCalendarApp.CalDavProvider.DavBasicConnection.Request(Uri url, String httpMethod, String contentType, String requestContent, Dictionary2 requestHeaders, Int32 maxRedirects)
   Exception_EndOfInnerExceptionStack
   at XCalendarApp.CalDavProvider.DavBasicConnection.Request(Uri url, String httpMethod, String contentType, String requestContent, Dictionary2 requestHeaders, Int32 maxRedirects)
   at XCalendarApp.CalDavProvider.DavBasicConnection.Request(Uri url, String method, String contentType, String requestContent, Dictionary2 requestHeaders)
   at Dav.Client.Common.DavCommon.Request(Uri url, String method, String contentType, String requestContent, Dictionary2 headers)
   at Dav.Client.CalDav.CalDavServerCalendar.RequestSync(String syncToken, Int32 maxFetchLimit, Boolean useLimits)
   at Dav.Client.CalDav.CalDavServerCalendar.RequestSync(String syncToken, Int32 maxFetchLimit, Boolean useLimits)

Stuff, [23/01/2025 09:15]
at Dav.Client.CalDav.CalDavServerCalendar.GetSyncChanges(String syncToken)
   at XCalendarApp.CalDavBaseProvider.CalDavBaseAccount1.<SyncReceiveCalendarFromProvider>d__16[[XCalendarApp.CalDavBaseProvider.CachedCalDavBaseCalendar, XCalendarApp.CalDavBaseProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at XCalendarApp.ProviderBase.AccountProviderBase9.<SyncReceiveCalendar>d__106[[XCalendarApp.CalDavBaseProvider.CachedCalDavBaseCalendar, XCalendarApp.CalDavBaseProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Dav.Client.CalDav.CalendarProperties, Dav.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[XCalendarApp.CalDavBaseProvider.CachedCalDavBaseAppointment, XCalendarApp.CalDavBaseProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CalDav.iCalendar.Event, CalDav.iCalendar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[XCalendarApp.CalDavBaseProvider.CachedCalDavBaseContacts, XCalendarApp.CalDavBaseProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[XCalendarApp.CalDavBaseProvider.CachedCalDavBaseContact, XCalendarApp.CalDavBaseProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CardDav.vCard.VCard, CardDav.vCard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[XCalendarApp.CalDavBaseProvider.CalDavBaseAppointmentDbData, XCalendarApp.CalDavBaseProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[OneSuite.Apps.Model.Domain.Accounts.CaldavAccountOptions, OneSuite.Apps.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
RequestType: REPORT
RequestUrl: https://aio.mikebakke.com/remote.php/dav/calendars/mike/personal/
RequestData: <sync-collection xmlns="DAV:">
  <sync-token />
  <sync-level>1</sync-level>
  <limit>
    <nresults>100</nresults>
  </limit>
  <prop>
    <getetag />
  </prop>
</sync-collection>
ResponseData: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
 <s:exception>Internal Server Error</s:exception>
 <s:message>
  The server was unable to complete your request.  If this happens again, please send the technical details below to the server administrator.  More details can be found in the server log.   </s:message>

 <s:technical-details>
  <s:remote-address>86.20.105.221</s:remote-address>
  <s:request-id>OawupUIPUTEVC5c05lGF</s:request-id>

  </s:technical-details>
</d:error>


Inner exception: CodeSpark.Apps.Common.Net.Exceptions.HttpException: net_http_message_not_success_statuscode_reason, 507, Insufficient Storage
 ---> System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode_reason, 507, Insufficient Storage
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CodeSpark.Apps.Common.Net.HttpClients.OneHttpClient.ExecuteRequest(CancellationToken cancellationToken, String url, String httpMethod, String requestContent, String authorizationHeader, Dictionary2 requestHeaders)
   Exception_EndOfInnerExceptionStack
   at CodeSpark.Apps.Common.Net.HttpClients.OneHttpClient.ExecuteRequest(CancellationToken cancellationToken, String url, String httpMethod, String requestContent, String authorizationHeader, Dictionary2 requestHeaders)
   at CodeSpark.Apps.Common.Net.WebRequests.WebRequest.ExecuteRaw(OneHttpClientFactory httpClientFactory, CancellationToken cancellationToken, XHttpClientRequirements httpClientRequirements, String url, String httpMethod, String mediaType, String requestData, String authorizationHeader, Dictionary2 requestHeaders, HttpCredential serverCredential, Boolean allowAutoRedirect, Boolean addUserAgentHeader, Encoding responseEncoding)
   at CodeSpark.Apps.Common.Net.WebRequests.ScopedWebRequest.ExecuteRaw(CancellationToken cancellationToken, XHttpClientRequirements httpClientRequirements, String url, String httpMethod, String mediaType, String requestData, String authorizationHeader, Dictionary2 requestHeaders, HttpCredential serverCredential, Boolean allowAutoRedirect, Boolean addUserAgentHeader, Encoding responseEncoding)

Stuff, [23/01/2025 09:15]
at XCalendarApp.CalDavProvider.DavBasicConnection.Request(Uri url, String httpMethod, String contentType, String requestContent, Dictionary2 requestHeaders, Int32 maxRedirects)
Inner exception: System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode_reason, 507, Insufficient Storage
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CodeSpark.Apps.Common.Net.HttpClients.OneHttpClient.ExecuteRequest(CancellationToken cancellationToken, String url, String httpMethod, String requestContent, String authorizationHeader, Dictionary2 requestHeaders)

**Comment by nouse4it** [comment]
I am using the beta version 31 beta 4 with the new updated calendar version 3.0.5
I delete my nextcloud account in One Calendar and created it again. Now the initial sync works!

**Comment by mikebakke** [comment]
@nouse4it  thanks for confirming - I'd prefer to stay on stable for this instance but may consider on my other one although as I'm AIO, not sure if that's supported.

tbh just amazed at how long Nextcloud are prepared to leave the (probably) most important collaboration app in an errored state. I suppose all the dev resource will be allocated towards AI "features" like in every other service today :-)

**Comment by poek1** [comment]
My Admin updated Nextcloud to 3.0.5 and I tested it. Delete the Account in onecalender and added as new. Can add it and get an Initial sync Error. And Error every sync i try

Bad.

**Comment by arcoast** [comment]
> I am using the beta version 31 beta 4 with the new updated calendar version 3.0.5 I delete my nextcloud account in One Calendar and created it again. Now the initial sync works!

As far as I understand it, the patch to fix will be reverted in the v31 branch, so you need to stay on beta 4 now until the fix is applied again in the v31 branch.

See this [comment above](https://github.com/nextcloud/server/issues/48678#issuecomment-2600928020) and this [PR](https://github.com/nextcloud/server/pull/49960)

**Comment by nouse4it** [comment]
> > I am using the beta version 31 beta 4 with the new updated calendar version 3.0.5 I delete my nextcloud account in One Calendar and created it again. Now the initial sync works!
> 
> [@nouse4it](https://github.com/nouse4it) As far as I understand it, the patch to fix will be reverted in the v31 branch, so you need to stay on beta 4 now until the fix is applied again in the v31 branch.
> 
> See this [comment above](https://github.com/nextcloud/server/issues/48678#issuecomment-2600928020) and this [PR](https://github.com/nextcloud/server/pull/49960)

Mhm, but this is only regarding the intial sync right? When the initial setup is done, there shouldn`t be any more problems?
Because I only ran into this whole issue because I needed to resetup my OneCalendar. 
Other users, who didn´t need to do this had the regular sync of the calendar working just fine the whole time.

I just don´t want to run a beta version, if I don´t need to anymore

**Comment by arcoast** [comment]
> > I am using the beta version 31 beta 4 with the new updated calendar version 3.0.5 I delete my nextcloud account in One Calendar and created it again. Now the initial sync works!
> 
> [@nouse4it](https://github.com/nouse4it) As far as I understand it, the patch to fix will be reverted in the v31 branch, so you need to stay on beta 4 now until the fix is applied again in the v31 branch.

I think going from v30 to v31 is a one way street, due to some database changes.  So unless you have a backup and restore you're kind of stuck on beta until v31 stable (the branch of which has a pending PR to revert the fix, but hopefully will be reimplemented before the release of v31)  It is all rather confusing...

**Comment by ChristophWurst** [comment]
Thank you @JeroenBer. This fix has priority and we have @kesselb work on this this week. If it were that simple, a fix would have landed a lot earlier. But be assured that we take this very serious.

**Comment by Razorblade12** [comment]
@ChristophWurst and @JeroenBer 
Do you have any updates on that?

**Comment by JeroenBer** [comment]
@Razorblade12 

The OneCalendar workaround is gradually being rolled out:
- Windows: fully rolled out (2025.124.1)
- iOS / macOS: tomorrow fully rolled out (5.7.1)
- Android: fully  rolled out next week (5.7.1)

So if you received a OneCalendar update with the version above (or higher) then please check and confirm if it works for you.

**Comment by mikebakke** [comment]
I just updated through Android Play Store and the synchronisation worked! Thank you, much appreciated

**Comment by poek1** [comment]
> I just updated through Android Play Store and the synchronisation worked! Thank you, much appreciated

i cant believe you, in Androis is no version 5.7.1 avaiable. Its still 5.7.0. Its still broken on my phone!

**Comment by JeroenBer** [comment]
As I said before it's rolled out gradually, that means it's not directly available for all devices but might take up to a week. So please try again in a week and it should be available. 
Or join the OneCalendar beta version where it's available for sure.

**Comment by mikebakke** [comment]
> > I just updated through Android Play Store and the synchronisation worked! Thank you, much appreciated
> 
> i cant believe you, in Androis is no version 5.7.1 avaiable. Its still 5.7.0. Its still broken on my phone!

Believe or don't believe - that's your choice. It clearly is available for me in UK

![Image](https://github.com/user-attachments/assets/b81dd553-44cb-479e-9ee4-8fc238bf9751)

**Comment by poek1** [comment]
Oh, UK first, for android updates :-) thanks for the screenshot, I am happy for you.

**Comment by vagner-dias** [comment]
Hello all. The update has arrived in Brazil. I have just updated the app in my Android to 5.7.1 and NC Calendar works perfectly now. Cheers.

**Comment by tpapp** [comment]
I have updated to OneCalendar 5.7.1 but I am still getting the error. Is there an extra step involved, eg removing the account then adding it back?

**Comment by PastCoder** [comment]
I had to remove the account from OneCalendar and to create it new. After that it worked.

**Comment by MajorP93** [comment]
I can confirm the workaround for this Nextcloud bug that OneCalendar implemented works fine.

Glad to see OneCalendar provided a solution where Nextcloud did not do so for a long time.

**Comment by VEF-Admin** [comment]
+1 from Hungary. The workaround solved the problem. No error message, calendar sync is just fine.

**Comment by poek1** [comment]
The workaround solved the problem, without resetup of the account (but i did a lot with older versions). After update to 5.7.1 the sync worked well again! Thank you so much

**Comment by MajorP93** [comment]
> Thank you [@JeroenBer](https://github.com/JeroenBer). This fix has priority and we have [@kesselb](https://github.com/kesselb) work on this this week. If it were that simple, a fix would have landed a lot earlier. But be assured that we take this very serious.

Is this prioritized fix included in the most recent stable release (v30.0.6)?
If not: for which release is it planned?

**Comment by MaggiWuerze** [comment]
@kesselb @ChristophWurst How is it looking for a february release? Not all of us usse OneCalendar...

**Comment by kesselb** [comment]
> How is it looking for a february release?

I'm afraid the patches didn't make it into the February release. However, things are looking good so far, and unless we spot any additional issues, the patches will be included in the March release. Also, the current release candidate for 31 should already include them.

> Not all of us use OneCalendar...

@MaggiWuerze Out of curiosity, which client are you using?

**Comment by kesselb** [comment]
Hi there,

The patches have been merged and will be included in the March maintenance releases, most likely on 2025-03-13.

PR for version 30: https://github.com/nextcloud/server/pull/49481 (Patch files: https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/49481.patch)

PR for version 29: https://github.com/nextcloud/server/pull/49483 (Patch file: https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/49483.patch)

Here's our guide on how to apply a patch: https://docs.nextcloud.com/server/31/admin_manual/issues/applying_patch.html#applying-a-patch

- Please remember to create a backup beforehand.
- Applying the patch will trigger the integrity check and display a warning about modified files.  
- The patch command will warn about changes in the test folders—this is expected, as we do not ship tests with the release.

**Comment by joshtrichards** [comment]
Thanks, @kesselb (along with all the reviewers), for seeing this through!

**Comment by MaggiWuerze** [comment]
@kesselb nice, thanks for your work

**Comment by Minstrel27** [comment]
I can confirm that I can now add a new user to the OneCalendar app.  This was tested in both 29.0.14 and 31.0.2.   I can't confirm if all CalDav calendars work as I only use OneCalendar.

Added bonus is that the docker hub version of NC 31.0.2 now uses PHP83
