### ISSUE TITLE
Internal Server Error when accessing shared file

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#4875]
Steps to reproduce:
1. Execute the script below, it will output the share token
2. Open `/s/[TOKEN]/download` in your browser
3. Get an 'Internal Server Error' (see log below for details)

This works fine with ownCloud 8.1.

```php
$username = 'admin';
$folder = 'uploads';
$file = 'hello.txt';
$contents = 'Hello World';

// TODO: Get IRootFolder via DI
$uploadFolder = $this->rootFolder->getUserFolder($username)
	->newFolder($folder);
$newFile = $uploadFolder->newFile($file);
$newFile->putContent($contents);

// This successfully prints out the share token
// Downloading the share via /s/[TOKEN]/download yields an Internal Server Error
echo \OCP\Share::shareItem(
	'file',
	$newFile->getId(),
	\OCP\Share::SHARE_TYPE_LINK,
	null, /* shareWith */
	\OCP\Constants::PERMISSION_READ
);
```

# Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"EivluV80pya9a20W5pfH","level":4,"time":"2017-05-15T12:20:19+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/1494850779","message":"Exception: {\"Message\":\"\",\"Exception\":\"InvalidArgumentException\",\"Code\":0,\"Trace\":\"#0 \\\/path-to-nextcloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(847): OC\\\\Share20\\\\Share->setSharedBy(NULL)\\n#1 \\\/path-to-nextcloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(503): OC\\\\Share20\\\\DefaultShareProvider->createShare(Array)\\n#2 \\\/path-to-nextcloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(911): OC\\\\Share20\\\\DefaultShareProvider->getSharesInFolder('admin', Object(OC\\\\Files\\\\Node\\\\Folder), true)\\n#3 [internal function]: OC\\\\Share20\\\\Manager->OC\\\\Share20\\\\{closure}(Array, Object(OC\\\\Share20\\\\DefaultShareProvider))\\n#4 \\\/path-to-nextcloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(920): array_reduce(Array, Object(Closure), Array)\\n#5 \\\/path-to-nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(145): OC\\\\Share20\\\\Manager->getSharesInFolder('admin', Object(OC\\\\Files\\\\Node\\\\Folder), true)\\n#6 \\\/path-to-nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(182): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->getSharesTypesInFolder(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#7 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#8 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#10 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#11 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server::getPropertiesIteratorForPath('1494850779', Array, 1)\\n#12 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#16 \\\/path-to-nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/path-to-nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/path-to-nextcloud\\\/remote.php(162): require_once('\\\/storage\\\/users\\\/...')\\n#19 {main}\",\"File\":\"\\\/path-to-nextcloud\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":292,\"User\":\"admin\"}","userAgent":"hidden","version":"12.0.0.19"}
```
</details>

**Comment by rullzer** [comment]
Don't use \OCP\Share (it still needs to die!)
use the ShareManager

`\OC::$server->getShareManager()`

**Comment by leonklingele** [comment]
@MorrisJobke why did you close this? The issue still persists and as
long as the API is still there, this bug shouldn't be closed.

BTW: I was able to work around the issue by using \OCP\Share, see
https://github.com/strukturag/nextcloud-spreedme/blob/v0.3.11/controller/filesharingcontroller.php#L117-L150

**Comment by MorrisJobke** [comment]
> @MorrisJobke why did you close this?

I thought it is closed.

**Comment by skjnldsv** [comment]
Well, closing as outdated
