### ISSUE TITLE
"Hide download" in public shares is no longer "hide download" but "prevent download" in Nextcloud 31

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#48954]
Since the migration of public shares to Vue [enabling _Hide download_ also removes the download permissions](https://github.com/nextcloud/server/commit/1d16bc47ffe7fbbf3f98a773612df6cdfa56f7de#diff-dbbe017dd357504abc442a6f1d0305166520ebf80353f42814b3f879a3e241bc). But a hidden download is not the same as a disabled download; a hidden download does not disable the download, but simply removes the option from the UI (as some of the viewer apps (like the PDF viewer) need to actually download the file to be able to show it).

Note that just updating to Nextcloud 31 will not change the behaviour of existing shares. However, any share then marked as _Hide download_ will behave as _Prevent download_.

If that new behaviour is intended then at least it should be documented to avoid surprises (some file types no longer viewable in public shares if download is hidden) for users coming from previous versions :-)

Related:
- https://github.com/nextcloud/server/issues/46256
- https://github.com/nextcloud/server/issues/45412

**Comment by sorbaugh** [comment]
@marcoambrosini @nfebe is this intended?

**Comment by chotaire** [comment]
Well, for me "Hide Download" doesn't work at all in Nextcloud 31.0.0 (Docker), but it worked fine in previous versions. 

When Hide Download is checked, all existing and new external shares will show the download button, both from the overlay (single files) and also when closing the overlay and being presented the folder (why has this been changed? this is only confusing for the user when being shared a single file). 

Hide Download also doesn't work for existing and new external shares of folders.

**Comment by marcoambrosini** [comment]
In my opinion hide download should not prevent download, and one should still be able to open files with the browser

**Comment by PeopleInside** [comment]
I upgraded to NextCloud 31 and now I'm unable to share video hiding the download button.
Will be cool have NextCloud forbid download and not only hide the button but as is now is no more working.
I share a video then I want disable the download and cannot do because the video never play.
An example for the next 30 days: https://mbcloud.peopleinside.it/nxtc/index.php/s/sRMM3ParPSwHJcd

[I reported](https://github.com/nextcloud/server/issues/51938#event-17131710959) this as soon I upgraded to the stable 31.
I hope a fix will come and I hope to see an improvement where video can play without be allowed to download.

**Comment by MarkusGasser2** [comment]
Ich verwende NextCloud 31.0.2.
Das Thema «Download» für öffentliche Links scheint total nicht mehr richtig zu funktionieren. 
Die Option «downloade verbergen» hat überhaupt keine Wirkung, und Download wird für den  Empfänger immer noch angezeigt, auch wenn verbergen ausgewählt wurde. Klickt einer dann auf nun doch sichtbaren «Download» Button, oder auf «Direktlink», kommt er eine Fehlermeldung, dass man keinen Zugriff habe und kommt nur noch raus, wenn man im Browser zurück geht.  So ist das natürlich für Leute, mit welchen man etwas teilt, keine gute Lösung, dann oft sind das Leute, welche selber kein NextCloud haben, es nicht einmal kennen.

**Comment by riczorn** [comment]
I can confirm the issue remains on 31.0.3.

The browser makes a  request to the server for the file i.e. `/public.php/dav/files/44d8cBBCGTk3K8H/:1`  which returns a 403 error. There are no traces in the server error logs. 

in the browser console there is a wrong `nonce` error (see the console contents below), but it may be unrelated as the same error appears when a video is shared without ticking "Hide download".

I tried removing the *Hide download* flag from the share to see if it worked, and I could not: I just click on the *Hide download* checkbox, it is not toggled, and a notice appears that the 'hide-download' status was saved (so once it's enabled, it remains enabled).


Copy of the console showing the `nonce` error
```
index.mjs:51 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config Object
log @ index.mjs:51
index.mjs:48 [INFO] viewer: 5 viewer handlers registered Object
session-heartbeat.js:83 session heartbeat polling started
index.mjs:54 [ERROR] Files_PDFViewer: But this does not appear to be a public page Object
log @ index.mjs:54
ServiceWorker.js:22 Refused to create a worker from 'https://cloud.example.com/index.php/apps/files/preview-service-worker.js' because it violates the following Content Security Policy directive: "script-src 'nonce-TyDllvNF7ac25XWQ8dD3xV5EGquEG5svmWvhzfe2NNo='". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ ServiceWorker.js:22
index.mjs:54 [ERROR] files: SW registration failed:  Object
log @ index.mjs:54
index.mjs:48 [INFO] viewer: Opening viewer for file  Object
44d8cBBCGTk3K8H:1 
            
            
           Failed to load resource: the server responded with a status of 403 (Forbidden)
/public.php/dav/files/44d8cBBCGTk3K8H/:1 
            
            
           Failed to load resource: the server responded with a status of 403 (Forbidden)
Videos.vue:181 Loading of file / failed, falling back to fetching it by hand
onFail @ Videos.vue:181
/public.php/dav/files/44d8cBBCGTk3K8H/:1 
            
            
           Failed to load resource: the server responded with a status of 403 (Forbidden)
/public.php/dav/files/44d8cBBCGTk3K8H/:1 
            
            
           Failed to load resource: the server responded with a status of 403 (Forbidden)
vue-async-computed.esm.js:194 Error evaluating async computed property: Error: Invalid response: 403 Forbidden
    at Rl (https://cloud.example.com/apps/viewer/js/logger-CSHmak5d.chunk.mjs:14:2474)
    at Pe (https://cloud.example.com/apps/viewer/js/logger-CSHmak5d.chunk.mjs:14:2714)
    at https://cloud.example.com/apps/viewer/js/logger-CSHmak5d.chunk.mjs:14:13324
    at async No (https://cloud.example.com/apps/viewer/js/viewer-init.mjs?v=adb124fd-11:4787:1173)
(anonymous) @ vue-async-computed.esm.js:194
```

**Comment by MarkusGasser2** [comment]
I can also confirm that version 31.0.3 is still involved. 

If the “Hide download” is enabled, it is not only not possible to download, it is also no longer possible to display any files in the browser. 
That is not the idea behind this function.
Hide download should only be used to ensure that no document can be downloaded and at the same time hide the download Button.

**Comment by susnux** [comment]
> Hide download should only be used to ensure that no document can be downloaded

Which it is doing: Showing in the browser will download the document, thats why it can only be viewed with Collabora because that is not downloading the document to the browser but uses some visualization that only will download some graphical representation of it.

But we are already working on bringing back the old behavior.

**Comment by PeopleInside** [comment]
> But we are already working on bringing back the old behavior.
I hope in the future the download can also be blocked.

For now let's wait a fix as I need completely hide with a CSS the many downloads button after the latest update

**Comment by boneycursor** [comment]
> But we are already working on bringing back the old behavior.

Yes please! Thanks for working on this, this is core functionality for us. We often want to share videos to preview while 'discouraging' downloading. It's fine if 'prevent download' is not bulletproof (as long as 'delete' is!).

**Comment by MarkusGasser2** [comment]
@boneycursor
That's exactly how I see it. If you can't even look at the documents in the browser because you're not allowed to download them, the share is useless anyway.
For the normal user, it is sufficient to simply hide the download link and button if you don't want the documents to be so easy to download.
If you don't want to be able to download the documents at all, don't share your documents or set a password so that only those who have access to them can do so.

**Comment by henmohr** [comment]
Hello. Can confirm that in version 31.0.4 (updated version) it still occurs.

In a fresh version 30 it doesn't occur.

**Comment by nfebe** [comment]
> Hello. Can confirm that in version 31.0.4 (updated version) it still occurs.
> 
> In a fresh version 30 it doesn't occur.

Hello @henmohr That should be because https://github.com/nextcloud/server/pull/52226 has not been merged.

Cc: @susnux

**Comment by infocillasas** [comment]
Hi,
Would it be possible to extend the "Hide Download" functionnality to internal shares ?
