### ISSUE TITLE
[Bug]: webdav 404 shows "Internal Server Error" as response

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#49002]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

PROPFIND on latest master shows 404, but "Internal Server Error" as content.

### Steps to reproduce

1. PROPFIND to a non-existing file
2. curl --request PROPFIND --url http://localhost/nc/remote.php/dav/files/tobi/eaea
3. see
```
<?xml version="1.0" encoding="utf-8"?>
<d:error
	xmlns:d="DAV:"
	xmlns:s="http://sabredav.org/ns">
	<s:exception>Internal Server Error</s:exception>
	<s:message>
		The server was unable to complete your request.		If this happens again, please send the technical details below to the server administrator.		More details can be found in the server log.			</s:message>
	<s:technical-details>
		<s:remote-address>127.0.0.1</s:remote-address>
		<s:request-id>22m49CndhYZvWBAIq8cr</s:request-id>
		<s:type>Sabre\DAV\Exception\NotFound</s:type>
		<s:code>0</s:code>
		<s:message>File with name //eaea could not be located</s:message>
		<s:file>/srv/http/nc/apps/dav/lib/Connector/Sabre/Directory.php</s:file>
		<s:line>188</s:line>
		<s:stacktrace>
			#0 /srv/http/nc/3rdparty/sabre/dav/lib/DAV/Tree.php(95): OCA\DAV\Connector\Sabre\Directory-&gt;getChild(&#039;eaea&#039;)
#1 /srv/http/nc/3rdparty/sabre/dav/lib/DAV/Server.php(971): Sabre\DAV\Tree-&gt;getNodeForPath(&#039;files/tobi/eaea&#039;)
#2 /srv/http/nc/3rdparty/sabre/dav/lib/DAV/Server.php(1662): Sabre\DAV\Server-&gt;getPropertiesIteratorForPath(&#039;files/tobi/eaea&#039;, Array, 1)
#3 /srv/http/nc/3rdparty/sabre/dav/lib/DAV/Server.php(1647): Sabre\DAV\Server-&gt;writeMultiStatus(Object(Sabre\Xml\Writer), Object(Generator), false)
#4 /srv/http/nc/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(346): Sabre\DAV\Server-&gt;generateMultiStatus(Object(Generator), false)
#5 /srv/http/nc/3rdparty/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin-&gt;httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /srv/http/nc/3rdparty/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server-&gt;emit(&#039;method:PROPFIND&#039;, Array)
#7 /srv/http/nc/apps/dav/lib/Connector/Sabre/Server.php(43): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#8 /srv/http/nc/apps/dav/lib/Server.php(380): OCA\DAV\Connector\Sabre\Server-&gt;start()
#9 /srv/http/nc/apps/dav/appinfo/v2/remote.php(19): OCA\DAV\Server-&gt;exec()
#10 /srv/http/nc/remote.php(145): require_once(&#039;/srv/http/nc/ap...&#039;)
#11 {main}		</s:stacktrace>
	</s:technical-details>
</d:error>
```

### Expected behavior

Correct error message:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error
	xmlns:d="DAV:"
	xmlns:s="http://sabredav.org/ns">
	<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
	<s:message>File with name //eaea could not be located</s:message>
</d:error>
```

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Resolved via 


- https://github.com/nextcloud/server/pull/49004 / https://github.com/nextcloud/server/pull/50498
- https://github.com/nextcloud/server/pull/49481
- https://github.com/nextcloud/server/pull/49483
- https://github.com/nextcloud/server/pull/49482
