### ISSUE TITLE
[Bug]: Flow "write to a conversation" broken.

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#49909]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I tried to setup a flow to write to a talk room whenever a file in a certain folder gets added/edited.

### Steps to reproduce

1. tried in c.nc.com
2. setup this flow:

![Image](https://github.com/user-attachments/assets/d1b394a2-1de3-4591-adfc-4493a1f6fe7d)

### Expected behavior

I can setup the flow but instead I get the error you see on the screenshot 

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json
Browser log:

`{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Cannot decode operation details"},"data":[]}}`
```

**Comment by RTechSn** [comment]
I confirm.

**Comment by RTechSn** [comment]
Here's some error from JS console:

<details>
```

store.js:42 TypeError: Cannot read properties of null (reading 'proxy')
    at w (useModelMigration-EhAWvqDD.mjs:3:33)
    at setup (NcSelect-DvGJHzaa.mjs:389:19)
    at hn (vue.runtime.esm.js:3033:30)
    at vue.runtime.esm.js:2457:27
    at vue.runtime.esm.js:5385:5
    at e._init (vue.runtime.esm.js:5714:9)
    at new o (vue.runtime.esm.js:5849:18)
    at vue.runtime.esm.js:4564:12
    at init (vue.runtime.esm.js:4426:52)
    at vue.runtime.esm.js:6591:17
	
store.js:107 
        
        
POST https://nextcloud.....com/ocs/v2.php/apps/workflowengine/api/v1/workflows/user?format=json 400 (Bad Request)
(anonymous) @ xhr.js:195
xhr @ xhr.js:15
p @ dispatchRequest.js:51
_request @ Axios.js:173
request @ Axios.js:40
(anonymous) @ Axios.js:212
(anonymous) @ bind.js:5
pushUpdateRule @ store.js:107
await in pushUpdateRule (async)
(anonymous) @ vuex.esm.js:851
f.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
saveRule @ Rule.vue:149
hn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
hn @ vue.runtime.esm.js:3033
e.$emit @ vue.runtime.esm.js:3732
click @ NcButton.mjs:232
hn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
Pr.i._wrapper @ vue.runtime.esm.js:7500
Show 18 more frames
Show less
Rule.vue:154 Failed to save operation
```

</details>

**Comment by Antreesy** [comment]
This affects any workflows. Probably caused by https://github.com/nextcloud-libraries/nextcloud-vue/pull/6172, as passed components can not grasp Vue instance of parent, therefore `getCurrentInstance` returns null.

Maybe it could be fixed in https://github.com/nextcloud/server/blob/f21ffabe0e92c1790262c07d51eb2a60f55796f2/apps/workflowengine/src/workflowengine.js ? cc @ShGKme @susnux

**Comment by blizzz** [comment]
And so also related to https://github.com/nextcloud-libraries/nextcloud-vue/issues/6360

**Comment by mammique** [comment]
I'm having this problem too, I confirm, NC-AIO latest update.

**Comment by blizzz** [comment]
@mammique are you running NC 30.0.9 or 31.0.3 and Talk (spreed) 21.0.2 or 20.1.6?

**Comment by mammique** [comment]
> [@mammique](https://github.com/mammique) are you running NC 30.0.9 or 31.0.3 and Talk (spreed) 21.0.2 or 20.1.6?

Hello, thank you for your reply, it' 30.0.8 and 20.1.6, AIO says it's up to date.

![Image](https://github.com/user-attachments/assets/59b431ef-a712-4201-9f3e-b8c3d6e9ce05)

**Comment by blizzz** [comment]
Closing as fixed in https://github.com/nextcloud/server/pull/50783 and https://github.com/nextcloud/spreed/pull/14367

**Comment by mammique** [comment]
> [@mammique](https://github.com/mammique) then AIO needs a release, as the version i mentioned contain the fix.
> 
> Another out-of-band release is expected soonish, maybe AIO waits for that.

Thanks!
