### ISSUE TITLE
Update fails with OAuth2 app

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#5024]
Upgrade testinstance from Beta 3 to final 12.0.0 this morning.

Running php 5.6 on localhost using the built in PHP webserver ("php -S localhost:2000")

Tried to upgrade a few times:
```
{"reqId":"ubWSCZph1GJiADrMwyEW","level":3,"time":"2017-05-22T06:48:10+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=kf%2BRJ9imsB8%2FdLpI%2BnT4%2FH04WgN5ydbzsUCnoNJUWZQ%3D%3A0J3hdI%2FW6il0Bf87jwyNiBNPLlQ7kJqR9TDlxLobLfE%3D","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"oauth2 can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(433): OC\\\\App\\\\AppManager->disableApp('oauth2')\\n#1 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(433): OC_App::disable('oauth2')\\n#2 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(263): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(130): OC\\\\Updater->doUpgrade('12.0.0.28', '12.0.0.20')\\n#4 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/core\\\/ajax\\\/update.php(206): OC\\\\Updater->upgrade()\\n#5 {main}\",\"File\":\"\\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":279}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.20"}
{"reqId":"ubWSCZph1GJiADrMwyEW","level":3,"time":"2017-05-22T06:48:10+00:00","remoteAddr":"::1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=kf%2BRJ9imsB8%2FdLpI%2BnT4%2FH04WgN5ydbzsUCnoNJUWZQ%3D%3A0J3hdI%2FW6il0Bf87jwyNiBNPLlQ7kJqR9TDlxLobLfE%3D","message":"\\OC\\Updater::failure: Exception: oauth2 can't be disabled.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.20"}
{"reqId":"zBH3hMxfc8QENWGrhGgY","level":3,"time":"2017-05-22T06:48:26+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=c1obDbdyOh0KonMV2DGurSncLEcq6%2B6Oxoeu965pI7c%3D%3AMjhrXuACYCtB0zZmrUnb2UerWBBosqLsgvfsk8YmV9I%3D","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"oauth2 can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(433): OC\\\\App\\\\AppManager->disableApp('oauth2')\\n#1 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(433): OC_App::disable('oauth2')\\n#2 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(263): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(130): OC\\\\Updater->doUpgrade('12.0.0.28', '12.0.0.20')\\n#4 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/core\\\/ajax\\\/update.php(206): OC\\\\Updater->upgrade()\\n#5 {main}\",\"File\":\"\\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":279}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.20"}
{"reqId":"zBH3hMxfc8QENWGrhGgY","level":3,"time":"2017-05-22T06:48:26+00:00","remoteAddr":"::1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=c1obDbdyOh0KonMV2DGurSncLEcq6%2B6Oxoeu965pI7c%3D%3AMjhrXuACYCtB0zZmrUnb2UerWBBosqLsgvfsk8YmV9I%3D","message":"\\OC\\Updater::failure: Exception: oauth2 can't be disabled.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.20"}
{"reqId":"60nsVy1PPouniMHGPOyn","level":3,"time":"2017-05-22T06:48:48+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=HxzYEAYMVMbE59Z20JacatiYLi4q4%2BDQMnGlbjEUkYw%3D%3AXn6oQ1F8DvCPlpMFpe7pHrbvWnlouqyydgHnCllb5ek%3D","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"oauth2 can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(433): OC\\\\App\\\\AppManager->disableApp('oauth2')\\n#1 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(433): OC_App::disable('oauth2')\\n#2 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(263): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(130): OC\\\\Updater->doUpgrade('12.0.0.28', '12.0.0.20')\\n#4 \\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/core\\\/ajax\\\/update.php(206): OC\\\\Updater->upgrade()\\n#5 {main}\",\"File\":\"\\\/home\\\/jospoortvliet\\\/source\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":279}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.20"}
{"reqId":"60nsVy1PPouniMHGPOyn","level":3,"time":"2017-05-22T06:48:48+00:00","remoteAddr":"::1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=HxzYEAYMVMbE59Z20JacatiYLi4q4%2BDQMnGlbjEUkYw%3D%3AXn6oQ1F8DvCPlpMFpe7pHrbvWnlouqyydgHnCllb5ek%3D","message":"\\OC\\Updater::failure: Exception: oauth2 can't be disabled.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","version":"12.0.0.20"}
```

App shows 'true':
```
08:54:54 jospoortvliet@jos-desktop:~/source/nextcloud/>php occ app:list
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: true
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - spreed: 2.0.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - bruteforcesettings
  - calendar
  - contacts
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
```

```
08:54:57 jospoortvliet@jos-desktop:~/source/nextcloud/>php occ app:disable oauth2
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
oauth2 can't be disabled.```

**Comment by JSoko** [comment]
See also https://help.nextcloud.com/t/upgrade-to-v12-0-0-fails-oauth2-cant-be-disabled/12846/7

**Comment by jospoortvliet** [comment]
@JSoko aw no t-shirt for me then, I'm not the first to report ;-)

**Comment by JSoko** [comment]
@jospoortvliet 
There are so many reasons for YOUR t-shirt...
...so you should send you one ;-)

**Comment by JSoko** [comment]
Btw: Updating 11.03 -> RC412.0.26 -> 12.0.027 -> 12.0.28 worked for me without this issue...

**Comment by jospoortvliet** [comment]
Add this to info.xml:
```
<dependencies>
	<nextcloud min-version="12" max-version="12" />
</dependencies>
```

Then run ```php occ app:enable oauth2```
Then run ```php occ upgrade```
and it works.
