### ISSUE TITLE
Nextcloud iOS app - External storage request timed out or slow connection

### ISSUE THREAD

**Issue by hddmet** [nextcloud/server#5037]
### Steps to reproduce
1. Add external SMB shared storage
2. Open the Nextcloud iOS app
3. Browse the SMB shared files

### Expected behaviour
The SMB shared should behave just like the normal files

### Actual behaviour
The app try connecting to SMB in the background.  Most of the time it will timeout.  Web app works perfectly but the iOS failed.

### Server configuration

**Operating system**:
FreeNAS
**Web server:**
nginx
**Database:**
MariaDB
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
FreeBSD package

**Signing status:**
<details>
<summary>Signing status</summary>
success
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "ocnk5ka6pmkt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.3.32",
            "nextcloud.delite.ca",
            "10.5.0.32"
        ],
        "datadirectory": "\/usr\/local\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.3.32",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "10.5.0.98",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Active Directory
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

+-------------------------------+-------------------------------------------------+
| Configuration                 |                                                 |
+-------------------------------+-------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                               |
| hasPagedResultSupport         |                                                 |
| homeFolderNamingRule          |                                                 |
| lastJpegPhotoLookup           | 0                                               |
| ldapAgentName                 | CN=ldapbind, CN=Users, DC=delite, DC=ca         |
| ldapAgentPassword             | ***                                             |
| ldapAttributesForGroupSearch  |                                                 |
| ldapAttributesForUserSearch   |                                                 |
| ldapBackupHost                |                                                 |
| ldapBackupPort                |                                                 |
| ldapBase                      | OU=Delite Users,DC=delite, DC=ca                |
| ldapBaseGroups                | OU=Delite Users, DC=delite, DC=ca               |
| ldapBaseUsers                 | OU=Delite Users, DC=delite, DC=ca               |
| ldapCacheTTL                  | 600                                             |
| ldapConfigurationActive       | 1                                               |
| ldapDynamicGroupMemberURL     |                                                 |
| ldapEmailAttribute            |                                                 |
| ldapExperiencedAdmin          | 0                                               |
| ldapExpertUUIDGroupAttr       |                                                 |
| ldapExpertUUIDUserAttr        |                                                 |
| ldapExpertUsernameAttr        |                                                 |
| ldapGroupDisplayName          | cn                                              |
| ldapGroupFilter               |                                                 |
| ldapGroupFilterGroups         |                                                 |
| ldapGroupFilterMode           | 0                                               |
| ldapGroupFilterObjectclass    |                                                 |
| ldapGroupMemberAssocAttr      | uniqueMember                                    |
| ldapHost                      | 192.168.3.20                                    |
| ldapIgnoreNamingRules         |                                                 |
| ldapLoginFilter               | (&(|(objectclass=person))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                 |
| ldapLoginFilterEmail          | 0                                               |
| ldapLoginFilterMode           | 0                                               |
| ldapLoginFilterUsername       | 1                                               |
| ldapNestedGroups              | 0                                               |
| ldapOverrideMainServer        |                                                 |
| ldapPagingSize                | 500                                             |
| ldapPort                      | 389                                             |
| ldapQuotaAttribute            |                                                 |
| ldapQuotaDefault              |                                                 |
| ldapTLS                       | 0                                               |
| ldapUserDisplayName           | displayName                                     |
| ldapUserDisplayName2          |                                                 |
| ldapUserFilter                | (|(objectclass=person))                         |
| ldapUserFilterGroups          |                                                 |
| ldapUserFilterMode            | 0                                               |
| ldapUserFilterObjectclass     | person                                          |
| ldapUuidGroupAttribute        | auto                                            |
| ldapUuidUserAttribute         | auto                                            |
| turnOffCertCheck              | 0                                               |
| turnOnPasswordChange          | 0                                               |
| useMemberOfToDetectMembership | 1                                               |
+-------------------------------+-------------------------------------------------+

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>
</summary>

```
{"reqId":"EWE20if8WTd2rCG2wUOT","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:42:43+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"sgT1udMBk8BVOjG+GFln","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:42:43+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"4+k1iRFFepBmuvMa8x9r","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:43:43+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"\/FnO5LGPxc76PM00he4p","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:43:44+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"OplqSIsm9f8JTQphwaxr","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:43:45+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"w60JqdudvvozMtVy\/R+R","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:43:46+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"Vwre0Mpf07\/lWi+dmNqr","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:45:11+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"+vjdhIVC2R58IGPOeQRm","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:45:11+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"1uj4c7I3xflQbBIm0DCZ","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:49:08+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"+xNqi7OhTx658fCnrLjo","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T06:49:08+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"E725B3F1-900A-41AD-A368-99056E4A2779","version":"11.0.2.7"}
{"reqId":"LsfE11hRB3AmLKRApoSx","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:16:14+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"admin","version":"11.0.2.7"}
{"reqId":"qzekLr\/QSkkkyDTYIEXt","remoteAddr":"192.168.3.88","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('SFTP\\\/My Picture...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1143,\"User\":\"74E15BA9-4C34-4497-93DD-E436C0F2FFBA\"}","level":4,"time":"2017-05-22T13:16:30+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/SFTP\/My%20Pictures","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"Jo2hOdBNaF1kUSYyD7z\/","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:18:58+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"admin","version":"11.0.2.7"}
{"reqId":"HuUnR7e+NJ8vpewk4P\/Z","remoteAddr":"192.168.3.88","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('SFTP\\\/My Picture...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1143,\"User\":\"74E15BA9-4C34-4497-93DD-E436C0F2FFBA\"}","level":4,"time":"2017-05-22T13:19:22+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/SFTP\/My%20Pictures","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"HLBAuLM6C+eDtpDFTyuz","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:19:41+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"xci+lhAuIlUWJws3RzqC","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:20:40+00:00","method":"POST","url":"\/heartbeat","user":"--","version":"11.0.2.7"}
{"reqId":"TE9oMW8luMhz8B64PTjF","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:21:15+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"vjirHn79\/Z2Gko06pkYr","remoteAddr":"192.168.3.88","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('SFTP\\\/My Picture...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1143,\"User\":\"74E15BA9-4C34-4497-93DD-E436C0F2FFBA\"}","level":4,"time":"2017-05-22T13:26:07+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/SFTP\/My%20Pictures","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"OJ5CUU\/kABtamNFc9KpZ","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:29:15+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"eSUHpgwtEAAJcu4SFc8M","remoteAddr":"192.168.3.88","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('SFTP\\\/My Picture...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1143,\"User\":\"74E15BA9-4C34-4497-93DD-E436C0F2FFBA\"}","level":4,"time":"2017-05-22T13:30:53+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/SFTP\/My%20Pictures","user":"74E15BA9-4C34-4497-93DD-E436C0F2FFBA","version":"11.0.2.7"}
{"reqId":"Wb+440HW0TyVnKJfuoTp","remoteAddr":"192.168.3.88","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-05-22T13:38:11+00:00","method":"POST","url":"\/index.php\/apps\/nextant\/ajax\/search_options.php","user":"admin","version":"11.0.2.7"}```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by hddmet** [comment]
Issue submitted to Nextcloud iOS repo
