### ISSUE TITLE
CalDAV: Support calendar sharing via MacOS Calendar.app

### ISSUE THREAD

**Issue by rumkol** [nextcloud/server#5050]
Currently, trying to share a calendar using the MacOS Calendar.app produce the following error:

"user":"ncadmin","app":"webdav","method":"POST","url":"\/remote.php\/dav\/calendars\/ncadmin\/3F283E41-2239-452D-BE13-382E6CBB282F\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no plugin in the system that was willing to handle this POST method.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotImplemented\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nc12\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nc12\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www\\\/nc12\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#3 \\\/var\\\/www\\\/nc12\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nc12\\\/a...')\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/nc12\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":487,\"User\":\"ncadmin\"}","userAgent":"Mac+OS+X\/10.12.5 (16F73) CalendarAgent\/386","version":"12.0.0.29"}

SabreDAV already support this->[http://sabre.io/blog/2016/sharing-changes/](http://sabre.io/blog/2016/sharing-changes/) and would be nice to see this implemented into NC.

**Comment by MorrisJobke** [comment]
cc @rullzer @georgehrke

**Comment by Inseeker** [comment]
I am having the same issue.
### The iCal error message:
    The server responded with an error.
    The request for account “xxx” failed.
    The server responded with“501”to operation CalDAVUpdateShareesQueuableOperation.

**Comment by BKapelari** [comment]
I am having the same issue. 

Der Server meldet Fehler
Die Anfrage für „Account „XXX““ ist fehlgeschlagen.

Antwort des Servers
„501“
an Vorgang CalDAVUpdateShareesQueuableOperation.

**Comment by georgehrke** [comment]
@BKapelari 
Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by szaimen** [comment]
Do you still want to implement this? If no, please close this issue. Thanks!

**Comment by rumxxx** [comment]
@szaimen Yes, please.

**Comment by szaimen** [comment]
So I suppose calendar sharing still doesn't work with the macOS calendar and NC21.0.2?

**Comment by ChristophWurst** [comment]
Also see https://github.com/nextcloud/server/issues/26668 for a related ticket about how sharing is handled now vs how it could be handled instead.

**Comment by mrzool** [comment]
Just adding some detail from my testing: this issue is particularly disrupting, as the error posted above by @Inseeker seems to persists even after unsharing the calendar or restarting Calendar.app.

As soon as a calendar gets shared using the built-in dialog in Calendar.app there's no way to get rid of the warning sign in the sidebar nor of the error messages popping up at regular intervals. You're pretty much stuck with a broken calendar.

<img width="222" alt="Screen Shot 2021-08-23 at 21 37 32" src="https://user-images.githubusercontent.com/6874363/130509004-d0e86de2-2d92-4859-a9e4-d2830fa7efa1.png">
<img width="372" alt="Screen Shot 2021-08-23 at 21 37 37" src="https://user-images.githubusercontent.com/6874363/130509086-1f0a3424-7e69-4426-9dfd-239b14ccf6b6.png">

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pulls?q=is%3Apr+is%3Aclosed+milestone%3A%22Nextcloud+26%22+label%3Abug vs https://github.com/nextcloud/server/pulls?q=is%3Apr+is%3Aclosed+milestone%3A%22Nextcloud+26%22+label%3Aenhancement

:v:
