### ISSUE TITLE
NC 12.0.0 - storage with mount id XX is not available

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#5153]
## Expected behavior
External WebDAV shares should always be available when they're accessed using e.g. the Nextcloud Android app.

## Current behavior
If an external WebDAV share is accessed via the Android Nextcloud app, the loading of the content lasts
very long and very often the message `Storage with mount id XX is not available` is displayed. If the
share is accessed via the WebGUI the content of the WebDAV share is instantly displayed and no exception is logged at all.

Here the relevant part of the log:
```
{"reqId":"aIeKqaYcCAo616YKYeeq","level":3,"time":"2017-05-28 20:14:33+02:00","remoteAddr":"192.168.1.67","user":"juergen","app":"no app in context","method":"GET","url":"\/nextcloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares?path=%2FMusik_Familie%2F&reshares=true&subfiles=true","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Storage with mount id 68 is not available\",\"Code\":1,\"Trace\":\"
#0 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(522): OC\\\\Files\\\\Storage\\\\FailedStorage->getAvailability()\\n
#1 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(64): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getAvailability()\\n
#2 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(75): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->isAvailable()\\n
#3 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(393): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->checkAvailability()\\n
#4 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(374): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->hasUpdated('', NULL)\\n
#5 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(374): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', NULL)\\n
#6 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Watcher.php(126): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', NULL)\\n
#7 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1314): OC\\\\Files\\\\Cache\\\\Watcher->needsUpdate('', Object(OC\\\\Files\\\\Cache\\\\CacheEntry))\\n
#8 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1352): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), '', '\\\/juergen\\\/files\\\/...')\\n
#9 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(196): OC\\\\Files\\\\View->getFileInfo('\\\/juergen\\\/files\\\/...')\\n
#10 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(133): OC\\\\Files\\\\Node\\\\Root->get('\\\/juergen\\\/files\\\/...')\\n
#11 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareAPIController.php(588): OC\\\\Files\\\\Node\\\\Folder->get('\\\/Musik_Familie\\\/')\\n
#12 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController->getShares('false', 'true', 'true', '\\\/Musik_Familie\\\/', 'false')\\n
#13 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n
#14 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController), 'getShares')\\n
#15 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController), 'getShares')\\n
#16 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ShareAPIControl...', 'getShares', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n
#18 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n
#19 \\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/ocs\\\/v1.php(77): OC\\\\Route\\\\Router->match('\\\/ocsapp\\\/apps\\\/fi...')\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/FailedStorage.php\",\"Line\":207}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/1.4.3","version":"12.0.0.29"}
```
### Steps to reproduce
1. Open the Android Nextcloud app.
2. Access a mounted WebDAV share.

#### Server Configuration
OS: Linux 3.16.42
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.29
Nextcloud version: 12.0.0
Nextcloud Android app version: 1.4.3

#### Client Configuration
Browser: Mozilla Firefox 53.0.3
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991 because the stack trace contains filesystem and sharing related stuff

**Comment by j-ed** [comment]
I want to mention that the problems seems to be solved with https://github.com/nextcloud/android/issues/468. Since I'm using the given app version I'm now able to access all files again. I cannot tell you how this fits together but before you spend to much time searching for a solution of this issue ...

**Comment by icewind1991** [comment]
Closing this one for now since it seems to be fixed on the android side
