### ISSUE TITLE
Cannot update file received via federation which has been changed in the webclient after trying to upload it with the desktop client.

### ISSUE THREAD

**Issue by Bubu** [nextcloud/server#5182]
This has been happenig at least since NC 10. But it's very annoying to report as it involves 2 NC instances and the desktop client. (Took me an hour to collect all this stuff...)
Interesting information should be inside nextcloud.log, browser log and probably the sync client log.

### Steps to reproduce
1. Receive a federated share with write permissions
2. Have it synchronized with the desktop client
3. The share owner makes an edit to the file
4. Make an edit to the file on your desktop computer, the sync client tries to upload the file -> Conflict file and error message, s below
5. Try to edit the file on the receiving end in the webclient.

### Expected behaviour
The file gets saved and updated normally.

### Actual behaviour
Get the following messages when saving the file:
```
Cannot save file as it has been modified since opening
```
```
There was a problem saving your changes. Click to resume editing.
```
Also when updating the file from the client the error message in the log is the following:
```
#=#=#=# Syncrun started 2017-05-30T22:29:18  
#=#=#=#=# Propagation starts 2017-05-30T22:29:19 (last step: 1030 msec, total: 1030 msec) 
||test.txt|INST_SYNC|Up|1496176114|592dd5ac1d7c2|85|00040383ocdp8h4ezfnn|3|Error transferring https://SAHRE-RECEIVER/remote.php/dav/files/m.hoffmann/test.txt - server replied: Precondition failed (An If-Match header was specified, but none of the specified the ETags matched.)|412|75|1496176044|592dd5ac1d7c2|    00040383ocdp8h4ezfnn|INST_NONE| 
#=#=#=# Syncrun finished 2017-05-30T22:29:19 (last step: 432 msec, total: 1462 msec)
```

### Server configuration

**Operating system**: Sharer: archlinux, Sharee: Debian 8

**Web server:** Sharer: apache 2.4.25-3, Sharee: 2.4.10-10+deb8u8 behind nginx proxy 1.10.3

**Database:** Sharer: mariadb 10.1.23-2, Sharee: mysql-server 5.5.55-0+deb8u1

**PHP version:** Sharer: 7.1.5-1, Sharee: 5.6.30+dfsg-0+deb8u1

**Nextcloud version:** Both 12.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Sharer from owncloud 8.2,9.0,9.1,NC 10, NC 11, NC12; Sharee from NC 10, NC 11

**Where did you install Nextcloud from:** archlinux: community/nextcloud, debian manually form release zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

Sharer:
```
{
    "system": {
        "instanceid": "oc5rziive344",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.bubu1.eu"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "dsg988-nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "nextcloud",
        "mail_domain": "xxxxxxxx",
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "xxxxxxxxxxxx"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "3"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "global_cache_gc_lastrun": "1436526299",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1432254332.3603",
            "lastcron": "1496177283",
            "lastupdateResult": "[]",
            "lastupdatedat": "1496098804",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "baf89d41b4d3584c6266a9d58b5ff8dc",
            "shareapi_allow_public_upload": "yes",
            "shareapi_allow_resharing": "no",
            "shareapi_enforce_links_password": "no",
            "umgmt_show_email": "true",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_external": {
            "\/extra": "1445604588",
            "\/extra2": "1445604570",
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "01111",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "calendar": "1.5.3",
            "contacts": "1.5.3",
            "core": "12.0.0.29",
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}
```
Sharee:
```
{
    "system": {
        "instanceid": "ocdp8h4ezfnn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx"
        ],
        "datadirectory": "\/srv\/nextcloud-data",
        "skeletondirectory": "",
        "overwrite.cli.url": "xxxxx",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud_akdsfh",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "10.0.3.1",
        "mail_smtpport": "25",
        "mail_from_address": "xxxx",
        "mail_domain": "xxxx",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "1"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "installedat": "1475183312.9459",
            "lastcron": "1496171703",
            "lastupdateResult": "[]",
            "lastupdatedat": "1496169699",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "073180797d04c2845cb6de79572add0c",
            "umgmt_send_email": "true",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "updater.secret.created": "1496159557",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "00111",
            "ocsid": "170871",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceUpperLowerCase": "0",
            "installed_version": "1.2.2",
            "minLength": "8",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "types": ""
        },
        "theming": {
            "backgroundMime": "backgroundColor",
            "cachebuster": "22",
            "color": "#7A7A7A",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "name": "CTS Cloud",
            "slogan": "CarTelSol Nextcloud.",
            "types": "logging",
            "url": "http:\/\/cartelsol.com"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "core": "11.0.3.2",
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 53.0.3

**Operating system:** Ubuntu Mate 17.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing on both ends.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Sharer:
When saving actually worked before using the sync client I got this:
{"reqId":"81uftviackjQm4Lq1fGE","level":3,"time":"2017-05-30T20:56:57+00:00","remoteAddr":"::1","user":"--","app":"no app in context","method":"PUT","url":"\/public.php\/webdav\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"No delete permission for path\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFolder.php(65): OC\\\\Files\\\\Node\\\\Folder->delete()\\n#1 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Preview\\\/Watcher.php(62): OC\\\\Files\\\\SimpleFS\\\\SimpleFolder->delete()\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Preview\\\/WatcherConnector.php(60): OC\\\\Preview\\\\Watcher->postWrite(Object(OC\\\\Files\\\\Node\\\\File))\\n#3 [internal function]: OC\\\\Preview\\\\WatcherConnector->OC\\\\Preview\\\\{closure}(Object(OC\\\\Files\\\\Node\\\\File))\\n#4 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(33): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\Files', 'postWrite', Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(134): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\Files', 'postWrite', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(84): OC\\\\Files\\\\Node\\\\Root->emit('\\\\\\\\OC\\\\\\\\Files', 'postWrite', Array)\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OC\\\\Files\\\\Node\\\\HookConnector->postWrite(Array)\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(297): OC_Hook::emit('OC_Filesystem', 'post_write', Array)\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(221): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emitPostHooks(true)\\n#11 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1129): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #11)\\n#12 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('', Resource id #11, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(105): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/public.php(76): require_once('\\\/usr\\\/share\\\/weba...')\\n#19 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php\",\"Line\":344}","userAgent":"Nextcloud Server Crawler","version":"12.0.0.29"}

Sharee:
A lot of;
{"reqId":"MVP5WKSNQ0zqKEzzh2gt","level":3,"time":"2017-05-30T20:54:50+00:00","remoteAddr":"10.0.3.1","user":"m.hoffmann","app":"files_texteditor","method":"PUT","url":"\/apps\/files_texteditor\/ajax\/savefile","message":"File: \/test.txt modified since opening.","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko\/20100101 Firefox\/53.0","version":"12.0.0.29"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

a) *The javascript console log:* Nothing
b) *The network log: *
```
savefile - Request
```
Host: xxxxxxxxxx
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
requesttoken: xxxxx
OCS-APIREQUEST: true
X-Requested-With: XMLHttpRequest
Content-Length: 174
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc_sessionPassphrase=xxxxxxxxx; nc_username=m.hoffmann; nc_token=xxxxxx; nc_session_id=xxxxx
Connection: keep-alive
```
Respone: 400 Bad request
```
Server: nginx/1.10.3
Date: Tue, 30 May 2017 21:01:56 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 68
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-xxxxxxx' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
X-Frame-Options: SAMEORIGIN
x-xss-protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
```
</details>

**Comment by rullzer** [comment]
Yeah I can reproduce this. It is basically that the receiving server doesn't properly do etag propegation of the federated share. It just assumes its data is still valid.

I think the only real 'proper' approach here is to do a root propfind to the share. But this will slow stuff down.

@icewind1991

**Comment by Bubu** [comment]
Any updates on this? Was there any work done on federation for NC13? This issue basically makes federated rw file sharing between instances unusable for me.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by Bubu** [comment]
I don't really use federated shares anymore, so I can't test this.
