### ISSUE TITLE
Fatal error in sync

### ISSUE THREAD

**Issue by thsnielsen** [nextcloud/server#5245]
### Steps to reproduce
Not sure how i ended up in this mess

### Expected behaviour
Sync with 1 nextcloud server 2 android phones with photo upload to folders (year month) enabled, and 2/3 linux clients laptops syncing everything with the nextcloud client for linux.
This worked quite a while, then when i really started using nextcloud - something bad happened

### Actual behaviour
Sync with the linux clients are blocked 

### Server configuration
Raspberyy, raspbian, nginx, mariadb nextcloud 12. everything quite up to date. Problem started under nextcloud 11.0.2

**Operating system**:
Raspbian  4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

**Web server:**
Package: nginx                           
Version: 1.10.3-1

**Database:**
Version: 10.0.30-0+deb8u2

**PHP version:**
php --version
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
12.0.0  (issue started 11.0.2 before upgrade)

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded from 11.x latest 11.0.2

**Where did you install Nextcloud from:**
downloaded v11 from nextcloud. Upgraded via web interface (after removing 3rd party apps)

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
"No errors have been found."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - direct_menu
  - files_external
  - notes
  - user_external
  - user_ldap

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "oc0labtwwnrl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.70",
            "thomastechtalk.ddns.net"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/192.168.0.70",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "loglevel": 2,
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "password": "***REMOVED SENSITIVE VALUE***",
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox 52.1.1 Linux 64

**Operating system:**
OpenSuse Tumbleweed 
 4.11.2-1-default #1 SMP PREEMP

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
not sure if this is what you want - below i copy paste from the loginterface when accessing from web as admin :
{"reqId":"\/QiquL5PyBdMCozZgTWR","remoteAddr":"195.200.175.6","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\Hi
ntException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(464): OCA\\\\Encryption\\\\Crypto\
\\\Crypt->checkSignature('dj38wEOrlz4i6J2...', 'O\\\\xA7\\\\xA7\\\\xD9(C\\\\x95q\\\\nD\\\\xB9\\\\f\\\\xA4\\\\xF5\\\\xA9...', 'ce19d51c6d7b339...')\\n#1 \\
\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(372): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent
('dj38wEOrlz4i6J2...', 'O\\\\xA7\\\\xA7\\\\xD9(C\\\\x95q\\\\nD\\\\xB9\\\\f\\\\xA4\\\\xF5\\\\xA9...', 'AES-256-CTR', 0, 0)\\n#2 \\\/var\\\/www\\\/nextcloud
\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(460): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('dj38wEOrlz4i6J2...', 0)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(291): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #30, 8192)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #33, Resource id #35, '12822104')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(498): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":484,\"User\":\"Thomas\"}","level":4,"time":"2017-05-20T22:52:00+00:00","method":"GET","url":"\/remote.php\/dav\/files\/Thomas\/NosPhotos\/2017\/05\/DSC_0166.JPG","user":"Thomas","version":"11.0.2.7"}

cat nextcloudServerFatal.txt 
        OCP\Encryption\Exceptions\GenericEncryptionException: Bad Signature

    /var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php - line 463: OCA\Encryption\Crypto\Crypt->checkSignature('dj38wEOrlz4i6J2...', 'O\xA7\xA7\xD9(C\x95q\nD\xB9\f\xA4\xF5\xA9...', 'ce19d51c6d7b339...')
    /var/www/nextcloud/apps/encryption/lib/Crypto/Encryption.php - line 372: OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('dj38wEOrlz4i6J2...', 'O\xA7\xA7\xD9(C\x95q\nD\xB9\f\xA4\xF5\xA9...', 'AES-256-CTR', 0, 0)
    /var/www/nextcloud/lib/private/Files/Stream/Encryption.php - line 460: OCA\Encryption\Crypto\Encryption->decrypt('dj38wEOrlz4i6J2...', 0)
    /var/www/nextcloud/lib/private/Files/Stream/Encryption.php - line 291: OC\Files\Stream\Encryption->readCache()
    [internal function] OC\Files\Stream\Encryption->stream_read(8192)
    /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php - line 83: fread(Resource id #25, 8192)
    /var/www/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php - line 91: Icewind\Streams\Wrapper->stream_read(8192)
    [internal function] Icewind\Streams\CallbackWrapper->stream_read(8192)
    /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php - line 78: stream_copy_to_stream(Resource id #28, Resource id #30, '12822104')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 498: Sabre\HTTP\Sapi sendResponse(Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))                                                                                                                                                    
    /var/www/nextcloud/apps/dav/lib/Server.php - line 253: Sabre\DAV\Server->exec()                                                                       
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()                                                                   
    /var/www/nextcloud/remote.php - line 162: require_once('/var/www/nextcl...')
    {main}

#### The client log
06-04 10:14:48:588 2311 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post treewalk" and starting new transaction
06-04 10:14:48:589 2311 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post stale entry removal" and starting new transaction
06-04 10:14:48:589 2311 OCC::OwncloudPropagator::start: Using QNAM/HTTP parallel code path
06-04 10:14:48:590 2311 OCC::SyncEngine::slotDiscoveryJobFinished: <<#### Post-Reconcile end ####################################################  32472
06-04 10:14:48:640 2311 OCC::Folder::slotSyncStarted: #### Propagation start #################################################### >>
06-04 10:14:48:644 2311 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://thomastechtalk.ddns.net:444/remote.php/dav/files/Thomas/" :  "Sync Running"
06-04 10:14:48:645 2311 OCC::PropagateDownloadFile::start: virtual void OCC::PropagateDownloadFile::start() "NosPhotos/2017/05/DSC_0165.JPG" 0
06-04 10:14:48:645 2311 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "NosPhotos/2017/05/DSC_0165.JPG" "NosPhotos/2017/05/.DSC_0165.JPG.~282aeaea" "3b374c0d1be6cfdd5221b3df2b39560c" 0
06-04 10:14:48:645 2311 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
06-04 10:14:48:658 2311 OCC::GETFileJob::start: virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x36cb588) false false
06-04 10:14:48:659 2311 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "https://thomastechtalk.ddns.net" + "/NosPhotos/2017/05/DSC_0165.JPG" "OCC::PropagateDownloadFile"
06-04 10:14:48:661 2311 OCC::PropagateDownloadFile::start: virtual void OCC::PropagateDownloadFile::start() "NosPhotos/2017/05/DSC_0166.JPG" 1
06-04 10:14:48:662 2311 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "NosPhotos/2017/05/DSC_0166.JPG" "NosPhotos/2017/05/.DSC_0166.JPG.~768e7d7d" "6dd9f6d139b0bc29eda6dd2f7561bdda" 0
06-04 10:14:48:663 2311 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
06-04 10:14:48:663 2311 OCC::GETFileJob::start: virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x36cb588) false false
06-04 10:14:48:664 2311 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "https://thomastechtalk.ddns.net" + "/NosPhotos/2017/05/DSC_0166.JPG" "OCC::PropagateDownloadFile"
06-04 10:14:48:667 2311 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/home/Download/nextcloud/NosPhotos/2017/05/.DSC_0165.JPG.~282aeaea"
06-04 10:14:48:668 2311 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/home/Download/nextcloud/NosPhotos/2017/05/.DSC_0166.JPG.~768e7d7d"
06-04 10:14:48:668 2311 OCC::PropagateDownloadFile::start: virtual void OCC::PropagateDownloadFile::start() "NosPhotos/2017/05/DSC_0169.JPG" 2
06-04 10:14:48:669 2311 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "NosPhotos/2017/05/DSC_0169.JPG" "NosPhotos/2017/05/.DSC_0169.JPG.~7c76c282" "727f1d9c8e23ceaf13cbb14abeea8b75" 0
06-04 10:14:48:670 2311 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
06-04 10:14:48:670 2311 OCC::GETFileJob::start: virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x36cb588) false false
06-04 10:14:48:670 2311 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "https://thomastechtalk.ddns.net" + "/NosPhotos/2017/05/DSC_0169.JPG" "OCC::PropagateDownloadFile"
06-04 10:14:48:674 2311 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/home/Download/nextcloud/NosPhotos/2017/05/.DSC_0169.JPG.~7c76c282"
06-04 10:14:49:640 2311 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/home/Download/nextcloud/NosPhotos/2017/05/.DSC_0165.JPG.~282aeaea"
06-04 10:14:49:958 2311 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/home/Download/nextcloud/NosPhotos/2017/05/.DSC_0166.JPG.~768e7d7d"
06-04 10:15:02:371 2311 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://thomastechtalk.ddns.net" + "/" "OCC::QuotaInfo"

**Comment by thsnielsen** [comment]
Hmm i cracked, and started deleting the always 3 files reported, as i could not view them in the web interface either. Then another 3 files would be reported as problematic and so on, but after some 20ish files, i had successful sync :-) So this issue is now obsolete, and only for reference :-/ still not sure what happened
