### ISSUE TITLE
No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured in logfile

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#5326]
### Steps to reproduce
1. Log message.  Scenario unknown
2.
3.

### Expected behaviour
The message should not be preset

### Actual behaviour
The message is there in the log file

Message\":\"HTTP\\\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

Various clients:

# grep Basic nextcloud.log| sed 's/","/@/g' | tr "@" "\n" | grep userAge | uniq -c
      2 userAgent":"CalDavSynchronizer\/2.21
     21 userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) akonadi_davgroupware_resource_1\/4.14.25 Safari\/534.34

The url of the server changed from https://owncloud.domain.tld/owncloud to https://owncloud.domain.tld

### Server configuration

**Operating system**:  openSUSE_42.2

**Web server:** Apache-2.4.x

**Database:** sqlite3

**PHP version:** 7.0.7

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** yes, update from owncloud

**Where did you install Nextcloud from:** from the nextcloud download page

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - admin_audit: 1.2.0
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - circles: 0.10.0
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.32
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
  - workin2gether: 0.9.6

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/owncloud",
        "dbtype": "sqlite3",
        "default_language": "nl",
        "defaultapp": "bookmarks",
        "version": "12.0.0.29",
        "installed": true,
        "instanceid": "5076f1b68ab6d",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 1048576,
        "loglevel": "0",
        "theme": "",
        "trusted_domains": [
            "<server>"
        ],
        "mail_from_address": "<user>",
        "mail_smtpmode": "php",
        "mail_domain": "<domain>",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "<emailserver>",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/<server>\/"
    },
    "apps": {
        "activity": {
            "installed_version": "2.1.3",
            "types": "filesystem",
            "enabled": "no"
        },
        "admin_audit": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "admin_dependencies_chk": {
            "installed_version": "0.02",
            "types": "",
            "enabled": "no",
            "ocsid": "166041"
        },
        "admin_migrate": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "no"
        },
        "appframework": {
            "installed_version": "0.103",
            "enabled": "no",
            "types": "",
            "ocsid": "158433"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.3.3",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "496"
        },
        "bookmarks": {
            "installed_version": "0.10.0",
            "types": "",
            "enabled": "yes"
        },
        "bruteforcesettings": {
            "installed_version": "1.0.2",
            "enabled": "yes",
            "types": ""
        },
        "calendar": {
            "installed_version": "1.5.3",
            "types": "",
            "enabled": "yes",
            "ocsid": "168707"
        },
        "circles": {
            "installed_version": "0.10.0",
            "enabled": "yes",
            "types": ""
        },
        "comments": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "1.5.3",
            "types": "",
            "enabled": "yes",
            "ocsid": "168708"
        },
        "core": {
            "installedat": "1342263603.9908",
            "lastupdatedat": "1497086735",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_calendar": "calendar\/share.php",
            "public_caldav": "calendar\/share.php",
            "remote_ampache": "media\/remote.php",
            "public_gallery": "gallery\/public.php",
            "public_shorty_relay": "\/apps\/shorty\/relay.php",
            "public_shorty_qrcode": "\/apps\/shorty\/qrcode.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "backgroundjobs_task": "",
            "global_cache_gc_lastrun": "1437195601",
            "backgroundjobs_step": "regular_tasks",
            "shareapi_allow_resharing": "yes",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "backgroundjobs_mode": "cron",
            "lastupdateResult": "[]",
            "lastcron": "1497096906",
            "repairlegacystoragesdone": "yes",
            "public_documents": "documents\/public.php",
            "shareapi_allow_public_notification": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_expire_date": "no",
            "shareapi_allow_mail_notification": "yes",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "vendor": "nextcloud",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "installed.bundles": "[\"CoreBundle\"]",
            "oc.integritycheck.checker": "[]",
            "scss.variables": "60923fa52042a85a2fe621f9e541813d"
        },
        "dashboard": {
            "installed_version": "1.6.1",
            "ocsid": "160265",
            "types": "type",
            "enabled": "no"
        },
        "dav": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes",
            "buildCalendarSearchIndex": "yes"
        },
        "direct_menu": {
            "enabled": "yes",
            "installed_version": "0.10.2",
            "types": "",
            "ocsid": "169148"
        },
        "documents": {
            "installed_version": "0.11.1",
            "enabled": "no",
            "types": "",
            "ocsid": "168711",
            "unstable": "false"
        },
        "external": {
            "installed_version": "2.0.3",
            "types": "",
            "enabled": "yes"
        },
        "fbsync": {
            "installed_version": "1.7.3",
            "types": "",
            "enabled": "no"
        },
        "federatedfilesharing": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.2.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.7.2",
            "types": "filesystem",
            "enabled": "yes",
            "default_quota": "1 GB",
            "mountconfigmtime": "1351330688",
            "cronjob_scan_files": "500"
        },
        "files_archive": {
            "installed_version": "0.2",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_embeddedvideo": {
            "installed_version": "0.0.6",
            "types": "",
            "enabled": "no"
        },
        "files_external": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes",
            "ocsid": "166048",
            "user_mounting_backends": "\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP,\\OC\\Files\\Storage\\SMB,\\OC\\Files\\Storage\\SMB_OC,\\OC\\Files\\Storage\\DAV",
            "allow_user_mounting": "yes",
            "google::580628286319-onkg50tj3no3ditea1417790914cId": "62341"
        },
        "files_imageviewer": {
            "installed_version": "1.0",
            "types": "",
            "enabled": "no"
        },
        "files_locking": {
            "installed_version": "",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_mv": {
            "installed_version": "0.8.2",
            "types": "filesystem",
            "enabled": "no",
            "ocsid": "150271"
        },
        "files_odfviewer": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "no"
        },
        "files_pdfviewer": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes",
            "ocsid": "166049"
        },
        "files_sharing": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_texteditor": {
            "installed_version": "0.4",
            "types": "",
            "enabled": "no",
            "ocsid": "166051"
        },
        "files_trashbin": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_tree": {
            "installed_version": "0.9.0",
            "types": "",
            "enabled": "no"
        },
        "files_versions": {
            "installed_version": "1.0.5",
            "types": "filesystem",
            "enabled": "no",
            "ocsid": "166053"
        },
        "files_videoplayer": {
            "installed_version": "1.1.0",
            "types": "",
            "enabled": "yes"
        },
        "files_videoviewer": {
            "installed_version": "0.1.3",
            "types": "",
            "enabled": "no",
            "ocsid": "166054"
        },
        "firstrunwizard": {
            "installed_version": "2.1",
            "types": "logging",
            "enabled": "yes"
        },
        "fluxx_compensator": {
            "installed_version": "0.2.5",
            "enabled": "no",
            "types": "base",
            "ocsid": "157091"
        },
        "gallery": {
            "installed_version": "17.0.0",
            "types": "",
            "enabled": "yes"
        },
        "galleryplus": {
            "installed_version": "14.3.0",
            "types": "",
            "enabled": "no",
            "ocsid": "169116"
        },
        "impress": {
            "installed_version": "1.0",
            "types": "",
            "enabled": "no"
        },
        "keeweb": {
            "installed_version": "0.4.0",
            "enabled": "yes",
            "types": ""
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "media": {
            "installed_version": "0.4.3",
            "types": "",
            "enabled": "no"
        },
        "music": {
            "installed_version": "0.3.8",
            "types": "filesystem",
            "enabled": "no",
            "ocsid": "164319"
        },
        "news": {
            "installed_version": "7.0.1",
            "enabled": "no",
            "types": ""
        },
        "nextcloud_announcements": {
            "installed_version": "1.1",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100"
        },
        "notifications": {
            "installed_version": "2.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.0.5",
            "types": "authentication",
            "enabled": "yes"
        },
        "oc-custom-tags": {
            "installed_version": "0.0.1",
            "types": "",
            "enabled": "no"
        },
        "oclife": {
            "installed_version": "0.2.0",
            "types": "",
            "enabled": "no",
            "useImageMagick": "1"
        },
        "ocusagecharts": {
            "installed_version": "3.4.3",
            "types": "",
            "enabled": "no"
        },
        "old_menu": {
            "installed_version": "1.2.1",
            "types": "",
            "enabled": "no"
        },
        "ownnote": {
            "installed_version": "1.05",
            "types": "",
            "enabled": "no",
            "ocsid": "168512"
        },
        "password_policy": {
            "installed_version": "1.2.2",
            "types": "",
            "enabled": "yes",
            "enforceUpperLowerCase": "1",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1"
        },
        "provisioning_api": {
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "richdocuments": {
            "installed_version": "1.12.32",
            "enabled": "yes",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/office.<domain>"
        },
        "search_lucene": {
            "installed_version": "0.7.0",
            "enabled": "no",
            "types": "filesystem",
            "ocsid": "168709"
        },
        "serverinfo": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "sharelinks": {
            "installed_version": "1.0.1",
            "enabled": "no",
            "types": "",
            "ocsid": "170527"
        },
        "shorty": {
            "installed_version": "0.2.8",
            "enabled": "no",
            "types": "",
            "id-alphabet": "Ll5iOHpw4ePkaFIKohxR3EBbMgmTNSUXZQYGjvsAtWwuVfd810q2n6C7c9DrzJ"
        },
        "storage_charts": {
            "installed_version": "2.2",
            "enabled": "no",
            "types": ""
        },
        "storagecharts2": {
            "installed_version": "2.6.1",
            "enabled": "no",
            "types": "",
            "ocsid": "165528"
        },
        "survey_client": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.8.1",
            "types": "",
            "enabled": "no",
            "ocsid": "164356"
        },
        "templateeditor": {
            "installed_version": "0.2",
            "types": "",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "1.3.0",
            "types": "logging",
            "enabled": "yes",
            "name": "Radoeka",
            "cachebuster": "2",
            "url": "https:\/\/<server>"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes",
            "direct_menu": "0.10.2",
            "calendar": "1.5.3",
            "core": "12.0.0.29",
            "update_check_errors": "0",
            "richdocuments": "1.12.32"
        },
        "updater": {
            "installed_version": "0.4",
            "types": "",
            "enabled": "no",
            "ocsid": "166059"
        },
        "user_migrate": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "no"
        },
        "user_openid": {
            "installed_version": "0.1.2",
            "types": "prelogin,authentication",
            "enabled": "yes"
        },
        "workflowengine": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "workin2gether": {
            "installed_version": "0.9.6",
            "enabled": "yes",
            "types": "",
            "suffix": "rule_displayname"
        },
        "148406": {
            "enabled": "no"
        },
        "150271": {
            "enabled": "no"
        }
    }
}



or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
nextcloud.log:{"reqId":"dMdAb5uKr4wjJi1mKodW","level":0,"time":"2017-06-10T13:07:10+02:00","remoteAddr":"<ipaddress>","user":"--","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/calendars\/<user>\/default%20calendar\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/remote.php(162): require_once('\\\/srv\\\/www\\\/vhosts...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/vhosts\\\/<server>\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}","userAgent":"CalDavSynchronizer\/2.21","version":"12.0.0.29"}

```
</details>

What's causing the the issue?  How to get rid of the message (how to solve it)??

**Comment by blizzz** [comment]
Given the log message, the client did not send the required header. Please report at KOrganizer.
