### ISSUE TITLE
Administrator->Logging: errors in webdav: filename is missing

### ISSUE THREAD

**Issue by koppd** [nextcloud/server#5376]
### Steps to reproduce
1. sync (upload) a large folder via desktop client.
2. sometimes an error occurs. In my case Website->Administrator->Logging: "Sabre\DAV\Exception\BadRequest: HTTP/1.1 400 expected filesize 9869824 got 1654784"
3.

### Expected behaviour
The web application Administrator->Logging shows me that there was an error. It should provide also information about the file name.

### Actual behaviour
The web application Administrator->Logging shows me that there was an error. It provides a lot information, but it does not reveal the file name.

The file name (in this case: "01_Energiebedarf.doc") is actually only in the data/nextcloud.log 

### Server configuration

**Operating system**:
Linux 4.11.3 (opensuse tumbleweed)
**Web server:**
Apache 2.4.25
**Database:**
sqlite 3.19.2
**PHP version:**
php 7.1.5
**Nextcloud version:** (see Nextcloud admin page)
11.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Nextcloud
**Where did you install Nextcloud from:**
From the nextcloud homepage / sources
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**
Win 7
#### Web server error log
<details>
<summary>Web server error log</summary>

```
93.228.71.124 - ichbins [13/Jun/2017:10:26:54 +0200] "PUT /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/10_Trafos/Zeiger%20f%C3%BCr%20Yz5n.jpg HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:26:54 +0200] "PUT /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/01_Einstieg.ppt HTTP/1.1" 201 -
93.228.71.124 - - [13/Jun/2017:10:26:56 +0200] "-" 408 -
93.228.71.124 - ichbins [13/Jun/2017:10:26:55 +0200] "PUT /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/01_Energiebedarf.doc HTTP/1.1" 400 231
93.228.71.124 - ichbins [13/Jun/2017:10:26:53 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/1628526805/00000003 HTTP/1.1" 400 232
::1 - - [13/Jun/2017:10:26:57 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.25 (Linux/SUSE) OpenSSL/1.0.2k-fips PHP/7.1.5 (internal dummy connection)"
93.228.71.124 - - [13/Jun/2017:10:26:57 +0200] "-" 408 -
::1 - - [13/Jun/2017:10:26:58 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.25 (Linux/SUSE) OpenSSL/1.0.2k-fips PHP/7.1.5 (internal dummy connection)"
::1 - - [13/Jun/2017:10:26:59 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.25 (Linux/SUSE) OpenSSL/1.0.2k-fips PHP/7.1.5 (internal dummy connection)"
93.228.71.124 - - [13/Jun/2017:10:27:00 +0200] "-" 408 -
::1 - - [13/Jun/2017:10:27:00 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.25 (Linux/SUSE) OpenSSL/1.0.2k-fips PHP/7.1.5 (internal dummy connection)"
93.228.71.124 - ichbins [13/Jun/2017:10:27:01 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/ HTTP/1.1" 207 537
93.228.71.124 - ichbins [13/Jun/2017:10:27:02 +0200] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
93.228.71.124 - ichbins [13/Jun/2017:10:27:02 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/ HTTP/1.1" 207 24363
93.228.71.124 - ichbins [13/Jun/2017:10:27:02 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen HTTP/1.1" 207 10797
93.228.71.124 - ichbins [13/Jun/2017:10:27:02 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE HTTP/1.1" 207 3659
93.228.71.124 - ichbins [13/Jun/2017:10:27:02 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh HTTP/1.1" 207 18311
93.228.71.124 - ichbins [13/Jun/2017:10:27:02 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/10_Trafos HTTP/1.1" 207 31306
...
93.228.71.124 - ichbins [13/Jun/2017:10:29:52 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M06.1_SG HTTP/1.1" 207 955
93.228.71.124 - ichbins [13/Jun/2017:10:29:58 +0200] "PROPFIND /nextcloud/remote.php/dav/uploads/ichbins/398024649 HTTP/1.1" 404 239
93.228.71.124 - ichbins [13/Jun/2017:10:29:58 +0200] "MKCOL /nextcloud/remote.php/dav/uploads/ichbins/398023808 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:29:58 +0200] "PROPFIND /nextcloud/remote.php/dav/uploads/ichbins/1628526805 HTTP/1.1" 207 1815
93.228.71.124 - ichbins [13/Jun/2017:10:30:01 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/ HTTP/1.1" 207 537
93.228.71.124 - ichbins [13/Jun/2017:10:30:03 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/ HTTP/1.1" 207 599
93.228.71.124 - ichbins [13/Jun/2017:10:29:58 +0200] "PUT /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/01_Energiebedarf.doc HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:29:58 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/398023808/00000000 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:29:58 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/1628526805/00000003 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:10 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/ HTTP/1.1" 207 557
93.228.71.124 - ichbins [13/Jun/2017:10:30:10 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/398023808/00000001 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:13 +0200] "MOVE /nextcloud/remote.php/dav/uploads/ichbins/398023808/.file HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:14 +0200] "PUT /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/AB_Laufwasserkraftwerk.doc HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:10 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/1628526805/00000004 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:19 +0200] "MOVE /nextcloud/remote.php/dav/uploads/ichbins/1628526805/.file HTTP/1.1" 201 -
...
93.228.71.124 - ichbins [13/Jun/2017:10:30:32 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/10_Trafos HTTP/1.1" 207 32060
93.228.71.124 - ichbins [13/Jun/2017:10:30:32 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung HTTP/1.1" 207 16264
93.228.71.124 - ichbins [13/Jun/2017:10:30:33 +0200] "PROPFIND /nextcloud/remote.php/dav/files/ichbins/ HTTP/1.1" 207 599
93.228.71.124 - ichbins [13/Jun/2017:10:30:24 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/3767364483/00000000 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:25 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/3806274180/00000000 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:25 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/4015182203/00000000 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:33 +0200] "GET /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/01_Energiebedarf.doc HTTP/1.1" 200 9869824
93.228.71.124 - ichbins [13/Jun/2017:10:30:33 +0200] "GET /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/01_Energiebedarf_Lsg.doc HTTP/1.1" 200 12486144
93.228.71.124 - ichbins [13/Jun/2017:10:30:36 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/3767364483/00000001 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:38 +0200] "GET /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/AB_Laufwasserkraftwerk.doc HTTP/1.1" 200 3351552
93.228.71.124 - ichbins [13/Jun/2017:10:30:37 +0200] "PUT /nextcloud/remote.php/dav/uploads/ichbins/4015182203/00000001 HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:39 +0200] "MOVE /nextcloud/remote.php/dav/uploads/ichbins/3767364483/.file HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:40 +0200] "MOVE /nextcloud/remote.php/dav/uploads/ichbins/4015182203/.file HTTP/1.1" 201 -
93.228.71.124 - ichbins [13/Jun/2017:10:30:40 +0200] "GET /nextcloud/remote.php/dav/files/ichbins/BSAOE%20Ausarbeitungen/M05.3_IE/M05.3_IE_Sh/Stoffsammlung/AB_Speicherkraftwerk.doc HTTP/1.1" 200 1083904
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"dF273kJ0Qj01ZCYa0WqI","remoteAddr":"93.228.71.124","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 9869824 got 1654784\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #31)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1072): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('01_Energiebedar...', Resource id #31)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('files\\\/ichbins\\\/B...', Resource id #31, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(231): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#9 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":150,\"User\":\"ichbins\"}","level":4,"time":"2017-06-13T08:26:56+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/dav\/files\/ichbins\/BSAOE%20Ausarbeitungen\/M05.3_IE\/M05.3_IE_Sh\/Stoffsammlung\/01_Energiebedarf.doc","user":"ichbins","version":"11.0.3.2"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
The file name is in the log file: `"url":"\/nextcloud\/remote.php\/dav\/files\/ichbins\/BSAOE%20Ausarbeitungen\/M05.3_IE\/M05.3_IE_Sh\/Stoffsammlung\/01_Energiebedarf.doc"`

For the actual reason for this we are looking already into it.
