### ISSUE TITLE
wrong color setting at upgrade time blocks scss compilation

### ISSUE THREAD

**Issue by Gibheer** [nextcloud/server#5536]
### Steps to reproduce
1. install nextcloud 11
2. run the SQL statement `run the following SQL statement: update oc_appconfig set configvalue = '##3a5f78' where configkey = 'color';` to place a wrong color code (which is totally legal since owncloud 7 or so)
3. upgrade to nextcloud 12

### Expected behaviour
I get an interface I can work with.

### Actual behaviour
The compilation crashes with an error leaving css files behind without content. This leads to a completely broken webinterface.

### Server configuration

**Operating system**: FreeBSD 11.0

**Web server:** nginx 1.12.0

**Database:** PostgreSQL 9.6.3

**PHP version:** PHP 7.0.20

**Nextcloud version:** 12.0
**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from 11.2

**Where did you install Nextcloud from:** official tar.gz

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"GEOFMkJY0xLvy7yp2xNM","level":3,"time":"2017-06-25T17:38:57+00:00","remoteAddr":"remote","user":"gibheer","app":"core","method":"GET","url":"\/apps\/theming\/styles?v=5","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##3a5f78;$color-primary-text: #ffffff;@import \"theming.scss\";` (stdin) on line 1 in \/srv\/<domain>\/htdocs\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/srv\/<domain>\/htdocs\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/srv\/<domain>\/htdocs\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/srv\/<domain>\/htdocs\/lib\/private\/Template\/SCSSCacher.php(213): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/srv\/<domain>\/htdocs\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/srv\/<domain>...', 'theming.css', 'theming.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'apps\/theming\/cs...')\n#4 \/srv\/<domain>\/htdocs\/apps\/theming\/lib\/Controller\/ThemingController.php(375): OC\\Template\\SCSSCacher->process('\/srv\/<domain>...', 'apps\/theming\/cs...', 'theming')\n#5 [internal function]: OCA\\Theming\\Controller\\ThemingController->getStylesheet()\n#6 \/srv\/<domain>\/htdocs\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#7 \/srv\/<domain>\/htdocs\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Theming\\Controller\\ThemingController), 'getStylesheet')\n#8 \/srv\/<domain>\/htdocs\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Theming\\Controller\\ThemingController), 'getStylesheet')\n#9 \/srv\/<domain>\/htdocs\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Theming\\\\Con...', 'getStylesheet', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/srv\/<domain>\/htdocs\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/srv\/<domain>\/htdocs\/lib\/base.php(1000): OC\\Route\\Router->match('\/apps\/theming\/s...')\n#13 \/srv\/<domain>\/htdocs\/index.php(40): OC::handleRequest()\n#14 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}
```
</details>

**Comment by MorrisJobke** [comment]
> run the SQL statement run the following SQL statement: update oc_appconfig set configvalue = '##3a5f78' where configkey = 'color'; to place a wrong color code (which is totally legal since owncloud 7 or so)

How was this entered? The UI didn't had any input for this. We can't fix all database columns that may be modified by hand.

I will close this as won't fix, because the broken state is only possible if the admin manipulates the DB by hand, which is not really supported.
