### ISSUE TITLE
Sharing not working on encrypted external storage

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/server#5590]
### Steps to reproduce
1. Set up external storage (in my case Amazon S3, Google Drive) with encryption/sharing enabled.
2. Upload files and share by link (in my case pdf's and jpg's)
3. Open link being logged in or without beeing logged in.

### Expected behaviour
Open/preview files when link is accessed.

### Actual behaviour
Links only work for jpg's, not for pdf's. 
Decryption fails for this files, both pdf's with text layer and pdf's without text layer.

### Server configuration
NC12 on Amazon EC2, CentOS, Apache, without SELinux.
Also tested NC12 on VM from Tech and Me, Ubuntu/Apache, got the same error.

**Operating system**: CentOS 7 without SELinux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** on CentOS from nextcloud.com, on Ubuntu I used the VM provided by Tech and Me. Below I will provide info for my server - CentOS.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.3
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - rainloop: 5.0.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocpjov949a0j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "aws.iscan.pro"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/aws.iscan.pro\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.release.channel": "beta",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** Amazon S3, Google Drive

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:* no

### Client configuration
**Browser:** Mozilla

**Operating system:** macOS Sierra

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sun Jul 02 03:26:02.383135 2017] [auth_digest:notice] [pid 2867] AH01757: generating secret for digest authentication ...
[Sun Jul 02 03:26:02.386114 2017] [lbmethod_heartbeat:notice] [pid 2867] AH02282: No slotmem from mod_heartmonitor
[Sun Jul 02 03:26:02.504306 2017] [mpm_prefork:notice] [pid 2867] AH00163: Apache/2.4.25 (Amazon) OpenSSL/1.0.1k-fips PHP/7.0.16 configured -- resuming normal operations
[Sun Jul 02 03:26:02.504324 2017] [core:notice] [pid 2867] AH00094: Command line: '/usr/sbin/httpd'
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"GRfi972AJcikmK3Ngm3b","level":3,"time":"2017-07-03T09:33:24+00:00","remoteAddr":"5.15.113.75","user":"laurentiu","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1499074404103","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(156): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/html\\\/n...')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/n...', NULL)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"MWZcnuMlt5ou5Y5NJ3F8","level":3,"time":"2017-07-03T09:33:28+00:00","remoteAddr":"5.15.113.75","user":"laurentiu","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1499074407425","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(156): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/html\\\/n...')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/n...', NULL)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"wbM6SWD1SnKOoNgpZc9R","level":3,"time":"2017-07-03T09:34:07+00:00","remoteAddr":"5.15.113.75","user":"--","app":"no app in context","method":"GET","url":"\/index.php\/s\/Dfz4NZfFpfv65VW\/download","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(372): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n#1 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder(NULL)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(63): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(280): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(1240): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder(NULL)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Encryption\\\/File.php(94): OC\\\\Share20\\\\Manager->getAccessList(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(257): OC\\\\Encryption\\\\File->getAccessList('\\\/laurentiu\\\/file...')\\n#7 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_open('ocencryption:\\\/\\\/', 'r', 0, NULL)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(198): fopen('ocencryption:\\\/\\\/', 'r', false, Resource id #150)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(180): OC\\\\Files\\\\Stream\\\\Encryption::wrapSource(Resource id #149, Resource id #150, 'ocencryption', 'OC\\\\\\\\Files\\\\\\\\Stream...', 'r')\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(460): OC\\\\Files\\\\Stream\\\\Encryption::wrap(Resource id #149, 'canoe.pdf', '\\\/laurentiu\\\/file...', Array, NULL, Object(OCA\\\\Encryption\\\\Crypto\\\\Encryption), Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability), Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), Object(OC\\\\Encryption\\\\Util), Object(OC\\\\Encryption\\\\File), 'r', '82068', 54686, 8192, true)\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('canoe.pdf', 'r')\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1130): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('canoe.pdf', 'r')\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(971): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/GoogleDrive\\\/ca...', Array, 'r')\\n#14 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(432): OC\\\\Files\\\\View->fopen('\\\/GoogleDrive\\\/ca...', 'r')\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(308): OC\\\\Files\\\\View->readfile('\\\/GoogleDrive\\\/ca...')\\n#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(120): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/GoogleDrive', 'canoe.pdf', Array)\\n#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(535): OC_Files::get('\\\/GoogleDrive', 'canoe.pdf', Array)\\n#18 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('Dfz4NZfFpfv65VW', NULL, '', '')\\n#19 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#21 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#22 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#23 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/routes.php(129): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#24 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#25 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#26 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/s\\\/Dfz4NZfFpfv6...')\\n#27 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#28 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":398}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"hwo4OBqMH3uZ4B4iBfjP","level":3,"time":"2017-07-03T09:34:18+00:00","remoteAddr":"5.15.113.75","user":"laurentiu","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1499074458442","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(156): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/html\\\/n...')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/n...', NULL)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"gwMWHWK1VZCTA1NP3Oo6","level":3,"time":"2017-07-03T09:34:21+00:00","remoteAddr":"5.15.113.75","user":"laurentiu","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1499074460746","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(156): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/html\\\/n...')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/n...', NULL)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```
</details>

**Comment by MorrisJobke** [comment]
cc @schiessle @icewind1991

**Comment by schiessle** [comment]
can't reproduce it. Feel free to re-open if this is still an issue with the latest version of Nextcloud
