### ISSUE TITLE
Internal server error while attempting v9.0.57.2 to v10.0.5 upgrade

### ISSUE THREAD

**Issue by ppharrington** [nextcloud/server#5633]
### Steps to reproduce
1. Apps deactivated
2. V9 files removed (except data and themes folders)
3. V10 files placed
4. "php occ upgrade --skip-migration-test" done, 
5. Apps activation via : 
        php occ app:enable activity
	php occ app:enable files_trashbin
        php occ app:enable gallery
	php occ app:enable user_ldap
	php occ app:enable notifications
	php occ app:enable files_pdfviewer
       With script "php occ upgrade --skip-migration-test" launched after each app activation.
       Each time platform access checked an everything going fine.
6. Activation of file sharing with: "php occ app:enable files_sharing", again with script "php occ upgrade --skip-migration-test" launched after
    
### Expected behaviour
Platform working fine with functionnal file sharing.

### Actual behaviour
Web platform shows : 

Internal server error
...
Remote address : xxxx...
Request ID : EFCwqyLVVn2KY7BTO5LU

### Server configuration

**Operating system**:  debian 8.8

**Web server:** nginx/1.10.3

**Database:** MariaDB 10

**PHP version:** 7.0.20-1~dotdeb+8.1

**Nextcloud version:** (see Nextcloud admin page) 9.0.57.2

**Updated from an older Nextcloud/ownCloud or fresh install:** owncloud 9

**Where did you install Nextcloud from:** sources

**Signing status:**
<details>
<summary>Signing status</summary>

```
Results
=======
- core
	- EXTRA_FILE
		- droitsnfs.sh

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [droitsnfs.sh] => Array
                        (
                            [expected] => 
                            [current] => ebc14ecbbf041de58c14fd76e9c2d98f43b9c91aa7bc6ff579d8b36b221328d99fa6db6461d7626267b63b809080ad05e74f84310fa71a0d0501b3004a0f2516
                        )

                )

        )

)
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.5.3
  - contacts: 1.5.3
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - gallery: 15.0.1
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - user_ldap: 1.0.1
  - workflowengine: true
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "516c185b3b4e1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.1.5.2",
        "dbname": "nextcloud",
        "dbhost": "mariadb-cms-master.in.ac-versailles.fr",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 0,
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "proxy": "proxy-tice-vip.in.ac-versailles.fr:3128",
        "default_language": "fr",
        "overwritehost": "URL",
        "forcessl": true,
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.apps.owncloud.com\/v1",
        "mail_smtpmode": "smtp",
        "maintenance": false,
        "loglevel": 0,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "theme": "",
        "custom_csp_policy": "default-src 'self'; script-src 'self' https:\/\/edu-web-stats.ac-versailles.fr 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "trusted_domains": [
            "URL"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "trashbin_retention_obligation": "auto, auto",
        "mail_domain": "ac-versailles.fr",
        "mail_from_address": "dsi-tice",
        "mail_smtphost": "messagerie.in.ac-versailles.fr",
        "logfile": "\/var\/log-owncloud\/owncloud.log",
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```
</details>

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```

+-------------------------------+---------------------------------------------------------------------+
| Configuration                 | NEW                                                                 |
+-------------------------------+---------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                   |
| hasPagedResultSupport         |                                                                     |
| homeFolderNamingRule          | attr:eleve                                                          |
| lastJpegPhotoLookup           | 0                                                                   |
| ldapAgentName                 |                                                                     |
| ldapAgentPassword             | ***                                                                 |
| ldapAttributesForGroupSearch  |                                                                     |
| ldapAttributesForUserSearch   |                                                                     |
| ldapBackupHost                | server-1                                                            |
| ldapBackupPort                | 421                                                                 |
| ldapBase                      | ou=...                                                              |
| ldapBaseGroups                | ou=Groups, ...                                                      |
| ldapBaseUsers                 | ou=...                                                              |
| ldapCacheTTL                  | 84600                                                               |
| ldapConfigurationActive       | 1                                                                   |
| ldapDynamicGroupMemberURL     |                                                                     |
| ldapEmailAttribute            | mail                                                                |
| ldapExperiencedAdmin          | 0                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                     |
| ldapExpertUUIDUserAttr        |                                                                     |
| ldapExpertUsernameAttr        |                                                                     |
| ldapGroupDisplayName          | cn                                                                  |
| ldapGroupFilter               | (&(|(objectclass=inetorgperson)(objectclass=organizationalPerson))) |
| ldapGroupFilterGroups         |                                                                     |
| ldapGroupFilterMode           | 0                                                                   |
| ldapGroupFilterObjectclass    | inetorgperson                                                       |
| ldapGroupMemberAssocAttr      | uniqueMember                                                        |
| ldapHost                      | server-1                                                            |
| ldapIgnoreNamingRules         |                                                                     |
| ldapLoginFilter               | uid=%uid                                                            |
| ldapLoginFilterAttributes     |                                                                     |
| ldapLoginFilterEmail          | 0                                                                   |
| ldapLoginFilterMode           | 0                                                                   |
| ldapLoginFilterUsername       | 1                                                                   |
| ldapNestedGroups              | 0                                                                   |
| ldapOverrideMainServer        | 0                                                                   |
| ldapPagingSize                | 100                                                                 |
| ldapPort                      | 421                                                                 |
| ldapQuotaAttribute            |                                                                     |
| ldapQuotaDefault              | 54288000                                                            |
| ldapTLS                       |                                                                     |
| ldapUserDisplayName           | cn                                                                  |
| ldapUserDisplayName2          |                                                                     |
| ldapUserFilter                | (objectclass=*)                                                     |
| ldapUserFilterGroups          |                                                                     |
| ldapUserFilterMode            | 0                                                                   |
| ldapUserFilterObjectclass     |                                                                     |
| ldapUuidGroupAttribute        | auto                                                                |
| ldapUuidUserAttribute         | auto                                                                |
| turnOffCertCheck              | 0                                                                   |
| useMemberOfToDetectMembership | 1                                                                   |
+-------------------------------+---------------------------------------------------------------------+
+-------------------------------+------------------------------------------------------------+
| Configuration                 |                                                            |
+-------------------------------+------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                            |
| hasPagedResultSupport         |                                                            |
| homeFolderNamingRule          |                                                            |
| lastJpegPhotoLookup           | 0                                                          |
| ldapAgentName                 |                                                            |
| ldapAgentPassword             | ***                                                        |
| ldapAttributesForGroupSearch  |                                                            |
| ldapAttributesForUserSearch   | mail;mailAlternateAddress;cn                               |
| ldapBackupHost                |                                                            |
| ldapBackupPort                |                                                            |
| ldapBase                      | ou=...                                                     |
| ldapBaseGroups                | ou=...                                                     |
| ldapBaseUsers                 | ou=...                                                     |
| ldapCacheTTL                  | 86400                                                      |
| ldapConfigurationActive       | 1                                                          |
| ldapDynamicGroupMemberURL     |                                                            |
| ldapEmailAttribute            | mail                                                       |
| ldapExperiencedAdmin          | 0                                                          |
| ldapExpertUUIDGroupAttr       |                                                            |
| ldapExpertUUIDUserAttr        |                                                            |
| ldapExpertUsernameAttr        |                                                            |
| ldapGroupDisplayName          | cn                                                         |
| ldapGroupFilter               | (&(|(objectclass=groupofuniquenames)))                     |
| ldapGroupFilterGroups         |                                                            |
| ldapGroupFilterMode           | 1                                                          |
| ldapGroupFilterObjectclass    | groupofuniquenames                                         |
| ldapGroupMemberAssocAttr      | uniqueMember                                               |
| ldapHost                      | server-2                                                   |
| ldapIgnoreNamingRules         |                                                            |
| ldapLoginFilter               | uid=%uid                                                   |
| ldapLoginFilterAttributes     |                                                            |
| ldapLoginFilterEmail          | 1                                                          |
| ldapLoginFilterMode           | 0                                                          |
| ldapLoginFilterUsername       | 1                                                          |
| ldapNestedGroups              | 0                                                          |
| ldapOverrideMainServer        | 0                                                          |
| ldapPagingSize                | 1000                                                       |
| ldapPort                      | 389                                                        |
| ldapQuotaAttribute            | cloudquota                                                 |
| ldapQuotaDefault              | 3024288000                                                 |
| ldapTLS                       |                                                            |
| ldapUserDisplayName           | cn                                                         |
| ldapUserDisplayName2          |                                                            |
| ldapUserFilter                | (objectclass=*)                                            |
| ldapUserFilterGroups          |                                                            |
| ldapUserFilterMode            | 1                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                              |
| ldapUuidGroupAttribute        | auto                                                       |
| ldapUuidUserAttribute         | auto                                                       |
| turnOffCertCheck              | 0                                                          |
| useMemberOfToDetectMembership | 1                                                          |
+-------------------------------+------------------------------------------------------------+

```
</details>

### Client configuration
**Browser:** firefox 54.0

**Operating system:** Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>

No server error log

Here is the access.log :
```
192.168.120.22 - - [06/Jul/2017:14:04:21 +0200] "POST /login HTTP/1.1" 303 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.120.22 - - [06/Jul/2017:14:04:21 +0200] "GET /apps/files/ HTTP/1.1" 500 9223 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.120.22 - - [06/Jul/2017:14:04:22 +0200] "GET /apps/files/index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 500 6923 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
```

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"2A6siD0qvXiF8Eh5LBan","remoteAddr":"192.168.120.22","app":"index","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(758): OC\\\\Share20\\\\Share->setSharedBy(NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(622): OC\\\\Share20\\\\DefaultShareProvider->createShare(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(957): OC\\\\Share20\\\\DefaultShareProvider->getSharedWith('2cc744fa-1dd211...', 0, NULL, -1, 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(71): OC\\\\Share20\\\\Manager->getSharedWith('2cc744fa-1dd211...', 0, NULL, -1)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(77): OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#5 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_Sharing\\\\MountProvider))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(78): array_map(Object(Closure), Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(426): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(374): OC\\\\Files\\\\Filesystem::initMountPoints('2cc744fa-1dd211...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(227): OC\\\\Files\\\\Filesystem::init('2cc744fa-1dd211...', '\\\/2cc744fa-1dd21...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(997): OC_Util::setupFS()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":288}","level":3,"time":"2017-07-06T12:13:53+00:00","method":"GET","url":"\/apps\/files\/","user":"2cc744fa-1dd211b2-80000000-00000000","version":"9.1.5.2"}
{"reqId":"bHmll82vEmCnzfVb4isv","remoteAddr":"192.168.120.22","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/apps\\\/files\\\/index.php\\\/apps\\\/gallery\\\/config) cannot be processed by the script '\\\/apps\\\/gallery\\\/config')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(953): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":695}","level":3,"time":"2017-07-06T12:13:53+00:00","method":"GET","url":"\/apps\/files\/index.php\/apps\/gallery\/config?extramediatypes=1","user":"2cc744fa-1dd211b2-80000000-00000000","version":"9.1.5.2"}


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log

ReferenceError: oc_appconfig is not defined[En savoir plus]  shareconfigmodel.js:24:4
	<anonyme> https://URL/core/js/shareconfigmodel.js:24:4
	<anonyme> https://URL/core/js/shareconfigmodel.js:13:2

b) The network log


c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Could I ask you to test the update to 11.0.4 again? Because this looks like a old bug, that was fixed in a more recent maintenance version.

Thanks
