### ISSUE TITLE
Groupfolder 507 Insufficient Storage

### ISSUE THREAD

**Issue by himbeere** [nextcloud/server#5767]
### Steps to reproduce
1. Create Groupfolder
2. Upload something directly to the groupfolder
3. 507 Insufficient Storage (although there is)

### Expected behaviour
I should be able to directly upload something to the groupfolder.

### Actual behaviour
Exception:  507 Insufficient Storage

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
MariaDB

**PHP version:**
7.1.7

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 11.

```
{"reqId":"6hZ9qZLcKrqKe9JBWhoH","level":4,"time":"2017-07-18T08:30:09+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"user","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Security\/bla.mp4","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('\\\/Security\\\/is...', Resource id #23, Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), false)\\n#1 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1093): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n#3 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Security\\\/iso...', Resource id #23, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud.domain.de\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":113,\"User\":\"user\"}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```

**Comment by himbeere** [comment]
It seems there is already an issue open. https://github.com/nextcloud/groupfolders/issues/42. I connect there.
