### ISSUE TITLE
Failed to connect to the database

### ISSUE THREAD

**Issue by FrankMaute** [nextcloud/server#5958]
Hello,

after the update to 12 RC4 I get the following error:

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:61

config as follows:

php -i | grep "pdo"
/etc/php/7.0/cli/conf.d/10-pdo.ini

[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
libxml
mbstring
mcrypt
mysqlnd
openssl
pcntl
pcre
PDO
Phar
posix
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

`
$CONFIG = array (
  'instanceid' => xxx,
  'passwordsalt' =>xxx,
  'secret' => xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => xxx.com',
  ),
  'datadirectory' => '/var/opt/ocdata/data',
  'overwrite.cli.url' => 'https://xxx.com/',
  'dbtype' => 'mysql',
  'version' => '12.0.0.29',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xxx,
  'dbpassword' => xxx,
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'xxx',
  'mail_domain' => xxx.com',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtphost' => 'mail.your-server.de',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'xxx@xxx.com',
  'mail_smtppassword' => xxx!!',
  'forcessl' => true,
  'app.mail.imaplog.enabled' => true,
  'theme' => '',
  'maintenance' => true,
  'loglevel' => 0,
  'log_rotate_size' => 104857600,
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => 'disabled',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'updatechecker' => false,
  'htaccess.RewriteBase' => '/',
  'updater.release.channel' => 'beta',
  'updater.secret' => xxx.xxx/xxx/DRUyIQZtwCDt3p5G',
);
`
### Server configuration

**Operating system**: 
Debian GNU/Linux 9

**Web server:**
Server version: Apache/2.4.25 (Debian)
Server built:   2017-07-18T18:37:33

**Database:**
mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**

PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
I think: 12 RC4

**Updated from an older Nextcloud/ownCloud or fresh install:**
from 12 beta 

**Where did you install Nextcloud from:**
Web Updater

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list

doesn't work. Throws the same error.

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

```
Insert your Nextcloud log here

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:61
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/owncloud/lib/private/DB/ConnectionFactory.php(150): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/owncloud/lib/private/Server.php(579): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/owncloud/lib/private/Server.php(1332): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/owncloud/lib/private/Server.php(308): OC\Server->getDatabaseConnection()
#17 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/owncloud/lib/private/Server.php(312): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#22 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#26 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Authenticati...')
#27 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/owncloud/lib/private/Server.php(328): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#31 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
#32 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\IUserSessio...')
#33 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#34 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('UserSession')
#35 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#36 /var/www/owncloud/lib/private/Server.php(1207): OC\ServerContainer->query('UserSession')
#37 /var/www/owncloud/lib/private/Server.php(930): OC\Server->getSession()
#38 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#39 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Security\\CSR...')
#40 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Security\\CSR...')
#41 /var/www/owncloud/lib/private/Server.php(926): OC\ServerContainer->query('OC\\Security\\CSR...')
#42 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#43 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('CsrfTokenManage...')
#44 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('CsrfTokenManage...')
#45 /var/www/owncloud/lib/private/Server.php(1680): OC\ServerContainer->query('CsrfTokenManage...')
#46 /var/www/owncloud/lib/private/Server.php(760): OC\Server->getCsrfTokenManager()
#47 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#48 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\IRequest')
#49 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IRequest')
#50 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\IRequest')
#51 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#52 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('Request')
#53 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('Request')
#54 /var/www/owncloud/lib/private/Server.php(1074): OC\ServerContainer->query('Request')
#55 /var/www/owncloud/lib/private/Server.php(407): OC\Server->getRequest()
#56 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#57 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\L10N\\IFacto...')
#58 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\L10N\\IFacto...')
#59 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\L10N\\IFacto...')
#60 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#61 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('L10NFactory')
#62 /var/www/owncloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('L10NFactory')
#63 /var/www/owncloud/lib/private/Server.php(1261): OC\ServerContainer->query('L10NFactory')
#64 /var/www/owncloud/lib/private/Server.php(1272): OC\Server->getL10NFactory()
#65 /var/www/owncloud/lib/base.php(225): OC\Server->getL10N('lib')
#66 /var/www/owncloud/lib/base.php(678): OC::checkConfig()
#67 /var/www/owncloud/lib/base.php(1086): OC::init()
#68 /var/www/owncloud/console.php(56): require_once('/var/www/ownclo...')
#69 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
```

```
I

**Comment by LukasReschke** [comment]
This is caused by a missing PHP module, likely pdo_mysql. As this is not a bug in our software but an issue in your infrastructure please open this as https://help.nextcloud.com/ instead.

**Comment by anmol26s** [comment]
@FrankMaute You can try php5 , it worked for me.

**Comment by MaxGitHubAccount** [comment]
I would ask to re-open this ticket.
I just tried to install Nextcloud 16 as a test with debian buster on a test machine with my productive system as a copy.

So I copied the files from the official nextcloud download page into the old folder - set the permissions for www-data and saw that it at least needs php7.1 which wasn't there with stretch yet so I updated to buster (not yet debian stable) with php7.3.
This leads to:
"An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:64"

For obvious reasons I cannot use PHP5.6 as suggested here, as NC16 requieres at least PHP7.1

Debian Buster
PHP 7.3.4-2 (cli) (built: Apr 13 2019 19:05:48) ( NTS )
Server version: Apache/2.4.38 (Debian)
Server version: 10.3.14-MariaDB-1 Debian buildd-unstable
Nextcloud 15.07 via updater app + nextcloud 16 from website copied and overwritten
running in lxd

**Comment by kesselb** [comment]
> This is caused by a missing PHP module, likely pdo_mysql. As this is not a bug in our software but an issue in your infrastructure please open this as https://help.nextcloud.com/ instead.

@MaxGitHubAccount

**Comment by MaxGitHubAccount** [comment]
> > This is caused by a missing PHP module, likely pdo_mysql. As this is not a bug in our software but an issue in your infrastructure please open this as https://help.nextcloud.com/ instead.
> 
> @MaxGitHubAccount

Thank you @kesselb for the response - I have checked all my modules - my error was that I thought that the bug reporter with "php -i | grep "pdo"" would have already checked that module - in fact quite a lot of modules were missing on my installation (compared to https://docs.nextcloud.com/server/16/admin_manual/installation/source_installation.html) Would it be possible to maybe have a more explainatory error message in this case instead of an exception with stacktrace?

Thanks

**Comment by vergissmiNET** [comment]
apt install php7.4-mysql

... did solve this issue for me after upgrading ubuntu from 18.04 to 20.04

**Comment by yangyang5214** [comment]
My case:
```
pi@raspberrypi:~/cloud/nextcloud$ php occ
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: could not find driver in /home/pi/cloud/nextcloud/lib/private/DB/Connection.php:67
Stack trace:
#0 /home/pi/cloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(889): OC\DB\Connection->connect()
#1 /home/pi/cloud/nextcloud/lib/private/DB/Connection.php(194): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM "...', Array, Array, NULL)
#2 /home/pi/cloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(200): OC\DB\Connection->executeQuery('SELECT * FROM "...', Array, Array)
#3 /home/pi/cloud/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(216): Doctrine\DBAL\Query\QueryBuilder->execute()
#4 /home/pi/cloud/nextcloud/lib/private/AppConfig.php(331): OC\DB\QueryBuilder\QueryBuilder->execute()
#5 /home/pi/cloud/nextcloud/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
#6 /home/pi/cloud/nextcloud/lib/private/AppConfig.php(287): OC\AppConfig->getApps()
#7 /home/pi/cloud/nextcloud/lib/private/legacy/OC_App.php(883): OC\AppConfig->getValues(false, 'installed_versi...')
#8 /home/pi/cloud/nextcloud/lib/private/Server.php(665): OC_App::getAppVersions()
#9 /home/pi/cloud/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#10 /home/pi/cloud/nextcloud/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
#11 /home/pi/cloud/nextcloud/lib/private/Server.php(1704): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#12 /home/pi/cloud/nextcloud/lib/private/Server.php(856): OC\Server->getMemCacheFactory()
#13 /home/pi/cloud/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#14 /home/pi/cloud/nextcloud/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#15 /home/pi/cloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OC\\App\\AppManag...')
#16 /home/pi/cloud/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /home/pi/cloud/nextcloud/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OCP\\App\\IAppMan...')
#18 /home/pi/cloud/nextcloud/lib/private/Server.php(1894): OC\ServerContainer->query('OCP\\App\\IAppMan...')
#19 /home/pi/cloud/nextcloud/lib/private/legacy/OC_App.php(347): OC\Server->getAppManager()
#20 /home/pi/cloud/nextcloud/lib/private/legacy/OC_App.php(114): OC_App::getEnabledApps()
#21 /home/pi/cloud/nextcloud/lib/base.php(648): OC_App::loadApps(Array)
#22 /home/pi/cloud/nextcloud/lib/base.php(1095): OC::init()
#23 /home/pi/cloud/nextcloud/console.php(49): require_once('/home/pi/cloud/...')
#24 /home/pi/cloud/nextcloud/occ(11): require_once('/home/pi/cloud/...')
```


###  success

```
sudo apt install php7.3-pgsql
```

**Comment by biguenique** [comment]
That's weird, my cron jobs started failing 5 days ago (same error message), thanks to this thread I figured out I had to reinstall php7.4-mysql as well as all these modules to fix it:

```
sudo apt-get install php7.4-mysql php7.4-curl php7.4-zip php7.4-mbstring php7.4-gd php7.4-intl
```

Anybody has any cue as why it suddenly stopped working?
