### ISSUE TITLE
Object Store as primary Storage broken with NC12

### ISSUE THREAD

**Issue by Berndinox** [nextcloud/server#6400]
### Steps to reproduce
**1.**
run a fresh nextcloud instance
**2.**
Add config Part:
https://docs.nextcloud.com/server/12/admin_manual/configuration_files/primary_storage.html?highlight=primary
in my Case OpenStack Swift (OVH)
```
  'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' =>
    array (
      'username' => 'xxxxxx',
      'password' => 'xxxxxx',
      'bucket' => 'nextcloud',
      'autocreate' => true,
      'region' => 'SBG1',
      'url' => 'https://auth.cloud.ovh.net/v2.0',
      'tenantName' => 'xxxxxxxxx',
      'serviceName' => 'swift',
      'urlType' => 'internal',
    ),
  ),

```

**3.**
Receive a:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

### Expected behaviour
Object Store should be used as Default Storage

### Actual behaviour
Server Error
**Log:**
```
{"reqId":"BCU3hEI0WjraHJBnCKHo","level":3,"time":"2017-09-07 10:40:22","remoteAddr":"10.0.0.4","user":"bernd","app":"objectstore","method":"GET","url":"\/apps\/files\/","message":"Could not create object urn:oid:143 for appdata_ocadc83b19e7\/js\/core\/merged-share-backend.js.gzip: {\"Exception\":\"OCP\\\\Files\\\\StorageAuthException\",\"Message\":\"Storage unauthorized. Unknown error\",\"Code\":4,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/Swift.php(243): OC\\\\Files\\\\ObjectStore\\\\Swift->init()\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/ObjectStoreStorage.php(367): OC\\\\Files\\\\ObjectStore\\\\Swift->writeObject('urn:oid:143', Resource id #112)\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->touch('appdata_ocadc83...', 1504780822)\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(373): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('appdata_ocadc83...', NULL)\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->touch('appdata_ocadc83...', NULL)\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1136): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('appdata_ocadc83...')\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(559): OC\\\\Files\\\\View->basicOperation('touch', '\\\/appdata_ocadc8...', Array, NULL)\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(181): OC\\\\Files\\\\View->touch('\\\/appdata_ocadc8...')\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFolder.php(83): OC\\\\Files\\\\Node\\\\Folder->newFile('merged-share-ba...')\\n#9 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(159): OC\\\\Files\\\\SimpleFS\\\\SimpleFolder->newFile('merged-share-ba...')\\n#10 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('\\\/nextcloud\\\/core...', 'merged-share-ba...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#11 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('\\\/nextcloud', 'core\\\/js\\\/merged-...', 'core')\\n#12 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(65): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('\\\/nextcloud', 'core\\\/js\\\/merged-...')\\n#13 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('core\\\/js\\\/merged-...')\\n#14 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#15 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#16 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('error', '')\\n#17 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#18 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(342): OC\\\\Template\\\\Base->printPage()\\n#19 \\\/nextcloud\\\/index.php(67): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotFoundException))\\n#20 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/Swift.php\",\"Line\":109}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}
{"reqId":"BCU3hEI0WjraHJBnCKHo","level":3,"time":"2017-09-07 10:40:23","remoteAddr":"10.0.0.4","user":"bernd","app":"core","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/*\\\\n * Copyright...')\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(163): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/*\\\\n * Copyright...')\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('\\\/nextcloud\\\/core...', 'merged-share-ba...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('\\\/nextcloud', 'core\\\/js\\\/merged-...', 'core')\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(65): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('\\\/nextcloud', 'core\\\/js\\\/merged-...')\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('core\\\/js\\\/merged-...')\\n#9 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#11 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 \\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 \\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}
{"reqId":"BCU3hEI0WjraHJBnCKHo","level":3,"time":"2017-09-07 10:40:23","remoteAddr":"10.0.0.4","user":"bernd","app":"core","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/*\\\\n * Copyright...')\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(163): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/*\\\\n * Copyright...')\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('\\\/nextcloud\\\/core...', 'merged-share-ba...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('\\\/nextcloud', 'core\\\/js\\\/merged-...', 'core')\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(65): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('\\\/nextcloud', 'core\\\/js\\\/merged-...')\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('core\\\/js\\\/merged-...')\\n#9 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#11 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('error', '')\\n#12 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#13 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(342): OC\\\\Template\\\\Base->printPage()\\n#14 \\\/nextcloud\\\/index.php(67): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotFoundException))\\n#15 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}

```

### Server configuration
wonderfall/nextcloud

**Operating system**:
coreos

**Web server:**
traefik + wonderfall/nextcloud

**Database:**
mariadb

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12 (latest)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
wonderfall/nextcloud

**List of activated apps:**
default

**Nextcloud configuration:**
default

**Comment by Berndinox** [comment]
After reading:
https://github.com/nextcloud/server/issues/5865

i changed the urtype, aswell as removed it, still got loads of errors!

```
{"reqId":"qOuGbsqnvADmW9Imb8US","level":3,"time":"2017-09-07 11:05:55","remoteAddr":"10.0.0.4","user":"--","app":"core","method":"GET","url":"\/login","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('(function($) {\\\\n...')\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(163): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('(function($) {\\\\n...')\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('\\\/nextcloud\\\/core...', 'merged-template...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('\\\/nextcloud', 'core\\\/js\\\/merged-...', 'core')\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(68): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('\\\/nextcloud', 'core\\\/js\\\/merged-...')\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('js\\\/merged-templ...')\\n#9 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#11 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('error', '')\\n#12 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#13 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(342): OC\\\\Template\\\\Base->printPage()\\n#14 \\\/nextcloud\\\/index.php(67): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotFoundException))\\n#15 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}
{"reqId":"u5sY0fKQ1u3SL8GGY7MC","level":3,"time":"2017-09-07 11:07:30","remoteAddr":"10.0.0.4","user":"--","app":"index","method":"GET","url":"\/login","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 1 passed to OC\\\\Files\\\\ObjectStore\\\\Swift::getCatalogForService() must be an instance of OpenCloud\\\\Common\\\\Service\\\\Catalog, null given, called in \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/Swift.php on line 133\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/Swift.php(133): OC\\\\Files\\\\ObjectStore\\\\Swift->getCatalogForService(NULL, 'swift')\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/Swift.php(243): OC\\\\Files\\\\ObjectStore\\\\Swift->init()\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/ObjectStoreStorage.php(367): OC\\\\Files\\\\ObjectStore\\\\Swift->writeObject('urn:oid:17', Resource id #42)\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->touch('appdata_ocadc83...', 1504782450)\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(373): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('appdata_ocadc83...', NULL)\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->touch('appdata_ocadc83...', NULL)\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1136): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('appdata_ocadc83...')\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(559): OC\\\\Files\\\\View->basicOperation('touch', '\\\/appdata_ocadc8...', Array, NULL)\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(181): OC\\\\Files\\\\View->touch('\\\/appdata_ocadc8...')\\n#9 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFolder.php(83): OC\\\\Files\\\\Node\\\\Folder->newFile('merged-template...')\\n#10 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(146): OC\\\\Files\\\\SimpleFS\\\\SimpleFolder->newFile('merged-template...')\\n#11 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('\\\/nextcloud\\\/core...', 'merged-template...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#12 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('\\\/nextcloud', 'core\\\/js\\\/merged-...', 'core')\\n#13 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/JSResourceLocator.php(68): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('\\\/nextcloud', 'core\\\/js\\\/merged-...')\\n#14 \\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('js\\\/merged-templ...')\\n#15 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#16 \\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#17 \\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('guest', 'core')\\n#18 \\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#19 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#20 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#21 \\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'showLoginForm', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#22 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#23 \\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#24 \\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/login')\\n#25 \\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#26 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/Swift.php\",\"Line\":196}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}
{"reqId":"u5sY0fKQ1u3SL8GGY7MC","level":3,"time":"2017-09-07 11:07:30","remoteAddr":"10.0.0.4","user":"--","app":"PHP","method":"GET","url":"\/login","message":"TypeError: Argument 1 passed to OC\\Files\\ObjectStore\\Swift::getCatalogForService() must be an instance of OpenCloud\\Common\\Service\\Catalog, null given, called in \/nextcloud\/lib\/private\/Files\/ObjectStore\/Swift.php on line 133 at \/nextcloud\/lib\/private\/Files\/ObjectStore\/Swift.php#196","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}
```

**Comment by Berndinox** [comment]
For prouction use this is too buggy anyway... :(

**Comment by MorrisJobke** [comment]
Duplicate #5865 I would say. We try to enhance this. Thanks for your report anyways
