### ISSUE TITLE
Ampersand (&) in Adressbook Name causes HTTP Error 400 

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#6533]
Coming from https://github.com/nextcloud/contacts/issues/237

> ### Steps to reproduce
> 1. Add new Adressbook with ampersand (&) in name  
> 2. Does not save, no visible feedback in the interface 
> 
> ### Expected behaviour
> It should work :) and it should report failure if something goes wrong, so that the user does need to open devtools. 
> 
> ### Actual behaviour
> Error 400 - this appears in devtools: 
> 
> ```
> MKCOL https://cloud.foo.bar/remote.php/dav/addressbooks/users/mt/a&b 400 ()
> send @ dav.js?v=6904cf9…-41:3641
> callee$2$0$ @ dav.js?v=6904cf9…-41:3156
> tryCatch @ dav.js?v=6904cf9…-41:121
> invoke @ dav.js?v=6904cf9…-41:294
> Gp.(anonymous function) @ dav.js?v=6904cf9…-41:330
> onFulfilled @ dav.js?v=6904cf9…-41:3737
> (anonymous) @ dav.js?v=6904cf9…-41:3726
> co @ dav.js?v=6904cf9…-41:3722
> send @ dav.js?v=6904cf9…-41:3134
> createCollection @ dav.js?v=6904cf9…-41:3453
> createAddressBook @ dav.js?v=6904cf9…-41:1696
> createAddressBook @ dav.js?v=6904cf9…-41:1492
> (anonymous) @ addressBook_service.js:58
> dav.js?v=6904cf9…-41:3649 Uncaught (in promise) Error: Bad status: 400
>     at XMLHttpRequest.request.onreadystatechange (dav.js?v=6904cf9…-41:3649)
> ```
> 
> Server logfile: 
> ```json
> {
>   "reqId": "k4P13g7cmlCRSrWPCRVj",
>   "level": 4,
>   "time": "2017-06-20T22:01:17+00:00",
>   "remoteAddr": "xxx",
>   "user": "mt",
>   "app": "webdav",
>   "method": "MKCOL",
>   "url": "/remote.php/dav/addressbooks/users/mt/A&B",
>   "message": "Exception: {\"Message\":\"HTTP\\/1.1 400 EntityRef: expecting ';'\\n on line 9, column 37\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 [intern
> al function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\/var\\/www\\/nextcloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitte
> rTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\/var\\/www\\/nextcloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)
> \\n#3 \\/var\\/www\\/nextcloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4
>  \\/var\\/www\\/nextcloud\\/apps\\/dav\\/lib\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\/var\\/www\\/nextcloud\\/apps\\/dav\\/appinfo\\/v2\\/remote.php(33): OCA\\\\DAV\\\\Server->exec
> ()\\n#6 \\/var\\/www\\/nextcloud\\/remote.php(162): require_once('\\/var\\/www\\/nextcl...')\\n#7 {main}\",\"File\":\"\\/var\\/www\\/nextcloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php\
> ",\"Line\":570,\"User\":\"foo@bar\"}",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36",
>   "version": "12.0.0.29"
> }
> ```
> ### Server configuration
> Nextcloud 12 - current Contacts app (1.5.3), PHP 7.1, nginx, PHP-FPM 
> 
> ### Client configuration
> **Browser:**
> Chrome 59, Win10

**Comment by skjnldsv** [comment]
> Filing this here because I think the error is coming from the contacts app. Looks like a missing excape in the Ajax request.

Tried with escaping and with cadaver, still doesn't work. The ampersand is refused by the server :)

**Comment by skjnldsv** [comment]
Fixed now
