### ISSUE TITLE
Swift Storage big file upload erros (incorrect chunk size?)

### ISSUE THREAD

**Issue by leonidasv** [nextcloud/server#6592]
### Steps to reproduce
1. Set a Swift Backend as default
2. Try uploading a file bigger than 5Gb

### Expected behaviour
The file should be uploaded.

### Actual behaviour
The file suddenly disappears after the upload is complete. Looking into the logs, the Swift Server is returning error 413 “Request Entity Too Large”.

I looked into the source code and found the "AbstractTransfer.php" library from Rackspace. It limits the upload max size to 5Gb (the max. Swift can handle). However, the Nextcloud server seens to be bypassing this configuration and trying to upload big files in one chunk. This leads to Swift backend rejecting the file.

### Server configuration

**Operating system**: Ubuntu 16.04.3

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.0-fpm

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** manual

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"SjzOZTudfP7hstVIvbpF","level":4,"time":"2017-09-20T15:49:26+00:00","remoteAddr":"159.203.65.245","user":"leonidas","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/bigfile.bin","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Client error response\\n[status code] 413\\n[reason phrase] Request Entity Too Large\\n[url] https:\\\/\\\/storage.bhs3.cloud.ovh.net\\\/v1\\\/AUTH_b36dc1647f3743a283ab3cb158947e75\\\/nextcloud\\\/urn:oid:406342\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(159): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(Guzzle\\\\Http\\\\Exception\\\\ClientErrorResponseException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #88)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('bigfile.bin', Resource id #88)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('bigfile.bin', Resource id #88, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":567}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/60.0.3112.113 Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.2.0"}
```
</details>

**Comment by nickvergessen** [comment]
@icewind1991 is this solved by https://github.com/nextcloud/server/pull/6602 ?

**Comment by leonidasv** [comment]
@nickvergessen nice solution for S3. Could this be easily adapted for Swift (I read the code  and found no mention to Swift, I think it only concerns to S3, right?)? 

I can make some tests with my Swift Storage to help.

**Comment by leonidasv** [comment]
Any news?

**Comment by skjnldsv** [comment]
Still happening?
