### ISSUE TITLE
Internal Server Error after upgrade to 12 - file not found

### ISSUE THREAD

**Issue by agilob** [nextcloud/server#6712]
### Steps to reproduce
1. Update from 11 to 12

### Expected behaviour
Tell us what should happen
After upgrading from 11 to 12 I'm getting 
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```
each time I visit nextcloud

### Server configuration

**Operating system**:
Debian

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
12.x.x cant visit admin page

**Updated from an older Nextcloud/ownCloud or fresh install:**
11

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
can't
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - tasks: 0.9.5
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - comments
  - documents
  - encryption
  - federation
  - files_external
  - files_trashbin
  - files_versions
  - firstrunwizard
  - hls_streamplayer
  - html5_videoplayer
  - notifications
  - ownnote
  - password_policy
  - survey_client
  - systemtags
  - theming
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "xxxxxxxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "overwrite.cli.url": "xxxxxx",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "xxxxx",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
fx

**Operating system:**

#### Web server error log
```
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\xxx/appdata_oci4ro44d792\/js\/core\/merged-template-prepend.js.deps): failed to open stream: No such file or directory at xxx/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at xxx/private\/Template\/JSCombiner.php#107","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \xxx/appdata_oci4ro44d792\/js\/core\/merged-share-backend.js because No such file or directory at xxx/private\/Files\/Storage\/Local.php#199","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \xxx/appdata_oci4ro44d792\/js\/core\/merged-share-backend.js.deps because No such file or directory at xxx/private\/Files\/Storage\/Local.php#199","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \xxx/appdata_oci4ro44d792\/js\/core\/merged-share-backend.js.gzip because No such file or directory at xxx/private\/Files\/Storage\/Local.php#199","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 xxxxxxxxx/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/*\\\\n * Copyright...')\\n#4 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSCombiner.php(163): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/*\\\\n * Copyright...')\\n#5 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('xxxxxxxxx/...', 'merged-share-ba...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#6 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('xxxxxxxxx', 'core\\\/js\\\/merged-...', 'core')\\n#7 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSResourceLocator.php(65): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('xxxxxxxxx', 'core\\\/js\\\/merged-...')\\n#8 xxxxxxxxx/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('core\\\/js\\\/merged-...')\\n#9 xxxxxxxxx/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 xxxxxxxxx/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#11 xxxxxxxxx/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 xxxxxxxxx/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 xxxxxxxxx/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 xxxxxxxxx/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 xxxxxxxxx/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 xxxxxxxxx/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 xxxxxxxxx/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 xxxxxxxxx/index.php(48): OC::handleRequest()\\n#20 {main}\",\"File\":\"xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\xxx/appdata_oci4ro44d792\/js\/core\/merged-template-prepend.js.deps): failed to open stream: No such file or directory at xxx/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at xxx/private\/Template\/JSCombiner.php#107","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \xxx/appdata_oci4ro44d792\/js\/core\/merged-share-backend.js because No such file or directory at xxx/private\/Files\/Storage\/Local.php#199","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \xxx/appdata_oci4ro44d792\/js\/core\/merged-share-backend.js.deps because No such file or directory at xxx/private\/Files\/Storage\/Local.php#199","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \xxx/appdata_oci4ro44d792\/js\/core\/merged-share-backend.js.gzip because No such file or directory at xxx/private\/Files\/Storage\/Local.php#199","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 xxxxxxxxx/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/*\\\\n * Copyright...')\\n#4 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSCombiner.php(163): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/*\\\\n * Copyright...')\\n#5 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('xxxxxxxxx/...', 'merged-share-ba...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#6 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('xxxxxxxxx', 'core\\\/js\\\/merged-...', 'core')\\n#7 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSResourceLocator.php(65): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('xxxxxxxxx', 'core\\\/js\\\/merged-...')\\n#8 xxxxxxxxx/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('core\\\/js\\\/merged-...')\\n#9 xxxxxxxxx/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 xxxxxxxxx/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#11 xxxxxxxxx/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 xxxxxxxxx/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 xxxxxxxxx/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 xxxxxxxxx/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 xxxxxxxxx/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 xxxxxxxxx/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 xxxxxxxxx/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 xxxxxxxxx/index.php(48): OC::handleRequest()\\n#20 {main}\",\"File\":\"xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"TyrdgwvmwpKQMdojhMcM","level":3,"time":"2017-09-30T20:24:01+00:00","remoteAddr":"xxx","user":"xxx","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 xxxxxxxxx/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/*\\\\n * Copyright...')\\n#4 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSCombiner.php(163): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/*\\\\n * Copyright...')\\n#5 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSCombiner.php(89): OC\\\\Template\\\\JSCombiner->cache('xxxxxxxxx/...', 'merged-share-ba...', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder))\\n#6 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSResourceLocator.php(105): OC\\\\Template\\\\JSCombiner->process('xxxxxxxxx', 'core\\\/js\\\/merged-...', 'core')\\n#7 xxxxxxxxx/lib\\\/private\\\/Template\\\/JSResourceLocator.php(65): OC\\\\Template\\\\JSResourceLocator->cacheAndAppendCombineJsonIfExist('xxxxxxxxx', 'core\\\/js\\\/merged-...')\\n#8 xxxxxxxxx/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\JSResourceLocator->doFind('core\\\/js\\\/merged-...')\\n#9 xxxxxxxxx/lib\\\/private\\\/TemplateLayout.php(249): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 xxxxxxxxx/lib\\\/private\\\/TemplateLayout.php(132): OC\\\\TemplateLayout::findJavascriptFiles(Array)\\n#11 xxxxxxxxx/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('error', '')\\n#12 xxxxxxxxx/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#13 xxxxxxxxx/lib\\\/private\\\/legacy\\\/template.php(342): OC\\\\Template\\\\Base->printPage()\\n#14 xxxxxxxxx/index.php(67): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotFoundException))\\n#15 {main}\",\"File\":\"xxxxxxxxx/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
```

**Comment by xdaYnax** [comment]
I had same problem.
I deleted appdata_XXXX/css and nextcloud regenereted it.

**Comment by nickvergessen** [comment]
Yeah make sure the chmod and chown are set correctly

**Comment by agilob** [comment]
@xdaYnax Didn't help me.

@nickvergessen 

> failed to open stream: No such file or directory at xxx/private\/Files\/Storage\/Local.php#20

this is clearly a problem with updater removing something it shouldn't. I didn't change chowns since last time updated crashed which was upgrade from 10.x to 11.x
