### ISSUE TITLE
Internal Server Error when trying to log in with not-previously logged in user

### ISSUE THREAD

**Issue by koelle25** [nextcloud/server#6956]
### Steps to reproduce
1. Login with a not-previously logged-in (LDAP-) user

### Expected behaviour
`/storage/nextcloud/<uuid>/cache` and `/storage/nextcloud/<uuid>/files` should be created and startpage (`/apps/files`) should be displayed.

### Actual behaviour
Stops with Internal Server Error.
Only `/storage/nextcloud/<uuid>/cache` gets created.
`/storage/nextcloud` and everything in it belongs to `www-data:www-data`. No access-rights have manually being changed (`/storage/nextcloud` has 770, `/storage/nextcloud/<uuid>` has 755).
Same error on subsequent logins with this user. Also happens with locally created user using admin-panel.
After creating the `files` directory manually (by `sudo -u www-data mkdir /storage/nextcloud/<uuid>/files`) everything works normally.

### Server configuration

**Operating system:** Ubuntu Server 16.04.3 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.20

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** From *.tar.bz2 (checked with SHA-256 and GPG)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - theming
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc4w3a8dwcka",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.22.167.162"
        ],
        "datadirectory": "\/storage\/nextcloud",
        "overwrite.cli.url": "http:\/\/172.22.167.162\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration
<details>
<summary>LDAP config</summary>

```
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                                        |
| hasPagedResultSupport         |                                                                                                                                          |
| homeFolderNamingRule          |                                                                                                                                          |
| lastJpegPhotoLookup           | 0                                                                                                                                        |
| ldapAgentName                 | cn=nextcloud,ou=systemUsers,dc=ohs,dc=fh                                                                                                 |
| ldapAgentPassword             | ***                                                                                                                                      |
| ldapAttributesForGroupSearch  | cn                                                                                                                                       |
| ldapAttributesForUserSearch   | uid;givenName;sn;cn                                                                                                                      |
| ldapBackupHost                |                                                                                                                                          |
| ldapBackupPort                |                                                                                                                                          |
| ldapBase                      | dc=ohs,dc=fh                                                                                                                             |
| ldapBaseGroups                | ou=groups,dc=ohs,dc=fh                                                                                                                   |
| ldapBaseUsers                 | ou=users,dc=ohs,dc=fh                                                                                                                    |
| ldapCacheTTL                  | 600                                                                                                                                      |
| ldapConfigurationActive       | 1                                                                                                                                        |
| ldapDefaultPPolicyDN          |                                                                                                                                          |
| ldapDynamicGroupMemberURL     | uniqueMember                                                                                                                             |
| ldapEmailAttribute            | mail                                                                                                                                     |
| ldapExperiencedAdmin          | 0                                                                                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                                                                                          |
| ldapExpertUUIDUserAttr        |                                                                                                                                          |
| ldapExpertUsernameAttr        |                                                                                                                                          |
| ldapGidNumber                 | gidNumber                                                                                                                                |
| ldapGroupDisplayName          | cn                                                                                                                                       |
| ldapGroupFilter               | (&(|(objectclass=groupOfUniqueNames)))                                                                                                   |
| ldapGroupFilterGroups         |                                                                                                                                          |
| ldapGroupFilterMode           | 0                                                                                                                                        |
| ldapGroupFilterObjectclass    | groupOfUniqueNames                                                                                                                       |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                             |
| ldapHost                      | 172.22.166.211                                                                                                                           |
| ldapIgnoreNamingRules         |                                                                                                                                          |
| ldapLoginFilter               | (&(&(objectclass=inetOrgPerson)(memberof=cn=nextcloudUsers,ou=groups,dc=ohs,dc=fh))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                          |
| ldapLoginFilterEmail          | 1                                                                                                                                        |
| ldapLoginFilterMode           | 0                                                                                                                                        |
| ldapLoginFilterUsername       | 1                                                                                                                                        |
| ldapNestedGroups              | 0                                                                                                                                        |
| ldapOverrideMainServer        |                                                                                                                                          |
| ldapPagingSize                | 500                                                                                                                                      |
| ldapPort                      | 389                                                                                                                                      |
| ldapQuotaAttribute            |                                                                                                                                          |
| ldapQuotaDefault              |                                                                                                                                          |
| ldapTLS                       | 0                                                                                                                                        |
| ldapUserDisplayName           | cn                                                                                                                                       |
| ldapUserDisplayName2          | mail                                                                                                                                     |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(memberof=cn=nextcloudUsers,ou=groups,dc=ohs,dc=fh))                                                        |
| ldapUserFilterGroups          |                                                                                                                                          |
| ldapUserFilterMode            | 1                                                                                                                                        |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                                                                     |
| ldapUuidUserAttribute         | auto                                                                                                                                     |
| turnOffCertCheck              | 0                                                                                                                                        |
| turnOnPasswordChange          | 0                                                                                                                                        |
| useMemberOfToDetectMembership | 1                                                                                                                                        |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Google Chrome 61.0.3163.100

**Operating system:** Windows 10 (Version 1703, Build 15063.674)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
<nothing here>
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  "reqId": "Vxv2Zy5FE3gxAbhEnlki",
  "level": 3,
  "time": "2017-10-25T13:39:56+00:00",
  "remoteAddr": "172.22.167.92",
  "user": "b9d49384-ecc3-1035-8530-5f0966054c98",
  "app": "index",
  "method": "GET",
  "url": "\/nextcloud\/apps\/files\/",
  "message": "Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}",
  "userAgent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36",
  "version": "12.0.3.3"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 172.22.167.92
Request ID: Vxv2Zy5FE3gxAbhEnlki
```

```
JQMIGRATE: Migrate is installed, version 1.4.0
merged-share-backend.js?v=95bd09bac580cba004665315a49b6c1f:24 Uncaught ReferenceError: oc_appconfig is not defined
    at merged-share-backend.js?v=95bd09bac580cba004665315a49b6c1f:24
    at merged-share-backend.js?v=95bd09bac580cba004665315a49b6c1f:80
(anonymous) @ merged-share-backend.js?v=95bd09bac580cba004665315a49b6c1f:24
(anonymous) @ merged-share-backend.js?v=95bd09bac580cba004665315a49b6c1f:80
merged-template-prepend.js?v=95bd09bac580cba004665315a49b6c1f:1349 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (merged-template-prepend.js?v=95bd09bac580cba004665315a49b6c1f:1349)
    at viewer.js?v=95bd09bac580cba004665315a49b6c1f:15
filePath @ merged-template-prepend.js?v=95bd09bac580cba004665315a49b6c1f:1349
(anonymous) @ viewer.js?v=95bd09bac580cba004665315a49b6c1f:15
172.22.167.162/:1 GET http://172.22.167.162/nextcloud/apps/files/ 500 (Internal Server Error)
Image (async)
buildFragment @ core.js?v=95bd09bac580cba004665315a49b6c1f:3
n.parseHTML @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
a.fn.init @ core.js?v=95bd09bac580cba004665315a49b6c1f:7
n @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
initialise @ merged.js?v=95bd09bac580cba004665315a49b6c1f:89
(anonymous) @ merged.js?v=95bd09bac580cba004665315a49b6c1f:485
j @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
fireWith @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
ready @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
I @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
core.js?v=95bd09bac580cba004665315a49b6c1f:4 GET http://172.22.167.162/nextcloud/apps/files/ 500 (Internal Server Error)
send @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
ajax @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
_fetch @ merged.js?v=95bd09bac580cba004665315a49b6c1f:431
initialFetch @ merged.js?v=95bd09bac580cba004665315a49b6c1f:201
initialise @ merged.js?v=95bd09bac580cba004665315a49b6c1f:97
(anonymous) @ merged.js?v=95bd09bac580cba004665315a49b6c1f:485
j @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
fireWith @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
ready @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
I @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
merged.js?v=95bd09bac580cba004665315a49b6c1f:273 Shutting down notifications: [500] Internal Server Error
_onFetchError @ merged.js?v=95bd09bac580cba004665315a49b6c1f:273
j @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
fireWith @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
x @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
(anonymous) @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
XMLHttpRequest.send (async)
send @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
ajax @ core.js?v=95bd09bac580cba004665315a49b6c1f:4
_fetch @ merged.js?v=95bd09bac580cba004665315a49b6c1f:431
initialFetch @ merged.js?v=95bd09bac580cba004665315a49b6c1f:201
initialise @ merged.js?v=95bd09bac580cba004665315a49b6c1f:97
(anonymous) @ merged.js?v=95bd09bac580cba004665315a49b6c1f:485
j @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
fireWith @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
ready @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
I @ core.js?v=95bd09bac580cba004665315a49b6c1f:2
```
</details>

**Comment by koelle25** [comment]
May be the same as or similar to #6701

**Comment by koelle25** [comment]
Maybe has sth. to do with #1862

**Comment by koelle25** [comment]
It seems I have solved it. My Redis-Server wasn't configured to create a Unix-Socket.

After reconfiguring everything works as expected.

**Comment by serverhack74** [comment]
Can you explain how you solved it? I have the same issue after upgrading to version 13. When a newly ldap user logs in the system creates the 'cache' and 'files_encryption' only, no 'files' or other directory and he receives an Internal Server Error.

Thanks and best regards!!!

**Comment by koelle25** [comment]
See above, I had configured Nextcloud to use Redis via socket, but my Redis-Server was only listening on IP/Port. After reconfiguration (either pointing the Nextcloud config to `localhost:<port>` or making Redis listen on socket) everything worked fine.

**Comment by whgandalf** [comment]
I solved it doing this:

https://guides.wp-bullet.com/how-to-configure-redis-to-use-unix-socket-speed-boost/
