### ISSUE TITLE
"Updates between multiple major versions and downgrades are unsupported" 11.0.3 -> 11.0.5

### ISSUE THREAD

**Issue by gjedeer** [nextcloud/server#7097]
### Steps to reproduce
1. Use nextcloud 11.0.3
2. Upgrade using the web app with production channel, or manually to 11.0.5 (both ways tried)

### Expected behaviour
11.0.5 version installed

### Actual behaviour

On db update step:
```
Preparing update
Set log level to debug
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. For more information check our forum post covering this issue.
```

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** mariadb 10.0.31-0ubuntu0.16.04.2

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.6
  - comments: 1.1.0
  - contacts: 2.0.1
  - dav: 1.1.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ojsxc: 3.3.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: true
Disabled:
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_reader
  - files_retention
  - ownbackup
  - tasks
  - unsplash
  - user_external
  - user_ldap
  - user_saml

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "\/srv\/owncloud-data",
        "dbtype": "sqlite3",
        "version": "11.0.3.2",
        "installedat": "1328029564.0652",
        "lastupdatedat": "1342961822.3781",
        "installed": true,
        "instanceid": "51c89bd926532",
        "maintenance": false,
        "forcessl": true,
        "defaultapp": "calendar",
        "remote_core.css": "\/core\/minimizer.php",
        "remote_core.js": "\/core\/minimizer.php",
        "theme": "",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "share_folder": "\/Shared",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "log_type": "owncloud",
        "logfile": "\/srv\/owncloud-data\/owncloud.log",
        "check_for_working_webdav": false,
        "mail_smtpdebug": true,
        "mail_from_address": "owncloud",
        "mail_domain": "gdr.name",
        "enable_previews": true,
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "dbindex": 2
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium on Linux, but fails also over ssh

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(empty)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"updater","message":"\\OC\\Updater::setDebugLogLevel: Set log level to debug","level":1,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"updater","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","level":1,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"core","message":"starting upgrade from 11.0.3.2 to 11.0.5.1","level":0,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/Updater.php(140): OC\\\\Updater->doUpgrade('11.0.5.1', '11.0.3.2')\\n#1 \\\/var\\\/www\\\/core\\\/Command\\\/Upgrade.php(261): OC\\\\Updater->upgrade()\\n#2 \\\/var\\\/www\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(256): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#3 \\\/var\\\/www\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(818): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#4 \\\/var\\\/www\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(186): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(117): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/lib\\\/private\\\/Console\\\/Application.php(169): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/console.php(98): OC\\\\Console\\\\Application->run()\\n#8 \\\/var\\\/www\\\/occ(11): require_once('\\\/var\\\/www\\\/consol...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/Updater.php\",\"Line\":233}","level":3,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"updater","message":"\\OC\\Updater::failure: Exception: Updates between multiple major versions and downgrades are unsupported.","level":3,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"updater","message":"\\OC\\Updater::updateEnd: Update failed","level":3,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"updater","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","level":1,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"GjOgIYVgf3RZkIQCnRuf","remoteAddr":"","app":"updater","message":"\\OC\\Updater::resetLogLevel: Reset log level to Debug(0)","level":1,"time":"2017-11-07T14:13:20+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
```
</details>

**Comment by MorrisJobke** [comment]
cc @rullzer @nickvergessen Ideas? the config.php looks good :/

**Comment by MorrisJobke** [comment]
Also `starting upgrade from 11.0.3.2 to 11.0.5.1` indicates, that everything should be fine.

**Comment by nickvergessen** [comment]
No idea, https://github.com/nextcloud/server/blob/stable11/version.php#L37

**Comment by gjedeer** [comment]
Could it be that for some reason I don't have `$currentVendor` set and I'm hitting this branch? 

https://github.com/nextcloud/server/blob/v11.0.3/lib/private/Updater.php#L209

My current version (11.0.3.2) doesn't seem to be on 11.0.5's valid version list. That list is checked if currentVendor is empty
https://github.com/nextcloud/server/blob/v11.0.5/lib/private/Updater.php#L74

I'm not sure how to check my $currentVendor value, though, I'm unable to track where getSystemValue() is getting its data from.

**Comment by gjedeer** [comment]
Added some echo statements to that function and it seems currentVendor is indeed empty:

```
== CURRENT VENDOR: 
== OLD VERSION: 11.0.3.2
== NEW VERSION: 11.0.5.1
```

Still unsure how to make it non-empty or where it's being read from

**Comment by nickvergessen** [comment]
It's set on update and installation.
You can set it manually by running the following sql command on your database:
```sql
INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('core', 'vendor', 'nextcloud');
```

**Comment by gjedeer** [comment]
Thank you.

I'll do it, but if it's supposed to be set automatically, it hasn't happened. I've been running this instance since ownCloud 3 or 4, and I've had Nextcloud upgrades before, too. `vendor` has never been set during any of these upgrades.

**Comment by nickvergessen** [comment]
The code to set the vendor is there since 11:
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Updater.php#L298

So not sure how you ended up there without it.
But glad that setting it fixed the issue.
