### ISSUE TITLE
Services registered in app container are not available during update repair steps

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#7133]
When running an app update from the app store, dependency injection in repair steps doesn't use the app container. That way custom services are not available and the update fails silently and nextcloud is locked in maintenance mode.

It only happens when update is triggered though settings/ajax/updateapp.php

On 12, NC11 doesn't seem to be affected.

This occured in deck: https://github.com/nextcloud/deck/issues/340

In deck we have a service registered in our AppInfo\Application class:

```
$container->registerService('databaseType', function($container) {
	return $container->getServer()->getConfig()->getSystemValue('dbtype', 'sqlite');
});
```

Injecting $databaseType doesn't work in a repairstep that is run during update of the app.

Exception thrown
```
{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Deck\\Migration\\UnknownUsers::__construct() must implement interface OCP\\IUserManager, none given, called in \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/Repair.php on line 105","Code":0,"Trace":"#0 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/Repair.php(105): OCA\\Deck\\Migration\\UnknownUsers->__construct()
#1 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/legacy\\/app.php(1106): OC\\Repair->addStep('OCA\\\\Deck\\\\Migrat...')
#2 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/legacy\\/app.php(1049): OC_App::executeRepairSteps('deck', Array)
#3 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/Installer.php(200): OC_App::updateApp('deck')
#4 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/settings\\/ajax\\/updateapp.php(50): OC\\Installer->updateAppstoreApp('deck')
#5 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/Route\\/Route.php(155) : runtime-created function(1): require_once('\\/mnt\\/raid1\\/clou...')
#6 [internal function]: __lambda_func(NULL)
#7 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/private\\/Route\\/Router.php(299): call_user_func('\\x00lambda_265', Array)
#8 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/lib\\/base.php(1004): OC\\Route\\Router->match('\\/settings\\/ajax\\/...')
#9 \\/mnt\\/raid1\\/cloud\\/nextcloud\\/index.php(48): OC::handleRequest()
#10 {main}","File":"\\/mnt\\/raid1\\/cloud\\/nextcloud\\/apps\\/deck\\/lib\\/Migration\\/UnknownUsers.php","Line":43}
```

**Comment by szaimen** [comment]
I suppose this issue is still valid?
