### ISSUE TITLE
WebDAV - Protocol Violation - No Authorization: Basic header found

### ISSUE THREAD

**Issue by tmaff** [nextcloud/server#7349]
### Steps to reproduce
1. Start the WebDAV App
2. Go into the folder and upload a file

### Expected behaviour
Upload the file into the folder

### Actual behaviour
Sometimes test file created but the app and an other webinterface get an error ..

### Server configuration

**Operating system**: Linux democloud.mydomain.de 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** nginx/1.6.3

**Database:** 5.5.56-MariaDB 

**PHP version:** PHP 7.0.25 (cli) (built: Oct 29 2017 13:43:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.25, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** download the zip file and extract ..

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap</summary>
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oczz4md6jdz7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "democloud.mydomain.de"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/democloud.mydomain.de",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "democloud",
        "mail_domain": "mydomain.de",
        "mail_smtphost": "mail.mydomain.de",
        "mail_smtpport": "25",
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "3",
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "F d, Y H:i:s"
    }
}
```
</summary>
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... : NO

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox, Iexplore, Google Chrome

**Operating system:** Windows 10, Debian, Centos ...

#### Web server error log
<details>
<summary>Web server error log</summary>

```
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"hnTuyJzsRkuBDZTKarmz","level":0,"time":"November 29, 2017 15:53:38","remoteAddr":"XX","user":"--","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/test\/Test\/Test_683b953330e54c73b45e179a9902bcde","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}","userAgent":"--","version":"12.0.3.3"}
```
</details>

#### Browser log
<details>
<summary>Tools log</summary>

```
1: ServerProtocolViolation: No http standard. Header are not terminated by cr and lf

2: Rei.Fs.SimpleWebException: Der Server hat eine Protokollverletzung ausgeführt.. Section=ResponseHeader Detail=Auf CR muss LF folgen
   bei Rei.Fs.Webdav.WebdavFs.GetResponse(HttpWebRequest 
```
</details>

Any ideas? With Windows explorer it works but i readed that windows ignore many failures!

**Comment by MorrisJobke** [comment]
>  WebDAV - Protocol Violation - No Authorization: Basic header found

This does only mean that it used the wrong authentication credentials.

All the provided logs don't contain any crucial information to properly debug this. I tried to reproduce this, but failed to do so. All works smooth here.

I will close this ticket for now. If you have more information on how to reporduce this, please let us know.

Thanks
