### ISSUE TITLE
personal profile not saving 

### ISSUE THREAD

**Issue by hantk8** [nextcloud/server#7411]
i can't change the emailadres on my install 
tried it on v11 and latest v12

### Steps to reproduce
1. logged in as admin
2. goto your url/index.php/settings/personal
3. click emailfield an fill with address
 

### Expected behaviour
the emailaddress should get saved but it doesn't
### Actual behaviour
the emailaddress doesn't get saved

### Server configuration

**Operating system**:
CENTOS
**Web server:**
Apache 2.4.29

**Database:**
MySQL 5.6.38

**PHP version:**
Php 7.0.26
**Nextcloud version:** (see Nextcloud admin page)
tested on 11 and 12
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installed 
**Where did you install Nextcloud from:**
from installer file and download zip
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (

  'trusted_domains' => 
  array (
  ),

  'dbtype' => 'mysql',
  'version' => '11.0.6.1',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
    'allow_user_to_change_display_name' => true,

);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Wigsiq4ajQWD32yoALPPMwAAAP4","remoteAddr":"87.67.106.172","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given object name is invalid\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(906): OC\\\\Activity\\\\Event->setObject('files', 2, false)\\n#1 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(191): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('hankila', 'created_self', Array, 2, false, true, true, 0, 'file_created')\\n#2 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(117): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/', 'file_created', 'created_self', 'created_by')\\n#3 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/View.php(1244): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/View.php(1170): OC\\\\Files\\\\View->runHooks(Array, '\\\/hankila\\\/files', true)\\n#8 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/View.php(266): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/hankila\\\/files', Array)\\n#9 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(149): OC\\\\Files\\\\View->mkdir('\\\/hankila\\\/files')\\n#10 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(380): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/hankila\\\/files')\\n#11 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('hankila')\\n#12 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#13 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#14 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Server.php(950): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('hankila')\\n#15 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/User\\\/Session.php(419): OC\\\\Server->getUserFolder('hankila')\\n#16 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/User\\\/Session.php(487): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#17 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/User\\\/Session.php(307): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#18 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Setup.php(394): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#19 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/core\\\/Controller\\\/SetupController.php(65): OC\\\\Setup->install(Array)\\n#20 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/base.php(959): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#21 \\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/index.php(48): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/home\\\/cloudbru\\\/domains\\\/cloud.brusystems.be\\\/public_html\\\/lib\\\/private\\\/Activity\\\/Event.php\",\"Line\":401}","level":3,"time":"2017-12-06T17:44:44+00:00","method":"POST","url":"\/index.php","user":"hankila","version":"11.0.6.1"}
```
</details>

**Comment by MorrisJobke** [comment]
after changing the email is there anything shown in the web developer tools in your browser? What is the result of the request that is send right after changing the email address (you can view them in the browsers web developer tools in the network tab).

**Comment by hantk8** [comment]
Hi we found a solution
apparently this was the reason https://raymii.org/s/blog/Owncloud_DirectAdmin,_Apache_2.4_and_Error_AH01797_client_denied_by_server_configuration.html
