### ISSUE TITLE
ContactsMenu triggers 500 when search is limited to groups

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#7537]
Just dumping this while I am investigating something else

0. On git master
1. Have to many users (i mostly from LDAP)
2. Have two users in a single local group
3. Limit search to within groups only
4. Open contactsmenu

Expected:

The other user shows up

Actual:

```
Argument 1 passed to OC\Group\Manager::getUserGroupIds() must implement interface OCP\IUser, null given, called in /srv/http/nextcloud/master/lib/private/Contacts/ContactsMenu/ContactsStore.php on line 160

#0 /srv/http/nextcloud/master/lib/private/Contacts/ContactsMenu/ContactsStore.php(160): OC\Group\Manager->getUserGroupIds(NULL)\
#1 [internal function]: OC\Contacts\ContactsMenu\ContactsStore->OC\Contacts\ContactsMenu\{closure}(*** sensitive parameters replaced ***)\
#2 /srv/http/nextcloud/master/lib/private/Contacts/ContactsMenu/ContactsStore.php(168): array_filter(Array, Object(Closure))\
#3 /srv/http/nextcloud/master/lib/private/Contacts/ContactsMenu/ContactsStore.php(87): OC\Contacts\ContactsMenu\ContactsStore->filterContacts(Object(OC\User\User), Array, 'person_13')\
#4 /srv/http/nextcloud/master/lib/private/Contacts/ContactsMenu/Manager.php(59): OC\Contacts\ContactsMenu\ContactsStore->getContacts(Object(OC\User\User), 'person_13')\
#5 /srv/http/nextcloud/master/core/Controller/ContactsMenuController.php(61): OC\Contacts\ContactsMenu\Manager->getEntries(Object(OC\User\User), 'person_13')\
#6 [internal function]: OC\Core\Controller\ContactsMenuController->index('person_13')\
#7 /srv/http/nextcloud/master/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)\
#8 /srv/http/nextcloud/master/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\ContactsMenuController), 'index')\
#9 /srv/http/nextcloud/master/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\ContactsMenuController), 'index')\
#10 /srv/http/nextcloud/master/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OC\Core\Control...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\
#11 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\
#12 /srv/http/nextcloud/master/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\
#13 /srv/http/nextcloud/master/lib/base.php(990): OC\Route\Router->match('/contactsmenu/c...')\
#14 /srv/http/nextcloud/master/index.php(37): OC::handleRequest()\
#15 {main}
"File":"/srv/http/nextcloud/master/lib/private/Group/Manager.php","Line":326
```

**Comment by blizzz** [comment]
might be due to an unclean, savaged install, doesn't happen on a fresh one… closing for now
