### ISSUE TITLE
Files not shown, error with IPWhitelist

### ISSUE THREAD

**Issue by edvanleeuwen** [nextcloud/server#7543]
### Steps to reproduce
1. Login to NC
2.
3.

### Expected behaviour
Files should be displayed and accessible.

### Actual behaviour
The web interface works. Files are not shown. The admin screen displays an error indicating WebDAV is not properly set up.

Error:
OCP\AppFramework\QueryException: Could not resolve OCA\BruteForceSettings\Settings\IPWhitelist! Class OCA\BruteForceSettings\Settings\IPWhitelist does not exist

### Server configuration

**Operating system**: Centos 7.3

**Web server:** Apache 2.4

**Database:** MariaDB 10.0.33

**PHP version:** 7.1.12

**Nextcloud version:** (see Nextcloud admin page) 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** No.

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - gallery
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc68a4m1vymi",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "www.covs-de-scheidsrechter.nl",
            "covs-de-scheidsrechter.nl"
        ],
        "datadirectory": "\/home\/covst\/domains\/covs-de-scheidsrechter.nl\/public_html\/bestanden\/data",
        "overwrite.cli.url": "https:\/\/www.covs-de-scheidsrechter.nl\/bestanden",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "covst_ownc1",
        "dbhost": "localhost",
        "dbtableprefix": "ownc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Amsterdam",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "htaccess.RewriteBase": "\/bestanden",
        "tempdirectory": "\/home\/covst\/domains\/covs-de-scheidsrechter.nl\/public_html\/sites\/default\/files\/tmp\/nextcloud",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "covs-de-scheidsrechter.nl",
        "updater.release.channel": "stable",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Markdown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
{"reqId":"WjQ1624OGzXj4gis4H-ybQAAAAE","level":3,"time":"2017-12-15T21:51:56+01:00","remoteAddr":"217.105.191.61","user":"admin","app":"no app in context","method":"GET","url":"\/bestanden\/settings\/admin\/additional","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\BruteForceSettings\\\\Settings\\\\IPWhitelist! Class OCA\\\\BruteForceSettings\\\\Settings\\\\IPWhitelist does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\BruteForceS...')\\n#1 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\BruteForceS...')\\n#2 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\BruteForceS...')\\n#3 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/Settings\\\/Manager.php(352): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\BruteForceS...')\\n#4 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/settings\\\/Controller\\\/AdminSettingsController.php(138): OC\\\\Settings\\\\Manager->getAdminSettings('security')\\n#5 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/settings\\\/Controller\\\/AdminSettingsController.php(72): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('additional')\\n#6 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('additional')\\n#7 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#8 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#9 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#10 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin...')\\n#14 \\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/index.php(48): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/home\\\/covst\\\/domains\\\/covs-de-scheidsrechter.nl\\\/public_html\\\/bestanden\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36 Edge\/16.16299","version":"12.0.4.3"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by edvanleeuwen** [comment]
Solved. The solution was to expand the http methods allowed. In my case, this is done via DirectAdmin/CustomBuild.

See this for a elaborate explanation: https://help.poralix.com/articles/webdav-support-with-nginxapache-on-directadmin-server
