### ISSUE TITLE
LDAP Users not mapped and authentication fails

### ISSUE THREAD

**Issue by Scott-St** [nextcloud/server#772]
This is a copy of the OwnCloud bug report.  I am having the exact same issue on NextCloud

I'm setting up a new Nextcloud 9.0.53 (stable) server connected to LDAP. I was able to get LDAP to work and it sees two users in my Active Directory when pressing on the "test" buttons, as expected. There is nothing "fancy" about my LDAP setup: just adding basic settings.

All tests run fine:
1. "Verify settings and count users" show me 2 users found in the only group that is allowed (Ok)
2. Login is only with "LDAP / AD Username:". I tested with the usernames of both users (john and jane) and in both cases pressing on "Verify settings" reports "User found and settings verified." (Ok)

However, in the "Users" admin section I can only see 1 user imported from AD (the jane user). john was not imported, not even after pressing on "Clear Username-LDAP User Mapping".

When trying to log in as john (the user not imported), the UI reports: "An internal error occurred. Please try again or contact your administrator"). I then see the following 3 error messages in the log:

`{"reqId":"RzgrPrCi8\/6CEsbHE7DI","remoteAddr":"4.53.90.68","app":"core","message":"Exception when running cache gc: Attempted to initialize mount points for null user and no user in session","level":2,"time":"2016-08-08T14:49:33+00:00","method":"POST","url":"\/index.php?redirect_url=%2Findex.php%2Fapps%2Ffiles%2F","user":"--"}`

`{"reqId":"RzgrPrCi8\/6CEsbHE7DI","remoteAddr":"4.53.90.68","app":"handleLogin","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Code\":0,\"Trace\":\"#0 \\\/config\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(336): OC\\\\Files\\\\Filesystem::initMountPoints('')\\n#1 \\\/config\\\/www\\\/nextcloud\\\/lib\\\/private\\\/server.php(756): OC\\\\Files\\\\Node\\\\Root->getUserFolder('')\\n#2 \\\/config\\\/www\\\/nextcloud\\\/lib\\\/private\\\/user.php(170): OC\\\\Server->getUserFolder('')\\n#3 \\\/config\\\/www\\\/nextcloud\\\/lib\\\/base.php(1167): OC_User::login(*** username and password replaced ***)\\n#4 \\\/config\\\/www\\\/nextcloud\\\/lib\\\/base.php(1063): OC::tryFormLogin()\\n#5 \\\/config\\\/www\\\/nextcloud\\\/lib\\\/base.php(1025): OC::handleLogin()\\n#6 \\\/config\\\/www\\\/nextcloud\\\/index.php(39): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/config\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":377}","level":3,"time":"2016-08-08T14:49:33+00:00","method":"POST","url":"\/index.php?redirect_url=%2Findex.php%2Fapps%2Ffiles%2F","user":"--"}`

`{"reqId":"RzgrPrCi8\/6CEsbHE7DI","remoteAddr":"4.53.90.68","app":"user_ldap","message":"No DN found for Sc****@st******e.net on AD.S********.NET","level":0,"time":"2016-08-08T14:49:33+00:00","method":"POST","url":"\/index.php?redirect_url=%2Findex.php%2Fapps%2Ffiles%2F","user":"--"}`

Using the Docker image for unraid by linuxserver.io : https://lime-technology.com/forum/index.php?topic=50090.0

### Expected behaviour
All users in AD group should show up in the users list and be able to login.

### Actual behaviour
Webpage crashes and after I get a 500 error.  I need to clear the cookies in order to see the webpage again. 

### Server configuration

**Operating system:**
Unraid

**Web server:**
nginx

**Database:**
MariaDB 10.1

**PHP version:**
7.0.4

**Nextcloud version:** 
9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Docker: https://lime-technology.com/forum/index.php?topic=50090.0

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - federation
  - files_external
  - user_external
</summary>
</details>

<details>
<summary>The content of config/config.php:
```
{
    "system": {
        "instanceid": "ocqua46unikg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.1.2.2",
            "some.domain"
        ],
        "datadirectory": "\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/10.1.2.2",
        "dbtype": "mysql",
        "version": "9.0.53.0",
        "dbname": "owncloud",
        "dbhost": "mariadb",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "sendgrid.net",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "smtp.sendgrid.net",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false
    }
}
```
</summary>
</details>

**Are you using external storage, if yes which one:** local...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Active Directory (LDAP)...

#### LDAP configuration (delete this part if not used)
<details>
<summary>+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                    |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                    |
| homeFolderNamingRule          |                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                  |
| ldapAgentName                 | CN=LDAP User,CN=Users,DC=domain,DC=com                                                                                          |
| ldapAgentPassword             | ***                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                    |
| ldapBackupHost                |                                                                                                                                    |
| ldapBackupPort                |                                                                                                                                    |
| ldapBase                      | CN=Users,DC=domain,DC=com                                                                                                       |
| ldapBaseGroups                | CN=Users,DC=domain,DC=com                                                                                                       |
| ldapBaseUsers                 | CN=Users,DC=domain,DC=com                                                                                                       |
| ldapCacheTTL                  | 600                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                    |
| ldapEmailAttribute            |                                                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                    |
| ldapExpertUsernameAttr        |                                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                 |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=Home Users)))                                                                                        |
| ldapGroupFilterGroups         | Home Users                                                                                                                         |
| ldapGroupFilterMode           | 0                                                                                                                                  |
| ldapGroupFilterObjectclass    | group                                                                                                                              |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                       |
| ldapHost                      | dc01.domain.com                                                                                                               |
| ldapIgnoreNamingRules         |                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=Home Users,CN=Users,DC=domain,DC=com)(primaryGroupID=1106))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                    |
| ldapLoginFilterEmail          | 0                                                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                |
| ldapPort                      | 389                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                  |
| ldapUserDisplayName           | displayName                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=Home Users,CN=Users,DC=domain,DC=com)(primaryGroupID=1106))))                         |
| ldapUserFilterGroups          | Home Users                                                                                                                         |
| ldapUserFilterMode            | 0                                                                                                                                  |
| ldapUserFilterObjectclass     | person                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                  |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------+</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10/Server 2012

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Scott-St** [comment]
Duplicate.
