### ISSUE TITLE
Files synced differently on 2 clients with the same account have been deleted on the server

### ISSUE THREAD

**Issue by Ouack23** [nextcloud/server#7730]
### Steps to reproduce
1. Instantiate Server + Client A which sync all folders
2. Client B which doesn't sync all folders, same account as client A but on an another computer

### Expected behaviour
All files are kept server side, and are available on the server web page.
Client side : A does have all files locally, and B only have files that he selected

### Actual behaviour
I don't know how I did this, but:
* As expected, I didn't have access to unselected folders on B computer.
* It deleted those files on my server too. I'm screwed here.
* I still had my files locally on computer A. So I said to myself : "let's boot computer A and re-upload files". But I think this deletion of files is considered to be more recent than the A-side version : it deleted all the folders that B didn't sync on A. I'm soo screwed here...

Actual situation: 
* I lost my files.
* I managed to still have 2 files from the lost folder, but I cannot re-upload them : I've got the following error on the client : 

File 1:
> Error transfering *** - server replied: Locked ("***" is locked)

File 2:
> Keep on blacklist : Error transfering "***" - Server replied: Forbidden (Sabre\DAV\Exception\Forbidden)

On the server:
File 2:
> janv. 08 10:28:18 *** ownCloud[2110]: {webdav} Exception: {"Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Message":"The resource you tried to create already exists","Code":0,"Trace":"#0 \/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Core
Plugin.php(590): Sabre\\DAV\\Server->createCollection('***', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/usr\/share\/webapps\/nextcloud\/3rdparty
\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/usr\/share\/webapps\/nextcloud\/3rdpar
ty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Server.php(258): Sabre\\DAV\\Server->exec()\n#6 \/usr\/share\/webapps\/nextcloud
\/apps\/dav\/appinfo\/v2\/remote.php(33): OCA\\DAV\\Server->exec()\n#7 \/usr\/share\/webapps\/nextcloud\/remote.php(162): require_once('\/usr\/share\/weba...')\n#8 {main}","File":"\/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1181}

File 1:
> janv. 08 10:28:19 *** ownCloud[2090]: {webdav} Exception: {"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Message":"\"***\" is locked","Code":0,"Trace":"#0 \/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Connector\/Sab
re\/Directory.php(151): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id # 19)\n#1 \/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1096): OCA\\DAV\\Connector\\Sabre\\Directory->createFile(***', Resource id # 19)\n#2 \/usr\/shar
e\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(525): Sabre\\DAV\\Server->createFile('***', Resource id # 19, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
\n#4 \/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)
\n#6 \/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Server.php(258): Sabre\\DAV\\Server
->exec()\n#8 \/usr\/share\/webapps\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php(33): OCA\\DAV\\Server->exec()\n#9 \/usr\/share\/webapps\/nextcloud\/remote.php(162): require_once('\/usr\/share\/weba...')\n#10 {main}","File":"\/usr\/share\/webapps\/nextcloud\/apps\/dav\/
lib\/Connector\/Sabre\/File.php","Line":176}

So I made some research, and did the following:
* I cleared manually the oc_file_locks table from my bdd. Not working, same errors. The table re lock the same files over and over.
* Checked my trashbin : my files aren't in there.
* I then discovered my deleted files are still listed in my oc_filecache table, potentially causing the issue ? So I attempted to clear my cache with `sudo -u http php occ files:cleanup -vvv` which gave me `0 orphaned file cache entries deleted`.

### Server configuration

**Operating system**: Archlinux ARM 4.9.70-1-ARCH

**Web server:**
> sudo pacman -Qs apache
local/apache 2.4.29-1
     A high performance Unix-based HTTP server
local/apr 1.6.3-1
     The Apache Portable Runtime
local/apr-util 1.6.1-1
     The Apache Portable Runtime
local/php-apache 7.1.12-1
     Apache SAPI for PHP

**Database:**
> sudo pacman -Qs mariadb
local/libmariadbclient 10.1.29-1
    MariaDB client libraries
local/mariadb 10.1.29-1
    Fast SQL database server, drop-in replacement for MySQL
local/mariadb-clients 10.1.29-1
    MariaDB client tools

**PHP version:**
> sudo pacman -Qs php
local/php 7.1.12-1
    A general-purpose scripting language that is especially suited to web development
local/php-apache 7.1.12-1
    Apache SAPI for PHP
local/php-apcu 5.1.8-1
    A userland caching module for PHP
local/php-fpm 7.1.12-1
    FastCGI Process Manager for PHP
local/php-gd 7.1.12-1
    gd module for PHP
local/php-imap 7.1.12-1
    imap module for PHP
local/php-intl 7.1.12-1
    intl module for PHP
local/php-mcrypt 7.1.12-1
    mcrypt module for PHP
local/php-memcached 3.0.4-1
    PHP extension for interfacing with memcached via libmemcached library
local/phpmyadmin 4.7.6-1
    PHP and hence web-based tool to administrate MySQL over the WWW

**Nextcloud version:**
> sudo pacman -Qs nextcloud
local/nextcloud 12.0.4-1
    A cloud server to store your files centrally on a hardware controlled by you

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Archlinux community package repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
> No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

> sudo -u http php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - audioplayer: 2.2.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - githubmergetracker: 0.0.18
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - music: 0.5.5
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.3
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - direct_menu
  - encryption
  - files_external
  - files_versions
  - firstrunwizard
  - lsd
  - password_policy
  - systemtags
  - user_external
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

> sudo -u http php occ config:list system
{
    "system": {
        "instanceid": "ocbi8oebd7yo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***"
        ],
        "datadirectory": "\/mnt\/dd1\/data",
        "overwrite.cli.url": "https:\/\/***\/",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***",
        "mail_domain": "***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "localhost",
        "mail_smtpport": "587",
        "openssl": {
            "config": "\/root\/ca\/intermediate\/openssl.cnf"
        },
        "enable_certificate_management": true,
        "theme": "",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Storage on external hdd mounted in /mnt/dd1/

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Firefox 57.0.4

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by icewind1991** [comment]
This sounds like a client issue mainly

**Comment by Ouack23** [comment]
The fact is, I never deleted files. I chose not to sync them. But the result is the same. I lost around 40GO of data in this operation !

**Comment by szaimen** [comment]
I'm closing this issue due to inactivity. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
