### ISSUE TITLE
Android client unable to login via default login method (class appName does not exist)

### ISSUE THREAD

**Issue by jose1711** [nextcloud/server#7788]
### Actual behaviour
Android client reports an error while attempting to connect to my nextcloud server instance. Old login method works. Desktop client works fine.

### Expected behaviour
Both methods (new and old) should be working.
 
### Steps to reproduce
Start Nextcloud Android client, enter server hostname

### Environment data
Android version: 6.0.1

Device model: Samsung S5

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.4-r1, Alpine Linux

#### Web server error log
```
192.168.0.119 - - [10/Jan/2018:21:16:54 +0000] "GET /status.php HTTP/1.0" 200 146 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.0" "192.168.0.1"                     
192.168.0.119 - - [10/Jan/2018:21:16:54 +0000] "HEAD /remote.php/webdav/ HTTP/1.0" 401 0 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.0" "192.168.0.1"              
192.168.0.119 - - [10/Jan/2018:21:16:55 +0000] "GET /index.php/login/flow HTTP/1.0" 500 4970 "-" "Samsung SM-G900F" "192.168.0.1"  
```
#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"U92ZrffjR2SEVEHQn7L5","level":3,"time":"2018-01-10T21:16:55+00:00","remoteAddr":"192.168.0.119","user":"--","app":"index","method":"GET","url":"\/index.php\/login\/flow","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve appName! Class appName does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('appName')\\n#1 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('appName')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(66): OC\\\\ServerContainer->query('appName')\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OC\\\\\\\\Core\\\\\\\\Control...')\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OC\\\\\\\\Core\\\\\\\\Control...')\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(416): OC\\\\ServerContainer->query('OC\\\\\\\\Core\\\\\\\\Control...')\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(101): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('OC\\\\\\\\Core\\\\\\\\Control...')\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ClientFlowLogin...', 'showAuthPickerP...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/login\\\/flow')\\n#12 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Samsung SM-G900F","version":"12.0.4.3"}```

**Comment by MorrisJobke** [comment]
@jose1711 What apps do you have enabled?

cc @tobiasKaminsky and @rullzer for the new login flow.

**Comment by jose1711** [comment]
Apps Enabled:
* Collaborative tags 1.2.0
* Deleted files 1.2.0
* File sharing 1.4.0
* Gallery 17.0.0
* Log Reader 2.0.0
* Versions 1.5.0
* Preview Generator 1.0.9
* Ransomware protection 1.0.5

**Comment by jose1711** [comment]
FYI: I have disabled unofficial apps (Preview Generator and Ransomware protection) to see if something improves but to no avail.

**Comment by rullzer** [comment]
It seems DI is doing something fishy... but debugging this won't be so easy... let me think if I can come up with something...

**Comment by rullzer** [comment]
@jose1711 we fixed some DI stuff and improved the error logging in Nextcloud 13. We just release the RC1 of Nextcloud13. Could you test that?

**Comment by jose1711** [comment]
made a full backup and deployed 13r1. now modern login method works fine from my cellphone. is there a plan to backport those fixes to 12-branch? otherwise i guess i'd need to wait for the next stable release.

**Comment by MorrisJobke** [comment]
> made a full backup and deployed 13r1. now modern login method works fine from my cellphone. is there a plan to backport those fixes to 12-branch? otherwise i guess i'd need to wait for the next stable release.

Sadly is was a major rework and we didn't back ported it. Nextcloud 13 is stable enough to run it now :)
