### ISSUE TITLE
cardDav read-only share has write access when original url is known

### ISSUE THREAD

**Issue by AlexanderLangguth** [nextcloud/server#7957]
### Steps to reproduce
1. Create user1 and user2
2. Create a contact-book with user1
3. Share the contact-book with user2 and do not set `can edit`
4. Switch to user2
5. Get the URI of the shared contact-book via the "Copy Link" Button
6. Change the URI from (5) back to the original URI that user1 would see based on the information you get from the URI. (change the user part of the URL and remove the shared_* stuff)
7. Import the changed URI into any external cardDav client (e.g. cardBook extension of Thunderbird) with the credentials of user2
8. Change some contacts in the external client and upload back to the server

### Expected behaviour
The data on the server should not changed.
Maybe either the import using the URI of user1 with credentials of user2 should fail or the upload should fail.

### Actual behaviour
By using the URI of the owner you can freely edit the contacts without having write- (maybe even read-) access to them.

### Server configuration

**Operating system**:
Docker-image: `nextcloud:apache`
exact image-id: `sha256:bccb23d8d81d17e50b0a36f87629192a8e0e12ef7439332f573ef37aeb56cb63`
That should be Debian 8

**Web server:**
Apache running in the docker container with nginx running on the host machine with proxy enabled.
Output of `apache2 -v` inside of the container:
```
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 20 2017 04:37:43
```

**Database:**
MariaDB 10.3.2 running in Docker.
Docker-image: `mariadb:10.3.2`

**PHP version:** 
Output of `php -v` inside of the container:
```
PHP 7.1.13 (cli) (built: Jan  9 2018 00:41:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13, Copyright (c) 1999-2017, by Zend Technologies
```

**Nextcloud version:** `12.0.4`

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

`No errors have been found.`

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "ocqfg8dq1c9r",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "https:\/\/cloud.patronus.io",
        "overwritehost": "cloud.patronus.io",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "nextcloud_db:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "cloud",
        "mail_domain": "patronus.io",
        "mail_smtphost": "smtp1.5hosting.com",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** mounted docker volume

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** -

### Client configuration
**Browser:** Chrome 62.0.3202.89

**Operating system:** Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
--- error log is empty ---
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"945nbAjUuwQpwl5Zwja5","level":4,"time":"2018-01-19T10:14:56+00:00","remoteAddr":"172.19.0.1","user":"alangguth","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/alangguth\/Contacts\/9a59931a-b6d9-43f1-8fe9-8ec782ffea31.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Message\":\"Validation error in vCard: The FN property must appear in the VCARD component exactly 1 time\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(294): Sabre\\\\CardDAV\\\\Plugin->validateVCard('BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#1 [internal function]: Sabre\\\\CardDAV\\\\Plugin->beforeWriteContent('addressbooks\\\/us...', Object(Sabre\\\\CardDAV\\\\Card), 'BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1128): Sabre\\\\Event\\\\EventEmitter->emit('beforeWriteCont...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('addressbooks\\\/us...', 'BEGIN:VCARD\\\\r\\\\nVE...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":397}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.89 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"Ro4OL3DlEHAaCLgEzRHz","level":2,"time":"2018-01-19T10:22:16+00:00","remoteAddr":"172.19.0.1","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/","message":"Login failed: 'alangguth' (Remote IP: '172.19.0.1')","userAgent":"CardDAV-Sync free\/0.4.21 (samsung; dream2ltexx; Android 7.0; de_DE; org.dmfs.carddav.sync\/143)","version":"12.0.4.3"}
{"reqId":"zoIO4OnLmCDm1Q3evkc8","level":2,"time":"2018-01-19T10:22:36+00:00","remoteAddr":"172.19.0.1","user":"--","app":"core","method":"POST","url":"\/login","message":"Login failed: 'alangguth' (Remote IP: '172.19.0.1')","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.89 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"AZfItutsqQMvavD6sDRa","level":4,"time":"2018-01-19T10:42:37+00:00","remoteAddr":"172.19.0.1","user":"alangguth","app":"webdav","method":"MKCOL","url":"\/remote.php\/dav\/addressbooks\/users\/alangguth\/Patronus.io","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Message\":\"The resource you tried to create already exists\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('addressbooks\\\/us...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1181}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.89 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"jGSmaUBNFNX8JZ0DQhhS","level":4,"time":"2018-01-19T10:43:06+00:00","remoteAddr":"172.19.0.1","user":"alangguth","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/alangguth\/Patronus.io%20Contacts\/9d56c4c4-b95e-4d36-ad86-8ad47f13ebd8.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Message\":\"Validation error in vCard: The FN property must appear in the VCARD component exactly 1 time\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(294): Sabre\\\\CardDAV\\\\Plugin->validateVCard('BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#1 [internal function]: Sabre\\\\CardDAV\\\\Plugin->beforeWriteContent('addressbooks\\\/us...', Object(Sabre\\\\CardDAV\\\\Card), 'BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1128): Sabre\\\\Event\\\\EventEmitter->emit('beforeWriteCont...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('addressbooks\\\/us...', 'BEGIN:VCARD\\\\r\\\\nVE...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":397}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.89 Safari\/537.36","version":"12.0.4.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
--- not applicable ---
```
</details>

**Comment by MorrisJobke** [comment]
cc @georgehrke @nickvergessen

**Comment by georgehrke** [comment]
@AlexanderLangguth Can you confirm that you never setup that account for user1 in cardBook (Thunderbird)? (Even if you deleted it again)

**Comment by AlexanderLangguth** [comment]
@georgehrke Looks like this really was the issue.

The plugin seems to just try all credentials until it works.
Once the plugin only had the valid credentials of user2 the changes could not be uploaded to the server.

user2 can still use the uri of user1, but that is not really an security issue.

I guess we can close this issue as "The client is the bug". Sorry :-|
