### ISSUE TITLE
Updating Nextcloud 12.0.5 to 13.0.0.rc2 fails on Postgres 

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#7960]
Upgraded to the latest git commit today from 12.0.4 to 12.0.5, then went for stable13. The update fails with 

    Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_jobs ALTER id TYPE BIGSERIAL':  SQLSTATE[42704]: Undefined object: 7 ERROR:  type "bigserial" does not exist

@MorrisJobke asked me to post these links:

* https://github.com/nextcloud/server/pull/6563/commits/a3bdb318e9f552f342de401d0aff24384a80fcd8
* https://github.com/nextcloud/server/issues/4504#issuecomment-354416206
* https://github.com/nextcloud/server/pull/6563#issuecomment-333070998

I suppose the migration steps do not work properly for postgres and you didnt run into these issues because you started with a fresh 12.x.x installation

### Server configuration

**Operating system**: Debian stable

**Web server:** Apache

**Database:** Postgres 9.6

**PHP version:** 5.6

**Where did you install Nextcloud from:** git

Enabled:
  - bookmarks: 0.10.1
  - calendar: 1.5.7
  - caniupdate: 0.1.1
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_sharing: 1.4.0
  - lookup_server_connector: 1.0.0
  - news: 12.0.0
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - workflowengine: 1.2.0

Disabled:
  - admin_audit
  - encryption
  - federation
  - files_encryption
  - files_external
  - files_trashbin
  - files_versions
  - testing
  - updatenotification
  - user_ldap

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "",
        "dbtype": "pgsql",
        "version": "12.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "overwrite.cli.url": "\/owncloud",
        "loglevel": 0,
        "debug": false,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "htaccess.RewriteBase": "\/owncloud"
    }
}

```
**Are you using encryption:** no

### Client configuration
**Browser:** Firefox stable

**Operating system:** Arch Linux

**Comment by BernhardPosselt** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Stacktrace?

**Comment by BernhardPosselt** [comment]
Don't think a stack trace will really help here. It happens in the migration code. If you want one I'll post one tomorrow

**Comment by BernhardPosselt** [comment]
```json
{
   "reqId":"2fUQbJUYga0eD3eYrAB8",
   "level":3,
   "time":"2018-01-20T11:25:52+00:00",
   "remoteAddr":"2a02:8388:6a82:3580:8ad7:f6ff:fec7:3749",
   "user":"--",
   "app":"core",
   "method":"GET",
   "url":"\/owncloud\/core\/ajax\/update.php?requesttoken=s1trTBIQ71iyFHJsyymhu8pM9hidShMXLF7nhWXpi4o%3D%3A5z1dGntUqG%2F3WDg1%2FmGZ6qU7kVL6YV9Nbh%2Bd1g7C5ec%3D",
   "message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE oc_jobs ALTER id TYPE BIGSERIAL':\\n\\nSQLSTATE[42704]: Undefined object: 7 ERROR:  type \\\"bigserial\\\" does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(964): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'ALTER TABLE oc_...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(260): Doctrine\\\\DBAL\\\\Connection->query('ALTER TABLE oc_...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(83): OC\\\\DB\\\\Migrator->applySchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(446): OC\\\\DB\\\\Migrator->migrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(434): OC\\\\DB\\\\Connection->migrateToSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(389): OC\\\\DB\\\\MigrationService->executeStep('13000Date201709...')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(312): OC\\\\DB\\\\MigrationService->migrate()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(260): OC\\\\Updater->doCoreUpgrade()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(139): OC\\\\Updater->doUpgrade('13.0.0.11', '12.0.5.1')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/ajax\\\/update.php(212): OC\\\\Updater->upgrade()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91}",
   "userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0",
   "version":"12.0.5.1"
}
```

**Comment by BernhardPosselt** [comment]
Solved by running git submodule update

**Comment by nickvergessen** [comment]
Fixed by `git submodule update`
