### ISSUE TITLE
Upgrade from stable9 to stable10 fails due to workflowengine

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#800]
### Steps to reproduce
1. Install from git with branch stable9
2. Switch to stable10
3. run ./occ upgrade

### Expected behaviour

Nextcloud should update without an error.

### Actual behaviour

```
$ ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
 Done                                                        
 14/14 [============================] 100%                   
Checking whether the database schema for <federatedfilesharing> can be updated (this can take a long time depending on the database size)
 Done                                                        
 2/2 [============================] 100%                     
Checking whether the database schema for <federation> can be updated (this can take a long time depending on the database size)
 Done                                                        
 7/7 [============================] 100%                     
Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
 Done                                                        
 9/9 [============================] 100%                     
Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Exception: workflowengine can't be disabled.
Update failed
Maintenance mode is kept active
Reset log level
```

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** stable9 / stable10

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** git

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - provisioning_api: 0.4.1
  - survey_client: 0.1.5
  - systemtags: 0.2
  - theming: 0.2.0
  - updatenotification: 0.1.0
  - workflowengine: true
Disabled:
  - direct_menu
  - encryption
  - files_external
  - news
  - ownnotes
  - serverinfo
  - survey_server
  - tasks
  - templateeditor
  - testing
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "bender.lan",
            "192.168.1.180"
        ],
        "datadirectory": "\/home\/jus\/repos\/nextcloud\/server\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "sqlite3",
        "version": "9.0.52.0",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocsis19bdvr2",
        "debug": "true",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"+uDwqRl4sWSZdmnmzKkc","remoteAddr":"127.0.0.1","app":"core","message":"starting upgrade from 9.0.52.0 to 9.1.0.14","level":0,"time":"2016-08-09T19:48:58+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=cWQkMiA0RAodET1YUB1iZCs%2BWBY3MRpCVlFBLiV%2BUHs%3D%3AH4abGFrxIaNnaWTTGTsyezWzabqyT710%2FbKTgeGmCSw%3D","user":"--"}
{"reqId":"+uDwqRl4sWSZdmnmzKkc","remoteAddr":"127.0.0.1","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"workflowengine can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jus\\\/repos\\\/nextcloud\\\/server\\\/lib\\\/private\\\/legacy\\\/app.php(409): OC\\\\App\\\\AppManager->disableApp('workflowengine')\\n#1 \\\/home\\\/jus\\\/repos\\\/nextcloud\\\/server\\\/lib\\\/private\\\/Updater.php(406): OC_App::disable('workflowengine')\\n#2 \\\/home\\\/jus\\\/repos\\\/nextcloud\\\/server\\\/lib\\\/private\\\/Updater.php(251): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/home\\\/jus\\\/repos\\\/nextcloud\\\/server\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.0.14', '9.0.52.0')\\n#4 \\\/home\\\/jus\\\/repos\\\/nextcloud\\\/server\\\/core\\\/ajax\\\/update.php(194): OC\\\\Updater->upgrade()\\n#5 {main}\",\"File\":\"\\\/home\\\/jus\\\/repos\\\/nextcloud\\\/server\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":258}","level":3,"time":"2016-08-09T19:49:00+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=cWQkMiA0RAodET1YUB1iZCs%2BWBY3MRpCVlFBLiV%2BUHs%3D%3AH4abGFrxIaNnaWTTGTsyezWzabqyT710%2FbKTgeGmCSw%3D","user":"--"}
```
</details>

**Comment by juliushaertl** [comment]
cc @MorrisJobke @nickvergessen

**Comment by MorrisJobke** [comment]
@LukasReschke this is most likely due to the fact that it is force enabled. Any idea why the updater wants to disable it? Isn't it a shipped app and then should not be disabled?

**Comment by MorrisJobke** [comment]
@karlitschek I would rate this a show blocker.

**Comment by MorrisJobke** [comment]
> @karlitschek I would rate this a show blocker.

Already for the RC tomorrow.

**Comment by karlitschek** [comment]
agreef

**Comment by LukasReschke** [comment]
I'll take a look.

**Comment by LukasReschke** [comment]
Can reproduce locally.

**Comment by LukasReschke** [comment]
Patch is at https://github.com/nextcloud/server/pull/803, @juliushaertl mind testing? Thanks a lot 🚀
