### ISSUE TITLE
Bruteforce: unrecognized address ::1

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#8005]
I updated to latest master via git pull on my test instance and did an update and now I get:
```
{"reqId":"Wmco638AAAEAADiP0K4AAABS","level":3,"time":"2018-01-23T12:22:03+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"GET","url":"\/nc\/index.php\/login","message":"inet_pton(): Unrecognized address ::1 at \/var\/www\/localhost\/htdocs\/nextcloud\/lib\/private\/Security\/Bruteforce\/Throttler.php#158","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"14.0.0.0"}
{"reqId":"Wmco638AAAEAADiP0K4AAABS","level":3,"time":"2018-01-23T12:22:03+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"GET","url":"\/nc\/index.php\/login","message":"inet_pton(): Unrecognized address ::1 at \/var\/www\/localhost\/htdocs\/nextcloud\/lib\/private\/Security\/Normalizer\/IpAddress.php#71","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"14.0.0.0"}
{"reqId":"Wmco638AAAEAADiP0K4AAABS","level":3,"time":"2018-01-23T12:22:03+00:00","remoteAddr":"::1","user":"--","app":"index","method":"GET","url":"\/nc\/index.php\/login","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"inet_ntop() expects parameter 1 to be string, boolean given\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Security\\\/Normalizer\\\/IpAddress.php(79): inet_ntop(false)\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Security\\\/Normalizer\\\/IpAddress.php(96): OC\\\\Security\\\\Normalizer\\\\IpAddress->getIPv6Subnet('::1', 128)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Security\\\/Bruteforce\\\/Throttler.php(219): OC\\\\Security\\\\Normalizer\\\\IpAddress->getSubnet()\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/core\\\/Controller\\\/LoginController.php(198): OC\\\\Security\\\\Bruteforce\\\\Throttler->getDelay('::1')\\n#4 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->showLoginForm(NULL, NULL, NULL)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'showLoginForm', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/base.php(981): OC\\\\Route\\\\Router->match('\\\/login')\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Security\\\/Normalizer\\\/IpAddress.php\",\"Line\":79}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"14.0.0.0"}
```

My computer has ipv4/v6 enabled and both valid ips.
/etc/hosts:
```
127.0.0.1       tobi-laptop     localhost.localdomain   localhost
::1     tobi-laptop     localhost6.localdomain6 localhost6

```

**Comment by rullzer** [comment]
It sounds like your php is not compiled with ipv6. but that would be weird...

**Comment by tobiasKaminsky** [comment]
```
PHP 7.1.13 (cli) (built: Jan 15 2018 11:50:50) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13, Copyright (c) 1999-2017, by Zend Technologies


php -i | grep -i v6

IPv6 Support => enabled
IPv6 => Yes
```

**Comment by tobiasKaminsky** [comment]
When accessing the same test server with my emulated android it is working...
Strange

**Comment by tobiasKaminsky** [comment]
Strange, after restarting apache it is now working.
Sorry for the noise.
