### ISSUE TITLE
user_ldap automatically disabled; high swap and memory usage overall

### ISSUE THREAD

**Issue by Isotop7** [nextcloud/server#8129]
### Steps to reproduce
1. Migrate vom OC 9.1 to NC 10; Update to NC 11.0.6
2. Use ldap login and wait some time
3. Test login with ldap user

### Expected behaviour
User should login as normal

### Actual behaviour
Login fails, on db-level app user_ldap is disabled (in table oc_appconfig)

### Server configuration

**Operating system**:
Ubuntu 16.04.3
**Web server:**
2.4.18
**Database:**
MySQL  5.6.33
**PHP version:**
PHP 7.0.22
**Nextcloud version:** (see Nextcloud admin page)
11.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:**
From OC 9.1 to NC 10 to NC 11
**Where did you install Nextcloud from:**
Source package
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - announcementcenter: 3.0.0
  - comments: 1.1.0
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - firstrunwizard
  - user_external
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc3xzc0toftd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***server ip***",
            "infocloud.domain.de"
        ],
        "datadirectory": "\/mnt\/infocloud\/",
        "overwrite.cli.url": "https:\/\/***server ip***\/",
        "dbtype": "mysql",
        "version": "11.0.6.1",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "theme": "owncloud-theme-domain",
        "mail_from_address": "infocloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "domain.de",
        "dbname": "infocloud_new",
        "dbhost": "***database host ip***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "singleuser": false,
        "mail_smtphost": "***smtp host ip***",
        "mail_smtpport": "25",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "auth.bruteforce.protection.enabled": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                           |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                         |
| hasPagedResultSupport         |                                                                                                                                           |
| homeFolderNamingRule          | attr:sAMAccountName                                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                                                         |
| ldapAgentName                 | <ldap query user>                                                                                                                                |
| ldapAgentPassword             | ***                                                                                                                                       |
| ldapAttributesForGroupSearch  | cn                                                                                                                                        |
| ldapAttributesForUserSearch   |                                                                                                                                           |
| ldapBackupHost                |                                                                                                                                           |
| ldapBackupPort                |                                                                                                                                           |
| ldapBase                      | DC=intern,DC=domain,DC=de                                                                                                             |
| ldapBaseGroups                | DC=intern,DC=domain,DC=de                                                                                                             |
| ldapBaseUsers                 | DC=intern,DC=domain,DC=de                                                                                                             |
| ldapCacheTTL                  | 600                                                                                                                                       |
| ldapConfigurationActive       | 1                                                                                                                                         |
| ldapDynamicGroupMemberURL     |                                                                                                                                           |
| ldapEmailAttribute            | mail                                                                                                                                      |
| ldapExperiencedAdmin          | 0                                                                                                                                         |
| ldapExpertUUIDGroupAttr       |                                                                                                                                           |
| ldapExpertUUIDUserAttr        |                                                                                                                                           |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                            |
| ldapGroupDisplayName          | cn                                                                                                                                        |
| ldapGroupFilter               | <ldapgroupfilter>                        |
| ldapGroupFilterGroups         | <filteredgroups>                                                                          |
| ldapGroupFilterMode           | 0                                                                                                                                         |
| ldapGroupFilterObjectclass    | group                                                                                                                                     |
| ldapGroupMemberAssocAttr      | member                                                                                                                                    |
| ldapHost                      | <server ip>                                                                                                                             |
| ldapIgnoreNamingRules         |                                                                                                                                           |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))                                              |
| ldapLoginFilterAttributes     |                                                                                                                                           |
| ldapLoginFilterEmail          | 1                                                                                                                                         |
| ldapLoginFilterMode           | 0                                                                                                                                         |
| ldapLoginFilterUsername       | 1                                                                                                                                         |
| ldapNestedGroups              | 1                                                                                                                                         |
| ldapOverrideMainServer        |                                                                                                                                           |
| ldapPagingSize                | 500                                                                                                                                       |
| ldapPort                      | 389                                                                                                                                       |
| ldapQuotaAttribute            | extensionAttribute10                                                                                                                      |
| ldapQuotaDefault              | 5368709120                                                                                                                                |
| ldapTLS                       | 0                                                                                                                                         |
| ldapUserDisplayName           | displayname                                                                                                                               |
| ldapUserDisplayName2          |                                                                                                                                           |
| ldapUserFilter                | <userfilter> |
| ldapUserFilterGroups          | Owncloud                                                                                                                                  |
| ldapUserFilterMode            | 1                                                                                                                                         |
| ldapUserFilterObjectclass     | person                                                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                                                      |
| ldapUuidUserAttribute         | auto                                                                                                                                      |
| turnOffCertCheck              | 0                                                                                                                                         |
| turnOnPasswordChange          | 0                                                                                                                                         |
| useMemberOfToDetectMembership | 1                                                                                                                                         |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Firefox, Chrome, IE
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Wed Jan 31 06:25:04.307334 2018] [ssl:warn] [pid 30506] AH01909: 172.16.16.22:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 31 06:25:04.307499 2018] [mpm_prefork:notice] [pid 30506] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Wed Jan 31 06:25:04.307512 2018] [core:notice] [pid 30506] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 31 07:25:07.312186 2018] [authz_core:error] [pid 22829] [client 192.168.222.181:39446] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 07:25:32.096462 2018] [authz_core:error] [pid 22829] [client 192.168.222.181:39582] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 07:30:41.203000 2018] [authz_core:error] [pid 22656] [client 192.168.222.181:41794] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 07:56:16.005444 2018] [authz_core:error] [pid 22656] [client 192.168.222.181:51618] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 07:59:17.283222 2018] [:error] [pid 22656] [client 192.168.222.181:52600] PHP Fatal error:  Uncaught Exception: Session has been closed - no further changes to the session are allowed in /var/www/nextcloud/lib/private/Session/Internal.php:158\nStack trace:\n#0 /var/www/nextcloud/lib/private/Session/Internal.php(64): OC\\Session\\Internal->validateSession()\n#1 /var/www/nextcloud/lib/private/Session/CryptoSessionData.php(164): OC\\Session\\Internal->set('encrypted_sessi...', '8892125f788a65a...')\n#2 /var/www/nextcloud/lib/private/Session/CryptoSessionData.php(67): OC\\Session\\CryptoSessionData->close()\n#3
[internal function]: OC\\Session\\CryptoSessionData->__destruct()\n#4 {main}\n  thrown in /var/www/nextcloud/lib/private/Session/Internal.php on line 158
[Wed Jan 31 08:05:32.733169 2018] [authz_core:error] [pid 22829] [client 192.168.222.181:54898] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:10:26.032105 2018] [authz_core:error] [pid 22655] [client 192.168.222.181:56548] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:12:54.210901 2018] [authz_core:error] [pid 22657] [client 192.168.222.181:57764] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:32:01.975589 2018] [authz_core:error] [pid 22658] [client 192.168.222.181:38386] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:32:50.136071 2018] [authz_core:error] [pid 22655] [client 192.168.222.181:38746] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:33:20.187884 2018] [authz_core:error] [pid 13284] [client 192.168.222.181:39072] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:33:52.373948 2018] [authz_core:error] [pid 22829] [client 192.168.222.181:39350] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:33:54.655320 2018] [authz_core:error] [pid 22655] [client 192.168.222.181:39372] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:34:22.431121 2018] [authz_core:error] [pid 22657] [client 192.168.222.181:39584] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:45:48.642123 2018] [authz_core:error] [pid 13284] [client 192.168.222.181:47034] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:49:03.569883 2018] [authz_core:error] [pid 22657] [client 192.168.222.181:49032] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:55:11.119312 2018] [authz_core:error] [pid 11524] [client 192.168.222.181:53456] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 08:55:16.078374 2018] [authz_core:error] [pid 27713] [client 192.168.222.181:53554] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:02:11.869012 2018] [authz_core:error] [pid 12763] [client 192.168.222.181:58118] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:16:21.231283 2018] [authz_core:error] [pid 22829] [client 192.168.222.181:40098] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:20:16.390198 2018] [authz_core:error] [pid 19660] [client 192.168.222.181:43426] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:22:35.322551 2018] [authz_core:error] [pid 19659] [client 192.168.222.181:45676] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:28:28.497732 2018] [authz_core:error] [pid 22657] [client 192.168.222.181:51258] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:30:09.306203 2018] [authz_core:error] [pid 9948] [client 192.168.222.181:52532] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:41:10.957383 2018] [authz_core:error] [pid 19660] [client 192.168.222.181:33830] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:51:17.574378 2018] [authz_core:error] [pid 19660] [client 192.168.222.181:43716] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 09:54:54.532337 2018] [authz_core:error] [pid 22657] [client 192.168.222.181:47146] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 10:15:55.042853 2018] [authz_core:error] [pid 11524] [client 192.168.222.181:39546] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 10:33:07.994573 2018] [authz_core:error] [pid 27713] [client 192.168.222.181:54382] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 10:57:02.865242 2018] [authz_core:error] [pid 9948] [client 192.168.222.181:49020] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 11:04:01.933983 2018] [authz_core:error] [pid 11524] [client 192.168.222.181:56606] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 11:18:51.350028 2018] [authz_core:error] [pid 22657] [client 192.168.222.181:44298] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 11:46:09.668407 2018] [authz_core:error] [pid 25264] [client 192.168.222.181:49222] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 12:12:29.709656 2018] [authz_core:error] [pid 26703] [client 192.168.222.181:43974] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 12:17:52.549999 2018] [authz_core:error] [pid 27219] [client 192.168.222.181:48062] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 12:52:44.589719 2018] [authz_core:error] [pid 29466] [client 192.168.222.181:57770] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 13:19:50.130263 2018] [authz_core:error] [pid 29466] [client 192.168.222.181:53436] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 13:42:46.234206 2018] [authz_core:error] [pid 26752] [client 192.168.222.181:49310] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 13:57:13.741664 2018] [authz_core:error] [pid 30717] [client 192.168.222.181:36730] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 14:04:05.419530 2018] [authz_core:error] [pid 25455] [client 192.168.222.181:46528] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 14:07:54.110437 2018] [authz_core:error] [pid 31100] [client 192.168.222.181:53622] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 14:30:37.518919 2018] [authz_core:error] [pid 12212] [client 192.168.222.181:40462] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 14:31:09.162533 2018] [authz_core:error] [pid 11092] [client 192.168.222.181:41134] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 14:31:41.147929 2018] [authz_core:error] [pid 29466] [client 192.168.222.181:41770] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 14:32:09.339790 2018] [authz_core:error] [pid 31100] [client 192.168.222.181:42308] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 15:07:04.089193 2018] [authz_core:error] [pid 13637] [client 192.168.222.181:54016] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 15:20:15.008558 2018] [authz_core:error] [pid 19660] [client 192.168.222.181:40708] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 15:27:19.579843 2018] [authz_core:error] [pid 11784] [client 192.168.222.181:48828] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 15:27:44.409035 2018] [authz_core:error] [pid 12212] [client 192.168.222.181:49258] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 16:03:17.229750 2018] [authz_core:error] [pid 11784] [client 192.168.222.181:34672] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 16:18:27.340162 2018] [authz_core:error] [pid 20418] [client 192.168.222.181:58610] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 16:29:34.525777 2018] [authz_core:error] [pid 20206] [client 192.168.222.181:43662] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 16:47:44.384128 2018] [authz_core:error] [pid 11784] [client 192.168.222.181:35190] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 16:55:07.090259 2018] [authz_core:error] [pid 13637] [client 192.168.222.181:41644] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 17:02:23.348158 2018] [authz_core:error] [pid 22238] [client 192.168.222.181:47372] AH01630: client denied by server configuration: /var/www/nextcloud/config
[Wed Jan 31 17:05:47.975464 2018] [authz_core:error] [pid 11784] [client 192.168.222.181:50252] AH01630: client denied by server configuration: /var/www/nextcloud/config
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Full of ldap query log messages
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> Full of ldap query log messages

They would be useful. ;)

cc @nextcloud/ldap

**Comment by Isotop7** [comment]
Let me grab them tomorrow and remove sensitive info like user names.

**Comment by Isotop7** [comment]
Side info:

My nextcloud.log is growing very fast. On monday it had 16 GB, now its at 34 GB and still growing.
The high load is caused by the cron.php, otherwise the server is idling. It has 4 CPUs and 4 GBs of RAM.

**Comment by Isotop7** [comment]
This is just a small excerpt as the log contains loads of sensitive data and masking it would be a pita but the log is smashed with these lines every second:

```
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"initializing paged search for  Filter (&(|(objectclass=group))(|(cn=group1)(cn=group2)(cn=group3)(cn=group4)(cn=group5))) base Array\n(\n    [0] => cn=group6,ou=spt,ou=group,ou=fra,ou=deu,ou=global,dc=intern,dc=domain,dc=de\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"initializing paged search for  Filter (&(|(objectclass=group))(|(cn=group1)(cn=group2)(cn=group3)(cn=group4)(cn=group5))) base Array\n(\n    [0] => cn=group7,ou=spt,ou=group,ou=fra,ou=deu,ou=global,dc=intern,dc=domain,dc=de\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"initializing paged search for  Filter (&(|(objectclass=group))(|(cn=group1)(cn=group2)(cn=group3)(cn=group4)(cn=group5))) base Array\n(\n    [0] => cn=group8,ou=spt,ou=group,ou=fra,ou=deu,ou=global,dc=intern,dc=domain,dc=de\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"initializing paged search for  Filter (&(|(objectclass=group))(|(cn=group1)(cn=group2)(cn=group3)(cn=group4)(cn=group5))) base Array\n(\n    [0] => cn=group9.domainen,ou=spt,ou=group,ou=fra,ou=deu,ou=global,dc=intern,dc=domain,dc=de\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"initializing paged search for  Filter (&(|(objectclass=group))(|(cn=group1)(cn=group2)(cn=group3)(cn=group4)(cn=group5))) base Array\n(\n    [0] => cn=group10,ou=acl,ou=group,ou=fra,ou=deu,ou=global,dc=intern,dc=domain,dc=de\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
{"reqId":"29JwP1fDIwGGiRdvDQ3Q","remoteAddr":"server-ip","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2018-02-01T09:10:30+01:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user1\/","user":"user1","version":"11.0.6.1"}
```

**Comment by MorrisJobke** [comment]
@isotop7 All the log lines there are debug log (log level 0). Try to raise the log level (either in the admin settings or in config.php) and then check again for possible messages in the Nextcloud log.

**Comment by Isotop7** [comment]
@MorrisJobke Did that. Let me get back when I get warning messages.

**Comment by Isotop7** [comment]
Still no error logs but high load when cronjob is run:

![grafik](https://user-images.githubusercontent.com/8883656/35742663-6ce090e0-083b-11e8-97c7-654d8add03f7.png)

**Comment by MorrisJobke** [comment]
@Isotop7 Could you check the table `oc_jobs` in the database? What is in there?

**Comment by Isotop7** [comment]
@MorrisJobke 
```
mysql> select * from oc_jobs;
+------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-------------+
| id   | class                                             | argument
                                                                                                                                                                                          | last_run   | last_checked | reserved_at |
+------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-------------+
|    1 | OCA\Activity\BackgroundJob\EmailNotification      | null
                                                                                                                                                                                          | 1517904901 |   1517904901 |           0 |
|    2 | OCA\Activity\BackgroundJob\ExpireActivities       | null
                                                                                                                                                                                          | 1517855401 |   1517904901 |           0 |
|    3 | OCA\Files_Trashbin\BackgroundJob\ExpireTrash      | null
                                                                                                                                                                                          | 1517904002 |   1517904901 |           0 |
|    5 | OCA\Files_Versions\BackgroundJob\ExpireVersions   | null
                                                                                                                                                                                          | 1517904002 |   1517904901 |           0 |
|  990 | OCA\Files\BackgroundJob\CleanupFileLocks          | null
                                                                                                                                                                                          | 1517904901 |   1517904901 |           0 |
| 1052 | OCA\Files\BackgroundJob\ScanFiles                 | null
                                                                                                                                                                                          | 1517872501 |   1517872501 |  1517872501 |
| 1053 | OCA\Files\BackgroundJob\DeleteOrphanedItems       | null
                                                                                                                                                                                          | 1517903102 |   1517904901 |           0 |
| 1055 | OCA\DAV\CardDAV\SyncJob                           | null
                                                                                                                                                                                          | 1517846402 |   1517904901 |           0 |
| 1056 | OCA\Federation\SyncJob                            | null
                                                                                                                                                                                          | 1517848207 |   1517904901 |           0 |
| 1057 | \OC\Authentication\Token\DefaultTokenCleanupJob   | null
                                                                                                                                                                                          | 1517904901 |   1517904901 |           0 |
| 1058 | OCA\UpdateNotification\Notification\BackgroundJob | null
                                                                                                                                                                                          | 1517848204 |   1517904901 |           0 |
| 1059 | OCA\User_LDAP\Jobs\UpdateGroups                   | null
                                                                                                                                                                                          | 1517903102 |   1517904901 |           0 |
| 1060 | OCA\User_LDAP\Jobs\CleanUp                        | null
                                                                                                                                                                                          | 1517902202 |   1517904901 |           0 |
| 1062 | OCA\DAV\CardDAV\Sync\SyncJob                      | null
                                                                                                                                                                                          |          0 |   1517901301 |  1517901301 |
| 1063 | OCA\Files_Sharing\DeleteOrphanedSharesJob         | null
                                                                                                                                                                                          | 1517904002 |   1517904901 |           0 |
| 1064 | OCA\Files_Sharing\ExpireSharesJob                 | null
                                                                                                                                                                                          | 1517857201 |   1517904901 |           0 |
| 3920 | OCA\NextcloudAnnouncements\Cron\Crawler           | null
                                                                                                                                                                                          | 1517873402 |   1517904901 |           0 |
+------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-------------+
```

**Comment by blizzz** [comment]
>  user_ldap is disabled

there should also be an exception buried in the log

**Comment by Isotop7** [comment]
> there should also be an exception buried in the log

I' gonna grep the log for every user_ldap message.
What I noticed in the meantime is that wenn I use OCC and any command connected to ldap (user:list or ldap:search) the command takes forever, its allocating much RAM until the machine almost stalls and then OOM is killing the task.

This doesnt seems right. Maybe my ldap config is borked in some way...

**Comment by blizzz** [comment]
Yeah, that does not sound right. Which LDAP server is in use?

**Comment by Isotop7** [comment]
It's a Microsoft Active Directory on a Windows Server 2012 R2 machine.

We're searching on the root dn. This could be the cause why queries are slower, but not the cause for freezes or memory overflows.

**Comment by blizzz** [comment]
anything about the log file? might not only be on user_ldap, but also PHP e.g.
