### ISSUE TITLE
occ broken on Nextcloud 13 rc 4

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#8190]
If I try to run the occ command on Nextcloud 13 RC4 I get:

````
An unhandled exception has been thrown:
Error: Call to undefined function OC\App\simplexml_load_file() in /home/schiesbn/repos/nextcloud/server/master/lib/private/App/InfoParser.php:64
Stack trace:
#0 /home/schiesbn/repos/nextcloud/server/master/lib/private/legacy/app.php(619): OC\App\InfoParser->parse('/home/schiesbn/...')
#1 /home/schiesbn/repos/nextcloud/server/master/lib/private/AppFramework/App.php(62): OC_App::getAppInfo('files')
#2 /home/schiesbn/repos/nextcloud/server/master/lib/private/legacy/app.php(211): OC\AppFramework\App::buildAppNamespace('files')
#3 /home/schiesbn/repos/nextcloud/server/master/lib/private/legacy/app.php(119): OC_App::registerAutoloading('files', '/home/schiesbn/...')
#4 /home/schiesbn/repos/nextcloud/server/master/lib/base.php(661): OC_App::loadApps(Array)
#5 /home/schiesbn/repos/nextcloud/server/master/lib/base.php(1080): OC::init()
#6 /home/schiesbn/repos/nextcloud/server/master/console.php(46): require_once('/home/schiesbn/...')
#7 /home/schiesbn/repos/nextcloud/server/master/occ(11): require_once('/home/schiesbn/...')
````

**Comment by newhinton** [comment]
i've got the exact same issue, how did you fix it? 
php-xml is installed, and my phpinfo() says so, too.

**Comment by richarZero22** [comment]
Hi @newhinton, I'd the same issue and I fixed that, if you need help you can say me, regards
