### ISSUE TITLE
Internal Server Error - Error	PHP	Out of memory (allocated 68419584) (tried to allocate 4310784 bytes) at /3rdparty/sabre/dav/lib/DAV/Server.php#1683

### ISSUE THREAD

**Issue by PetrusVermaak** [nextcloud/server#8388]
### Steps to reproduce
1. Upgraded from Nextcloud 12 to Nextcloud 13 via the updater and then problem started.
2. Performed clean install of nextcloud 12 with existing database, error still exists.
3. Performed clean install of nextcloud 13 with existing database, error still exists.

### Expected behaviour
Nextcloud should sync via the desktop app, instead I get "Internal Server Error"
Nextcloud should allow me to log into the website and open a specific folder, instead I get  

### Actual behaviour
Nextcloud should sync via the desktop app, instead I get "Internal Server Error"
Nextcloud should allow me to log into the website and open a specific folder, instead I get  

### Server configuration
NEXTCLOUD installed to folder \public_html\storagecloud\
DATA folder remapped to \public_html\cloud_data\
SHARED HOSTING
PHP5.6
MYSQL

**Operating system**:
CENTOS

**Web server:**
SHARED HOSTING

**Database:**
MySQL

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
13

**Updated from an older Nextcloud/ownCloud or fresh install:**
First time updated existing Nextcloud 12 installation via the online updater.
Second time re-used database, fresh nextcloud install

**Where did you install Nextcloud from:**
1. Updated existing Nextcloud 12 through the web updater
2. Download standalone 12 from nextcloud.com
3. Download standalone 13 from nextcloud.com

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**List of activated apps:**
Activity 2.6.1 Official
Auditing / Logging 1.3.0 Official
Brute-force settings 1.0.3
Collaborative tags 1.3.0 Official
Comments 1.3.0 Official
Deleted files 1.3.0 Official
Federation 1.3.0 Official
File sharing 1.5.0 Official
First run wizard 2.2.1 Official
Gallery 18.0.0 Official
Log Reader 2.0.0 Official
Monitoring 1.3.0 Official
Nextcloud announcements 1.2.0 Official
Notifications 2.1.2 Official
Password policy 1.3.0 Official
PDF viewer 1.2.0 Official
Share by mail 1.3.0 Official
Text editor 2.5.1 Official
Theming 1.4.1 Official
Update notification 1.3.0 Official
Usage survey 1.1.0 Official
Versions 1.6.0 Official
Video player 1.2.0 Official 


Insert your config.php content here. 
<?php
$CONFIG = array (
  'instanceid' => 'ochejhfwbwki',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'petrusv.co.za',
    1 => 'scloud.petrusv.co.za',
    2 => 'web191.secure-secure.co.uk',
  ),
  'datadirectory' => '/home/sites/petrusv.co.za/public_html/cloud_data/data',
  'overwrite.cli.url' => 'http://petrusv.co.za/storagecloud',
  'dbtype' => 'mysql',
  'version' => '13.0.0.14',
  'dbname' => 'cl54-nextcloud',
  'dbhost' => '217.199.187.191',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cl54-nextcloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxx',
  'filelocking.enabled' => false,
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO, Same server but different folder location.
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
Windows nexcloud desktop client 2.3.3 build 1 & Firefox & Chrome Browser

**Operating system:**
Windows 10

### Logs

#### Web server error log
Insert your webserver log here
3769 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215:     0  : /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3772 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215: \r  0     0    0     0    0 : /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3774 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215:     0 : /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3776 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215:      0 -: /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3769 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215: -:--:-- : /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3774 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215: --:--:-: /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3776 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215: - --:--:-: /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3771 petrusv.co.za [Fri Feb 16 07:00:13 2018] [error] [client 169.239.180.208:41052] AH01215: -     0: /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3767 petrusv.co.za [Fri Feb 16 07:00:14 2018] [error] [client 169.239.180.208:41052] AH01215: \r  0    20    0    20    0     0     36  : /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
3768 petrusv.co.za [Fri Feb 16 07:00:14 2018] [error] [client 169.239.180.208:41052] AH01215:     0 --:--:-- --:--:-- --:--:--    41: /home/sites/petrusv.co.za/public_html/cron_jobs/petrusv.co.za.cloud.cron.curl.php
15574 scloud.petrusv.co.za [Thu Feb 15 19:50:24 2018] [error] [client 41.66.203.229:41090] AH01215: #2 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
15595 scloud.petrusv.co.za [Thu Feb 15 19:50:24 2018] [error] [client 41.66.203.229:41090] AH01215: #3 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
15591 scloud.petrusv.co.za [Thu Feb 15 19:50:24 2018] [error] [client 41.66.203.229:41090] AH01215: #4 /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/DB/Connection.php(148): Doctrine\\DBAL\\Con in /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/DB/Connection.php on line 61: /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17235 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: #0 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17242 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: Stack trace:: /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17233 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: #1 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17238 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No route to host' in /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/DB/Connection.php:61: /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17234 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: #3 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17241 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: #2 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17239 scloud.petrusv.co.za [Thu Feb 15 20:39:10 2018] [error] [client 41.66.203.229:59936] AH01215: #4 /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/DB/Connection.php(148): Doctrine\\DBAL\\Con in /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/DB/Connection.php on line 61: /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17239 scloud.petrusv.co.za [Thu Feb 15 20:39:13 2018] [error] [client 41.66.203.229:59936] AH01215: PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No route to host' in /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/DB/Connection.php:61: /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17238 scloud.petrusv.co.za [Thu Feb 15 20:39:13 2018] [error] [client 41.66.203.229:59936] AH01215: Stack trace:: /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17240 scloud.petrusv.co.za [Thu Feb 15 20:39:13 2018] [error] [client 41.66.203.229:59936] AH01215: #0 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php
17235 scloud.petrusv.co.za [Thu Feb 15 20:39:13 2018] [error] [client 41.66.203.229:59936] AH01215: #1 /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion(): /home/sites/petrusv.co.za/public_html/storagecloud/index.php

#### Nextcloud log (data/nextcloud.log)
Security & setup warnings

It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the Tips & Tricks section and the documentation for more information.

    Transactional file locking is disabled, this might lead to issues with race conditions. Enable 'filelocking.enabled' in config.php to avoid these problems. See the documentation ↗ for more information.

    The "X-XSS-Protection" HTTP header is not set to "1; mode=block". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
    The "X-Content-Type-Options" HTTP header is not set to "nosniff". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
    The "X-Robots-Tag" HTTP header is not set to "none". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
    The "X-Download-Options" HTTP header is not set to "noopen". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
    The "X-Permitted-Cross-Domain-Policies" HTTP header is not set to "none". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
    Accessing site insecurely via HTTP. You are strongly adviced to set up your server to require HTTPS instead, as described in the security tips.

    No memory cache has been configured. To enhance performance, please configure a memcache, if available. Further information can be found in the documentation.
    You are currently running PHP 5.6.32. Upgrade your PHP version to take advantage of performance and security updates provided by the PHP Group as soon as your distribution supports it.
    You are currently running PHP 5.6. The current major version of Nextcloud is the last that is supported on PHP 5.6. It is recommended to upgrade the PHP version to 7.0+ to be able to upgrade to Nextcloud 14.
    The PHP OPcache is not properly configured. For better performance it is recommended to use the following settings in the php.ini:

    opcache.enable=1
    opcache.enable_cli=1
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.save_comments=1
    opcache.revalidate_freq=1


Insert your Nextcloud log here
Error | PHP | Out  of memory (allocated 67633152) (tried to allocate 5989872 bytes) at  /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/sabre/dav/lib/DAV/Server.php#1684 | 2018-02-16T09:05:11+0200
-- | -- | -- | --
Error | PHP | Out  of memory (allocated 70516736) (tried to allocate 4122466 bytes) at  /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/sabre/dav/lib/DAV/Server.php#1684 | 2018-02-16T08:59:24+0200
Error | PHP | Out  of memory (allocated 70516736) (tried to allocate 4122466 bytes) at  /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/sabre/dav/lib/DAV/Server.php#1684 | 2018-02-16T08:58:39+0200
Error | PHP | Out  of memory (allocated 70516736) (tried to allocate 4122466 bytes) at  /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/sabre/dav/lib/DAV/Server.php#1684 | 2018-02-16T08:57:31+0200
Error | PHP | Out  of memory (allocated 70516736) (tried to allocate 4122466 bytes) at  /home/sites/petrusv.co.za/public_html/storagecloud/3rdparty/sabre/dav/lib/DAV/Server.php#1684 | 2018-02-16T08:57:02+0200
Error | PHP | Automatically  populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a  future version. To avoid this warning set  'always_populate_raw_post_data' to '-1' in php.ini and use the  php://input stream instead. at Unknown#0 | 2018-02-16T08:56:38+0200
Error | PHP | Automatically  populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a  future version. To avoid this warning set  'always_populate_raw_post_data' to '-1' in php.ini and use the  php://input stream instead. at Unknown#0 | 2018-02-16T08:54:46+0200
Error | PHP | imagettftext(): Could not read font at /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/Avatar.php#266 | 2018-02-16T08:51:02+0200
Error | PHP | imagettfbbox(): Could not read font at /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/Avatar.php#260 | 2018-02-16T08:51:02+0200
Error | PHP | imagettftext(): Could not read font at /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/Avatar.php#266 | 2018-02-16T08:50:58+0200
Error | PHP | imagettfbbox(): Could not read font at /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/Avatar.php#260 | 2018-02-16T08:50:58+0200
Error | PHP | imagettftext(): Could not read font at /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/Avatar.php#266 | 2018-02-16T08:50:58+0200
Error | PHP | imagettfbbox(): Could not read font at /home/sites/petrusv.co.za/public_html/storagecloud/lib/private/Avatar.php#260

**Comment by rullzer** [comment]
Please increase the memory php can use. It seems it is set a very low value.68419584 bytes ~ 65mb
