### ISSUE TITLE
Increase in processor and memory with ios client and nexcloud 13

### ISSUE THREAD

**Issue by ruimgspereira** [nextcloud/server#8394]
Whenever I use the ios app on a non-cached folder the CPU usage increases and the memory fills up, creating a error 500: Internal server error.

The 
/usr/sbin/apache2 -k start CPU usage is full (with various PID) also with around 500MB memory usage
/usr/sbin/mysqld memory is high 
Example below:

  1  [||||||||||||||||||||||||||||||||||||||||||100.0%]   Tasks: 95, 23 thr; 39 running
  2  [||||||||||||||||||||||||||||||||||||||||||100.0%]   Load average: 37.21 19.27 11.05
  Mem[|||||||||||||||||||||||||||||||||||||1.84G/1.96G]   Uptime: 11:57:03
  Swp[|||||||||||||||||||||||||||||||||||||1.99G/1.99G]

 ```
 PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 1913 www-data   20   0  358M   99M  3836 R  2.5  5.0  0:08.24 /usr/sbin/apache2 -k start
 1565 www-data   20   0  346M 96964  3092 R  3.2  4.7  0:13.95 /usr/sbin/apache2 -k start
 1571 www-data   20   0  345M 96040  3100 R  2.5  4.7  0:13.02 /usr/sbin/apache2 -k start
 1922 www-data   20   0  358M 95224  3832 R  3.2  4.6  0:08.02 /usr/sbin/apache2 -k start
 2204 www-data   20   0  345M 91776  3092 R  2.5  4.5  0:04.96 /usr/sbin/apache2 -k start
 2206 www-data   20   0  345M 81184  3092 R  3.2  4.0  0:04.90 /usr/sbin/apache2 -k start
 2229 www-data   20   0  345M 80436  4448 R  2.5  3.9  0:03.82 /usr/sbin/apache2 -k start
 1549 www-data   20   0  360M 80012  3088 R  2.5  3.9  0:14.23 /usr/sbin/apache2 -k start
 2227 www-data   20   0  345M 77784  4448 R  2.5  3.8  0:03.76 /usr/sbin/apache2 -k start
 1306 www-data   20   0  348M 74916  3604 R  2.5  3.7  1:05.88 /usr/sbin/apache2 -k start
 1927 www-data   20   0  358M 74812  3088 R  1.9  3.6  0:06.47 /usr/sbin/apache2 -k start
 2222 www-data   20   0  346M 72120  3128 R  3.2  3.5  0:04.60 /usr/sbin/apache2 -k start
 1542 www-data   20   0  360M 71612  3088 R  3.2  3.5  0:15.45 /usr/sbin/apache2 -k start
 2413 mysql      20   0 99412 71372  4268 S  0.0  3.5  0:00.62 /usr/sbin/mysqld
32058 www-data   20   0  369M 69236  3152 R  2.5  3.4  2:02.45 /usr/sbin/apache2 -k start
  990 www-data   20   0  367M 65724  3148 R  2.5  3.2  1:09.14 /usr/sbin/apache2 -k start
 1654 www-data   20   0  287M 55828  3956 R  2.5  2.7  0:11.58 /usr/sbin/apache2 -k start
 2233 www-data   20   0  284M 55060  3964 R  2.5  2.7  0:03.10 /usr/sbin/apache2 -k start
 2239 www-data   20   0  284M 53612  3968 R  3.2  2.6  0:03.02 /usr/sbin/apache2 -k start
 2207 www-data   20   0  285M 51288  3960 R  2.5  2.5  0:03.68 /usr/sbin/apache2 -k start
 2236 www-data   20   0  285M 50048  3960 R  2.5  2.4  0:03.20 /usr/sbin/apache2 -k start
 2202 www-data   20   0  345M 49728  3088 R  1.9  2.4  0:05.79 /usr/sbin/apache2 -k start
  989 www-data   20   0  356M 47780  3152 R  2.5  2.3  1:13.18 /usr/sbin/apache2 -k start
32060 www-data   20   0  370M 42764  3152 R  2.5  2.1  2:44.07 /usr/sbin/apache2 -k start
 1647 www-data   20   0  345M 35096  3088 R  3.2  1.7  0:13.56 /usr/sbin/apache2 -k start
 1928 www-data   20   0  345M 33824  3088 R  3.2  1.6  0:06.36 /usr/sbin/apache2 -k start
 1570 www-data   20   0  345M 32144  3088 R  2.5  1.6  0:15.00 /usr/sbin/apache2 -k start
 1444 www-data   20   0  347M 23260  3088 R  3.2  1.1  0:15.71 /usr/sbin/apache2 -k start
 2223 www-data   20   0  235M 11372  7528 S  0.0  0.6  0:01.77 /usr/sbin/apache2 -k start
32150 www-data   20   0  235M 10812  6992 S  0.0  0.5  1:06.56 /usr/sbin/apache2 -k start
 1443 www-data   20   0  234M 14280 10540 S  2.5  0.7  0:07.96 /usr/sbin/apache2 -k start
31917 www-data   20   0  234M 10508  6968 S  0.0  0.5  1:00.05 /usr/sbin/apache2 -k start
 1652 www-data   20   0  345M 12768  3088 R  2.5  0.6  0:11.60 /usr/sbin/apache2 -k start
 4436 www-data   20   0  354M 12752  3152 R  2.5  0.6  2:07.63 /usr/sbin/apache2 -k start
 1891 www-data   20   0  345M 12724  3096 R  2.5  0.6  0:11.23 /usr/sbin/apache2 -k start
 1552 www-data   20   0  345M 12600  3088 R  2.5  0.6  0:16.01 /usr/sbin/apache2 -k start
 2320 www-data   20   0  234M  8644  5692 S  0.0  0.4  0:00.68 /usr/sbin/apache2 -k start
 2315 www-data   20   0  234M 11856  8916 S  0.0  0.6  0:00.56 /usr/sbin/apache2 -k start
 2321 www-data   20   0  234M  8636  5668 S  0.0  0.4  0:00.55 /usr/sbin/apache2 -k start
 2316 www-data   20   0  234M  8600  5700 S  0.0  0.4  0:00.44 /usr/sbin/apache2 -k start
 1653 www-data   20   0  345M 12104  3088 R  3.2  0.6  0:11.35 /usr/sbin/apache2 -k start
 2327 www-data   20   0  234M  8608  5668 R  2.5  0.4  0:00.54 /usr/sbin/apache2 -k start
 2324 www-data   20   0  234M  8580  5668 S  0.0  0.4  0:00.50 /usr/sbin/apache2 -k start
 2326 www-data   20   0  234M  8564  5640 R  1.3  0.4  0:00.50 /usr/sbin/apache2 -k start
 1651 www-data   20   0  345M 11724  3088 R  2.5  0.6  0:08.08 /usr/sbin/apache2 -k start
31923 www-data   20   0  357M 11672  3152 R  2.5  0.6  2:03.65 /usr/sbin/apache2 -k start
 2413 mysql      20   0 99412 73396  6168 S  0.0  3.6  0:00.62 /usr/sbin/mysqld
    1 root       20   0 24196  2332  1832 S  0.0  0.1  0:15.05 /sbin/init
```

### Steps to reproduce
1. Open ios app (insure the cache is clean)
2. Access a folder with thumbnails to load (or reload after clean cache)
3. After a while internal server error : 500 occurs

### Expected behaviour
For the server to load the thumbnails and operate accordingly

### Actual behaviour
The server processor shoots through the roof 
Memory starts to fill up to the limits, then the swap, until... it cannot allocate more memory

### Server configuration
Humble configuration: Intel atom with 2gb ram

**Operating system**: 
Ubuntu 16.04

**Web server:**
Apache 2

**Database:**
Mysql

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
NO

**Where did you install Nextcloud from:**
Nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - music: 0.5.5
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "blabla.ddns.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/blabla.ddns.net\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome 63.0.3239.132 but on this case IOS App 
**Operating system:**
Windows 10 but on this case IOS  11.2.5

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
I have numerous lines like this but ending with...
[Fri Feb 16 10:30:30.757494 2018] [:error] [pid 32150] [client bla.bla.bla.bla:55817] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/nextcloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrin in /var/www/html/nextcloud/lib/private/DB/Connection.php on line 64
[Fri Feb 16 10:30:31.706506 2018] [:error] [pid 31994] [client bla.bla.bla.bla:55818] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/nextcloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrin in /var/www/html/nextcloud/lib/private/DB/Connection.php on line 64
[Fri Feb 16 10:30:31.728337 2018] [:error] [pid 31928] [client bla.bla.bla.bla:55819] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/nextcloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrin in /var/www/html/nextcloud/lib/private/DB/Connection.php on line 64

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Again, I have numerous like this:

{"reqId":"WGf77akRieFoJIUZYdiO","level":3,"time":"2018-02-16T10:31:14+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150389.JPG","message":"Error while sending QUERY packet. PID=4360 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"shwpM22fRhFVQlAcuQ2p","level":3,"time":"2018-02-16T10:31:29+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150380.JPG","message":"Error while sending QUERY packet. PID=31927 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"ikHFZJ9dWRGNC9FE3C7Z","level":3,"time":"2018-02-16T10:31:32+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150358.JPG","message":"Error while sending QUERY packet. PID=31992 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"PVPjw7adxf8zQrfBSzrL","level":3,"time":"2018-02-16T10:31:35+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150362.JPG","message":"Error while sending QUERY packet. PID=4504 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"LdDT113rxCfT5FE6BLP1","level":3,"time":"2018-02-16T10:31:35+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150359.JPG","message":"Error while sending QUERY packet. PID=31979 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"AghuNXwX2E2HDHquCWXD","level":3,"time":"2018-02-16T10:31:36+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150361.JPG","message":"Error while sending QUERY packet. PID=31978 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"2IqpcCbH0iJvHWS2jCk2","level":3,"time":"2018-02-16T10:31:37+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150360.JPG","message":"Error while sending QUERY packet. PID=31977 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"GpwkeK9nYu6VWH4cSDOU","level":3,"time":"2018-02-16T10:31:40+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150380.JPG","message":"Error while sending QUERY packet. PID=31997 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"vtTy7GJcwa2l5TSOVrcR","level":3,"time":"2018-02-16T10:31:42+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150384.JPG","message":"Error while sending QUERY packet. PID=31999 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"FyIRxjvJIGp05t9Q2VmK","level":3,"time":"2018-02-16T10:31:46+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150383.JPG","message":"Error while sending QUERY packet. PID=32004 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"wUBEuuahGoMqRp0reRVq","level":3,"time":"2018-02-16T10:31:47+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150385.JPG","message":"Error while sending QUERY packet. PID=32000 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"Dfn4KgbP1bUNf19S0CY0","level":3,"time":"2018-02-16T10:31:47+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150356.JPG","message":"Error while sending QUERY packet. PID=32002 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"IMwqcZuAftGHfrE94dm6","level":3,"time":"2018-02-16T10:31:48+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150386.JPG","message":"Error while sending QUERY packet. PID=32001 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"fTtZw80JYX6XPQcM5XeF","level":3,"time":"2018-02-16T10:31:51+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150387.JPG","message":"Error while sending QUERY packet. PID=32058 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"IxG5AtKvl8Rtm5NlsLGm","level":3,"time":"2018-02-16T10:32:00+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150382.JPG","message":"Error while sending QUERY packet. PID=31922 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"Ru9FYhXGvehGmkmSTfnv","level":3,"time":"2018-02-16T10:32:02+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150372.JPG","message":"Error while sending QUERY packet. PID=31917 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"ILrwAybJUsFPfgX8rTyw","level":3,"time":"2018-02-16T10:32:03+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150381.JPG","message":"Error while sending QUERY packet. PID=32003 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"J7UF4joPJ6zLD8uSPnKz","level":3,"time":"2018-02-16T10:32:03+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150367.JPG","message":"Error while sending QUERY packet. PID=31989 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"KVQjo90JvAfFuW7okOCV","level":3,"time":"2018-02-16T10:32:05+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150368.JPG","message":"Error while sending QUERY packet. PID=31988 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"WIpLGw05MYz3hKXGM7iI","level":3,"time":"2018-02-16T10:32:06+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150388.JPG","message":"Error while sending QUERY packet. PID=32060 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
{"reqId":"Xs0v6eNojgRYQ5p5etdZ","level":3,"time":"2018-02-16T10:32:06+00:00","remoteAddr":"bla.bla.bla.bla","user":"user","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/128\/128\/Photos%20Owncloud\/2018\/02\/P2150370.JPG","message":"Error while sending QUERY packet. PID=31983 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.20.1","version":"13.0.0.14"}
</details>

**Comment by tflidd** [comment]
It's a good idea to let mysql use as much memory it needs, however it shouldn't crash the system. In your case, you have a lot of apache processes running. I'd reduce this number down to a value that it can handle accesses to Nextcloud.
If you don't have installed caching (redis, APCU), this can reduce the load on your system considerably.

I don't see a real issue we can handle in the code. For further configuration questions, ask in the forum: help.nextcloud.com or if you have ideas to improve the documentation, this can be put here https://github.com/nextcloud/documentation/issues
