### ISSUE TITLE
NC13 - Call to undefined method OC_Defaults::replaceImagePath()

### ISSUE THREAD

**Issue by alexBeuth** [nextcloud/server#8420]
### Steps to reproduce
1. Update to Nextcloud 13
2. Go to login page

### Expected behaviour
Login page is shown

### Actual behaviour
White page - 500 Server error

### Workaround:
Disable Theming app

### Server configuration

**Operating system**:
Raspbian Stretch
**Web server:**
Nginx
**Database:**
MariaDB
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
13.0.0.14
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 12
**Where did you install Nextcloud from:**
Updater
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - theming
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": ""***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "overwritehost": ""***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "http",
        "maintenance": false,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 58.0
**Operating system:**
Windows
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No relevent logs
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Pngq05PZplJgvoOVthk1","level":3,"time":"2018-02-18T15:24:02+00:00","remoteAddr":"***","user":"--","app":"index","method":"GET","url":"\/index.php\/login","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC_Defaults::replaceImagePath()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(198): OC\\\\URLGenerator->imagePath('core', 'favicon-touch.p...')\\n#1 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->showLoginForm(NULL, NULL, NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'showLoginForm', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/login')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(37): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php\",\"Line\":173}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"Pngq05PZplJgvoOVthk1","level":3,"time":"2018-02-18T15:24:02+00:00","remoteAddr":"***","user":"--","app":"PHP","method":"GET","url":"\/index.php\/login","message":"Error: Call to undefined method OC_Defaults::replaceImagePath() at \/var\/www\/owncloud\/lib\/private\/URLGenerator.php#173","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"7dknFans2fNlmhuxWXwR","level":3,"time":"2018-02-18T15:24:03+00:00","remoteAddr":"***","user":"--","app":"index","method":"GET","url":"\/index.php\/login","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC_Defaults::replaceImagePath()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(198): OC\\\\URLGenerator->imagePath('core', 'favicon-touch.p...')\\n#1 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->showLoginForm(NULL, NULL, NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'showLoginForm', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/login')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(37): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php\",\"Line\":173}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
I have not saved this. Can reproduce if needed
```
</details>

**Comment by MorrisJobke** [comment]
> {"reqId":"Pngq05PZplJgvoOVthk1","level":3,"time":"2018-02-18T15:24:02+00:00","remoteAddr":"***","user":"--","app":"PHP","method":"GET","url":"\/index.php\/login","message":"Error: Call to undefined method OC_Defaults::replaceImagePath() at \/var\/www\/owncloud\/lib\/private\/URLGenerator.php#173","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

I guess why this happens:

If the domain is not trusted it falls back to \OC_Defaults. Let me try to verify this.

**Comment by MorrisJobke** [comment]
Fix is in #8557

**Comment by DavidVentura** [comment]
I just upgraded via the webUI and I'm having this same issue.

**Comment by MorrisJobke** [comment]
Will be fixed in 13.0.1

**Comment by MaartenMol96** [comment]
@MorrisJobke When will this be released? I am using the Docker image, and having the same issue. Is there a workaround?

**Comment by alexBeuth** [comment]
As a workaround you can disable the theming app

**Comment by MaartenMol96** [comment]
@alexBeuth just by deleting the theming folder in de apps folder?

**Comment by alexBeuth** [comment]
I used the [occ](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html) tool
`sudo -u www-data php occ app:disable theming`

**Comment by MaartenMol96** [comment]
So update 13.0.1 did fix access to the web panel, however the theming app is not working anymore. Whenever I change something it doesn't change anything.
