### ISSUE TITLE
Server replied: Internal Server error

### ISSUE THREAD

**Issue by addaitrs** [nextcloud/server#8547]
### Steps to reproduce
1. Create a file on client PC, allow desktop client to upload to server
2. Make changes to document and save
3. Desktop client tried uploading the file to the server

### Expected behaviour
It should overwrite the exiting file with the new version

### Actual behaviour
Desktop client errors with

"The item is not synced because of previous errors: Error transferring https:/blahblah/texfile.txt - server replied: Internal Server error

### Server configuration

**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
.OVF from techandme

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"YyyNRechxSAADDAAdJuy","level":2,"time":"2018-02-26T16:53:42+00:00","remoteAddr":"139.162.78.135","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"139.162.78.135\" tried to access using \"193.105.231.83\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/45.0.2454.101 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"sin8mcZ8c7x7VdtVvwlG","level":3,"time":"2018-02-26T17:04:37+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"cjd36uuKLV0ZHnkgIH4l","level":3,"time":"2018-02-26T17:04:40+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"NeFQmKlVgoQkEHUdZZzq","level":3,"time":"2018-02-26T17:06:04+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"rSBZ0ytARdbXOmECIWEW","level":3,"time":"2018-02-26T17:06:06+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"W8kAlYf9OGkyjFurPqZ7","level":3,"time":"2018-02-26T17:13:44+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"KFmTzaYO0OZKIjnoFYpz","level":3,"time":"2018-02-26T17:13:47+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"KnHWZaigN8RNlp7pYl9Q","level":3,"time":"2018-02-26T17:14:08+00:00","remoteAddr":"IPAddress","user":"UserName","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/UserName\/BMS\/company\/hello.txt","message":"include(\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/composer\/..\/icewind\/smb\/src\/Exception\/InvalidArgumentException.php): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"KnHWZaigN8RNlp7pYl9Q","level":3,"time":"2018-02-26T17:14:08+00:00","remoteAddr":"IPAddress","user":"UserName","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/UserName\/BMS\/company\/hello.txt","message":"include(): Failed opening '\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/composer\/..\/icewind\/smb\/src\/Exception\/InvalidArgumentException.php' for inclusion (include_path='\/var\/www\/nextcloud\/3rdparty\/pear\/console_getopt:\/var\/www\/nextcloud\/3rdparty\/pear\/pear_exception:\/var\/www\/nextcloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/nextcloud\/3rdparty\/pear\/archive_tar:\/var\/www\/nextcloud\/apps') at \/var\/www\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"KnHWZaigN8RNlp7pYl9Q","level":3,"time":"2018-02-26T17:14:08+00:00","remoteAddr":"IPAddress","user":"UserName","app":"remote","method":"PUT","url":"\/remote.php\/dav\/files\/UserName\/BMS\/company\/hello.txt","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class '\\\\Icewind\\\\SMB\\\\Exception\\\\InvalidArgumentException' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(49): Icewind\\\\SMB\\\\Exception\\\\Exception::fromMap(Array, 22, '\\\/Data\\\/company\\\/h...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(61): Icewind\\\\SMB\\\\NativeState->handleError('\\\/Data\\\/company\\\/h...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(125): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/172.16.10...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(160): Icewind\\\\SMB\\\\NativeState->rename('smb:\\\/\\\/172.16.10...', 'smb:\\\/\\\/172.16.10...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(198): Icewind\\\\SMB\\\\NativeShare->rename('\\\/Data\\\/company\\\/h...', '\\\/Data\\\/company\\\/h...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(276): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(299): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(160): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(285): OCA\\\\Files_Trashbin\\\\Storage->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(582): OCA\\\\FilesAccessControl\\\\StorageWrapper->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(210): OCA\\\\FilesAccessControl\\\\StorageWrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'company\\\/hello.t...', 'company\\\/hello.t...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #22)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/russellsa...', Resource id #22, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#19 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Exception\\\/Exception.php\",\"Line\":30}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"YaqYy0qgZVBMmmWQu5Rk","level":3,"time":"2018-02-26T17:16:05+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"FzYGyYoCh7dwVE5Cui6Z","level":3,"time":"2018-02-26T17:16:09+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"hgziR2Kqlp2RlYxuh8aS","level":3,"time":"2018-02-26T17:16:18+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"EbIDqTZZTeFk66Ptpqzv","level":3,"time":"2018-02-26T17:16:22+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"68U4ayEHEPREmQltZiLI","level":3,"time":"2018-02-26T17:16:26+00:00","remoteAddr":"IPAddress","user":"UserName","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.97 Safari\/537.36 Vivaldi\/1.94.1008.44","version":"13.0.0.14"}
{"reqId":"aekZl4lYS4vL3bJBYY4u","level":3,"time":"2018-02-26T17:23:40+00:00","remoteAddr":"IPAddress","user":"UserName","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/UserName\/BMS\/company\/hello.txt","message":"include(\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/composer\/..\/icewind\/smb\/src\/Exception\/InvalidArgumentException.php): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"aekZl4lYS4vL3bJBYY4u","level":3,"time":"2018-02-26T17:23:40+00:00","remoteAddr":"IPAddress","user":"UserName","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/UserName\/BMS\/company\/hello.txt","message":"include(): Failed opening '\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/composer\/..\/icewind\/smb\/src\/Exception\/InvalidArgumentException.php' for inclusion (include_path='\/var\/www\/nextcloud\/3rdparty\/pear\/console_getopt:\/var\/www\/nextcloud\/3rdparty\/pear\/pear_exception:\/var\/www\/nextcloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/nextcloud\/3rdparty\/pear\/archive_tar:\/var\/www\/nextcloud\/apps') at \/var\/www\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"aekZl4lYS4vL3bJBYY4u","level":3,"time":"2018-02-26T17:23:40+00:00","remoteAddr":"IPAddress","user":"UserName","app":"remote","method":"PUT","url":"\/remote.php\/dav\/files\/UserName\/BMS\/company\/hello.txt","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class '\\\\Icewind\\\\SMB\\\\Exception\\\\InvalidArgumentException' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(49): Icewind\\\\SMB\\\\Exception\\\\Exception::fromMap(Array, 22, '\\\/Data\\\/company\\\/h...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(61): Icewind\\\\SMB\\\\NativeState->handleError('\\\/Data\\\/company\\\/h...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(125): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/172.16.10...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(160): Icewind\\\\SMB\\\\NativeState->rename('smb:\\\/\\\/172.16.10...', 'smb:\\\/\\\/172.16.10...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(198): Icewind\\\\SMB\\\\NativeShare->rename('\\\/Data\\\/company\\\/h...', '\\\/Data\\\/company\\\/h...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(276): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(299): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(160): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(285): OCA\\\\Files_Trashbin\\\\Storage->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(582): OCA\\\\FilesAccessControl\\\\StorageWrapper->rename('company\\\/hello.t...', 'company\\\/hello.t...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(210): OCA\\\\FilesAccessControl\\\\StorageWrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'company\\\/hello.t...', 'company\\\/hello.t...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #25)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/russellsa...', Resource id #25, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#19 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Exception\\\/Exception.php\",\"Line\":30}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
`Class '\\\\Icewind\\\\SMB\\\\Exception\\\\InvalidArgumentException' not found` - cc @icewind1991

**Comment by Orbital-Bit** [comment]
same issue with external storage on SMB (CIFS) as i reported here: [8978](https://github.com/nextcloud/server/issues/8978) and someone else reported here: [9000](https://github.com/nextcloud/server/issues/9000)

**Comment by icewind1991** [comment]
Please try applying https://github.com/nextcloud/server/pull/9017 which should hopefully provide some more info

**Comment by Orbital-Bit** [comment]
applied the patch, the problem is still there, 
here is what is in the
<details>
<summary>nextcloud.log</summary>
{"reqId":"7Q7mhnop3WFQRZ3JeLLY","level":3,"time":"2018-03-28T16:02:13+00:00","remoteAddr":"10.20.30.232","user":"syncMaster","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/sync-DEMO\/test.file.txt","message":"renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: true)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36 OPR\/51.0.2830.55","version":"12.0.6.1"}
{"reqId":"7Q7mhnop3WFQRZ3JeLLY","level":4,"time":"2018-03-28T16:02:13+00:00","remoteAddr":"10.20.30.232","user":"syncMaster","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/sync-DEMO\/test.file.txt","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #9)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('sync-DEMO\\\/test....', Resource id #9, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":186}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36 OPR\/51.0.2830.55","version":"12.0.6.1"}
</details>
and
<details>
<summary>Logging section in Admin page</summary>

Level | App | Message | Time
-- | -- | -- | --
Fatal | webdav | Sabre\DAV\Exception: Could not rename part file to final file/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1130:OCA\DAV\Connector\Sabre\File->put(Resource id #9)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 513:Sabre\DAV\Server->updateFile('sync-DEMO/test....', Resource id #9, NULL)[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array(Array, Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit('method PUT', Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 76:Sabre\DAV\Server->exec()/var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...'){main} | 2018-03-28T12:02:13-0400
Error | webdav | renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: true) | 2018-03-28T12:02:13-0400

</details>
<br>
because the error mentions renaming, tried to rename the file manually via the web interface, that worked as expected.

**Comment by seederp2p** [comment]
I've the same issue...

**Comment by seederp2p** [comment]
@icewind1991 any hint?

**Comment by Orbital-Bit** [comment]
there was an issue reported [here 9021](https://github.com/nextcloud/server/issues/9021) that sounds very similar, but it involves Federated Storage as external storage location.

**Comment by MorrisJobke** [comment]
Let's close this as duplicate of #8978 (and it's other linked tickets) and continue there.
