### ISSUE TITLE
OC\Updater not found in core/Command/Upgrade.php

### ISSUE THREAD

**Issue by DrissiReda** [nextcloud/server#8712]
Today there was apparently an update for the TOTP app and when I launch the updater it just shows me "An error occurred." and nothing else.
### Steps to reproduce
1. Launching the upgrade from the browser
2. Or launch the updater from terminal

### Expected behaviour
Update should work

### Actual behaviour
Error and the upgrade fails

### Server configuration

**Operating system**:
Debian 9 Stretch 
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.2.3
**Nextcloud version:** 
13.0.0.14
**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_frommail: 0.1.0
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 0.4.4
  - twofactor_u2f: 1.5.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.2",
            "redval.sytes.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/192.168.1.2\/cloud",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "debug": true,
        "integrity.check.disabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "production",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/"
    }
}
```
</details>

### Client configuration
**Browser:**
Firefox 58
**Operating system:**
Debian 9 Stretch
#### Nextcloud log 
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"r8qZGUNvwLNXCIKfZzau","level":3,"time":"2018-03-07T11:25:39+00:00","remoteAddr":"193.51.24.13","user":"--","app":"PHP","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=WR33dMvsVepBjWj0UFsey%2FevMQbrUILRSZ24lXGi4S8%3D%3ACUyyQPq8J4EDuwyQOg1rn5mbdHWNCNqLefmBpkHKm34%3D","message":"Error: Class 'OC\\Updater' not found at \/var\/www\/cloud\/core\/ajax\/update.php#116","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
```
</details>

#### Return of occ upgrade 
<details>
<summary>occ upgrade</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
An unhandled exception has been thrown:
Error: Class 'OC\Updater' not found in /var/www/cloud/core/Command/Upgrade.php:104
Stack trace:
#0 /var/www/cloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/cloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/cloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/cloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/cloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/cloud/console.php(90): OC\Console\Application->run()
#6 /var/www/cloud/occ(11): require_once('/var/www/cloud/...')
#7 {main}
```
</details>
I cannot access the account so even if I could just ignore this update and continue to use the server normally that would be great.

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen Have you an idea?

**Comment by mr-bolle** [comment]
Hi,

i have the same behavor also with other Apps, and found the reason - the App is stored into several 'apps_paths'. I remove the folder from the App into the path ex. /var/www/html/apps/twofactor_totp. 
And update the App again.

/var/www/html/config/config.php
      'path' => '/var/www/html/apps',
      'path' => '/var/www/html/custom_apps',

**Comment by nickvergessen** [comment]
hu, not really. Class `OC\Updater` not found.

**Comment by MorrisJobke** [comment]
As we cannot reproduce this and it seems that there were no further occurrences of this I will close this. We can reopen if this happens again and there is a reliable way of reproducing this.
