### ISSUE TITLE
Internal Server Error on wrong password for LDAP user

### ISSUE THREAD

**Issue by c-po** [nextcloud/server#8734]
### Steps to reproduce
1. Ensure your NextCloud instance is connected to an LDAP/AD server for user storage
2. Login w/ your LDAP credentials
3. Logout
4. Login with LDAP username and a wrong password

### Expected behaviour
Wrong password dialog box.

### Actual behaviour
Internal Server Error

![image](https://user-images.githubusercontent.com/25299219/37167782-31e21a26-2303-11e8-8d43-78e05326b390.png)

### Server configuration

**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

**Web server:**
Apache/2.4.25-3+deb9u3

**Database:**
MySQL/5.8+1.0.2

**PHP version:**
7.0.27-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Nextcloud 12.x

**Where did you install Nextcloud from:**
Release version

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 1.0.3
  - checksum: 0.3.5
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_u2f: 1.5.1
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_videoplayer
  - firstrunwizard
  - sharebymail
  - survey_client
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'datadirectory' => '/var/www/html/nextcloud/data',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '13.0.0.14',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
   'memcache.local' => '\\OC\\Memcache\\APCu',
  'lost_password_link' => 'disabled',
  'allow_user_to_change_display_name' => false,
  'updater.release.channel' => 'stable',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                                |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                                                                    |
| homeFolderNamingRule          |                                                                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                  |
| ldapAgentName                 | CN=SA-Nextcloud,CN=Serviceaccounts,CN=MAIN,DC=foo,DC=net                                                                                                                         |
| ldapAgentPassword             | ***                                                                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                                                                    |
| ldapBackupHost                | dc02.foo.net                                                                                                                                                                     |
| ldapBackupPort                | 636                                                                                                                                                                                |
| ldapBase                      | CN=MAIN,DC=foo,DC=net                                                                                                                                                            |
| ldapBaseGroups                | CN=Groups,CN=MAIN,DC=foo,DC=net                                                                                                                                                  |
| ldapBaseUsers                 | CN=Users,CN=MAIN,DC=foo,DC=net                                                                                                                                                   |
| ldapCacheTTL                  | 600                                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                                  |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                    |
| ldapEmailAttribute            | cpo                                                                                                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                                    |
| ldapExpertUsernameAttr        |                                                                                                                                                                                    |
| ldapGidNumber                 | gidNumber                                                                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                                                                                 |
| ldapGroupFilter               |                                                                                                                                                                                    |
| ldapGroupFilterGroups         |                                                                                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                                       |
| ldapHost                      | ldaps://dc01.foo.net                                                                                                                                                             |
| ldapIgnoreNamingRules         |                                                                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=A_NEXTCLOUD,CN=Groups,CN=MAIN,DC=foo,DC=net)(primaryGroupID=1620))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                                    |
| ldapLoginFilterEmail          | 1                                                                                                                                                                                  |
| ldapLoginFilterMode           | 1                                                                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                                                                |
| ldapPort                      | 636                                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                                  |
| ldapUserDisplayName           | displayname                                                                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=A_NEXTCLOUD,CN=Groups,CN=MAIN,DC=foo,DC=net)(primaryGroupID=1620))))                                                                     |
| ldapUserFilterGroups          | A_NEXTCLOUD                                                                                                                                                                        |
| ldapUserFilterMode            | 0                                                                                                                                                                                  |
| ldapUserFilterObjectclass     | user                                                                                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                                                                  |
| turnOnPasswordChange          | 0                                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                  |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
172.16.36.10 - - [08/Mar/2018:18:59:37 +0100] "POST /login HTTP/1.1" 500 4881
172.16.36.10 - - [08/Mar/2018:18:59:37 +0100] "GET /core/img/favicon.ico HTTP/1.1" 200 3262
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
root@lnx03:/var/www/html/nextcloud/data# cat nextcloud.log | grep LWpgw8fMoKQIv6EssDBg
{"reqId":"LWpgw8fMoKQIv6EssDBg","level":2,"time":"2018-03-08T17:59:37+00:00","remoteAddr":"172.16.36.10","user":"--","app":"user_ldap","method":"POST","url":"\/index.php","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"LWpgw8fMoKQIv6EssDBg","level":3,"time":"2018-03-08T17:59:37+00:00","remoteAddr":"172.16.36.10","user":"--","app":"index","method":"POST","url":"\/index.php","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(371): OCA\\\\User_LDAP\\\\LDAP->processLDAPError(Resource id #22)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(295): OCA\\\\User_LDAP\\\\LDAP->postFunctionCall()\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(46): OCA\\\\User_LDAP\\\\LDAP->invokeLDAPMethod(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(621): OCA\\\\User_LDAP\\\\LDAP->bind(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(563): OCA\\\\User_LDAP\\\\Connection->bind(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(178): OCA\\\\User_LDAP\\\\Connection->establishConnection()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(186): OCA\\\\User_LDAP\\\\Connection->init()\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(615): OCA\\\\User_LDAP\\\\Connection->getConnectionResource()\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(1508): OCA\\\\User_LDAP\\\\Connection->bind(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(201): OCA\\\\User_LDAP\\\\Access->areCredentialsValid(*** sensitive parameters replaced ***)\\n#10 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(108): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(150): OCA\\\\User_LDAP\\\\User_Proxy->callOnLastSeenOn('cpo', 'checkPassword', Array, false)\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(196): OCA\\\\User_LDAP\\\\Proxy->handleRequest('cpo', 'checkPassword', Array)\\n#14 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(204): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/Controller\\\/LoginController.php(254): OC\\\\User\\\\Manager->checkPasswordNoLogging(*** sensitive parameters replaced ***)\\n#16 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#19 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#20 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#21 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#22 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#23 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/login')\\n#24 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php\",\"Line\":333}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
```
</details>

</details>

**Comment by blizzz** [comment]
Is it reproducible? The error message suggests that the LDAP server appears offline.

**Comment by c-po** [comment]
@blizzz it is completely reproducible. This is the error I get every time I enter a wrong password.

**Comment by retide** [comment]
I am running a similar environment (nextcloud 13, ubunut 16.04, apache, external AD/LDAP for user authentification) and cannot reproduce the error. This is probably not the cause of your problem, but your ldapLoginFilter seems awkwardly cluttered:

> (&
>     (&
>         (|(objectclass=person))
>         (|
>             (|
>                 (memberof=CN=A_NEXTCLOUD,CN=Groups,CN=MAIN,DC=foo,DC=net)
>                 (primaryGroupID=1620)
>             )
>         )
>     )
>     (|
>         (samaccountname=%uid)
>         (|
>             (mailPrimaryAddress=%uid)
>             (mail=%uid)
>         )
>     )
> )

can be simplified to

> (&
> (
>     (objectclass=person)
>     (|
>         (memberof=CN=A_NEXTCLOUD,CN=Groups,CN=MAIN,DC=foo,DC=net)
>         (primaryGroupID=1620)
>     )
>     (|
>         (samaccountname=%uid)
>         (mailPrimaryAddress=%uid)
>         (mail=%uid)
>     )
> )
> )

**Comment by c-po** [comment]
@retide the "cluttered" cluttered LDAP configuration was generated using the LDAP / AD integration dialog, thus I assume it's OK. I aggree it could look easier.

![image](https://user-images.githubusercontent.com/25299219/37406576-c702c202-2797-11e8-8270-677ba1079726.png)

![image](https://user-images.githubusercontent.com/25299219/37406617-dfa12fec-2797-11e8-88c9-fdc0a7a2513d.png)

I can confirm that when I remove the configured "Backup (Replica) Host" host, I see a proper error message

![image](https://user-images.githubusercontent.com/25299219/37406743-2bb0eb84-2798-11e8-979a-d1cf2a2b4a5a.png)

**Comment by c-po** [comment]
Looks like it was a configuration problem at all. I missed the `ldaps://` prefix for the backup host. After adding `ldaps://` I get the correct error message.
