### ISSUE TITLE
Opening /settings/admin results in a HTTP 500 error code

### ISSUE THREAD

**Issue by vanyasem** [nextcloud/server#8763]
### Steps to reproduce
1. Update a few apps to their latest version
2. Open Admin settings page

### Expected behaviour
Admin page opens successfully 

### Actual behaviour
Admin page gives a HTTP 500 error

### Server configuration

**Operating system**:
Ubuntu Server 16.04

**Web server:**
nginx/1.10.3

**Database:**
mysql Ver 15.1

**PHP version:**
7.0.25

**Nextcloud version:**
12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated Nextcloud from 12.0.3.3 3 months ago

**Where did you install Nextcloud from:**
Manual installation following the docs

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.8
  - comments: 1.2.0
  - contacts: 2.1.2
  - dav: 1.3.0
  - deck: 0.3.1
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_clipboard: 0.7.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.1
  - oauth2: 1.0.5
  - ocsms: 1.12.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - systemtags: 1.2.0
  - tasks: 0.9.6
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - workflowengine: 1.2.0
Disabled:
  - drawio
  - encryption
  - files_external
  - notes
  - notifications
  - quota_warning
  - richdocuments
  - survey_client
  - updatenotification
  - user_external
  - user_lda
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ochfpiaqesez",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mynameisivan.ru"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/nextcloud.mynameisivan.ru",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_domain": "mynameisivan.ru",
        "mail_from_address": "noreply",
        "mail_smtphost": "smtp.yandex.ru",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 58.0.2 (64-bit)

**Operating system:**
Arch GNU/Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
192.168.1.1 - - [10/Mar/2018:02:23:43 +0300] "GET /settings/admin HTTP/2.0" 500 6620 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"J6O4fMPRvBkRsqJ05jI8","level":3,"time":"2018-03-09T23:28:13+00:00","remoteAddr":"192.168.1.1","user":"vanyasem","app":"index","method":"GET","url":"\/settings\/admin\/logging","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/nextcloud\\\/apps\\\/drawio\\\/lib\\\/adminsettings.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/nextcl...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(94): ReflectionClass->__construct('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(352): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(138): OC\\\\Settings\\\\Manager->getAdminSettings('server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(72): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('logging')\\n#10 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('logging')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin...')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.4.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
ReferenceError: oc_appconfig is not defined merged-share-backend.js:24:4
TypeError: link is undefined merged-template-prepend.js:1349:1

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.mynameisivan.ru/core/vendor/core.js?v=0ec366bcca9c688a8cdc1d5f2674b60a-7
Source Map URL: purify.min.js.map
```
</details>

**Comment by vanyasem** [comment]
Fixed by enabling drawio extenstion. The question is: how to disable it (and remove it completely) without breaking Nextcloud?

**Comment by vanyasem** [comment]
Turns out I updated a disabled app which rendered my settings page inaccessible. Enabling and disabling drawio again fixed the issue for me. Closing
