### ISSUE TITLE
Unable to create new note

### ISSUE THREAD

**Issue by hshan1689** [nextcloud/server#8844]
### Steps to reproduce
1) Click New note
2) No note being created (after clicking, nothing happen on note page)
3) But the record in Activity state that note being created
![image](https://user-images.githubusercontent.com/37432250/37506823-9a0e3ca0-2926-11e8-82ec-18462d7da334.png)

### Expected behaviour
Note created/displayed successfully

### Actual behaviour
No note being created on note page but the record  in Activity state that note being created

**Comment by hshan1689** [comment]
Could not create object urn:oid:45112 for files/Notes/New note.txt: {"Exception":"Aws\\S3\\Exception\\S3MultipartUploadException","Message":"An exception occurred while completing a multipart upload: Error executing \"CompleteMultipartUpload\" on \"http:\/\/s3-sg.cloudian.1bytepro.com\/nc-1byte\/urn%3Aoid%3A45112?uploadId=MDA4YjE2NzUxNTIxNDMxNjk1NDY3\"; AWS HTTP error: Client error response [url] http:\/\/s3-sg.cloudian.1bytepro.com\/nc-1byte\/urn%3Aoid%3A45112?uploadId=MDA4YjE2NzUxNTIxNDMxNjk1NDY3 [status code] 400 [reason phrase] Bad Request MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - <?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>MalformedXML<\/Code><Message>The XML you provided was not well-formed or did not validate against our published schema<\/Message><RequestId>c02e60b2-ce6e-1259-8cf8-54ab3ad969a0<\/RequestId><HostId>C6Uzbrs-wbypi4nZS7s6Tt0o87LAJoRNBRJXy7jAyZ8<\/HostId><\/Error>","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(203): Aws\\Multipart\\AbstractUploadManager->Aws\\Multipart\\{closure}(*** sensitive parameters replaced ***)\n#1 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(2, Object(Aws\\S3\\Exception\\S3Exception), Array)\n#2 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}(*** sensitive parameters replaced ***)\n#3 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(234): GuzzleHttp\\Promise\\TaskQueue->run()\n#4 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#5 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#6 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#7 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#8 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#9 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Coroutine.php(65): GuzzleHttp\\Promise\\Promise->wait()\n#10 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(246): GuzzleHttp\\Promise\\Coroutine->GuzzleHttp\\Promise\\{closure}(*** sensitive parameters replaced ***)\n#11 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#12 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#13 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#14 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#15 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/Multipart\/AbstractUploadManager.php(83): GuzzleHttp\\Promise\\Promise->wait()\n#16 \/var\/www\/nextcloud\/lib\/private\/Files\/ObjectStore\/S3ObjectTrait.php(107): Aws\\Multipart\\AbstractUploadManager->upload()\n#17 \/var\/www\/nextcloud\/lib\/private\/Files\/ObjectStore\/S3ObjectTrait.php(83): OC\\Files\\ObjectStore\\S3->multiPartUpload('urn:oid:45112', Resource id #41)\n#18 \/var\/www\/nextcloud\/lib\/private\/Files\/ObjectStore\/ObjectStoreStorage.php(406): OC\\Files\\ObjectStore\\S3->writeObject('urn:oid:45112', Resource id #41)\n#19 \/var\/www\/nextcloud\/lib\/private\/Files\/ObjectStore\/ObjectStoreStorage.php(306): OC\\Files\\ObjectStore\\ObjectStoreStorage->writeBack('\/tmp\/oc_tmp_Mzf...', 'files\/Notes\/New...')\n#20 [internal function]: OC\\Files\\ObjectStore\\ObjectStoreStorage->OC\\Files\\ObjectStore\\{closure}(*** sensitive parameters replaced ***)\n#21 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#22 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#23 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php(203): fclose(Resource id #40)\n#24 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(255): OC\\Files\\Storage\\Common->file_put_contents('files\/Notes\/New...', '')\n#25 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php(277): OC\\Files\\Storage\\Wrapper\\Wrapper->file_put_contents('files\/Notes\/New...', '')\n#26 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Quota.php(116): OC\\Files\\Storage\\Wrapper\\Availability->file_put_contents('files\/Notes\/New...', '')\n#27 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(255): OC\\Files\\Storage\\Wrapper\\Quota->file_put_contents('files\/Notes\/New...', '')\n#28 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1146): OC\\Files\\Storage\\Wrapper\\Wrapper->file_put_contents('files\/Notes\/New...', '')\n#29 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(688): OC\\Files\\View->basicOperation('file_put_conten...', '\/Huang Shan\/fil...', Array, '')\n#30 \/var\/www\/nextcloud\/lib\/private\/Files\/Node\/File.php(64): OC\\Files\\View->file_put_contents('\/Huang Shan\/fil...', '')\n#31 \/var\/www\/nextcloud\/custom_apps\/notes\/service\/notesservice.php(168): OC\\Files\\Node\\File->putContent('')\n#32 \/var\/www\/nextcloud\/custom_apps\/notes\/controller\/notescontroller.php(88): OCA\\Notes\\Service\\NotesService->update(45112, '', 'Huang Shan')\n#33 [internal function]: OCA\\Notes\\Controller\\NotesController->create('')\n#34 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161): call_user_func_array(Array, Array)\n#35 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Notes\\Controller\\NotesController), 'create')\n#36 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Notes\\Controller\\NotesController), 'create')\n#37 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Notes\\\\Contr...', 'create', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#38 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#39 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#40 \/var\/www\/nextcloud\/lib\/base.php(998): OC\\Route\\Router->match('\/apps\/notes\/not...')\n#41 \/var\/www\/nextcloud\/index.php(37): OC::handleRequest()\n#42 {main}","File":"\/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/Multipart\/AbstractUploadManager.php","Line":136}

**Comment by hshan1689** [comment]
Could not create object urn:oid:45112 for files/Notes/New note.txt: {"Exception":"Aws\S3\Exception\S3MultipartUploadException","Message":"An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "http://s3-sg.cloudian.1bytepro.com/nc-1byte/urn%3Aoid%3A45112?uploadId=MDA4YjE2NzUxNTIxNDMxNjk1NDY3"; AWS HTTP error: Client error response [url] http://s3-sg.cloudian.1bytepro.com/nc-1byte/urn%3Aoid%3A45112?uploadId=MDA4YjE2NzUxNTIxNDMxNjk1NDY3 [status code] 400 [reason phrase] Bad Request MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - MalformedXML</Code>The XML you provided was not well-formed or did not validate against our published schema</Message>c02e60b2-ce6e-1259-8cf8-54ab3ad969a0</RequestId>C6Uzbrs-wbypi4nZS7s6Tt0o87LAJoRNBRJXy7jAyZ8</HostId></Error>","Code":0,"Trace":"#0 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(203): Aws\Multipart\AbstractUploadManager->Aws\Multipart\{closure}(*** sensitive parameters replaced )\n#1 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(2, Object(Aws\S3\Exception\S3Exception), Array)\n#2 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}( sensitive parameters replaced )\n#3 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(234): GuzzleHttp\Promise\TaskQueue->run()\n#4 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()\n#5 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()\n#6 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()\n#7 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()\n#8 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()\n#9 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait()\n#10 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}( sensitive parameters replaced )\n#11 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()\n#12 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()\n#13 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()\n#14 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()\n#15 /var/www/nextcloud/3rdparty/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php(83): GuzzleHttp\Promise\Promise->wait()\n#16 /var/www/nextcloud/lib/private/Files/ObjectStore/S3ObjectTrait.php(107): Aws\Multipart\AbstractUploadManager->upload()\n#17 /var/www/nextcloud/lib/private/Files/ObjectStore/S3ObjectTrait.php(83): OC\Files\ObjectStore\S3->multiPartUpload('urn:oid:45112', Resource id #41)\n#18 /var/www/nextcloud/lib/private/Files/ObjectStore/ObjectStoreStorage.php(406): OC\Files\ObjectStore\S3->writeObject('urn:oid:45112', Resource id #41)\n#19 /var/www/nextcloud/lib/private/Files/ObjectStore/ObjectStoreStorage.php(306): OC\Files\ObjectStore\ObjectStoreStorage->writeBack('/tmp/oc_tmp_Mzf...', 'files/Notes/New...')\n#20 [internal function]: OC\Files\ObjectStore\ObjectStoreStorage->OC\Files\ObjectStore\{closure}( sensitive parameters replaced ***)\n#21 /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#22 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()\n#23 /var/www/nextcloud/lib/private/Files/Storage/Common.php(203): fclose(Resource id #40)\n#24 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(255): OC\Files\Storage\Common->file_put_contents('files/Notes/New...', '')\n#25 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php(277): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('files/Notes/New...', '')\n#26 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php(116): OC\Files\Storage\Wrapper\Availability->file_put_contents('files/Notes/New...', '')\n#27 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(255): OC\Files\Storage\Wrapper\Quota->file_put_contents('files/Notes/New...', '')\n#28 /var/www/nextcloud/lib/private/Files/View.php(1146): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('files/Notes/New...', '')\n#29 /var/www/nextcloud/lib/private/Files/View.php(688): OC\Files\View->basicOperation('file_put_conten...', '/hshan/fil...', Array, '')\n#30 /var/www/nextcloud/lib/private/Files/Node/File.php(64): OC\Files\View->file_put_contents('/hshan/fil...', '')\n#31 /var/www/nextcloud/custom_apps/notes/service/notesservice.php(168): OC\Files\Node\File->putContent('')\n#32 /var/www/nextcloud/custom_apps/notes/controller/notescontroller.php(88): OCA\Notes\Service\NotesService->update(45112, '', 'hshan')\n#33 [internal function]: OCA\Notes\Controller\NotesController->create('')\n#34 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)\n#35 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Notes\Controller\NotesController), 'create')\n#36 /var/www/nextcloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Notes\Controller\NotesController), 'create')\n#37 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Notes\\Contr...', 'create', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#38 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\n#39 /var/www/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\n#40 /var/www/nextcloud/lib/base.php(998): OC\Route\Router->match('/apps/notes/not...')\n#41 /var/www/nextcloud/index.php(37): OC::handleRequest()\n#42 {main}","File":"/var/www/nextcloud/3rdparty/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php","Line":136}

**Comment by hshan1689** [comment]
solved.
