### ISSUE TITLE
Using the Android lib for Nextcloud produces 500 HTTP status code

### ISSUE THREAD

**Issue by dartmann** [nextcloud/server#8982]
### Steps to reproduce
1. Use Android library to upload an image taken via the camera of the Android device (I use the same code as in the upload example of the [documentation](https://docs.nextcloud.com/server/12/developer_manual/android_library/examples.html)).
2. Look at the Nextcloud log.
3. See webdav error: "InvalidArgumentException: X-OC-MTime header must be an integer (unix timestamp)."
4. The file gets uploaded any way.

### Expected behaviour
The upload should produce a 200 response code.

### Actual behaviour
The upload produces a 500 response code.

### Server configuration

**Operating system**: Ubuntu 16.04.4 LTS

**Web server:** Apache/2.4.18

**Database:** Ver 15.1 Distrib 10.0.34-MariaDB

**PHP version:** 7.0.28

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** downloaded from official website and web installer from bundle.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "keller2",
            "192.168.178.64",
            "keller2.8pzkpdxsetbyyr3f.myfritz.net",
            "keller2.fritz.box"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/keller\/owncloud",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "integrity.check.disabled": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 59.0.1

**Operating system:** MacOS 10.13.3

#### Web server error log
<details>
<summary>Web server error log</summary>

```
87.143.197.214 - david [26/Mar/2018:12:20:48 +0200] "PUT /nextcloud/remote.php/webdav/hochzeit_bilder_upload/e6a04f6e-3fed-4b66-b43a-f31f87efdd77_1522059646804_-2112166988.jpg HTTP/1.1" 500 4594 "-" "Jakarta Commons-HttpClient/3.1"
2003:75:d13:af00:c89e:810:1fef:6020 - david [26/Mar/2018:12:20:54 +0200] "PROPFIND /nextcloud/remote.php/dav/files/david/ HTTP/1.1" 207 4796 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)"
2003:75:d13:af00:c89e:810:1fef:6020 - david [26/Mar/2018:12:20:54 +0200] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 838 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)"
2003:75:d13:af00:c89e:810:1fef:6020 - david [26/Mar/2018:12:20:56 +0200] "PROPFIND /nextcloud/remote.php/dav/files/david/ HTTP/1.1" 207 11407 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)"
2003:75:d13:af00:c89e:810:1fef:6020 - david [26/Mar/2018:12:20:56 +0200] "PROPFIND /nextcloud/remote.php/dav/files/david/hochzeit_bilder_upload HTTP/1.1" 207 3185 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)"
2003:75:d13:af00:c89e:810:1fef:6020 - david [26/Mar/2018:12:20:56 +0200] "GET /nextcloud/remote.php/dav/files/david/hochzeit_bilder_upload/e6a04f6e-3fed-4b66-b43a-f31f87efdd77_1522059646804_-2112166988.jpg HTTP/1.1" 200 389733 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"eQiAe53QMeojagXUJe2A","level":4,"time":"2018-03-26T10:20:48+00:00","remoteAddr":"87.143.197.214","user":"david","app":"webdav","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/hochzeit_bilder_upload\/e6a04f6e-3fed-4b66-b43a-f31f87efdd77_1522059646804_-2112166988.jpg","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"X-OC-MTime header must be an integer (unix timestamp).\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(234): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Node->sanitizeMtime('Mon Mar 26 12:2...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #8)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('e6a04f6e-3fed-4...', Resource id #8)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('hochzeit_bilder...', Resource id #8, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Node.php\",\"Line\":369}","userAgent":"Jakarta Commons-HttpClient\/3.1","version":"13.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Not relevant.
```
</details>

**Comment by dartmann** [comment]
Ok, got it. The send timestamp in the upload request did not have a valid format. With a simple
```
new Date().getTime()
```
The response status is 200.

**Comment by rullzer** [comment]
Glad it is resolved.
