### ISSUE TITLE
Move via Federated-Cloud error: renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: false)

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#9021]
### Steps to reproduce
1. Add share from user@nc1.example.com to user@nc2.example.com 
2. Accept the Federated-Share on nc2.example.com
3. Move from nc2.example.com via the botten ( `https://nc2.example.com/apps/files/?dir=/…&fileid=…` )

### Expected behaviour
The file is moved to the folder of nc1.example.com.

### Actual behaviour
It issued the message "... could not be moved".

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Apache2

**Database:**
Mariadb

**PHP version:**
PHP 7.0.27-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
nc1 it a fresh installation. nc2 exists already Owncloud 6 or something

**Where did you install Nextcloud from:**
In both cases via tar file download.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - checksum: 0.3.5
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - deck: 0.3.1
  - encryption: 2.0.0
  - end_to_end_encryption: 1.0.5
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.2.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_frommail: 0.1.0
  - files_linkeditor: 1.0.4
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.3.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - metadata: 0.6.0
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - polls: 0.8.1
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - w2g2: 1.1.0
  - workflowengine: 1.3.0
Disabled:
  - files_inotify
  - initialcheck
  - orcid
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.coinpg.net"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "nc.coinpg.net",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.coinpg.net",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "updater.release.channel": "production",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** Federated-Cloud

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 59.0.1 (64-Bit)

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
….….….… - user [28/Mar/2018:19:52:55 +0200] "PROPFIND /remote.php/dav/files/user/ HTTP/1.0" 207 1412 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
….….….… - - [28/Mar/2018:19:52:56 +0200] "PROPFIND /public.php/webdav/ HTTP/1.0" 401 1750 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
….….….… - LgP8NrEbar6Qna6 [28/Mar/2018:19:52:56 +0200] "PROPFIND /public.php/webdav/ HTTP/1.0" 207 2180 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
….….….… - - [28/Mar/2018:19:52:38 +0200] "GET /apps/logreader/poll?lastReqId=WrvWQQoKCnAAAHk2xacAAAAN HTTP/1.0" 200 842 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
….….….… - LgP8NrEbar6Qna6 [28/Mar/2018:19:52:58 +0200] "PROPFIND /public.php/webdav/Sortieren HTTP/1.0" 207 2188 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
….….….… - - [28/Mar/2018:19:52:59 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 1308 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
….….….… - - [28/Mar/2018:19:52:59 +0200] "POST /index.php/apps/files_sharing/shareinfo?t=LgP8NrEbar6Qna6 HTTP/1.0" 200 27093 "-" "Nextcloud Server Crawler"
….….….… - LgP8NrEbar6Qna6 [28/Mar/2018:19:53:05 +0200] "PROPFIND /public.php/webdav/Sortieren/DCP%20-%20Sitzung%202018-01-24.pdf HTTP/1.0" 404 1709 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
….….….… - user [28/Mar/2018:19:53:10 +0200] "PROPFIND /remote.php/dav/files/user/ HTTP/1.0" 207 1411 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
….….….… - - [28/Mar/2018:19:52:59 +0200] "GET /apps/logreader/poll?lastReqId=WrvWQQoKCnAAAHk2xacAAAAN HTTP/1.0" 200 842 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
….….….… - LgP8NrEbar6Qna6 [28/Mar/2018:19:53:07 +0200] "PUT /public.php/webdav/Sortieren/DCP%20-%20Sitzung%202018-01-24.pdf HTTP/1.0" 500 1637 "-" "Nextcloud Server Crawler"
….….….… - - [28/Mar/2018:19:53:20 +0200] "GET /apps/logreader/poll?lastReqId=WrvWQQoKCnAAAHk2xacAAAAN HTTP/1.0" 200 3465 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WrvUYwoKCnAAAAWmYd8AAAAQ","level":3,"time":"2018-03-28T17:44:17+00:00","remoteAddr":"….….….…","user":"--","app":"webdav","method":"PUT","url":"\/public.php\/webdav\/Example\/Example.file","message":"renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: false)","userAgent":"Nextcloud Server Crawler","version":"13.0.1.1"}
{"reqId":"WrvUYwoKCnAAAAWmYd8AAAAQ","level":4,"time":"2018-03-28T17:44:17+00:00","remoteAddr":"….….….…","user":"--","app":"webdav","method":"PUT","url":"\/public.php\/webdav\/Example\/example.file","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #142)\\n#1 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('DCP - Sitzung 2...', Resource id #142)\\n#2 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Example\\\/Examp...', Resource id #142, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6
\\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(107): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/public.php(79): require_once('\\\/var\\\/www\\\/nc1\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nc1\\\/nextcloud-13.0.1\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":213}","userAgent":"Nextcloud Server Crawler","version":"13.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
-
```
</details>

**Comment by Orbital-Bit** [comment]
error seems identical to the issue i posted, [8978](https://github.com/nextcloud/server/issues/8978).
though the external storage is different, the mechanics on the backend are the same WebDAV.
maybe the issues are more related.

**Comment by Orbital-Bit** [comment]
just to gather some more points of data for comparison.
do you know what the underlying storage is on the federated server?
can you manually (via web interface) rename a file inside a federated share?

**Comment by YoSiJo** [comment]
@Orbital-Bit Both servers belong to me.
Both have a mysql backend and btrfs storage for files.

I can not create or rename a file in the share.

**Comment by YoSiJo** [comment]
Good day,
I am sorry, but due to the takeover of github by Microsoft I will delete my account here.
I hope that the problem will be solved.

**Comment by TrapoSAMA** [comment]
Hi!

I have this error with external storage like DFS (cifs/smb), can create and delete folder but dont upload or rename files.

I using version 13.0.3.2

exist fix  for this error ?

**Comment by MorrisJobke** [comment]
Let's continue this in #8978
