### ISSUE TITLE
Unable to log in to Nextcloud in Chrome

### ISSUE THREAD

**Issue by dm-m** [nextcloud/server#9057]
### Steps to reproduce
1. Try logging in to Nextcloud instance in Google Chrome
2. Nothing happens

### Expected behaviour
A user should be able to log in Nextcloud instance in Google Chrome.

### Actual behaviour
I am using KeePassHttp-Connector for pasting login details on different websites. So, I click on the login fields, they got pasted with the username and password and after clicking "Log in" nothing happens.

Nothing was changed in the server backend these days. Also, I managed to log in Firefox.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** nginx/1.13.6

**Database:** 10.0.34-MariaDB-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12

**Where did you install Nextcloud from:** CLI

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - audioplayer: 2.2.5
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - deck: 0.3.1
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.4
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - weather: 1.5.1
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "singleuser": false,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable"
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Chrome extensions:
- Cookie AutoDelete
- Cookiebro
- Decentraleyes
- Follow Feed | Feedly
- Google Docs Offline
- HTTPS Everywhere
- KeePassHttp-Connector
- LastPass
- No Coin
- PhishProtect Beta
- Privacy Badger
- Quick Note
- Restlet Client - REST API Testing
- uBlock Origin

**Operating system:** Windows 10 Home (10.0.16299 Build 16299)

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing related in the webserver log.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

The latest record from the log:

```
{"reqId":"AOnWzIMsgKQNZQnG7vz2","level":3,"time":"2018-04-03T02:54:10+00:00","remoteAddr":"23.99.122.165","user":"--","app":"index","method":"POST","url":"\/login","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Username must be string\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/login')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/core\\\/Controller\\\/LoginController.php\",\"Line\":237}","userAgent":"--","version":"13.0.1.1"}
```
This IP is not mine.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Console log:
```
Uncaught SyntaxError: Invalid regular expression: missing / core.js?v=c7853754-28:1397
previewplugin.js?v=c7853754-28:128 Uncaught ReferenceError: OCA is not defined
    at previewplugin.js?v=c7853754-28:128
(anonymous) @ previewplugin.js?v=c7853754-28:128
viewer.js?v=c7853754-28:15 Uncaught ReferenceError: OC is not defined
    at viewer.js?v=c7853754-28:15
(anonymous) @ viewer.js?v=c7853754-28:15
jquery-ui-fixes.js?v=c7853754-28:5 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui-fixes.js?v=c7853754-28:5
(anonymous) @ jquery-ui-fixes.js?v=c7853754-28:5
fileinfo.js?v=c7853754-28:142 Uncaught ReferenceError: OC is not defined
    at fileinfo.js?v=c7853754-28:142
(anonymous) @ fileinfo.js?v=c7853754-28:142
client.js?v=c7853754-28:931 Uncaught ReferenceError: OC is not defined
    at client.js?v=c7853754-28:931
(anonymous) @ client.js?v=c7853754-28:931
contactsmenu.js?v=c7853754-28:538 Uncaught ReferenceError: OC is not defined
    at contactsmenu.js?v=c7853754-28:538
(anonymous) @ contactsmenu.js?v=c7853754-28:538
merged-login.js?v=c7853754-28:2 Uncaught ReferenceError: $ is not defined
    at merged-login.js?v=c7853754-28:2
(anonymous) @ merged-login.js?v=c7853754-28:2
theming?v=28:2 Uncaught ReferenceError: OCA is not defined
    at theming?v=28:2
    at theming?v=28:10
```

JS network log:
```
core.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
merged-template-prepend.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
search.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
merged-share-backend.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
plugin.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
apporder.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
previewplugin.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
viewer.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
jquery-ui-fixes.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
fileinfo.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
client.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
contactsmenu.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
jstz.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
merged-login.js?v=c7853754-28 | 200 | script | login | (from memory cache) | 0 ms
theming?v=28 | 200 | script | login | (from memory cache) | 0 ms
```
</details>

**Comment by dm-m** [comment]
I managed to log in by purging everything in Chrome: plugin data, LSO, local storage, cookies and history. Closing the issue.
