### ISSUE TITLE
Shared folder its showing "Storage is temporarily not available"

### ISSUE THREAD

**Issue by webtyphoon** [nextcloud/server#9125]
### Steps to reproduce
1. Updated from NC13.0.0 - 13.0.1
2. Click a shared folder its showing "Storage is temporarily not available"

### Expected behaviour
Click a shared folder should open up.

### Actual behaviour
All shared folders are redirecting to the root by clicking  them. Small popup is showing "Storage is temporarily not available". I haven't add an external storage to the system.

When I try to open up a new share the loading cycle will appear and don't stop.

### Server configuration

**Operating system**:
Linux v1hgb 4.13.13-6-pve #1 SMP PVE 4.13.13-41 (Wed, 21 Feb 2018 10:07:54 +0100) x86_64 GNU/Linux

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 20 2017 04:37:43

**Database:**
mySQL 5.7.8

**PHP version:**
7.2.3 (also tested on 7.0.26

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
13.0.0

**Where did you install Nextcloud from:**
a view versions below - migration from owncloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - audioplayer: 2.2.5
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.3.0
  - ownbackup: 17.5.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - firstrunwizard
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "terrawaycloud.cplogin.de",
            "hgbcloud.cplogin.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/domainname.de",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "debug": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "signed": "true",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "admin_notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "1.1.2",
            "ocsid": "173921",
            "signed": "true",
            "types": ""
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "2.2.5",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.11.0",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.1",
            "signed": "true",
            "types": ""
        },
        "calendarplus": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "ocsid": "170560",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "no",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "backend_ldap": "false",
            "enabled": "yes",
            "installed_version": "2.1.3",
            "signed": "true",
            "types": ""
        },
        "core": {
            "OC_Channel": "daily",
            "backgroundjobs_mode": "webcron",
            "global_cache_gc_lastrun": "1439134454",
            "incoming_server2server_share_enabled": "no",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1415178686.5768",
            "lastcron": "1474569906",
            "lastupdateResult": "[]",
            "lastupdatedat": "1523280983",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "no",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_calendarplus": "calendarplus\/share.php",
            "public_calendarplusevent": "calendarplus\/shareevent.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendarplus": "calendarplus\/appinfo\/remote.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "85bc6b82ce5069e332ef088f55a65a5f",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_resharing": "yes",
            "shareapi_allow_share_dialog_user_enumeration": "no",
            "shareapi_default_expire_date": "no",
            "shareapi_enabled": "yes",
            "shareapi_enforce_links_password": "no",
            "shareapi_exclude_groups": "no",
            "shareapi_only_share_with_group_members": "yes",
            "umgmt_send_email": "false",
            "umgmt_show_backend": "false",
            "umgmt_show_email": "false",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "false",
            "updater.secret.created": "1496913502",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.4.6",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "no",
            "installed_version": "0.7.1",
            "types": ""
        },
        "disablerememberlogin": {
            "enabled": "no",
            "installed_version": "0.3",
            "ocsid": "162551",
            "types": ""
        },
        "documents": {
            "converter": "off",
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": "",
            "unstable": "false"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "3.0.2",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "25 GB",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_path": "\/usr\/bin\/clamscan",
            "enabled": "no",
            "installed_version": "0.10.0.0",
            "ocsid": "157439",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "signed": "true",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.5.0",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "signed": "true",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "signed": "true",
            "types": ""
        },
        "imprint": {
            "content": "Imprint and Privacy Policy is comming soon....",
            "enabled": "no",
            "installed_version": "0.2.5",
            "position-guest": "footer-right",
            "position-login": "footer-right",
            "position-user": "header-right",
            "standalone": "false",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "market": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "ojsxc": {
            "apiSecret": "YLhK5+iU2CtsEofSKfGEUEJ",
            "boshUrl": "",
            "chromeExtension": "",
            "enabled": "no",
            "externalServices": "",
            "firefoxExtension": "",
            "iceCredential": "",
            "iceSecret": "",
            "iceTtl": "",
            "iceUrl": "",
            "iceUsername": "",
            "installed_version": "3.2.1",
            "serverType": "internal",
            "timeLimitedToken": "false",
            "types": "prelogin",
            "xmppDomain": "",
            "xmppOverwrite": "false",
            "xmppPreferMail": "false",
            "xmppResource": "",
            "xmppStartMinimized": "false"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerSecret": "",
            "DocumentServerUrl": "https:\/\/domainname.de\/docing\/",
            "StorageUrl": "",
            "defFormats": "{\"docx\":\"true\",\"xlsx\":\"true\",\"pptx\":\"true\",\"ppsx\":\"true\",\"txt\":\"true\"}",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "ocsid": "174798",
            "sameTab": "false",
            "skey": "1496930121876",
            "types": "filesystem"
        },
        "ownbackup": {
            "enabled": "yes",
            "installed_version": "17.5.0",
            "ocsid": "170674",
            "signed": "true",
            "types": ""
        },
        "ownnote": {
            "disableAnnouncement": null,
            "enabled": "no",
            "installed_version": "1.08",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "quicknotes": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "ocsid": "174716",
            "types": ""
        },
        "quota_warning": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.12.32",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "2.0.1",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.6",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "17",
            "color": "#159AB9",
            "enabled": "yes",
            "installed_version": "1.4.1",
            "name": "HGB Cloud",
            "slogan": "ein sicherer Ort f\u00fcr all Ihre Daten",
            "types": "logging",
            "url": "https:\/\/hgbcloud.cplogin.de"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "notify_groups": "[]",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.4",
            "types": "authentication,prelogin"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "153220": {
            "enabled": "no"
        },
        "170678": {
            "enabled": "no"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
firefox latest, chrome latest, safari latest

**Operating system:**
Mac OS 10.13.4

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

fatal | webdav  | Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available/var/www/.../htdocs/next18/3rdparty/sabre/dav/lib/DAV/Server.php - line 967:  OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('Feines Mahl')/var/www/.../htdocs/next18/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666:  Sabre\DAV\Server->getPropertiesIteratorForPath('Feines Mahl', Array, 1)/var/www/.../htdocs/next18/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 355:  Sabre\DAV\Server->generateMultiStatus(Object(Generator), false)[internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/.../htdocs/next18/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/.../htdocs/next18/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method PROPFIND', Array)/var/www/.../htdocs/next18/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/.../htdocs/next18/apps/dav/appinfo/v1/webdav.php - line 80:  Sabre\DAV\Server->exec()/var/www/.../htdocs/next18/remote.php - line 164:  require_once('/var/www/...'){main}

{"reqId":"...","level":4,"time":"2018-04-09T13:45:17+00:00","remoteAddr":"...","user":"...","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Feines%20Mahl","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Storage is temporarily not available\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(967): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Feines Mahl')\\n#1 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('Feines Mahl', Array, 1)\\n#2 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/remote.php(164): require_once('\\\/var\\\/www\\\/....')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/...\\\/htdocs\\\/next18\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

?
```
</details>

**Comment by tomtomas99911** [comment]
Same problem here

**Comment by 4001982248998** [comment]
maybe #9298 is related?

**Comment by 4001982248998** [comment]
to clarify: the storage is *not* external, so it is very likely an internal error.

**Comment by cyberb** [comment]
Can a user access share if the author of the share is logged in to Nextcoud at the same time?

**Comment by 4001982248998** [comment]
meanwhile I could find out that the share's author account has since been deleted.

It was shared with another user, who has shared a folder further with other users.

So the share's author has been deleted, but the share remained, but is in sort of a zombie state. You can see it, but neither use nor manipulate it. It is also causing errors in the desktop sync client.

**Comment by slankes** [comment]
I am seeing the issue as well under the same circumstances that @4001982248998 has.
I just updated to 13.0.4 (from 13.0.2) and the issue is still there.

**Comment by mariuspana** [comment]
I am seeing this as well with 13.0.4 due to a weird LDAP sync issue.
Our ldap was offline for a few hours, came back but in nextcloud our groups were empty and user mappings seem to have changed. Now we have dozens of shares in this zombie state.

**Comment by mikolodz** [comment]
Have similar problem but it came up in other circumstances on **13.0.7**. I didn't upgrade the nextcloud version - I just created a full copy of the nextcloud (snap) and moved it to the other machine. Everything seems to be working fine except **group folder sharing**. After clicking on a directory, I'm getting same error "Storage is temporarily not available". In addition, just as @Raqbit wrote, I cannot delete those broken folders. The problem is serious because it makes NextCloud unreliable - if I can't clone the system so it would work properly, I'm only asking for trouble.

**Comment by skjnldsv** [comment]
Hi everyone!
Is this still happening for any of you?

**Comment by cyberb** [comment]
Not for me, I think ldap group was not correctly confogured.

**Comment by Raqbit** [comment]
I am still having the same exact issue

**Comment by skjnldsv** [comment]
@cyberb good news :)

@Raqbit Could you share your oc_share_external table with me?
You can send it at skjnldsv@protonmail.com ([Commit sign proof](https://github.com/nextcloud/server/commit/a3447ed49a7cfea3eb59db5310535f12ac8aaa1e))

**Comment by NathanRussellUK** [comment]
> @cyberb good news :)
> 
> @Raqbit Could you share your oc_share_external table with me?
> You can send it at [skjnldsv@protonmail.com](mailto:skjnldsv@protonmail.com) ([Commit sign proof](https://github.com/nextcloud/server/commit/a3447ed49a7cfea3eb59db5310535f12ac8aaa1e))

Did you ever got that info you needed? I think I'm still experiencing this issue!

**Comment by choffm** [comment]
Experiencing the same issue with two nextcloud instances, both running 19.0

**Comment by vwbusguy** [comment]
I'm seeing this, too.  In my case, it appears to have caused the problem here: https://github.com/nextcloud/maps/issues/193

**Comment by vwbusguy** [comment]
I was able to fix it by deleting the offending row in oc_mounts and oc_share_external.

**Comment by mhellmeier** [comment]
Same problem here with Nextcloud 20.

**Comment by LaurentiuCTN** [comment]
The issue still persists even on nextcloud 21.0.3 only with shared folders with a huge number of files/folders
Ubuntu 20 LTS
Apache, PHP 8
PostgreSQL 13

I tried many installations (also with PHP 7, or MariaDB) but the problem still persists.

There really is no solution to this issue that persist for so long?

**Comment by mhellmeier** [comment]
> @Raqbit Could you share your oc_share_external table with me? You can send it at [skjnldsv@protonmail.com](mailto:skjnldsv@protonmail.com) ([Commit sign proof](https://github.com/nextcloud/server/commit/a3447ed49a7cfea3eb59db5310535f12ac8aaa1e))

I just shared some detailed information with you, @Raqbit . Hope that helps!

Since this issue was closed by the Nextcloud bot although the problem still exists, I created a new issue with detailed information for Nextlocud 22.X : #29515

**Comment by mhellmeier** [comment]
> @Raqbit Could you share your oc_share_external table with me? You can send it at [skjnldsv@protonmail.com](mailto:skjnldsv@protonmail.com) ([Commit sign proof](https://github.com/nextcloud/server/commit/a3447ed49a7cfea3eb59db5310535f12ac8aaa1e))

I just shared some detailed information with you, @skjnldsv. Hope that helps!

Since this issue was closed by the Nextcloud bot although the problem still exists, I created a new issue with detailed information for Nextlocud 22.X : #29515

**Comment by frocelu** [comment]
It seems like the app "file sharing" caused this happened,too.
I also have this problem in 21.0.0.2. I could not open the setting page and get  "Storage is temporarily not available" message until I disable the  "file sharing".

**Comment by mhellmeier** [comment]
Great progress on this issue, @frocelu !

I just tested it in my concrete case. If the file-sharing plugin is activated, I can see the shared (problematic) folder but if I try to access it I get the message "Storage is temporarily not available". After disabling the plugin, the (problematic) folder disappears completely.
