### ISSUE TITLE
Files above 1GB not properly uploading with External Storage

### ISSUE THREAD

**Issue by Apperator** [nextcloud/server#9146]
### Steps to reproduce
1. Upload file >1GB to external storage. (Either browser or desktop client)
2. Receive an error

### Expected behaviour
The file should be properly uploaded and at the right size.
For example I uploaded a 1.12GB file.

### Actual behaviour
File is not properly uploaded.
Error while copying file to target location (copied bytes: 1228800, expected filesize: 10485760 )

## Server configuration detail

**Operating system:** Linux 4.15.14-300.fc27.x86_64 #1 SMP Thu Mar 29 16:13:44 UTC 2018 x86_64

**Webserver:** Apache/2.4.33 (Fedora) OpenSSL/1.1.0h-fips (fpm-fcgi)

**Database:** mysql 10.2.14

**PHP version:** 7.1.16
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, igbinary, smbclient, zip, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.3.2
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "45.33.42.244",
        "nc3.gudako.info",
        "semiramis.gudako.info"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/45.33.42.244\/nextcloud",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
S3 Wasabi Sys

**Are you using encryption:** no

</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Server log</summary>

```
[Wed Apr 11 02:01:18.614929 2018] [mpm_event:notice] [pid 629:tid 139947609993216] AH00492: caught SIGWINCH, shutting down gracefully
[Wed Apr 11 02:01:18.732528 2018] [proxy_fcgi:error] [pid 1214:tid 139946878826240] [client 67.169.103.233:61468] AH01067: Failed to read FastCGI header
[Wed Apr 11 02:01:18.732563 2018] [proxy_fcgi:error] [pid 1214:tid 139946878826240] (104)Connection reset by peer: [client 67.169.103.233:61468] AH01075: Error dispatching request to : 
[Wed Apr 11 02:01:18.732873 2018] [proxy_fcgi:error] [pid 1214:tid 139946965522176] [client 67.169.103.233:60538] AH01067: Failed to read FastCGI header
[Wed Apr 11 02:01:18.732881 2018] [proxy_fcgi:error] [pid 1214:tid 139946965522176] (104)Connection reset by peer: [client 67.169.103.233:60538] AH01075: Error dispatching request to : 
[Wed Apr 11 02:01:18.735497 2018] [proxy_fcgi:error] [pid 1214:tid 139946744542976] [client 67.169.103.233:61603] AH01067: Failed to read FastCGI header
[Wed Apr 11 02:01:18.735515 2018] [proxy_fcgi:error] [pid 1214:tid 139946744542976] (104)Connection reset by peer: [client 67.169.103.233:61603] AH01075: Error dispatching request to : 
[Wed Apr 11 02:01:18.737138 2018] [proxy_fcgi:error] [pid 754:tid 139946786506496] [client 67.169.103.233:61576] AH01067: Failed to read FastCGI header
[Wed Apr 11 02:01:18.737153 2018] [proxy_fcgi:error] [pid 754:tid 139946786506496] (104)Connection reset by peer: [client 67.169.103.233:61576] AH01075: Error dispatching request to : 
[Wed Apr 11 02:01:49.338176 2018] [core:notice] [pid 634:tid 139855966769152] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Apr 11 02:01:49.355483 2018] [suexec:notice] [pid 634:tid 139855966769152] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 11 02:01:49.562826 2018] [lbmethod_heartbeat:notice] [pid 634:tid 139855966769152] AH02282: No slotmem from mod_heartmonitor
[Wed Apr 11 02:01:49.697485 2018] [mpm_event:notice] [pid 634:tid 139855966769152] AH00489: Apache/2.4.33 (Fedora) OpenSSL/1.1.0h-fips configured -- resuming normal operations
[Wed Apr 11 02:01:49.697523 2018] [core:notice] [pid 634:tid 139855966769152] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Apr 11 02:06:20.540275 2018] [authz_core:error] [pid 1217:tid 139855216477952] [client 67.169.103.233:61884] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Wed Apr 11 02:06:22.943046 2018] [authz_core:error] [pid 1217:tid 139854595745536] [client 67.169.103.233:61876] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Wed Apr 11 02:06:26.082786 2018] [authz_core:error] [pid 1217:tid 139855266834176] [client 67.169.103.233:61889] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Wed Apr 11 02:11:58.710060 2018] [authz_core:error] [pid 1217:tid 139855157729024] [client 67.169.103.233:62071] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Wed Apr 11 02:12:01.258817 2018] [authz_core:error] [pid 1217:tid 139855191299840] [client 67.169.103.233:62073] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Wed Apr 11 02:37:16.298371 2018] [authz_core:error] [pid 1217:tid 139855090587392] [client 67.169.103.233:63020] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Wed Apr 11 02:57:15.778934 2018] [authz_core:error] [pid 1217:tid 139855149336320] [client 67.169.103.233:63737] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata

```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"Ws3OmqGrrzkmvNL0f-aXTQAAAM8","level":3,"time":"2018-04-11T09:00:10+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3OpaGrrzkmvNL0f-aXXgAAANg","level":3,"time":"2018-04-11T09:00:21+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3OpaGrrzkmvNL0f-aXXgAAANg","level":3,"time":"2018-04-11T09:00:21+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3Op4jNZZUWmpsiW@bjsQAAAIE","level":3,"time":"2018-04-11T09:00:23+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/externalstorages","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3Op4jNZZUWmpsiW@bjsQAAAIE","level":3,"time":"2018-04-11T09:00:23+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/externalstorages","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3OqaGrrzkmvNL0f-aXagAAANA","level":3,"time":"2018-04-11T09:00:25+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/encryption","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3OqaGrrzkmvNL0f-aXagAAANA","level":3,"time":"2018-04-11T09:00:25+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/encryption","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3Oq4jNZZUWmpsiW@bjxAAAAIE","level":3,"time":"2018-04-11T09:00:27+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/files_accesscontrol","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3Oq4jNZZUWmpsiW@bjxAAAAIE","level":3,"time":"2018-04-11T09:00:27+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/files_accesscontrol","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3OsqGrrzkmvNL0f-aXgwAAANM","level":3,"time":"2018-04-11T09:00:34+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3OsqGrrzkmvNL0f-aXgwAAANM","level":3,"time":"2018-04-11T09:00:34+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3Ot4jNZZUWmpsiW@bj1QAAAIw","level":3,"time":"2018-04-11T09:00:39+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3Ot4jNZZUWmpsiW@bj1QAAAIw","level":3,"time":"2018-04-11T09:00:39+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QC@b4adtVHZDequRm-QAAANI","level":3,"time":"2018-04-11T09:06:20+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QC@b4adtVHZDequRm-QAAANI","level":3,"time":"2018-04-11T09:06:20+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QDub4adtVHZDequRnBwAAANU","level":3,"time":"2018-04-11T09:06:22+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/files_accesscontrol","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QDub4adtVHZDequRnBwAAANU","level":3,"time":"2018-04-11T09:06:22+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/files_accesscontrol","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QEeb4adtVHZDequRnFAAAAM4","level":3,"time":"2018-04-11T09:06:25+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/issuetemplate","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QEeb4adtVHZDequRnFAAAAM4","level":3,"time":"2018-04-11T09:06:25+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/issuetemplate","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3QEeb4adtVHZDequRnFAAAAM4","level":3,"time":"2018-04-11T09:06:25+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/issuetemplate","message":"Array to string conversion at \/var\/www\/html\/nextcloud\/apps\/issuetemplate\/lib\/DetailManager.php#104","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3RXub4adtVHZDequRo@wAAANU","level":3,"time":"2018-04-11T09:11:58+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3RXub4adtVHZDequRo@wAAANU","level":3,"time":"2018-04-11T09:11:58+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3RYOb4adtVHZDequRpBQAAANg","level":3,"time":"2018-04-11T09:12:00+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3RYOb4adtVHZDequRpBQAAANg","level":3,"time":"2018-04-11T09:12:00+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3U3Ob4adtVHZDequRtywAAAMw","level":4,"time":"2018-04-11T09:26:54+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/Admin3\/web-file-upload-f133b1c5a3361836d116f914c0ff1ea5-1523437469640\/985661440","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Error while copying file to target location (copied bytes: 1228800, expected filesize: 10485760 )\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #9)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(39): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('985661440', Resource id #9)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile('985661440', Resource id #9)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('uploads\\\/Admin3\\\/...', Resource id #9, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":171}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3XS@b4adtVHZDequRv2AAAAM0","level":3,"time":"2018-04-11T09:37:15+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"Undefined index: loginForm at \/var\/www\/html\/nextcloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"Ws3XS@b4adtVHZDequRv2AAAAM0","level":3,"time":"2018-04-11T09:37:15+00:00","remoteAddr":"67.169.103.233","user":"Admin3","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"AuGVLaHh2oLvnABrUfSb","level":3,"time":"2018-04-11T09:45:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#295","userAgent":"--","version":"13.0.1.1"}

```
</details>

<details><summary>Admin Log</summary>

Fatal | webdav | Sabre\DAV\Exception: Error while copying file to target location (copied bytes: 1228800, expected filesize: 10485760 )/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 151:OCA\DAV\Connector\Sabre\File->put(Resource id #9)/var/www/html/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 39:OCA\DAV\Connector\Sabre\Directory->createFile('985661440', Resource id #9)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:OCA\DAV\Upload\UploadFolder->createFile('985661440', Resource id #9)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('uploads/Admin3/...', Resource id #9, NULL)[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array(Array, Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/var/www/html/nextcloud/remote.php - line 164: require_once('/var/www/html/n...'){main}
-- | -- | --
</details>

**Comment by Apperator** [comment]
Hi, 

I have configured the server for large uploads.
I am able to upload large files sucessfully into a non external storage.

This unexpected behavior only occurs when using external storage.

**Comment by najcardboyz** [comment]
same as me, i was used minio and wasabi as primary storage on nextcloud, problem came from big file, if upload more than 1 GB, it not work.

**Comment by ikogan** [comment]
I'm seeing related issues when synchronizing files from Android to external storage over SSH. The file copy from the Nextcloud server to the SSH server takes too long, causing timeouts all over the place.

It's unreasonable for an app like this in 2019 to demand a single, stable HTTP stream to handle file uploads in this manner. This is why the sync clients chunk the file uploads but since the resulting file is first assembled on the Nextcloud server and then moved to external storage, the problem still occurs.

**Comment by aitronssesin** [comment]
I have exactly teh same issue
