### ISSUE TITLE
Problem renaming folders

### ISSUE THREAD

**Issue by jar361** [nextcloud/server#9152]
### Steps to reproduce
1. Rename "2018 test" folder in NextCloud Web UI to new name "Testing"
2. Get error message "Could not rename 2018 test in Web UI
3. New folder "Testing" was created
4. "2018 test" still exist
5. Get the following in the nextcloud logs:
Exception: {"Exception":"InvalidArgumentException","Message":"Found 1 error while validating the input provided for the DeleteObjects operation:\n[Delete] is missing and is a required parameter","Code":0,"Trace":"#0

### Expected behaviour
Folder get rename from "2018 test" to "Testing"

### Actual behaviour
1. Rename "2018 test" folder in NextCloud Web UI to new name "Testing"
2. Get error message "Could not rename 2018 test in Web UI
3. New folder "Testing" was created
4. "2018 test" still exist
5. Get the following in the nextcloud logs:
Exception: {"Exception":"InvalidArgumentException","Message":"Found 1 error while validating the input provided for the DeleteObjects operation:\n[Delete] is missing and is a required parameter","Code":0,"Trace":"#0

### Server configuration

**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache2.4.7

**Database:** mysql

**PHP version:** php7

**Nextcloud version:** (see Nextcloud admin page) 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** from 12.0.2

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - files_pdfviewer
  - notifications
  - sharebymail
  - survey_client

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<?php
$CONFIG = array (
  'instanceid' => 'instanceid',
  'passwordsalt' => 'pwsalt',
  'secret' => 'my secret',
  'trusted_domains' =>
  array (
    0 => 'cloud.powerhrg.com',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://cloud.powerhrg.com',
  'dbtype' => 'mysql',
  'version' => '12.0.5.3',
  'dbname' => 'dbname',
  'dbhost' => 'db.host.com',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'dbpassword',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'mailAddress',
  'mail_domain' => 'mailDomain',
  'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\S3',
    'arguments' =>
    array (
      'bucket' => 'nextcloud-default',
      'autocreate' => false,
      'key' => 'my key',
      'secret' => 'my secret',
      'hostname' => 's3 hostname',
      'use_ssl' => true,
      'use_path_style' => true,
    ),
  ),
  'loglevel' => 1,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array(
    'host' => 'redishost',
    'port' => '13764',
  ),
  'versions_retention_obligation' => 'auto',
  'logfile' => '/var/log/nextcloud.log',
  'updater.release.channel' => 'production',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'my mail server',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'smtpname',
  'mail_smtppassword' => 'my password',
  'tempdirectory' => '/data/mnt/nitrocloud_tmp/cache',
  'updatechecker' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes. S3 NetApp StorageGrid 10.4

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

| Configuration                 | s01                                                |
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                  |
| hasPagedResultSupport         |                                                    |
| homeFolderNamingRule          |                                                    |
| lastJpegPhotoLookup           | 0                                                  |
| ldapAgentName                 | cn=agentName                     |
| ldapAgentPassword             | ***                                                |
| ldapAttributesForGroupSearch  |                                                    |
| ldapAttributesForUserSearch   | uid                                                |
| ldapBackupHost                |                                                    |
| ldapBackupPort                |                                                    |
| ldapBase                      | dc=base                                 |
| ldapBaseGroups                | ou=groupsDN                       |
| ldapBaseUsers                 | ou=usersDN                        |
| ldapCacheTTL                  | 600                                                |
| ldapConfigurationActive       | 1                                                  |
| ldapDefaultPPolicyDN          |                                                    |
| ldapDynamicGroupMemberURL     |                                                    |
| ldapEmailAttribute            | mail                                               |
| ldapExperiencedAdmin          | 1                                                  |
| ldapExpertUUIDGroupAttr       |                                                    |
| ldapExpertUUIDUserAttr        |                                                    |
| ldapExpertUsernameAttr        |                                                    |
| ldapGidNumber                 | gidNumber                                          |
| ldapGroupDisplayName          | cn                                                 |
| ldapGroupFilter               | (&(objectclass=posixGroup))                        |
| ldapGroupFilterGroups         |                                                    |
| ldapGroupFilterMode           | 0                                                  |
| ldapGroupFilterObjectclass    | posixGroup                                         |
| ldapGroupMemberAssocAttr      | memberUid                                          |
| ldapHost                      | ldaphost                                  |
| ldapIgnoreNamingRules         |                                                    |
| ldapLoginFilter               | (&(objectclass=posixAccount)(uid=%uid))            |
| ldapLoginFilterAttributes     |                                                    |
| ldapLoginFilterEmail          | 0                                                  |
| ldapLoginFilterMode           | 1                                                  |
| ldapLoginFilterUsername       | 1                                                  |
| ldapNestedGroups              | 0                                                  |
| ldapOverrideMainServer        |                                                    |
| ldapPagingSize                | 500                                                |
| ldapPort                      | 389                                                |
| ldapQuotaAttribute            |                                                    |
| ldapQuotaDefault              |                                                    |
| ldapTLS                       | 0                                                  |
| ldapUserDisplayName           | displayName                                        |
| ldapUserDisplayName2          |                                                    |
| ldapUserFilter                | (&(objectclass=posixAccount)(mail=mailFilter)) |
| ldapUserFilterGroups          |                                                    |
| ldapUserFilterMode            | 1                                                  |
| ldapUserFilterObjectclass     | posixAccount                                       |
| ldapUuidGroupAttribute        | auto                                               |
| ldapUuidUserAttribute         | auto                                               |
| turnOffCertCheck              | 0                                                  |
| turnOnPasswordChange          | 0                                                  |
| useMemberOfToDetectMembership | 0

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome Version 65.0.3325.181
Firefox 59.0.4(64bit)

**Operating system:** OS X 10.13.4

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Exception: {"Exception":"InvalidArgumentException","Message":"Found 1 error while validating the input provided for the DeleteObjects operation:\n[Delete] is missing and is a required parameter","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/Middleware.php(79): Aws\\Api\\Validator->validate('DeleteObjects', Object(Aws\\Api\\StructureShape), Array)\n#1 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3Client.php(421): Aws\\Middleware::Aws\\{closure}(*** sensitive parameters replaced ***)\n#2 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3Client.php(444): Aws\\S3\\S3Client::Aws\\S3\\{closure}(*** sensitive parameters replaced ***)\n#3 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3Client.php(378): Aws\\S3\\S3Client::Aws\\S3\\{closure}(*** sensitive parameters replaced ***)\n#4 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3Client.php(397): Aws\\S3\\S3Client::Aws\\S3\\{closure}(*** sensitive parameters replaced ***)\n#5 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/Middleware.php(55): Aws\\S3\\S3Client::Aws\\S3\\{closure}(*** sensitive parameters replaced ***)\n#6 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/SSECMiddleware.php(59): Aws\\Middleware::Aws\\{closure}(*** sensitive parameters replaced ***)\n#7 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/IdempotencyTokenMiddleware.php(77): Aws\\S3\\SSECMiddleware->__invoke(Object(Aws\\Command), NULL)\n#8 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/AwsClientTrait.php(65): Aws\\IdempotencyTokenMiddleware->__invoke(Object(Aws\\Command))\n#9 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/AwsClientTrait.php(59): Aws\\AwsClient->executeAsync(Object(Aws\\Command))\n#10 \/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/AwsClientTrait.php(78): Aws\\AwsClient->execute(Object(Aws\\Command))\n#11 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php(255): Aws\\AwsClient->__call('deleteObjects', Array)\n#12 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php(224): OCA\\Files_External\\Lib\\Storage\\AmazonS3->batchDelete('2018 test')\n#13 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php(561): OCA\\Files_External\\Lib\\Storage\\AmazonS3->rmdir('2018 test')\n#14 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(272): OCA\\Files_External\\Lib\\Storage\\AmazonS3->rename('2018 test', 'Testing')\n#15 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php(296): OC\\Files\\Storage\\Wrapper\\Wrapper->rename('2018 test', 'Testing')\n#16 \/var\/www\/nextcloud\/apps\/files_trashbin\/lib\/Storage.php(141): OC\\Files\\Storage\\Wrapper\\Availability->rename('2018 test', 'Testing')\n#17 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(817): OCA\\Files_Trashbin\\Storage->rename('2018 test', 'Testing')\n#18 \/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Node.php(137): OC\\Files\\View->rename('\/Power Video\/20...', '\/Power Video\/Te...')\n#19 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(151): OCA\\DAV\\Connector\\Sabre\\Node->setName('Testing')\n#20 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(642): Sabre\\DAV\\Tree->move('Power Video\/201...', 'Power Video\/Tes...')\n#21 [internal function]: Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#22 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#23 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:MOVE', Array)\n#24 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#25 \/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(76): Sabre\\DAV\\Server->exec()\n#26 \/var\/www\/nextcloud\/remote.php(162): require_once('\/var\/www\/nextcl...')\n#27 {main}","File":"\/var\/www\/nextcloud\/3rdparty\/aws\/aws-sdk-php\/src\/Api\/Validator.php","Line":65}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jar361** [comment]
The issue mainly happens on S3(external storage) network shares.  I can rename folders on a locally mounted share.
