### ISSUE TITLE
Fresh install NC 13.0.1 : Exception: Doctrine\DBAL\Exception\TableNotFoundException\

### ISSUE THREAD

**Issue by pousterlus** [nextcloud/server#9253]
Hello everyone,

I searched the forum but I found nothing relevant to my specific problem.
I read some solutions for quite close cases, but not sure if it applies for mine, especially something about "mysql.utf8mb4".
I prefer to have your advice before beginning to mess around trying every solutions :)

Thanks !

### Steps to reproduce
1. Click the "Share" icon of any folder
2. Start typing a name of another user in Nextcloud

### Expected behaviour
Names of configured users are shown.

### Actual behaviour
Nothing shows up.

### Server configuration

**Operating system**: FreeBSD 11.1
**Web server:** Apache 2.4.33
**Database:** MySQL 5.7
**PHP version:** 7.1.16
**Nextcloud version:** (see Nextcloud admin page) Nextcloud 13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Ports tree

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.domain.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.domain.fr",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "apps_paths": [
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
                "url": "\/apps-pkg",
                "writable": false
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false
    }
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:** Firefox / Chrome / Opera

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
86.247.XX.YY - - [20/Apr/2018:14:18:14 +0200] "GET /ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=nathalie&perPage=200&itemType=folder HTTP/1.1" 200 228
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"u9bbGBziwSndsnEuwsdv","level":3,"time":"2018-04-20T11:41:27+00:00","remoteAddr":"86.247.66.97","user":"max","app":"no app in context","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=natha&perPage=200&itemType=folder","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uri`, `displayname`, `principaluri`, `description`, `synctoken` FROM `oc_addressbooks` WHERE `principaluri` = ?' with params [\\\"principals\\\\\\\/users\\\\\\\/max\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_addressbooks' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps-pkg\\\/dav\\\/lib\\\/CardDAV\\\/CardDavBackend.php(155): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps-pkg\\\/dav\\\/lib\\\/CardDAV\\\/ContactsManager.php(56): OCA\\\\DAV\\\\CardDAV\\\\CardDavBackend->getAddressBooksForUser('principals\\\/user...')\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps-pkg\\\/dav\\\/lib\\\/AppInfo\\\/Application.php(75): OCA\\\\DAV\\\\CardDAV\\\\ContactsManager->setupContactsProvider(Object(OC\\\\ContactsManager), 'max', Object(OC\\\\URLGenerator))\\n#8 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps-pkg\\\/dav\\\/appinfo\\\/app.php(55): OCA\\\\DAV\\\\AppInfo\\\\Application->setupContactsProvider(Object(OC\\\\ContactsManager), 'max')\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ContactsManager.php(185): OC_App::{closure}(*** sensitive parameters replaced ***)\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ContactsManager.php(42): OC\\\\ContactsManager->loadAddressBooks()\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Collaboration\\\/Collaborators\\\/RemotePlugin.php(59): OC\\\\ContactsManager->search('natha', Array)\\n#12 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Collaboration\\\/Collaborators\\\/Search.php(65): OC\\\\Collaboration\\\\Collaborators\\\\RemotePlugin->search('natha', 200, 0, Object(OC\\\\Collaboration\\\\Collaborators\\\\SearchResult))\\n#13 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps-pkg\\\/files_sharing\\\/lib\\\/Controller\\\/ShareesAPIController.php(181): OC\\\\Collaboration\\\\Collaborators\\\\Search->search('natha', Array, true, 200, 0)\\n#14 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareesAPIController->search('natha', 'folder', 1, 200, NULL, true)\\n#15 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#16 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareesAPIController), 'search')\\n#17 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareesAPIController), 'search')\\n#18 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Shari...', 'search', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#19 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#20 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#21 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/ocs\\\/v1.php(78): OC\\\\Route\\\\Router->match('\\\/ocsapp\\\/apps\\\/fi...')\\n#22 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36 OPR\/52.0.2871.40","version":"13.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing.
```
</details>

-- 
Léo.

**Comment by pousterlus** [comment]
Hello,

If other people get into this, easy fix : Go to the nextcloud directory, and type : 
`sudo -u www php occ app:enable dav`
or
`sudo -u www-data php occ app:enable dav`
According to your server configuration.

-- 
Léo.
