### ISSUE TITLE
Upgrading from 11.0.3.2 to 12.0.7 fails to enable oauth2 app

### ISSUE THREAD

**Issue by walec51** [nextcloud/server#9426]
Web browser based upgrade - I'm on a hosted enviorment

### Expected behavior
Clean upgrade to 12.0.7

### Actual behaviour
Failed upgrade with message in browser: oauth2: Failed to enable app oauth2
Not working installation after upgrade

### Server configuration

**Operating system**: Debian Jessie

**Database:** 10.0.34-MariaDB-1~jessie

**PHP version:** 7.1

**Nextcloud version:** 12.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:** 11.0.3.2

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'masked.id',
  'passwordsalt' => 'masked.salt',
  'secret' => 'masked.secret',
  'trusted_domains' => 
  array (
    0 => 'pliki.walczakparkiety.pl',
  ),
  'datadirectory' => '/www/walczak_files/data',
  'overwrite.cli.url' => 'https://masked.url',
  'dbtype' => 'mysql',
  'version' => '12.0.7.1',
  'dbname' => 'walczak_files',
  'dbhost' => 'masked.url',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'walczak_files',
  'dbpassword' => 'masked.password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 1,
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'masked.url',
  'updater.release.channel' => 'stable',
  'updater.secret' => 'masked.secret',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WvHqsVZv8psAACmbyUkAAADM","level":3,"time":"2018-05-08T18:21:48+00:00","remoteAddr":"83.11.109.89","user":"--","app":"oauth2","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=uGXIujRl5Tvsg0LmA%2FNTXpja2mDMKtWjT%2F2MgyL7JnE%3D%3A9g6wlXUQjAyhwTuPbcQ%2Fb8CAsVnjT7LzN6m58Q2YSQA%3D","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app oauth2\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/walczak_files\\\/files-www\\\/lib\\\/private\\\/Installer.php(501): OC\\\\Installer::installShippedApp('oauth2')\\n#1 \\\/www\\\/walczak_files\\\/files-www\\\/lib\\\/private\\\/Updater.php(275): OC\\\\Installer::installShippedApps(true)\\n#2 \\\/www\\\/walczak_files\\\/files-www\\\/lib\\\/private\\\/Updater.php(130): OC\\\\Updater->doUpgrade('12.0.7.1', '11.0.3.2')\\n#3 \\\/www\\\/walczak_files\\\/files-www\\\/core\\\/ajax\\\/update.php(206): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/www\\\/walczak_files\\\/files-www\\\/lib\\\/private\\\/Installer.php\",\"Line\":537}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.79 Safari\/537.36","version":"11.0.3.2"}
{"reqId":"WvHqsVZv8psAACmbyUkAAADM","level":3,"time":"2018-05-08T18:21:48+00:00","remoteAddr":"83.11.109.89","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=uGXIujRl5Tvsg0LmA%2FNTXpja2mDMKtWjT%2F2MgyL7JnE%3D%3A9g6wlXUQjAyhwTuPbcQ%2Fb8CAsVnjT7LzN6m58Q2YSQA%3D","message":"\\OC\\Updater::failure: oauth2: Failed to enable app oauth2","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.79 Safari\/537.36","version":"11.0.3.2"}
```
</details>

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer Any idea why this could happen?

**Comment by walec51** [comment]
if managed to workaround this problem by deleting the oauth table manualy before upgrading

now I have a different problem - I'll report it separatly
