### ISSUE TITLE
cron: Call to getLogger() on null in lib/public/Util.php:158

### ISSUE THREAD

**Issue by cweiske** [nextcloud/server#9476]
### Steps to reproduce
1. Run cronjob `cron.php`
2. (Sometimes) Get e-mail with failure

### Expected behaviour
No error

### Actual behaviour
I get an error e-mail:

```
PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /path/to/lib/public/Util.php:158
Stack trace:
#0 /path/to/cron.php(158): OCP\Util::writeLog('cron', 'Could not acqui...', 4)
#1 {main}
  thrown in /path/to/lib/public/Util.php on line 158
```

I could see the underlying error while collecting information for this bug report:

```
An unhandled exception has been thrown:
Exception: Could not acquire a shared lock on the config file /path/to/config/config.php in /path/to/lib/private/Config.php:210
Stack trace:
#0 /path/to/lib/private/Config.php(63): OC\Config->readData()
#1 /path/to/lib/base.php(134): OC\Config->__construct('/var/www/system...')
#2 /path/to/lib/base.php(597): OC::initPaths()
#3 /path/to/lib/base.php(1081): OC::init()
#4 /path/to/console.php(46): require_once('/var/www/system...')
#5 /path/to/occ(11): require_once('/var/www/system...')
#6 {main}
```

This only happens since upgrading to Nextcloud 13. With Nextcloud 12, I never had such an error.

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2

**Database:** MySQL 5.5

**PHP version:** 7.0.27

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - grauphel: 0.6.7
  - issuetemplate: 0.3.0
  - lookup_server_connector: 1.1.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.1
  - tasks: 0.9.6
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - comments
  - encryption
  - files_external
  - files_pdfviewer
  - logreader
  - news
  - nextcloud_announcements
  - serverinfo
  - survey_client
  - systemtags
  - theming
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "defaultapp": "calendar",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "mydomain"
        ],
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{mymailserver:993\/imap\/ssl}"
                ]
            }
        ],
        "loglevel": 3,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "overwrite.cli.url": "https:\/\/cloud.endrullis.de"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** imap

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no relevant entries
```
</details>

**Comment by MorrisJobke** [comment]
Sadly there isn't much we can do here - it tries to get a FS lock on the config file to read the config, but fails to do so. Then we can't read the info about where to log the error to and thus fails hard. 

cc @rullzer @icewind1991 or do you have another idea here?

**Comment by cweiske** [comment]
It was a resource problem on my server - out of 1000 locks allowed, MySQL hat used up over 900 leaving not much for other apps.

So we can ignore this issue, or check if the logger is there - and if not, simply echo the exception instead of logging it.

**Comment by MorrisJobke** [comment]
We intentionally not echo the exception to not leak any internals in case it is called via web.
