### ISSUE TITLE
"The supplied iCalendar datetime value is incorrect"

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#950]
Found in cloud.nextcloud.com logs, this is a fatal exception.

@oparoz Do you have more information on that? It seems to be caused by your user account :) 

```
Exception: {"Message":"The supplied iCalendar datetime value is incorrect: master","Exception":"LogicException","Code":0,"Trace":"#0 \/var\/www\/html\/3rdparty\/sabre\/vobject\/lib\/DateTimeParser.php(188): Sabre\\VObject\\DateTimeParser::parseDateTime('master', NULL)\n#1 \/var\/www\/html\/3rdparty\/sabre\/vobject\/lib\/ITip\/Broker.php(758): Sabre\\VObject\\DateTimeParser::parse('master', NULL)\n#2 \/var\/www\/html\/3rdparty\/sabre\/vobject\/lib\/ITip\/Broker.php(257): Sabre\\VObject\\ITip\\Broker->parseEventForAttendee(Object(Sabre\\VObject\\Component\\VCalendar), Array, Array, Object(Sabre\\VObject\\Property\\ICalendar\\CalAddress))\n#3 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(349): Sabre\\VObject\\ITip\\Broker->parseEvent(NULL, Array, Object(Sabre\\VObject\\Component\\VCalendar))\n#4 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->beforeUnbind('calendars\/olivi...')\n#5 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(284): Sabre\\Event\\EventEmitter->emit('beforeUnbind', Array)\n#7 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#10 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/var\/www\/html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#12 \/var\/www\/html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#13 \/var\/www\/html\/remote.php(165): require_once('\/var\/www\/html\/a...')\n#14 {main}","File":"\/var\/www\/html\/3rdparty\/sabre\/vobject\/lib\/DateTimeParser.php","Line":40,"User":"olivier"} 
```

**Comment by oparoz** [comment]
If that's the bug I'm thinking about

1. Create an event
2. Set the start date to 2 weeks ago
3. Click on create

The event will vanish

**Comment by Maxqia** [comment]
I can reproduce this on Nextcloud 9 while importing a calendar, and if I import it using ics2owncloud, it imports fine and displays fine on my phone, but the Nextcloud calendar says "Some events in this calender are broken, Please check the JS console for more info"

**Comment by MorrisJobke** [comment]
Move to 10.0.2

**Comment by MorrisJobke** [comment]
> * Create an event
> * Set the start date to 2 weeks ago
> * Click on create

Tested and works on master -> closing
