### ISSUE TITLE
Web upload should probably ignore OSX pointer files

### ISSUE THREAD

**Issue by RNCTX** [nextcloud/server#9533]
### Steps to reproduce
1. Drag and drop a folder from an OSX client
2. cd /path/to/www/nextcloud/data/user/folder
3. find . '*.ext'

### Expected behaviour
Nextcloud should probably ignore hidden metadata files that OSX puts all over its file system.

### Actual behaviour
For every file uploaded in this manner from an OSX client, there will be a hidden metadata file beginning in ._

(ex myfile.pdf will have another named ._myfile.pdf)

### Server configuration

**Operating system**:
FreeBSD 11.1-STABLE
**Web server:**
Nginx 1.12
**Database:**
postgres 9.5
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
13.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
official site zip file
### Client configuration
**Browser:**
Chrome v66.0.3359.181
**Operating system:**
OSX

I can't find the document on an Apple domain, but here's an edu user still hosting the Apple document from way back when, explaining OSX's file metadata behavior (from 2001).  I can confirm that as of the current version of OSX this has not changed...

http://barbie.uta.edu/~jli/Resources/Resource%20Provisoning&Performance%20Evaluation/81.pdf

On page 182, in "The Finder and File Operations":

> When the Finder copies or moves a file, it uses the richest model available, given the
> formats of the source and destination volumes. The formats that are most significant
> in these kinds of operations are HFS+ (or HFS) and UFS. These operations
> particularly affect the representation of the HFS and HFS+ resource fork and the
> Finder attributes, especially the type and creator codes.
> 
> As one might expect, the Finder preserves the resource fork and Finder attributes of
> an HFS+ file “as is” when it copies the file to an HFS+ (or HFS) volume. The more
> interesting case, however, is when it copies an HFS+ file to a UFS volume. When this
> happens, the Finder splits out the information that is not in the data fork
> (particularly the type and creator codes) and writes this information to a hidden file
> in the same directory location as the copied file. This hidden file has the same name
> as the UFS file, except that it has a “dot-underscore” prefix. Thus, if you have an
> HFS+ file named MyMug.jpeg, when you copy it to a UFS volume, there will be a file
> named ._MyMug.jpeg in the same location.
> 
> When the Finder copies a UFS file to an HFS or HFS+ volume, it looks for the hidden
> “dot-underscore” file. If one exists, it creates an HFS+ (or HFS) file reintegrating the
> information in the hidden file into the file’s resource fork and Finder attributes. If
> the hidden file does not exist, the copied file has no resource fork.

I get that this is a really stupid design on Apple's part to litter users' file systems with gazillions of hidden files, and it's not the fault of Nextcloud, but it would be nice for batch processing apps/functions if Nextcloud could ignore, or have the option to ignore, these OSX metadata files (.DS_Store being another notorious one, that everyone knows about) from batch uploads such as folder drag/drop operations.

**Comment by tflidd** [comment]
If you use the nextcloud client, https://github.com/nextcloud/client/issues is the better place for a report. If you use it as a webdav-network-drive, then it should stay.

**Comment by RNCTX** [comment]
The report is in reference to the web interface (hence listing my Chrome version).  I do not use the desktop client(s).

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript 

IMO this makes a lot of sense

**Comment by RNCTX** [comment]
Rationale from my POV as an OSX desktop user and *nix server user:

1) If I wanted to retain OSX's metadata files (for a proper backup of a whole or part of a filesystem) I would use another tool to ensure that hidden files/folders are transferred such as tar archives, git, rsync, OSX's integral backup tool, etc. I have no reason to expect that a browser upload accesses hidden files outside of the directories that belong to the browser application.

2) If a user knows enough about *nix filesystems to know that hidden files begin with a dot, they should rightfully assume that a web browser function does not expose hidden files on their system. All browsers on OSX ignore a user's request to upload their entire home folder from OSX via a browser, because that would include their .ssh folders, for example.

3) I think the #2 example is a sort of 'scorched earth' policy, in that the browser refuses to perform the user's request, but a default-off option to ignore dot-hidden files from uploads seems like a wise change, in keeping with common practices of handling dot-hidden *nix files. If a user actively seeks out what is preventing him/her from uploading dot-hidden files and disables it despite warnings to the contrary, then the responsibility belongs to the user.

**Comment by skjnldsv** [comment]
@MorrisJobke should we create a list to ignore like our desktop client?

**Comment by RNCTX** [comment]
Update to this:

As you guys may or may not have noticed if you've worked on this (I have since I'm utilizing WebDAV in an unrelated project...), there is no way to stop OSX from doing this.

So this becomes a bit of a catch22, upon further investigation.

If you stop the OSX client from putting the dot-underscore files in there, it will keep trying to put them there.  If you delete them, it will put them there again as soon as it changes directories and gets an updated directory contents from the server.

Here's the info-level output of a Rails app that I'm working with, in trying to get an OSX client talking to the Rails implementation of WebDAV...

```
passenger (5.3.4) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (5.3.4) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
passenger (5.3.4) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.3.4) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
passenger (5.3.4) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
I, [2018-08-27T17:42:31.951648 #29134]  INFO -- : Started LOCK "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:31 -0500
I, [2018-08-27T17:42:31.956540 #36034]  INFO -- : Started PROPFIND "/webdav/._Beechcraft" for 192.168.1.1 at 2018-08-27 17:42:31 -0500
I, [2018-08-27T17:42:31.968143 #29134]  INFO -- : Started PROPFIND "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:31 -0500
I, [2018-08-27T17:42:31.977465 #29134]  INFO -- : Started PROPFIND "/webdav/._Piper" for 192.168.1.1 at 2018-08-27 17:42:31 -0500
I, [2018-08-27T17:42:31.985922 #29134]  INFO -- : Started PROPFIND "/webdav/._Appareo" for 192.168.1.1 at 2018-08-27 17:42:31 -0500
I, [2018-08-27T17:42:31.997406 #29134]  INFO -- : Started PROPFIND "/webdav/._Garmin" for 192.168.1.1 at 2018-08-27 17:42:31 -0500
I, [2018-08-27T17:42:32.012099 #29134]  INFO -- : Started PROPFIND "/webdav/._Continental" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.037552 #29134]  INFO -- : Started PROPFIND "/webdav/" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.075780 #29134]  INFO -- : Started PROPFIND "/webdav/._Narco" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.085319 #29134]  INFO -- : Started PROPFIND "/webdav/._King" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.093756 #29134]  INFO -- : Started PROPFIND "/webdav/._." for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.102617 #29134]  INFO -- : Started PROPFIND "/webdav/._Diamond%2040" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.111850 #29134]  INFO -- : Started PROPFIND "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.121465 #29134]  INFO -- : Started PROPFIND "/webdav/._PS%20Engineering" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.135168 #29134]  INFO -- : Started PROPFIND "/webdav/._Interav" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.149347 #29134]  INFO -- : Started PROPFIND "/webdav/" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.197219 #29134]  INFO -- : Started PROPFIND "/webdav/._E.I." for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.209227 #29134]  INFO -- : Started PROPFIND "/webdav/" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.225705 #29134]  INFO -- : Started PROPFIND "/webdav/._Trig" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.239484 #29134]  INFO -- : Started PROPFIND "/webdav/._Grumman" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.255156 #29134]  INFO -- : Started PROPFIND "/webdav/" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.309564 #29134]  INFO -- : Started PROPFIND "/webdav/._Plane%20Power" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.318652 #29134]  INFO -- : Started PROPFIND "/webdav/._Navworx" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.330345 #29134]  INFO -- : Started PROPFIND "/webdav/._Century" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.343673 #29134]  INFO -- : Started PROPFIND "/webdav/._Cessna" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.356480 #29134]  INFO -- : Started PROPFIND "/webdav/._Transcal" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.372014 #29134]  INFO -- : Started PROPFIND "/webdav/._Aspen%20Avionics" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.387780 #29134]  INFO -- : Started PROPFIND "/webdav/._Continental%20Aero" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.402557 #29134]  INFO -- : Started PROPFIND "/webdav/._Manuals" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.416025 #29134]  INFO -- : Started PROPFIND "/webdav/._S-TEC" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.431174 #29134]  INFO -- : Started PROPFIND "/webdav/._Stormscope" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.445125 #29134]  INFO -- : Started PROPFIND "/webdav/._Lycoming" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.460110 #29134]  INFO -- : Started PROPFIND "/webdav/._JPInstruments" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.474989 #29134]  INFO -- : Started PROPFIND "/webdav/._Sandel" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.490162 #29134]  INFO -- : Started PROPFIND "/webdav/._Commander" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.505189 #29134]  INFO -- : Started PROPFIND "/webdav/._Mooney" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.519377 #29134]  INFO -- : Started PROPFIND "/webdav/._Cirrus" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.533269 #29134]  INFO -- : Started PROPFIND "/webdav/._Aircraft%20Inspection" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.549568 #29134]  INFO -- : Started PROPFIND "/webdav/._Aviation%20Mechanic" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.563987 #29134]  INFO -- : Started PROPFIND "/webdav/._Avidyne" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.582202 #29134]  INFO -- : Started PROPFIND "/webdav/Navworx/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.595886 #29134]  INFO -- : Started PROPFIND "/webdav/Cessna/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.610940 #29134]  INFO -- : Started PROPFIND "/webdav/Aspen%20Avionics/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.624925 #29134]  INFO -- : Started PROPFIND "/webdav/Pratt%20&%20Whitney/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.639981 #29134]  INFO -- : Started PROPFIND "/webdav/Pratt%20&%20Whitney/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.641254 #36034]  INFO -- : Started PROPFIND "/webdav/Beechcraft/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.655243 #29134]  INFO -- : Started PROPFIND "/webdav/Piper/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.670972 #29134]  INFO -- : Started PROPFIND "/webdav/Piper/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.671683 #36034]  INFO -- : Started PROPFIND "/webdav/Appareo/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.686476 #29134]  INFO -- : Started PROPFIND "/webdav/Garmin/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.700566 #29134]  INFO -- : Started PROPFIND "/webdav/Continental/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.716376 #29134]  INFO -- : Started PROPFIND "/webdav/Narco/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.731656 #29134]  INFO -- : Started PROPFIND "/webdav/King/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.746442 #29134]  INFO -- : Started PROPFIND "/webdav/Diamond%2040/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.760734 #29134]  INFO -- : Started PROPFIND "/webdav/PS%20Engineering/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.775552 #29134]  INFO -- : Started PROPFIND "/webdav/Interav/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.789874 #29134]  INFO -- : Started PROPFIND "/webdav/E.I./.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.803966 #29134]  INFO -- : Started PROPFIND "/webdav/Trig/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.818540 #29134]  INFO -- : Started PROPFIND "/webdav/Grumman/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.833437 #29134]  INFO -- : Started PROPFIND "/webdav/Plane%20Power/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.849281 #29134]  INFO -- : Started PROPFIND "/webdav/Century/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.862719 #29134]  INFO -- : Started PROPFIND "/webdav/Transcal/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.876652 #29134]  INFO -- : Started PROPFIND "/webdav/Continental%20Aero/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.876869 #36034]  INFO -- : Started PROPFIND "/webdav/Transcal/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.891197 #29134]  INFO -- : Started PROPFIND "/webdav/Manuals/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.905952 #29134]  INFO -- : Started PROPFIND "/webdav/S-TEC/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.921062 #29134]  INFO -- : Started PROPFIND "/webdav/Stormscope/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.937065 #29134]  INFO -- : Started PROPFIND "/webdav/Lycoming/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.938111 #36034]  INFO -- : Started PROPFIND "/webdav/Stormscope/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.952128 #29134]  INFO -- : Started PROPFIND "/webdav/JPInstruments/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.967592 #29134]  INFO -- : Started PROPFIND "/webdav/Sandel/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.982307 #29134]  INFO -- : Started PROPFIND "/webdav/Commander/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.997923 #29134]  INFO -- : Started PROPFIND "/webdav/Commander/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:32.998890 #36034]  INFO -- : Started PROPFIND "/webdav/Mooney/.localized" for 192.168.1.1 at 2018-08-27 17:42:32 -0500
I, [2018-08-27T17:42:33.013428 #29134]  INFO -- : Started PROPFIND "/webdav/Cirrus/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:33.028498 #29134]  INFO -- : Started PROPFIND "/webdav/Aircraft%20Inspection/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:33.043706 #29134]  INFO -- : Started PROPFIND "/webdav/Aircraft%20Inspection/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:33.044287 #36034]  INFO -- : Started PROPFIND "/webdav/Aviation%20Mechanic/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:33.060315 #29134]  INFO -- : Started PROPFIND "/webdav/Avidyne/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:33.075344 #29134]  INFO -- : Started PROPFIND "/webdav/Avidyne/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:33.104173 #29134]  INFO -- : Started PROPFIND "/webdav/.localized" for 192.168.1.1 at 2018-08-27 17:42:33 -0500
I, [2018-08-27T17:42:37.015203 #29134]  INFO -- : Started PROPFIND "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500
I, [2018-08-27T17:42:37.030826 #29134]  INFO -- : Started PROPFIND "/webdav/._.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500
I, [2018-08-27T17:42:37.042033 #29134]  INFO -- : Started GET "/webdav/._.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500
I, [2018-08-27T17:42:37.053449 #29134]  INFO -- : Started LOCK "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500
I, [2018-08-27T17:42:37.069311 #29134]  INFO -- : Started GET "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500
I, [2018-08-27T17:42:37.081103 #29134]  INFO -- : Started PUT "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500
I, [2018-08-27T17:42:37.091523 #29134]  INFO -- : Started UNLOCK "/webdav/.DS_Store" for 192.168.1.1 at 2018-08-27 17:42:37 -0500

```

In my case there are other issues because of Nginx not having a complete implementation of WebDAV so the Passenger errors can be ignored in this context, I just picked that as a starting point for an OSX client's initial re-connect to the server.

As you can see as soon as the OSX client tried to connect, it immediately checked for the presence of those dot-underscore files throughout the directory tree (those are all folders in the above example).

What will it do if it fails to find them?  Good question.  I'll know tomorrow or the day after, I have to replace my setup with Apache to get WebDAV working in my Rails example.

**Comment by szaimen** [comment]
Please fix this yourself by adding those files to the ignore list of the desktop client if they are not already present in the default ignore list. Please reopen if you still want to implement this.
