### ISSUE TITLE
OVH's OpenStack Swift remote storage fails without any apparent reason

### ISSUE THREAD

**Issue by babolivier** [nextcloud/server#9543]
### Steps to reproduce
1. Create an OpenStack Swift container hosted by OVH (Public Cloud Storage)
2. Configure it as external storage in Nextcloud

### Expected behaviour
The external storage is mounted, or I get an error explaining to me why it's not.

### Actual behaviour
![image](https://user-images.githubusercontent.com/5547783/40360282-f146afb0-5dc5-11e8-9184-fb372108515d.png)

Validation fails, no related error appears in Nextcloud's logs. When I try to access the mount point using the Files app, I get an "empty response from server" error (I'm translating the error message from French fwiw).

### Server configuration

**Operating system:** Archlinux

**Web server:** Caddy

**Database:** PostgreSQL

**PHP version:** 7.2.5

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated, but not recently, and unsure about whether this is related to my issue.

**Where did you install Nextcloud from:** [Archlinux packages](https://www.archlinux.org/packages/community/any/nextcloud/)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - music: 0.5.6
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.abolivier.bzh"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.abolivier.bzh",
        "dbtype": "pgsql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** Trying to use OVH's OpenStack Swift as external storage (currently failing), no other external storage is configured

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Unsure about the relevance of my answer, but I'm using CalDAV/CardDAV to sync my contacts and calendars with my phone.

### Client configuration
**Browser:** Firefox 60.0 (64-bit)

**Operating system:** Archlinux

#### Web server error log
<details>
<summary>Web server error log</summary>

Nothing related in my web server error log.

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Not directly related but I get this error every minute where NC seems to check the mounted external storage:
```
{"reqId":"0pcGk9l68KTcElFiFTgi","level":4,"time":"2018-05-22T11:37:17+00:00","remoteAddr":"**REDACTED**","user":"brendan","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/brendan\/PCS","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Storage with mount id 5 is not available\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChild('PCS')\\n#1 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(967): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/brendan\\\/P...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('files\\\/brendan\\\/P...', Array, 1)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#11 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":216}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.4.1","version":"13.0.2.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Network request sent by NC when validating the settings:
```
PUT /index.php/apps/files_external/globalstorages/5 HTTP/1.1
Host: **REDACTED**
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: fr,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
requesttoken: **REDACTED**
OCS-APIREQUEST: true
X-Requested-With: XMLHttpRequest
Content-Length: 522
Cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=brendan; nc_token=**REDACTED**; nc_session_id=**REDACTED**; oc_music_volume=50; oc_sessionPassphrase=**REDACTED**
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

{
  "mountPoint": "PCS",
  "backend": "swift",
  "authMechanism": "openstack::openstack",
  "backendOptions": {
    "service_name": "OVH PCS",
    "region": "GRA3",
    "bucket": "nextcloud",
    "timeout": "300",
    "user": "**REDACTED**",
    "password": "**REDACTED**",
    "tenant": "**REDACTED**",
    "url": "https://auth.cloud.ovh.net/v2.0"
  },
  "testOnly": true,
  "id": 5,
  "mountOptions": {
    "encrypt": true,
    "previews": true,
    "enable_sharing": false,
    "filesystem_check_changes": 1,
    "encoding_compatibility": false
  },
  "applicableUsers": [],
  "applicableGroups": [],
  "priority": 100
}
```

Response:
```
200 OK

{
  "id": 5,
  "mountPoint": "/PCS",
  "backend": "swift",
  "authMechanism": "openstack::openstack",
  "backendOptions": {
    "bucket": "nextcloud",
    "password": "**REDACTED**",
    "region": "GRA3",
    "service_name": "OVH PCS",
    "tenant": "**REDACTED**",
    "timeout": "300",
    "url": "https://auth.cloud.ovh.net/v2.0",
    "user": "**REDACTED**"
  },
  "priority": 100,
  "mountOptions": {
    "encrypt": true,
    "previews": true,
    "enable_sharing": false,
    "filesystem_check_changes": 1,
    "encoding_compatibility": false
  },
  "status": 1,
  "userProvided": false,
  "type": "system"
}
```
</details>

**Comment by MorrisJobke** [comment]
See the last comments of https://github.com/nextcloud/server/issues/5882 for some tips. I will close this here for now.
