### ISSUE TITLE
NC13 Unable to save personal information

### ISSUE THREAD

**Issue by akrantz01** [nextcloud/server#9639]
### Steps to reproduce
1. Type anything into Full Name, Email, Phone number, Address, Website, or Twitter fields on personal info page
2. Wait for it to save
3. Look at JavaScript console

### Expected behaviour
Enter email, display name, phone number, address, webiste, or twitter and have it be saved.

### Actual behaviour
Nothing gets saved

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** nginx 1.10.3

**Database:** mysql 5.7.22

**PHP version:** 7.0.3

**Nextcloud version:** 13

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Nextcloud archive file

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.alexkrantz.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/files.alexkrantz.com",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Google Chrome 66.0.3359.181

**Operating system:** Ubuntu 17.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2018/05/28 11:18:07 [notice] 25441#25441: signal process started
2018/05/28 11:30:19 [notice] 25635#25635: signal process started
2018/05/28 11:30:28 [error] 25639#25639: *248151 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 136
PHP message: {"reqId":"VFP8n774Zw4cL9Ro8M1u","level":3,"time":"2018-05-28T18:30:28+00:00","remoteAddr":"172.68.141.106","user":"--","app":"PHP","method":"GET","url":"\/","message":"touch(): Unable to create file \/var\/www\/nextcloud\/config\/config.php because Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#240","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":""}
PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 136
PHP message: {"reqId":"VFP8n774Zw4cL9Ro8M1u","level":3,"time":"2018-05-28T18:30:28+00:00","remoteAddr":"172.68.141.106","user":"--","app":"PHP","method":"GET","url":"\/","message":"fopen(\/var\/www\/nextcloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Config.php#241","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":""}
PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 136
PHP message: {"reqId":"VFP8n774Zw4cL9Ro8M1u","level":3,"time":"2018-05-28T18:30:28+00:00","remoteAddr":"172.68.141.106","user":"--","app":"PHP","method":"GET","url":"\/","message":"chmod(): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Config.php#244","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":""}
PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 136
PHP
2018/05/28 11:30:28 [error] 25639#25639: *248151 FastCGI sent in stderr: "1u","level":3,"time":"2018-05-28T18:30:28+00:00","remoteAddr":"172.68.141.106","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occured in driver: could not find driver\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(992): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(623): OC\\\\DB\\\\Connection->executeUpdate('PRAGMA read_unc...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(151): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#4 \\\/var\\\/ww" while reading response header from upstream, client: 172.68.141.106, server: files.alexkrantz.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "files.alexkrantz.com"
2018/05/28 11:30:28 [error] 25639#25639: *248151 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 136
PHP message: {"reqId":"VFP8n774Zw4cL9Ro8M1u","level":3,"time":"2018-05-28T18:30:28+00:00","remoteAddr":"172.68.141.106","user":"--","app":"PHP","method":"GET","url":"\/","message":"fileperms(): stat failed for \/var\/www\/nextcloud\/data\/nextcloud.log at \/var\/www\/nextcloud\/lib\/private\/Log\/File.php#136","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":""}
PHP message: {"reqId":"VFP8n774Zw4cL9Ro8M1u","level":3,"time":"2018-05-28T18:30:28+00:00","remoteAddr":"172.68.141.106","user":"--","app":"PHP","method":"GET","url":"\/","message":"chmod(): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Log\/File.php#137","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":""}" while reading upstream, client: 172.68.141.106, server: files.alexkrantz.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "files.alexkrantz.com"
2018/05/28 11:38:10 [notice] 28677#28677: signal process started
2018/05/28 11:38:28 [notice] 29109#29109: signal process started
2018/05/28 11:55:04 [emerg] 8404#8404: invalid number of arguments in "ssl_certificate" directive in /etc/nginx/sites-enabled/nextcloud:20
2018/05/28 12:06:50 [emerg] 8581#8581: invalid number of arguments in "ssl_certificate" directive in /etc/nginx/sites-enabled/nextcloud:20
2018/05/28 12:08:33 [notice] 8639#8639: signal process started
2018/05/28 12:20:46 [notice] 8734#8734: signal process started
2018/05/28 12:20:51 [notice] 8736#8736: signal process started
2018/05/28 13:32:04 [notice] 12077#12077: signal process started
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(Nothing)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Refused to load the script 'https://files.alexkrantz.com/cdn-cgi/apps/head/iJuEvXevugi3p3h_pBQ2063loxI.js' because it violates the following Content Security Policy directive: "script-src 'nonce-K0gvcDdkTXB4Y3piOXpUQWF6bkNIMUI5enU5eVlNNllzdmp5UjNrV0lvOD06dkRXejFiWnVqb3VRejNIM0gwT3ZUVFFadjRnMUxZbit5OHk4TFV4bEcrbz0=' 'unsafe-eval'".
22
core.js?v=39830eaf-0:7 JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://files.alexkrantz.com/core/vendor/purify.min.js.map
DevTools failed to parse SourceMap: https://files.alexkrantz.com/settings/zxcvbn.js.map
merged-template-prep…s?v=39830eaf-0:3969 TypeError: Cannot read property 'replace' of undefined
    at Object._build (merged-template-prep…s?v=39830eaf-0:3962)
    at Object.init (merged-template-prep…s?v=39830eaf-0:3955)
    at a.fn.init.$.fn.octemplate (merged-template-prep…s?v=39830eaf-0:3981)
    at Object.<anonymous> (merged-template-prep…js?v=39830eaf-0:356)
    at Object.<anonymous> (core.js?v=39830eaf-0:2)
    at j (core.js?v=39830eaf-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=39830eaf-0:2)
    at Object.e.(anonymous function) [as resolve] (https://files.alexkrantz.com/core/vendor/core.js?v=39830eaf-0:2:28718)
    at Object.success (merged-template-prep…s?v=39830eaf-0:1025)
    at j (core.js?v=39830eaf-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=39830eaf-0:2)
    at x (core.js?v=39830eaf-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=39830eaf-0:4) "data:" undefined
merged-template-prep…s?v=39830eaf-0:3969 TypeError: Cannot read property 'replace' of undefined
    at Object._build (merged-template-prep…s?v=39830eaf-0:3962)
    at Object.init (merged-template-prep…s?v=39830eaf-0:3955)
    at a.fn.init.$.fn.octemplate (merged-template-prep…s?v=39830eaf-0:3981)
    at Object.<anonymous> (merged-template-prep…js?v=39830eaf-0:356)
    at Object.<anonymous> (core.js?v=39830eaf-0:2)
    at j (core.js?v=39830eaf-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=39830eaf-0:2)
    at Object.e.(anonymous function) [as resolve] (https://files.alexkrantz.com/core/vendor/core.js?v=39830eaf-0:2:28718)
    at Object.success (merged-template-prep…s?v=39830eaf-0:1025)
    at j (core.js?v=39830eaf-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=39830eaf-0:2)
    at x (core.js?v=39830eaf-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=39830eaf-0:4) "data:" undefined
```
</details>

**Comment by akrantz01** [comment]
Nevermind. Fixed by logging out and logging back in.
