### ISSUE TITLE
Replacing non-existent avatar object results in no-action

### ISSUE THREAD

**Issue by vpecinka** [nextcloud/server#9764]
Running NC 13.0.1.1 with Swift as primary store.

When you try to change avatar for your account in the settings, and there is no object file in the object storage (just a record for it in the oc_filecache), nothing happens and there is silent error (in the log). I suggest in such case (404 Not found in the storage) do not bother and simply ignore it and replace/upload new object.

the log file contains this and no new avatar is uploaded:

```
Could not delete object id:21329567 for appdata_ocdn3mtk0j94/avatar/775DA7E6-9157-48EE-92AD-DE87D45E22F1/generated: {"Exception":"Guzzle\\Http\\Exception\\ClientErrorResponseException","Message":"Client error response\n[status code] 404\n[reason phrase] Not Found\n[url] http:\/\/swift-proxy\/v1\/AUTH_s_64\/nc_0\/id:21329567","Code":0,"Trace":"#0 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Message\/Request.php(145): Guzzle\\Http\\Exception\\BadResponseException::factory(Object(Guzzle\\Http\\Message\\EntityEnclosingRequest), Object(Guzzle\\Http\\Message\\Response))\n#1 [internal function]: Guzzle\\Http\\Message\\Request::onRequestError(Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#2 \/www\/nextcloud\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php(212): call_user_func(Array, Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#3 \/www\/nextcloud\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\Common\\Event))\n#4 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Message\/Request.php(589): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('request.error', Object(Guzzle\\Common\\Event))\n#5 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Message\/Request.php(378): Guzzle\\Http\\Message\\Request->processResponse(Array)\n#6 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Message\/EntityEnclosingRequest.php(49): Guzzle\\Http\\Message\\Request->setState('complete', Array)\n#7 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(286): Guzzle\\Http\\Message\\EntityEnclosingRequest->setState('complete', Array)\n#8 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(244): Guzzle\\Http\\Curl\\CurlMulti->processResponse(Object(Guzzle\\Http\\Message\\EntityEnclosingRequest), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)\n#9 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(227): Guzzle\\Http\\Curl\\CurlMulti->processMessages()\n#10 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(211): Guzzle\\Http\\Curl\\CurlMulti->executeHandles()\n#11 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(105): Guzzle\\Http\\Curl\\CurlMulti->perform()\n#12 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMultiProxy.php(91): Guzzle\\Http\\Curl\\CurlMulti->send()\n#13 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Client.php(282): Guzzle\\Http\\Curl\\CurlMultiProxy->send()\n#14 \/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Message\/Request.php(198): Guzzle\\Http\\Client->send(Object(Guzzle\\Http\\Message\\EntityEnclosingRequest))\n#15 \/www\/nextcloud\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/ObjectStore\/Resource\/DataObject.php(384): Guzzle\\Http\\Message\\Request->send()\n#16 \/www\/nextcloud\/lib\/private\/Files\/ObjectStore\/Swift.php(311): OpenCloud\\ObjectStore\\Resource\\DataObject->delete()\n#17 \/www\/nextcloud\/lib\/private\/Files\/ObjectStore\/ObjectStoreStorage.php(191): OC\\Files\\ObjectStore\\Swift->deleteObject('id:21329567')\n#18 \/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(265): OC\\Files\\ObjectStore\\ObjectStoreStorage->unlink('appdata_ocdn3mt...')\n#19 \/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php(288): OC\\Files\\Storage\\Wrapper\\Wrapper->unlink('appdata_ocdn3mt...')\n#20 [internal function]: OC\\Files\\Storage\\Wrapper\\Availability->unlink('appdata_ocdn3mt...')\n#21 \/www\/nextcloud\/apps\/files_trashbin\/lib\/Storage.php(273): call_user_func_array(Array, Array)\n#22 \/www\/nextcloud\/apps\/files_trashbin\/lib\/Storage.php(182): OCA\\Files_Trashbin\\Storage->doDelete('appdata_ocdn3mt...', 'unlink')\n#23 \/www\/nextcloud\/lib\/private\/Files\/View.php(1148): OCA\\Files_Trashbin\\Storage->unlink('appdata_ocdn3mt...')\n#24 \/www\/nextcloud\/lib\/private\/Files\/View.php(710): OC\\Files\\View->basicOperation('unlink', '\/appdata_ocdn3m...', Array)\n#25 \/www\/nextcloud\/lib\/private\/Files\/Node\/File.php(116): OC\\Files\\View->unlink('\/appdata_ocdn3m...')\n#26 \/www\/nextcloud\/lib\/private\/Files\/SimpleFS\/SimpleFile.php(138): OC\\Files\\Node\\File->delete()\n#27 \/www\/nextcloud\/lib\/private\/Avatar.php(145): OC\\Files\\SimpleFS\\SimpleFile->delete()\n#28 \/www\/nextcloud\/core\/Controller\/AvatarController.php(329): OC\\Avatar->set('\\xFF\\xD8\\xFF\\xE0\\x00\\x10JFIF\\x00\\x01\\x01\\x01\\x00...')\n#29 [internal function]: OC\\Core\\Controller\\AvatarController->postCroppedAvatar(Array)\n#30 \/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161): call_user_func_array(Array, Array)\n#31 \/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Core\\Controller\\AvatarController), 'postCroppedAvat...')\n#32 \/www\/nextcloud\/lib\/private\/AppFramework\/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Core\\Controller\\AvatarController), 'postCroppedAvat...')\n#33 \/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OC\\\\Core\\\\Control...', 'postCroppedAvat...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#34 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#35 \/www\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#36 \/www\/nextcloud\/lib\/base.php(998): OC\\Route\\Router->match('\/avatar\/cropped')\n#37 \/www\/nextcloud\/index.php(37): OC::handleRequest()\n#38 {main}","File":"\/www\/nextcloud\/3rdparty\/guzzle\/guzzle\/src\/Guzzle\/Http\/Exception\/BadResponseException.php","Line":43}
```

**Comment by MorrisJobke** [comment]
> When you try to change avatar for your account in the settings, and there is no object file in the object storage (just a record for it in the oc_filecache), nothing happens and there is silent error (in the log).

Why is the file not there anymore? Usually this should not happen. To fix this run a `occ files:scan` and the filecache should be cleaned up properly then this error should not happen anymore.

**Comment by vpecinka** [comment]
Yes, it shouldn`t happen but happens. Maybe it is related to #9749 - sometimes Avatar are not generated, sometimes have different size in db and in the storage (1 or 0 bytes).

I'd like to point out, that this is NC cache, it uses Swift object storage (I think `occ files:scan` will not help because of not local filesystem?) and it is related to generated Avatars only.

**Comment by vpecinka** [comment]
I thik it is broken more than this, because for instance this should not happen as well (one R/W database):

```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`size`,`mtime`,`storage_mtime`,`permissions`,`etag`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["1", "2", 0, 1530602462, 1530602462, 31, "5b3b23dea11c8", "0f1903cfd791f8fb41dea5e91f3b4b6d", "appdata_ocdn3mtk0j94\/dav-photocache\/3cb13585e17d0368af81fab584ea6841", 21329958, "3cb13585e17d0368af81fab584ea6841", 1, 1, "0f1903cfd791f8fb41dea5e91f3b4b6d"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-0f1903cfd791f8fb41dea5e91f3b4b6d' for key 'fs_storage_path_hash'


/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1015: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)
/www/nextcloud/lib/private/DB/Connection.php - line 216: Doctrine\DBAL\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)
/www/nextcloud/lib/private/DB/Adapter.php - line 114: OC\DB\Connection->executeUpdate('INSERT INTO `oc...', Array)
/www/nextcloud/lib/private/DB/Connection.php - line 254: OC\DB\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)
/www/nextcloud/lib/private/Files/Cache/Cache.php - line 273: OC\DB\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)
/www/nextcloud/lib/private/Files/Cache/Cache.php - line 230: OC\Files\Cache\Cache->insert('appdata_ocdn3mt...', Array)
/www/nextcloud/lib/private/Files/ObjectStore/ObjectStoreStorage.php - line 111: OC\Files\Cache\Cache->put('appdata_ocdn3mt...', Array)
/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 81: OC\Files\ObjectStore\ObjectStoreStorage->mkdir('appdata_ocdn3mt...')
/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 87: OC\Files\Storage\Wrapper\Wrapper->mkdir('appdata_ocdn3mt...')
/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 81: OC\Files\Storage\Wrapper\Availability->mkdir('appdata_ocdn3mt...')
/www/nextcloud/lib/private/Files/View.php - line 1148: OC\Files\Storage\Wrapper\Wrapper->mkdir('appdata_ocdn3mt...')
/www/nextcloud/lib/private/Files/View.php - line 267: OC\Files\View->basicOperation('mkdir', '/appdata_ocdn3m...', Array)
/www/nextcloud/lib/private/Files/Node/Folder.php - line 160: OC\Files\View->mkdir('/appdata_ocdn3m...')
/www/nextcloud/lib/private/Files/AppData/AppData.php - line 112: OC\Files\Node\Folder->newFolder('3cb13585e17d036...')
/www/nextcloud/apps/dav/lib/CardDAV/PhotoCache.php - line 166: OC\Files\AppData\AppData->newFolder('3cb13585e17d036...')
/www/nextcloud/apps/dav/lib/CardDAV/PhotoCache.php - line 264: OCA\DAV\CardDAV\PhotoCache->getFolder('1', 'LDAP 23131293-9...')
/www/nextcloud/apps/dav/lib/AppInfo/Application.php - line 143: OCA\DAV\CardDAV\PhotoCache->delete('1', 'LDAP 23131293-9...')
[internal function] OCA\DAV\AppInfo\Application->OCA\DAV\AppInfo\{closure}(*** sensitive parameters replaced ***)
/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 212: call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 44: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\GenericEvent))
/www/nextcloud/apps/dav/lib/CardDAV/CardDavBackend.php - line 683: Symfony\Component\EventDispatcher\EventDispatcher->dispatch('\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\GenericEvent))
/www/nextcloud/apps/dav/lib/CardDAV/SyncService.php - line 285: OCA\DAV\CardDAV\CardDavBackend->updateCard('1', 'LDAP 23131293-9...', 'BEGIN VCARD\r\nVE...')
/www/nextcloud/apps/dav/lib/HookManager.php - line 124: OCA\DAV\CardDAV\SyncService->updateUser(Object(OC\User\User))
/www/nextcloud/lib/private/legacy/hook.php - line 106: OCA\DAV\HookManager->changeUser(Array)
/www/nextcloud/lib/private/Server.php - line 409: OC_Hook emit('OC_User', 'changeUser', Array)
[internal function] OC\Server->OC\{closure}(*** sensitive parameters replaced ***)
/www/nextcloud/lib/private/Hooks/EmitterTrait.php - line 99: call_user_func_array(Object(Closure), Array)
/www/nextcloud/lib/private/Hooks/PublicEmitter.php - line 36: OC\Hooks\BasicEmitter->emit('\\OC\\User', 'changeUser', Array)
/www/nextcloud/lib/private/User/User.php - line 456: OC\Hooks\PublicEmitter->emit('\\OC\\User', 'changeUser', Array)
/www/nextcloud/lib/private/Avatar.php - line 166: OC\User\User->triggerChange('avatar', '')
/www/nextcloud/lib/private/Avatar.php - line 138: OC\Avatar->remove()
/www/nextcloud/apps/user_ldap/lib/User/User.php - line 596: OC\Avatar->set('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01\x00...')
/www/nextcloud/apps/user_ldap/lib/User/User.php - line 571: OCA\User_LDAP\User\User->setOwnCloudAvatar()
/www/nextcloud/apps/user_ldap/lib/User/User.php - line 553: OCA\User_LDAP\User\User->updateAvatar()
/www/nextcloud/lib/private/legacy/hook.php - line 106: OCA\User_LDAP\User\User->updateAvatarPostLogin(Array)
/www/nextcloud/lib/private/Server.php - line 398: OC_Hook emit('OC_User', 'post_login', Array)
[internal function] OC\Server->OC\{closure}(*** sensitive parameters replaced ***)
/www/nextcloud/lib/private/Hooks/EmitterTrait.php - line 99: call_user_func_array(Object(Closure), Array)
/www/nextcloud/lib/private/Hooks/PublicEmitter.php - line 36: OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postLogin', Array)
/www/nextcloud/lib/private/User/Session.php - line 368: OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postLogin', Array)
/www/nextcloud/lib/private/User/Session.php - line 605: OC\User\Session->completeLogin(*** sensitive parameters replaced ***)
/www/nextcloud/lib/private/User/Session.php - line 333: OC\User\Session->loginWithToken(*** sensitive parameters replaced ***)
/www/nextcloud/lib/private/User/Session.php - line 411: OC\User\Session->login(*** sensitive parameters replaced ***)
/www/nextcloud/lib/private/User/Session.php - line 525: OC\User\Session->logClientIn(*** sensitive parameters replaced ***)
/www/nextcloud/lib/base.php - line 1053: OC\User\Session->tryBasicAuthLogin(Object(OC\AppFramework\Http\Request), Object(OC\Security\Bruteforce\Throttler))
/www/nextcloud/lib/base.php - line 988: OC handleLogin(Object(OC\AppFramework\Http\Request))
/www/nextcloud/index.php - line 42: OC handleRequest()
{main}
```

**Comment by MorrisJobke** [comment]
> I'd like to point out, that this is NC cache, it uses Swift object storage (I think occ files:scan will not help because of not local filesystem?) and it is related to generated Avatars only.

Even if the table is named "filecache" it actually is the index. The files:scan also scan all storages not only local ones.

> Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`size`,`mtime`,`storage_mtime`,`permissions`,`etag`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["1", "2", 0, 1530602462, 1530602462, 31, "5b3b23dea11c8", "0f1903cfd791f8fb41dea5e91f3b4b6d", "appdata_ocdn3mtk0j94\/dav-photocache\/3cb13585e17d0368af81fab584ea6841", 21329958, "3cb13585e17d0368af81fab584ea6841", 1, 1, "0f1903cfd791f8fb41dea5e91f3b4b6d"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-0f1903cfd791f8fb41dea5e91f3b4b6d' for key 'fs_storage_path_hash'

This is a completely different issue - see #6160 

How did you manage to get there. We tried locally and it works here just fine. Do you mean the default avatars or avatars uploaded by users?

**Comment by vpecinka** [comment]
To be honest I don`t know what is doing this, sometimes I can see this in my log file. First I suspected our large Swift deployment  - there can be delays until some object is available on another swift proxy.

But the NC should always check database for existence of the object (it can relay on anonymous object id) so this delays cannot mislead NC to think there is no such object and trying to create it...

**Comment by vpecinka** [comment]
You right that this is weird. But the issue with avatar file, or the photo cache both are internal objects created by NC, not user objects (files). I suspect that Swift implementation (filesystem abstraction) is broken in this case. I mean that database entries are created, not the respective objects. 

Feel free to close this issue, I'll try to play with PHP code and debug it, because I understand it can be hard to replicate this issue. If found something, I reopen or create new issue or proposal. Thanks.

**Comment by MorrisJobke** [comment]
> You right that this is weird. But the issue with avatar file, or the photo cache both are internal objects created by NC, not user objects (files). I suspect that Swift implementation (filesystem abstraction) is broken in this case. I mean that database entries are created, not the respective objects.

We use exactly the same code for user files as for NC files. So it's unlikely that one part work and another one not. For example the UI is not broken for you, right? Those files are stored with the exact same mechanism as avatars and are served in the same way. So that is what makes this feel weird. :/



> Feel free to close this issue, I'll try to play with PHP code and debug it, because I understand it can be hard to replicate this issue. If found something, I reopen or create new issue or proposal. Thanks.

Thank you a lot. We are happy to work together with you on this once we know more about the exact steps to reproduce this. And thanks for your debugging help.
